/*
created : 12/12/2016 jxc517/nxk CCN Project Team....
          Below rename the order date to arrival_date and add order date
*/


ALTER TABLE BANK_DEP_BAG_TICKORD RENAME COLUMN ORDER_DATE to ARRIVAL_DATE;
ALTER TABLE BANK_DEP_BAG_TICKORD ADD ORDER_DATE DATE;
  
ALTER TABLE BANK_DEP_BAG_TICKORD_FUTURE RENAME COLUMN ORDER_DATE to ARRIVAL_DATE;
ALTER TABLE BANK_DEP_BAG_TICKORD_FUTURE ADD ORDER_DATE DATE;

ALTER TABLE BANK_DEP_BAG_TICKORD_HIST RENAME COLUMN ORDER_DATE to ARRIVAL_DATE;
ALTER TABLE BANK_DEP_BAG_TICKORD_HIST ADD ORDER_DATE DATE;


ALTER TABLE BANK_DEP_TICKORD RENAME COLUMN ORDER_DATE to ARRIVAL_DATE;
ALTER TABLE BANK_DEP_TICKORD ADD ORDER_DATE DATE;

ALTER TABLE BANK_DEP_TICKORD_FUTURE RENAME COLUMN ORDER_DATE to ARRIVAL_DATE;
ALTER TABLE BANK_DEP_TICKORD_FUTURE ADD ORDER_DATE DATE;

ALTER TABLE BANK_DEP_TICKORD_HIST RENAME COLUMN ORDER_DATE to ARRIVAL_DATE;
ALTER TABLE BANK_DEP_TICKORD_HIST ADD ORDER_DATE DATE;