CREATE TABLE ACH_DRFTS_EXTRCT_CNTRL_FL_PREV 
   (	COST_CENTER_CODE VARCHAR2(4), 
	CENTURY VARCHAR2(1), 
	YEAR VARCHAR2(2), 
	MONTH VARCHAR2(2), 
	DAY VARCHAR2(2), 
	BANK_DEP_AMT VARCHAR2(10), 
	BANK_ACCOUNT_NBR VARCHAR2(17), 
	BANK_AUTO_REC_IND VARCHAR2(1)
   );
   /