/*
Created : nxk927 03/21/2017
          adding new columns ORIGINATED_BANK_ACCNT_NBR.
		  Renaming SOURCE_BANK_ACCOUNT to ORIGINATED_BANK_ACCNT_NBR
*/


ALTER TABLE ACH_DRFTS_EXT_CTRL ADD ORIGINATED_BANK_ACCNT_NBR VARCHAR2(17);
ALTER TABLE SUMMARY_EXTRCT_CNTRL_FL ADD ORIGINATED_BANK_ACCNT_NBR VARCHAR2(17);

ALTER TABLE MISCTRAN_DETAILS ADD ORIGINATED_BANK_ACCNT_NBR VARCHAR2(17);

ALTER TABLE MISCTRAN RENAME COLUMN SOURCE_BANK_ACCOUNT  TO ORIGINATED_BANK_ACCNT_NBR;
ALTER TABLE UAR_MISCTRAN RENAME COLUMN SOURCE_BANK_ACCOUNT  TO ORIGINATED_BANK_ACCNT_NBR;
ALTER TABLE OVERSHRT RENAME COLUMN SOURCE_BANK_ACCOUNT  TO ORIGINATED_BANK_ACCNT_NBR;
ALTER TABLE UAR_OVERSHRT RENAME COLUMN SOURCE_BANK_ACCOUNT  TO ORIGINATED_BANK_ACCNT_NBR;