ALTER TABLE BANK_ACCOUNT
  MODIFY BANK_ACCOUNT_NBR varchar2(20);
ALTER TABLE BANK_ACCOUNT_T
  MODIFY BANK_ACCOUNT_NBR varchar2(20);
ALTER TABLE BANK_ACCOUNT_FUTURE
  MODIFY BANK_ACCOUNT_NBR varchar2(20);
ALTER TABLE BANK_ACCOUNT_HIST
  MODIFY BANK_ACCOUNT_NBR varchar2(20);
  
ALTER TABLE BANK_DEP_BAG_TICK
  MODIFY BANK_ACCOUNT_NBR varchar2(20);
ALTER TABLE BANK_DEP_BAG_TICK_HIST
  MODIFY BANK_ACCOUNT_NBR varchar2(20);
  
ALTER TABLE BANK_DEP_TICK
  MODIFY BANK_ACCOUNT_NBR varchar2(20);
ALTER TABLE BANK_DEP_TICK_HIST
  MODIFY BANK_ACCOUNT_NBR varchar2(20);
ALTER TABLE BANK_DEP_TICK_T
  MODIFY BANK_ACCOUNT_NBR varchar2(20);
  
ALTER TABLE BANK_DEP_TICKORD
  MODIFY BANK_ACCOUNT_NBR varchar2(20);
ALTER TABLE BANK_DEP_TICKORD_HIST
  MODIFY BANK_ACCOUNT_NBR varchar2(20);
ALTER TABLE BANK_DEP_TICKORD_T
  MODIFY BANK_ACCOUNT_NBR varchar2(20);  

ALTER TABLE BANK_MICR_FORMAT
  MODIFY BANK_ACCOUNT_NBR varchar2(20);
ALTER TABLE BANK_MICR_FORMAT_T
  MODIFY BANK_ACCOUNT_NBR varchar2(20);
ALTER TABLE BANK_MICR_FORMAT_FUTURE
  MODIFY BANK_ACCOUNT_NBR varchar2(20);
ALTER TABLE BANK_MICR_FORMAT_HIST
  MODIFY BANK_ACCOUNT_NBR varchar2(20);
  
ALTER TABLE LEAD_BANK_CC
  MODIFY LEAD_BANK_ACCOUNT_NBR varchar2(20);
ALTER TABLE LEAD_BANK_CC_T
  MODIFY BANK_ACCOUNT_NBR varchar2(20);
ALTER TABLE LEAD_BANK_CC_HIST
  MODIFY LEAD_BANK_ACCOUNT_NBR varchar2(20);
ALTER TABLE LEAD_BANK_CC_FUTURE
  MODIFY LEAD_BANK_ACCOUNT_NBR varchar2(20); 
  
ALTER TABLE MEMBER_BANK_CC
  MODIFY MEMBER_BANK_ACCOUNT_NBR varchar2(20);
ALTER TABLE MEMBER_BANK_CC_T
  MODIFY BANK_ACCOUNT_NUMBER varchar2(20);
ALTER TABLE MEMBER_BANK_CC_HIST
  MODIFY MEMBER_BANK_ACCOUNT_NBR varchar2(20);
ALTER TABLE MEMBER_BANK_CC_FUTURE
  MODIFY MEMBER_BANK_ACCOUNT_NBR varchar2(20); 
  
ALTER TABLE ERROR_LOG
  MODIFY BANK_ACCOUNT_NBR varchar2(20);
ALTER TABLE JV_EXTRCT_CNTRL_FL_PREV
  MODIFY BANK_ACCOUNT_NBR varchar2(20);
  
ALTER TABLE STR_BNK_DPST_DLY_RCNCL_TBL
  MODIFY BANK_ACCOUNT_NBR varchar2(20);
ALTER TABLE SUMMARY_EXTRCT_CNTRL_FL_PREV
  MODIFY BANK_ACCOUNT_NBR varchar2(20); 
  