/*
Created : 06/08/2018 nxk927 
          Dropping bank_account_nbr constraint from all the bag tables
*/
ALTER TABLE BANK_DEP_BAG_TICK DROP CONSTRAINT BANK_DEP_BAG_TICK_FK;
ALTER TABLE BANK_DEP_BAG_TICKORD DROP CONSTRAINT BANK_DEP_BAG_TICKORD_FK;
ALTER TABLE BANK_DEP_BAG_TICKORD_FUTURE DROP CONSTRAINT BANK_DEP_BAG_TICKORD_FUTURE_FK;
ALTER TABLE BANK_DEP_BAG_TICK_FUTURE DROP CONSTRAINT BANK_DEP_BAG_TICK_FUTURE_FK;
