ALTER TABLE BANK_DEP_TICK
DROP CONSTRAINT BANK_DEP_TICK_PK;

ALTER TABLE BANK_DEP_TICK
ADD CONSTRAINT BANK_DEP_TICK_PK PRIMARY KEY (BANK_ACCOUNT_NBR, COST_CENTER_CODE);

ALTER TABLE BANK_DEP_BAG_TICK
DROP CONSTRAINT BANK_DEP_BAG_TICK_PK;

ALTER TABLE BANK_DEP_BAG_TICK
ADD CONSTRAINT BANK_DEP_BAG_TICK_PK PRIMARY KEY (BANK_ACCOUNT_NBR, COST_CENTER_CODE);

ALTER TABLE BANK_DEP_TICK_FUTURE
DROP CONSTRAINT BANK_DEP_TICK_FUTURE_PK;

ALTER TABLE BANK_DEP_TICK_FUTURE
ADD CONSTRAINT BANK_DEP_TICK_FUTURE_PK PRIMARY KEY (BANK_ACCOUNT_NBR, COST_CENTER_CODE, FUTURE_ID);

ALTER TABLE BANK_DEP_BAG_TICK_FUTURE
DROP CONSTRAINT BANK_DEP_BAG_TICK_FUTURE_PK;

ALTER TABLE BANK_DEP_BAG_TICK_FUTURE
ADD CONSTRAINT BANK_DEP_BAG_TICK_FUTURE_PK PRIMARY KEY (BANK_ACCOUNT_NBR, COST_CENTER_CODE, FUTURE_ID);

ALTER TABLE BANK_DEP_BAG_TICKORD
DROP CONSTRAINT BANK_DEP_BAG_TICKORD_PK;

ALTER TABLE BANK_DEP_BAG_TICKORD
ADD CONSTRAINT BANK_DEP_BAG_TICKORD_PK PRIMARY KEY (BANK_ACCOUNT_NBR, COST_CENTER_CODE, BANK_DEP_BAG_FTR_ID);

ALTER TABLE BANK_DEP_BAG_TICKORD_FUTURE
DROP CONSTRAINT BANK_DEP_BAG_TICKORD_FUTURE_PK;

ALTER TABLE BANK_DEP_BAG_TICKORD_FUTURE
ADD CONSTRAINT BANK_DEP_BAG_TICKORD_FUTURE_PK PRIMARY KEY (BANK_ACCOUNT_NBR, COST_CENTER_CODE,FUTURE_ID, BANK_DEP_BAG_FTR_ID);

ALTER TABLE BANK_DEP_TICKORD
DROP CONSTRAINT BANK_DEP_TICKORD_PK;

ALTER TABLE BANK_DEP_TICKORD
ADD CONSTRAINT BANK_DEP_TICKORD_PK PRIMARY KEY (BANK_ACCOUNT_NBR, COST_CENTER_CODE, BANK_DEP_TICK_FTR_ID);

ALTER TABLE BANK_DEP_TICKORD_FUTURE
DROP CONSTRAINT BANK_DEP_TICKORD_FUTURE_PK;

ALTER TABLE BANK_DEP_TICKORD_FUTURE
ADD CONSTRAINT BANK_DEP_TICKORD_FUTURE_PK PRIMARY KEY (BANK_ACCOUNT_NBR, COST_CENTER_CODE,FUTURE_ID, BANK_DEP_TICK_FTR_ID);


