
  CREATE TABLE AUDIT_LOG 
   (	LOG_ID NUMBER(12,0) NOT NULL ENABLE, 
	TRANSACTION_ID VARCHAR2(500) NOT NULL ENABLE, 
	TRANSACTION_DATE DATE, 
	TABLE_NAME VARCHAR2(32), 
	TABLE_ROW_DATA XMLTYPE, 
	CHANGE_BY VARCHAR2(32), 
	TABLE_PK_VALUE XMLTYPE, 
	AUDIT_REC_FLAG VARCHAR2(1), 
	AUDIT_REC_EFF_DATE DATE, 
	 CONSTRAINT AUDIT_LOG_PK PRIMARY KEY (LOG_ID, TRANSACTION_ID) ENABLE
   ) ;

   COMMENT ON COLUMN AUDIT_LOG.AUDIT_REC_FLAG IS 'flag to indicate that this was used as a audit record.Values ''Y'' yes or null (not used)';
   COMMENT ON COLUMN AUDIT_LOG.AUDIT_REC_EFF_DATE IS 'Date that the AUDIT_REC_FLAG was set.';

  CREATE INDEX TBLNM_AUDRECFLAG_IDX ON AUDIT_LOG (TABLE_NAME, AUDIT_REC_FLAG);

  CREATE INDEX TBLNM_TRNSCTNDT_INDX ON AUDIT_LOG (TABLE_NAME, TRANSACTION_DATE);

  CREATE INDEX TBLNM_TRNSCTNID_IDX ON AUDIT_LOG (TABLE_NAME, TRANSACTION_ID);

  CREATE INDEX TRNSCTNDT_INDX ON AUDIT_LOG (TRANSACTION_DATE);

