  CREATE TABLE BANK_PRCDIST 
   (PRICE_DIST_NBR VARCHAR2(5) NOT NULL ENABLE, 
	PRICE_DIST_NAME VARCHAR2(35), 
	EFFECTIVE_DATE DATE, 
	EXPIRATION_DATE DATE, 
	LAST_MAINT_AUTH_ID VARCHAR2(6), 
	 CONSTRAINT BANK_PRCDIST_PK PRIMARY KEY (PRICE_DIST_NBR)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE BANKING_DATA  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BANKING_DATA" ;
  
  /