  CREATE TABLE BANK_PRCCNTR_HIST 
   (PRICE_DIST_NBR VARCHAR2(5) NOT NULL ENABLE, 
	COST_CENTER_CODE VARCHAR2(6) NOT NULL ENABLE, 
	EFFECTIVE_DATE DATE NOT NULL ENABLE, 
	EXPIRATION_DATE DATE NOT NULL ENABLE, 
	LAST_MAINT_AUTH_ID VARCHAR2(6)
   ) ;
  /