  CREATE TABLE BANK_PRCCNTR_T 
   (	PRICE_DIST_NBR VARCHAR2(5), 
	COST_CENTER_CODE VARCHAR2(6), 
	EFFECTIVE_DATE VARCHAR2(8), 
	EXPIRATION_DATE VARCHAR2(8), 
	LAST_MAINT_AUTH_ID VARCHAR2(6)
   ) ;
  
  /