  CREATE TABLE BANK_DEP_TICKORD_DLY_T 
   (BANK_ACCOUNT_NBR VARCHAR2(16), 
	COST_CENTER_CODE VARCHAR2(6), 
	DEPOSIT_ORDER_PRIORITY VARCHAR2(3), 
	DEPOSIT_ORDER_STATUS VARCHAR2(1), 
	COST_CENTER VARCHAR2(4), 
	DEPOSIT_ORDER_SEQ_NBR VARCHAR2(3), 
	EFFECTIVE_DATE VARCHAR2(8), 
	EXPIRATION_DATE VARCHAR2(8), 
	LAST_MAINTENANCE_DATE VARCHAR2(8), 
	LAST_MAINT_USER_ID VARCHAR2(6), 
	ORDER_DATE VARCHAR2(8), 
	EXTRACTED_USER_ID VARCHAR2(8)
   ) ;
/