  CREATE TABLE BANK_DEP_TICKOAK 
   (	DEPOSIT_TICKET_OOAK VARCHAR2(8), 
	REORDER_POINT VARCHAR2(5), 
	REORDER_NUMBER_BKS VARCHAR2(5), 
	IMAGES_PER_PAGE VARCHAR2(1), 
	NBR_FORMS_PER_BK VARCHAR2(5), 
	PART_PAPER_PER_FORM VARCHAR2(1), 
	NBR_DEP_TICKETS_PER_BK VARCHAR2(5), 
	SHEETS_OF_PAPER_PER_BK VARCHAR2(5), 
	DEP_BAG_TYPE VARCHAR2(1), 
	DEP_BAG_REORDER_POINT VARCHAR2(5), 
	DEPBAG_REORDER_QTY VARCHAR2(5), 
	EFFECTIVE_DATE DATE, 
	EXPIRATION_DATE DATE, 
	LAST_MAINTENANCE_DATE DATE, 
	LAST_MAINT_USER_ID VARCHAR2(6)
   ); 
  /