/**********************************************************
Changed : 11/03/2015 jxc517 CCN Project....
          Modified table to change some VARCHAR2(*) fields to NUMBER
**********************************************************/
DROP TABLE BANK_DEP_BAG_TICK_HIST;
  CREATE TABLE BANK_DEP_BAG_TICK_HIST 
   (BANK_ACCOUNT_NBR VARCHAR2(16) NOT NULL ENABLE, 
	COST_CENTER_CODE VARCHAR2(6) NOT NULL ENABLE, 
	DEPBAG_DAILY_USE_ACTUAL NUMBER, 
	DEPBAG_DLY_USE_OVERRIDE NUMBER, 
	DEPBAG_LAST_ORDER_DATE DATE, 
	DEPBAG_LAST_ORDER_QTY NUMBER, 
	DEPBAG_ONHAND_QTY NUMBER, 
	DEPBAG_REORDER_QTY NUMBER, 
	DEPBAG_YTD_ORDERED_QTY NUMBER, 
	DEP_BAG_REORDER_POINT NUMBER, 
	DEP_BAG_TYPE VARCHAR2(1), 
	DEP_BAG_REORDER_SWITCH VARCHAR2(1), 
	EFFECTIVE_DATE DATE, 
	EXPIRATION_DATE DATE
   ) ; 
 
  
  /