SELECT * FROM BANK_ACCOUNT WHERE BOOK_KEEPER_NBR IS NULL;
UPDATE BANK_ACCOUNT SET BOOK_KEEPER_NBR = 0 WHERE BOOK_KEEPER_NBR IS NULL;
COMMIT;
ALTER TABLE BANK_ACCOUNT MODIFY BOOK_KEEPER_NBR VARCHAR2(2) NOT NULL;