  CREATE TABLE BANK_PRCCNTR_HIST 
   (PRICE_DIST_NBR VARCHAR2(5) NOT NULL ENABLE, 
	COST_CENTER_CODE VARCHAR2(6) NOT NULL ENABLE, 
	EFFECTIVE_DATE DATE NOT NULL ENABLE, 
	EXPIRATION_DATE DATE NOT NULL ENABLE, 
	LAST_MAINT_AUTH_ID VARCHAR2(6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BANKING_DATA"
  /