  CREATE TABLE BANK_PRCDIST 
   (PRICE_DIST_NBR VARCHAR2(5) NOT NULL ENABLE, 
	PRICE_DIST_NAME VARCHAR2(35), 
	EFFECTIVE_DATE DATE, 
	EXPIRATION_DATE DATE, 
	LAST_MAINT_AUTH_ID VARCHAR2(6), 
	 CONSTRAINT BANK_PRCDIST_PK PRIMARY KEY (PRICE_DIST_NBR)
   );
  
  /