CREATE TABLE BANK_ACCOUNT_FUTURE 
   (BANK_ACCOUNT_NBR VARCHAR2(16) NOT NULL ENABLE, 
	EFFECTIVE_DATE DATE, 
	EXPIRATION_DATE DATE, 
	BANK_NAME VARCHAR2(30), 
	BOOK_KEEPER_NBR VARCHAR2(2), 
	STATEMENT_TYPE VARCHAR2(2), 
	BANK_AUTO_RECON_IND VARCHAR2(1), 
	RECON_START_DATE DATE, 
	RECON_BANK_ACCOUNT_NBR VARCHAR2(16), 
	JV_BOOK_KEEPER_REF VARCHAR2(6), 
	JV_BANK_SHORT_NAME VARCHAR2(6), 
	IDI_BOOKKEEPER_REF VARCHAR2(6), 
	IDI_BANK_SHORT_NAME VARCHAR2(6), 
	ROUTING_NBR VARCHAR2(9), 
	FUTURE_ID NUMBER, 
	 CONSTRAINT BANK_ACCOUNT_FUTURE_PK PRIMARY KEY (FUTURE_ID, BANK_ACCOUNT_NBR)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE BANKING_DATA  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BANKING_DATA"; 
  
  /
  