/*
Created : nxk927 07/23/2018
          cleaning up all the unused components
*/
DROP TABLE BANK_DEP_BAG_TICKORD_HIST_B;
DROP TABLE BANK_DEP_TICKORD_HIST_B;
DROP TABLE FF_DPST_TCKT_POS_CNTS;
DROP TABLE FF_GIFT_CARD_POS_TRANS;
DROP TABLE FF_INTERIM_DEPST;
DROP TABLE MISCTRAN_DETAILS_BKP_VXV;
DROP TABLE TEMP_DPST_TCKT_POS_CNTS;
DROP TABLE TEMP_GIFT_CARD_POS_TRANS;
DROP TABLE TEMP_INTERIM_DEPST;
DROP PACKAGE BNK_RECONCILE_DIFF_REPORT_PKG;