/**********************************************************
Changed : 11/03/2015 jxc517 CCN Project....
          Modified table to change some VARCHAR2(*) fields to NUMBER
**********************************************************/
DROP TABLE BANK_DEP_TICK_HIST;
  CREATE TABLE BANK_DEP_TICK_HIST 
   (	BANK_ACCOUNT_NBR VARCHAR2(20) NOT NULL ENABLE,
	COST_CENTER_CODE VARCHAR2(6) NOT NULL ENABLE,
	DAILY_USE_ACTUAL NUMBER,
	DAILY_USE_OVERRIDE NUMBER,
	DEP_TKTS_ONHAND_QTY NUMBER,
	YTD_DEP_TKTS_ORDERED_QTY NUMBER,
	REORDER_POINT NUMBER,
	REORDER_NUMBER_BKS NUMBER,
	IMAGES_PER_PAGE NUMBER,
	NBR_FORMS_PER_BK NUMBER,
	PART_PAPER_PER_FORM NUMBER,
	NBR_DEP_TICKETS_PER_BK NUMBER,
	SHEETS_OF_PAPER_PER_BK NUMBER,
	EFFECTIVE_DATE DATE,
	EXPIRATION_DATE DATE,
	LAST_MAINTENANCE_DATE DATE,
	LAST_MAINT_USER_ID VARCHAR2(6),
	REORDER_SWITCH VARCHAR2(1),
	LAST_VW_ORDER_DATE DATE
   );
  /