/*******************************************************************************
  The table is used to hold the banking batchload run date configuration information 
  CREATED : 06/21/2016 MXK766 CCN PROJECT....
  CHANGED : 
*******************************************************************************/
CREATE TABLE BANKING_PARAM
(
DAILY_LOAD_RUNDATE      DATE,
TICKET_TRACKING_RUNDATE DATE,
BAG_TRACKING_RUNDATE    DATE
);