  CREATE TABLE BANK_DEP_TICKORD 
   (	BANK_ACCOUNT_NBR VARCHAR2(20) NOT NULL ENABLE,
	COST_CENTER_CODE VARCHAR2(6) NOT NULL ENABLE,
	DEPOSIT_ORDER_PRIORITY VARCHAR2(3),
	DEPOSIT_ORDER_STATUS VARCHAR2(1),
	DEPOSIT_ORDER_SEQ_NBR VARCHAR2(3),
	EFFECTIVE_DATE DATE NOT NULL ENABLE,
	EXPIRATION_DATE DATE,
	LAST_MAINTENANCE_DATE DATE NOT NULL ENABLE,
	LAST_MAINT_USER_ID VARCHAR2(6) NOT NULL ENABLE,
	EXTRACT_DATE DATE,
	EXTRACTED_USER_ID VARCHAR2(8),
	CONSTRAINT BANK_DEP_TICKORD_PK PRIMARY KEY (COST_CENTER_CODE) ENABLE,
	CONSTRAINT BANK_DEP_TICKORD_FK FOREIGN KEY (BANK_ACCOUNT_NBR)
	 REFERENCES BANKING.BANK_ACCOUNT (BANK_ACCOUNT_NBR) ENABLE
   );


/