/**********************************************************
Changed : 11/03/2015 jxc517 CCN Project....
          Modified table to change some VARCHAR2(*) fields to NUMBER
**********************************************************/
DROP TABLE BANK_DEP_TICK;
  CREATE TABLE BANK_DEP_TICK 
   (	BANK_ACCOUNT_NBR VARCHAR2(16) NOT NULL ENABLE,
	COST_CENTER_CODE VARCHAR2(6) NOT NULL ENABLE,
	DAILY_USE_ACTUAL NUMBER,
	DAILY_USE_OVERRIDE NUMBER,
	DEP_TKTS_ONHAND_QTY NUMBER,
	YTD_DEP_TKTS_ORDERED_QTY NUMBER,
	REORDER_POINT NUMBER,
	REORDER_NUMBER_BKS NUMBER,
	IMAGES_PER_PAGE NUMBER,
	NBR_FORMS_PER_BK NUMBER,
	PART_PAPER_PER_FORM NUMBER,
	NBR_DEP_TICKETS_PER_BK NUMBER,
	SHEETS_OF_PAPER_PER_BK NUMBER,
	EFFECTIVE_DATE DATE NOT NULL ENABLE,
	EXPIRATION_DATE DATE,
	LAST_MAINTENANCE_DATE DATE NOT NULL ENABLE,
	LAST_MAINT_USER_ID VARCHAR2(6) NOT NULL ENABLE,
	REORDER_SWITCH VARCHAR2(1),
	LAST_VW_ORDER_DATE DATE,
	CONSTRAINT BANK_DEP_TICK_PK PRIMARY KEY (COST_CENTER_CODE) ENABLE,
	CONSTRAINT BANK_DEP_TICK_FK1 FOREIGN KEY (BANK_ACCOUNT_NBR)
	 REFERENCES BANKING.BANK_ACCOUNT (BANK_ACCOUNT_NBR) ENABLE
   );

/