  CREATE TABLE BANK_DEP_TICK_T 
   (BANK_ACCOUNT_NBR VARCHAR2(16), 
	COST_CENTER_CODE VARCHAR2(6), 
	DAILY_USE_ACTUAL VARCHAR2(3), 
	DAILY_USE_OVERRIDE VARCHAR2(3), 
	DEP_TKTS_ONHAND_QTY VARCHAR2(5), 
	YTD_DEP_TKTS_ORDERED_QTY VARCHAR2(5), 
	DJDE_FORM_PARM VARCHAR2(6), 
	DJDE_FEED_PARM VARCHAR2(5), 
	MICR_COST_CNTR VARCHAR2(8), 
	MICR_ROUTING_NBR VARCHAR2(11), 
	MICR_FORMAT_ACCT_NBR VARCHAR2(17), 
	REORDER_POINT VARCHAR2(5), 
	REORDER_NUMBER_BKS VARCHAR2(5), 
	IMAGES_PER_PAGE VARCHAR2(1), 
	NBR_FORMS_PER_BK VARCHAR2(5), 
	PART_PAPER_PER_FORM VARCHAR2(1), 
	NBR_DEP_TICKETS_PER_BK VARCHAR2(5), 
	SHEETS_OF_PAPER_PER_BK VARCHAR2(5), 
	FORMAT_NAME VARCHAR2(6), 
	DEPBAG_DAILY_USE_ACTUAL VARCHAR2(5), 
	DEPBAG_DLY_USE_OVERRIDE VARCHAR2(5), 
	DEPBAG_ONHAND_QTY VARCHAR2(5), 
	DEPBAG_YTD_ORDERED_QTY VARCHAR2(5), 
	DEPBAG_LAST_ORDER_DATE VARCHAR2(8), 
	DEPBAG_LAST_ORDER_QTY VARCHAR2(5), 
	DEP_BAG_TYPE VARCHAR2(1), 
	DEP_BAG_REORDER_POINT VARCHAR2(5), 
	DEPBAG_REORDER_QTY VARCHAR2(5), 
	EFFECTIVE_DATE VARCHAR2(8), 
	EXPIRATION_DATE VARCHAR2(8), 
	LAST_MAINTENANCE_DATE VARCHAR2(8), 
	LAST_MAINT_USER_ID VARCHAR2(6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BANKING_DATA"; 
  /