  CREATE TABLE BANK_PRCCNTR 
   (PRICE_DIST_NBR VARCHAR2(5) NOT NULL ENABLE, 
	COST_CENTER_CODE VARCHAR2(6) NOT NULL ENABLE, 
	EFFECTIVE_DATE DATE NOT NULL ENABLE, 
	EXPIRATION_DATE DATE, 
	LAST_MAINT_AUTH_ID VARCHAR2(6), 
	 CONSTRAINT BANK_PRCCNTR_PK PRIMARY KEY (PRICE_DIST_NBR, COST_CENTER_CODE, EFFECTIVE_DATE)  ENABLE, 
	 CONSTRAINT BANK_PRCCNTR_FK1 FOREIGN KEY (PRICE_DIST_NBR)
	  REFERENCES BANKING.BANK_PRCDIST (PRICE_DIST_NBR) ENABLE
   ) ;
  /
  