  CREATE TABLE BANK_DEP_BAG_TICKORD_FUTURE
   (	BANK_ACCOUNT_NBR           VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	COST_CENTER_CODE           VARCHAR2(6 BYTE) NOT NULL ENABLE, 
	DEPOSIT_BAG_ORDER_PRIORITY VARCHAR2(3 BYTE), 
	DEPOSIT_BAG_ORDER_STATUS   VARCHAR2(1 BYTE), 
	DEPOSIT_BAG_ORDER_SEQ_NBR  VARCHAR2(3 BYTE), 
	EFFECTIVE_DATE             DATE NOT NULL ENABLE, 
	EXPIRATION_DATE            DATE, 
	LAST_MAINTENANCE_DATE      DATE NOT NULL ENABLE, 
	LAST_MAINT_USER_ID         VARCHAR2(6 BYTE) NOT NULL ENABLE, 
	ORDER_DATE                 DATE,
	EXTRACTED_USER_ID          VARCHAR2(8 BYTE),
	FUTURE_ID                  NUMBER NOT NULL ENABLE,
	CONSTRAINT BANK_DEP_BAG_TICKORD_FUTURE_PK PRIMARY KEY (COST_CENTER_CODE, FUTURE_ID),
	CONSTRAINT BANK_DEP_BAG_TICKORD_FUTURE_FK FOREIGN KEY (BANK_ACCOUNT_NBR, FUTURE_ID) REFERENCES BANK_ACCOUNT_FUTURE (BANK_ACCOUNT_NBR, FUTURE_ID) ENABLE
   );