/**********************************************************
Changed : 11/03/2015 jxc517 CCN Project....
          Modified table to change some VARCHAR2(*) fields to NUMBER
**********************************************************/
DROP TABLE BANK_DEP_TICKOAK;
  CREATE TABLE BANK_DEP_TICKOAK 
   (	DEPOSIT_TICKET_OOAK VARCHAR2(8), 
	REORDER_POINT NUMBER, 
	REORDER_NUMBER_BKS NUMBER, 
	IMAGES_PER_PAGE NUMBER, 
	NBR_FORMS_PER_BK NUMBER, 
	PART_PAPER_PER_FORM NUMBER, 
	NBR_DEP_TICKETS_PER_BK NUMBER, 
	SHEETS_OF_PAPER_PER_BK NUMBER, 
	DEP_BAG_TYPE VARCHAR2(1), 
	DEP_BAG_REORDER_POINT NUMBER, 
	DEPBAG_REORDER_QTY NUMBER, 
	EFFECTIVE_DATE DATE, 
	EXPIRATION_DATE DATE, 
	LAST_MAINTENANCE_DATE DATE, 
	LAST_MAINT_USER_ID VARCHAR2(6)
   ); 
  /