/*
Created : dxv848 11/21/2015 create CODE_DETAIL table.
*/

CREATE TABLE CODE_DETAIL 
(
  CODE_HEADER_NAME VARCHAR2(30) NOT NULL 
, CODE_HEADER_TYPE VARCHAR2(3) NOT NULL 
, CODE_DETAIL_VALUE VARCHAR2(32) NOT NULL 
, CODE_DETAIL_DESCRIPTION VARCHAR2(100) 
, CODE_DETAIL_EXPIRE_FLAG CHAR(1) 
, CODE_DETAIL_EXPIRE_USER VARCHAR2(20) 
, CODE_DETAIL_EXPIRE_EFF_DATE DATE 
, CODE_DETAIL_ID NUMBER(*,3) 
, CODE_DETAIL_CREATE_USER VARCHAR2(25) 
, CODE_DETAIL_EFF_DATE DATE 
, CONSTRAINT CODE_DETAIL_PK PRIMARY KEY(CODE_HEADER_NAME,CODE_HEADER_TYPE,CODE_DETAIL_VALUE)
, CONSTRAINT CODE_HEADER_CODE_DETAIL foreign key(CODE_HEADER_NAME,CODE_HEADER_TYPE) references CODE_HEADER(CODE_HEADER_NAME,CODE_HEADER_TYPE);
);

