  CREATE TABLE ERROR_LOG 
   (ERROR_ID NUMBER NOT NULL ENABLE, 
	BANK_ACCOUNT_NBR VARCHAR2(16) NOT NULL ENABLE, 
	ERROR_DATE DATE NOT NULL ENABLE, 
	"MODULE" VARCHAR2(65) NOT NULL ENABLE, 
	ERROR_TEXT VARCHAR2(500), 
	NOTES VARCHAR2(200), 
	ERROR_CODE VARCHAR2(9), 
	COST_CENTER_CODE VARCHAR2(6), 
	TABLE_NAME VARCHAR2(30), 
	 CONSTRAINT ERROR_LOG_PK PRIMARY KEY (ERROR_ID, BANK_ACCOUNT_NBR, ERROR_DATE, MODULE)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE BANKING_DATA  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BANKING_DATA" ;
  
  /