CREATE TABLE JV_EXTRCT_CNTRL_FL_PREV 
(	BANK_ACCOUNT_NBR VARCHAR2(17 BYTE), 
	COST_CENTER_CODE VARCHAR2(4 BYTE), 
	CENTURY VARCHAR2(1 BYTE), 
	"YEAR" VARCHAR2(2 BYTE), 
	"MONTH" VARCHAR2(2 BYTE), 
	"DAY" VARCHAR2(2 BYTE), 
	TRAN_SEQNUM VARCHAR2(9 BYTE), 
	TCODE VARCHAR2(4 BYTE), 
	AMOUNT VARCHAR2(12 BYTE), 
	JV_TYPE VARCHAR2(3 BYTE), 
	CFA_SIGN VARCHAR2(1 BYTE), 
	REFEED_TCODE VARCHAR2(4 BYTE), 
	DR_DIV VARCHAR2(3 BYTE), 
	DR_PRIME VARCHAR2(4 BYTE), 
	DR_SUB VARCHAR2(3 BYTE), 
	DR_CC VARCHAR2(4 BYTE), 
	DR_PROJ VARCHAR2(4 BYTE), 
	DR_OFFSET_CDE VARCHAR2(1 BYTE), 
	CR_DIV VARCHAR2(3 BYTE), 
	CR_PRIME VARCHAR2(4 BYTE), 
	CR_SUB VARCHAR2(3 BYTE), 
	CR_CC VARCHAR2(4 BYTE), 
	CR_PROJ VARCHAR2(4 BYTE), 
	CR_OFFSET_CDE VARCHAR2(1 BYTE), 
	FILLER VARCHAR2(1 BYTE)
   );
	/
  

   