  CREATE TABLE LEAD_BANK_CC_HIST 
   (LEAD_BANK_ACCOUNT_NBR VARCHAR2(16 BYTE) NOT NULL ENABLE, 
	LEAD_STORE_NBR VARCHAR2(6 BYTE) NOT NULL ENABLE, 
	EFFECTIVE_DATE DATE NOT NULL ENABLE, 
	EXPIRATION_DATE DATE NOT NULL ENABLE, 
	BANK_BRANCH_NBR VARCHAR2(8 BYTE), 
	BANK_TYPE_CODE VARCHAR2(1 BYTE), 
	UPDATE_DATE DATE NOT NULL ENABLE, 
	LAST_UPD_USER_ID VARCHAR2(8 BYTE) NOT NULL ENABLE
   );
  /
  CREATE INDEX LEAD_BANK_CC_HIST_INDX ON LEAD_BANK_CC_HIST (LEAD_BANK_ACCOUNT_NBR, LEAD_STORE_NBR, EFFECTIVE_DATE);
 /