  CREATE TABLE LEAD_BANK_CC 
   (BANK_ACCOUNT_NBR VARCHAR2(16) NOT NULL ENABLE, 
	COST_CENTER_CODE VARCHAR2(6) NOT NULL ENABLE, 
	EFFECTIVE_DATE DATE, 
	EXPIRATION_DATE DATE, 
	BANK_BRANCH_NBR VARCHAR2(8), 
	BANK_TYPE_CODE VARCHAR2(1), 
	 CONSTRAINT BANK_CC_ASSIGNMENT_PK PRIMARY KEY (COST_CENTER_CODE)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE BANKING_DATA  ENABLE, 
	 CONSTRAINT BANK_CC_ASSGN_BANK_ACCOUNT_FK FOREIGN KEY (BANK_ACCOUNT_NBR)
	  REFERENCES BANKING.BANK_ACCOUNT (BANK_ACCOUNT_NBR) ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BANKING_DATA" ;
  /