  CREATE TABLE LEAD_BANK_CC_FUTURE 
   (BANK_ACCOUNT_NBR VARCHAR2(16) NOT NULL ENABLE, 
	COST_CENTER_CODE VARCHAR2(6) NOT NULL ENABLE, 
	EFFECTIVE_DATE DATE NOT NULL ENABLE, 
	EXPIRATION_DATE DATE, 
	BANK_BRANCH_NBR VARCHAR2(8), 
	BANK_TYPE_CODE VARCHAR2(1), 
	UPDATE_DATE DATE, 
	LAST_UPD_USER_ID VARCHAR2(8), 
	FUTURE_ID NUMBER, 
	 CONSTRAINT LEAD_BANK_CC_FUTURE_PK PRIMARY KEY (BANK_ACCOUNT_NBR, COST_CENTER_CODE, FUTURE_ID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE BANKING_DATA  ENABLE, 
	 CONSTRAINT LEAD_BANK_CC_FUTURE_FK FOREIGN KEY (FUTURE_ID, BANK_ACCOUNT_NBR)
	  REFERENCES BANKING.BANK_ACCOUNT_FUTURE (FUTURE_ID, BANK_ACCOUNT_NBR) ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BANKING_DATA" ;
  
  /