  CREATE TABLE LEAD_BANK_CC_T 
   (BANK_ACCOUNT_NBR VARCHAR2(16), 
	COST_CENTER_CODE VARCHAR2(6), 
	EFFECTIVE_DATE VARCHAR2(8), 
	EXPIRATION_DATE VARCHAR2(8), 
	BANK_BRANCH_NBR VARCHAR2(8), 
	BANK_TYPE_CODE VARCHAR2(1)
   );
  
  /