  CREATE TABLE MEMBER_BANK_CONCENTRATION_CC
            (LEAD_STORE_NBR VARCHAR2(6 BYTE) NOT NULL ENABLE, 
	           MEMBER_STORE_NBR VARCHAR2(6 BYTE) NOT NULL ENABLE, 
	           LOAD_DATE DATE
   );