  CREATE TABLE MEMBER_BANK_CC_FUTURE 
   (BANK_ACCOUNT_NUMBER VARCHAR2(16), 
	LEAD_STORE_NBR VARCHAR2(6) NOT NULL ENABLE, 
	MEMBER_STORE_NBR VARCHAR2(6) NOT NULL ENABLE, 
	EFFECTIVE_DATE DATE NOT NULL ENABLE, 
	EXPIRATION_DATE DATE, 
	BANK_BRANCH_NBR VARCHAR2(8), 
	UPDATE_DATE DATE, 
	LAST_UPD_USER_ID VARCHAR2(8), 
	FUTURE_ID NUMBER, 
	 CONSTRAINT MEMBER_BANK_CC_FUTURE_PK PRIMARY KEY (LEAD_STORE_NBR, MEMBER_STORE_NBR, EFFECTIVE_DATE, FUTURE_ID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE BANKING_DATA  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BANKING_DATA" ;

  /