  CREATE TABLE MEMBER_BANK_CC_T 
   (BANK_ACCOUNT_NUMBER VARCHAR2(16), 
	LEAD_STORE_NBR VARCHAR2(6), 
	MEMBER_STORE_NBR VARCHAR2(6), 
	EFFECTIVE_DATE VARCHAR2(8), 
	EXPIRATION_DATE VARCHAR2(8), 
	BANK_BRANCH_NBR VARCHAR2(8)
   );
  /