GRANT SELECT ON LEAD_BANK_CC_VW TO NETEZZA_ACCESS;
GRANT SELECT ON MEMBER_BANK_CC_VW TO NETEZZA_ACCESS;
GRANT SELECT ON BANK_ACCOUNT_VW TO NETEZZA_ACCESS;

CREATE OR REPLACE SYNONYM NETEZZA_ACCESS.LEAD_BANK_CC_VW FOR BANKING.LEAD_BANK_CC_VW;
CREATE OR REPLACE SYNONYM NETEZZA_ACCESS.MEMBER_BANK_CC_VW FOR BANKING.MEMBER_BANK_CC_VW;
CREATE OR REPLACE SYNONYM NETEZZA_ACCESS.BANK_ACCOUNT_VW FOR BANKING.BANK_ACCOUNT_VW;

