/*
Created : 08/14/2018 pxa852 CCN Project....
          This table will hold the data for PNP.CCN_BATCH_SUMMARY table. This table is created for testing purpose.
*/
 CREATE TABLE POS_SUMM_EXTRCT_CNTRL_FL_TST
   (COST_CENTER_CODE          VARCHAR2(6),
    BANK_DEP_AMT              NUMBER,
    BANK_ACCOUNT_NBR          VARCHAR2(17),
    TRANSACTION_DATE          DATE,
    LOAD_DATE                 DATE,
    ORIGINATED_BANK_ACCNT_NBR VARCHAR2(17),
    RLS_RUN_CYCLE             NUMBER
   );
  CREATE INDEX POS_SUMM_EXTRCT_IDX1_TST ON POS_SUMM_EXTRCT_CNTRL_FL_TST (TRANSACTION_DATE,COST_CENTER_CODE);
  CREATE INDEX POS_SUMM_EXTRCT_IDX_TST ON POS_SUMM_EXTRCT_CNTRL_FL_TST (COST_CENTER_CODE,BANK_DEP_AMT,TRANSACTION_DATE);