/*
Created : 06/22/2018 nxk927 CCN Project....
          This table will hold the data for SUMMARY_EXTRCT_CNTRL_FL
*/
 CREATE TABLE POS_SUMMARY_EXTRCT_CNTRL_FL
   (COST_CENTER_CODE           VARCHAR2(6),
    BANK_DEP_AMT               NUMBER,
    BANK_ACCOUNT_NBR           VARCHAR2(17),
    TRANSACTION_DATE           DATE, 
    LOAD_DATE                  DATE,
    ORIGINATED_BANK_ACCNT_NBR  VARCHAR2(17),
    RLS_RUN_CYCLE              NUMBER);
    
  CREATE INDEX POS_SUMMARY_EXTRCT_IDX ON POS_SUMMARY_EXTRCT_CNTRL_FL (COST_CENTER_CODE, BANK_DEP_AMT, TRANSACTION_DATE);
  CREATE INDEX POS_SUMMARY_EXTRCT_IDX1 ON POS_SUMMARY_EXTRCT_CNTRL_FL (TRANSACTION_DATE, COST_CENTER_CODE);