  CREATE TABLE STORE_MICR_FORMAT_DTLS_HIST 
   (	BANK_ACCOUNT_NBR VARCHAR2(20) NOT NULL ENABLE,
	MICR_FORMAT_ID NUMBER NOT NULL ENABLE,
	COST_CENTER_CODE VARCHAR2(6) NOT NULL ENABLE,
	MICR_COST_CNTR VARCHAR2(8),
	MICR_ROUTING_NBR VARCHAR2(11),
	MICR_FORMAT_ACCT_NBR VARCHAR2(17),
	EFFECTIVE_DATE DATE NOT NULL ENABLE,
	EXPIRATION_DATE DATE
   );
/