CREATE TABLE STR_BNK_DPST_DLY_RCNCL_TBL 
   (	COST_CENTER_CODE VARCHAR2(6), 
	BANK_ACCOUNT_NBR VARCHAR2(17), 
	COST_CENTER_NAME VARCHAR2(50), 
	BANK_NAME VARCHAR2(50), 
	RECONCILIATION_DATE DATE, 
	RECONCILIATION_IND VARCHAR2(1), 
	LEAD_BANK_CC VARCHAR2(6), 
	BANK_TYPE_CODE VARCHAR2(1), 
	DIVISION VARCHAR2(2), 
	AREA VARCHAR2(2), 
	DISTRICT VARCHAR2(2), 
	CONSTRAINT STR_BNK_DPST_DLY_RCNCL_TBL_PK PRIMARY KEY (BANK_ACCOUNT_NBR, COST_CENTER_CODE);
	/