CREATE OR REPLACE SYNONYM COST_CENTER FOR COSTCNTR.COST_CENTER;
CREATE OR REPLACE SYNONYM CCN_COMMON_TOOLS FOR CCN_UTILITY.CCN_COMMON_TOOLS;

CREATE OR REPLACE SYNONYM BATCH_JOB FOR CCN_UTILITY.BATCH_JOB;
CREATE OR REPLACE SYNONYM CCN_BATCH_PKG FOR CCN_UTILITY.CCN_BATCH_PKG;
CREATE OR REPLACE SYNONYM PHONE_NBR FOR COSTCNTR.CCN_PHONE_INFO_VW;
CREATE OR REPLACE SYNONYM HIERARCHY_DETAIL_VIEW FOR COSTCNTR.HIERARCHY_DETAIL_VIEW;
CREATE OR REPLACE SYNONYM ADDRESS_VW FOR COSTCNTR.ADDRESS_VW;
/