/********************************************************************************** 
This script is created to create Synonyms

Created : 07/26/2019 axm868 CCN Project CCNBN-12....
          Run this script in BANKING Schema
Modified: 
**********************************************************************************/
CREATE OR REPLACE SYNONYM CCN_UTILITY.BANKING_ERROR_LOG FOR BANKING.ERROR_LOG;
CREATE OR REPLACE SYNONYM CCN_UTILITY.BANK_DEP_TICKORD FOR BANKING.BANK_DEP_TICKORD;
CREATE OR REPLACE SYNONYM CCN_UTILITY.BANK_DEP_BAG_TICKORD FOR BANKING.BANK_DEP_BAG_TICKORD;
CREATE OR REPLACE SYNONYM CCN_UTILITY.BANK_DEP_TICK FOR BANKING.BANK_DEP_TICK;
CREATE OR REPLACE SYNONYM CCN_UTILITY.BANK_DEP_BAG_TICK FOR BANKING.BANK_DEP_BAG_TICK;
CREATE OR REPLACE SYNONYM CCN_UTILITY.BANK_DEP_TICK_BAG_EXCLD_CCS FOR BANKING.BANK_DEP_TICK_BAG_EXCLD_CCS;