CREATE TABLE UAR_ACH_DRFTS_EXT_CTRL
   (COST_CENTER_CODE VARCHAR2(4),
    CENTURY          VARCHAR2(1),
    TRANSACTION_DATE DATE,
    BANK_DEP_AMT     VARCHAR2(10),
    BANK_ACCOUNT_NBR VARCHAR2(17),
    LOAD_DATE        DATE);
