CREATE TABLE UAR_MISCTRAN
  (COST_CENTER_CODE VARCHAR2(4),
   AMOUNT           VARCHAR2(12),
   TRANSACTION_DATE DATE,
   TCODE            VARCHAR2(4),
   DISTRICT         VARCHAR2(2),
   AREA             VARCHAR2(2),
   DIVISION         VARCHAR2(2),
   TRAN_SEQNUM      VARCHAR2(9),
   DB_CR_CODE       VARCHAR2(2),
   SNZ_SAM_CODE     VARCHAR2(3),
   LOAD_DATE        DATE
   );