CREATE TABLE MISCTRAN
  (BANK_ACCOUNT_NBR VARCHAR2(20),
   COST_CENTER_CODE VARCHAR2(4),
   AMOUNT           VARCHAR2(12),
   TRANSACTION_DATE DATE,
   TCODE            VARCHAR2(4),
   TRAN_SEQNUM      VARCHAR2(9),
   DB_CR_CODE       VARCHAR2(2),
   SNZ_SAM_CODE     VARCHAR2(3),
   LOAD_DATE        DATE
   );