CREATE TABLE UAR_JV_EXTRCT_CNTRL_FL 
(	BANK_ACCOUNT_NBR VARCHAR2(17), 
	COST_CENTER_CODE VARCHAR2(4), 
	CENTURY VARCHAR2(1), 
	TRAN_SEQNUM VARCHAR2(9), 
	TCODE VARCHAR2(4), 
	AMOUNT VARCHAR2(12), 
	JV_TYPE VARCHAR2(3), 
	CFA_SIGN VARCHAR2(1), 
	REFEED_TCODE VARCHAR2(4), 
	DR_DIV VARCHAR2(3), 
	DR_PRIME VARCHAR2(4), 
	DR_SUB VARCHAR2(3), 
	DR_CC VARCHAR2(4), 
	DR_PROJ VARCHAR2(4), 
	DR_OFFSET_CDE VARCHAR2(1), 
	CR_DIV VARCHAR2(3), 
	CR_PRIME VARCHAR2(4), 
	CR_SUB VARCHAR2(3), 
	CR_CC VARCHAR2(4), 
	CR_PROJ VARCHAR2(4), 
	CR_OFFSET_CDE VARCHAR2(1), 
	FILLER VARCHAR2(1),
    TRANSACTION_DATE DATE, 
	LOAD_DATE DATE
   );
	
  CREATE INDEX UAR_JV_EXTRCT_INDX1 ON UAR_JV_EXTRCT_CNTRL_FL (COST_CENTER_CODE, LOAD_DATE); 
  CREATE INDEX UAR_JV_EXTRCT_INDX2 ON UAR_JV_EXTRCT_CNTRL_FL (BANK_ACCOUNT_NBR, LOAD_DATE);
  CREATE INDEX UAR_JV_EXTRCT_INDX3 ON UAR_JV_EXTRCT_CNTRL_FL (LOAD_DATE); 
  