 CREATE TABLE UAR_SUMMARY_EXTRCT_CNTRL_FL
   (COST_CENTER_CODE VARCHAR2(4), 
	CENTURY VARCHAR2(1), 
	BANK_DEP_AMT VARCHAR2(9), 
	FILLER VARCHAR2(1), 
	BANK_ACCOUNT_NBR VARCHAR2(17),
	TRANSACTION_DATE DATE, 
	LOAD_DATE DATE
    ) ;
	
  CREATE INDEX UAR_SUMMARY_EXTRCT_INDX1 ON UAR_SUMMARY_EXTRCT_CNTRL_FL (COST_CENTER_CODE, LOAD_DATE) ;
  CREATE INDEX UAR_SUMMARY_EXTRCT_INDX2 ON UAR_SUMMARY_EXTRCT_CNTRL_FL (BANK_ACCOUNT_NBR, LOAD_DATE) ;
  CREATE INDEX UAR_SUMMARY_EXTRCT_INDX3 ON UAR_SUMMARY_EXTRCT_CNTRL_FL (LOAD_DATE) ;