CREATE TABLE "STORDRFT"."DLY_CUSTOMER_DETAILS" 
   (	"COST_CENTER_CODE" VARCHAR2(4 BYTE), 
	"TERMINAL_NUMBER" VARCHAR2(5 BYTE), 
	"TRANSACTION_NUMBER" VARCHAR2(5 BYTE), 
	"SORT_FORCE" VARCHAR2(3 BYTE), 
	"SEGMENT_CODE" VARCHAR2(2 BYTE), 
	"SUB_SEGMENT_CODE" VARCHAR2(2 BYTE), 
	"FILLER" VARCHAR2(5 BYTE), 
	"SALES_NUMBER" VARCHAR2(9 BYTE), 
	"ITEM_QUANTITY_SIGN" VARCHAR2(1 BYTE), 
	"ITEM_QUANTITY" VARCHAR2(7 BYTE), 
	"ITEM_PRICE_SIGN" VARCHAR2(1 BYTE), 
	"ITEM_PRICE" VARCHAR2(7 BYTE), 
	"ITEM_EXTERNAL_AMOUNT_SIGN" VARCHAR2(1 BYTE), 
	"ITEM_EXTERNAL_AMOUNT" VARCHAR2(7 BYTE), 
	"ITEM_DISC_AMOUNT_SIGN" VARCHAR2(1 BYTE), 
	"ITEM_DISC_AMOUNT" VARCHAR2(7 BYTE), 
	"ITEM_SALES_TAX_INDICATOR" VARCHAR2(1 BYTE), 
	"ITEM_DISC_CODE" VARCHAR2(1 BYTE), 
	"ITEM_DISC_TYPE" VARCHAR2(1 BYTE), 
	"SALES_PROMO_CODE" VARCHAR2(1 BYTE), 
	"GL_PRIME_ACCOUNT" VARCHAR2(4 BYTE), 
	"GL_SUB_ACCOUNT" VARCHAR2(3 BYTE), 
	"SCHEDULE_TYPE" VARCHAR2(2 BYTE), 
	"SCHEDULE_VERSION" VARCHAR2(6 BYTE), 
	"PRICE_LVL_CODE" VARCHAR2(1 BYTE), 
	"PERCENT_OFF_LVL" VARCHAR2(3 BYTE), 
	"PROD_DESC_SOURCE" VARCHAR2(1 BYTE), 
	"ORGNL_POS_TERMINAL_NUMBER" VARCHAR2(5 BYTE), 
	"ORGNL_POS_TRANSACTION_NUMBER" VARCHAR2(5 BYTE)
   ) 
   ORGANIZATION EXTERNAL 
    ( TYPE ORACLE_LOADER
      DEFAULT DIRECTORY "STORDRFT_LOAD_FILES"
      ACCESS PARAMETERS
      ( RECORDS DELIMITED BY NEWLINE
        badfile "STORDRFT_LOAD_FILES":'DLY_CUSTOMER_DETAILS.bad'
        logfile "STORDRFT_LOAD_FILES":'DLY_CUSTOMER_DETAILS.log'
        discardfile "STORDRFT_LOAD_FILES":'DLY_CUSTOMER_DETAILS.dsc'
        LOAD WHEN ((18:19) = '01' OR (18:19) = '09')
        FIELDS(
                COST_CENTER_CODE         CHAR(4),
                TERMINAL_NUMBER          CHAR(5),
                TRANSACTION_NUMBER       CHAR(5),
                SORT_FORCE               CHAR(3),
                SEGMENT_CODE             CHAR(2),
                SUB_SEGMENT_CODE         CHAR(2),
                FILLER                   CHAR(5),
                SALES_NUMBER             CHAR(9),
                ITEM_QUANTITY_SIGN       CHAR(1),
                ITEM_QUANTITY            CHAR(7),
                ITEM_PRICE_SIGN          CHAR(1),
                ITEM_PRICE               CHAR(7),
                ITEM_EXTERNAL_AMOUNT_SIGN CHAR(1),
                ITEM_EXTERNAL_AMOUNT     CHAR(7),
                ITEM_DISC_AMOUNT_SIGN    CHAR(1),
                ITEM_DISC_AMOUNT         CHAR(7),
                ITEM_SALES_TAX_INDICATOR CHAR(1),
                ITEM_DISC_CODE           CHAR(1),
                ITEM_DISC_TYPE           CHAR(1),
                SALES_PROMO_CODE         CHAR(1),
                GL_PRIME_ACCOUNT         CHAR(4),
                GL_SUB_ACCOUNT           CHAR(3),
                SCHEDULE_TYPE            CHAR(2),
                SCHEDULE_VERSION         CHAR(6),
                PRICE_LVL_CODE           CHAR(1),
                PERCENT_OFF_LVL          CHAR(3),
                PROD_DESC_SOURCE         CHAR(1),
                ORGNL_POS_TERMINAL_NUMBER CHAR(5),
                ORGNL_POS_TRANSACTION_NUMBER CHAR(5)
                               )
              )
      LOCATION
       ( 'CUSTOMER_LABOR.TXT'
       )
    );
