BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE DLY_DISBURSMENT_LINE_ITEM_DATA';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

  CREATE TABLE DLY_DISBURSMENT_LINE_ITEM_DATA 
   (	TRANSACTION_SOURCE VARCHAR2(1 BYTE), 
	TRANSACTION_TYPE VARCHAR2(1 BYTE), 
	COST_CENTER_CODE VARCHAR2(4 BYTE), 
	CHECK_SERIAL_NUMBER VARCHAR2(10 BYTE), 
	PROCESS_DATE VARCHAR2(7 BYTE), 
	FILLER VARCHAR2(16 BYTE), 
	TRANSACTION_SEGMENT_TYPE VARCHAR2(1 BYTE), 
	ITEM_EXT_AMOUNT_SIGN VARCHAR2(1 BYTE), 
	ITEM_EXT_AMOUNT VARCHAR2(9 BYTE), 
	ORGNL_CUSTOMER_ACCOUNT_NUMBER VARCHAR2(9 BYTE), 
	ORGNL_JOB_NUMBER VARCHAR2(2 BYTE)
   ) 
   ORGANIZATION EXTERNAL 
    ( TYPE ORACLE_LOADER
      DEFAULT DIRECTORY STORDRFT_LOAD_FILES
      ACCESS PARAMETERS
      ( RECORDS DELIMITED BY NEWLINE
        badfile STORDRFT_LOAD_FILES:'DLY_DISBURSMENT_LINE_ITEM_DATA.bad'
        logfile STORDRFT_LOAD_FILES:'DLY_DISBURSMENT_LINE_ITEM_DATA.log'
        discardfile STORDRFT_LOAD_FILES:'DLY_DISBURSMENT_LINE_ITEM_DATA.dsc'
        LOAD WHEN ((40:40) = 'L')
        FIELDS(
                TRANSACTION_SOURCE             CHAR(1),
                TRANSACTION_TYPE               CHAR(1),
                COST_CENTER_CODE               CHAR(4),
                CHECK_SERIAL_NUMBER            CHAR(10),
                PROCESS_DATE                   CHAR(7),
                FILLER                         CHAR(16),
                TRANSACTION_SEGMENT_TYPE       CHAR(1),
                ITEM_EXT_AMOUNT_SIGN           CHAR(1),
                ITEM_EXT_AMOUNT                CHAR(9),
                ORGNL_CUSTOMER_ACCOUNT_NUMBER  CHAR(9),
                ORGNL_JOB_NUMBER               CHAR(2)
                               )
              )
      LOCATION
       ( 'STORE_DRAFT.TXT'
       )
    );
