BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE TEMP_STORE_DRAFT_DETAIL_HST';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

  CREATE TABLE TEMP_STORE_DRAFT_DETAIL_HST 
     (	COST_CENTER_CODE VARCHAR2(6 BYTE), 
  	CHECK_SERIAL_NUMBER VARCHAR2(10 BYTE), 
  	TRANSACTION_DATE VARCHAR2(8 BYTE), 
  	TERM_NUMBER VARCHAR2(5 BYTE), 
  	TRANSACTION_NUMBER VARCHAR2(5 BYTE), 
  	CUSTOMER_ACCOUNT_NUMBER VARCHAR2(9 BYTE), 
  	CUSTOMER_JOB_NUMBER VARCHAR2(2 BYTE), 
  	GL_PRIME_ACCOUNT_NUMBER VARCHAR2(4 BYTE), 
  	GL_SUB_ACCOUNT_NUMBER VARCHAR2(3 BYTE), 
  	ITEM_QUANTITY VARCHAR2(7 BYTE), 
  	ITEM_PRICE VARCHAR2(7 BYTE), 
  	ITEM_PRICE_SGN VARCHAR2(1 BYTE), 
  	ITEM_EXT_AMOUNT VARCHAR2(7 BYTE), 
  	ITEM_EXT_AMOUNT_SGN VARCHAR2(1 BYTE), 
  	BOOK_DATE_SEQUENCE VARCHAR2(5 BYTE), 
  	LBR_TRANSACTION_DATE VARCHAR2(8 BYTE), 
  	LBR_TERM_NUMBER VARCHAR2(5 BYTE), 
  	LBR_TRANSACTION_NUMBER VARCHAR2(5 BYTE)
     ) 
     ORGANIZATION EXTERNAL 
      ( TYPE ORACLE_LOADER
        DEFAULT DIRECTORY STORDRFT_LOAD_FILES
        ACCESS PARAMETERS
        ( RECORDS FIXED 99
            badfile STORDRFT_LOAD_FILES:'TEMP_STORE_DRAFT_DETAIL_HST.bad'
            logfile STORDRFT_LOAD_FILES:'TEMP_STORE_DRAFT_DETAIL_HST.log'
            discardfile STORDRFT_LOAD_FILES:'TEMP_STORE_DRAFT_DETAIL_HST.dsc'
              FIELDS
              missing field values are null
      ( 
        COST_CENTER_CODE    CHAR(6), 
        CHECK_SERIAL_NUMBER CHAR(10), 
        TRANSACTION_DATE    CHAR(8),
        TERM_NUMBER         CHAR(5), 
        TRANSACTION_NUMBER  CHAR(5), 
        CUSTOMER_ACCOUNT_NUMBER CHAR(9), 
        CUSTOMER_JOB_NUMBER     CHAR(2), 
        GL_PRIME_ACCOUNT_NUMBER CHAR(4), 
        GL_SUB_ACCOUNT_NUMBER   CHAR(3), 
        ITEM_QUANTITY           CHAR(7), 
        ITEM_PRICE              CHAR(7), 
        ITEM_PRICE_SGN              CHAR(1), 
        ITEM_EXT_AMOUNT         CHAR(7), 
        ITEM_EXT_AMOUNT_SGN         CHAR(1), 
        BOOK_DATE_SEQUENCE      CHAR(5), 
        LBR_TRANSACTION_DATE    CHAR(8), 
        LBR_TERM_NUMBER         CHAR(5), 
        LBR_TRANSACTION_NUMBER  CHAR(5) 
      ) 
                                        )
        LOCATION
         ( 'STBD9000_DLINEIT_1999.TXT', 
           'STBD9000_DLINEIT_2000.TXT', 
           'STBD9000_DLINEIT_2001.TXT', 
           'STBD9000_DLINEIT_2002.TXT', 
           'STBD9000_DLINEIT_2003.TXT', 
           'STBD9000_DLINEIT_2004.TXT', 
           'STBD9000_DLINEIT_2005.TXT', 
           'STBD9000_DLINEIT_2006.TXT', 
           'STBD9000_DLINEIT_2007.TXT', 
           'STBD9000_DLINEIT_2008.TXT', 
           'STBD9000_DLINEIT_2009.TXT', 
           'STBD9000_DLINEIT_2010.TXT', 
           'STBD9000_DLINEIT_2011.TXT', 
           'STBD9000_DLINEIT_2012.TXT', 
           'STBD9000_DLINEIT_2013.TXT'
         )
    );
