BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE TEMP_STORE_DRAFT_DETAIL';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE TEMP_STORE_DRAFT_DETAIL 
   (	COST_CENTER_CODE VARCHAR2(6 BYTE), 
	CHECK_SERIAL_NUMBER VARCHAR2(10 BYTE), 
	TRANSACTION_DATE VARCHAR2(8 BYTE), 
	TERM_NUMBER VARCHAR2(5 BYTE), 
	TRANSACTION_NUMBER VARCHAR2(5 BYTE), 
	CUSTOMER_ACCOUNT_NUMBER VARCHAR2(9 BYTE), 
	CUSTOMER_JOB_NUMBER VARCHAR2(2 BYTE), 
	GL_PRIME_ACCOUNT_NUMBER VARCHAR2(4 BYTE), 
	GL_SUB_ACCOUNT_NUMBER VARCHAR2(3 BYTE), 
	ITEM_QUANTITY VARCHAR2(7 BYTE), 
	ITEM_PRICE VARCHAR2(7 BYTE), 
	ITEM_EXT_AMOUNT VARCHAR2(7 BYTE), 
	BOOK_DATE_SEQUENCE VARCHAR2(5 BYTE), 
	LBR_TRANSACTION_DATE VARCHAR2(8 BYTE), 
	LBR_TERM_NUMBER VARCHAR2(5 BYTE), 
	LBR_TRANSACTION_NUMBER VARCHAR2(5 BYTE)
   ) 
   ORGANIZATION EXTERNAL 
    ( TYPE ORACLE_LOADER
      DEFAULT DIRECTORY STORDRFT_LOAD_FILES
      ACCESS PARAMETERS
      ( RECORDS FIXED 99
        badfile STORDRFT_LOAD_FILES:'TEMP_STORE_DRAFT_DETAIL.bad'
        logfile STORDRFT_LOAD_FILES:'TEMP_STORE_DRAFT_DETAIL.log'
        discardfile STORDRFT_LOAD_FILES:'TEMP_STORE_DRAFT_DETAIL.dsc'
          FIELDS
          missing field values are null
  ( 
    COST_CENTER_CODE    CHAR(6), 
    CHECK_SERIAL_NUMBER CHAR(10), 
    TRANSACTION_DATE    CHAR(8),
    TERM_NUMBER         CHAR(5), 
    TRANSACTION_NUMBER  CHAR(5), 
    CUSTOMER_ACCOUNT_NUMBER CHAR(9), 
    CUSTOMER_JOB_NUMBER     CHAR(2), 
    GL_PRIME_ACCOUNT_NUMBER CHAR(4), 
    GL_SUB_ACCOUNT_NUMBER   CHAR(3), 
    ITEM_QUANTITY           CHAR(7), 
    ITEM_PRICE              CHAR(8), 
    ITEM_EXT_AMOUNT         CHAR(8), 
    BOOK_DATE_SEQUENCE      CHAR(5), 
    LBR_TRANSACTION_DATE    CHAR(8), 
    LBR_TERM_NUMBER         CHAR(5), 
    LBR_TRANSACTION_NUMBER  CHAR(5) 
  ) 
                            )
      LOCATION
       ( 'CCN99CTR_DLINEIT.TXT'
       )
    );
