/*
ASP-1255 This script will rename STORE_NO to STORECCN column in CCN_HEADERS_T table.
Created  : 05/31/2019 sxs484 
*/
ALTER TABLE CCN_HEADERS_T MODIFY STORE_NO VARCHAR2(6);

ALTER TABLE CCN_HEADERS_T RENAME COLUMN STORE_NO TO STORECCN;

-- Data Conversion of existing 4 digit store_no to 6 .
SET SERVEROUTPUT ON;
DECLARE
    V_CC VARCHAR2(6);
BEGIN
    FOR rec IN (SELECT DISTINCT STORECCN FROM CCN_HEADERS_T) LOOP
        BEGIN
            V_CC := COMMON_TOOLS.COST_CENTER_LOOK_UP_FNC(rec.STORECCN);
            UPDATE CCN_HEADERS_T SET STORECCN = V_CC WHERE STORECCN = rec.STORECCN;
            COMMIT;
            V_CC := NULL;
        EXCEPTION
            WHEN OTHERS THEN
                DBMS_OUTPUT.PUT_LINE(SQLCODE ||':'|| SQLERRM);
        END;
    END LOOP;
END;

ALTER TABLE CCN_HEADERS_T MODIFY (STORECCN NOT NULL);
