/*
This script is used to alter CUSTOMER_DEPOSIT_HEADER,CUSTOMER_DEPOSIT_HEADER_HST tables to drop CLEARED_REASON,CLOSED_DATE,NOTES,REFERENCE_NUMBER

Created : 01/31/2019 sxg151 CCN Project Team....
Changed :
*/
Alter Table CUSTOMER_DEPOSIT_HEADER
      drop (CLEARED_REASON,CLOSED_DATE,NOTES,REFERENCE_NUMBER);
	  
Alter Table CUSTOMER_DEPOSIT_HEADER_HST
      drop (CLEARED_REASON,CLOSED_DATE,NOTES,REFERENCE_NUMBER);