 
 /*ASP-1255 sxs484*/
 --From TEST : Missing in QA .  
    CREATE INDEX "CSTMR_DPSTS"."CCN_HEADERS_T_IND" ON "CSTMR_DPSTS"."CCN_HEADERS_T" ("STORECCN", "ACCTNBR", "TRAN_DATE", "TERMNBR", "TRANNBR") 
  TABLESPACE "CSTMR_DPSTS_DATA" ;
  
    CREATE INDEX "CSTMR_DPSTS"."CCN_HEADERS_T_IND1" ON "CSTMR_DPSTS"."CCN_HEADERS_T" ("TRAN_GUID") 
  TABLESPACE "CSTMR_DPSTS_DATA" ;
  
  CREATE INDEX "CSTMR_DPSTS"."CCN_HEADERS_T_INDEX2" ON "CSTMR_DPSTS"."CCN_HEADERS_T" ("RLS_RUN_CYCLE", "ACCTNBR") 
  TABLESPACE "CSTMR_DPSTS_DATA" ;