/*
This script to add index in CCN_HEADERS_T table.

Created : 06/11/2019 sxs484 CCN Project Team....
Changed :
*/
CREATE INDEX CCN_HEADERS_T_IND ON CCN_HEADERS_T (STORECCN, ACCTNBR, TRAN_DATE, TERMNBR, TRANNBR);

CREATE INDEX CCN_HEADERS_T_IND1 ON CCN_HEADERS_T (TRAN_GUID);

CREATE INDEX CCN_HEADERS_T_INDEX2 ON CCN_HEADERS_T (RLS_RUN_CYCLE, ACCTNBR);