--indexes on intermediate tables
--05/30/2018 sxh487
CREATE INDEX CCN_SALES_LINES_T_INDEX1 ON CSTMR_DPSTS.CCN_SALES_LINES_T (TRAN_GUID, RLS_RUN_CYCLE, NON_MERCH_CODE);
CREATE INDEX CCN_HEADERS_T_INDEX1 ON CSTMR_DPSTS.CCN_HEADERS_T (RLS_RUN_CYCLE);