/***************************************************************
Description : Table CUSTOMER_DEPOSIT_DETAILS
Created  : 09/28/2017 sxh487 CCN Project Team.....
***************************************************************/
CREATE TABLE CUSTOMER_DEPOSIT_DETAILS 
   (	COST_CENTER_CODE VARCHAR2(6) NOT NULL ENABLE, 
	TRANSACTION_DATE DATE NOT NULL ENABLE, 
	TERMINAL_NUMBER VARCHAR2(5) NOT NULL ENABLE, 
	TRANSACTION_NUMBER VARCHAR2(5) NOT NULL ENABLE, 
	TRANSACTION_GUID RAW(16), 
	CUSTOMER_ACCOUNT_NUMBER VARCHAR2(9), 
	POS_TRANSACTION_CODE VARCHAR2(2), 
	TRAN_TIMESTAMP TIMESTAMP (6), 
	TRANSACTION_TYPE VARCHAR2(50), 
	TOTAL_SALES NUMBER, 
	CUSTOMER_NET_BALANCE NUMBER, 
	LOAD_DATE DATE, 
	RLS_RUN_CYCLE NUMBER, 
	CONSTRAINT CUSTOMER_DEPOSIT_DETAILS_FK FOREIGN KEY (TRANSACTION_GUID)
	REFERENCES CUSTOMER_DEPOSIT (TRANSACTION_GUID) ENABLE
   );