/*
     Created: 04/30/2018 sxh487 CCN Project Team..
     This table is for maintaining audit history for CUSTOMER_DEPOSIT_DETAILS
*/
CREATE TABLE CUSTOMER_DEPOSIT_DETAILS_HIST 
   (	COST_CENTER_CODE           VARCHAR2(6),
	TRANSACTION_DATE           DATE,
	TERMINAL_NUMBER            VARCHAR2(5),
	TRANSACTION_NUMBER         VARCHAR2(5),
	TRANSACTION_GUID           RAW(16),
	CUSTOMER_ACCOUNT_NUMBER    VARCHAR2(9),
	POS_TRANSACTION_CODE       VARCHAR2(2),
	TRAN_TIMESTAMP             TIMESTAMP(6),
	TRANSACTION_TYPE           VARCHAR2(50),
	TOTAL_SALES                NUMBER,
	CUSTOMER_NET_BALANCE       NUMBER,
	LOAD_DATE                  DATE,
	RLS_RUN_CYCLE              NUMBER,
	ADJUSTED_DATE              DATE,
	REFERENCE_NUMBER           VARCHAR2(5),
	CLEARED_REASON             VARCHAR2(100),
	NOTES                      VARCHAR2(1000),
	CLOSED_DATE                DATE,
	GL_DIVISION                VARCHAR2(20),
	HIST_LOAD_DT               DATE
   );