/*
     Created: 01/11/2019 pxa852 CCN Project Team..
     This script creates a new table CUST_DEP_CRD_RED_DETAILS
     This table stores the data from CUST_DEP_CREDIT_DETAILS and
     CUST_DEP_REDEMPTION_DETAILS tables.
*/
CREATE TABLE CUST_DEP_CRD_RED_DETAILS
   (CRD_RED_SEQ                     NUMBER NOT NULL,
    TRANSACTION_SQ_ID               NUMBER,
    TRANSACTION_TYPE                VARCHAR2(50),
    DEPOSIT_REMAINING_BAL           NUMBER,
    ORGNL_DEPOSIT_TERMINAL_NBR      VARCHAR2(5),
    ORGNL_DEPOSIT_TRANSACTION_NBR   VARCHAR2(5),
    ORGNL_DEPOSIT_TRANSACTION_DATE  DATE,
    CONSTRAINT CUST_DEP_CRD_RED_DETAILS1_PK PRIMARY KEY (CRD_RED_SEQ),
    CONSTRAINT CUST_DEP_CRD_RED_DETAILS1_FK1 FOREIGN KEY (TRANSACTION_SQ_ID)
     REFERENCES CSTMR_DPSTS.CUSTOMER_DEPOSIT_DETAILS (TRANSACTION_SQ_ID)
   );
CREATE INDEX CUST_DEP_CRD_RED_DETAILS_INDE ON CUST_DEP_CRD_RED_DETAILS (TRANSACTION_SQ_ID);