/*
     Created: 04/30/2018 sxh487 CCN Project Team..
     This script is for adding new columns and constraints
*/
ALTER TABLE CUSTOMER_DEPOSIT_HEADER
ADD (CLEARED_REASON   VARCHAR2(100),
     CLOSED_DATE      DATE,
     NOTES            VARCHAR2(4000),
     REFERENCE_NUMBER VARCHAR2(5));

ALTER TABLE CUSTOMER_DEPOSIT_DETAILS
ADD (ADJUSTED_DATE    DATE,
     CLEARED_REASON   VARCHAR2(1000),
     CLOSED_DATE      DATE,
     GL_DIVISION      VARCHAR2(20),
     NOTES            VARCHAR2(4000),
     REFERENCE_NUMBER VARCHAR2(5));
ALTER TABLE CUSTOMER_DEPOSIT_DETAILS MODIFY (CUSTOMER_ACCOUNT_NUMBER NOT NULL ENABLE);
ALTER TABLE CUSTOMER_DEPOSIT_DETAILS DROP CONSTRAINT CUSTOMER_DEPOSIT_DETAILS_FK;
ALTER TABLE CUSTOMER_DEPOSIT_DETAILS ADD CONSTRAINT CUSTOMER_DEPOSIT_DETAILS_PK PRIMARY KEY (COST_CENTER_CODE,TRANSACTION_DATE,TERMINAL_NUMBER,TRANSACTION_NUMBER,CUSTOMER_ACCOUNT_NUMBER);
ALTER TABLE CUSTOMER_DEPOSIT_DETAILS ADD CONSTRAINT CUSTOMER_DEPOSIT_DETAILS_FK FOREIGN KEY (CUSTOMER_ACCOUNT_NUMBER) REFERENCES CSTMR_DPSTS.CUSTOMER_DEPOSIT_HEADER(CUSTOMER_ACCOUNT_NUMBER);
