/*******************************************************************************
This script is intended to create a CUSTOMER_DEPOSIT_TRANSACTION_DTL table
which holds the deposit and redemption data from POS.
Alos, this table is storing the deposit remaining balance and orginals.
CREATED : 02/12/2019 pxa852 CCN Project...
*******************************************************************************/
CREATE TABLE CUSTOMER_DEPOSIT_TRANSACTION_DTL
   (CUST_DEP_TRANS_DETAIL_SEQ      NUMBER NOT NULL,
    COST_CENTER_CODE               VARCHAR2(6) NOT NULL,
    TRANSACTION_DATE               DATE NOT NULL,
    TERMINAL_NUMBER                VARCHAR2(5) NOT NULL,
    TRANSACTION_NUMBER             VARCHAR2(5) NOT NULL,
    TRANSACTION_GUID               RAW(16),
    CUSTOMER_ACCOUNT_NUMBER        VARCHAR2(9) NOT NULL,
    POS_TRANSACTION_CODE           VARCHAR2(2),
    TRAN_TIMESTAMP                 TIMESTAMP(6),
    TRANSACTION_TYPE               VARCHAR2(50),
    CSTMR_DPST_SALES_LN_ITM_AMT    NUMBER,
    CUSTOMER_NET_BALANCE           NUMBER,
    DEPOSIT_REMAINING_BAL          NUMBER,
    CLOSED_DATE                    DATE,
    REFERENCE_NUMBER               VARCHAR2(5),
    CLEARED_REASON                 VARCHAR2(1000),
    NOTES                          VARCHAR2(4000),
    ORGNL_DEPOSIT_TERMINAL_NBR     VARCHAR2(5),
    ORGNL_DEPOSIT_TRANSACTION_NBR  VARCHAR2(5),
    ORGNL_DEPOSIT_TRANSACTION_DATE DATE,
    LOAD_DATE                      DATE,
    RLS_RUN_CYCLE                  NUMBER,
    ADJUSTED_DATE                  DATE,
    GL_DIVISION                    VARCHAR2(20),
CONSTRAINT CUST_DEP_TRANS_DTL_PK PRIMARY KEY (CUST_DEP_TRANS_DETAIL_SEQ, COST_CENTER_CODE, CUSTOMER_ACCOUNT_NUMBER, TERMINAL_NUMBER),
CONSTRAINT CUST_DEP_TRANS_DTL_FK FOREIGN KEY (COST_CENTER_CODE, TERMINAL_NUMBER, CUSTOMER_ACCOUNT_NUMBER)
           REFERENCES CUSTOMER_DEPOSIT_TRANSACTION_HDR (COST_CENTER_CODE, TERMINAL_NUMBER, CUSTOMER_ACCOUNT_NUMBER));

CREATE INDEX CUST_DEP_TRANS_DTL_INDE ON CUSTOMER_DEPOSIT_TRANSACTION_DTL (CUSTOMER_ACCOUNT_NUMBER, TRAN_TIMESTAMP);

CREATE INDEX CUST_DEP_TRANS_DTL_INDE1 ON CUSTOMER_DEPOSIT_TRANSACTION_DTL (TRANSACTION_DATE);

CREATE INDEX CUST_DEP_TRANS_DTL_INDX ON CUSTOMER_DEPOSIT_TRANSACTION_DTL (CUSTOMER_ACCOUNT_NUMBER);

CREATE INDEX CUST_DEP_TRANS_DTL_IND ON CUSTOMER_DEPOSIT_TRANSACTION_DTL (TERMINAL_NUMBER, TRANSACTION_NUMBER,TRANSACTION_DATE);
