CREATE OR REPLACE VIEW CUSTOMER_DEPOSIT_VW 
AS 
  SELECT 
/*******************************************************************************
This view will provide the CUSTOMER_DEPOSIT information.

Created  : 03/23/2018 sxh487 CCN Project
Modified : 05/29/2018 sxh487 Added CSTMR_DPST_SALES_LN_ITM_AMT
         : 11/19/2017 kxm302 Removed filter on CUSTOMER_ACCOUNT_NUMBER to include all customers
         : 01/22/2019 pxa852 CCN Project team...
           Added customer account number in order by clause.
*******************************************************************************/
         CDD.CUSTOMER_ACCOUNT_NUMBER AS CUSTOMER_NUMBER,
         CDD.COST_CENTER_CODE AS STORE,
         CDD.TRANSACTION_TYPE TRAN_TYPE,
         CDD.TRANSACTION_NUMBER TRANS_NBR,
         CDD.TERMINAL_NUMBER,
         POS_TRANSACTION_CODE,
         CDD.TRANSACTION_DATE TRAN_DATE,
         CDD.TRAN_TIMESTAMP,
         CDD.CSTMR_DPST_SALES_LN_ITM_AMT,
         CDD.CUSTOMER_NET_BALANCE AS CUST_REM_BALANCE,
         CDR.ORIGINAL_DEP_TRANS_NBR,
         CDR.ORIGINAL_DEP_TERM_NBR,
         CDR.ORIGINAL_DEP_TRAN_DATE,
         REFERENCE_NUMBER,
         CLEARED_REASON,
         NOTES,
         CLOSED_DATE,
         GL_DIVISION
  FROM CUSTOMER_DEPOSIT_DETAILS CDD,
       CUST_DEP_REDEMPTION_DETAILS CDR
 WHERE CDD.CUSTOMER_ACCOUNT_NUMBER = CDR.CUSTOMER_ACCOUNT_NUMBER (+)
   AND CDD.TRANSACTION_DATE        = CDR.TRANSACTION_DATE(+)
   AND CDD.TERMINAL_NUMBER         = CDR.TERMINAL_NUMBER(+)
   AND CDD.TRANSACTION_NUMBER      = CDR.TRANSACTION_NUMBER(+)
   AND CDD.COST_CENTER_CODE        = CDR.COST_CENTER_CODE (+)
 ORDER BY CDD.CUSTOMER_ACCOUNT_NUMBER, CDD.TRAN_TIMESTAMP;
