/*
     Created: 04/30/2018 sxh487 CCN Project Team..
     This script creates a new table CUST_DEP_CREDIT_DETAILS 
     for storing the deposit remaining balance
*/
CREATE TABLE CUST_DEP_CREDIT_DETAILS 
   (	CREDIT_ID                 NUMBER,    
	COST_CENTER_CODE          VARCHAR2(6),
	CUSTOMER_ACCOUNT_NUMBER   VARCHAR2(9),
	TRANSACTION_NUMBER        VARCHAR2(5),
	TRANSACTION_DATE          DATE,
	TERMINAL_NUMBER           VARCHAR2(5),
	DEPOSIT_REMAINING_BAL     NUMBER,
	LOAD_DATE                 DATE,
	TRAN_TIMESTAMP            TIMESTAMP(6),
	CONSTRAINT CUST_DEP_CREDIT_DETAILS_PK PRIMARY KEY (CREDIT_ID),
	CONSTRAINT CUST_DEP_CREDIT_DETAILS_FK FOREIGN KEY (COST_CENTER_CODE,TRANSACTION_DATE,TERMINAL_NUMBER,TRANSACTION_NUMBER,CUSTOMER_ACCOUNT_NUMBER)
	 REFERENCES CSTMR_DPSTS.CUSTOMER_DEPOSIT_DETAILS (COST_CENTER_CODE,TRANSACTION_DATE,TERMINAL_NUMBER,TRANSACTION_NUMBER,CUSTOMER_ACCOUNT_NUMBER)
   );
