/***************************************************
This script to update databse Tables/Indexes/CONSTRAINTS. for Customer deposit changes.  

Created : 11/27/2018 sxg151 CCN Project Team....
        : ASP-1150
***************************************************/

-- Add Column  "TRANSACTION_SQ_ID"
 
 ALTER TABLE CUSTOMER_DEPOSIT_DETAILS
    ADD TRANSACTION_SQ_ID NUMBER;
 
 ALTER TABLE CUSTOMER_DEPOSIT_DETAILS_HIST
    ADD TRANSACTION_SQ_ID NUMBER;
 
 ALTER TABLE CUST_DEP_REDEMPTION_DETAILS
    ADD TRANSACTION_SQ_ID NUMBER;
 
 ALTER TABLE CUST_DEP_CREDIT_DETAILS
    ADD TRANSACTION_SQ_ID NUMBER;
 
 -- Create SEQUENCE on TRANSACTION_SQ_ID
 
 CREATE SEQUENCE TRANSACTION_SQ_ID  MINVALUE 0 MAXVALUE 999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE;
 
 
 -- Drop F.K Before dropping the P.K check for the Chaild tables and drop the F.K
  
select * from all_constraints 
where constraint_type='R'
and r_constraint_name='CUSTOMER_DEPOSIT_DETAILS_PK';

ALTER TABLE CUST_DEP_CREDIT_DETAILS 
    DROP CONSTRAINT CUST_DEP_CREDIT_DETAILS_FK;

ALTER TABLE CUST_DEP_REDEMPTION_DETAILS 
    DROP CONSTRAINT CUST_DEP_REDEMPTION_DETAILS_FK;

--CREATE P.K 

-- Note * Create the below P.K After executing the anonymous script which will load the data into TRANSACTION_SQ_ID field.

ALTER TABLE CUSTOMER_DEPOSIT_DETAILS
    ADD CONSTRAINT CUSTOMER_DEPOSIT_DETAILS_PK PRIMARY KEY (TRANSACTION_SQ_ID);

-- Add F.K 

ALTER TABLE         CUST_DEP_CREDIT_DETAILS
    ADD CONSTRAINT  CUST_DEP_CREDIT_DETAILS_FK FOREIGN KEY (TRANSACTION_SQ_ID)
        REFERENCES  CUSTOMER_DEPOSIT_DETAILS(TRANSACTION_SQ_ID);
 
 ALTER TABLE         CUST_DEP_REDEMPTION_DETAILS
    ADD CONSTRAINT  CUST_DEP_REDEMPTION_DETAILS_FK FOREIGN KEY (TRANSACTION_SQ_ID)
        REFERENCES  CUSTOMER_DEPOSIT_DETAILS(TRANSACTION_SQ_ID);
		
-- Create Index on CUST_DEP_CREDIT_DETAILS and

CREATE INDEX CUST_DEP_CREDIT_DETAILS_INDEX2 ON CUST_DEP_CREDIT_DETAILS (COST_CENTER_CODE, CUSTOMER_ACCOUNT_NUMBER, TRANSACTION_NUMBER, TRANSACTION_DATE, TERMINAL_NUMBER);

CREATE INDEX CUST_DEP_REDEMPTION_DETAILS_I1 ON CUST_DEP_REDEMPTION_DETAILS (COST_CENTER_CODE, CUSTOMER_ACCOUNT_NUMBER, TRANSACTION_NUMBER, TRANSACTION_DATE, TERMINAL_NUMBER);
