/*
This script grant access to execute the "CUST_DEP_UI_INTERFACE_APP_PKG" package to CSTMR_DPSTS_USR
and create a synonym on CSTMR_DPSTS_USR schema
*/
GRANT EXECUTE ON CUST_DEP_UI_INTERFACE_APP_PKG TO CSTMR_DPSTS_USR;

CREATE OR REPLACE SYNONYM CSTMR_DPSTS_USR.CUST_DEP_UI_INTERFACE_APP_PKG FOR CSTMR_DPSTS.CUST_DEP_UI_INTERFACE_APP_PKG;