-- Create SYNONYM for CCN_UTILITY.CCN_BATCH_PKG
--   Run in CSTMR_DPSTS
-- created by sxg151 on 01/15/2019

CREATE OR REPLACE SYNONYM CCN_BATCH_PKG FOR CCN_UTILITY.CCN_BATCH_PKG;

CREATE OR REPLACE SYNONYM BATCH_JOB FOR CCN_UTILITY.BATCH_JOB;