
  CREATE OR REPLACE VIEW ADDRESS_VW AS 
  WITH T AS (SELECT COST_CENTER_CODE AS COST_CENTER_CD,
                  DECODE(CATEGORY,
                         'T',
                         (SELECT NVL(HOME_STORE, COST_CENTER_CODE)
                            FROM TERRITORY
                           WHERE COST_CENTER_CODE = C.COST_CENTER_CODE),
                         COST_CENTER_CODE) CC_CODE
             FROM COST_CENTER C)
  SELECT
  /*********************************************************** 
  This view will have all the address information for all teh cost centers
  created  : 09/14/2015
  modified : 09/14/2015 nxk927 
             added the active flag 
		   : 09/17/2015 jxc527 
		     query changed to handle Territory store's address.
		   : 11/24/2015 nxk927 
             corrected the active spelling 
		   : 11/24/2015 nxk927 
			 added ADMIN_COST_CNTR_TYPE column
  ************************************************************/
T.COST_CENTER_CD AS COST_CENTER_CODE
,(SELECT ADMIN_COST_CNTR_TYPE FROM ADMINISTRATION WHERE COST_CENTER_CODE = T.COST_CENTER_CD) COST_CNTR_TYPE
,ADDRESS_TYPE
,DECODE(EXPIRATION_DATE, NULL, 'Y', 'N') ACTIVE_FLAG
,NVL(CCN_PICK_LIST_PKG.GET_CODE_DETAIL_VALUE_DSCRPTN('ADDRESS_TYPE','COD',ADDRESS_TYPE),'N/A') ADDRESS_TYPE_DESCRIPTION
,EFFECTIVE_DATE
,EXPIRATION_DATE
,ADDRESS_LINE_1
,ADDRESS_LINE_2
,ADDRESS_LINE_3
,CITY
,PROVINCE_CODE
,NULL AS PROVINCE_CODE_DESCRIPTION
,STATE_CODE
,NVL(CCN_PICK_LIST_PKG.GET_CODE_DETAIL_VALUE_DSCRPTN('STATE_CODE','COD',STATE_CODE),'N/A') STATE_CODE_DESCRIPTION
,POSTAL_CODE
,NULL AS ZIP_CODE
,NULL AS ZIP_CODE_4
,NULL AS COUNTY
,NULL AS FIPS_CODE
,NULL AS DESTINATION_POINT
,NULL AS CHECK_DIGIT
,VALID_ADDRESS
,COUNTRY_CODE
,NVL(CCN_PICK_LIST_PKG.GET_CODE_DETAIL_VALUE_DSCRPTN('COUNTRY_CODE','COD',COUNTRY_CODE),'N/A') COUNTRY_CODE_DESCRIPTION
 FROM ADDRESS_OTHER, T WHERE COST_CENTER_CODE = CC_CODE
UNION ALL
SELECT
T.COST_CENTER_CD AS COST_CENTER_CODE
,(SELECT ADMIN_COST_CNTR_TYPE FROM ADMINISTRATION WHERE COST_CENTER_CODE = T.COST_CENTER_CD) COST_CNTR_TYPE
,ADDRESS_TYPE
,DECODE(EXPIRATION_DATE, NULL, 'Y', 'N') ACTIVE_FLAG
,NVL(CCN_PICK_LIST_PKG.GET_CODE_DETAIL_VALUE_DSCRPTN('ADDRESS_TYPE','COD',ADDRESS_TYPE),'N/A') ADDRESS_TYPE_DESCRIPTION
,EFFECTIVE_DATE
,EXPIRATION_DATE
,ADDRESS_LINE_1
,ADDRESS_LINE_2
,ADDRESS_LINE_3
,CITY
,NULL AS PROVINCE_CODE
,NULL AS PROVINCE_CODE_DESCRIPTION
,STATE_CODE
,NVL(CCN_PICK_LIST_PKG.GET_CODE_DETAIL_VALUE_DSCRPTN('STATE_CODE','COD',STATE_CODE),'N/A') STATE_CODE_DESCRIPTION
,NULL AS POSTAL_CODE
,ZIP_CODE
,ZIP_CODE_4
,COUNTY
,FIPS_CODE
,DESTINATION_POINT
,CHECK_DIGIT
,VALID_ADDRESS
,COUNTRY_CODE
,NVL(CCN_PICK_LIST_PKG.GET_CODE_DETAIL_VALUE_DSCRPTN('COUNTRY_CODE','COD',COUNTRY_CODE),'N/A') COUNTRY_CODE_DESCRIPTION
FROM ADDRESS_USA, T WHERE COST_CENTER_CODE = CC_CODE
UNION ALL
SELECT 
T.COST_CENTER_CD AS COST_CENTER_CODE
,(SELECT ADMIN_COST_CNTR_TYPE FROM ADMINISTRATION WHERE COST_CENTER_CODE = T.COST_CENTER_CD) COST_CNTR_TYPE
,ADDRESS_TYPE
,DECODE(EXPIRATION_DATE, NULL, 'Y', 'N') ACTIVE_FLAG
,NVL(CCN_PICK_LIST_PKG.GET_CODE_DETAIL_VALUE_DSCRPTN('ADDRESS_TYPE','COD',ADDRESS_TYPE),'N/A') ADDRESS_TYPE_DESCRIPTION
,EFFECTIVE_DATE
,EXPIRATION_DATE
,ADDRESS_LINE_1
,ADDRESS_LINE_2
,ADDRESS_LINE_3
,CITY
,PROVINCE_CODE
,NVL(CCN_PICK_LIST_PKG.GET_CODE_DETAIL_VALUE_DSCRPTN('PROVINCE_CODE_CAN','COD',PROVINCE_CODE),'N/A') PROVINCE_CODE_DESCRIPTION
,NULL AS STATE_CODE
,NULL AS STATE_CODE_DESCRIPTION
,POSTAL_CODE
,NULL AS ZIP_CODE
,NULL AS ZIP_CODE_4
,NULL AS COUNTY
,NULL AS FIPS_CODE
,NULL AS DESTINATION_POINT
,NULL AS CHECK_DIGIT
,VALID_ADDRESS
,COUNTRY_CODE
,NVL(CCN_PICK_LIST_PKG.GET_CODE_DETAIL_VALUE_DSCRPTN('COUNTRY_CODE','COD',COUNTRY_CODE),'N/A') COUNTRY_CODE_DESCRIPTION
FROM ADDRESS_CAN, T WHERE COST_CENTER_CODE = CC_CODE
UNION ALL 
SELECT 
T.COST_CENTER_CD AS COST_CENTER_CODE
,(SELECT ADMIN_COST_CNTR_TYPE FROM ADMINISTRATION WHERE COST_CENTER_CODE = T.COST_CENTER_CD) COST_CNTR_TYPE
,ADDRESS_TYPE
,DECODE(EXPIRATION_DATE, NULL, 'Y', 'N') ACTIVE_FLAG
,NVL(CCN_PICK_LIST_PKG.GET_CODE_DETAIL_VALUE_DSCRPTN('ADDRESS_TYPE','COD',ADDRESS_TYPE),'N/A') ADDRESS_TYPE_DESCRIPTION
,EFFECTIVE_DATE
,EXPIRATION_DATE
,ADDRESS_LINE_1
,ADDRESS_LINE_2
,ADDRESS_LINE_3
,CITY
,PROVINCE_CODE
,NVL(CCN_PICK_LIST_PKG.GET_CODE_DETAIL_VALUE_DSCRPTN('PROVINCE_CODE_MEX','COD',PROVINCE_CODE),'N/A') PROVINCE_CODE_DESCRIPTION
,NULL AS STATE_CODE
,NULL AS STATE_CODE_DESCRIPTION
,POSTAL_CODE
,NULL AS ZIP_CODE
,NULL AS ZIP_CODE_4
,NULL AS COUNTY
,NULL AS FIPS_CODE
,NULL AS DESTINATION_POINT
,NULL AS CHECK_DIGIT
,VALID_ADDRESS
,COUNTRY_CODE
,NVL(CCN_PICK_LIST_PKG.GET_CODE_DETAIL_VALUE_DSCRPTN('COUNTRY_CODE','COD',COUNTRY_CODE),'N/A') COUNTRY_CODE_DESCRIPTION
FROM ADDRESS_MEX, T WHERE COST_CENTER_CODE = CC_CODE;