CREATE TABLE ADDRESS_BRB(
      COST_CENTER_CODE VARCHAR2(6) DEFAULT NULL NOT NULL ENABLE, 
      ADDRESS_TYPE     VARCHAR2(2) NOT NULL ENABLE, 
      EFFECTIVE_DATE   DATE NOT NULL ENABLE, 
      EXPIRATION_DATE  DATE, 
      PREMISES         VARCHAR2(50), 
      AVENUE_LANE      VARCHAR2(50), 
      DISTRICT         VARCHAR2(50), 
      PARISH           VARCHAR2(25), 
      POSTAL_CODE      VARCHAR2(7), 
      VALID_ADDRESS    VARCHAR2(1), 
      COUNTRY_CODE     VARCHAR2(3) DEFAULT 'BRB', 
      CONSTRAINT ADDRESS_BRB_PK PRIMARY KEY (ADDRESS_TYPE, EFFECTIVE_DATE, COST_CENTER_CODE),
      CONSTRAINT COST_CENTER_ADDRESS_BRB FOREIGN KEY (COST_CENTER_CODE) REFERENCES COST_CENTER (COST_CENTER_CODE) ENABLE
);

