CREATE OR REPLACE FORCE VIEW "COSTCNTR"."ADMIN_TO_SALES_DIST_HRCHY_VW" ("STATEMENT_TYPE", "STATEMENT_TYPE_DESCRIPTION", "HRCHY_HDR_NAME", "COST_CENTER_CODE", "HRCHY_DTL_EFF_DATE", "HRCHY_DTL_EXP_DATE", "DOMAIN", "GROUP", "DIVISION", "AREA", "DISTRICT", "CITY_SALES_MANAGER", "ZONE", "SPECIAL_ROLES", "DOMAIN_NAME", "GROUP_NAME", "DIVISION_NAME", "AREA_NAME", "DISTRICT_NAME", "CITY_SALES_MANAGER_NAME", "ZONE_NAME", "SPECIAL_ROLES_NAME", "COST_CENTER_NAME") AS 
SELECT 
/*******************************************************************************
This View will give all the details of Admin_to_sales_district hierarchies for linked to the cost center
Created  : 10/28/2015 SXG151 CCN 
*******************************************************************************/ 
"STATEMENT_TYPE",
"STATEMENT_TYPE_DESCRIPTION",
"HRCHY_HDR_NAME",
"COST_CENTER_CODE",
"HRCHY_DTL_EFF_DATE",
"HRCHY_DTL_EXP_DATE",
"DOMAIN",
"GROUP",
"DIVISION",
"AREA",
"DISTRICT",
"CITY_SALES_MANAGER",
"ZONE",
"SPECIAL_ROLES",
"DOMAIN_NAME",
"GROUP_NAME",
"DIVISION_NAME",
"AREA_NAME",
"DISTRICT_NAME",
"CITY_SALES_MANAGER_NAME",
"ZONE_NAME",
"SPECIAL_ROLES_NAME",
"COST_CENTER_NAME" 
FROM ADMIN_TO_SALES_HIERARCHY_VW
WHERE HRCHY_HDR_NAME = 'ADMIN_TO_SALES_DISTRICT';