/*
Created : nxk927 CCN Project...
          ALtering the column size address tables
*/
ALTER TABLE ADDRESS_USA MODIFY ADDRESS_LINE_1 VARCHAR2(100);
ALTER TABLE ADDRESS_USA MODIFY ADDRESS_LINE_2 VARCHAR2(100);
ALTER TABLE ADDRESS_USA MODIFY ADDRESS_LINE_3 VARCHAR2(100);


ALTER TABLE ADDRESS_CAN MODIFY ADDRESS_LINE_1 VARCHAR2(100);
ALTER TABLE ADDRESS_CAN MODIFY ADDRESS_LINE_2 VARCHAR2(100);
ALTER TABLE ADDRESS_CAN MODIFY ADDRESS_LINE_3 VARCHAR2(100);


ALTER TABLE ADDRESS_MEX MODIFY ADDRESS_LINE_1 VARCHAR2(100);
ALTER TABLE ADDRESS_MEX MODIFY ADDRESS_LINE_2 VARCHAR2(100);
ALTER TABLE ADDRESS_MEX MODIFY ADDRESS_LINE_3 VARCHAR2(100);

ALTER TABLE ADDRESS_OTHER MODIFY ADDRESS_LINE_1 VARCHAR2(100);
ALTER TABLE ADDRESS_OTHER MODIFY ADDRESS_LINE_2 VARCHAR2(100);
ALTER TABLE ADDRESS_OTHER MODIFY ADDRESS_LINE_3 VARCHAR2(100);

ALTER TABLE ARC_ADDRESS_CAN MODIFY ADDRESS_LINE_1 VARCHAR2(100);
ALTER TABLE ARC_ADDRESS_CAN MODIFY ADDRESS_LINE_2 VARCHAR2(100);
ALTER TABLE ARC_ADDRESS_CAN MODIFY ADDRESS_LINE_3 VARCHAR2(100);


ALTER TABLE ARC_ADDRESS_MEX MODIFY ADDRESS_LINE_1 VARCHAR2(100);
ALTER TABLE ARC_ADDRESS_MEX MODIFY ADDRESS_LINE_2 VARCHAR2(100);
ALTER TABLE ARC_ADDRESS_MEX MODIFY ADDRESS_LINE_3 VARCHAR2(100);


ALTER TABLE ARC_ADDRESS_OTHER MODIFY ADDRESS_LINE_1 VARCHAR2(100);
ALTER TABLE ARC_ADDRESS_OTHER MODIFY ADDRESS_LINE_2 VARCHAR2(100);
ALTER TABLE ARC_ADDRESS_OTHER MODIFY ADDRESS_LINE_3 VARCHAR2(100);

ALTER TABLE ARC_ADDRESS_USA MODIFY ADDRESS_LINE_1 VARCHAR2(100);
ALTER TABLE ARC_ADDRESS_USA MODIFY ADDRESS_LINE_2 VARCHAR2(100);
ALTER TABLE ARC_ADDRESS_USA MODIFY ADDRESS_LINE_3 VARCHAR2(100);