--Script to create table to store the additional fields to include in the audit process
  CREATE TABLE "COSTCNTR"."CCN_ADDITIONAL_AUDIT_FIELDS" 
   (	"TABLE_NAME" VARCHAR2(30 BYTE), 
	"COLUMN_NAME" VARCHAR2(30 BYTE), 
	"DATA_TYPE" VARCHAR2(30 BYTE), 
	"DATA_LENGTH" NUMBER, 
	"COLUMN_ID" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "COSTCNTR_DATA" ;




--Script to create table to store the tables that we exclude in the audit process  
  CREATE TABLE "COSTCNTR"."CCN_AUDIT_EXCLUDED_TABLES" 
   (	"TABLE_NAME" VARCHAR2(30 BYTE), 
	"EXCLUDED_INDICATOR" VARCHAR2(1 BYTE), 
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "COSTCNTR_DATA" ;

--index for Audit log table  
CREATE INDEX INDEX_TRANSACTION_DATE ON AUDIT_LOG(TRANSACTION_DATE);