/*
Below grants and synonyms are needed for batch job execution

Created : 11/7/2019 jxc517 CCN Project Team....
Changed :
*/

GRANT EXECUTE ON CCN_BATCH_PROCESS               to CCNUSER;
CREATE OR REPLACE SYNONYM CCNUSER.CCN_BATCH_PROCESS FOR COSTCNTR.CCN_BATCH_PROCESS;

GRANT EXECUTE ON CCN_HIERARCHY_FUT_TO_CURR_PKG   to CCNUSER;
CREATE OR REPLACE SYNONYM CCNUSER.CCN_HIERARCHY_FUT_TO_CURR_PKG FOR COSTCNTR.CCN_HIERARCHY_FUT_TO_CURR_PKG;

GRANT EXECUTE ON CCN_RESTRICTION_PKG             to CCNUSER;
CREATE OR REPLACE SYNONYM CCNUSER.CCN_RESTRICTION_PKG FOR COSTCNTR.CCN_RESTRICTION_PKG;
