--------------------------------------------------------
--  File created - Tuesday-March-18-2014   
--------------------------------------------------------
---------------------------
--New VIEW
--COST_CENTER_VW
---------------------------
CREATE OR REPLACE FORCE VIEW "COSTCNTR"."COST_CENTER_VW" 
 ( "COST_CENTER_CODE", "COST_CENTER_NAME", "CATEGORY", "STATEMENT_TYPE", "COUNTRY_CODE", "BEGIN_DATE", "OPEN_DATE", "MOVE_DATE", "CLOSE_DATE", "MISSION_TYPE_CODE", "DUNS_NUMBER"
  )  AS 
  SELECT COST_CENTER_CODE, COST_CENTER_NAME, CATEGORY, 
STATEMENT_TYPE,
COUNTRY_CODE,
BEGIN_DATE,
OPEN_DATE,
MOVE_DATE,
CLOSE_DATE,
MISSION_TYPE_CODE,
DUNS_NUMBER
from cost_center;
---------------------------
--New VIEW
--ADDRESS_VW
---------------------------
CREATE OR REPLACE FORCE VIEW "COSTCNTR"."ADDRESS_VW" 
 ( "COST_CENTER_CODE", "ADDRESS_TYPE", "EFFECTIVE_DATE", "EXPIRATION_DATE", "ADDRESS_LINE_1", "ADDRESS_LINE_2", "ADDRESS_LINE_3", "CITY", "PROVINCE_CODE", "STATE_CODE", "POSTAL_CODE", "ZIP_CODE", "ZIP_CODE_4", "COUNTY", "FIPS_CODE", "DESTINATION_POINT", "CHECK_DIGIT", "VALID_ADDRESS", "COUNTRY_CODE"
  )  AS 
  SELECT COST_CENTER_CODE
,ADDRESS_TYPE
,EFFECTIVE_DATE
,EXPIRATION_DATE
,ADDRESS_LINE_1
,ADDRESS_LINE_2
,ADDRESS_LINE_3
,CITY
,PROVINCE_CODE
,STATE_CODE
,POSTAL_CODE
,NULL AS ZIP_CODE
,NULL AS ZIP_CODE_4
,NULL AS COUNTY
,NULL AS FIPS_CODE
,NULL AS DESTINATION_POINT
,NULL AS CHECK_DIGIT
,VALID_ADDRESS
,COUNTRY_CODE
 FROM ADDRESS_OTHER

UNION

SELECT
COST_CENTER_CODE
,ADDRESS_TYPE
,EFFECTIVE_DATE
,EXPIRATION_DATE
,ADDRESS_LINE_1
,ADDRESS_LINE_2
,ADDRESS_LINE_3
,CITY
,NULL AS PROVINCE_CODE
,STATE_CODE
,NULL AS POSTAL_CODE
,ZIP_CODE
,ZIP_CODE_4
,COUNTY
,FIPS_CODE
,DESTINATION_POINT
,CHECK_DIGIT
,VALID_ADDRESS
,COUNTRY_CODE
FROM ADDRESS_USA

UNION

SELECT 
COST_CENTER_CODE
,ADDRESS_TYPE
,EFFECTIVE_DATE
,EXPIRATION_DATE
,ADDRESS_LINE_1
,ADDRESS_LINE_2
,ADDRESS_LINE_3
,CITY
,PROVINCE_CODE
,NULL AS STATE_CODE
,POSTAL_CODE
,NULL AS ZIP_CODE
,NULL AS ZIP_CODE_4
,NULL AS COUNTY
,NULL AS FIPS_CODE
,NULL AS DESTINATION_POINT
,NULL AS CHECK_DIGIT
,VALID_ADDRESS
,COUNTRY_CODE
FROM ADDRESS_CAN

UNION 
SELECT 
COST_CENTER_CODE
,ADDRESS_TYPE
,EFFECTIVE_DATE
,EXPIRATION_DATE
,ADDRESS_LINE_1
,ADDRESS_LINE_2
,ADDRESS_LINE_3
,CITY
,PROVINCE_CODE
,NULL AS STATE_CODE
,POSTAL_CODE
,NULL AS ZIP_CODE
,NULL AS ZIP_CODE_4
,NULL AS COUNTY
,NULL AS FIPS_CODE
,NULL AS DESTINATION_POINT
,NULL AS CHECK_DIGIT
,VALID_ADDRESS
,COUNTRY_CODE
FROM ADDRESS_MEX;
