--WITH ROWID INCLUDING NEW VALUES : This clause is to have fast refresh
--TYPE
---------------------------
CREATE MATERIALIZED VIEW LOG ON "COSTCNTR"."TYPE" WITH ROWID INCLUDING NEW VALUES;
--TERMINAL
---------------------------
CREATE MATERIALIZED VIEW LOG ON "COSTCNTR"."TERMINAL" WITH ROWID INCLUDING NEW VALUES;
--TAXWARE
---------------------------
CREATE MATERIALIZED VIEW LOG ON "COSTCNTR"."TAXWARE" WITH ROWID INCLUDING NEW VALUES;
--STORE
---------------------------
CREATE MATERIALIZED VIEW LOG ON "COSTCNTR"."STORE" WITH ROWID INCLUDING NEW VALUES;
--STATUS
---------------------------
CREATE MATERIALIZED VIEW LOG ON "COSTCNTR"."STATUS" WITH ROWID INCLUDING NEW VALUES;
--POLLING
---------------------------
CREATE MATERIALIZED VIEW LOG ON "COSTCNTR"."POLLING" WITH ROWID INCLUDING NEW VALUES;
--PHONE
---------------------------
CREATE MATERIALIZED VIEW LOG ON "COSTCNTR"."PHONE" WITH ROWID INCLUDING NEW VALUES;
--MARKETING
---------------------------
CREATE MATERIALIZED VIEW LOG ON "COSTCNTR"."MARKETING" WITH ROWID INCLUDING NEW VALUES;
--COST_CENTER
---------------------------
CREATE MATERIALIZED VIEW LOG ON "COSTCNTR"."COST_CENTER" WITH ROWID INCLUDING NEW VALUES;
--BANK_CARD
---------------------------
CREATE MATERIALIZED VIEW LOG ON "COSTCNTR"."BANK_CARD" WITH ROWID INCLUDING NEW VALUES;
--ADDRESS_USA
---------------------------
CREATE MATERIALIZED VIEW LOG ON "COSTCNTR"."ADDRESS_USA" WITH ROWID INCLUDING NEW VALUES;
--ADDRESS_OTHER
---------------------------
CREATE MATERIALIZED VIEW LOG ON "COSTCNTR"."ADDRESS_OTHER" WITH ROWID INCLUDING NEW VALUES;
--ADDRESS_MEX
---------------------------
CREATE MATERIALIZED VIEW LOG ON "COSTCNTR"."ADDRESS_MEX" WITH ROWID INCLUDING NEW VALUES;
--ADDRESS_CAN
---------------------------
CREATE MATERIALIZED VIEW LOG ON "COSTCNTR"."ADDRESS_CAN" WITH ROWID INCLUDING NEW VALUES;
