--------------------------------------------------------
--  File created - Friday-February-28-2014   
--------------------------------------------------------
---------------------------
--Changed TABLE
--HIERARCHY_HEADER
---------------------------
ALTER TABLE "COSTCNTR"."HIERARCHY_HEADER" ADD ("ALL_APPLICABLE_ATTRIBUTES" "PUBLIC"."XMLTYPE");

---------------------------
--New TABLE
--COST_CENTER_COPY
---------------------------
  CREATE TABLE "COSTCNTR"."COST_CENTER_COPY" 
   (	"COST_CENTER_CODE_OLD" VARCHAR2(6),
	"COST_CENTER_CODE_NEW" VARCHAR2(6)
   ) ORGANIZATION EXTERNAL
  ( TYPE ORACLE_LOADER
    DEFAULT DIRECTORY "CCN_LOAD_FILES"
    ACCESS PARAMETERS 
    ( RECORDS DELIMITED BY NEWLINE SKIP 1 badfile "CCN_LOAD_FILES":'
    COST_CENTER_COPY.bad' logfile "CCN_LOAD_FILES":'
    COST_CENTER_COPY.log' FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY
    '"' LDRTRIM MISSING FIELD VALUES ARE NULL(COST_CENTER_CODE_OLD,COST_CENTER_CODE_NEW)
      ) 
    LOCATION 
    ( 'COST_CENTER_COPY.csv'
    ) 
  ) 
  REJECT LIMIT UNLIMITED;
---------------------------
--Changed TABLE
--CCN_DISCDMN
---------------------------
ALTER TABLE "COSTCNTR"."CCN_DISCDMN" ADD CONSTRAINT "CCN_DISCDMN_PK" PRIMARY KEY ("CRSTC_NAME","CRSTC_CODE","DISC_CODE") ENABLE;
ALTER TABLE "COSTCNTR"."CCN_DISCDMN" ADD CONSTRAINT "CCN_DISCDMN_CCN_CRSTC_FK1" FOREIGN KEY ("CRSTC_NAME","CRSTC_CODE") REFERENCES "COSTCNTR"."CCN_CRSTC"("CRSTC_NAME","CRSTC_CODE") ENABLE;

---------------------------
--Changed TABLE
--CCN_CRSTC
---------------------------
ALTER TABLE "COSTCNTR"."CCN_CRSTC" ADD CONSTRAINT "CCN_CRSTC_PK" PRIMARY KEY ("CRSTC_NAME","CRSTC_CODE") ENABLE;

