/*
     Created: 06/26/2017 axt754 CCN Project Team..
     This script creates a new table CCN_ACCOUNTING_TBL for ccn 
     accounting view report
*/

CREATE TABLE CCN_ACCOUNTING_TBL
 (COST_CENTER_CODE          VARCHAR2(6)
  ,COST_CENTER_NAME         VARCHAR2(35)
  ,"CATEGORY"               VARCHAR2(1)
  ,CATEGORY_DESC            VARCHAR2(100)
  ,ACQUISITION_CODE         VARCHAR2(2)
  ,ACQUISITION_CODE_DESC    VARCHAR2(100)
  ,STATEMENT_TYPE           VARCHAR2(2)
  ,STATEMENT_TYPE_DESC      VARCHAR2(100)
  ,MISSION_TYPE_CODE        VARCHAR2(2)
  ,MISSION_TYPE_CODE_DESC   VARCHAR2(100)
  ,OPEN_DATE                DATE
  ,CLOSE_DATE               DATE
  ,CURRENCY_CODE            VARCHAR2(3)
  ,CURRENCY_CODE_DESC       VARCHAR2(100)
  ,MKT_MISSION              VARCHAR2(3)
  ,MKT_MISSION_DESC         VARCHAR2(100)
  ,MKT_SALES_FLOOR_SIZE     VARCHAR2(2)
  ,MKT_SALES_FLOOR_SIZE_DESC VARCHAR2(100)
  ,MKT_WAREHOUSE_SIZE       VARCHAR2(2)
  ,MKT_WAREHOUSE_SIZE_DESC  VARCHAR2(100)
  ,STATE_CODE               VARCHAR2(2)
  ,STATE_DESCRIPTION        VARCHAR2(100)
  ,PROVINCE_CODE            VARCHAR2(2)
  ,PROVINCE_DESCRIPTION     VARCHAR2(100)
  ,DOMAIN                   VARCHAR2(100)
  ,DOMAIN_NAME              VARCHAR2(100)
  ,"GROUP"                  VARCHAR2(100)
  ,GROUP_NAME               VARCHAR2(100)
  ,DIVISION                 VARCHAR2(100)
  ,DIVISION_NAME            VARCHAR2(100)
  ,AREA                     VARCHAR2(100)
  ,AREA_NAME                VARCHAR2(100)
  ,DISTRICT                 VARCHAR2(100)
  ,DISTRICT_NAME            VARCHAR2(100)
  ,CITY_SALES_MGR           VARCHAR2(100)
  ,CITY_SALES_MGR_NAME      VARCHAR2(100)
  ,"ZONE"                   VARCHAR2(100)
  ,ZONE_NAME                VARCHAR2(100)
  ,SPECIAL_ROLES            VARCHAR2(100)
  ,SPECIAL_ROLES_NAME       VARCHAR2(100)
  ,SGL_DIVISION             VARCHAR2(100)
  ,SGL_DIVISION_NAME        VARCHAR2(100)
  ,COA_DIVISION             VARCHAR2(100)
  ,COA_DIVISION_NAME        VARCHAR2(100)
  ,DIV_MGR_NAME             VARCHAR2(100)
  ,AREA_MGR_NAME            VARCHAR2(100)
  ,DISTRICT_MGR_NAME        VARCHAR2(100)
  ,CITY_MGR_NAME            VARCHAR2(100)
  ,CC_MGR_NAME              VARCHAR2(100)
  ,LOAD_DATE                DATE
  ,CONSTRAINT CCN_APPLICATION_TBL_PK PRIMARY KEY(COST_CENTER_CODE,LOAD_DATE));