CREATE OR REPLACE VIEW COSTCNTR.CCN_PHONE_INFO_VW
AS 
SELECT DISTINCT CC.COST_CENTER_CODE   COST_CENTER_CODE,
                CC.COST_CENTER_NAME   COST_CENTER_DESCRIPTION,
                COSTCNTR.COMMON_TOOLS.GET_PHONE_NUMBER ( CC.COST_CENTER_CODE, 'PRI')  PRIMARY_PHONE_NUMBER,
                COSTCNTR.COMMON_TOOLS.GET_PHONE_NUMBER ( CC.COST_CENTER_CODE, 'SCD')  SECONDARY_PHONE_NUMBER,
                COSTCNTR.COMMON_TOOLS.GET_PHONE_NUMBER ( CC.COST_CENTER_CODE, 'FAX')  FAX_PHONE_NUMBER                
                FROM COSTCNTR.COST_CENTER CC;

				
CREATE OR REPLACE SYNONYM COSTCNTR.CCN_PHONE_INFO FOR COSTCNTR.CCN_PHONE_INFO_VW;