--Drop if table already exists
DROP TABLE MAILING_GROUP;
DROP TABLE MAILING_DETAILS;

--script to create MAILING_GROUP table
CREATE TABLE "COSTCNTR"."MAILING_GROUP"
  (
    "GROUP_ID" VARCHAR2(3 BYTE) NOT NULL ENABLE,
     "MAIL_ID" VARCHAR2(2000 BYTE), 
     CONSTRAINT "MAILING_GROUP_PK" PRIMARY KEY ("GROUP_ID") USING INDEX
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(INITIAL 65536
    NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1
    FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "COSTCNTR_DATA" ENABLE
  )
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0
    FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  TABLESPACE "COSTCNTR_DATA" ;
  
--script to create MAILING_DETAILS table
CREATE TABLE "COSTCNTR"."MAILING_DETAILS"
  (
    "MAIL_CATEGORY" VARCHAR2(100 BYTE),
    "GROUP_ID"      VARCHAR2(3 BYTE),
    "SUBJECT"       VARCHAR2(1000 BYTE), 
    "FROM_P"        VARCHAR2(1000 BYTE), 
    "MESSAGE"       VARCHAR2(4000 BYTE), 
    "SIGNATURE"     VARCHAR2(4000 BYTE), 
    CONSTRAINT "MAILING_DETAILS_FK1" FOREIGN KEY ("GROUP_ID") REFERENCES "COSTCNTR".
    "MAILING_GROUP" ("GROUP_ID") ENABLE
  )
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0
    FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  TABLESPACE "COSTCNTR_DATA" ;


  