--HIERARCHY_HEADER
---------------------------
ALTER TABLE "COSTCNTR"."HIERARCHY_HEADER" ADD ("STMNT_TYPE_VALIDATION_IND" VARCHAR2(1));

--ROLE_DETAILS
---------------------------
  CREATE TABLE "COSTCNTR"."ROLE_DETAILS" 
   (	"ROLE_CODE" VARCHAR2(6),
	"ROLE_DESCRIPTION" VARCHAR2(100),
	"ADMIN_FLAG" VARCHAR2(1),
	"INSERT_FLAG" VARCHAR2(1),
	"UPDATE_FLAG" VARCHAR2(1),
	"SELECT_FLAG" VARCHAR2(1),
	CONSTRAINT "ROLE_CODE_PK" PRIMARY KEY ("ROLE_CODE") ENABLE
   );

--Truncating this table
TRUNCATE TABLE SECURITY_MATRIX;

--SECURITY_MATRIX
---------------------------
ALTER TABLE "COSTCNTR"."SECURITY_MATRIX" ADD ("ROLE_CODE" VARCHAR2(4));
ALTER TABLE "COSTCNTR"."SECURITY_MATRIX" DROP ("ADMIN_FLAG");
ALTER TABLE "COSTCNTR"."SECURITY_MATRIX" DROP ("INSERT_FLAG");
ALTER TABLE "COSTCNTR"."SECURITY_MATRIX" DROP ("SELECT_FLAG");
ALTER TABLE "COSTCNTR"."SECURITY_MATRIX" DROP ("UPDATE_FLAG");
ALTER TABLE "COSTCNTR"."SECURITY_MATRIX" ADD CONSTRAINT "SECURITY_MATRIX_PK" PRIMARY KEY ("USER_ID","ROLE_CODE") ENABLE;
ALTER TABLE "COSTCNTR"."SECURITY_MATRIX" ADD CONSTRAINT "SECURITY_MATRIX_FK" FOREIGN KEY ("ROLE_CODE") REFERENCES "COSTCNTR"."ROLE_DETAILS"("ROLE_CODE") ENABLE;

--CODE_HEADER
---------------------------
ALTER TABLE "COSTCNTR"."CODE_HEADER" ADD ("CODE_HEADER_CREATE_USER" VARCHAR2(25));
ALTER TABLE "COSTCNTR"."CODE_HEADER" ADD ("CODE_HEADER_EFF_DATE" DATE);

--CODE_DETAIL
---------------------------
ALTER TABLE "COSTCNTR"."CODE_DETAIL" ADD ("CODE_DETAIL_CREATE_USER" VARCHAR2(25));
ALTER TABLE "COSTCNTR"."CODE_DETAIL" ADD ("CODE_DETAIL_EFF_DATE" DATE);

--HIERARCHY_DETAIL_TEST
---------------------------
  CREATE TABLE "COSTCNTR"."HIERARCHY_DETAIL_TEST" 
   (	"HRCHY_HDR_NAME" VARCHAR2(100) NOT NULL ENABLE,
	"HRCHY_DTL_LEVEL" VARCHAR2(2) NOT NULL ENABLE,
	"HRCHY_DTL_PREV_LVL_VAL" VARCHAR2(1000) NOT NULL DISABLE,
	"HRCHY_DTL_CURR_LVL_VAL" VARCHAR2(1000) NOT NULL ENABLE,
	"HRCHY_DTL_NEXT_LVL_VAL" VARCHAR2(1000) NOT NULL DISABLE,
	"HRCHY_DTL_EFF_DATE" DATE NOT NULL ENABLE,
	"HRCHY_DTL_EXP_DATE" DATE,
	"HRCHY_DTL_DESC" VARCHAR2(100),
	"HRCHY_DTL_CURR_ROW_VAL" VARCHAR2(100),
	"UPPER_LVL_VER_VALUE" "SYS"."XMLTYPE"
   )
 XMLTYPE COLUMN "UPPER_LVL_VER_VALUE"  STORE AS BASICFILE CLOB  (
  DISABLE STORAGE IN ROW);

--CCN_CRSTC
---------------------------
  CREATE TABLE "COSTCNTR"."CCN_CRSTC" 
   (	"CRSTC_NAME" VARCHAR2(30) NOT NULL ENABLE,
	"CRSTC_CODE" VARCHAR2(8) NOT NULL ENABLE,
	"CREATED_DATE" DATE,
	"USER_ID" VARCHAR2(8),
	"UPDATED_DATE" DATE
   );

--CCN_DISCDMN
---------------------------
  CREATE TABLE "COSTCNTR"."CCN_DISCDMN" 
   (	"CRSTC_NAME" VARCHAR2(30) NOT NULL ENABLE,
	"CRSTC_CODE" VARCHAR2(8) NOT NULL ENABLE,
	"DISC_NAME" VARCHAR2(15) NOT NULL ENABLE,
	"DISC_CODE" VARCHAR2(30) NOT NULL ENABLE,
	"CREATED_DATE" DATE,
	"USER_ID" VARCHAR2(8),
	"UPDATED_DATE" DATE
   );

--MAILING_GROUP
---------------------------
  CREATE TABLE "COSTCNTR"."MAILING_GROUP" 
   (	"GROUP_ID" VARCHAR2(100) NOT NULL ENABLE,
	"MAIL_ID" VARCHAR2(2000),
	CONSTRAINT "MAILING_GROUP_PK" PRIMARY KEY ("GROUP_ID") ENABLE
   );

--MAILING_DETAILS
---------------------------
  CREATE TABLE "COSTCNTR"."MAILING_DETAILS" 
   (	"SUBJECT" VARCHAR2(1000),
	"FROM_P" VARCHAR2(1000),
	"MESSAGE" VARCHAR2(4000),
	"GROUP_ID" VARCHAR2(20),
	"SIGNATURE" VARCHAR2(4000),
	CONSTRAINT "SH_MAIL_FK1" FOREIGN KEY ("GROUP_ID")
	 REFERENCES "COSTCNTR"."MAILING_GROUP" ("GROUP_ID") ENABLE
   );

--COST_CENTER_HIERARCHY
---------------------------
  CREATE TABLE "COSTCNTR"."COST_CENTER_HIERARCHY" 
   (	"COST_CENTER_CODE" VARCHAR2(6),
	"MANAGER_ID" VARCHAR2(20),
	"ADMIN_TO_SALES_AREA" VARCHAR2(100),
	"ADMIN_TO_SALES_DISTRICT" VARCHAR2(100),
	"ADMIN_TO_SALES_DIVISION" VARCHAR2(100),
	"ALTERNATE_DAD" VARCHAR2(100),
	"FACTS_DIVISION" VARCHAR2(100),
	"LEGACY_GL_DIVISION" VARCHAR2(100),
	"GLOBAL_HIERARCHY" VARCHAR2(100)
   ) ORGANIZATION EXTERNAL
  ( TYPE ORACLE_LOADER
    DEFAULT DIRECTORY "CCN_LOAD_FILES"
    ACCESS PARAMETERS 
    ( RECORDS DELIMITED BY NEWLINE SKIP 1 badfile "CCN_LOAD_FILES":'
    COST_CENTER_HIERARCHY.bad' logfile "CCN_LOAD_FILES":'
    COST_CENTER_HIERARCHY.log' FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY
    '"' LDRTRIM MISSING FIELD VALUES ARE NULL(COST_CENTER_CODE ,MANAGER_ID,
    ADMIN_TO_SALES_AREA, ADMIN_TO_SALES_DISTRICT, ADMIN_TO_SALES_DIVISION,
    ALTERNATE_DAD, FACTS_DIVISION, LEGACY_GL_DIVISION, GLOBAL_HIERARCHY)
  ) 
    LOCATION 
    ( 'COST_CENTER_HIERARCHY.csv'
    ) 
  ) 
  REJECT LIMIT UNLIMITED;

--HRCHY_DTL_CURR_ROW_VAL_INDEX
---------------------------
  CREATE INDEX "COSTCNTR"."HRCHY_DTL_CURR_ROW_VAL_INDEX" ON "COSTCNTR"."HIERARCHY_DETAIL" ("HRCHY_DTL_CURR_ROW_VAL");
