CREATE OR REPLACE VIEW COSTCNTR.CCN_PHONE_INFO_VW 
AS 
SELECT DISTINCT CC.COST_CENTER_CODE   COST_CENTER_CODE,
                CC.COST_CENTER_NAME   COST_CENTER_DESCRIPTION,
       (SELECT P.PHONE_AREA_CODE  P.PHONE_NUMBER
          FROM COSTCNTR.PHONE P
         WHERE P.PHONE_NUMBER_TYPE = 'PRI'
           AND P.COST_CENTER_CODE = CC.COST_CENTER_CODE) PRIMARY_PHONE_NUMBER,
       (SELECT P.PHONE_AREA_CODE P.PHONE_NUMBER
          FROM COSTCNTR.PHONE P
         WHERE P.PHONE_NUMBER_TYPE = 'SCD'
           AND P.COST_CENTER_CODE = CC.COST_CENTER_CODE) SECONDARY_PHONE_NUMBER,
       (SELECT P.PHONE_AREA_CODE P.PHONE_NUMBER
          FROM COSTCNTR.PHONE P
         WHERE P.PHONE_NUMBER_TYPE = 'FAX'
           AND P.COST_CENTER_CODE = CC.COST_CENTER_CODE) FAX_PHONE_NUMBER
  FROM COSTCNTR.COST_CENTER CC;
