/*
--Execute below script in Development and get the scripts everytime to compile in heigher user environments
SELECT 'CREATE OR REPLACE SYNONYM "'||USER||'"."'||SYNONYM_NAME||'" FOR "'||TABLE_OWNER||'"."'||TABLE_NAME||'";' FROM USER_SYNONYMS;
*/

CREATE OR REPLACE SYNONYM "CCNUSER"."ADDRESS_ALL_SYN" FOR "COSTCNTR"."ADDRESS_ALL";
CREATE OR REPLACE SYNONYM "CCNUSER"."HIERARCHY_DETAIL_VIEW" FOR "COSTCNTR"."HIERARCHY_DETAIL_VIEW";
CREATE OR REPLACE SYNONYM "CCNUSER"."COST_CENTER" FOR "COSTCNTR"."COST_CENTER";
CREATE OR REPLACE SYNONYM "CCNUSER"."ADDRESS_CAN" FOR "COSTCNTR"."ADDRESS_CAN";
CREATE OR REPLACE SYNONYM "CCNUSER"."COST_CENTER_VIEW_SYN" FOR "COSTCNTR"."COST_CENTER_VIEW";
CREATE OR REPLACE SYNONYM "CCNUSER"."POLLING_VIEW_SYN" FOR "COSTCNTR"."POLLING_VIEW";
CREATE OR REPLACE SYNONYM "CCNUSER"."ADDRESS_MEX" FOR "COSTCNTR"."ADDRESS_MEX";
CREATE OR REPLACE SYNONYM "CCNUSER"."ADDRESS_OTHER" FOR "COSTCNTR"."ADDRESS_OTHER";
CREATE OR REPLACE SYNONYM "CCNUSER"."ADDRESS_USA" FOR "COSTCNTR"."ADDRESS_USA";
CREATE OR REPLACE SYNONYM "CCNUSER"."ADMINISTRATION" FOR "COSTCNTR"."ADMINISTRATION";
CREATE OR REPLACE SYNONYM "CCNUSER"."OTHER" FOR "COSTCNTR"."OTHER";
CREATE OR REPLACE SYNONYM "CCNUSER"."PHONE" FOR "COSTCNTR"."PHONE";
CREATE OR REPLACE SYNONYM "CCNUSER"."REAL_ESTATE" FOR "COSTCNTR"."REAL_ESTATE";
CREATE OR REPLACE SYNONYM "CCNUSER"."STATUS" FOR "COSTCNTR"."STATUS";
CREATE OR REPLACE SYNONYM "CCNUSER"."STORE" FOR "COSTCNTR"."STORE";
CREATE OR REPLACE SYNONYM "CCNUSER"."POLLING" FOR "COSTCNTR"."POLLING";
CREATE OR REPLACE SYNONYM "CCNUSER"."TYPE" FOR "COSTCNTR"."TYPE";
CREATE OR REPLACE SYNONYM "CCNUSER"."BANK_CARD" FOR "COSTCNTR"."BANK_CARD";
CREATE OR REPLACE SYNONYM "CCNUSER"."POLLING_DWLD_RSN_HIST" FOR "COSTCNTR"."POLLING_DWLD_RSN_HIST";
CREATE OR REPLACE SYNONYM "CCNUSER"."TERMINAL" FOR "COSTCNTR"."TERMINAL";
CREATE OR REPLACE SYNONYM "CCNUSER"."SALES_REP" FOR "COSTCNTR"."SALES_REP";
CREATE OR REPLACE SYNONYM "CCNUSER"."TERRITORY_SALES_MGR" FOR "COSTCNTR"."TERRITORY_SALES_MGR";
CREATE OR REPLACE SYNONYM "CCNUSER"."TERRITORY" FOR "COSTCNTR"."TERRITORY";
CREATE OR REPLACE SYNONYM "CCNUSER"."TERRITORY_ASSIGNMENT" FOR "COSTCNTR"."TERRITORY_ASSIGNMENT";
CREATE OR REPLACE SYNONYM "CCNUSER"."CODE_HEADER" FOR "COSTCNTR"."CODE_HEADER";
CREATE OR REPLACE SYNONYM "CCNUSER"."CODE_DETAIL" FOR "COSTCNTR"."CODE_DETAIL";
CREATE OR REPLACE SYNONYM "CCNUSER"."HIERARCHY_HEADER" FOR "COSTCNTR"."HIERARCHY_HEADER";
CREATE OR REPLACE SYNONYM "CCNUSER"."HIERARCHY_DESCRIPTION" FOR "COSTCNTR"."HIERARCHY_DESCRIPTION";
CREATE OR REPLACE SYNONYM "CCNUSER"."HIERARCHY_DETAIL" FOR "COSTCNTR"."HIERARCHY_DETAIL";
CREATE OR REPLACE SYNONYM "CCNUSER"."MARKETING" FOR "COSTCNTR"."MARKETING";
CREATE OR REPLACE SYNONYM "CCNUSER"."TAXWARE" FOR "COSTCNTR"."TAXWARE";
CREATE OR REPLACE SYNONYM "CCNUSER"."COST_CENTER_UPLOAD" FOR "COSTCNTR"."COST_CENTER_UPLOAD";
CREATE OR REPLACE SYNONYM "CCNUSER"."COMMON_TOOLS" FOR "COSTCNTR"."COMMON_TOOLS";
CREATE OR REPLACE SYNONYM "CCNUSER"."CCN_UI_INTERFACE_APP_PKG" FOR "COSTCNTR"."CCN_UI_INTERFACE_APP_PKG";
CREATE OR REPLACE SYNONYM "CCNUSER"."CCN_TABLE_IU_PKG" FOR "COSTCNTR"."CCN_TABLE_IU_PKG";
CREATE OR REPLACE SYNONYM "CCNUSER"."CCN_PICK_LIST_PKG" FOR "COSTCNTR"."CCN_PICK_LIST_PKG";
CREATE OR REPLACE SYNONYM "CCNUSER"."CCN_HIERARCHY" FOR "COSTCNTR"."CCN_HIERARCHY";
