/*
Adding new fields to COST_CENTER table

Created : 11/11/2016 jxc517 CCN Project Team....
*/
ALTER TABLE COST_CENTER ADD SPRAY_EQP_RPR_IND VARCHAR2(1);
ALTER TABLE COST_CENTER ADD BOOK_PLN_PROFILE_CD VARCHAR2(2);
