/*******************************************************************************
Created : 03/07/2018 bxa919 CCN Project Team...
          The script will created tables  CCN_COST_CENTER_INFO table.The data in the table 
          is used to generate 'CCN08900' file to sens ro Real Estate.
*******************************************************************************/
CREATE TABLE CCN_COST_CENTER_INFO (	
        IGNORE                               VARCHAR2(1),  
        COST_CENTER                          VARCHAR2(6) NOT NULL ENABLE, 
        DIVISION                             VARCHAR2(4), 
        OLD_COST_CENTER                      VARCHAR2(4), 
        COST_CENTER_NAME                     VARCHAR2(35), 
        CREDIT_CENTER                        VARCHAR2(5), 
        BOOKKEEPER_UAR                       VARCHAR2(30), 
        AQUISITION_CODE                      VARCHAR2(3), 
        DAD                                  VARCHAR2(6), 
        PHONE_NBR                            VARCHAR2(14), 
        RURAL_METRO_ZONE                     VARCHAR2(1), 
        COST_CENTER_CATEGORY                 VARCHAR2(1), 
        GNRC_GROUP_IND                       VARCHAR2(2), 
        ADDRESS_LINE1                        VARCHAR2(100), 
        ADDRESS_LINE2                        VARCHAR2(100), 
        CITY                                 VARCHAR2(30), 
        STATE                                VARCHAR2(5), 
        ZIP_CODE4                            VARCHAR2(10), 
        COUNTY                               VARCHAR2(20), 
        COUNTRY_CODE                         VARCHAR2(5), 
        COST_CENTER_DIV5101                  VARCHAR2(2), 
        COST_CENTER_DIVISION                 VARCHAR2(2), 
        COST_CENTER_AREA                     VARCHAR2(2), 
        COST_CENTER_DISTICT                  VARCHAR2(2), 
        DIVISION_SGL                         VARCHAR2(3), 
        STATUS_CODE                          VARCHAR2(1), 
        TYPE_CODE                            VARCHAR2(2), 
        SALES_VOLUME_CLS_CD                  VARCHAR2(2), 
        IWC_BK_PLN_PROF_CD                   VARCHAR2(2), 
        IWC_BIN_COUNT                        VARCHAR2(4), 
        IWC_PHY_BIN_COUNT                    VARCHAR2(4), 
        IWC_BIN_CNT_5402                     VARCHAR2(4), 
        IWC_BIN_CNT_5403                     VARCHAR2(4), 
        BIN_VOL_IND                          VARCHAR2(1), 
        SPRY_EQUIP_RPR_IND                   VARCHAR2(1), 
        SPRY_EQUIP_STK_IND                   VARCHAR2(1), 
        IM_FACILITY_IND                      VARCHAR2(1), 
        CC_FACILITY_IND                      VARCHAR2(1), 
        POP_KIT_COUNT                        VARCHAR2(1), 
        DSC_CODE_PAINT                       VARCHAR2(4), 
        DSC_CODE_AP                          VARCHAR2(4), 
        DCS_CODE_WC                          VARCHAR2(4), 
        EMP_FIRST_NAME                       VARCHAR2(150), 
        EMP_MIDDL_NAME                       VARCHAR2(60), 
        EMP_LAST_NAME                        VARCHAR2(150), 
        ADI_CODE                             VARCHAR2(3), 
        SMSA_CODE                            VARCHAR2(4), 
        SALES_REP_TYPE_BUSN                  VARCHAR2(2), 
        MISSION_TYPE                         VARCHAR2(2), 
        FAX_NUMBER                           VARCHAR2(14), 
        SALES_REP_HOME_STORE                 VARCHAR2(6), 
        SHELF_LABEL_CODE                     VARCHAR2(1), 
        SHELF_LABEL_SET_CT                   VARCHAR2(3), 
        SHELF_LABEL_ACT_CD                   VARCHAR2(1), 
        POLLING_STATUS                       VARCHAR2(1), 
        COUNTY_CODE                          VARCHAR2(3), 
        ADDR_STATE_CD_NUM                    VARCHAR2(2), 
        CCNTR_DUNS_NBR                       VARCHAR2(9), 
        CCNTR_OPEN_DATE                      VARCHAR2(8), 
        CCNTR_MOVE_DATE                      VARCHAR2(8), 
        CCNTR_CLOSE_DATE                     VARCHAR2(8), 
        FILLER                               VARCHAR2(180), 
        FILE_NAME                            VARCHAR2(24), 
        FILLER_BYTE                          VARCHAR2(1)
CONSTRAINT CCN_INFO_TB_PK PRIMARY KEY (COST_CENTER));