/*
SCRIPT NAME: DDL_CCN_SWC_PN_SQFT_INT_HIST.SQL
PURPOSE    : CREATING THE CCN_SWC_PN_SQFT_INT_HIST TABLE.

CREATED : 07/11/2017 km302 CCN PROJECT....
CHANGED : 
*/

CREATE  TABLE CCN_SWC_PN_SQFT_INT_HIST (
    DIVISION              VARCHAR2(10),
    COST_CENTER           VARCHAR2(10),
    LEASING_SALES_SQ_FT   VARCHAR2(50),
    LEASING_TOTAL_SQ_FT   VARCHAR2(50),
    LEASE_OR_OWNED        VARCHAR2(2),
    LOAD_DATE             DATE,
    CONSTRAINT COST_CENTER_SWC_HIST_PK PRIMARY KEY (COST_CENTER)
);


