  ALTER TABLE BANK_CARD ADD PCI_MERCHANT_ID VARCHAR2(20);
  ALTER TABLE BANK_CARD ADD PCI_DISCOVER_ID VARCHAR2(20);
  ALTER TABLE TERMINAL  ADD (PCI_TERMINAL_ID VARCHAR2(50),
                             PCI_VALUE_LINK_MID VARCHAR2(50),
                             PCI_VAL_LINK_ALT_MID VARCHAR2(50));
  