  ALTER TABLE BANK_CARD ADD PCI_MERCHANT_ID VARCHAR2(20);
  ALTER TABLE BANK_CARD ADD PCI_DISCOVER_ID VARCHAR2(20);
  ALTER TABLE TERMINAL  ADD (PCI_TERMINAL_ID VARCHAR2(50),
                             PCI_VALUE_LINK_MID VARCHAR2(50),
                             PCI_VAL_LINK_ALT_MID VARCHAR2(50));
  
 /
  CREATE TABLE TEMP_PCI_TERMINAL_ID
   (PCI_TERMINAL_ID VARCHAR2(50), 
	  COST_CENTER_CODE VARCHAR2(4)
   ) 
   ORGANIZATION EXTERNAL 
    ( TYPE ORACLE_LOADER
      DEFAULT DIRECTORY "CCN_DATAFILES"
      ACCESS PARAMETERS
      ( RECORDS delimited by NEWLINE
        badfile CCN_LOAD_FILES:'TEMP_PCI_TERMINAL_ID.bad'
        logfile CCN_LOAD_FILES:'TEMP_PCI_TERMINAL_ID.log'
        discardfile CCN_LOAD_FILES:'TEMP_PCI_TERMINAL_ID.dsc'
        FIELDS TERMINATED BY ','
        MISSING FIELD VALUES ARE NULL
        (PCI_TERMINAL_ID      CHAR(50),
         COST_CENTER_CODE     CHAR(4)))
      LOCATION
       ( 'PCI_TERMINAL_ID.csv'
       )
    );
/

  CREATE TABLE TEMP_PCI_VAL_LINK_MID
   (PCI_VAL_LINK_MID VARCHAR2(50), 
	  COST_CENTER_CODE VARCHAR2(4)
   ) 
   ORGANIZATION EXTERNAL 
    ( TYPE ORACLE_LOADER
      DEFAULT DIRECTORY "CCN_DATAFILES"
      ACCESS PARAMETERS
      ( RECORDS delimited by NEWLINE
        badfile CCN_LOAD_FILES:'TEMP_PCI_VAL_LINK_MID.bad'
        logfile CCN_LOAD_FILES:'TEMP_PCI_VAL_LINK_MID.log'
        discardfile CCN_LOAD_FILES:'TEMP_PCI_VAL_LINK_MID.dsc'
        FIELDS TERMINATED BY ','
        MISSING FIELD VALUES ARE NULL
        (PCI_VAL_LINK_MID      CHAR(50),
         COST_CENTER_CODE      CHAR(4)))
      LOCATION
       ( 'PCI_VAL_LINK_MID.csv'
       )
    );
 /   
  CREATE TABLE TEMP_PCI_VAL_LINK_ALT_MID
   (PCI_VAL_LINK_ALT_MID VARCHAR2(50), 
	  COST_CENTER_CODE VARCHAR2(4)
   ) 
   ORGANIZATION EXTERNAL 
    ( TYPE ORACLE_LOADER
      DEFAULT DIRECTORY "CCN_DATAFILES"
      ACCESS PARAMETERS
      ( RECORDS delimited by NEWLINE
        badfile CCN_LOAD_FILES:'TEMP_PCI_VAL_LINK_ALT_MID.bad'
        logfile CCN_LOAD_FILES:'TEMP_PCI_VAL_LINK_ALT_MID.log'
        discardfile CCN_LOAD_FILES:'TEMP_PCI_VAL_LINK_ALT_MID.dsc'
        FIELDS TERMINATED BY ','
        MISSING FIELD VALUES ARE NULL
        (PCI_VAL_LINK_ALT_MID      CHAR(50),
         COST_CENTER_CODE          CHAR(4)))
      LOCATION
       ( 'PCI_VAL_LINK_ALT_MID.csv'
       )
    );
/

CREATE TABLE TEMP_PCI_MID 
   (PCI_MERCHANT_ID	VARCHAR2(20),
    COST_CENTER_CODE VARCHAR2(4)) 
   ORGANIZATION EXTERNAL 
    ( TYPE ORACLE_LOADER
      DEFAULT DIRECTORY "CCN_DATAFILES"
      ACCESS PARAMETERS
      ( RECORDS delimited by NEWLINE
        badfile CCN_LOAD_FILES:'TEMP_PCI_MID.bad'
        logfile CCN_LOAD_FILES:'TEMP_PCI_MID.log'
        discardfile CCN_LOAD_FILES:'TEMP_PCI_MID.dsc'
        FIELDS TERMINATED BY ','
        MISSING FIELD VALUES ARE NULL
        (PCI_MERCHANT_ID      CHAR(20),
         COST_CENTER_CODE     CHAR(4)))
      LOCATION
       ('PAX_MID.csv'
       )
    );
	
/
CREATE TABLE TEMP_PCI_DISCOVER_ID 
   (PCI_DISCOVER_ID	VARCHAR2(20),
    COST_CENTER_CODE VARCHAR2(4)) 
   ORGANIZATION EXTERNAL 
    ( TYPE ORACLE_LOADER
      DEFAULT DIRECTORY "CCN_DATAFILES"
      ACCESS PARAMETERS
      ( RECORDS delimited by NEWLINE
        badfile CCN_LOAD_FILES:'TEMP_PCI_DISCOVER_ID.bad'
        logfile CCN_LOAD_FILES:'TEMP_PCI_DISCOVER_ID.log'
        discardfile CCN_LOAD_FILES:'TEMP_PCI_DISCOVER_ID.dsc'
        FIELDS TERMINATED BY ','
        MISSING FIELD VALUES ARE NULL
        (PCI_DISCOVER_ID      CHAR(20),
         COST_CENTER_CODE     CHAR(4)))
      LOCATION
       ('PAX_DISCOVER_ID.csv'
       )
    );
/	