/********************************************************************************
Adding new Cost Center category  "D - Dispatch Terminal" for Terminal type cost centers INTO CODE_DETAIL

Adding Records into DISPATCH_TERMINAL TABle

Update Cost center category to "D" which are Dispatch termials

Created : 04/11/2017 rxa457 CCN Project Team....
Created:
********************************************************************************/
SET DEFINE OFF;

REM INSERTING into CODE_DETAIL
Insert into CODE_DETAIL (CODE_HEADER_NAME,CODE_HEADER_TYPE,CODE_DETAIL_VALUE,CODE_DETAIL_DESCRIPTION,CODE_DETAIL_EXPIRE_FLAG,CODE_DETAIL_EXPIRE_USER,CODE_DETAIL_EXPIRE_EFF_DATE,CODE_DETAIL_ID,CODE_DETAIL_CREATE_USER,CODE_DETAIL_EFF_DATE) values ('CATEGORY','COD','D','DISPATCH TERMINAL','N',null,null,7,null,null);

REM INSERTING into INSERTORDER
Insert into INSERTORDER (TABLE_NAME,TABLE_ORDER) values ('DISPATCH_TERMINAL',21);


REM UPDATING COST_CENTER CATEGORY 
UPDATE COST_CENTER A SET A.CATEGORY = 'D' WHERE COST_CENTER_CODE LIKE '%T' AND COST_CENTER_CODE NOT IN ('83MXMT', '83VIET', '81GPOT','OOPPFT', '76782T')
AND EXISTS(SELECT 'X' FROM COST_CENTER C WHERE SUBSTR(C.COST_CENTER_CODE,-4,4) = SUBSTR(A.COST_CENTER_NAME,-4,4) AND C.CATEGORY = 'S')
AND A.CATEGORY !='D';

REM INSERTING into DISPATCH_TERMINAL
INSERT INTO DISPATCH_TERMINAL 
SELECT COST_CENTER_CODE, CATEGORY, 
(SELECT COST_CENTER_CODE FROM COST_CENTER C WHERE SUBSTR(C.COST_CENTER_CODE,-4,4) = SUBSTR(A.COST_CENTER_NAME,-4,4) AND C.CATEGORY = 'S') HOME_STORE 
FROM  COST_CENTER A WHERE  A.CATEGORY = 'D' AND  NOT EXISTS(SELECT 'X' FROM DISPATCH_TERMINAL D WHERE A.COST_CENTER_CODE = D.COST_CENTER_CODE);

COMMIT;
