CREATE OR REPLACE VIEW GLOBAL_HIERARCHY_ATTRBT_VW
AS 
SELECT 
/*******************************************************************************
This View holds all the details of global hierarchy linked to the cost center i.e. this view will 
have all the details of each and every level of the global hierarchy for a particular cost center.
It will also have all the upper level value attributes in separate columns for each level (1-9).

Created  : 10/14/2015 nxk927 CCN Project....
Modified : 11/12/2015 sxt410 CCN Project...
           Getting the Attributes using function to optimize the query.
         : 11/25/2015 AXK326 CCN Project Team....
           Modified *_UPPER_LVL_VER_VALUE to *_MGR_NAME to determine the manager names associated to it
         : 01/18/2015 nxk927 CCN Project Team....
           adding back the upper level value for each level
*******************************************************************************/
       GV.STATEMENT_TYPE,
       GV.HRCHY_HDR_NAME,
       GV.COST_CENTER_CODE,
       GV.HRCHY_DTL_EFF_DATE,
       GV.HRCHY_DTL_EXP_DATE,
       GV.DOMAIN,
       GV."GROUP",
       GV.DIVISION,
       GV.AREA,
       GV.DISTRICT,
       GV.CITY_SALES_MANAGER,
       GV."ZONE",
       GV.SPECIAL_ROLES,
       GV.COST_CENTER,
       GV.DOMAIN_NAME,
       GV.GROUP_NAME,
       GV.DIVISION_NAME,
       GV.AREA_NAME,
       GV.DISTRICT_NAME,
       GV.CITY_SALES_MANAGER_NAME,
       GV.ZONE_NAME,
       GV.SPECIAL_ROLES_NAME,
       GV.COST_CENTER_NAME,
       CCN_EMPLOYEE_DETAILS_PKG.GET_EMPLOYEE_NAME(CCN_HIERARCHY.GET_RQSTD_ATTRIBUTE_VALUE(COMMON_TOOLS.GET_UPPER_LVL_VER_VALUE ( GV.HRCHY_HDR_NAME, GV.DOMAIN, GV.DOMAIN||GV."GROUP", '~~~' ), 'ManagerName')) DOMAIN_MGR_NAME,
       CCN_EMPLOYEE_DETAILS_PKG.GET_EMPLOYEE_NAME(CCN_HIERARCHY.GET_RQSTD_ATTRIBUTE_VALUE(COMMON_TOOLS.GET_UPPER_LVL_VER_VALUE ( GV.HRCHY_HDR_NAME, GV.DOMAIN||GV."GROUP", GV.DOMAIN||GV."GROUP"||GV.DIVISION, GV.DOMAIN ), 'ManagerName')) GROUP_MGR_NAME,
       CCN_EMPLOYEE_DETAILS_PKG.GET_EMPLOYEE_NAME(CCN_HIERARCHY.GET_RQSTD_ATTRIBUTE_VALUE(COMMON_TOOLS.GET_UPPER_LVL_VER_VALUE ( GV.HRCHY_HDR_NAME, GV.DOMAIN||GV."GROUP"||GV.DIVISION, GV.DOMAIN||GV."GROUP"||GV.DIVISION||GV.AREA, GV.DOMAIN||GV."GROUP" ), 'ManagerName')) DIV_MGR_NAME,
       CCN_EMPLOYEE_DETAILS_PKG.GET_EMPLOYEE_NAME(CCN_HIERARCHY.GET_RQSTD_ATTRIBUTE_VALUE(COMMON_TOOLS.GET_UPPER_LVL_VER_VALUE ( GV.HRCHY_HDR_NAME, GV.DOMAIN||GV."GROUP"||GV.DIVISION||GV.AREA, GV.DOMAIN||GV."GROUP"||GV.DIVISION||GV.AREA||GV.DISTRICT, GV.DOMAIN||GV."GROUP"||GV.DIVISION ), 'ManagerName')) AREA_MGR_NAME,
       CCN_EMPLOYEE_DETAILS_PKG.GET_EMPLOYEE_NAME(CCN_HIERARCHY.GET_RQSTD_ATTRIBUTE_VALUE(COMMON_TOOLS.GET_UPPER_LVL_VER_VALUE ( GV.HRCHY_HDR_NAME, GV.DOMAIN||GV."GROUP"||GV.DIVISION||GV.AREA||GV.DISTRICT, GV.DOMAIN||GV."GROUP"||GV.DIVISION||GV.AREA||GV.DISTRICT||GV.CITY_SALES_MANAGER, GV.DOMAIN||GV."GROUP"||GV.DIVISION||GV.AREA ), 'ManagerName')) DISTRICT_MGR_NAME,
       CCN_EMPLOYEE_DETAILS_PKG.GET_EMPLOYEE_NAME(CCN_HIERARCHY.GET_RQSTD_ATTRIBUTE_VALUE(COMMON_TOOLS.GET_UPPER_LVL_VER_VALUE ( GV.HRCHY_HDR_NAME, GV.DOMAIN||GV."GROUP"||GV.DIVISION||GV.AREA||GV.DISTRICT||GV.CITY_SALES_MANAGER, GV.DOMAIN||GV."GROUP"||GV.DIVISION||GV.AREA||GV.DISTRICT||GV.CITY_SALES_MANAGER||GV."ZONE", GV.DOMAIN||GV."GROUP"||GV.DIVISION||GV.AREA||GV.DISTRICT ), 'ManagerName')) CITY_MGR_NAME,
       CCN_EMPLOYEE_DETAILS_PKG.GET_EMPLOYEE_NAME(CCN_HIERARCHY.GET_RQSTD_ATTRIBUTE_VALUE(COMMON_TOOLS.GET_UPPER_LVL_VER_VALUE ( GV.HRCHY_HDR_NAME, GV.DOMAIN||GV."GROUP"||GV.DIVISION||GV.AREA||GV.DISTRICT||GV.CITY_SALES_MANAGER||GV."ZONE", GV.DOMAIN||GV."GROUP"||GV.DIVISION||GV.AREA||GV.DISTRICT||GV.CITY_SALES_MANAGER||GV."ZONE"||GV.SPECIAL_ROLES, GV.DOMAIN||GV."GROUP"||GV.DIVISION||GV.AREA||GV.DISTRICT||GV.CITY_SALES_MANAGER ), 'ManagerName')) ZONE_MGR_NAME,
       CCN_EMPLOYEE_DETAILS_PKG.GET_EMPLOYEE_NAME(CCN_HIERARCHY.GET_RQSTD_ATTRIBUTE_VALUE(COMMON_TOOLS.GET_UPPER_LVL_VER_VALUE ( GV.HRCHY_HDR_NAME, GV.DOMAIN||GV."GROUP"||GV.DIVISION||GV.AREA||GV.DISTRICT||GV.CITY_SALES_MANAGER||GV."ZONE"||GV.SPECIAL_ROLES, GV.DOMAIN||GV."GROUP"||GV.DIVISION||GV.AREA||GV.DISTRICT||GV.CITY_SALES_MANAGER||GV."ZONE"||GV.SPECIAL_ROLES||GV.COST_CENTER_CODE, GV.DOMAIN||GV."GROUP"||GV.DIVISION||GV.AREA||GV.DISTRICT||GV.CITY_SALES_MANAGER||GV."ZONE" ), 'ManagerName')) SPECIAL_ROLES_MGR_NAME,
       CCN_EMPLOYEE_DETAILS_PKG.GET_EMPLOYEE_NAME(CCN_HIERARCHY.GET_RQSTD_ATTRIBUTE_VALUE(COMMON_TOOLS.GET_UPPER_LVL_VER_VALUE ( GV.HRCHY_HDR_NAME, GV.DOMAIN||GV."GROUP"||GV.DIVISION||GV.AREA||GV.DISTRICT||GV.CITY_SALES_MANAGER||GV."ZONE"||GV.SPECIAL_ROLES||GV.COST_CENTER_CODE, '~~~', GV.DOMAIN||GV."GROUP"||GV.DIVISION||GV.AREA||GV.DISTRICT||GV.CITY_SALES_MANAGER||GV."ZONE"||GV.SPECIAL_ROLES ), 'ManagerName')) CC_MGR_NAME,
       COMMON_TOOLS.GET_UPPER_LVL_VER_VALUE ( GV.HRCHY_HDR_NAME, GV.DOMAIN, GV.DOMAIN||GV."GROUP", '~~~' )DOMAIN_UPPER_VALUE,
       COMMON_TOOLS.GET_UPPER_LVL_VER_VALUE ( GV.HRCHY_HDR_NAME, GV.DOMAIN||GV."GROUP", GV.DOMAIN||GV."GROUP"||GV.DIVISION, GV.DOMAIN )GROUP_UPPER_VALUE,
       COMMON_TOOLS.GET_UPPER_LVL_VER_VALUE ( GV.HRCHY_HDR_NAME, GV.DOMAIN||GV."GROUP"||GV.DIVISION, GV.DOMAIN||GV."GROUP"||GV.DIVISION||GV.AREA, GV.DOMAIN||GV."GROUP" )DIV_UPPER_VALUE,
       COMMON_TOOLS.GET_UPPER_LVL_VER_VALUE ( GV.HRCHY_HDR_NAME, GV.DOMAIN||GV."GROUP"||GV.DIVISION||GV.AREA, GV.DOMAIN||GV."GROUP"||GV.DIVISION||GV.AREA||GV.DISTRICT, GV.DOMAIN||GV."GROUP"||GV.DIVISION )AREA_UPPER_VALUE,
       COMMON_TOOLS.GET_UPPER_LVL_VER_VALUE ( GV.HRCHY_HDR_NAME, GV.DOMAIN||GV."GROUP"||GV.DIVISION||GV.AREA||GV.DISTRICT, GV.DOMAIN||GV."GROUP"||GV.DIVISION||GV.AREA||GV.DISTRICT||GV.CITY_SALES_MANAGER, GV.DOMAIN||GV."GROUP"||GV.DIVISION||GV.AREA )DISTRICT_UPPER_VALUE,
       COMMON_TOOLS.GET_UPPER_LVL_VER_VALUE ( GV.HRCHY_HDR_NAME, GV.DOMAIN||GV."GROUP"||GV.DIVISION||GV.AREA||GV.DISTRICT||GV.CITY_SALES_MANAGER, GV.DOMAIN||GV."GROUP"||GV.DIVISION||GV.AREA||GV.DISTRICT||GV.CITY_SALES_MANAGER||GV."ZONE", GV.DOMAIN||GV."GROUP"||GV.DIVISION||GV.AREA||GV.DISTRICT )CITY_UPPER_VALUE,
       COMMON_TOOLS.GET_UPPER_LVL_VER_VALUE ( GV.HRCHY_HDR_NAME, GV.DOMAIN||GV."GROUP"||GV.DIVISION||GV.AREA||GV.DISTRICT||GV.CITY_SALES_MANAGER||GV."ZONE", GV.DOMAIN||GV."GROUP"||GV.DIVISION||GV.AREA||GV.DISTRICT||GV.CITY_SALES_MANAGER||GV."ZONE"||GV.SPECIAL_ROLES, GV.DOMAIN||GV."GROUP"||GV.DIVISION||GV.AREA||GV.DISTRICT||GV.CITY_SALES_MANAGER )ZONE_UPPER_VALUE,
       COMMON_TOOLS.GET_UPPER_LVL_VER_VALUE ( GV.HRCHY_HDR_NAME, GV.DOMAIN||GV."GROUP"||GV.DIVISION||GV.AREA||GV.DISTRICT||GV.CITY_SALES_MANAGER||GV."ZONE"||GV.SPECIAL_ROLES, GV.DOMAIN||GV."GROUP"||GV.DIVISION||GV.AREA||GV.DISTRICT||GV.CITY_SALES_MANAGER||GV."ZONE"||GV.SPECIAL_ROLES||GV.COST_CENTER_CODE, GV.DOMAIN||GV."GROUP"||GV.DIVISION||GV.AREA||GV.DISTRICT||GV.CITY_SALES_MANAGER||GV."ZONE" )SPECIAL_ROLES_UPPER_VALUE,
       COMMON_TOOLS.GET_UPPER_LVL_VER_VALUE ( GV.HRCHY_HDR_NAME, GV.DOMAIN||GV."GROUP"||GV.DIVISION||GV.AREA||GV.DISTRICT||GV.CITY_SALES_MANAGER||GV."ZONE"||GV.SPECIAL_ROLES||GV.COST_CENTER_CODE, '~~~', GV.DOMAIN||GV."GROUP"||GV.DIVISION||GV.AREA||GV.DISTRICT||GV.CITY_SALES_MANAGER||GV."ZONE"||GV.SPECIAL_ROLES )CC_UPPER_LVL_VALUE
  FROM HIERARCHY_DETAIL_VIEW GV
 WHERE GV.HRCHY_HDR_NAME = 'GLOBAL_HIERARCHY';