CREATE OR REPLACE VIEW GLOBAL_HIERARCHY_ATTRBT_VW
AS 
SELECT 
/*******************************************************************************
This View holds all the details of global hierarchy linked to the cost center i.e. this view will 
have all the details of each and every level of the global hierarchy for a particular cost center.
It will also have all the upper level value attributes in separate columns for each level (1-9).

Created  : 10/14/2015 nxk927 CCN Project....
Modified : 11/12/2015 sxt410 CCN Project...
           Getting the Attributes using function to optimize the query.
*******************************************************************************/
       GV.STATEMENT_TYPE,
       GV.HRCHY_HDR_NAME,
       GV.COST_CENTER_CODE,
       GV.HRCHY_DTL_EFF_DATE,
       GV.HRCHY_DTL_EXP_DATE,
       GV.DOMAIN,
       GV."GROUP",
       GV.DIVISION,
       GV.AREA,
       GV.DISTRICT,
       GV.CITY_SALES_MANAGER,
       GV."ZONE",
       GV.SPECIAL_ROLES,
       GV.COST_CENTER,
       GV.DOMAIN_NAME,
       GV.GROUP_NAME,
       GV.DIVISION_NAME,
       GV.AREA_NAME,
       GV.DISTRICT_NAME,
       GV.CITY_SALES_MANAGER_NAME,
       GV.ZONE_NAME,
       GV.SPECIAL_ROLES_NAME,
       GV.COST_CENTER_NAME,
       COMMON_TOOLS.GET_UPPER_LVL_VER_VALUE ( GV.HRCHY_HDR_NAME, GV.DOMAIN, GV.DOMAIN||GV."GROUP", '~~~' )DOMAIN_UPPER_VALUE,
       COMMON_TOOLS.GET_UPPER_LVL_VER_VALUE ( GV.HRCHY_HDR_NAME, GV.DOMAIN||GV."GROUP", GV.DOMAIN||GV."GROUP"||GV.DIVISION, GV.DOMAIN )GROUP_UPPER_VALUE,
       COMMON_TOOLS.GET_UPPER_LVL_VER_VALUE ( GV.HRCHY_HDR_NAME, GV.DOMAIN||GV."GROUP"||GV.DIVISION, GV.DOMAIN||GV."GROUP"||GV.DIVISION||GV.AREA, GV.DOMAIN||GV."GROUP" )DIV_UPPER_VALUE,
       COMMON_TOOLS.GET_UPPER_LVL_VER_VALUE ( GV.HRCHY_HDR_NAME, GV.DOMAIN||GV."GROUP"||GV.DIVISION||GV.AREA, GV.DOMAIN||GV."GROUP"||GV.DIVISION||GV.AREA||GV.DISTRICT, GV.DOMAIN||GV."GROUP"||GV.DIVISION )AREA_UPPER_VALUE,
       COMMON_TOOLS.GET_UPPER_LVL_VER_VALUE ( GV.HRCHY_HDR_NAME, GV.DOMAIN||GV."GROUP"||GV.DIVISION||GV.AREA||GV.DISTRICT, GV.DOMAIN||GV."GROUP"||GV.DIVISION||GV.AREA||GV.DISTRICT||GV.CITY_SALES_MANAGER, GV.DOMAIN||GV."GROUP"||GV.DIVISION||GV.AREA )DISTRICT_UPPER_VALUE,
       COMMON_TOOLS.GET_UPPER_LVL_VER_VALUE ( GV.HRCHY_HDR_NAME, GV.DOMAIN||GV."GROUP"||GV.DIVISION||GV.AREA||GV.DISTRICT||GV.CITY_SALES_MANAGER, GV.DOMAIN||GV."GROUP"||GV.DIVISION||GV.AREA||GV.DISTRICT||GV.CITY_SALES_MANAGER||GV."ZONE", GV.DOMAIN||GV."GROUP"||GV.DIVISION||GV.AREA||GV.DISTRICT )CITY_UPPER_VALUE,
       COMMON_TOOLS.GET_UPPER_LVL_VER_VALUE ( GV.HRCHY_HDR_NAME, GV.DOMAIN||GV."GROUP"||GV.DIVISION||GV.AREA||GV.DISTRICT||GV.CITY_SALES_MANAGER||GV."ZONE", GV.DOMAIN||GV."GROUP"||GV.DIVISION||GV.AREA||GV.DISTRICT||GV.CITY_SALES_MANAGER||GV."ZONE"||GV.SPECIAL_ROLES, GV.DOMAIN||GV."GROUP"||GV.DIVISION||GV.AREA||GV.DISTRICT||GV.CITY_SALES_MANAGER )ZONE_UPPER_VALUE,
       COMMON_TOOLS.GET_UPPER_LVL_VER_VALUE ( GV.HRCHY_HDR_NAME, GV.DOMAIN||GV."GROUP"||GV.DIVISION||GV.AREA||GV.DISTRICT||GV.CITY_SALES_MANAGER||GV."ZONE"||GV.SPECIAL_ROLES, GV.DOMAIN||GV."GROUP"||GV.DIVISION||GV.AREA||GV.DISTRICT||GV.CITY_SALES_MANAGER||GV."ZONE"||GV.SPECIAL_ROLES||GV.COST_CENTER_CODE, GV.DOMAIN||GV."GROUP"||GV.DIVISION||GV.AREA||GV.DISTRICT||GV.CITY_SALES_MANAGER||GV."ZONE" )SPECIAL_ROLES_UPPER_VALUE,
       COMMON_TOOLS.GET_UPPER_LVL_VER_VALUE ( GV.HRCHY_HDR_NAME, GV.DOMAIN||GV."GROUP"||GV.DIVISION||GV.AREA||GV.DISTRICT||GV.CITY_SALES_MANAGER||GV."ZONE"||GV.SPECIAL_ROLES||GV.COST_CENTER_CODE, '~~~', GV.DOMAIN||GV."GROUP"||GV.DIVISION||GV.AREA||GV.DISTRICT||GV.CITY_SALES_MANAGER||GV."ZONE"||GV.SPECIAL_ROLES )CC_UPPER_LVL_VALUE
  FROM HIERARCHY_DETAIL_VIEW GV
 WHERE GV.HRCHY_HDR_NAME = 'GLOBAL_HIERARCHY';