CREATE OR REPLACE VIEW GLOBAL_HIERARCHY_ATTRBT_VW
AS 
SELECT 
/*******************************************************************************
This View holds all the details of global hierarchy linked to the cost center i.e. this view will 
have all the details of each and every level of the global hierarchy for a particular cost center.
It will also have all the upper level value attributes in separate columns for each level (1-9).


Created  : 10/14/2015 nxk927 CCN Project....
Modified : 
*******************************************************************************/
       GV."STATEMENT_TYPE",GV."HRCHY_HDR_NAME",GV."COST_CENTER_CODE",GV."HRCHY_DTL_EFF_DATE",GV."HRCHY_DTL_EXP_DATE",GV."DOMAIN",GV."GROUP",GV."DIVISION",GV."AREA",GV."DISTRICT",GV."CITY_SALES_MANAGER",GV."ZONE",GV."SPECIAL_ROLES",GV."COST_CENTER",GV."DOMAIN_NAME",GV."GROUP_NAME",GV."DIVISION_NAME",GV."AREA_NAME",GV."DISTRICT_NAME",GV."CITY_SALES_MANAGER_NAME",GV."ZONE_NAME",GV."SPECIAL_ROLES_NAME",GV."COST_CENTER_NAME",
       (SELECT UPPER_LVL_VER_VALUE 
          FROM HIERARCHY_DETAIL 
         WHERE HRCHY_HDR_NAME = GV.HRCHY_HDR_NAME 
           AND HRCHY_DTL_CURR_LVL_VAL = GV.DOMAIN
           AND HRCHY_DTL_NEXT_LVL_VAL = GV.DOMAIN||GV."GROUP"
           AND HRCHY_DTL_PREV_LVL_VAL = '~~~'
           AND ROWNUM <2) DOMAIN_UPPER_VALUE,
       (SELECT UPPER_LVL_VER_VALUE 
          FROM HIERARCHY_DETAIL 
         WHERE HRCHY_HDR_NAME = GV.HRCHY_HDR_NAME
           AND HRCHY_DTL_CURR_LVL_VAL = GV.DOMAIN||GV."GROUP"
           AND HRCHY_DTL_NEXT_LVL_VAL = GV.DOMAIN||GV."GROUP"||GV.DIVISION
           AND HRCHY_DTL_PREV_LVL_VAL = GV.DOMAIN
           AND ROWNUM <2) GROUP_UPPER_VALUE,
       (SELECT UPPER_LVL_VER_VALUE 
          FROM HIERARCHY_DETAIL 
         WHERE HRCHY_HDR_NAME = GV.HRCHY_HDR_NAME
           AND HRCHY_DTL_CURR_LVL_VAL = GV.DOMAIN||GV."GROUP"||GV.DIVISION
           AND HRCHY_DTL_NEXT_LVL_VAL = GV.DOMAIN||GV."GROUP"||GV.DIVISION||GV.AREA
           AND HRCHY_DTL_PREV_LVL_VAL = GV.DOMAIN||GV."GROUP"
           AND ROWNUM <2) DIV_UPPER_VALUE,
       (SELECT UPPER_LVL_VER_VALUE 
          FROM HIERARCHY_DETAIL 
         WHERE HRCHY_HDR_NAME = GV.HRCHY_HDR_NAME
           AND HRCHY_DTL_CURR_LVL_VAL = GV.DOMAIN||GV."GROUP"||GV.DIVISION||GV.AREA
           AND HRCHY_DTL_NEXT_LVL_VAL = GV.DOMAIN||GV."GROUP"||GV.DIVISION||GV.AREA||GV.DISTRICT
           AND HRCHY_DTL_PREV_LVL_VAL = GV.DOMAIN||GV."GROUP"||GV.DIVISION
           AND ROWNUM <2) AREA_UPPER_VALUE,
       (SELECT UPPER_LVL_VER_VALUE 
          FROM HIERARCHY_DETAIL 
         WHERE HRCHY_HDR_NAME = GV.HRCHY_HDR_NAME
           AND HRCHY_DTL_CURR_LVL_VAL = GV.DOMAIN||GV."GROUP"||GV.DIVISION||GV.AREA||GV.DISTRICT
           AND HRCHY_DTL_NEXT_LVL_VAL = GV.DOMAIN||GV."GROUP"||GV.DIVISION||GV.AREA||GV.DISTRICT||GV.CITY_SALES_MANAGER
           AND HRCHY_DTL_PREV_LVL_VAL = GV.DOMAIN||GV."GROUP"||GV.DIVISION||GV.AREA
           AND ROWNUM <2) DISTRICT_UPPER_VALUE,
       (SELECT UPPER_LVL_VER_VALUE 
          FROM HIERARCHY_DETAIL 
         WHERE HRCHY_HDR_NAME = GV.HRCHY_HDR_NAME
           AND HRCHY_DTL_CURR_LVL_VAL = GV.DOMAIN||GV."GROUP"||GV.DIVISION||GV.AREA||GV.DISTRICT||GV.CITY_SALES_MANAGER
           AND HRCHY_DTL_NEXT_LVL_VAL = GV.DOMAIN||GV."GROUP"||GV.DIVISION||GV.AREA||GV.DISTRICT||GV.CITY_SALES_MANAGER||GV."ZONE"
           AND HRCHY_DTL_PREV_LVL_VAL = GV.DOMAIN||GV."GROUP"||GV.DIVISION||GV.AREA||GV.DISTRICT
           AND ROWNUM <2) CITY_UPPER_VALUE, 
       (SELECT UPPER_LVL_VER_VALUE 
          FROM HIERARCHY_DETAIL 
         WHERE HRCHY_HDR_NAME = GV.HRCHY_HDR_NAME
           AND HRCHY_DTL_CURR_LVL_VAL = GV.DOMAIN||GV."GROUP"||GV.DIVISION||GV.AREA||GV.DISTRICT||GV.CITY_SALES_MANAGER||GV."ZONE"
           AND HRCHY_DTL_NEXT_LVL_VAL = GV.DOMAIN||GV."GROUP"||GV.DIVISION||GV.AREA||GV.DISTRICT||GV.CITY_SALES_MANAGER||GV."ZONE"||GV.SPECIAL_ROLES
           AND HRCHY_DTL_PREV_LVL_VAL = GV.DOMAIN||GV."GROUP"||GV.DIVISION||GV.AREA||GV.DISTRICT||GV.CITY_SALES_MANAGER
           AND ROWNUM <2) ZONE_UPPER_VALUE,
       (SELECT UPPER_LVL_VER_VALUE 
          FROM HIERARCHY_DETAIL 
         WHERE HRCHY_HDR_NAME = GV.HRCHY_HDR_NAME
           AND HRCHY_DTL_CURR_LVL_VAL = GV.DOMAIN||GV."GROUP"||GV.DIVISION||GV.AREA||GV.DISTRICT||GV.CITY_SALES_MANAGER||GV."ZONE"||GV.SPECIAL_ROLES
           AND HRCHY_DTL_NEXT_LVL_VAL = GV.DOMAIN||GV."GROUP"||GV.DIVISION||GV.AREA||GV.DISTRICT||GV.CITY_SALES_MANAGER||GV."ZONE"||GV.SPECIAL_ROLES||GV.COST_CENTER_CODE
           AND HRCHY_DTL_PREV_LVL_VAL = GV.DOMAIN||GV."GROUP"||GV.DIVISION||GV.AREA||GV.DISTRICT||GV.CITY_SALES_MANAGER||GV."ZONE"
           AND ROWNUM <2) SPECIAL_ROLES_UPPER_VALUE,
       (SELECT UPPER_LVL_VER_VALUE 
          FROM HIERARCHY_DETAIL 
         WHERE HRCHY_HDR_NAME = GV.HRCHY_HDR_NAME
           AND HRCHY_DTL_CURR_LVL_VAL = GV.DOMAIN||GV."GROUP"||GV.DIVISION||GV.AREA||GV.DISTRICT||GV.CITY_SALES_MANAGER||GV."ZONE"||GV.SPECIAL_ROLES||GV.COST_CENTER_CODE
           AND HRCHY_DTL_NEXT_LVL_VAL = '~~~'
           AND HRCHY_DTL_PREV_LVL_VAL = GV.DOMAIN||GV."GROUP"||GV.DIVISION||GV.AREA||GV.DISTRICT||GV.CITY_SALES_MANAGER||GV."ZONE"||GV.SPECIAL_ROLES
           AND ROWNUM <2) CC_UPPER_LVL_VALUE   
          FROM HIERARCHY_DETAIL_VIEW GV
 WHERE GV.HRCHY_HDR_NAME = 'GLOBAL_HIERARCHY';