-- created by BXA919 on 02/20/2018
-- Run this in COSTCNTR

GRANT SELECT  ON CCN_PD_USA TO CCN_UTILITY;
GRANT EXECUTE ON CCN_PD_USA TO CCN_UTILITY;
GRANT SELECT  ON CCN_PD_CAN TO CCN_UTILITY;
GRANT EXECUTE ON CCN_PD_CAN TO CCN_UTILITY;