/***********************************************************
Table HIERARCHY_DETAIL_DAILY_SNAP_H
created : 01/05/2018 SXG151
revised :
************************************************************/
CREATE TABLE HIERARCHY_DETAIL_DAILY_SNAP_H
(
    HRCHY_HDR_NAME          VARCHAR2(100) NOT NULL,
    HRCHY_DTL_LEVEL         VARCHAR2(2) NOT NULL,
    HRCHY_DTL_PREV_LVL_VAL  VARCHAR2(1000),
    HRCHY_DTL_CURR_LVL_VAL  VARCHAR2(1000) NOT NULL,
    HRCHY_DTL_NEXT_LVL_VAL  VARCHAR2(1000),
    HRCHY_DTL_EFF_DATE      DATE NOT NULL,
    HRCHY_DTL_EXP_DATE      DATE,
    HRCHY_DTL_DESC          VARCHAR2(100),
    HRCHY_DTL_CURR_ROW_VAL  VARCHAR2(100),
    UPPER_LVL_VER_VALUE     XMLTYPE,
    LOAD_DATE               DATE   NOT NULL)
    PARTITION BY RANGE (LOAD_DATE) INTERVAL (NUMTODSINTERVAL(1, 'DAY'))
        (PARTITION P_LOAD_DATE_20171220 VALUES LESS THAN (TO_DATE('03-JAN-2018','DD-MON-YY'))
);

CREATE INDEX INDX_HST ON HIERARCHY_DETAIL_DAILY_SNAP_H (HRCHY_HDR_NAME, LOAD_DATE);