create or replace type hd_type is object(
             COST_CENTER_CODE       VARCHAR2(10),
             HRCHY_HDR_NAME         VARCHAR2(100),
             HRCHY_DTL_LEVEL        VARCHAR2(2),
             HRCHY_DTL_EFF_DATE     DATE,
             HRCHY_DTL_EXP_DATE     DATE,
             HRCHY_DTL_DESC         VARCHAR2(100),
             HRCHY_DTL_CURR_ROW_VAL VARCHAR2(100));
/
create or replace type hd_table is table of hd_type;
/

  CREATE OR REPLACE FORCE VIEW "COSTCNTR"."HIERARCHY_DETAIL_VIEW" ("COST_CENTER_CODE", "Domain", "Group", "Division", "Area", "District", "City_Sales_Manager", "Zone", "Special_Roles", "Cost_Center", "Effective_Date", "Expiration_Date") AS 
  SELECT B.COST_CENTER_CODE,
         MAX(DECODE(HRCHY_DTL_LEVEL,1,HRCHY_DTL_CURR_ROW_VAL)) AS "Domain",
         MAX(DECODE(HRCHY_DTL_LEVEL,2,HRCHY_DTL_CURR_ROW_VAL)) AS "Group",
         MAX(DECODE(HRCHY_DTL_LEVEL,3,HRCHY_DTL_CURR_ROW_VAL)) AS "Division",
         MAX(DECODE(HRCHY_DTL_LEVEL,4,HRCHY_DTL_CURR_ROW_VAL)) AS "Area",
         MAX(DECODE(HRCHY_DTL_LEVEL,5,HRCHY_DTL_CURR_ROW_VAL)) AS "District",
         MAX(DECODE(HRCHY_DTL_LEVEL,6,HRCHY_DTL_CURR_ROW_VAL)) AS "City_Sales_Manager",
         MAX(DECODE(HRCHY_DTL_LEVEL,7,HRCHY_DTL_CURR_ROW_VAL)) AS "Zone",
         MAX(DECODE(HRCHY_DTL_LEVEL,8,HRCHY_DTL_CURR_ROW_VAL)) AS "Special_Roles",
         MAX(DECODE(HRCHY_DTL_LEVEL,9,HRCHY_DTL_CURR_ROW_VAL)) AS "Cost_Center",
         MAX(DECODE(HRCHY_DTL_LEVEL,9,HRCHY_DTL_EFF_DATE)) AS "Effective_Date",
         MAX(DECODE(HRCHY_DTL_LEVEL,9,HRCHY_DTL_EXP_DATE)) AS "Expiration_Date"
    FROM COST_CENTER B, TABLE(CCN_HIERARCHY.GLOBAL_HIERARCHY_VIEW_RESULT('GLOBAL_HIERARCHY',B.COST_CENTER_CODE,'9')) A
   GROUP BY B.COST_CENTER_CODE;
/

  CREATE OR REPLACE FORCE VIEW "COSTCNTR"."HIERARCHY_DETAIL_DESC_VIEW" ("HRCHY_HDR_NAME", "HRCHY_DTL_LEVEL", "HRCHY_DTL_DESC", "HRCHY_DTL_CURR_LVL_VAL") AS 
  SELECT DISTINCT hr.HRCHY_HDR_NAME,
                  hr.HRCHY_DTL_LEVEL,
                  hr.HRCHY_DTL_DESC,
                  hr.HRCHY_DTL_CURR_LVL_VAL
    FROM HIERARCHY_DETAIL hr
   WHERE HRCHY_HDR_NAME         = 'GLOBAL_HIERARCHY';
/

