 CREATE TABLE HIERARCHY_DETAIL_FUTURE
 (HRCHY_HDR_NAME VARCHAR2(100) NOT NULL ENABLE,
  HRCHY_DTL_LEVEL VARCHAR2(2) NOT NULL ENABLE,
  HRCHY_DTL_PREV_LVL_VAL VARCHAR2(1000),
  HRCHY_DTL_CURR_LVL_VAL VARCHAR2(1000) NOT NULL ENABLE,
  HRCHY_DTL_NEXT_LVL_VAL VARCHAR2(1000),
  HRCHY_DTL_EFF_DATE DATE NOT NULL ENABLE,
  HRCHY_DTL_EXP_DATE DATE,
  HRCHY_DTL_DESC VARCHAR2(100),
  HRCHY_DTL_CURR_ROW_VAL VARCHAR2(100),
  UPPER_LVL_VER_VALUE SYS.XMLTYPE
  );

  CREATE INDEX HIERARCHY_DT_FT_INDEX ON HIERARCHY_DETAIL_FUTURE (HRCHY_HDR_NAME, HRCHY_DTL_CURR_ROW_VAL);
  CREATE INDEX HRCHY_DT_FT_INDX ON HIERARCHY_DETAIL_FUTURE (HRCHY_HDR_NAME, HRCHY_DTL_LEVEL, HRCHY_DTL_CURR_LVL_VA