
--script to create JOB_TITLE_GROUP table

CREATE TABLE JOB_TITLE_GROUP
   ("JOB_TITLE" VARCHAR2(50) NOT NULL ENABLE, 
    "JOB_GROUP" VARCHAR2(50), 
    "NONMGR_IND" CHAR(1), 
	 CONSTRAINT "JOB_TITLE" PRIMARY KEY ("JOB_TITLE") ENABLE
	) ;