/*
     Created: 02/07/2018 mxv711 CCN Project Team..
     This script creates a new table LAD_CUSTOMER for new category Latin American call centers
*/

CREATE TABLE LAD_CUSTOMER
(COST_CENTER_CODE VARCHAR2(6 BYTE) NOT NULL , 
 "CATEGORY" VARCHAR2(1 BYTE) NOT NULL, 
 CONSTRAINT LAD_CUSTOMER_PK PRIMARY KEY (COST_CENTER_CODE),
 CONSTRAINT COST_CENTER_LAD_CUSTOMER_FK FOREIGN KEY (COST_CENTER_CODE)
 REFERENCES COSTCNTR.COST_CENTER (COST_CENTER_CODE) 
);

CREATE OR REPLACE TRIGGER "COSTCNTR"."TR_LAD_CUSTOMER_DEL" 
BEFORE DELETE ON "COSTCNTR"."LAD_CUSTOMER"
REFERENCING FOR EACH ROW
DECLARE
V_USERNAME     VARCHAR2(10);
V_TEXT         CLOB;
BEGIN
--Get the User Name from system OS Context
SELECT SYS_CONTEXT('USERENV', 'OS_USER') INTO V_USERNAME FROM DUAL;
--Get the Primary Key Data
V_TEXT := :OLD.COST_CENTER_CODE;
ERRPKG.INSERT_ERROR_LOG_SP('000000','TR_LAD_CUSTOMER_DEL','USER '||V_USERNAME||' HAS DELETED RECORD - '||SUBSTR(V_TEXT,1,450),'DELETE');
END;


/
ALTER TRIGGER "COSTCNTR"."TR_LAD_CUSTOMER_DEL" ENABLE;
/

GRANT SELECT ON LAD_CUSTOMER TO CCNUSER;
CREATE OR REPLACE SYNONYM CCNUSER.LAD_CUSTOMER FOR COSTCNTR.LAD_CUSTOMER;
/
