/*
     Created: 02/07/2018 mxv711 CCN Project Team..
     This script creates a new table LAD_CUSTOMER for new category Latin American call centers
*/

CREATE TABLE LAD_CUSTOMER
(COST_CENTER_CODE VARCHAR2(6) NOT NULL , 
 "CATEGORY"       VARCHAR2(1) NOT NULL, 
 CONSTRAINT       LAD_CUSTOMER_PK PRIMARY KEY (COST_CENTER_CODE),
 CONSTRAINT       COST_CENTER_LAD_CUSTOMER_FK FOREIGN KEY (COST_CENTER_CODE) REFERENCES COST_CENTER (COST_CENTER_CODE) 
);

