GRANT SELECT ON CCN_PHONE_INFO_VW to NETEZZA_ACCESS;
GRANT SELECT ON STATUS_VIEW to NETEZZA_ACCESS;
GRANT SELECT ON  CCN_PHONE_INFO_VW   to NETEZZA_ACCESS ;
GRANT SELECT ON  POLLING_VIEW to NETEZZA_ACCESS ;
GRANT SELECT ON  BANK_CARD_VW to NETEZZA_ACCESS ;
GRANT SELECT ON  TERMINAL_VW to NETEZZA_ACCESS ;
GRANT SELECT ON  GLOBAL_HIERARCHY_ATTRBT_VW to NETEZZA_ACCESS ;

CREATE OR REPLACE SYNONYM NETEZZA_ACCESS.CCN_PHONE_INFO_VW FOR CCN_PHONE_INFO_VW;
CREATE OR REPLACE SYNONYM NETEZZA_ACCESS.STATUS_VIEW FOR STATUS_VIEW;
CREATE OR REPLACE SYNONYM NETEZZA_ACCESS.CCN_PHONE_INFO_VW  FOR CCN_PHONE_INFO_VW  ;
CREATE OR REPLACE SYNONYM NETEZZA_ACCESS.POLLING_VIEW FOR POLLING_VIEW ;
CREATE OR REPLACE SYNONYM NETEZZA_ACCESS.BANK_CARD_VW FOR BANK_CARD_VW ;
CREATE OR REPLACE SYNONYM NETEZZA_ACCESS.TERMINAL_VW FOR TERMINAL_VW ;
CREATE OR REPLACE SYNONYM NETEZZA_ACCESS.GLOBAL_HIERARCHY_ATTRBT_VW FOR GLOBAL_HIERARCHY_ATTRBT_VW ;
