/*
Created :dxv848 09/21/2015 . Creating a POS_XML_IFACE_LOCAL table 
*/

CREATE TABLE POS_XML_IFACE_LOCAL
    (    GUID RAW(16) NOT NULL ENABLE, 
	 QUEUE_NAME VARCHAR2(48 ), 
	 BROKER_NAME VARCHAR2(48 ), 
	 MESSAGE_ID RAW(24), 
	 PUT_TIME TIMESTAMP (6) WITH TIME ZONE, 
	 XML_DOCUMENT SYS.XMLTYPE  NOT NULL ENABLE, 
	 SHRED_TS TIMESTAMP (6) WITH TIME ZONE, 
	 CREATED_TS TIMESTAMP (6) WITH TIME ZONE NOT NULL ENABLE, 
	 STATUS VARCHAR2(1 BYTE)
    );