/*
Below scripts will create tables needed for processors window

Created : 10/14/2016 jxc517 CCN Project Team....
*/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE PROCESSOR_STATES';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE PROCESSORS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE HIST_PROCESSORS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE HIST_PROCESSOR_STATES';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE PROCESSORS (
    PROCESSOR_ID     NUMBER,
    PROCESSOR_NAME   VARCHAR2(200),
    PHONE_NUMBER     VARCHAR2(50),
    CONSTRAINT PROCESSORS_PK PRIMARY KEY (PROCESSOR_ID)
);
/

CREATE TABLE PROCESSOR_STATES (
    STATE_CODE          VARCHAR2(2),
    PROCESSOR_ID        NUMBER,
    CONSTRAINT PROCESSOR_STATES_PK PRIMARY KEY (STATE_CODE),
    CONSTRAINT PROCESSOR_STATES_FK FOREIGN KEY (PROCESSOR_ID) REFERENCES PROCESSORS(PROCESSOR_ID)
);
/

CREATE TABLE HIST_PROCESSORS (
    PROCESSOR_ID     NUMBER,
    PROCESSOR_NAME   VARCHAR2(200),
    PHONE_NUMBER     VARCHAR2(50),
    HIST_LOAD_DATE   DATE
);
/

CREATE TABLE HIST_PROCESSOR_STATES (
    STATE_CODE          VARCHAR2(2),
    PROCESSOR_ID        NUMBER,
    HIST_LOAD_DATE      DATE
);
/

