
CREATE TABLE GENERAL_LEDGER_ACCOUNTS
(GL_ACCOUNT_NUMBER      VARCHAR2(16) NOT NULL ENABLE,
DESCRIPTION             VARCHAR2(100),
PROFIT_OR_LOSS          VARCHAR2(5),
EFFECTIVE_DATE          DATE,
CREATED_BY              VARCHAR2(10),
EXPIRATION_DATE         DATE,
CONSTRAINT GL_ACCNT_PK PRIMARY KEY (GL_ACCOUNT_NUMBER));

CREATE TABLE PRGM_GL_ACCNT_RLTN_DTLS
(GL_PS_ACCOUNT_NUMBER      VARCHAR2(16) NOT NULL ENABLE,
PROGRAM_NAME               VARCHAR2(100)NOT NULL ENABLE,
SORTED_SEQUENCE            NUMBER,
SHARED                     VARCHAR2(5),
EFFECTIVE_DATE             DATE,
CREATED_BY                 VARCHAR2(10),
EXPIRATION_DATE            DATE,
CONSTRAINT GL_PS_ACCNT_PK PRIMARY KEY (GL_PS_ACCOUNT_NUMBER,PROGRAM_NAME),
CONSTRAINT PS_ACCNT_FK FOREIGN KEY (GL_PS_ACCOUNT_NUMBER) REFERENCES GENERAL_LEDGER_ACCOUNTS(GL_ACCOUNT_NUMBER),
CONSTRAINT PS_PRGRM_FK FOREIGN KEY (PROGRAM_NAME) REFERENCES PROGRAMS(PROGRAM_NAME));

CREATE TABLE PROGRAMS
(PROGRAM_NAME           VARCHAR2(100) NOT NULL ENABLE,
EFFECTIVE_DATE          DATE,
CREATED_BY              VARCHAR2(10),
EXPIRATION_DATE         DATE,
CONSTRAINT GL_PS_PROGRAMS_PK PRIMARY KEY (PROGRAM_NAME));