/*******************************************************************************
Alter table script to rename effetive_date to POLL_STATUS_EFF_DT and expiration_date to POLL_STATUS_EXP_DT
CREATED : 07/10/2018 pxa852 CCN Project...
*******************************************************************************/

   ALTER TABLE POLLING RENAME COLUMN POLLING_EFFECTIVE_DATE TO POLL_STATUS_EFF_DT;
   ALTER TABLE POLLING RENAME COLUMN POLLING_EXPIRATION_DATE TO POLL_STATUS_EXP_DT;

   ALTER TABLE POLLING_HST RENAME COLUMN POLLING_EFFECTIVE_DATE TO POLL_STATUS_EFF_DT;
   ALTER TABLE POLLING_HST RENAME COLUMN POLLING_EXPIRATION_DATE TO POLL_STATUS_EXP_DT;

   ALTER TABLE POLLING_HST_NEW RENAME COLUMN POLLING_EFFECTIVE_DATE TO POLL_STATUS_EFF_DT;
   ALTER TABLE POLLING_HST_NEW RENAME COLUMN POLLING_EXPIRATION_DATE TO POLL_STATUS_EXP_DT;

   ALTER TABLE POLLING_HST_BKP RENAME COLUMN POLLING_EFFECTIVE_DATE TO POLL_STATUS_EFF_DT;
   ALTER TABLE POLLING_HST_BKP RENAME COLUMN POLLING_EXPIRATION_DATE TO POLL_STATUS_EXP_DT;
commit;