/*******************************************************************************
Alter table script to rename effetive_date to polling_effective_date and expiration_date to polling_expiration_date
CREATED : 07/10/2018 pxa852 CCN Project...
*******************************************************************************/

   ALTER TABLE POLLING RENAME COLUMN EFFECTIVE_DATE TO POLLING_EFFECTIVE_DATE;
   ALTER TABLE POLLING RENAME COLUMN EXPIRATION_DATE TO POLLING_EXPIRATION_DATE;

   ALTER TABLE POLLING_HST RENAME COLUMN EFFECTIVE_DATE TO POLLING_EFFECTIVE_DATE;
   ALTER TABLE POLLING_HST RENAME COLUMN EXPIRATION_DATE TO POLLING_EXPIRATION_DATE;

   ALTER TABLE POLLING_HST_NEW RENAME COLUMN EFFECTIVE_DATE TO POLLING_EFFECTIVE_DATE;
   ALTER TABLE POLLING_HST_NEW RENAME COLUMN EXPIRATION_DATE TO POLLING_EXPIRATION_DATE;

   ALTER TABLE POLLING_HST_BKP RENAME COLUMN EFFECTIVE_DATE TO POLLING_EFFECTIVE_DATE;
   ALTER TABLE POLLING_HST_BKP RENAME COLUMN EXPIRATION_DATE TO POLLING_EXPIRATION_DATE;
commit;