CREATE OR REPLACE VIEW STORE_MAIN_VW
AS 
SELECT  
/* Comments
This view holds required information about STORE
such as Store number, Zone code, Statement type, Store name,Store open/close date, 
Status, Status description, Cost center Type, Cost center and Mission code.
Created  : 12/11/2014 SXT410 CCN project
Modified : 
*/    
      SUBSTR(CCN.COST_CENTER_CODE,3) STORE_NUMBER,
      (SELECT RURAL_METRO_ZONE_CODE 
       FROM   STORE 
      WHERE   COST_CENTER_CODE = CCN.COST_CENTER_CODE) ZONE_CODE,
      CCN.STATEMENT_TYPE     STATEMENT_TYPE,
      CCN.COST_CENTER_NAME   STORE_NAME,
      CCN.OPEN_DATE          STORE_OPEN_DATE,
      CCN.CLOSE_DATE         STORE_CLOSE_DATE,  
      STS.STATUS_CODE        CCN_STATUS,      
      CCN_PICK_LIST_PKG.GET_CODE_DETAIL_VALUE_DSCRPTN('STATUS_CODE','COD',STS.STATUS_CODE) CCN_STATUS_DESCRIPTION,        
      CCN_HIERARCHY.GET_TYPE_FNC(CCN.COST_CENTER_CODE)  CCN_TYPE,
      CCN.COST_CENTER_CODE   ORACLE_COST_CENTER,
      CCN.MISSION_TYPE_CODE  MISSION_CODE
FROM  COST_CENTER CCN,
      STATUS STS
WHERE CCN.COST_CENTER_CODE = STS.COST_CENTER_CODE
AND   STS.EXPIRATION_DATE IS NULL;