/*
Purpose : For creating the synonym SWC_HR_TAG_CCN_V for SWC_HR_GENERIC_V@EBS_LINK.
          For creating a backup for EMPLOYEE_DETAILS    
Created : 03/19/2018 sxh487 CCN Project....
*/
CREATE OR REPLACE SYNONYM SWC_HR_TAG_CCN_V FOR SWC_HR_TAG_CCN.SWC_HR_GENERIC_V@EBS_LINK;
CREATE TABLE EMPLOYEE_DETAILS_BKUP AS SELECT * FROM EMPLOYEE_DETAILS; 