/*#############################################################
This script creates a Table CCN_DSC_CODE_DESC and CCN_DSC_CODE_DESC_HIST

Created : 04/23/2018 sxg151 CCN Team...
#############################################################*/

CREATE TABLE CCN_DSC_CODE_DESC
    (COST_CENTER_CODE VARCHAR2(21),
     PRIMARY_DSC      NUMBER(3),
     PRI_DSC_DESCR    VARCHAR2(500),
     SECONDARY_DSC    NUMBER(3),
     SEC_DSC_DESCR   VARCHAR2(500),
CONSTRAINT PK_CCN_DSC_CODE_DESC1 PRIMARY KEY (COST_CENTER_CODE)
    );

GRANT SELECT ON CCN_DSC_CODE_DESC TO CCN_UTILITY;

-- Create History table

CREATE TABLE CCN_DSC_CODE_DESC_HIST
    (COST_CENTER_CODE VARCHAR2(21),
     PRIMARY_DSC      NUMBER(3),
     PRI_DSC_DESCR    VARCHAR2(500),
     SECONDARY_DSC    NUMBER(3),
     SEC_DSC_DESCR    VARCHAR2(500),
     LOAD_DATE        DATE,
     CONSTRAINT PK_CCN_DSC_CODE_DESC_HIST PRIMARY KEY (COST_CENTER_CODE,LOAD_DATE)
     );