/*********************************************************** 
This table HIERARCHY_DETAIL_SNAP cteated to load data from HIERARCHY_DETAIL
created : 12/20/2017 SXG151
revised : 
************************************************************/  

CREATE TABLE HIERARCHY_DETAIL_SNAP
   (	HRCHY_HDR_NAME VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	HRCHY_DTL_LEVEL VARCHAR2(2 BYTE) NOT NULL ENABLE, 
	HRCHY_DTL_PREV_LVL_VAL VARCHAR2(1000 BYTE), 
	HRCHY_DTL_CURR_LVL_VAL VARCHAR2(1000 BYTE) NOT NULL ENABLE, 
	HRCHY_DTL_NEXT_LVL_VAL VARCHAR2(1000 BYTE), 
	HRCHY_DTL_EFF_DATE DATE NOT NULL ENABLE, 
	HRCHY_DTL_EXP_DATE DATE, 
	HRCHY_DTL_DESC VARCHAR2(100 BYTE), 
	HRCHY_DTL_CURR_ROW_VAL VARCHAR2(100 BYTE), 
	UPPER_LVL_VER_VALUE XMLTYPE, 
  LOAD_DATE DATE   NOT NULL)
    PARTITION BY RANGE (LOAD_DATE) INTERVAL (NUMTODSINTERVAL(1, 'DAY'))
           ( PARTITION P_LOAD_DATE_20171220 VALUES LESS THAN (TO_DATE('03-JAN-2018','DD-MON-YY'))
) ;    



  CREATE INDEX HRCHY_DTL__CURR_ROW_VAL_INX ON COSTCNTR.HIERARCHY_DETAIL_SNAP (HRCHY_DTL_CURR_ROW_VAL) ;

  CREATE INDEX COSTCNTR.INDX1 ON COSTCNTR.HIERARCHY_DETAIL_SNAP (HRCHY_HDR_NAME, HRCHY_DTL_LEVEL, HRCHY_DTL_PREV_LVL_VAL);

  CREATE INDEX COSTCNTR.INDX2 ON COSTCNTR.HIERARCHY_DETAIL_SNAP (HRCHY_DTL_LEVEL||HRCHY_DTL_CURR_LVL_VAL, HRCHY_HDR_NAME);

  CREATE INDEX COSTCNTR.INDX3 ON COSTCNTR.HIERARCHY_DETAIL_SNAP (HRCHY_DTL_CURR_LVL_VAL||HRCHY_DTL_NEXT_LVL_VAL, HRCHY_HDR_NAME) ;

  CREATE INDEX COSTCNTR.INDX4 ON COSTCNTR.HIERARCHY_DETAIL_SNAP (HRCHY_HDR_NAME, HRCHY_DTL_LEVEL, HRCHY_DTL_CURR_LVL_VAL) ;

  CREATE INDEX COSTCNTR.INDX5 ON COSTCNTR.HIERARCHY_DETAIL_SNAP (HRCHY_HDR_NAME, HRCHY_DTL_CURR_LVL_VAL, HRCHY_DTL_NEXT_LVL_VAL, HRCHY_DTL_PREV_LVL_VAL);