/*********************************************************** 
This table HIERARCHY_DETAIL_DAILY_SNAP cteated to load data from HIERARCHY_DETAIL
created : 1/04/2017 SXG151
revised : 
************************************************************/  

CREATE TABLE HIERARCHY_DETAIL_DAILY_SNAP
   (	HRCHY_HDR_NAME VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	HRCHY_DTL_LEVEL VARCHAR2(2 BYTE) NOT NULL ENABLE, 
	HRCHY_DTL_PREV_LVL_VAL VARCHAR2(1000 BYTE), 
	HRCHY_DTL_CURR_LVL_VAL VARCHAR2(1000 BYTE) NOT NULL ENABLE, 
	HRCHY_DTL_NEXT_LVL_VAL VARCHAR2(1000 BYTE), 
	HRCHY_DTL_EFF_DATE DATE NOT NULL ENABLE, 
	HRCHY_DTL_EXP_DATE DATE, 
	HRCHY_DTL_DESC VARCHAR2(100 BYTE), 
	HRCHY_DTL_CURR_ROW_VAL VARCHAR2(100 BYTE), 
	UPPER_LVL_VER_VALUE XMLTYPE, 
  LOAD_DATE DATE   NOT NULL
) ;    

CREATE INDEX INDX1 ON HIERARCHY_DETAIL_DAILY_SNAP (HRCHY_HDR_NAME, LOAD_DATE);