/*******************************************************************************
Create Table COST_CENTER_VIEW_MONTHLY_SNAP Same as COST_CENTER_VW Along With LOAD_DATE
Created  : 01/23/2019 SXG151 CCN
*******************************************************************************/

CREATE TABLE COST_CENTER_VIEW_MONTHLY_SNAP
  (
    COST_CENTER_CODE               VARCHAR2(6) NOT NULL,
    COST_CENTER_NAME               VARCHAR2(35) NOT NULL,
    CATEGORY                       VARCHAR2(1),
    CATEGORY_DESCRIPTION           VARCHAR2(4000),
    STATEMENT_TYPE                 VARCHAR2(2),
    STATEMENT_TYPE_DESCRIPTION     VARCHAR2(4000),
    COUNTRY_CODE                   VARCHAR2(3),
    COUNTRY_CODE_DESCRIPTION       VARCHAR2(4000),
    BEGIN_DATE                     DATE,
    OPEN_DATE                      DATE,
    MOVE_DATE                      DATE,
    CLOSE_DATE                     DATE,
    CURRENCY_CODE                  VARCHAR2(3),
    MISSION_TYPE_CODE              VARCHAR2(2),
    MISSION_TYPE_CODE_DESCRIPTION  VARCHAR2(4000),
    DUNS_NUMBER                    VARCHAR2(9),
    ACQUISITION_CODE               VARCHAR2(2),
    PRI_LOGO_GROUP_IND             VARCHAR2(3),
    PRI_LOGO_GROUP_IND_DESCRIPTION VARCHAR2(4000),
    SCD_LOGO_GROUP_IND             VARCHAR2(3),
    SCD_LOGO_GROUP_IND_DESCRIPTION VARCHAR2(4000),
    COLOR_CONSULTANT_TYPE          XMLTYPE ,
    PCC_PCL_STORE                  XMLTYPE ,
    FAX_PHONE_NUMBER              VARCHAR2(4000),
    TYPE_CODE                     VARCHAR2(4000),
    STATUS_CODE                   VARCHAR2(1),
    POLLING_IND                   VARCHAR2(1),
    POLLING_START_DATE            DATE,
    POLLING_STOP_DATE             DATE,
    POLLING_STATUS_CODE           VARCHAR2(1),
    POLLING_STATUS_COD_DESC       VARCHAR2(100),
    TERR_HOME_STORE_NO            VARCHAR2(6),
    FIRST_NAME                    VARCHAR2(150),
    MIDDLE_INITIAL                VARCHAR2(60),
    LAST_NAME                     VARCHAR2(150),
    ADMIN_COST_CNTR_TYPE          VARCHAR2(5),
    TERRITORY_TYPE_BUSN_CODE      VARCHAR2(2),
    TERRITORY_TYPE_BUSN_CODE_DESC VARCHAR2(4000),
    STD_COST_IDENTIFIER           VARCHAR2(2),
    PRIM_COST_IDENTIFIER          VARCHAR2(2),
    INVENTORY_INDICATOR           VARCHAR2(1),
    PERP_INV_START_DATE           DATE,
    RURAL_METRO_ZONE_CODE         VARCHAR2(1),
    TYPE_CODE_DESCRIPTION         VARCHAR2(4000),
    STORE_EMAIL                   VARCHAR2(31),
    BOOK_PLN_PROFILE_CD           VARCHAR2(2),
    SPRAY_EQP_RPR_IND             VARCHAR2(1),
    CLASSIFICATION_CODE           VARCHAR2(2),
    CLASSIFICATION_CODE_DESC      VARCHAR2(100),
    SELLING_STORE_FLAG            VARCHAR2(1),
    POP_KIT_CODE                  VARCHAR2(1),
    POP_KIT_CODE_DESC             VARCHAR2(4000),
    SALES_VOL_CLASS_CODE          VARCHAR2(2),
    SALES_VOL_CLASS_CODE_DESC     VARCHAR2(100),
    LONGITUDE                     VARCHAR2(4000),
    LATITUDE                      VARCHAR2(4000),
    LEASING_SALES_SQ_FT           NUMBER,
    LEASING_TOTAL_SQ_FT           NUMBER,
    LEASE_OR_OWNED                VARCHAR2(1),
    CC_MGR_NAME                   VARCHAR2(4000),
    LOAD_DATE                     DATE
  );

CREATE INDEX COST_CENTER_VIEW_MNT_SNAP_INDX ON COST_CENTER_VIEW_MONTHLY_SNAP (LOAD_DATE);
