CREATE TABLE TEMP_SALES_VOLUME_CLASS
(
  COST_CENTER_CODE      VARCHAR2(4 BYTE),
  FUNCTION              VARCHAR2(2 BYTE),
  MAINTENANCE_TYPE      VARCHAR2(2 BYTE),
  MAINTENANCE_CODE      VARCHAR2(1 BYTE),
  SALES_VOL_CLASS_CODE  VARCHAR2(2 BYTE),
  EFFECTIVE_DATE        VARCHAR2(8 BYTE),
  EXPIRATION_DATE       VARCHAR2(8 BYTE),
  YEAR_TTL_SALES        VARCHAR2(9 BYTE),
  YEAR_OPER_PROFT       VARCHAR2(9 BYTE)
)
ORGANIZATION EXTERNAL
  (  TYPE ORACLE_LOADER
     DEFAULT DIRECTORY CCN_DATAFILES
     ACCESS PARAMETERS 
       ( RECORDS DELIMITED BY NEWLINE
         BADFILE CCN_DATAFILES:'SALES_VOLUME_CLASS_PROCESS.bad'
         LOGFILE CCN_DATAFILES:'SALES_VOLUME_CLASS_PROCESS.log'
         DISCARDFILE CCN_DATAFILES:'SALES_VOLUME_CLASS_PROCESS.dsc'
         FIELDS
         MISSING FIELD VALUES ARE NULL      
(
COST_CENTER_CODE     POSITION(8:11),
FUNCTION             POSITION(12:13),
MAINTENANCE_TYPE     POSITION(14:15),
MAINTENANCE_CODE     POSITION(16:16),
SALES_VOL_CLASS_CODE POSITION(17:18),
EFFECTIVE_DATE       POSITION(19:26),
EXPIRATION_DATE      POSITION(27:34),
YEAR_TTL_SALES       POSITION(35:43),
YEAR_OPER_PROFT      POSITION(44:52)
)
          )
     LOCATION (CCN_DATAFILES:'can.txt')
  );