 CREATE OR REPLACE VIEW TERRITORY_VW AS
  SELECT 
/*******************************************************************************
This View will give all the details from the TERRITORY table including the status of the cost center

Created  : 03/06/2018 nxk927 CCN Project....
Modified : 
*******************************************************************************/
        T.COST_CENTER_CODE,
       (SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE= T.COST_CENTER_CODE) COST_CENTER_NAME,
       T.CATEGORY,
       NVL(CCN_PICK_LIST_PKG.GET_CODE_DETAIL_VALUE_DSCRPTN('CATEGORY','COD',CATEGORY),'N/A') TERRITORY_CATEGORY,
       T.LEASE_CAR_INDICATOR,
       T.HOME_STORE,
       (SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE= T.HOME_STORE) HOME_STORE_NAME,
       T.TERRITORY_TYPE_BUSN_CODE,
       NVL(CCN_PICK_LIST_PKG.GET_CODE_DETAIL_VALUE_DSCRPTN('TERRITORY_TYPE_BUSN_CODE','COD',TERRITORY_TYPE_BUSN_CODE),'N/A') TERRITORY_TYPE_BUSN_CODE_DESC,
       S.STATUS_CODE,
       NVL(CCN_PICK_LIST_PKG.GET_CODE_DETAIL_VALUE_DSCRPTN('STATUS_CODE','COD',STATUS_CODE),'N/A') STATUS_CODE_DESC
  FROM TERRITORY T, STATUS S
 WHERE T.COST_CENTER_CODE = S.COST_CENTER_CODE
   AND S.EXPIRATION_DATE IS NULL;