CREATE OR REPLACE TYPE address_can_ot UNDER address_ot (
ADDRESS_LINE_1             VARCHAR2(35),
ADDRESS_LINE_2             VARCHAR2(35),
ADDRESS_LINE_3             VARCHAR2(35),
CITY                       VARCHAR2(25),
PROVINCE_CODE             VARCHAR2(2),
POSTAL_CODE               VARCHAR2(6),
VALID_ADDRESS             VARCHAR2(1),
COUNTRY_CODE              VARCHAR2(3),

CONSTRUCTOR FUNCTION address_can_ot(IN_COST_CENTER_CODE IN    VARCHAR2,
                                    IN_ADDRESS_TYPE     IN    VARCHAR2) RETURN SELF AS RESULT,

OVERRIDING MEMBER FUNCTION print_header_delimited(IN_DELIMITER    IN    VARCHAR2) RETURN VARCHAR2,

OVERRIDING MEMBER FUNCTION print_values_delimited(IN_DELIMITER        IN    VARCHAR2) RETURN VARCHAR2
);