CREATE OR REPLACE TYPE address_ot AS OBJECT (
COST_CENTER_CODE   VARCHAR2(6),
ADDRESS_TYPE       VARCHAR2(2),
EFFECTIVE_DATE     DATE,
EXPIRATION_DATE    DATE,

MEMBER FUNCTION print_header_delimited(IN_DELIMITER    IN    VARCHAR2) RETURN VARCHAR2,

MEMBER FUNCTION print_values_delimited(IN_DELIMITER        IN    VARCHAR2) RETURN VARCHAR2
) NOT INSTANTIABLE NOT FINAL;