  CREATE TABLE TEMP_LEAD_BANK_CC 
   (BANK_ACCOUNT_NBR VARCHAR2(16), 
	COST_CENTER_CODE VARCHAR2(6), 
	EFFECTIVE_DATE VARCHAR2(8), 
	EXPIRATION_DATE VARCHAR2(8), 
	BANK_BRANCH_NBR VARCHAR2(8), 
	BANK_TYPE_CODE VARCHAR2(1)
   ) 
   ORGANIZATION EXTERNAL 
    ( TYPE ORACLE_LOADER
      DEFAULT DIRECTORY "BANKING_LOAD_FILES"
	  ACCESS PARAMETERS
      ( RECORDS DELIMITED BY NEWLINE
        badfile BANKING_LOAD_FILES:'TEMP_BANK_CC_ASSIGNMENT.bad'
        logfile BANKING_LOAD_FILES:'TEMP_BANK_CC_ASSIGNMENT.log'
        discardfile BANKING_LOAD_FILES:'TEMP_BANK_CC_ASSIGNMENT.dsc'
        FIELDS MISSING FIELD VALUES ARE NULL
      (
        BANK_ACCOUNT_NBR CHAR(16), 
        COST_CENTER_CODE CHAR(6),
        EFFECTIVE_DATE   CHAR(8), 
        EXPIRATION_DATE  CHAR(8), 
        BANK_BRANCH_NBR  CHAR(8), 
        BANK_TYPE_CODE   CHAR(1)
       )
         )
      LOCATION
       ( 'CCN99CTR_BNKCNTR.TXT'
       )
    );

	/