  CREATE TABLE TEMP_DEP_TICKOAK 
   (DEPOSIT_TICKET_OOAK VARCHAR2(8), 
	REORDER_POINT VARCHAR2(5), 
	REORDER_NUMBER_BKS VARCHAR2(5), 
	IMAGES_PER_PAGE VARCHAR2(1), 
	NBR_FORMS_PER_BK VARCHAR2(5), 
	PART_PAPER_PER_FORM VARCHAR2(1), 
	NBR_DEP_TICKETS_PER_BK VARCHAR2(5), 
	SHEETS_OF_PAPER_PER_BK VARCHAR2(5), 
	DEP_BAG_TYPE VARCHAR2(1), 
	DEP_BAG_REORDER_POINT VARCHAR2(5), 
	DEPBAG_REORDER_QTY VARCHAR2(5), 
	EFFECTIVE_DATE VARCHAR2(8), 
	EXPIRATION_DATE VARCHAR2(8), 
	LAST_MAINTENANCE_DATE VARCHAR2(8), 
	LAST_MAINT_USER_ID VARCHAR2(6), 
	FILLER VARCHAR2(1)
   ) 
   ORGANIZATION EXTERNAL 
    ( TYPE ORACLE_LOADER
      DEFAULT DIRECTORY "BANKING_LOAD_FILES"
	  ACCESS PARAMETERS
      ( RECORDS DELIMITED BY NEWLINE
        badfile BANKING_LOAD_FILES:'TEMP_DEP_TICKOAK.bad'
        logfile BANKING_LOAD_FILES:'TEMP_DEP_TICKOAK.log'
        discardfile BANKING_LOAD_FILES:'TEMP_DEP_TICKOAK.dsc'
        FIELDS MISSING FIELD VALUES ARE NULL
      (
        DEPOSIT_TICKET_OOAK    CHAR(8),
        REORDER_POINT          CHAR(5),
        REORDER_NUMBER_BKS     CHAR(5),
        IMAGES_PER_PAGE        CHAR(1),
        NBR_FORMS_PER_BK       CHAR(5),
        PART_PAPER_PER_FORM    CHAR(1),
        NBR_DEP_TICKETS_PER_BK CHAR(5),
        SHEETS_OF_PAPER_PER_BK CHAR(5),
        DEP_BAG_TYPE           CHAR(1),
        DEP_BAG_REORDER_POINT  CHAR(5),
        DEPBAG_REORDER_QTY     CHAR(5),
        EFFECTIVE_DATE         CHAR(8),
        EXPIRATION_DATE        CHAR(8),
        LAST_MAINTENANCE_DATE  CHAR(8),
        LAST_MAINT_USER_ID     CHAR(6),
        FILLER                 CHAR(1)
       )
         )
      LOCATION
       ( 'CCN99CTR_TICKOAK.TXT'
       )
    );

	/