 CREATE TABLE TEMP_DEP_TICKORD_DLY 
   (BANK_ACCOUNT_NBR VARCHAR2(16), 
	COST_CENTER_CODE VARCHAR2(6), 
	DEPOSIT_ORDER_PRIORITY VARCHAR2(3), 
	DEPOSIT_ORDER_STATUS VARCHAR2(1), 
	COST_CENTER VARCHAR2(4), 
	DEPOSIT_ORDER_SEQ_NBR VARCHAR2(3), 
	EFFECTIVE_DATE VARCHAR2(8), 
	EXPIRATION_DATE VARCHAR2(8), 
	LAST_MAINTENANCE_DATE VARCHAR2(8), 
	LAST_MAINT_USER_ID VARCHAR2(6), 
	ORDER_DATE VARCHAR2(8), 
	EXTRACTED_USER_ID VARCHAR2(8), 
	FILLER VARCHAR2(1)
   ) 
   ORGANIZATION EXTERNAL 
    ( TYPE ORACLE_LOADER
      DEFAULT DIRECTORY "BANKING_LOAD_FILES"
	  ACCESS PARAMETERS
      ( RECORDS DELIMITED BY NEWLINE
        badfile BANKING_LOAD_FILES:'TEMP_DEP_TICKORD_DLY.bad'
        logfile BANKING_LOAD_FILES:'TEMP_DEP_TICKORD_DLY.log'
        discardfile BANKING_LOAD_FILES:'TEMP_DEP_TICKORD_DLY.dsc'
        FIELDS MISSING FIELD VALUES ARE NULL
      (
        BANK_ACCOUNT_NBR        CHAR(16),
        COST_CENTER_CODE        CHAR(6),
        DEPOSIT_ORDER_PRIORITY  CHAR(3),
        DEPOSIT_ORDER_STATUS    CHAR(1),
        COST_CENTER             CHAR(4),
        DEPOSIT_ORDER_SEQ_NBR   CHAR(3),
        EFFECTIVE_DATE          CHAR(8),
        EXPIRATION_DATE         CHAR(8),
        LAST_MAINTENANCE_DATE   CHAR(8),
        LAST_MAINT_USER_ID      CHAR(6),
        ORDER_DATE              CHAR(8),
        EXTRACTED_USER_ID       CHAR(8),
        FILLER                  CHAR(1)
       )
         )
      LOCATION
       ( 'CCN08100_TCKORD.TXT'
       )
    );
/