 CREATE TABLE TEMP_ACH_DRFTS_EXT_CTRL
   (COST_CENTER_CODE VARCHAR2(4),
    CENTURY          VARCHAR2(1),
    TRANSACTION_DATE VARCHAR2(6),
    BANK_DEP_AMT     VARCHAR2(10),
    BANK_ACCOUNT_NBR VARCHAR2(17)
   )
   ORGANIZATION EXTERNAL
    ( TYPE ORACLE_LOADER
      DEFAULT DIRECTORY "BANKING_LOAD_FILES"
      ACCESS PARAMETERS
      ( RECORDS DELIMITED BY NEWLINE
        badfile BANKING_LOAD_FILES:'TEMP_ACH_DRFTS_EXT_CTRL.bad'
        logfile BANKING_LOAD_FILES:'TEMP_ACH_DRFTS_EXT_CTRL.log'
        discardfile BANKING_LOAD_FILES:'TEMP_ACH_DRFTS_EXT_CTRL.dsc'
        FIELDS( COST_CENTER_CODE  CHAR(4),
                CENTURY           CHAR(1),
                TRANSACTION_DATE  CHAR(6),
                BANK_DEP_AMT      CHAR(10),
                BANK_ACCOUNT_NBR  CHAR(17))
                  )
      LOCATION
       ( 'SRA10910.TXT'
       )
    );