  CREATE TABLE TEMP_MICR_FORMAT 
   (BANK_ACCOUNT_NBR VARCHAR2(16), 
	FORMAT_NAME VARCHAR2(6), 
	DJDE_FORM_PARM VARCHAR2(6), 
	DJDE_FEED_PARM VARCHAR2(5), 
	MICR_COST_CNTR VARCHAR2(8), 
	MICR_ROUTING_NBR VARCHAR2(11), 
	MICR_FORMAT_ACTNBR VARCHAR2(17), 
	REORDER_POINT VARCHAR2(5), 
	REORDER_NUMBER_BKS VARCHAR2(5), 
	IMAGES_PER_PAGE VARCHAR2(1), 
	NBR_FORMS_PER_BK VARCHAR2(5), 
	PART_PAPER_PER_FORM VARCHAR2(1), 
	NBR_DEP_TICKETS_PER_BK VARCHAR2(5), 
	SHEETS_OF_PAPER_PER_BK VARCHAR2(5), 
	EFFECTIVE_DATE VARCHAR2(8), 
	EXPIRATION_DATE VARCHAR2(8), 
	LAST_MAINTENANCE_DATE VARCHAR2(8), 
	LAST_MAINT_USER_ID VARCHAR2(6)
   ) 
   ORGANIZATION EXTERNAL 
    ( TYPE ORACLE_LOADER
      DEFAULT DIRECTORY "BANKING_LOAD_FILES"
	  ACCESS PARAMETERS
      ( RECORDS DELIMITED BY NEWLINE
        badfile BANKING_LOAD_FILES:'TEMP_MICR_FORMAT.bad'
        logfile BANKING_LOAD_FILES:'TEMP_MICR_FORMAT.log'
        discardfile BANKING_LOAD_FILES:'TEMP_MICR_FORMAT.dsc'
        FIELDS MISSING FIELD VALUES ARE NULL
      (
        BANK_ACCOUNT_NBR        CHAR(16),
        FORMAT_NAME             CHAR(6),
        DJDE_FORM_PARM          CHAR(6),
        DJDE_FEED_PARM          CHAR(5),
        MICR_COST_CNTR          CHAR(8),
        MICR_ROUTING_NBR        CHAR(11),
        MICR_FORMAT_ACTNBR      CHAR(17),
        REORDER_POINT           CHAR(5),
        REORDER_NUMBER_BKS      CHAR(5),
        IMAGES_PER_PAGE         CHAR(1),
        NBR_FORMS_PER_BK        CHAR(5),
        PART_PAPER_PER_FORM     CHAR(1),
        NBR_DEP_TICKETS_PER_BK  CHAR(5),
        SHEETS_OF_PAPER_PER_BK  CHAR(5),
        EFFECTIVE_DATE          CHAR(8),
        EXPIRATION_DATE         CHAR(8),
        LAST_MAINTENANCE_DATE   CHAR(8),
        LAST_MAINT_USER_ID      CHAR(6)
       )
         )
      LOCATION
       ( 'CCN99CTR_BNKMICR.TXT'
       )
    );

	/