DROP TABLE TEMP_ACH_DRFTS_EXT_CTRL;

CREATE TABLE TEMP_ACH_DRFTS_EXT_CTRL
   (COST_CENTER_CODE VARCHAR2(4 BYTE),
    BANK_DEP_AMT VARCHAR2(12 BYTE),
    BANK_ACCOUNT_NBR VARCHAR2(25 BYTE)
   )
   ORGANIZATION EXTERNAL
    ( TYPE ORACLE_LOADER
      DEFAULT DIRECTORY "BANKING_LOAD_FILES"
      ACCESS PARAMETERS
      ( RECORDS DELIMITED BY NEWLINE
       badfile BANKING_LOAD_FILES:'TEMP_UAR_ACH.bad'
        logfile BANKING_LOAD_FILES:'TEMP_UAR_ACH.log'
        discardfile BANKING_LOAD_FILES:'TEMP_UAR_ACH.dsc'
        LOAD WHEN ((1:3) = '627')
         FIELDS missing field values are null
         (COST_CENTER_CODE POSITION(40:44)   CHAR(4),
          BANK_DEP_AMT     POSITION(30:40)   CHAR(10),
          BANK_ACCOUNT_NBR POSITION(13:29)   CHAR(17))
                        )
      LOCATION
       ( 'stores_ach.txt'
       )
    );
