  CREATE TABLE TEMP_DEP_TICK_DLY 
   (BANK_ACCOUNT_NBR VARCHAR2(16), 
	COST_CENTER_CODE VARCHAR2(6), 
	DAILY_USE_ACTUAL VARCHAR2(3), 
	DAILY_USE_OVERRIDE VARCHAR2(3), 
	DEP_TKTS_ONHAND_QTY VARCHAR2(5), 
	YTD_DEP_TKTS_ORDERED_QTY VARCHAR2(5), 
	DJDE_FORM_PARM VARCHAR2(6), 
	DJDE_FEED_PARM VARCHAR2(5), 
	MICR_COST_CNTR VARCHAR2(8), 
	MICR_ROUTING_NBR VARCHAR2(11), 
	MICR_FORMAT_ACCT_NBR VARCHAR2(17), 
	REORDER_POINT VARCHAR2(5), 
	REORDER_NUMBER_BKS VARCHAR2(5), 
	IMAGES_PER_PAGE VARCHAR2(1), 
	NBR_FORMS_PER_BK VARCHAR2(5), 
	PART_PAPER_PER_FORM VARCHAR2(1), 
	NBR_DEP_TICKETS_PER_BK VARCHAR2(5), 
	SHEETS_OF_PAPER_PER_BK VARCHAR2(5), 
	FORMAT_NAME VARCHAR2(6), 
	DEPBAG_DAILY_USE_ACTUAL VARCHAR2(5), 
	DEPBAG_DLY_USE_OVERRIDE VARCHAR2(5), 
	DEPBAG_ONHAND_QTY VARCHAR2(5), 
	DEPBAG_YTD_ORDERED_QTY VARCHAR2(5), 
	DEPBAG_LAST_ORDER_DATE VARCHAR2(8), 
	DEPBAG_LAST_ORDER_QTY VARCHAR2(5), 
	DEP_BAG_TYPE VARCHAR2(1), 
	DEP_BAG_REORDER_POINT VARCHAR2(5), 
	DEPBAG_REORDER_QTY VARCHAR2(5), 
	EFFECTIVE_DATE VARCHAR2(8), 
	EXPIRATION_DATE VARCHAR2(8), 
	LAST_MAINTENANCE_DATE VARCHAR2(8), 
	LAST_MAINT_USER_ID VARCHAR2(6), 
	FILLER VARCHAR2(1)
   ) 
   ORGANIZATION EXTERNAL 
    ( TYPE ORACLE_LOADER
      DEFAULT DIRECTORY "BANKING_LOAD_FILES" 
	  ACCESS PARAMETERS
      ( RECORDS DELIMITED BY NEWLINE
        badfile BANKING_LOAD_FILES:'TEMP_DEP_TICK_DLY.bad'
        logfile BANKING_LOAD_FILES:'TEMP_DEP_TICK_DLY.log'
        discardfile BANKING_LOAD_FILES:'TEMP_DEP_TICK_DLY.dsc'
        FIELDS MISSING FIELD VALUES ARE NULL
      (
        BANK_ACCOUNT_NBR         CHAR(16),
        COST_CENTER_CODE         CHAR(6),
        DAILY_USE_ACTUAL         CHAR(3),
        DAILY_USE_OVERRIDE       CHAR(3),
        DEP_TKTS_ONHAND_QTY      CHAR(5),
        YTD_DEP_TKTS_ORDERED_QTY CHAR(5),
        DJDE_FORM_PARM           CHAR(6),
        DJDE_FEED_PARM           CHAR(5),
        MICR_COST_CNTR           CHAR(8),
        MICR_ROUTING_NBR         CHAR(11),
        MICR_FORMAT_ACCT_NBR     CHAR(17),
        REORDER_POINT            CHAR(5),
        REORDER_NUMBER_BKS       CHAR(5),
        IMAGES_PER_PAGE          CHAR(1),
        NBR_FORMS_PER_BK         CHAR(5),
        PART_PAPER_PER_FORM      CHAR(1),
        NBR_DEP_TICKETS_PER_BK   CHAR(5),
        SHEETS_OF_PAPER_PER_BK   CHAR(5),
        FORMAT_NAME              CHAR(6),
        DEPBAG_DAILY_USE_ACTUAL  CHAR(5),
        DEPBAG_DLY_USE_OVERRIDE  CHAR(5),
        DEPBAG_ONHAND_QTY        CHAR(5),
        DEPBAG_YTD_ORDERED_QTY   CHAR(5),
        DEPBAG_LAST_ORDER_DATE   CHAR(8),
        DEPBAG_LAST_ORDER_QTY    CHAR(5),
        DEP_BAG_TYPE             CHAR(1),
        DEP_BAG_REORDER_POINT    CHAR(5),
        DEPBAG_REORDER_QTY       CHAR(5),
        EFFECTIVE_DATE           CHAR(8),
        EXPIRATION_DATE          CHAR(8),
        LAST_MAINTENANCE_DATE    CHAR(8),
        LAST_MAINT_USER_ID       CHAR(6),
        FILLER                   CHAR(1)
       )
          )
      LOCATION
       ( BANKING_LOAD_FILES:'CCN08100_DEPTKT.TXT'
       )
    );
/