CREATE TABLE TEMP_BANK_ACCOUNT 
   (BANK_ACCOUNT_NBR VARCHAR2(16), 
	EFFECTIVE_DATE VARCHAR2(8), 
	EXPIRATION_DATE VARCHAR2(8), 
	BANK_NAME VARCHAR2(30), 
	BOOK_KEEPER_NBR VARCHAR2(2), 
	STATEMENT_TYPE VARCHAR2(2), 
	BANK_AUTO_RECON_IND VARCHAR2(1), 
	RECON_START_DATE VARCHAR2(8), 
	RECON_BANK_ACCOUNT_NBR VARCHAR2(16), 
	JV_BOOK_KEEPER_REF VARCHAR2(6), 
	JV_BANK_SHORT_NAME VARCHAR2(6), 
	IDI_BOOKKEEPER_REF VARCHAR2(6), 
	IDI_BANK_SHORT_NAME VARCHAR2(6), 
	ROUTING_NBR VARCHAR2(9)
   ) 
   ORGANIZATION EXTERNAL 
    ( TYPE ORACLE_LOADER
      DEFAULT DIRECTORY "BANKING_LOAD_FILES"
	  ACCESS PARAMETERS
      ( RECORDS DELIMITED BY NEWLINE
        badfile BANKING_LOAD_FILES:'TEMP_BANK_ACCOUNT.bad'
        logfile BANKING_LOAD_FILES:'TEMP_BANK_ACCOUNT.log'
        discardfile BANKING_LOAD_FILES:'TEMP_BANK_ACCOUNT.dsc'
        FIELDS MISSING FIELD VALUES ARE NULL
      (
        BANK_ACCOUNT_NBR        CHAR(16),
        EFFECTIVE_DATE          CHAR(8),
        EXPIRATION_DATE         CHAR(8),
        BANK_NAME               CHAR(30),
        BOOK_KEEPER_NBR         CHAR(2),
        STATEMENT_TYPE          CHAR(2),
        BANK_AUTO_RECON_IND     CHAR(1),
        RECON_START_DATE        CHAR(8),
        RECON_BANK_ACCOUNT_NBR  CHAR(16),
        JV_BOOK_KEEPER_REF      CHAR(6),
        JV_BANK_SHORT_NAME      CHAR(6),
        IDI_BOOKKEEPER_REF      CHAR(6),
        IDI_BANK_SHORT_NAME     CHAR(6),
        ROUTING_NBR             CHAR(9)
       )
         )
      LOCATION
       ( 'CCN99CTR_BNKACCT.TXT'
       )
    );
	
/