  CREATE TABLE TEMP_BANK_SUB_ACCOUNT 
   (TABLE_NAME VARCHAR2(8), 
	TABLE_ARGUMENT VARCHAR2(32), 
	TABLE_RESULT VARCHAR2(100), 
	FILLER VARCHAR2(1)
   ) 
   ORGANIZATION EXTERNAL 
    ( TYPE ORACLE_LOADER
      DEFAULT DIRECTORY "BANKING_LOAD_FILES" 
	  ACCESS PARAMETERS
      ( RECORDS DELIMITED BY NEWLINE
        badfile BANKING_LOAD_FILES:'TEMP_BANK_SUB_ACCOUNT.bad'
        logfile BANKING_LOAD_FILES:'TEMP_BANK_SUB_ACCOUNT.log'
        discardfile BANKING_LOAD_FILES:'TEMP_BANK_SUB_ACCOUNT.dsc'
        FIELDS MISSING FIELD VALUES ARE NULL
      (
        TABLE_NAME     CHAR(8), 
        TABLE_ARGUMENT CHAR(32), 
        TABLE_RESULT   CHAR(100), 
        FILLER         CHAR(1)
       )
         )
      LOCATION
       ( 'CCN99CTR_SUBACCTS.TXT'
       )
    );

   /