  CREATE TABLE TEMP_MEMBER_BANK_CC 
   (LEAD_STORE_NBR VARCHAR2(6), 
	MEMBER_STORE_NBR VARCHAR2(6), 
	EFFECTIVE_DATE VARCHAR2(8), 
	EXPIRATION_DATE VARCHAR2(8), 
	BANK_BRANCH_NBR VARCHAR2(8), 
	BANK_ACCOUNT_NUMBER VARCHAR2(16)
   ) 
   ORGANIZATION EXTERNAL 
    ( TYPE ORACLE_LOADER
      DEFAULT DIRECTORY "BANKING_LOAD_FILES"
	  ACCESS PARAMETERS
      ( RECORDS DELIMITED BY NEWLINE
        badfile BANKING_LOAD_FILES:'TEMP_BANK_CONC.bad'
        logfile BANKING_LOAD_FILES:'TEMP_BANK_CONC.log'
        discardfile BANKING_LOAD_FILES:'TEMP_BANK_CONC.dsc'
        FIELDS MISSING FIELD VALUES ARE NULL
      (
        LEAD_STORE_NBR   CHAR(6), 
        MEMBER_STORE_NBR CHAR(6),
        EFFECTIVE_DATE   CHAR(8), 
        EXPIRATION_DATE  CHAR(8), 
        BANK_BRANCH_NBR  CHAR(8),
        BANK_ACCOUNT_NUMBER CHAR(16)
       )
             )
      LOCATION
       ( 'CCN99CTR_BNKCONC.TXT'
       )
    );
	/