/*
   Create synonym for common_tools for Fieldpayroll
*/
GRANT EXECUTE ON COMMON_TOOLS TO FLDPRRPT;

CREATE OR REPLACE SYNONYM FLDPRRPT.COMMON_TOOLS FOR COSTCNTR.COMMON_TOOLS;


GRANT SELECT ON DISPATCH_TERMINAL_VW TO FLDPRRPT;

CREATE OR REPLACE SYNONYM FLDPRRPT.DISPATCH_TERMINAL_VW FOR COSTCNTR.DISPATCH_TERMINAL_VW;


