/*
Created: 03/14/2018 nxk927 
         this will update the polling start date and stop date and drop the temp table
*/
DECLARE
CURSOR CUR IS
   SELECT *
     FROM TMP_POLLING_START_STOP_INTLOAD;
BEGIN
   FOR REC IN CUR LOOP
      UPDATE POLLING
         SET POLLING_START_DATE = TO_DATE(REC.POLLING_START_DATE, 'MM/DD/YYYY'), 
             POLLING_STOP_DATE  = TO_DATE(REC.POLLING_STOP_DATE, 'MM/DD/YYYY')
       WHERE SUBSTR(COST_CENTER_CODE,3) = REC.COST_CENTER_CODE
         AND EXPIRATION_DATE IS NULL
         AND CURRENT_FLAG = 'Y';
   END LOOP;
   COMMIT;
END;


/
DROP TABLE TMP_POLLING_START_STOP_INTLOAD;
/