/*********************************************************************************
   This script is for inserting GL_DIVISION A100
   
   created : 11/27/2018  JXC517/SXH487 CCN Project
*********************************************************************************/
INSERT INTO CUSTOMER_DEPOSIT_DETAILS
SELECT *
  FROM CUST_DEP_DET_BEFORE_01SEP
 WHERE GL_DIVISION NOT IN ('A100')
   AND TRANSACTION_DATE < '01-SEP-2017';

COMMIT;

DECLARE
   V_LOAD_DATE      DATE;
   V_CREDIT_ROW     CUST_DEP_CREDIT_DETAILS%ROWTYPE;
   V_REDEMPTION_ROW CUST_DEP_REDEMPTION_DETAILS%ROWTYPE;   
   V_ORIG_DEP_NBR   CUSTOMER_DEPOSIT_DETAILS.TRANSACTION_NUMBER%TYPE;
   V_ORIG_TERM_NBR  CUSTOMER_DEPOSIT_DETAILS.TERMINAL_NUMBER%TYPE;
   V_ORIG_TRAN_DATE CUSTOMER_DEPOSIT_DETAILS.TRANSACTION_DATE%TYPE;
   V_NET_BAL        NUMBER;

    CURSOR main_cur IS
        SELECT DISTINCT CUSTOMER_ACCOUNT_NUMBER
          FROM CUSTOMER_DEPOSIT_DETAILS
         WHERE GL_DIVISION NOT IN ('A100')
           AND TRANSACTION_DATE < '01-SEP-2017'
          ORDER BY CUSTOMER_ACCOUNT_NUMBER;

    CURSOR Account_det (IN_CUST_ACCOUNT_NBR VARCHAR2) IS
           SELECT D.*, ROWID 
             FROM CUSTOMER_DEPOSIT_DETAILS D 
            WHERE D.CUSTOMER_ACCOUNT_NUMBER = IN_CUST_ACCOUNT_NBR
            ORDER BY D.CUSTOMER_ACCOUNT_NUMBER, D.TRAN_TIMESTAMP;
BEGIN
    FOR rec IN main_cur LOOP
       DELETE FROM CUST_DEP_REDEMPTION_DETAILS R WHERE R.CUSTOMER_ACCOUNT_NUMBER = rec.CUSTOMER_ACCOUNT_NUMBER;
       DELETE FROM CUST_DEP_CREDIT_DETAILS C     WHERE C.CUSTOMER_ACCOUNT_NUMBER = rec.CUSTOMER_ACCOUNT_NUMBER;

       V_NET_BAL :=0;
       FOR rec1 IN Account_det(rec.CUSTOMER_ACCOUNT_NUMBER) LOOP
           V_NET_BAL  := V_NET_BAL + rec1.CSTMR_DPST_SALES_LN_ITM_AMT;
           UPDATE CUSTOMER_DEPOSIT_DETAILS
              SET CUSTOMER_NET_BALANCE    = V_NET_BAL
            WHERE ROWID                = rec1.ROWID
              AND CUSTOMER_NET_BALANCE <> V_NET_BAL;

           IF rec1.TRANSACTION_TYPE = 'DEPOSIT' THEN
               V_CREDIT_ROW.CREDIT_ID                := SEQ_CREDIT_ID.nextval;
               V_CREDIT_ROW.COST_CENTER_CODE         := rec1.COST_CENTER_CODE;
               V_CREDIT_ROW.CUSTOMER_ACCOUNT_NUMBER  := rec1.CUSTOMER_ACCOUNT_NUMBER;
               V_CREDIT_ROW.TRANSACTION_NUMBER       := rec1.TRANSACTION_NUMBER;
               V_CREDIT_ROW.TRANSACTION_DATE         := rec1.TRANSACTION_DATE;
               V_CREDIT_ROW.TERMINAL_NUMBER          := rec1.TERMINAL_NUMBER;           
               V_CREDIT_ROW.DEPOSIT_REMAINING_BAL    := rec1.CSTMR_DPST_SALES_LN_ITM_AMT;
               V_CREDIT_ROW.TRAN_TIMESTAMP           := rec1.TRAN_TIMESTAMP;
               V_CREDIT_ROW.LOAD_DATE                := rec1.LOAD_DATE;
               TABLE_IU_PKG.CUST_DEPOSIT_CREDIT_I_SP(V_CREDIT_ROW);
           END IF;
           IF rec1.TRANSACTION_TYPE = 'REDEMPTION' THEN
               CUSTOMER_DEPOSIT_MAINT_PKG.ORIG_DEP_REM_BAL_UPD(rec1.CSTMR_DPST_SALES_LN_ITM_AMT,
                                                               rec1.CUSTOMER_ACCOUNT_NUMBER,
                                                               rec1.TRANSACTION_DATE,
                                                               V_ORIG_DEP_NBR,
                                                               V_ORIG_TERM_NBR,
                                                               V_ORIG_TRAN_DATE);

               V_REDEMPTION_ROW.REDEMPTION_ID            := SEQ_REDEMPTION_ID.nextval;
               V_REDEMPTION_ROW.COST_CENTER_CODE         := rec1.COST_CENTER_CODE;
               V_REDEMPTION_ROW.CUSTOMER_ACCOUNT_NUMBER  := rec1.CUSTOMER_ACCOUNT_NUMBER;
               V_REDEMPTION_ROW.TRANSACTION_NUMBER       := rec1.TRANSACTION_NUMBER;
               V_REDEMPTION_ROW.TRANSACTION_DATE         := rec1.TRANSACTION_DATE;
               V_REDEMPTION_ROW.TERMINAL_NUMBER          := rec1.TERMINAL_NUMBER;
               V_REDEMPTION_ROW.ORIGINAL_DEP_TRANS_NBR   := V_ORIG_DEP_NBR;  
               V_REDEMPTION_ROW.ORIGINAL_DEP_TERM_NBR    := V_ORIG_TERM_NBR;
               V_REDEMPTION_ROW.ORIGINAL_DEP_TRAN_DATE   := V_ORIG_TRAN_DATE;
               V_REDEMPTION_ROW.TRAN_TIMESTAMP           := rec1.TRAN_TIMESTAMP;
               V_REDEMPTION_ROW.LOAD_DATE                := rec1.LOAD_DATE;

               TABLE_IU_PKG.CUST_DEPOSIT_REDEMPTION_I_SP(V_REDEMPTION_ROW);
           END IF;
       END LOOP;
       COMMIT;
   END LOOP;
END;
/

/*
SELECT * FROM CUSTOMER_DEPOSIT_DETAILS    WHERE CUSTOMER_ACCOUNT_NUMBER = '561225731' ORDER BY TRAN_TIMESTAMP;
SELECT * FROM CUST_DEP_CREDIT_DETAILS     WHERE CUSTOMER_ACCOUNT_NUMBER = '561225731' ORDER BY TRAN_TIMESTAMP;
SELECT * FROM CUST_DEP_REDEMPTION_DETAILS WHERE CUSTOMER_ACCOUNT_NUMBER = '561225731' ORDER BY TRAN_TIMESTAMP;
*/