/*
     Created: 07/27/2018 sxh487 CCN Project Team..
     script to Truncate and backup the customer deposit tables
*/
CREATE TABLE CUST_DEP_ACCUMS_T_BKUP AS SELECT * FROM CUST_DEP_CCN_ACCUMS_T WHERE RLS_RUN_CYCLE IN (1333, 1334, 1335);
CREATE TABLE CCN_HEADERS_T_BKUP AS SELECT * FROM CCN_HEADERS_T WHERE RLS_RUN_CYCLE IN (1333, 1334, 1335);
CREATE TABLE CCN_SALES_LINES_T_BKUP AS SELECT * FROM CCN_SALES_LINES_T WHERE RLS_RUN_CYCLE IN (1333, 1334, 1335);

CREATE TABLE CUSTOMER_DEPOSIT_DET_BKUP1 AS SELECT * FROM CUSTOMER_DEPOSIT_DETAILS;
CREATE TABLE CUSTOMER_DEPOSIT_HEADER_BKUP AS SELECT * FROM CUSTOMER_DEPOSIT_HEADER;
CREATE TABLE CUST_DEP_REDEMPTION_DET_BKUP AS SELECT * FROM CUST_DEP_REDEMPTION_DETAILS;
CREATE TABLE CUST_DEP_CREDIT_DET_BKUP AS SELECT * FROM CUST_DEP_CREDIT_DETAILS;

TRUNCATE TABLE CUST_DEP_REDEMPTION_DETAILS;
TRUNCATE TABLE CUST_DEP_CREDIT_DETAILS;
TRUNCATE TABLE CUSTOMER_DEPOSIT_DETAILS;
TRUNCATE TABLE CUSTOMER_DEPOSIT_HEADER_HST;
TRUNCATE TABLE CUSTOMER_DEPOSIT_HEADER;
/
