--inserting the Deposits and Redemptions for the initial load
--created 04/09/2018 sxh487 
INSERT INTO CUST_DEP_CREDIT_DETAILS 
(
 CREDIT_ID,
 COST_CENTER_CODE,
 CUSTOMER_ACCOUNT_NUMBER,
 TRANSACTION_NUMBER,
 TRANSACTION_DATE,
 TERMINAL_NUMBER,
 LOAD_DATE,
 TRAN_TIMESTAMP)
SELECT SEQ_CREDIT_ID.nextval,
       COST_CENTER_CODE,
       CUSTOMER_ACCOUNT_NUMBER,
       TRANSACTION_NUMBER,
       TRANSACTION_DATE,
       TERMINAL_NUMBER,
       LOAD_DATE, 
       TRAN_TIMESTAMP
FROM CUSTOMER_DEPOSIT_DETAILS WHERE TRANSACTION_TYPE ='DEPOSIT';
       
INSERT INTO CUST_DEP_REDEMPTION_DETAILS 
(
 REDEMPTION_ID,
 COST_CENTER_CODE,
 CUSTOMER_ACCOUNT_NUMBER,
 TRANSACTION_NUMBER,
 TRANSACTION_DATE,
 TERMINAL_NUMBER,
 LOAD_DATE
)
SELECT SEQ_REDEMPTION_ID.nextval,
       COST_CENTER_CODE,
       CUSTOMER_ACCOUNT_NUMBER,
       TRANSACTION_NUMBER,
       TRANSACTION_DATE,
       TERMINAL_NUMBER,
       LOAD_DATE
FROM CUSTOMER_DEPOSIT_DETAILS WHERE TRANSACTION_TYPE ='REDEMPTION';

COMMIT;

--updating the DEPOSIT_REMAINING_BAL to the total_sales for the initial load
UPDATE CUST_DEP_CREDIT_DETAILS a
    SET DEPOSIT_REMAINING_BAL = (SELECT TOTAL_SALES
                                   FROM CUSTOMER_DEPOSIT_DETAILS
                                  WHERE CUSTOMER_ACCOUNT_NUMBER = a.CUSTOMER_ACCOUNT_NUMBER
                                    AND TRANSACTION_NUMBER = a.TRANSACTION_NUMBER
                                    AND TERMINAL_NUMBER = a.TERMINAL_NUMBER
                                    AND transaction_date =a.transaction_date
                                    AND COST_CENTER_CODE =a.COST_CENTER_CODE
                                    AND TRANSACTION_TYPE    = 'DEPOSIT');
COMMIT;          
