/*
     Created: 01/11/2019 pxa852 CCN Project Team..
     This script inserts data into a new table CUST_DEP_CRD_RED_DETAILS
     from CUST_DEP_CREDIT_DETAILS and CUST_DEP_REDEMPTION_DETAILS tables.
*/
SELECT COUNT(*) FROM CUST_DEP_CREDIT_DETAILS;
SELECT COUNT(*) from CUST_DEP_REDEMPTION_DETAILS;

INSERT INTO CUST_DEP_CRD_RED_DETAILS
(SELECT CRD_RED_SEQ.NEXTVAL,
        TRANSACTION_SQ_ID,
        TRANSACTION_TYPE,
        DEPOSIT_REMAINING_BAL,
        ORGNL_DEPOSIT_TERMINAL_NBR,
        ORGNL_DEPOSIT_TRANSACTION_NBR,
        ORGNL_DEPOSIT_TRANSACTION_DATE
   FROM (SELECT TRANSACTION_SQ_ID,
                'DEPOSIT' TRANSACTION_TYPE,
                DEPOSIT_REMAINING_BAL,
                NULL ORGNL_DEPOSIT_TERMINAL_NBR,
                NULL ORGNL_DEPOSIT_TRANSACTION_NBR,
                NULL ORGNL_DEPOSIT_TRANSACTION_DATE
            FROM CUST_DEP_CREDIT_DETAILS
         UNION ALL
         SELECT TRANSACTION_SQ_ID,
                'REDEMPTION' TRANSACTION_TYPE,
                NULL DEPOSIT_REMAINING_BAL,
                ORGNL_DEPOSIT_TERMINAL_NBR,
                ORGNL_DEPOSIT_TRANSACTION_NBR,
                ORGNL_DEPOSIT_TRANSACTION_DATE
            FROM CUST_DEP_REDEMPTION_DETAILS));

SELECT COUNT(*) FROM CUST_DEP_CRD_RED_DETAILS WHERE TRANSACTION_TYPE='DEPOSIT';
SELECT COUNT(*) FROM CUST_DEP_CRD_RED_DETAILS WHERE TRANSACTION_TYPE='REDEMPTION';
