DECLARE
  V_REDEMPTION_ID  CUST_DEP_REDEMPTION_DETAILS.REDEMPTION_ID%TYPE;
BEGIN
  INSERT INTO CUSTOMER_DEPOSIT_DETAILS 
SELECT COST_CENTER_CODE, 
       TRANSACTION_DATE - INTERVAL '1' SECOND TRANSACTION_DATE, 
       TERMINAL_NUMBER, 
       TRANSACTION_NUMBER, 
       TRANSACTION_GUID, 
       CUSTOMER_ACCOUNT_NUMBER,
       POS_TRANSACTION_CODE, 
       SYSDATE TRAN_TIMESTAMP,
       'MANUAL' TRANSACTION_TYPE,
       TOTAL_SALES,
       0 CUSTOMER_NET_BALANCE,
       SYSDATE LOAD_DATE,
       RLS_RUN_CYCLE, 
       ADJUSTED_DATE, 
       CLEARED_REASON,
       TRUNC(SYSDATE) CLOSED_DATE,
       GL_DIVISION,
       'Offset of original transaction number' NOTES,
       REFERENCE_NUMBER, 
       -1 * CSTMR_DPST_SALES_LN_ITM_AMT
  FROM CUSTOMER_DEPOSIT_DETAILS
 WHERE CUSTOMER_ACCOUNT_NUMBER = '273678557';
 
  INSERT INTO CUST_DEP_REDEMPTION_DETAILS VALUES (SEQ_REDEMPTION_ID.nextval, '703877','273678557','71071','27-FEB-2017','17319','17319','71071','27-FEB-2017',SYSDATE, NULL)
  RETURNING REDEMPTION_ID INTO V_REDEMPTION_ID;
 
  UPDATE CUST_DEP_REDEMPTION_DETAILS 
   SET TRAN_TIMESTAMP = (SELECT TRAN_TIMESTAMP FROM CUST_DEP_CREDIT_DETAILS WHERE CREDIT_ID = '480472')
 WHERE REDEMPTION_ID = V_REDEMPTION_ID;
  
  UPDATE CUST_DEP_CREDIT_DETAILS 
   SET DEPOSIT_REMAINING_BAL = 0 
 WHERE CREDIT_ID = '480472';
 
 UPDATE CUSTOMER_DEPOSIT_DETAILS 
    SET CLOSED_DATE = TRUNC(SYSDATE)
  WHERE CUSTOMER_ACCOUNT_NUMBER ='273678557';
 
 COMMIT;
END;
/