/*
Below script will provide Jeremy same access on CCN as Marissa

Created : 9/16/2019 jxc517 CCN Project Team....
Changed : 
*/
--Get current Marissas roles
--SELECT * FROM SECURITY_MATRIX WHERE USER_ID = 'map497';
SELECT * FROM SECURITY_MATRIX WHERE USER_ID = 'jxh619';
INSERT INTO SECURITY_MATRIX VALUES ('jxh619','jxh619','CCNUS1');
INSERT INTO SECURITY_MATRIX VALUES ('jxh619','jxh619','CSDU');
INSERT INTO SECURITY_MATRIX VALUES ('jxh619','jxh619','HWUAGS');
INSERT INTO SECURITY_MATRIX VALUES ('jxh619','jxh619','SDU');
SELECT * FROM SECURITY_MATRIX WHERE USER_ID = 'jxh619';

COMMIT;