/*
This script inserts data into our translation tables to store Country code, Currency code transitions

Created : 11/15/2017 axt754 CCN Project Team....
Changed :
*/
-- INSERT INTO TRANSLATION_HEADER
INSERT INTO TRANSLATION_HEADER VALUES ('COUNTRY_CD_CURRENCY_CD','CURRENCY CODE FOR COUNTRY CODE','N',NULL,NULL,3,NULL);

-- INSERT INTO TRANSALATION_DETAIL
INSERT INTO TRANSLATION_DETAIL VALUES ('COUNTRY_CD_CURRENCY_CD','ABW',1,'AWG','N',NULL,NULL);
INSERT INTO TRANSLATION_DETAIL VALUES ('COUNTRY_CD_CURRENCY_CD','ANT',2,'NAF','N',NULL,NULL);
INSERT INTO TRANSLATION_DETAIL VALUES ('COUNTRY_CD_CURRENCY_CD','BRB',3,'BBD','N',NULL,NULL);
INSERT INTO TRANSLATION_DETAIL VALUES ('COUNTRY_CD_CURRENCY_CD','CUW',4,'NAF','N',NULL,NULL);
INSERT INTO TRANSLATION_DETAIL VALUES ('COUNTRY_CD_CURRENCY_CD','GRD',5,'EC','N',NULL,NULL);
INSERT INTO TRANSLATION_DETAIL VALUES ('COUNTRY_CD_CURRENCY_CD','LCA',6,'XCD','N',NULL,NULL);
INSERT INTO TRANSLATION_DETAIL VALUES ('COUNTRY_CD_CURRENCY_CD','TTO',7,'TT$','N',NULL,NULL);

COMMIT;
