--Delete DSCRTS_CTGRY_TYP_CD  from translation header and detail tables

DELETE FROM TRANSLATION_DETAIL WHERE HEADER_NAME = 'DSCRTS_CTGRY_TYP_CD';
DELETE FROM TRANSLATION_HEADER WHERE HEADER_NAME = 'DSCRTS_CTGRY_TYP_CD';

commit;