/*
Below script will grant CCN View access on cost center to Lee and remove for Kaite
Lee Niedenthal:  LXN782 
Katie Pschesang: KMP440

Created :10/25/2018 kxm302 CCN Project Team....
Changed :
*/

SELECT * FROM SECURITY_MATRIX WHERE UPPER(USER_ID) = 'KMP440';

DELETE FROM SECURITY_MATRIX WHERE UPPER(USER_ID)='KMP440';

SELECT * FROM SECURITY_MATRIX WHERE UPPER(USER_ID) = 'KMP440';

SELECT * FROM SECURITY_MATRIX WHERE LOWER(USER_ID) = 'lxn782';

INSERT INTO SECURITY_MATRIX VALUES ('lxn782', 'lxn782', 'CCNUS1');
INSERT INTO SECURITY_MATRIX VALUES ('lxn782', 'lxn782', 'SDU');

SELECT * FROM SECURITY_MATRIX WHERE LOWER(USER_ID) = 'lxn782';


COMMIT;
