/*
Below script will add roles for las841, rae4gr, ems17r same like jmk01r

Created : 09/01/2017 jxc517 CCCN Project Team....
Changed :
*/
REM INSERTING into SECURITY_MATRIX
SET DEFINE OFF;
INSERT INTO SECURITY_MATRIX (USER_ID,PASSWORD,ROLE_CODE) values ('las841','las841','CCNUS1');
INSERT INTO SECURITY_MATRIX (USER_ID,PASSWORD,ROLE_CODE) values ('las841','las841','CCNPHS');
INSERT INTO SECURITY_MATRIX (USER_ID,PASSWORD,ROLE_CODE) values ('las841','las841','HWU2');
INSERT INTO SECURITY_MATRIX (USER_ID,PASSWORD,ROLE_CODE) values ('las841','las841','CCNUPB');
INSERT INTO SECURITY_MATRIX (USER_ID,PASSWORD,ROLE_CODE) values ('las841','las841','CCNUS4');

INSERT INTO SECURITY_MATRIX (USER_ID,PASSWORD,ROLE_CODE) values ('rae4gr','rae4gr','CCNPHS');
INSERT INTO SECURITY_MATRIX (USER_ID,PASSWORD,ROLE_CODE) values ('rae4gr','rae4gr','CCNUPB');
INSERT INTO SECURITY_MATRIX (USER_ID,PASSWORD,ROLE_CODE) values ('rae4gr','rae4gr','CCNUS4');

INSERT INTO SECURITY_MATRIX (USER_ID,PASSWORD,ROLE_CODE) values ('ems17r','ems17r','CCNPHS');
INSERT INTO SECURITY_MATRIX (USER_ID,PASSWORD,ROLE_CODE) values ('ems17r','ems17r','CCNUPB');
INSERT INTO SECURITY_MATRIX (USER_ID,PASSWORD,ROLE_CODE) values ('ems17r','ems17r','CCNUS4');

COMMIT;
