/*
CREATED : nxk927 10/23/2017
          giving access to katie pschesang (kmp440) (similar to Mary kirkpatrick).
*/


SELECT * FROM SECURITY_MATRIX WHERE USER_ID = 'mfk543';
INSERT INTO SECURITY_MATRIX VALUES ('KMP440','KMP440','CCNUS1');
INSERT INTO SECURITY_MATRIX VALUES ('KMP440','KMP440','SDU');

SELECT * FROM SECURITY_MATRIX WHERE USER_ID IN ('mfk543', 'KMP440');


COMMIT;