/********************************************************************************************************************************************
Inserting new country code ISO for specific countries present in Transaction details table.In order to populate ISO numeric country code in ValueLink file
Inserts into TRANSLATION_HEADER for Country Code ISO.

Created : 11/09/2017 bxa919 CCN Project Team....

********************************************************************************************************************************************/

REM INSERTING into EXPORT_TABLE
SET DEFINE OFF;
Insert into TRANSLATION_HEADER (HEADER_NAME,HEADER_DESCRIPTION,HEADER_EXPIRE_FLAG,HEADER_EXPIRE_USER,HEADER_EXPIRE_EFF_DATE,HEADER_TRANSLATE_SIZE,HEADER_SYSTEM_OWNED) values ('COUNTRY_CODE_ISO','COUNTRY ISO CODES','N',null,null,3,null);


REM INSERTING into TRANSLATION_DETAIL
SET DEFINE OFF;
Insert into TRANSLATION_DETAIL (HEADER_NAME,DETAIL_VALUE,DETAIL_SEQ_NUMBER,DETAIL_TRANSLATION,DETAIL_EXPIRE_FLAG,DETAIL_EXPIRE_USER,DETAIL_EXPIRE_EFF_DATE) values ('COUNTRY_CODE_ISO','USA',1,'840','N',null,null);
Insert into TRANSLATION_DETAIL (HEADER_NAME,DETAIL_VALUE,DETAIL_SEQ_NUMBER,DETAIL_TRANSLATION,DETAIL_EXPIRE_FLAG,DETAIL_EXPIRE_USER,DETAIL_EXPIRE_EFF_DATE) values ('COUNTRY_CODE_ISO','ABW',1,'840','N',null,null);
Insert into TRANSLATION_DETAIL (HEADER_NAME,DETAIL_VALUE,DETAIL_SEQ_NUMBER,DETAIL_TRANSLATION,DETAIL_EXPIRE_FLAG,DETAIL_EXPIRE_USER,DETAIL_EXPIRE_EFF_DATE) values ('COUNTRY_CODE_ISO','BRB',1,'052','N',null,null);
Insert into TRANSLATION_DETAIL (HEADER_NAME,DETAIL_VALUE,DETAIL_SEQ_NUMBER,DETAIL_TRANSLATION,DETAIL_EXPIRE_FLAG,DETAIL_EXPIRE_USER,DETAIL_EXPIRE_EFF_DATE) values ('COUNTRY_CODE_ISO','ANT',1,'530','N',null,null);
Insert into TRANSLATION_DETAIL (HEADER_NAME,DETAIL_VALUE,DETAIL_SEQ_NUMBER,DETAIL_TRANSLATION,DETAIL_EXPIRE_FLAG,DETAIL_EXPIRE_USER,DETAIL_EXPIRE_EFF_DATE) values ('COUNTRY_CODE_ISO','CAN',1,'124','N',null,null);
Insert into TRANSLATION_DETAIL (HEADER_NAME,DETAIL_VALUE,DETAIL_SEQ_NUMBER,DETAIL_TRANSLATION,DETAIL_EXPIRE_FLAG,DETAIL_EXPIRE_USER,DETAIL_EXPIRE_EFF_DATE) values ('COUNTRY_CODE_ISO','GRD',1,'308','N',null,null);
Insert into TRANSLATION_DETAIL (HEADER_NAME,DETAIL_VALUE,DETAIL_SEQ_NUMBER,DETAIL_TRANSLATION,DETAIL_EXPIRE_FLAG,DETAIL_EXPIRE_USER,DETAIL_EXPIRE_EFF_DATE) values ('COUNTRY_CODE_ISO','JAM',1,'388','N',null,null);
Insert into TRANSLATION_DETAIL (HEADER_NAME,DETAIL_VALUE,DETAIL_SEQ_NUMBER,DETAIL_TRANSLATION,DETAIL_EXPIRE_FLAG,DETAIL_EXPIRE_USER,DETAIL_EXPIRE_EFF_DATE) values ('COUNTRY_CODE_ISO','LCA',1,'662','N',null,null);
Insert into TRANSLATION_DETAIL (HEADER_NAME,DETAIL_VALUE,DETAIL_SEQ_NUMBER,DETAIL_TRANSLATION,DETAIL_EXPIRE_FLAG,DETAIL_EXPIRE_USER,DETAIL_EXPIRE_EFF_DATE) values ('COUNTRY_CODE_ISO','MEX',1,'484','N',null,null);
Insert into TRANSLATION_DETAIL (HEADER_NAME,DETAIL_VALUE,DETAIL_SEQ_NUMBER,DETAIL_TRANSLATION,DETAIL_EXPIRE_FLAG,DETAIL_EXPIRE_USER,DETAIL_EXPIRE_EFF_DATE) values ('COUNTRY_CODE_ISO','PRI',1,'630','N',null,null);
Insert into TRANSLATION_DETAIL (HEADER_NAME,DETAIL_VALUE,DETAIL_SEQ_NUMBER,DETAIL_TRANSLATION,DETAIL_EXPIRE_FLAG,DETAIL_EXPIRE_USER,DETAIL_EXPIRE_EFF_DATE) values ('COUNTRY_CODE_ISO','TTO',1,'780','N',null,null);

COMMIT;