/*
This script will rename the  tables/columns
   Tables
       STORE_DRAFT_REPORT TO SD_INSTALLER_GAIN_LOSS_REPORT and
       HST_STORE_DRAFT_REPORT TO HST_SD_INSTLR_GAIN_LOSS_REPORT

   Column
       PURCHASE_ORDER_NUMBER TO CUSTOMER_NAME   

Created  : 12/13/2017 nxk927 CCN Project Team...
Modified :
*/
RENAME STORE_DRAFT_REPORT TO SD_INSTALLER_GAIN_LOSS_REPORT;
RENAME HST_STORE_DRAFT_REPORT TO HST_SD_INSTLR_GAIN_LOSS_REPORT;
ALTER TABLE SD_INSTALLER_GAIN_LOSS_REPORT RENAME COLUMN PURCHASE_ORDER_NUMBER TO CUSTOMER_NAME;
ALTER TABLE HST_SD_INSTLR_GAIN_LOSS_REPORT RENAME COLUMN PURCHASE_ORDER_NUMBER TO CUSTOMER_NAME;