/*
CCNCC-18 This script will modify column COST_CENTER_CODE from 4 to 6 chars.
Created  : 07/02/2019 sxs484 
*/


ALTER TABLE DLY_POS_CSTMR_BANK_CARD MODIFY COST_CENTER_CODE	VARCHAR2(6);
--ALTER TABLE DLY_POS_ISSUE_CHANGE_DATA RENAME COLUMN STORE_NBR TO STORECCN;
SET SERVEROUTPUT ON;
DECLARE
    V_CC VARCHAR2(6);
BEGIN
    FOR rec IN (SELECT DISTINCT COST_CENTER_CODE FROM DLY_POS_CSTMR_BANK_CARD) LOOP
        BEGIN
            V_CC := COMMON_TOOLS.COST_CENTER_LOOK_UP_FNC(rec.COST_CENTER_CODE);
            UPDATE DLY_POS_CSTMR_BANK_CARD SET COST_CENTER_CODE = V_CC WHERE COST_CENTER_CODE = rec.COST_CENTER_CODE;
            COMMIT;
            V_CC := NULL;
        EXCEPTION
            WHEN OTHERS THEN
                DBMS_OUTPUT.PUT_LINE(SQLCODE ||':'|| SQLERRM);
        END;
    END LOOP;
END;
ALTER TABLE DLY_POS_CSTMR_BANK_CARD MODIFY COST_CENTER_CODE	NOT NULL;

--DLY_POS_ISSUE_CHANGE_DATA
ALTER TABLE DLY_POS_ISSUE_CHANGE_DATA MODIFY COST_CENTER_CODE	VARCHAR2(6);
--ALTER TABLE DLY_POS_ISSUE_CHANGE_DATA RENAME COLUMN STORE_NBR TO STORECCN;
SET SERVEROUTPUT ON;
DECLARE
    V_CC VARCHAR2(6);
BEGIN
    FOR rec IN (SELECT DISTINCT COST_CENTER_CODE FROM DLY_POS_ISSUE_CHANGE_DATA) LOOP --2575  Rows
        BEGIN
            V_CC := COMMON_TOOLS.COST_CENTER_LOOK_UP_FNC(rec.COST_CENTER_CODE);
            UPDATE DLY_POS_ISSUE_CHANGE_DATA SET COST_CENTER_CODE = V_CC WHERE COST_CENTER_CODE = rec.COST_CENTER_CODE;
            COMMIT;
            V_CC := NULL;
        EXCEPTION
            WHEN OTHERS THEN
                DBMS_OUTPUT.PUT_LINE(SQLCODE ||':'|| SQLERRM);
        END;
    END LOOP;
END;
ALTER TABLE DLY_POS_ISSUE_CHANGE_DATA MODIFY COST_CENTER_CODE	NOT NULL;




--DLY_POS_BANK_PAID_DATA
ALTER TABLE DLY_POS_BANK_PAID_DATA MODIFY COST_CENTER_CODE	VARCHAR2(6);
--ALTER TABLE DLY_POS_ISSUE_CHANGE_DATA RENAME COLUMN STORE_NBR TO STORECCN;
SET SERVEROUTPUT ON;
DECLARE
    V_CC VARCHAR2(6);
BEGIN
    FOR rec IN (SELECT DISTINCT COST_CENTER_CODE FROM DLY_POS_BANK_PAID_DATA) LOOP --2575  Rows
        BEGIN
            V_CC := COMMON_TOOLS.COST_CENTER_LOOK_UP_FNC(rec.COST_CENTER_CODE);
            UPDATE DLY_POS_BANK_PAID_DATA SET COST_CENTER_CODE = V_CC WHERE COST_CENTER_CODE = rec.COST_CENTER_CODE;
            COMMIT;
            V_CC := NULL;
        EXCEPTION
            WHEN OTHERS THEN
                DBMS_OUTPUT.PUT_LINE(SQLCODE ||':'|| SQLERRM);
        END;
    END LOOP;
END;
ALTER TABLE DLY_POS_BANK_PAID_DATA MODIFY COST_CENTER_CODE	NOT NULL;

--DLY_POS_INSTLLR_LN_ITM_DATA
ALTER TABLE DLY_POS_INSTLLR_LN_ITM_DATA MODIFY COST_CENTER_CODE	VARCHAR2(6);
--ALTER TABLE DLY_POS_ISSUE_CHANGE_DATA RENAME COLUMN STORE_NBR TO STORECCN;
SET SERVEROUTPUT ON;
DECLARE
    V_CC VARCHAR2(6);
BEGIN
    FOR rec IN (SELECT DISTINCT COST_CENTER_CODE FROM DLY_POS_INSTLLR_LN_ITM_DATA) LOOP --2575  Rows
        BEGIN
            V_CC := COMMON_TOOLS.COST_CENTER_LOOK_UP_FNC(rec.COST_CENTER_CODE);
            UPDATE DLY_POS_INSTLLR_LN_ITM_DATA SET COST_CENTER_CODE = V_CC WHERE COST_CENTER_CODE = rec.COST_CENTER_CODE;
            COMMIT;
            V_CC := NULL;
        EXCEPTION
            WHEN OTHERS THEN
                DBMS_OUTPUT.PUT_LINE(SQLCODE ||':'|| SQLERRM);
        END;
    END LOOP;
END;
ALTER TABLE DLY_POS_INSTLLR_LN_ITM_DATA MODIFY COST_CENTER_CODE	NOT NULL;


--DLY_POS_CSTMR_LINE_ITEM_DATA
ALTER TABLE DLY_POS_CSTMR_LINE_ITEM_DATA MODIFY COST_CENTER_CODE	VARCHAR2(6);
--ALTER TABLE DLY_POS_ISSUE_CHANGE_DATA RENAME COLUMN STORE_NBR TO STORECCN;
SET SERVEROUTPUT ON;
DECLARE
    V_CC VARCHAR2(6);
BEGIN
    FOR rec IN (SELECT DISTINCT COST_CENTER_CODE FROM DLY_POS_CSTMR_LINE_ITEM_DATA) LOOP --2575  Rows
        BEGIN
            V_CC := COMMON_TOOLS.COST_CENTER_LOOK_UP_FNC(rec.COST_CENTER_CODE);
            UPDATE DLY_POS_CSTMR_LINE_ITEM_DATA SET COST_CENTER_CODE = V_CC WHERE COST_CENTER_CODE = rec.COST_CENTER_CODE;
            COMMIT;
            V_CC := NULL;
        EXCEPTION
            WHEN OTHERS THEN
                DBMS_OUTPUT.PUT_LINE(SQLCODE ||':'|| SQLERRM);
        END;
    END LOOP;
END;
ALTER TABLE DLY_POS_CSTMR_LINE_ITEM_DATA MODIFY COST_CENTER_CODE	NOT NULL;

--DLY_POS_DSBRSMNT_LN_ITM_DATA
ALTER TABLE DLY_POS_DSBRSMNT_LN_ITM_DATA MODIFY COST_CENTER_CODE	VARCHAR2(6);
--ALTER TABLE DLY_POS_ISSUE_CHANGE_DATA RENAME COLUMN STORE_NBR TO STORECCN;
SET SERVEROUTPUT ON;
DECLARE
    V_CC VARCHAR2(6);
BEGIN
    FOR rec IN (SELECT DISTINCT COST_CENTER_CODE FROM DLY_POS_DSBRSMNT_LN_ITM_DATA) LOOP --2575  Rows
        BEGIN
            V_CC := COMMON_TOOLS.COST_CENTER_LOOK_UP_FNC(rec.COST_CENTER_CODE);
            UPDATE DLY_POS_DSBRSMNT_LN_ITM_DATA SET COST_CENTER_CODE = V_CC WHERE COST_CENTER_CODE = rec.COST_CENTER_CODE;
            COMMIT;
            V_CC := NULL;
        EXCEPTION
            WHEN OTHERS THEN
                DBMS_OUTPUT.PUT_LINE(SQLCODE ||':'|| SQLERRM);
        END;
    END LOOP;
END;
ALTER TABLE DLY_POS_DSBRSMNT_LN_ITM_DATA MODIFY COST_CENTER_CODE	NOT NULL;


--DLY_POS_CUSTOMER
ALTER TABLE DLY_POS_CUSTOMER MODIFY COST_CENTER_CODE	VARCHAR2(6);
--ALTER TABLE DLY_POS_ISSUE_CHANGE_DATA RENAME COLUMN STORE_NBR TO STORECCN;
SET SERVEROUTPUT ON;
DECLARE
    V_CC VARCHAR2(6);
BEGIN
    FOR rec IN (SELECT DISTINCT COST_CENTER_CODE FROM DLY_POS_CUSTOMER) LOOP --2575  Rows
        BEGIN
            V_CC := COMMON_TOOLS.COST_CENTER_LOOK_UP_FNC(rec.COST_CENTER_CODE);
            UPDATE DLY_POS_CUSTOMER SET COST_CENTER_CODE = V_CC WHERE COST_CENTER_CODE = rec.COST_CENTER_CODE;
            COMMIT;
            V_CC := NULL;
        EXCEPTION
            WHEN OTHERS THEN
                DBMS_OUTPUT.PUT_LINE(SQLCODE ||':'|| SQLERRM);
        END;
    END LOOP;
END;
ALTER TABLE DLY_POS_CUSTOMER MODIFY COST_CENTER_CODE	NOT NULL;


--DLY_POS_CUSTOMER_DETAILS
ALTER TABLE DLY_POS_CUSTOMER_DETAILS MODIFY COST_CENTER_CODE	VARCHAR2(6);
--ALTER TABLE DLY_POS_ISSUE_CHANGE_DATA RENAME COLUMN STORE_NBR TO STORECCN;
SET SERVEROUTPUT ON;
DECLARE
    V_CC VARCHAR2(6);
BEGIN
    FOR rec IN (SELECT DISTINCT COST_CENTER_CODE FROM DLY_POS_CUSTOMER_DETAILS) LOOP --2575  Rows
        BEGIN
            V_CC := COMMON_TOOLS.COST_CENTER_LOOK_UP_FNC(rec.COST_CENTER_CODE);
            UPDATE DLY_POS_CUSTOMER_DETAILS SET COST_CENTER_CODE = V_CC WHERE COST_CENTER_CODE = rec.COST_CENTER_CODE;
            COMMIT;
            V_CC := NULL;
        EXCEPTION
            WHEN OTHERS THEN
                DBMS_OUTPUT.PUT_LINE(SQLCODE ||':'|| SQLERRM);
        END;
    END LOOP;
END;
ALTER TABLE DLY_POS_CUSTOMER_DETAILS MODIFY COST_CENTER_CODE	NOT NULL;


--DLY_POS_CSTMR_SALES_TAX
ALTER TABLE DLY_POS_CSTMR_SALES_TAX MODIFY COST_CENTER_CODE	VARCHAR2(6);
--ALTER TABLE DLY_POS_ISSUE_CHANGE_DATA RENAME COLUMN STORE_NBR TO STORECCN;
SET SERVEROUTPUT ON;
DECLARE
    V_CC VARCHAR2(6);
BEGIN
    FOR rec IN (SELECT DISTINCT COST_CENTER_CODE FROM DLY_POS_CSTMR_SALES_TAX) LOOP --2575  Rows
        BEGIN
            V_CC := COMMON_TOOLS.COST_CENTER_LOOK_UP_FNC(rec.COST_CENTER_CODE);
            UPDATE DLY_POS_CSTMR_SALES_TAX SET COST_CENTER_CODE = V_CC WHERE COST_CENTER_CODE = rec.COST_CENTER_CODE;
            COMMIT;
            V_CC := NULL;
        EXCEPTION
            WHEN OTHERS THEN
                DBMS_OUTPUT.PUT_LINE(SQLCODE ||':'|| SQLERRM);
        END;
    END LOOP;
END;
ALTER TABLE DLY_POS_CSTMR_SALES_TAX MODIFY COST_CENTER_CODE	NOT NULL;

--DLY_POS_CSTMR_FORM_OF_PAY
ALTER TABLE DLY_POS_CSTMR_FORM_OF_PAY MODIFY COST_CENTER_CODE	VARCHAR2(6);
--ALTER TABLE DLY_POS_ISSUE_CHANGE_DATA RENAME COLUMN STORE_NBR TO STORECCN;
SET SERVEROUTPUT ON;
DECLARE
    V_CC VARCHAR2(6);
BEGIN
    FOR rec IN (SELECT DISTINCT COST_CENTER_CODE FROM DLY_POS_CSTMR_FORM_OF_PAY) LOOP --2575  Rows
        BEGIN
            V_CC := COMMON_TOOLS.COST_CENTER_LOOK_UP_FNC(rec.COST_CENTER_CODE);
            UPDATE DLY_POS_CSTMR_FORM_OF_PAY SET COST_CENTER_CODE = V_CC WHERE COST_CENTER_CODE = rec.COST_CENTER_CODE;
            COMMIT;
            V_CC := NULL;
        EXCEPTION
            WHEN OTHERS THEN
                DBMS_OUTPUT.PUT_LINE(SQLCODE ||':'|| SQLERRM);
        END;
    END LOOP;
END;
ALTER TABLE DLY_POS_CSTMR_FORM_OF_PAY MODIFY COST_CENTER_CODE	NOT NULL;

--DLY_POS_CCN_ACCUMS
--ALTER TABLE DLY_POS_CSTMR_FORM_OF_PAY MODIFY COST_CENTER_CODE	VARCHAR2(6);
--ALTER TABLE DLY_POS_ISSUE_CHANGE_DATA RENAME COLUMN STORE_NBR TO STORECCN;
SET SERVEROUTPUT ON;
DECLARE
    V_CC VARCHAR2(6);
BEGIN
    FOR rec IN (SELECT DISTINCT COST_CENTER_CODE FROM DLY_POS_CCN_ACCUMS) LOOP --2575  Rows
        BEGIN
            V_CC := COMMON_TOOLS.COST_CENTER_LOOK_UP_FNC(rec.COST_CENTER_CODE);
            UPDATE DLY_POS_CCN_ACCUMS SET COST_CENTER_CODE = V_CC WHERE COST_CENTER_CODE = rec.COST_CENTER_CODE;
            COMMIT;
            V_CC := NULL;
        EXCEPTION
            WHEN OTHERS THEN
                DBMS_OUTPUT.PUT_LINE(SQLCODE ||':'|| SQLERRM);
        END;
    END LOOP;
END;
ALTER TABLE DLY_POS_CCN_ACCUMS MODIFY COST_CENTER_CODE	NOT NULL;
