/*
Below grants and synonyms are needed for batch job execution

Created : 11/7/2019 jxc517 CCN Project Team....
Changed :
*/

GRANT SELECT, INSERT ON PAID_DETAILS_ROYAL     to STDRFTUSR;
CREATE OR REPLACE SYNONYM STDRFTUSR.PAID_DETAILS_ROYAL FOR STORDRFT.PAID_DETAILS_ROYAL;

GRANT SELECT, INSERT ON PAID_DETAILS_SUNTRUST  to STDRFTUSR;
CREATE OR REPLACE SYNONYM STDRFTUSR.PAID_DETAILS_SUNTRUST FOR STORDRFT.PAID_DETAILS_SUNTRUST;

GRANT EXECUTE ON SD_PAID_DETAILS_LOAD  to STDRFTUSR;
CREATE OR REPLACE SYNONYM STDRFTUSR.SD_PAID_DETAILS_LOAD FOR STORDRFT.SD_PAID_DETAILS_LOAD;

