CREATE TABLE "STORDRFT"."CODE_DETAIL" 
   (	"CODE_HEADER_NAME" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"CODE_HEADER_TYPE" VARCHAR2(3 BYTE) NOT NULL ENABLE, 
	"CODE_DETAIL_VALUE" VARCHAR2(32 BYTE) NOT NULL ENABLE, 
	"CODE_DETAIL_DESCRIPTION" VARCHAR2(100 BYTE), 
	"CODE_DETAIL_EXPIRE_FLAG" CHAR(1 BYTE), 
	"CODE_DETAIL_EXPIRE_USER" VARCHAR2(20 BYTE), 
	"CODE_DETAIL_EXPIRE_EFF_DATE" DATE, 
	"CODE_DETAIL_ID" NUMBER(10,3), 
	"CODE_DETAIL_CREATE_USER" VARCHAR2(25 BYTE), 
	"CODE_DETAIL_EFF_DATE" DATE, 
	 CONSTRAINT "CODE_DETAIL_PK" PRIMARY KEY ("CODE_HEADER_NAME", "CODE_HEADER_TYPE", "CODE_DETAIL_VALUE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "STORDRFT_DATA"  ENABLE, 
	 CONSTRAINT "CODE_HEADER_CODE_DETAIL" FOREIGN KEY ("CODE_HEADER_NAME", "CODE_HEADER_TYPE")
	  REFERENCES "STORDRFT"."CODE_HEADER" ("CODE_HEADER_NAME", "CODE_HEADER_TYPE") ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "STORDRFT_DATA" ;

   COMMENT ON COLUMN "STORDRFT"."CODE_DETAIL"."CODE_HEADER_NAME" IS 'The Code_Name names the table to be defined.';
   COMMENT ON COLUMN "STORDRFT"."CODE_DETAIL"."CODE_DETAIL_DESCRIPTION" IS 'The Detail_Description gives definition to an entry in the self defining table.';
   COMMENT ON COLUMN "STORDRFT"."CODE_DETAIL"."CODE_DETAIL_ID" IS 'This colum,n is used for ordering while displaying in the UI';
   COMMENT ON TABLE "STORDRFT"."CODE_DETAIL"  IS 'This is the table that holds the actual table entries of the self defined table.';
