CREATE TABLE "STORDRFT"."CODE_HEADER" 
   (	"CODE_HEADER_NAME" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"CODE_HEADER_TYPE" VARCHAR2(3 BYTE) NOT NULL ENABLE, 
	"CODE_HEADER_DESCRIPTION" VARCHAR2(100 BYTE), 
	"CODE_HEADER_EXPIRE_FLAG" CHAR(1 BYTE), 
	"CODE_HEADER_EXPIRE_USER" VARCHAR2(20 BYTE), 
	"CODE_HEADER_EXPIRE_EFF_DATE" DATE, 
	"CODE_HEADER_DTL_VAL_SIZE" NUMBER(2,0), 
	"CODE_HEADER_DTL_VAL_DEFAULT" VARCHAR2(32 BYTE), 
	"CODE_HEADER_CREATE_USER" VARCHAR2(25 BYTE), 
	"CODE_HEADER_EFF_DATE" DATE, 
	 CONSTRAINT "CODE_HEADER_PK" PRIMARY KEY ("CODE_HEADER_NAME", "CODE_HEADER_TYPE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "STORDRFT_DATA"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "STORDRFT_DATA" ;

   COMMENT ON COLUMN "STORDRFT"."CODE_HEADER"."CODE_HEADER_NAME" IS 'The Code_Name names the table to be defined.';
   COMMENT ON COLUMN "STORDRFT"."CODE_HEADER"."CODE_HEADER_DESCRIPTION" IS 'This is the description of the named table.';
   COMMENT ON COLUMN "STORDRFT"."CODE_HEADER"."CODE_HEADER_DTL_VAL_SIZE" IS 'Defines the size of Code Detail Value Size.';
   COMMENT ON COLUMN "STORDRFT"."CODE_HEADER"."CODE_HEADER_DTL_VAL_DEFAULT" IS 'The default value for a particular pick list.';
   COMMENT ON TABLE "STORDRFT"."CODE_HEADER"  IS 'This is the table that holds the name and definition of self defined tables.';
