
  CREATE TABLE CUSTOMER_FORM_OF_PAY 
   (	CUSTOMER_FORM_OF_PAY_ID NUMBER(15,0) NOT NULL ENABLE, 
	COST_CENTER_CODE VARCHAR2(6 CHAR) NOT NULL ENABLE, 
	TRANSACTION_DATE DATE NOT NULL ENABLE, 
	TERMINAL_NUMBER VARCHAR2(5 CHAR) NOT NULL ENABLE, 
	TRANSACTION_NUMBER VARCHAR2(5 CHAR) NOT NULL ENABLE, 
	SEGMENT_CODE VARCHAR2(2 CHAR) NOT NULL ENABLE, 
	SUB_SEGMENT_CODE VARCHAR2(2 CHAR) NOT NULL ENABLE, 
	PAY_DISC_CODE VARCHAR2(1 CHAR), 
	TRANSACTION_TOTAL_AMT NUMBER(7,2), 
	POS_LINE_COUNT VARCHAR2(5 CHAR), 
	PAY_AMOUNT NUMBER(7,2), 
	PAY_DISCOUNT NUMBER(7,2), 
	SALES_DISCOUNT_AMT NUMBER(7,2), 
	CONSTRAINT CUSTOMER_FRM_OF_PAY_BNK_CRD_PK PRIMARY KEY (CUSTOMER_FORM_OF_PAY_ID, COST_CENTER_CODE, TRANSACTION_DATE, TERMINAL_NUMBER, TRANSACTION_NUMBER) ENABLE, 
	CONSTRAINT CUSTOMER_FORM_OF_PAY_FK FOREIGN KEY (COST_CENTER_CODE, TRANSACTION_DATE, TERMINAL_NUMBER, TRANSACTION_NUMBER) REFERENCES CUSTOMER (COST_CENTER_CODE, TRANSACTION_DATE, TERMINAL_NUMBER, TRANSACTION_NUMBER) ENABLE
   );

  CREATE INDEX CUSTOMER_FORM_OF_PAY_IDX ON CUSTOMER_FORM_OF_PAY (COST_CENTER_CODE, TRANSACTION_DATE, TERMINAL_NUMBER, TRANSACTION_NUMBER);
