CREATE TABLE "STORDRFT"."CUSTOMER_T" 
   (	"COST_CENTER_CODE" VARCHAR2(6 BYTE), 
	"TRANSACTION_DATE" VARCHAR2(8 BYTE), 
	"TERM_NUMBER" VARCHAR2(5 BYTE), 
	"TRANSACTION_NUMBER" VARCHAR2(5 BYTE), 
	"CUSTOMER_ACCOUNT_NUMBER" VARCHAR2(9 BYTE), 
	"CUSTOMER_JOB_NUMBER" VARCHAR2(2 BYTE), 
	"POS_TRANSACTION_CODE" VARCHAR2(2 BYTE), 
	"POS_TRANSACTION_BATCH_NUMBER" VARCHAR2(6 BYTE), 
	"POS_TRANSACTION_TIME" VARCHAR2(4 BYTE), 
	"CYCLE_RUN_NUMBER" VARCHAR2(2 BYTE), 
	"EMPLOYEE_NUMBER" VARCHAR2(2 BYTE), 
	"POS_MOD_IND" VARCHAR2(1 BYTE), 
	"BUSINESS_TYPE_CODE" VARCHAR2(2 BYTE), 
	"SALES_TERRITORY_NUMBER" VARCHAR2(4 BYTE), 
	"SALES_TERRITORY_NUMBER_COR" VARCHAR2(4 BYTE), 
	"TERR_SPLIT_IND" VARCHAR2(1 BYTE), 
	"ORGNL_POS_TRANSACTION_DATE" VARCHAR2(8 BYTE), 
	"ORGNL_POS_TERM_NUMBER" VARCHAR2(5 BYTE), 
	"ORGNL_POS_TRANSACTION_NBR" VARCHAR2(5 BYTE), 
	"ORIGINAL_DATA_IND" VARCHAR2(1 BYTE), 
	"PURCHASE_ORDER_NUMBER" VARCHAR2(20 BYTE), 
	"BOOK_DATE_SEQUENCE" VARCHAR2(5 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STORDRFT_DATA" ;
