-- sxt410 09/16/2015 Script to create CUSTOMER_INFO_VW view.
CREATE OR REPLACE FORCE VIEW STORDRFT.CUSTOMER_INFO_VW
AS 
SELECT
/*******************************************************************************
This view holds required information about Customer.

Created  : 09/15/2015 SXT410 CCN Project Team...
Modified : 
*******************************************************************************/
       CD.COST_CENTER_CODE
      ,(SELECT CUSTOMER_ACCOUNT_NUMBER
          FROM CUSTOMER
         WHERE COST_CENTER_CODE   = CD.COST_CENTER_CODE
           AND TERMINAL_NUMBER    = CD.TERMINAL_NUMBER
           AND TRANSACTION_NUMBER = CD.TRANSACTION_NUMBER
           AND ROWNUM = 1) CUSTOMER_ACCOUNT_NUMBER
      ,(SELECT CUSTOMER_JOB_NUMBER
          FROM CUSTOMER
         WHERE COST_CENTER_CODE   = CD.COST_CENTER_CODE
           AND TERMINAL_NUMBER    = CD.TERMINAL_NUMBER
           AND TRANSACTION_NUMBER = CD.TRANSACTION_NUMBER
           AND ROWNUM = 1) CUSTOMER_JOB_NUMBER
      ,(SELECT EMPLOYEE_NUMBER
          FROM CUSTOMER
         WHERE COST_CENTER_CODE   = CD.COST_CENTER_CODE
           AND TERMINAL_NUMBER    = CD.TERMINAL_NUMBER
           AND TRANSACTION_NUMBER = CD.TRANSACTION_NUMBER
           AND ROWNUM = 1) EMPLOYEE_NUMBER
      ,(SELECT BUSSINESS_TYPE_CODE
          FROM CUSTOMER
         WHERE COST_CENTER_CODE   = CD.COST_CENTER_CODE
           AND TERMINAL_NUMBER    = CD.TERMINAL_NUMBER
           AND TRANSACTION_NUMBER = CD.TRANSACTION_NUMBER
           AND ROWNUM = 1) BUSSINESS_TYPE_CODE
      ,(SELECT PURCHASE_ORDER_NUMBER
          FROM CUSTOMER
         WHERE COST_CENTER_CODE   = CD.COST_CENTER_CODE
           AND TERMINAL_NUMBER    = CD.TERMINAL_NUMBER
           AND TRANSACTION_NUMBER = CD.TRANSACTION_NUMBER
           AND ROWNUM = 1) PURCHASE_ORDER_NUMBER
      ,CD.TRANSACTION_DATE
      ,CD.TERMINAL_NUMBER
      ,CD.TRANSACTION_NUMBER
      ,CD.SEGMENT_CODE
      ,CD.SALES_NUMBER
      ,CD.ITEM_QUANTITY
      ,CD.ITEM_PRICE
      ,CD.ITEM_EXT_AMOUNT
      ,CD.ITEM_DISCOUNT_AMOUNT
      ,CD.ITEM_SALES_TAX_IND
      ,CD.ITEM_DISCOUNT_CODE
      ,CD.ITEM_DISCOUNT_TYPE
      ,CD.SALES_PROMO_CODE
      ,CD.GL_PRIME_ACCOUNT_NUMBER
      ,CD.GL_SUB_ACCOUNT_NUMBER
      ,CD.SCHEDULE_TYPE
      ,CD.SCHEDULE_VERSION
      ,CD.PRICE_LEVEL_CODE
      ,CD.PERCENT_OFF_LEVEL
      ,CD.PROD_DESC_SRCE
      ,CD.ORGNL_POS_TERM_NUMBER
      ,CD.ORGNL_POS_TRANS_NUMBER
 FROM CUSTOMER_DETAILS CD;