
  CREATE TABLE CUSTOMER_FORM_OF_PAY_T 
   (	COST_CENTER_CODE VARCHAR2(6 BYTE), 
	TRANSACTION_DATE VARCHAR2(8 BYTE), 
	TERM_NUMBER VARCHAR2(5 BYTE), 
	TRANSACTION_NUMBER VARCHAR2(5 BYTE), 
	SEGMENT_CODE VARCHAR2(2 BYTE), 
	SUB_SEGMENT_CODE VARCHAR2(2 BYTE), 
	PAY_DISC_CODE VARCHAR2(1 BYTE), 
	TRANSACTION_TOTAL_AMT VARCHAR2(7 BYTE), 
	TRAN_TOTAL_AMT_SGN VARCHAR2(1 BYTE), 
	POS_LINE_COUNT VARCHAR2(5 BYTE), 
	PAY_AMOUNT VARCHAR2(7 BYTE), 
	PAY_AMOUNT_SGN VARCHAR2(1 BYTE), 
	PAY_DISCOUNT VARCHAR2(7 BYTE), 
	PAY_DISCOUNT_SGN VARCHAR2(1 BYTE), 
	SALES_DISCOUNT_AMT VARCHAR2(7 BYTE), 
	SALES_DISCOUNT_AMT_SGN VARCHAR2(1 BYTE)
   );
