CREATE TABLE "STORDRFT"."CUSTOMER_DETAILS_T" 
   (	"COST_CENTER_CODE" VARCHAR2(6 BYTE), 
	"TRANSACTION_DATE" VARCHAR2(8 BYTE), 
	"TERM_NUMBER" VARCHAR2(5 BYTE), 
	"TRANSACTION_NUMBER" VARCHAR2(5 BYTE), 
	"SEGMENT_CODE" VARCHAR2(2 BYTE), 
	"SALES_NUMBER" VARCHAR2(9 BYTE), 
	"ITEM_QTY" VARCHAR2(7 BYTE), 
	"ITEM_PRICE" VARCHAR2(7 BYTE), 
	"ITEM_PRICE_SGN" VARCHAR2(1 BYTE), 
	"ITEM_EXT_AMOUNT" VARCHAR2(7 BYTE), 
	"ITEM_EXT_AMT_SGN" VARCHAR2(1 BYTE), 
	"ITEM_DISC_AMOUNT" VARCHAR2(7 BYTE), 
	"ITEM_DISC_AMT_SGN" VARCHAR2(1 BYTE), 
	"ITEM_SLS_TAX_IND" VARCHAR2(1 BYTE), 
	"ITEM_DISC_CODE" VARCHAR2(1 BYTE), 
	"ITEM_DISC_TYPE" VARCHAR2(1 BYTE), 
	"SLS_PROMO_CODE" VARCHAR2(2 BYTE), 
	"GL_PRIME_ACCT_NBR" VARCHAR2(4 BYTE), 
	"GL_SUB_ACCT_NBR" VARCHAR2(3 BYTE), 
	"SCHED_TYPE" VARCHAR2(2 BYTE), 
	"SCHED_VERSION" VARCHAR2(6 BYTE), 
	"PRICE_LVL_CODE" VARCHAR2(1 BYTE), 
	"PERCENT_OFF_LVL" VARCHAR2(3 BYTE), 
	"PROD_DESC_SRCE" VARCHAR2(1 BYTE), 
	"ORIG_POS_TERM_NBR" VARCHAR2(5 BYTE), 
	"ORIG_POS_TRAN_NBR" VARCHAR2(5 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STORDRFT_DATA" ;

  CREATE INDEX "STORDRFT"."CUSTOMER_DETAIL_T_INDX" ON "STORDRFT"."CUSTOMER_DETAILS_T" ("COST_CENTER_CODE", "TRANSACTION_DATE", "TERM_NUMBER", "TRANSACTION_NUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STORDRFT_DATA" ;
