
  CREATE TABLE CUSTOMER_BANK_CARD_T 
   (	COST_CENTER_CODE VARCHAR2(6 BYTE), 
	TRANSACTION_DATE VARCHAR2(8 BYTE), 
	TERM_NUMBER VARCHAR2(5 BYTE), 
	TRANSACTION_NUMBER VARCHAR2(5 BYTE), 
	SEGMENT_CODE VARCHAR2(2 BYTE), 
	SUB_SEGMENT_CODE VARCHAR2(2 BYTE), 
	BANK_CARD_ACCOUNT_NUMBER VARCHAR2(16 BYTE), 
	BANK_AUTH VARCHAR2(9 BYTE), 
	BANK_AMOUNT VARCHAR2(9 BYTE), 
	BANK_AMOUNT_SGN VARCHAR2(1 BYTE), 
	BANK_TYPE VARCHAR2(1 BYTE)
   );
