CREATE TABLE "STORDRFT"."CUSTOMER" 
   (	"COST_CENTER_CODE" VARCHAR2(6 CHAR) NOT NULL ENABLE, 
	"TRANSACTION_DATE" DATE NOT NULL ENABLE, 
	"TERMINAL_NUMBER" VARCHAR2(5 CHAR) NOT NULL ENABLE, 
	"TRANSACTION_NUMBER" VARCHAR2(5 CHAR) NOT NULL ENABLE, 
	"CUSTOMER_ACCOUNT_NUMBER" VARCHAR2(9 CHAR), 
	"CUSTOMER_JOB_NUMBER" VARCHAR2(2 CHAR), 
	"POS_TRANSACTION_CODE" VARCHAR2(2 CHAR), 
	"POS_TRANSACTION_BATCH_NUMBER" VARCHAR2(6 CHAR), 
	"POS_TRANSACTION_TIME" VARCHAR2(4 CHAR), 
	"CYCLE_RUN_NUMBER" VARCHAR2(2 CHAR), 
	"EMPLOYEE_NUMBER" VARCHAR2(2 CHAR), 
	"BUSSINESS_TYPE_CODE" VARCHAR2(2 CHAR), 
	"SALES_TERRITORY_NUMBER" VARCHAR2(4 CHAR), 
	"SALES_TERRITORY_NUMBER_COR" VARCHAR2(4 CHAR), 
	"ORGNL_POS_TRANSACTION_DATE" DATE, 
	"ORGNL_POS_TERM_NUMBER" VARCHAR2(5 CHAR), 
	"ORGNL_POS_TRANSACTION_NBR" VARCHAR2(5 CHAR), 
	"PURCHASE_ORDER_NUMBER" VARCHAR2(20 CHAR), 
	"BOOK_DATE_SEQUENCE" VARCHAR2(5 CHAR), 
	 CONSTRAINT "CUSTOMER_PK" PRIMARY KEY ("COST_CENTER_CODE", "TRANSACTION_DATE", "TERMINAL_NUMBER", "TRANSACTION_NUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STORDRFT_DATA"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STORDRFT_DATA" ;
