CREATE TABLE "STORDRFT"."CUSTOMER_CC_ACCOUNT_T" 
   (	"COST_CENTER_CODE" VARCHAR2(6 BYTE), 
	"TRANSACTION_DATE" VARCHAR2(8 BYTE), 
	"TERM_NUMBER" VARCHAR2(5 BYTE), 
	"TRANSACTION_NUMBER" VARCHAR2(5 BYTE), 
	"SEGMENT_CODE" VARCHAR2(2 BYTE), 
	"SUB_SEGMENT_CODE" VARCHAR2(2 BYTE), 
	"PAY_DISC_CODE" VARCHAR2(1 BYTE), 
	"TRANSACTOIN_TOTAL_AMT" VARCHAR2(7 BYTE), 
	"TRAN_TOTAL_AMT_SGN" VARCHAR2(1 BYTE), 
	"POS_LINE_COUNT" VARCHAR2(5 BYTE), 
	"PAY_AMOUNT" VARCHAR2(7 BYTE), 
	"PAY_AMOUNT_SGN" VARCHAR2(1 BYTE), 
	"PAY_DISCOUNT" VARCHAR2(7 BYTE), 
	"PAY_DISCOUNT_SGN" VARCHAR2(1 BYTE), 
	"SALES_DISCOUNT_AMT" VARCHAR2(7 BYTE), 
	"SALES_DISCOUNT_AMT_SGN" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STORDRFT_DATA" ;
