CREATE TABLE "STORDRFT"."CUSTOMER_BANK_CARD" 
   (	"CUSTOMER_BANK_CARD_ID" NUMBER(15,0) NOT NULL ENABLE, 
	"COST_CENTER_CODE" VARCHAR2(6 CHAR) NOT NULL ENABLE, 
	"TRANSACTION_DATE" DATE NOT NULL ENABLE, 
	"TERMINAL_NUMBER" VARCHAR2(5 CHAR) NOT NULL ENABLE, 
	"TRANSACTION_NUMBER" VARCHAR2(5 CHAR) NOT NULL ENABLE, 
	"SEGMENT_CODE" VARCHAR2(2 CHAR) NOT NULL ENABLE, 
	"SUB_SEGMENT_CODE" VARCHAR2(2 CHAR) NOT NULL ENABLE, 
	"BANK_CARD_ACCOUNT_NUMBER" VARCHAR2(16 CHAR), 
	"BANK_AUTH" VARCHAR2(9 CHAR), 
	"BANK_AMOUNT" NUMBER(9,2), 
	"BANK_TYPE" VARCHAR2(1 CHAR), 
	 CONSTRAINT "CUSTOMER_BANK_CARD_PK" PRIMARY KEY ("CUSTOMER_BANK_CARD_ID", "COST_CENTER_CODE", "TRANSACTION_DATE", "TERMINAL_NUMBER", "TRANSACTION_NUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STORDRFT_DATA"  ENABLE, 
	 CONSTRAINT "CUSTOMER_BANK_CARD_FK" FOREIGN KEY ("COST_CENTER_CODE", "TRANSACTION_DATE", "TERMINAL_NUMBER", "TRANSACTION_NUMBER")
	  REFERENCES "STORDRFT"."CUSTOMER" ("COST_CENTER_CODE", "TRANSACTION_DATE", "TERMINAL_NUMBER", "TRANSACTION_NUMBER") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STORDRFT_DATA" ;

  CREATE INDEX "STORDRFT"."CUSTOMER_BANK_CARD_IDX" ON "STORDRFT"."CUSTOMER_BANK_CARD" ("COST_CENTER_CODE", "TRANSACTION_DATE", "TERMINAL_NUMBER", "TRANSACTION_NUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STORDRFT_DATA" ;
