/**********************************************************
THIS DDL will create the table to validate current prod data 
CREATED : 12/03/2014 AXK326 CCN Project team....
**********************************************************/

CREATE TABLE CUSTOMER_DETAILS_AXK
   (	CUSTOMER_DETAIL_ID NUMBER(15,0) NOT NULL ENABLE, 
	COST_CENTER_CODE VARCHAR2(6 CHAR) NOT NULL ENABLE, 
	TRANSACTION_DATE DATE NOT NULL ENABLE, 
	TERMINAL_NUMBER VARCHAR2(5 CHAR) NOT NULL ENABLE, 
	TRANSACTION_NUMBER VARCHAR2(5 CHAR) NOT NULL ENABLE, 
	SEGMENT_CODE VARCHAR2(2 CHAR) NOT NULL ENABLE, 
	SALES_NUMBER VARCHAR2(9 CHAR) NOT NULL ENABLE, 
	ITEM_QUANTITY NUMBER(7,2), 
	ITEM_PRICE NUMBER(7,2), 
	ITEM_EXT_AMOUNT NUMBER(7,2), 
	ITEM_DISCOUNT_AMOUNT NUMBER(7,2), 
	ITEM_SALES_TAX_IND VARCHAR2(1 CHAR), 
	ITEM_DISCOUNT_CODE VARCHAR2(1 CHAR), 
	ITEM_DISCOUNT_TYPE VARCHAR2(1 CHAR), 
	SALES_PROMO_CODE VARCHAR2(2 CHAR), 
	GL_PRIME_ACCOUNT_NUMBER VARCHAR2(4 CHAR), 
	GL_SUB_ACCOUNT_NUMBER VARCHAR2(3 CHAR), 
	SCHEDULE_TYPE VARCHAR2(2 CHAR), 
	SCHEDULE_VERSION VARCHAR2(6 CHAR), 
	PRICE_LEVEL_CODE VARCHAR2(1 CHAR), 
	PERCENT_OFF_LEVEL NUMBER(7,2), 
	PROD_DESC_SRCE VARCHAR2(1 CHAR), 
	ORGNL_POS_TERM_NUMBER VARCHAR2(5 CHAR), 
	ORGNL_POS_TRANS_NUMBER VARCHAR2(5 CHAR), 
	 CONSTRAINT CUSTOMER_DETAILS_PK PRIMARY KEY (CUSTOMER_DETAIL_ID, COST_CENTER_CODE, TRANSACTION_DATE, TERMINAL_NUMBER, TRANSACTION_NUMBER) ENABLE, 
	 CONSTRAINT CUSTOMER_DETAILS_FK FOREIGN KEY (COST_CENTER_CODE, TRANSACTION_DATE, TERMINAL_NUMBER, TRANSACTION_NUMBER)
	  REFERENCES STORDRFT.CUSTOMER (COST_CENTER_CODE, TRANSACTION_DATE, TERMINAL_NUMBER, TRANSACTION_NUMBER) ENABLE
   ) ;

  CREATE INDEX STORDRFT.CUSTOMER_DETAILS_1_IDX ON STORDRFT.CUSTOMER_DETAILS (COST_CENTER_CODE, TRANSACTION_DATE, TERMINAL_NUMBER, TRANSACTION_NUMBER) 
  ;
