CREATE TABLE "STORDRFT"."CUSTOMER_SALES_TAX_T" 
   (	"COST_CENTER_CODE" VARCHAR2(6 BYTE), 
	"TRANSACTION_DATE" VARCHAR2(8 BYTE), 
	"TERM_NUMBER" VARCHAR2(5 BYTE), 
	"TRANSACTION_NUMBER" VARCHAR2(5 BYTE), 
	"SALES_TAX_CORR_IND" VARCHAR2(1 BYTE), 
	"SALES_TAX_COLL_AMT" VARCHAR2(7 BYTE), 
	"SALES_TAX_IND" VARCHAR2(1 BYTE), 
	"SALES_TAX_RATE" VARCHAR2(5 BYTE), 
	"SALES_TAX_CODE" VARCHAR2(5 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STORDRFT_DATA" ;
