
  CREATE TABLE CUSTOMER_SALES_TAX_T 
   (	COST_CENTER_CODE VARCHAR2(6 BYTE), 
	TRANSACTION_DATE VARCHAR2(8 BYTE), 
	TERM_NUMBER VARCHAR2(5 BYTE), 
	TRANSACTION_NUMBER VARCHAR2(5 BYTE), 
	SALES_TAX_CORR_IND VARCHAR2(1 BYTE), 
	SALES_TAX_COLL_AMT VARCHAR2(7 BYTE), 
	SALES_TAX_IND VARCHAR2(1 BYTE), 
	SALES_TAX_RATE VARCHAR2(5 BYTE), 
	SALES_TAX_CODE VARCHAR2(5 BYTE)
   );
