
  CREATE TABLE CUSTOMER_SALES_TAX 
   (	CUSTOMER_SALES_TAX_ID NUMBER(15,0) NOT NULL ENABLE, 
	COST_CENTER_CODE VARCHAR2(6 CHAR) NOT NULL ENABLE, 
	TRANSACTION_DATE DATE NOT NULL ENABLE, 
	TERMINAL_NUMBER VARCHAR2(5 CHAR) NOT NULL ENABLE, 
	TRANSACTION_NUMBER VARCHAR2(5 CHAR) NOT NULL ENABLE, 
	SALES_TAX_CORR_IND VARCHAR2(1 CHAR), 
	SALES_TAX_COLL_AMT NUMBER(7,2), 
	SALES_TAX_IND VARCHAR2(1 CHAR), 
	SALES_TAX_RATE NUMBER(5,3), 
	SALES_TAX_CODE VARCHAR2(5 CHAR), 
	CONSTRAINT CUSTOMER_SALES_TAX_PK PRIMARY KEY (CUSTOMER_SALES_TAX_ID, COST_CENTER_CODE, TRANSACTION_DATE, TERMINAL_NUMBER, TRANSACTION_NUMBER) ENABLE, 
	CONSTRAINT CUSTOMER_SALES_TAX_FK FOREIGN KEY (COST_CENTER_CODE, TRANSACTION_DATE, TERMINAL_NUMBER, TRANSACTION_NUMBER) REFERENCES CUSTOMER (COST_CENTER_CODE, TRANSACTION_DATE, TERMINAL_NUMBER, TRANSACTION_NUMBER) ENABLE
   );

  CREATE INDEX CUSTOMER_SALES_TAX_IDX ON CUSTOMER_SALES_TAX (COST_CENTER_CODE, TRANSACTION_DATE, TERMINAL_NUMBER, TRANSACTION_NUMBER);
