CREATE TABLE "STORDRFT"."CUSTOMER_FORM_OF_PAY" 
   (	"CUSTOMER_FORM_OF_PAY_ID" NUMBER(15,0) NOT NULL ENABLE, 
	"COST_CENTER_CODE" VARCHAR2(6 CHAR) NOT NULL ENABLE, 
	"TRANSACTION_DATE" DATE NOT NULL ENABLE, 
	"TERMINAL_NUMBER" VARCHAR2(5 CHAR) NOT NULL ENABLE, 
	"TRANSACTION_NUMBER" VARCHAR2(5 CHAR) NOT NULL ENABLE, 
	"SEGMENT_CODE" VARCHAR2(2 CHAR) NOT NULL ENABLE, 
	"SUB_SEGMENT_CODE" VARCHAR2(2 CHAR) NOT NULL ENABLE, 
	"PAY_DISC_CODE" VARCHAR2(1 CHAR), 
	"TRANSACTION_TOTAL_AMT" NUMBER(7,2), 
	"POS_LINE_COUNT" VARCHAR2(5 CHAR), 
	"PAY_AMOUNT" NUMBER(7,2), 
	"PAY_DISCOUNT" NUMBER(7,2), 
	"SALES_DISCOUNT_AMT" NUMBER(7,2), 
	 CONSTRAINT "CUSTOMER_FRM_OF_PAY_BNK_CRD_PK" PRIMARY KEY ("CUSTOMER_FORM_OF_PAY_ID", "COST_CENTER_CODE", "TRANSACTION_DATE", "TERMINAL_NUMBER", "TRANSACTION_NUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STORDRFT_DATA"  ENABLE, 
	 CONSTRAINT "CUSTOMER_FORM_OF_PAY_FK" FOREIGN KEY ("COST_CENTER_CODE", "TRANSACTION_DATE", "TERMINAL_NUMBER", "TRANSACTION_NUMBER")
	  REFERENCES "STORDRFT"."CUSTOMER" ("COST_CENTER_CODE", "TRANSACTION_DATE", "TERMINAL_NUMBER", "TRANSACTION_NUMBER") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STORDRFT_DATA" ;

  CREATE INDEX "STORDRFT"."CUSTOMER_FORM_OF_PAY_IDX" ON "STORDRFT"."CUSTOMER_FORM_OF_PAY" ("COST_CENTER_CODE", "TRANSACTION_DATE", "TERMINAL_NUMBER", "TRANSACTION_NUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STORDRFT_DATA" ;
