
  CREATE TABLE CUSTOMER_BANK_CARD 
   (	CUSTOMER_BANK_CARD_ID NUMBER(15,0) NOT NULL ENABLE, 
	COST_CENTER_CODE VARCHAR2(6 CHAR) NOT NULL ENABLE, 
	TRANSACTION_DATE DATE NOT NULL ENABLE, 
	TERMINAL_NUMBER VARCHAR2(5 CHAR) NOT NULL ENABLE, 
	TRANSACTION_NUMBER VARCHAR2(5 CHAR) NOT NULL ENABLE, 
	SEGMENT_CODE VARCHAR2(2 CHAR) NOT NULL ENABLE, 
	SUB_SEGMENT_CODE VARCHAR2(2 CHAR) NOT NULL ENABLE, 
	BANK_CARD_ACCOUNT_NUMBER VARCHAR2(16 CHAR), 
	BANK_AUTH VARCHAR2(9 CHAR), 
	BANK_AMOUNT NUMBER(9,2), 
	BANK_TYPE VARCHAR2(1 CHAR), 
	CONSTRAINT CUSTOMER_BANK_CARD_PK PRIMARY KEY (CUSTOMER_BANK_CARD_ID, COST_CENTER_CODE, TRANSACTION_DATE, TERMINAL_NUMBER, TRANSACTION_NUMBER) ENABLE, 
	CONSTRAINT CUSTOMER_BANK_CARD_FK FOREIGN KEY (COST_CENTER_CODE, TRANSACTION_DATE, TERMINAL_NUMBER, TRANSACTION_NUMBER) REFERENCES CUSTOMER (COST_CENTER_CODE, TRANSACTION_DATE, TERMINAL_NUMBER, TRANSACTION_NUMBER) ENABLE
   ) ;
