/*---------------------------------------
Below script will create tables for Store drafts tracking/printing services tables


Created: 01/18/2019 kxm302
------------------------------------------*/
  CREATE TABLE SD_CHECK_NBR_PRNT_EXTRCT_DTLS 
   (CHKS_ORDERED_DATE     DATE, 
	SRT_CHKDLY_SEQ_NBR    NUMBER, 
	COST_CENTER_CODE      VARCHAR2(6), 
	TERMINAL_NUMBER       VARCHAR2(5), 
	ORDERED_DRFT_NUMBER   NUMBER, 
	CHECK_DIGIT           NUMBER, 
	ROUTING_NBR           VARCHAR2(100), 
	ACCOUNT_NUMBER        VARCHAR2(100), 
	LETTER                VARCHAR2(1), 
	RUN_TYPE              VARCHAR2(1 ), 
	RUNTYPE_DESCRIPTION   VARCHAR2(1000), 
	USED_IN_POS_ON_DATE   DATE, 
	 CONSTRAINT SD_CHECK_NBR_PRNT_EXTRCT_DTLS PRIMARY KEY (CHKS_ORDERED_DATE, COST_CENTER_CODE, ORDERED_DRFT_NUMBER));
	 
	 
  CREATE TABLE SD_CHECK_NBR_RUN_TYPE_PRNT_DTLS 
   (STORE_DRAFT_CHECK_RUN_TYPE   VARCHAR2(1), 
	NO_OF_BOOKS                  NUMBER, 
	CHECKS_PER_BOOK              NUMBER, 
	STORE_DRFT_THRESHOLD         NUMBER, 
	BANK_ACCOUNT_NBR             VARCHAR2(100), 
	BANK_ROUTING_NBR             VARCHAR2(100), 
	EFFECTIVE_DATE               DATE, 
	EXPIRATION_DATE              DATE, 
	CREATED_BY_USER_ID           VARCHAR2(100), 
	CREATED_ON_DATE              DATE, 
	 CONSTRAINT SD_CHECK_NBR_RUN_TYPE_PRNT_DTLS_PK PRIMARY KEY (STORE_DRAFT_CHECK_RUN_TYPE, EFFECTIVE_DATE));

  CREATE TABLE SD_CHECK_NBR_TRCKNG_DTLS 
   (COST_CENTER_CODE           VARCHAR2(6), 
	CHKS_ORDERED_DATE          DATE, 
	ORDERED_STRTNG_DRFT        NUMBER, 
	ORDERED_ENDNG_DRFT         NUMBER, 
	 CONSTRAINT SD_CHECK_NBR_TRCKNG_DTLS_PK PRIMARY KEY (COST_CENTER_CODE, CHKS_ORDERED_DATE));


  CREATE TABLE STORE_RUN_TYP_THRSHLD_DTLS 
   (COST_CENTER_CODE              VARCHAR2(6 ), 
	STORE_DRAFT_CHECK_RUN_TYPE    VARCHAR2(1 ), 
	EFFECTIVE_DATE                DATE, 
	EXPIRATION_DATE               DATE, 
	CREATED_BY_USER_ID            VARCHAR2(100), 
	CREATED_ON_DATE               DATE, 
	 CONSTRAINT STORE_RUN_TYP_THRSHLD_DTLS_PK PRIMARY KEY (COST_CENTER_CODE, EFFECTIVE_DATE));	 