CREATE TABLE ROYAL_BANK_REPORT_EXT_T
(TRANSIT_NUMBER VARCHAR2(5 BYTE),
 ACCOUNT_NUMBER VARCHAR2(7 BYTE),
 TRANSIT_TYPE   VARCHAR2(2 BYTE),
 SUB_CODE       VARCHAR2(2 BYTE),
 SERIAL_NUMBER  VARCHAR2(8 BYTE),
 AMOUNT         VARCHAR2(11 BYTE),
 STATUS_FLAG    VARCHAR2(1 BYTE),
 FILLER         VARCHAR2(1 BYTE),
 ISSUE_DATE     VARCHAR2(6 BYTE),
 PAID_DATE      VARCHAR2(6 BYTE),
 TRANS_CODE     VARCHAR2(4 BYTE),
 CHECK_NUMBER   VARCHAR2(9 BYTE),
 FILLER1        VARCHAR2(9 BYTE),
 STATUS         VARCHAR2(2 BYTE),
 TOLRNC_AMOUNT  VARCHAR2(3 BYTE)
 )
    ORGANIZATION EXTERNAL 
    ( TYPE ORACLE_LOADER
      DEFAULT DIRECTORY "STORDRFT_DATAFILES"
      ACCESS PARAMETERS
      ( RECORDS DELIMITED BY NEWLINE
        LOAD WHEN (TRANSIT_TYPE != "99")
        SKIP 5
        badfile     STORDRFT_DATAFILES:'ROYAL_BANK_REPORT.bad'
        logfile     STORDRFT_DATAFILES:'ROYAL_BANK_REPORT.log'
        discardfile STORDRFT_DATAFILES:'ROYAL_BANK_REPORT.dsc'
        FIELDS MISSING FIELD VALUES ARE NULL
              (TRANSIT_NUMBER  CHAR(5),
               ACCOUNT_NUMBER  CHAR(7),
               TRANSIT_TYPE    CHAR(2),
               SUB_CODE        CHAR(2),
               SERIAL_NUMBER   CHAR(8),
               AMOUNT          CHAR(11),
               STATUS_FLAG     CHAR(1),
               FILLER          CHAR(1),
               ISSUE_DATE      CHAR(6),
               PAID_DATE       CHAR(6),
               TRANS_CODE      CHAR(4),
               CHECK_NUMBER    CHAR(9),
               FILLER1         CHAR(9),
               STATUS          CHAR(2),
               TOLRNC_AMOUNT   CHAR(3)))
        LOCATION
       ( 'DAREPORT.567.txt'
       ))
       REJECT LIMIT UNLIMITED;