/*
CCNCC-18 This script will Drop obsolete External tables.
Created  : 07/26/2019 sxs484 
*/
SELECT *
  FROM USER_EXTERNAL_TABLES
 WHERE table_name like 'DLY%';

DROP TABLE DLY_BANK_PAID_DATA ;
DROP TABLE DLY_CSTMR_BANK_CARD ;
DROP TABLE DLY_CSTMR_FORM_OF_PAY ;
DROP TABLE DLY_CSTMR_SALES_TAX ;
DROP TABLE DLY_CUSTOMER ;
DROP TABLE DLY_CUSTOMER_DETAILS ;
DROP TABLE DLY_CUSTOMER_LINE_ITEM_DATA ;
DROP TABLE DLY_DISBURSMENT_LINE_ITEM_DATA ;
DROP TABLE DLY_INSTALLER_LINE_ITEM_DATA ;
DROP TABLE DLY_ISSUE_CHANGE_DATA ;


SELECT *
  FROM USER_EXTERNAL_TABLES
 WHERE table_name like 'DLY%';