CREATE TABLE "STORDRFT"."ERROR_LOG" 
   (	"ERROR_ID" NUMBER NOT NULL ENABLE, 
	"COST_CENTER" VARCHAR2(6 BYTE) NOT NULL ENABLE, 
	"ERROR_DATE" DATE NOT NULL ENABLE, 
	"MODULE" VARCHAR2(200 BYTE) NOT NULL ENABLE, 
	"CHECK_SERIAL_NUMBER" VARCHAR2(100 BYTE), 
	"ERROR_TEXT" VARCHAR2(4000 BYTE), 
	"NOTES" VARCHAR2(2000 BYTE), 
	"ERROR_CODE" VARCHAR2(9 BYTE), 
	 CONSTRAINT "ERROR_LOG_PK" PRIMARY KEY ("ERROR_ID", "COST_CENTER", "ERROR_DATE", "MODULE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STORDRFT_DATA"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STORDRFT_DATA" ;

   COMMENT ON COLUMN "STORDRFT"."ERROR_LOG"."ERROR_ID" IS 'Transaction Sequence ID';
   COMMENT ON COLUMN "STORDRFT"."ERROR_LOG"."COST_CENTER" IS 'Cost Center cauding error';
   COMMENT ON COLUMN "STORDRFT"."ERROR_LOG"."ERROR_DATE" IS 'Date error was added';
   COMMENT ON COLUMN "STORDRFT"."ERROR_LOG"."MODULE" IS 'Application Name/or batch job name';
   COMMENT ON COLUMN "STORDRFT"."ERROR_LOG"."ERROR_TEXT" IS 'Error message text';
   COMMENT ON COLUMN "STORDRFT"."ERROR_LOG"."NOTES" IS 'Free Notes....';
   COMMENT ON COLUMN "STORDRFT"."ERROR_LOG"."ERROR_CODE" IS 'ERROR CODE';
