
  CREATE TABLE FILE_1099_MONTHLY 
   (	FILE_NUMBER VARCHAR2(7), 
	STORE_NUMBER VARCHAR2(4), 
	CHECK_NUMBER VARCHAR2(4), 
	CHECK_AMOUNT VARCHAR2(10), 
	CHECK_DATE VARCHAR2(6), 
	JV_NUMBER VARCHAR2(6), 
	FILLER VARCHAR2(1), 
	TRANSACTION_CODE VARCHAR2(2), 
	TAX_ID VARCHAR2(9)
   ) ;

