/*---------------------------------------
Below script will GRANT roles for tables of Store drafts tracking/printing services tables


Created: 01/18/2019 kxm302
------------------------------------------*/

GRANT  ALTER ON SD_CHECK_NBR_TRCKNG_DTLS TO STDRFTUSR;
GRANT  DELETE ON SD_CHECK_NBR_TRCKNG_DTLS TO STDRFTUSR;
GRANT  INDEX ON SD_CHECK_NBR_TRCKNG_DTLS TO STDRFTUSR;
GRANT  INSERT ON SD_CHECK_NBR_TRCKNG_DTLS TO STDRFTUSR;
GRANT  SELECT ON SD_CHECK_NBR_TRCKNG_DTLS TO STDRFTUSR;
GRANT  UPDATE ON SD_CHECK_NBR_TRCKNG_DTLS TO STDRFTUSR;
GRANT  REFERENCES ON SD_CHECK_NBR_TRCKNG_DTLS TO STDRFTUSR;
GRANT  READ ON SD_CHECK_NBR_TRCKNG_DTLS TO STDRFTUSR;
GRANT  ON COMMIT REFRESH ON SD_CHECK_NBR_TRCKNG_DTLS TO STDRFTUSR;
GRANT  QUERY REWRITE ON SD_CHECK_NBR_TRCKNG_DTLS TO STDRFTUSR;
GRANT  DEBUG ON SD_CHECK_NBR_TRCKNG_DTLS TO STDRFTUSR;
GRANT  FLASHBACK ON SD_CHECK_NBR_TRCKNG_DTLS TO STDRFTUSR;
GRANT  SELECT ON SD_CHECK_NBR_PRNT_EXTRCT_DTLS TO STDRFTUSR;
GRANT  SELECT ON SD_CHECK_NBR_RUN_TYPE_PRNT_DTLS TO STDRFTUSR;
GRANT  SELECT ON STORE_RUN_TYP_THRSHLD_DTLS TO STDRFTUSR;
