--Load_date column add

ALTER TABLE STORE_DRAFTS ADD LOAD_DATE DATE;
ALTER TABLE HST_STORE_DRAFTS ADD LOAD_DATE DATE;
ALTER TABLE UNATTACHED_MNL_DRFT_DTL ADD LOAD_DATE DATE;
ALTER TABLE UNATTACHED_MNL_DRFT_DTL_HST ADD LOAD_DATE DATE;