/*
Below tables are used for daily suntrust paids laod

Created : 11/7/2019 jxc517 CCN Project Team....
Changed :
*/

  --DROP TABLE PAID_DETAILS_SUNTRUST;
  --DROP TABLE PAID_DETAILS_SUNTRUST_HST;
  CREATE TABLE PAID_DETAILS_SUNTRUST
   (FILLER                   VARCHAR2(1), 
    TRANSACTION_TYPE_CODE    VARCHAR2(2), 
    PAID_BANK_NUMBER         VARCHAR2(3), 
    PAID_ACCOUNT_NUMBER      VARCHAR2(10), 
    PAID_CHECK_SERIAL_NUMBER VARCHAR2(10), 
    PAID_DATE_PAID           VARCHAR2(6), 
    PAID_AMONUT_ITEMS        VARCHAR2(10), 
    PAID_CPCS_NUMBER         VARCHAR2(9)
   );

   CREATE TABLE PAID_DETAILS_SUNTRUST_HST AS SELECT A.*, SYSDATE AS LOAD_DATE, 10 AS RUN_NBR FROM PAID_DETAILS_SUNTRUST A WHERE 1=2;