/*
Below tables are used for daily royal paids laod

Created : 11/7/2019 jxc517 CCN Project Team....
Changed :
*/

  --DROP TABLE PAID_DETAILS_ROYAL;
  --DROP TABLE PAID_DETAILS_ROYAL_HST;
  CREATE TABLE PAID_DETAILS_ROYAL
   (TRANSACTION_NUMBER      VARCHAR2(5), 
    ACCOUNT_NUMBER          VARCHAR2(7), 
    TRANSACTION_TYPE_CODE   VARCHAR2(2), 
    SUB_REPORT_CODE         VARCHAR2(2), 
    SERIAL_NUMBER_STORE     VARCHAR2(4), 
    SERIAL_NUMBER_SEQUENCE  VARCHAR2(4), 
    AMOUNT                  VARCHAR2(11), 
    STATUS_FLAG             VARCHAR2(2), 
    ISSUE_DATE              VARCHAR2(6), 
    PAID_DATE               VARCHAR2(6), 
    TRANSACTION_CODE        VARCHAR2(3),
    FILLER                  VARCHAR2(1),
    CHECK_NUMBER_CC         VARCHAR2(4), 
    CHECK_NUMBER_SQ         VARCHAR2(4), 
    CHECK_NUMBER_CK         VARCHAR2(1), 
    FILLER1                 VARCHAR2(9), 
    STATUS                  VARCHAR2(2), 
    TOLERANCE_AMOUNT        VARCHAR2(3), 
    TOLERANCE_INDICATOR     VARCHAR2(1)
   );

   CREATE TABLE PAID_DETAILS_ROYAL_HST AS SELECT A.*, SYSDATE AS LOAD_DATE, 10 AS RUN_NBR FROM PAID_DETAILS_ROYAL A WHERE 1=2;