CREATE TABLE ROYAL_BANK_RPT_MAIN
(TRANSIT_NUMBER      VARCHAR2(5),  
ACCOUNT_NUMBER      VARCHAR2(11), 
TRANSIT_TYPE        VARCHAR2(2),  
SUB_CODE            VARCHAR2(2),  
SERIAL_NUMBER       VARCHAR2(11), 
AMOUNT              VARCHAR2(11), 
STATUS_FLAG         VARCHAR2(1) ,  
ISSUE_DATE          VARCHAR2(11), 
PAID_DATE           VARCHAR2(11), 
TRANS_CODE          VARCHAR2(4),  
CHECK_NUMBER        VARCHAR2(11),
STATUS              VARCHAR2(2),  
TOLRNC_AMOUNT       VARCHAR2(3));