CREATE TABLE ROYAL_DEBIT_TTL_RPT
(TRANSIT_TYPE        VARCHAR2(2),
TRANSIT_NUMBER      VARCHAR2(5),
ACCOUNT_NUMBER      VARCHAR2(11),
DESCRIPTION         VARCHAR2(32),
DB_AMOUNT           VARCHAR2(15));