/*
Created : nxk927 07/23/2018
          cleaning up all store drafts. Removing all the pos tables and packages as we don't need them any more
*/
DROP TABLE CCN_INTERIM_DEPOSITS;
DROP TABLE CCN_GIFT_CARD_LOG;
DROP TABLE CCN_BATCH_SUMMARY;
DROP TABLE CCN_TAX_TTL;
DROP TABLE CCN_TW_TAX_TTL;
DROP TABLE BANK_PAID_DATA;
DROP TABLE CSTMR_BANK_CARD_DATA;
DROP TABLE CSTMR_FORM_OF_PAY_DATA;
DROP TABLE CSTMR_SALES_TAX_DATA;
DROP TABLE CUSTOMER_DATA;
DROP TABLE CUSTOMER_DETAILS_DATA;
DROP TABLE CUSTOMER_LINE_ITEM_DATA;
DROP TABLE DISBRSMT_LINE_ITEM_DATA;
DROP TABLE INSTLR_LN_ITEM_DATA;
DROP TABLE ISSUE_CHANGE_DATA;
DROP TABLE POSXML_BNK_PAID_DATA_TMP;

DROP PACKAGE SD_RECONCILE_DIFF_REPORT_PKG;
