/*
Created : nxk927 07/23/2018
          cleaning up all store drafts. Removing all the pos tables and packages as we don't need them any more
*/
DROP TABLE POS_CUSTOMER_BANK_CARD;
DROP TABLE POS_CUSTOMER_DETAILS;
DROP TABLE POS_CUSTOMER_FORM_OF_PAY;
DROP TABLE POS_CUSTOMER_SALES_TAX;
DROP TABLE POS_HST_STORE_DRAFTS;
DROP TABLE POS_HST_STORE_DRAFTS_DETAIL;
DROP TABLE POS_STORE_DRAFTS;
DROP TABLE POS_STORE_DRAFTS_DETAIL;
DROP TABLE POS_UNATTACHED_MNL_DRFT_DTL;
DROP TABLE POS_UNATTCHD_MNL_DRFT_HST;
DROP TABLE CCN_INTERIM_DEPOSITS;
DROP TABLE CCN_GIFT_CARD_LOG;
DROP TABLE CCN_BATCH_SUMMARY;
DROP TABLE CCN_TAX_TTL;
DROP TABLE CCN_TW_TAX_TTL;
DROP TABLE BANK_PAID_DATA;
DROP TABLE CSTMR_BANK_CARD_DATA;
DROP TABLE CSTMR_FORM_OF_PAY_DATA;
DROP TABLE CSTMR_SALES_TAX_DATA;
DROP TABLE CUSTOMER_DATA;
DROP TABLE CUSTOMER_DETAILS_DATA;
DROP TABLE CUSTOMER_LINE_ITEM_DATA;
DROP TABLE DISBRSMT_LINE_ITEM_DATA;
DROP TABLE INSTLR_LN_ITEM_DATA;
DROP TABLE ISSUE_CHANGE_DATA;
DROP TABLE POSXML_BNK_PAID_DATA_TMP;
DROP TABLE POS_CCN_ACCUMS;
DROP TABLE POS_CCN_DISC;
DROP TABLE POS_CSTMR_FORM_OF_PAY;
DROP TABLE POS_CUSTOMER;
DROP PACKAGE SD_RECONCILE_DIFF_REPORT_PKG;
DROP PACKAGE MF_SD_DAILY_LOAD;