-- SXT410 04/14/2015
ALTER TABLE STORE_DRAFTS ADD FNCL_SRVCS_SENT_DATE DATE;
ALTER TABLE HST_STORE_DRAFTS ADD FNCL_SRVCS_SENT_DATE DATE;
ALTER TABLE UNATTACHED_MNL_DRFT_DTL ADD FNCL_SRVCS_SENT_DATE DATE;
ALTER TABLE UNATTACHED_MNL_DRFT_DTL_HST ADD FNCL_SRVCS_SENT_DATE DATE;