CREATE TABLE "STORDRFT"."STORE_DRAFTS" 
   (	"COST_CENTER_CODE" VARCHAR2(6 CHAR) NOT NULL ENABLE, 
	"CHECK_SERIAL_NUMBER" VARCHAR2(10 CHAR) NOT NULL ENABLE, 
	"TRANSACTION_DATE" DATE NOT NULL ENABLE, 
	"TERMINAL_NUMBER" VARCHAR2(5 CHAR), 
	"TRANSACTION_NUMBER" VARCHAR2(5 CHAR), 
	"CUSTOMER_ACCOUNT_NUMBER" VARCHAR2(9 CHAR), 
	"CUSTOMER_JOB_NUMBER" VARCHAR2(2 CHAR), 
	"POS_TRANSACTION_CODE" VARCHAR2(2 CHAR), 
	"POS_TRANSACTION_TIME" VARCHAR2(4 CHAR), 
	"BANK_NUMBER" VARCHAR2(3 CHAR), 
	"BANK_ACCOUNT_NUMBER" VARCHAR2(16 CHAR), 
	"BANK_REFERENCE" VARCHAR2(6 CHAR), 
	"PAYEE_NAME" VARCHAR2(30 CHAR), 
	"ADDRESS_LINE_1" VARCHAR2(30 CHAR), 
	"ADDRESS_LINE_2" VARCHAR2(30 CHAR), 
	"CITY" VARCHAR2(15 CHAR), 
	"STATE_CODE" VARCHAR2(2 CHAR), 
	"ZIP_CODE_PREFIX" VARCHAR2(6 CHAR), 
	"ZIP_CODE_SUFFIX" VARCHAR2(4 CHAR), 
	"PHONE_AREA_CODE" VARCHAR2(3 CHAR), 
	"PHONE_NUMBER" VARCHAR2(7 CHAR), 
	"EMPLOYEE_NUMBER" VARCHAR2(2 CHAR), 
	"ISSUE_DATE" DATE, 
	"PAID_DATE" DATE, 
	"STOP_PAY_DATE" DATE, 
	"STOP_PAY_REMOVE_DATE" DATE, 
	"VOID_DATE" DATE, 
	"AMOUNT_CHANGE_DATE" DATE, 
	"GROSS_AMOUNT" NUMBER(9,2), 
	"RETAIN_AMOUNT" NUMBER(9,2), 
	"NET_AMOUNT" NUMBER(9,2), 
	"ORIGINAL_NET_AMOUNT" NUMBER(9,2), 
	"BANK_PAID_AMOUNT" NUMBER(9,2), 
	"TRANSACTION_SOURCE" VARCHAR2(1 CHAR), 
	"CHANGE_DATE" DATE, 
	"CHANGE_SOURCE" VARCHAR2(8 CHAR), 
	"SLS_BOOK_DATE" VARCHAR2(4 CHAR), 
	"CYCLE_RUN_NUMBER" VARCHAR2(2 CHAR), 
	"BOOK_DATE_SEQUENCE" VARCHAR2(5 CHAR), 
	"REASON_CODE" VARCHAR2(2 CHAR), 
	 CONSTRAINT "STORE_DRAFTS_MASTER_PK" PRIMARY KEY ("COST_CENTER_CODE", "CHECK_SERIAL_NUMBER", "TRANSACTION_DATE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STORDRFT_DATA"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STORDRFT_DATA" ;
