-- sxt410 09/16/2015 Script to create STORE_DRAFT_INFO_VW view.
CREATE OR REPLACE FORCE VIEW STORDRFT.STORE_DRAFT_INFO_VW
AS 
SELECT
/*******************************************************************************
This view holds Match Store Draft Information and any relevant data.

Created  : 09/15/2015 SXT410 CCN Project Team...
Modified : 
*******************************************************************************/
        SDD.COST_CENTER_CODE
       ,SDD.CHECK_SERIAL_NUMBER
       ,SDD.TRANSACTION_DATE DRAFT_TRANS_DATE
       ,CD.TRANSACTION_DATE CUSTOMER_TRANS_DATE
       ,SDD.TERMINAL_NUMBER
       ,SDD.TRANSACTION_NUMBER
       ,SDD.CUSTOMER_ACCOUNT_NUMBER
       ,SDD.CUSTOMER_JOB_NUMBER
       ,SDD.GL_PRIME_ACCOUNT_NUMBER
       ,SDD.GL_SUB_ACCOUNT_NUMBER DRAFT_GL_SUB_ACCOUNT_NUMBER
       ,CD.GL_SUB_ACCOUNT_NUMBER  CUSTOMER_GL_SUB_ACCOUNT_NUMBER
       ,CD.SALES_NUMBER
       ,CD.ITEM_QUANTITY
       ,CD.ITEM_PRICE
       ,CD.ITEM_EXT_AMOUNT
       ,SDD.LBR_TRANSACTION_DATE
       ,SDD.LBR_TERMINAL_NUMBER
       ,SDD.LBR_TRANSACTION_NUMBER
       ,CD.SEGMENT_CODE
  FROM STORE_DRAFTS_DETAIL SDD,
       CUSTOMER_DETAILS CD
WHERE  SDD.COST_CENTER_CODE                                   = CD.COST_CENTER_CODE
   AND NVL(SDD.LBR_TERMINAL_NUMBER, SDD.TERMINAL_NUMBER)      = CD.TERMINAL_NUMBER
   AND NVL(SDD.LBR_TRANSACTION_NUMBER,SDD.TRANSACTION_NUMBER) = CD.TRANSACTION_NUMBER;