/*******************************************************************************
Adding FSS_INVOICE_NUMBER to STORE_DRAFTS, HST_STORE_DRAFTS, UNATTACHED_MNL_DRFT_DTL
and UNATTACHED_MNL_DRFT_DTL_HST

Created : 03/18/2016 jxc517/sxh487 CCN Project....
Changed : 
*******************************************************************************/

ALTER TABLE STORE_DRAFTS ADD FSS_INVOICE_NUMBER NUMBER;
ALTER TABLE HST_STORE_DRAFTS ADD FSS_INVOICE_NUMBER NUMBER;
ALTER TABLE UNATTACHED_MNL_DRFT_DTL ADD FSS_INVOICE_NUMBER NUMBER;
ALTER TABLE UNATTACHED_MNL_DRFT_DTL_HST ADD FSS_INVOICE_NUMBER NUMBER;
