CREATE TABLE "STORDRFT"."STORE_DRAFTS_T" 
   (	"COST_CENTER_CODE" VARCHAR2(6 BYTE), 
	"CHECK_SERIAL_NUMBER" VARCHAR2(10 BYTE), 
	"TRANSACTION_DATE" VARCHAR2(8 BYTE), 
	"TERM_NUMBER" VARCHAR2(5 BYTE), 
	"TRANSACTION_NUMBER" VARCHAR2(5 BYTE), 
	"CUSTOMER_ACCOUNT_NUMBER" VARCHAR2(9 BYTE), 
	"CUSTOMER_JOB_NUMBER" VARCHAR2(2 BYTE), 
	"POS_TRANSACTION_CODE" VARCHAR2(2 BYTE), 
	"POS_TRANSACTION_TIME" VARCHAR2(4 BYTE), 
	"BANK_NUMBER" VARCHAR2(3 BYTE), 
	"BANK_ACCOUNT_NUMBER" VARCHAR2(16 BYTE), 
	"BANK_REFERENCE" VARCHAR2(6 BYTE), 
	"PAYEE_NAME" VARCHAR2(30 BYTE), 
	"ADDRESS_LINE_1" VARCHAR2(30 BYTE), 
	"ADDRESS_LINE_2" VARCHAR2(30 BYTE), 
	"CITY" VARCHAR2(15 BYTE), 
	"STATE_CODE" VARCHAR2(2 BYTE), 
	"ZIP_CODE_PREFIX" VARCHAR2(6 BYTE), 
	"ZIP_CODE_SUFFIX" VARCHAR2(4 BYTE), 
	"PHONE_AREA_CODE" VARCHAR2(3 BYTE), 
	"PHONE_NUMBER" VARCHAR2(7 BYTE), 
	"EMPLOYEE_NUMBER" VARCHAR2(2 BYTE), 
	"ISSUE_DATE" VARCHAR2(8 BYTE), 
	"PAID_DATE" VARCHAR2(8 BYTE), 
	"STOP_PAY_DATE" VARCHAR2(8 BYTE), 
	"STOP_PAY_REMOVE_DATE" VARCHAR2(8 BYTE), 
	"VOID_DATE" VARCHAR2(8 BYTE), 
	"AMOUNT_CHANGE_DATE" VARCHAR2(8 BYTE), 
	"GROSS_AMOUNT" VARCHAR2(9 BYTE), 
	"RETAIN_AMOUNT" VARCHAR2(9 BYTE), 
	"NET_AMOUNT" VARCHAR2(9 BYTE), 
	"ORIGINAL_NET_AMOUNT" VARCHAR2(9 BYTE), 
	"BANK_PAID_AMOUNT" VARCHAR2(9 BYTE), 
	"TRANSACTION_SOURCE" VARCHAR2(1 BYTE), 
	"CHANGE_DATE" VARCHAR2(8 BYTE), 
	"CHANGE_SOURCE" VARCHAR2(8 BYTE), 
	"SLS_BOOK_DATE" VARCHAR2(4 BYTE), 
	"CYCLE_RUN_NUMBER" VARCHAR2(2 BYTE), 
	"BOOK_DATE_SEQUENCE" VARCHAR2(5 BYTE), 
	"REASON_CODE" VARCHAR2(2 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STORDRFT_DATA" ;
