CREATE OR REPLACE SYNONYM COST_CENTER FOR COSTCNTR.COST_CENTER;
CREATE SYNONYM CCN_COMMON_TOOLS FOR CCN_UTILITY.CCN_COMMON_TOOLS;

/*
--below script should be executed in store draft user
CREATE OR REPLACE SYNONYM SD_UI_INTERFACE_APP_PKG FOR STORDRFT.SD_UI_INTERFACE_APP_PKG;
*/