CREATE OR REPLACE SYNONYM COST_CENTER FOR COSTCNTR.COST_CENTER;

/*
--below script should be executed in store draft user
CREATE OR REPLACE SYNONYM SD_UI_INTERFACE_APP_PKG FOR STORDRFT.SD_UI_INTERFACE_APP_PKG;
*/