CREATE TABLE "STORDRFT"."TEMP_STORE_DRAFTS_LABOR_DETAIL" 
   (	"COST_CENTER_CODE" VARCHAR2(6 BYTE), 
	"TRANSACTION_DATE" VARCHAR2(8 BYTE), 
	"TERM_NUMBER" VARCHAR2(5 BYTE), 
	"TRANSACTION_NUMBER" VARCHAR2(5 BYTE), 
	"SEGMENT_CODE" VARCHAR2(2 BYTE), 
	"SALES_NUMBER" VARCHAR2(9 BYTE), 
	"ITEM_QTY" VARCHAR2(7 BYTE), 
	"ITEM_PRICE" VARCHAR2(7 BYTE), 
	"ITEM_PRICE_SGN" VARCHAR2(1 BYTE), 
	"ITEM_EXT_AMOUNT" VARCHAR2(7 BYTE), 
	"ITEM_EXT_AMT_SGN" VARCHAR2(1 BYTE), 
	"ITEM_DISC_AMOUNT" VARCHAR2(7 BYTE), 
	"ITEM_DISC_AMT_SGN" VARCHAR2(1 BYTE), 
	"ITEM_SLS_TAX_IND" VARCHAR2(1 BYTE), 
	"ITEM_DISC_CODE" VARCHAR2(1 BYTE), 
	"ITEM_DISC_TYPE" VARCHAR2(1 BYTE), 
	"SLS_PROMO_CODE" VARCHAR2(2 BYTE), 
	"GL_PRIME_ACCT_NBR" VARCHAR2(4 BYTE), 
	"GL_SUB_ACCT_NBR" VARCHAR2(3 BYTE), 
	"SCHED_TYPE" VARCHAR2(2 BYTE), 
	"SCHED_VERSION" VARCHAR2(6 BYTE), 
	"PRICE_LVL_CODE" VARCHAR2(1 BYTE), 
	"PERCENT_OFF_LVL" VARCHAR2(3 BYTE), 
	"PROD_DESC_SRCE" VARCHAR2(1 BYTE), 
	"ORIG_POS_TERM_NBR" VARCHAR2(5 BYTE), 
	"ORIG_POS_TRAN_NBR" VARCHAR2(5 BYTE)
   ) 
   ORGANIZATION EXTERNAL 
    ( TYPE ORACLE_LOADER
      DEFAULT DIRECTORY "STORDRFT_LOAD_FILES"
      ACCESS PARAMETERS
      ( RECORDS FIXED 103 
        badfile "STORDRFT_LOAD_FILES":'TEMP_STORE_DRAFTS_LABOR_DETAIL.bad'
        logfile "STORDRFT_LOAD_FILES":'TEMP_STORE_DRAFTS_LABOR_DETAIL.log'
        discardfile "STORDRFT_LOAD_FILES":'TEMP_STORE_DRAFTS_LABOR_DETAIL.dsc'
        FIELDS(
        COST_CENTER_CODE  CHAR(6), 
        TRANSACTION_DATE  CHAR(8), 
        TERM_NUMBER CHAR(5), 
        TRANSACTION_NUMBER CHAR(5), 
        SEGMENT_CODE CHAR(2), 
        SALES_NUMBER CHAR(9),
        ITEM_QTY     CHAR(7),
        ITEM_PRICE   CHAR(7),
        ITEM_PRICE_SGN CHAR(1),
        ITEM_EXT_AMOUNT CHAR(7),
        ITEM_EXT_AMT_SGN  CHAR(1),
        ITEM_DISC_AMOUNT CHAR(7),
        ITEM_DISC_AMT_SGN  CHAR(1),
        ITEM_SLS_TAX_IND  CHAR(1),
        ITEM_DISC_CODE  CHAR(1),
        ITEM_DISC_TYPE  CHAR(1),
        SLS_PROMO_CODE CHAR(2),
        GL_PRIME_ACCT_NBR CHAR(4),
        GL_SUB_ACCT_NBR CHAR(3),
        SCHED_TYPE CHAR(2),
        SCHED_VERSION CHAR(6),
        PRICE_LVL_CODE  CHAR(1),
        PERCENT_OFF_LVL CHAR(3),
        PROD_DESC_SRCE  CHAR(1),
        ORIG_POS_TERM_NBR CHAR(5), 
        ORIG_POS_TRAN_NBR CHAR(5)
                               )
                  )
      LOCATION
       ( 'CCN99CTR_LLINEIT.TXT'
       )
    );
