CREATE TABLE "STORDRFT"."UNATTACHED_MNL_DRFT_DTL" 
   (	"COST_CENTER_CODE" VARCHAR2(6 CHAR) NOT NULL ENABLE, 
	"CHECK_SERIAL_NUMBER" VARCHAR2(10 CHAR) NOT NULL ENABLE, 
	"TRANSACTION_DATE" DATE NOT NULL ENABLE, 
	"TERMINAL_NUMBER" VARCHAR2(5 CHAR) NOT NULL ENABLE, 
	"TRANSACTION_NUMBER" VARCHAR2(5 CHAR), 
	"CUSTOMER_ACCOUNT_NUMBER" VARCHAR2(9 CHAR), 
	"CUSTOMER_JOB_NUMBER" VARCHAR2(2 CHAR), 
	"GL_PRIME_ACCOUNT_NUMBER" VARCHAR2(4 CHAR), 
	"GL_SUB_ACCOUNT_NUMBER" VARCHAR2(3 CHAR), 
	"ITEM_QUANTITY" NUMBER(7,2), 
	"ITEM_PRICE" NUMBER(7,2), 
	"ITEM_EXT_AMOUNT" NUMBER(7,2), 
	"BOOK_DATE_SEQUENCE" VARCHAR2(5 CHAR), 
	"LBR_TRANSACTION_DATE" DATE, 
	"LBR_TERMINAL_NUMBER" VARCHAR2(5 CHAR), 
	"LBR_TRANSACTION_NUMBER" VARCHAR2(5 CHAR), 
	"PROCESS_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STORDRFT_DATA" ;

  CREATE INDEX "STORDRFT"."UNATTCHD_MNL_DRFT_DTL_IDX" ON "STORDRFT"."UNATTACHED_MNL_DRFT_DTL" ("COST_CENTER_CODE", "CHECK_SERIAL_NUMBER", "TRANSACTION_DATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STORDRFT_DATA" ;
