/*
Script Name: UTIL_SYNONYMS_STRDRFT.sql
Purpose    : Synonyms for ROLE_DETAILS and SECURITY_MATRIX in STRDRFT 

Created    : 11/08/2017 axt754 CCN Project....
Changed    : 
*/


CREATE OR REPLACE SYNONYM SECURITY_MATRIX FOR CCN_UTILITY.SECURITY_MATRIX;

CREATE OR REPLACE SYNONYM ROLE_DETAILS FOR CCN_UTILITY.ROLE_DETAILS;