/**************************** 
updating the TERRITORY_TYPE_BUSN_CODE in TERRITORY table           
and cost center name in the cost center table 

Business Rules : The value used in TERRITORY_TYPE_BUSN_CODE column should be present in CODE_DETAIL table 

SELECT * FROM CODE_DETAIL  
WHERE CODE_DETAIL.CODE_HEADER_NAME = 'TERRITORY_TYPE_BUSN_CODE'    
AND CODE_DETAIL.CODE_DETAIL_VALUE IN ('CM','MS','NR','PM','RR'); 

Created : vxv336 02/10/2017           

*******************************/

UPDATE COST_CENTER SET COST_CENTER_NAME = 'DETROIT COMM REP' WHERE COST_CENTER_CODE = '754789';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'CM' WHERE COST_CENTER_CODE = '754789';

UPDATE COST_CENTER SET COST_CENTER_NAME = 'DETROIT MULTI SEG REP' WHERE COST_CENTER_CODE = '754794';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '754794';

UPDATE COST_CENTER SET COST_CENTER_NAME = 'DETROIT RES REPAINT REP' WHERE COST_CENTER_CODE = '756078';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '756078';

UPDATE COST_CENTER SET COST_CENTER_NAME = 'GRAND RAPIDS RES REPAINT REP' WHERE COST_CENTER_CODE = '756549';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '756549';

UPDATE COST_CENTER SET COST_CENTER_NAME = 'GRAND RAPIDS RES REPAINT REP' WHERE COST_CENTER_CODE = '756705';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '756705';

UPDATE COST_CENTER SET COST_CENTER_NAME = 'GRAND RAPIDS NEW RES REP' WHERE COST_CENTER_CODE = '756709';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'NR' WHERE COST_CENTER_CODE = '756709';

UPDATE COST_CENTER SET COST_CENTER_NAME = 'NORTHERN MICHIGAN RES REPAINT REP' WHERE COST_CENTER_CODE = '756864';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '756864';

UPDATE COST_CENTER SET COST_CENTER_NAME = 'MID OHIO RES REPAINT REP' WHERE COST_CENTER_CODE = '756822';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '756822';

UPDATE COST_CENTER SET COST_CENTER_NAME = 'MID OHIO RES REPAINT REP' WHERE COST_CENTER_CODE = '756866';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '756866';

UPDATE COST_CENTER SET COST_CENTER_NAME = 'MID OHIO MULTI SEG REP' WHERE COST_CENTER_CODE = '758487';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '758487';

UPDATE COST_CENTER SET COST_CENTER_NAME = 'SEATTLE RES REPAINT REP' WHERE COST_CENTER_CODE = '75Q016';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '75Q016';

UPDATE COST_CENTER SET COST_CENTER_NAME = 'SEATTLE NEW RES REP' WHERE COST_CENTER_CODE = '756586';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'NR' WHERE COST_CENTER_CODE = '756586';

UPDATE COST_CENTER SET COST_CENTER_NAME = 'SEATTLE COMM REP' WHERE COST_CENTER_CODE = '756915';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'CM' WHERE COST_CENTER_CODE = '756915';

UPDATE COST_CENTER SET COST_CENTER_NAME = 'GREEN BAY COMM REP' WHERE COST_CENTER_CODE = '754161';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'CM' WHERE COST_CENTER_CODE = '754161';

UPDATE COST_CENTER SET COST_CENTER_NAME = 'GREEN BAY PROP MAINT REP' WHERE COST_CENTER_CODE = '754168';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'PM' WHERE COST_CENTER_CODE = '754168';

UPDATE COST_CENTER SET COST_CENTER_NAME = 'CHICAGO METRO PROP MAINT REP' WHERE COST_CENTER_CODE = '75Q391';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'PM' WHERE COST_CENTER_CODE = '75Q391';

UPDATE COST_CENTER SET COST_CENTER_NAME = 'CHICAGO METRO COMM REP' WHERE COST_CENTER_CODE = '754485';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'CM' WHERE COST_CENTER_CODE = '754485';

UPDATE COST_CENTER SET COST_CENTER_NAME = 'CHICAGO METRO COMM REP' WHERE COST_CENTER_CODE = '754607';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'CM' WHERE COST_CENTER_CODE = '754607';

UPDATE COST_CENTER SET COST_CENTER_NAME = 'MADISON COMM REP' WHERE COST_CENTER_CODE = '754017';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'CM' WHERE COST_CENTER_CODE = '754017';

UPDATE COST_CENTER SET COST_CENTER_NAME = 'MADISON NEW RES REP' WHERE COST_CENTER_CODE = '754157';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'NR' WHERE COST_CENTER_CODE = '754157';

UPDATE COST_CENTER SET COST_CENTER_NAME = 'MADISON RES REPAINT REP' WHERE COST_CENTER_CODE = '754929';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '754929';

UPDATE COST_CENTER SET COST_CENTER_NAME = 'INDIANAPOLIS NEW RES REP' WHERE COST_CENTER_CODE = '756725';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'NR' WHERE COST_CENTER_CODE = '756725';

UPDATE COST_CENTER SET COST_CENTER_NAME = 'LOUISVILLE MULTI SEG REP' WHERE COST_CENTER_CODE = '754812';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '754812';

UPDATE COST_CENTER SET COST_CENTER_NAME = 'LOUISVILLE NEW RES REP' WHERE COST_CENTER_CODE = '756271';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'NR' WHERE COST_CENTER_CODE = '756271';

UPDATE COST_CENTER SET COST_CENTER_NAME = 'CINCINNATI COMM REP' WHERE COST_CENTER_CODE = '754696';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'CM' WHERE COST_CENTER_CODE = '754696';

UPDATE COST_CENTER SET COST_CENTER_NAME = 'CEDAR RAPIDS PROP MAINT REP' WHERE COST_CENTER_CODE = '754154';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'PM' WHERE COST_CENTER_CODE = '754154';

UPDATE COST_CENTER SET COST_CENTER_NAME = 'CEDAR RAPIDS MULTI SEG REP' WHERE COST_CENTER_CODE = '754267';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '754267';

UPDATE COST_CENTER SET COST_CENTER_NAME = 'MINNESOTA MULTI SEG REP' WHERE COST_CENTER_CODE = '75Q375';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '75Q375';

UPDATE COST_CENTER SET COST_CENTER_NAME = 'TWIN CITIES RES REPAINT REP' WHERE COST_CENTER_CODE = '754268';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '754268';

UPDATE COST_CENTER SET COST_CENTER_NAME = 'OMAHA RES REPAINT REP' WHERE COST_CENTER_CODE = '754810';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '754810';

UPDATE COST_CENTER SET COST_CENTER_NAME = 'WESTERN NEW YORK RES REPAINT REP' WHERE COST_CENTER_CODE = '756660';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '756660';

UPDATE COST_CENTER SET COST_CENTER_NAME = 'BALTIMORE RES REPAINT REP' WHERE COST_CENTER_CODE = '75Q406';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '75Q406';

UPDATE COST_CENTER SET COST_CENTER_NAME = 'CAPITAL MULTI SEG REP' WHERE COST_CENTER_CODE = '754036';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '754036';

UPDATE COST_CENTER SET COST_CENTER_NAME = 'CAPITAL COMM REP' WHERE COST_CENTER_CODE = '755555';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'CM' WHERE COST_CENTER_CODE = '755555';

UPDATE COST_CENTER SET COST_CENTER_NAME = 'CAPITAL MULTI SEG REP' WHERE COST_CENTER_CODE = '755618';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '755618';

UPDATE COST_CENTER SET COST_CENTER_NAME = 'METRO CONNECTICUT MULTI SEG REP' WHERE COST_CENTER_CODE = '754621';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '754621';

UPDATE COST_CENTER SET COST_CENTER_NAME = 'METRO NEW YORK MULTI SEG REP' WHERE COST_CENTER_CODE = '75Q418';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '75Q418';

UPDATE COST_CENTER SET COST_CENTER_NAME = 'METRO NEW YORK MULTI SEG REP' WHERE COST_CENTER_CODE = '75Q456';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '75Q456';

UPDATE COST_CENTER SET COST_CENTER_NAME = 'METRO NEW JERSEY MULTI SEG REP' WHERE COST_CENTER_CODE = '75Q428';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '75Q428';

UPDATE COST_CENTER SET COST_CENTER_NAME = 'METRO NEW JERSEY MULTI SEG REP' WHERE COST_CENTER_CODE = '75Q430';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '75Q430';

UPDATE COST_CENTER SET COST_CENTER_NAME = 'METRO NEW JERSEY MULTI SEG REP' WHERE COST_CENTER_CODE = '75Q434';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '75Q434';

UPDATE COST_CENTER SET COST_CENTER_NAME = 'METRO NEW JERSEY MULTI SEG REP' WHERE COST_CENTER_CODE = '75Q450';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '75Q450';

UPDATE COST_CENTER SET COST_CENTER_NAME = 'LONG ISLAND MULTI SEG REP' WHERE COST_CENTER_CODE = '75Q454';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '75Q454';

UPDATE COST_CENTER SET COST_CENTER_NAME = 'LONG ISLAND MULTI SEG REP' WHERE COST_CENTER_CODE = '75Q462';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '75Q462';

UPDATE COST_CENTER SET COST_CENTER_NAME = 'LONG ISLAND MULTI SEG REP' WHERE COST_CENTER_CODE = '75Q466';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '75Q466';

UPDATE COST_CENTER SET COST_CENTER_NAME = 'LONG ISLAND MULTI SEG REP' WHERE COST_CENTER_CODE = '755986';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '755986';

UPDATE COST_CENTER SET COST_CENTER_NAME = 'DELMAR RES REPAINT REP' WHERE COST_CENTER_CODE = '75Q408';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '75Q408';

UPDATE COST_CENTER SET COST_CENTER_NAME = 'DELMAR MULTI SEG REP' WHERE COST_CENTER_CODE = '754512';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '754512';

UPDATE COST_CENTER SET COST_CENTER_NAME = 'DELMAR PROP MAINT REP' WHERE COST_CENTER_CODE = '755549';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'PM' WHERE COST_CENTER_CODE = '755549';

UPDATE COST_CENTER SET COST_CENTER_NAME = 'DELMAR COMM REP' WHERE COST_CENTER_CODE = '755601';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'CM' WHERE COST_CENTER_CODE = '755601';

UPDATE COST_CENTER SET COST_CENTER_NAME = 'PHILADELPHIA COMM REP' WHERE COST_CENTER_CODE = '75Q442';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'CM' WHERE COST_CENTER_CODE = '75Q442';

UPDATE COST_CENTER SET COST_CENTER_NAME = 'PHILADELPHIA COMM REP' WHERE COST_CENTER_CODE = '756922';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'CM' WHERE COST_CENTER_CODE = '756922';

UPDATE COST_CENTER SET COST_CENTER_NAME = 'PITTSBURGH RES REPAINT REP' WHERE COST_CENTER_CODE = '754511';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '754511';

UPDATE COST_CENTER SET COST_CENTER_NAME = 'PITTSBURGH PROP MAINT REP' WHERE COST_CENTER_CODE = '755516';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'PM' WHERE COST_CENTER_CODE = '755516';

UPDATE COST_CENTER SET COST_CENTER_NAME = 'CHARLOTTE METRO MULTI SEG REP' WHERE COST_CENTER_CODE = '75Q585';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '75Q585';

UPDATE COST_CENTER SET COST_CENTER_NAME = 'CHARLESTON METRO MULTI SEG REP' WHERE COST_CENTER_CODE = '754446';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '754446';

UPDATE COST_CENTER SET COST_CENTER_NAME = 'CHARLESTON METRO COMM REP' WHERE COST_CENTER_CODE = '754466';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'CM' WHERE COST_CENTER_CODE = '754466';

UPDATE COST_CENTER SET COST_CENTER_NAME = 'WILMINGTON COMM REP' WHERE COST_CENTER_CODE = '754578';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'CM' WHERE COST_CENTER_CODE = '754578';

UPDATE COST_CENTER SET COST_CENTER_NAME = 'ATLANTA RES REPAINT REP' WHERE COST_CENTER_CODE = '754112';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '754112';

UPDATE COST_CENTER SET COST_CENTER_NAME = 'ATLANTA COMM REP' WHERE COST_CENTER_CODE = '754916';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'CM' WHERE COST_CENTER_CODE = '754916';

UPDATE COST_CENTER SET COST_CENTER_NAME = 'ATLANTA NEW RES REP' WHERE COST_CENTER_CODE = '755761';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'NR' WHERE COST_CENTER_CODE = '755761';

UPDATE COST_CENTER SET COST_CENTER_NAME = 'ATLANTA MULTI SEG REP' WHERE COST_CENTER_CODE = '756059';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '756059';

UPDATE COST_CENTER SET COST_CENTER_NAME = 'ATLANTA MULTI SEG REP' WHERE COST_CENTER_CODE = '756490';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '756490';

-- Failed: value too large for column COST_CENTER_NAME
-- UPDATE COST_CENTER SET COST_CENTER_NAME = 'SOUTHWEST FLORIDA METRO MULTI SEG REP' WHERE COST_CENTER_CODE = '754444';
-- UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '754444';

UPDATE COST_CENTER SET COST_CENTER_NAME = 'SOUTH FLORIDA METRO MULTI SEG REP' WHERE COST_CENTER_CODE = '754451';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '754451';

UPDATE COST_CENTER SET COST_CENTER_NAME = 'TAMPA MULTI SEG REP' WHERE COST_CENTER_CODE = '75Q220';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '75Q220';

UPDATE COST_CENTER SET COST_CENTER_NAME = 'FLORIDA PANHANDLE MULTI SEG REP' WHERE COST_CENTER_CODE = '75Q562';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '75Q562';

UPDATE COST_CENTER SET COST_CENTER_NAME = 'ORLANDO NEW RES REP' WHERE COST_CENTER_CODE = '75Q225';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'NR' WHERE COST_CENTER_CODE = '75Q225';

UPDATE COST_CENTER SET COST_CENTER_NAME = 'ORLANDO MULTI SEG REP' WHERE COST_CENTER_CODE = '754041';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '754041';

UPDATE COST_CENTER SET COST_CENTER_NAME = 'ORLANDO COMM REP' WHERE COST_CENTER_CODE = '758356';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'CM' WHERE COST_CENTER_CODE = '758356';

UPDATE COST_CENTER SET COST_CENTER_NAME = 'ORLANDO RES REPAINT REP' WHERE COST_CENTER_CODE = '758440';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '758440';

UPDATE COST_CENTER SET COST_CENTER_NAME = 'EAST COAST FLORIDA NEW RES REP' WHERE COST_CENTER_CODE = '75Q191';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'NR' WHERE COST_CENTER_CODE = '75Q191';

UPDATE COST_CENTER SET COST_CENTER_NAME = 'EAST COAST FLORIDA PROP MAINT REP' WHERE COST_CENTER_CODE = '75Q213';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'PM' WHERE COST_CENTER_CODE = '75Q213';

UPDATE COST_CENTER SET COST_CENTER_NAME = 'EAST COAST FLORIDA COMM REP' WHERE COST_CENTER_CODE = '75Q548';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'CM' WHERE COST_CENTER_CODE = '75Q548';

UPDATE COST_CENTER SET COST_CENTER_NAME = 'EAST COAST FLORIDA MULTI SEG REP' WHERE COST_CENTER_CODE = '754235';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '754235';

UPDATE COST_CENTER SET COST_CENTER_NAME = 'EAST COAST FLORIDA NEW RES REP' WHERE COST_CENTER_CODE = '754270';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'NR' WHERE COST_CENTER_CODE = '754270';

UPDATE COST_CENTER SET COST_CENTER_NAME = 'PUERTO RICO PROP MAINT REP' WHERE COST_CENTER_CODE = '756028';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'PM' WHERE COST_CENTER_CODE = '756028';

UPDATE COST_CENTER SET COST_CENTER_NAME = 'MEMPHIS PROP MAINT REP' WHERE COST_CENTER_CODE = '756125';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'PM' WHERE COST_CENTER_CODE = '756125';

UPDATE COST_CENTER SET COST_CENTER_NAME = 'LOUISIANA MULTI SEG REP' WHERE COST_CENTER_CODE = '75Q546';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '75Q546';

UPDATE COST_CENTER SET COST_CENTER_NAME = 'LOUISIANA MULTI SEG REP' WHERE COST_CENTER_CODE = '75Q573';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '75Q573';

UPDATE COST_CENTER SET COST_CENTER_NAME = 'LOUISIANA COMM REP' WHERE COST_CENTER_CODE = '756520';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'CM' WHERE COST_CENTER_CODE = '756520';

UPDATE COST_CENTER SET COST_CENTER_NAME = 'NEW ORLEANS MULTI SEG REP' WHERE COST_CENTER_CODE = '75Q531';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '75Q531';

UPDATE COST_CENTER SET COST_CENTER_NAME = 'SAN ANTONIO PROP MAINT REP' WHERE COST_CENTER_CODE = '75Q147';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'PM' WHERE COST_CENTER_CODE = '75Q147';

UPDATE COST_CENTER SET COST_CENTER_NAME = 'SAN ANTONIO MULTI SEG REP' WHERE COST_CENTER_CODE = '756638';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '756638';

UPDATE COST_CENTER SET COST_CENTER_NAME = 'AUSTIN RES REPAINT REP' WHERE COST_CENTER_CODE = '75Q636';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '75Q636';

UPDATE COST_CENTER SET COST_CENTER_NAME = 'AUSTIN MULTI SEG REP' WHERE COST_CENTER_CODE = '75Q678';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '75Q678';

UPDATE COST_CENTER SET COST_CENTER_NAME = 'HOUSTON RES REPAINT REP' WHERE COST_CENTER_CODE = '75Q157';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '75Q157';

UPDATE COST_CENTER SET COST_CENTER_NAME = 'MID-TEXAS MULTI SEG REP' WHERE COST_CENTER_CODE = '75Q650';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '75Q650';

UPDATE COST_CENTER SET COST_CENTER_NAME = 'CALIFORNIA NORTH MULTI SEG REP' WHERE COST_CENTER_CODE = '754768';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '754768';

UPDATE COST_CENTER SET COST_CENTER_NAME = 'CALIFORNIA NORTH RES REPAINT REP' WHERE COST_CENTER_CODE = '756842';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '756842';

UPDATE COST_CENTER SET COST_CENTER_NAME = 'CALIFORNIA NORTH COMM REP' WHERE COST_CENTER_CODE = '757839';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'CM' WHERE COST_CENTER_CODE = '757839';

UPDATE COST_CENTER SET COST_CENTER_NAME = 'CALIFORNIA CENTRAL RES REPAINT REP' WHERE COST_CENTER_CODE = '75Q068';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '75Q068';

UPDATE COST_CENTER SET COST_CENTER_NAME = 'CALIFORNIA BAY MULTI SEG REP' WHERE COST_CENTER_CODE = '756326';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '756326';

UPDATE COST_CENTER SET COST_CENTER_NAME = 'CALIFORNIA BAY MULTI SEG REP' WHERE COST_CENTER_CODE = '756464';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '756464';

UPDATE COST_CENTER SET COST_CENTER_NAME = 'LOS ANGELES MULTI SEG REP' WHERE COST_CENTER_CODE = '75Q045';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '75Q045';

UPDATE COST_CENTER SET COST_CENTER_NAME = 'LOS ANGELES RES REPAINT REP' WHERE COST_CENTER_CODE = '75Q079';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '75Q079';

UPDATE COST_CENTER SET COST_CENTER_NAME = 'LOS ANGELES PROP MAINT REP' WHERE COST_CENTER_CODE = '75Q096';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'PM' WHERE COST_CENTER_CODE = '75Q096';

UPDATE COST_CENTER SET COST_CENTER_NAME = 'LOS ANGELES RES REPAINT REP' WHERE COST_CENTER_CODE = '75Q098';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '75Q098';

UPDATE COST_CENTER SET COST_CENTER_NAME = 'LOS ANGELES MULTI SEG REP' WHERE COST_CENTER_CODE = '75Q101';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '75Q101';

UPDATE COST_CENTER SET COST_CENTER_NAME = 'LOS ANGELES COMM REP' WHERE COST_CENTER_CODE = '75Q612';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'CM' WHERE COST_CENTER_CODE = '75Q612';

UPDATE COST_CENTER SET COST_CENTER_NAME = 'LOS ANGELES RES REPAINT REP' WHERE COST_CENTER_CODE = '75Q635';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '75Q635';

UPDATE COST_CENTER SET COST_CENTER_NAME = 'LOS ANGELES MULTI SEG REP' WHERE COST_CENTER_CODE = '754951';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '754951';

UPDATE COST_CENTER SET COST_CENTER_NAME = 'LOS ANGELES COMM REP' WHERE COST_CENTER_CODE = '754965';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'CM' WHERE COST_CENTER_CODE = '754965';

UPDATE COST_CENTER SET COST_CENTER_NAME = 'HAWAII MULTI SEG REP' WHERE COST_CENTER_CODE = '756734';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '756734';

UPDATE COST_CENTER SET COST_CENTER_NAME = 'SAN FERNANDO RES REPAINT REP' WHERE COST_CENTER_CODE = '757932';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '757932';

UPDATE COST_CENTER SET COST_CENTER_NAME = 'NORTHERN COLORADO RES REPAINT REP' WHERE COST_CENTER_CODE = '75Q118';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '75Q118';

UPDATE COST_CENTER SET COST_CENTER_NAME = 'SALT LAKE CITY RES REPAINT REP' WHERE COST_CENTER_CODE = '75Q162';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '75Q162';

UPDATE COST_CENTER SET COST_CENTER_NAME = 'SALT LAKE CITY NEW RES REP' WHERE COST_CENTER_CODE = '75Q163';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'NR' WHERE COST_CENTER_CODE = '75Q163';

UPDATE COST_CENTER SET COST_CENTER_NAME = 'SALT LAKE CITY RES REPAINT REP' WHERE COST_CENTER_CODE = '75Q173';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '75Q173';

UPDATE COST_CENTER SET COST_CENTER_NAME = 'SALT LAKE CITY RES REPAINT REP' WHERE COST_CENTER_CODE = '75Q178';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '75Q178';

UPDATE COST_CENTER SET COST_CENTER_NAME = 'SALT LAKE CITY RES REPAINT REP' WHERE COST_CENTER_CODE = '754913';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '754913';

UPDATE COST_CENTER SET COST_CENTER_NAME = 'ARIZONA RES REPAINT REP' WHERE COST_CENTER_CODE = '755834';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '755834';

UPDATE COST_CENTER SET COST_CENTER_NAME = 'SPRINGFIELD NEW RES REP' WHERE COST_CENTER_CODE = '754117';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'NR' WHERE COST_CENTER_CODE = '754117';

UPDATE COST_CENTER SET COST_CENTER_NAME = 'SOUTHWEST ONTARIO MULTI SEG REP' WHERE COST_CENTER_CODE = '766823';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '766823';

UPDATE COST_CENTER SET COST_CENTER_NAME = 'QUEBEC RES REPAINT REP' WHERE COST_CENTER_CODE = '76Q856';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '76Q856';

UPDATE COST_CENTER SET COST_CENTER_NAME = 'QUEBEC MULTI SEG REP' WHERE COST_CENTER_CODE = '76Q863';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '76Q863';

UPDATE COST_CENTER SET COST_CENTER_NAME = 'QUEBEC MULTI SEG REP' WHERE COST_CENTER_CODE = '76Q865';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '76Q865';

UPDATE COST_CENTER SET COST_CENTER_NAME = 'QUEBEC COMM REP' WHERE COST_CENTER_CODE = '76Q867';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'CM' WHERE COST_CENTER_CODE = '76Q867';

UPDATE COST_CENTER SET COST_CENTER_NAME = 'QUEBEC MULTI SEG REP' WHERE COST_CENTER_CODE = '76Q874';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '76Q874';

UPDATE COST_CENTER SET COST_CENTER_NAME = 'EASTERN CANADA MULTI SEG REP' WHERE COST_CENTER_CODE = '76Q873';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '76Q873';

UPDATE COST_CENTER SET COST_CENTER_NAME = 'EASTERN CANADA MULTI SEG REP' WHERE COST_CENTER_CODE = '76Q875';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '76Q875';

UPDATE COST_CENTER SET COST_CENTER_NAME = 'BRITISH COLUMBIA COMM REP' WHERE COST_CENTER_CODE = '76Q233';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'CM' WHERE COST_CENTER_CODE = '76Q233';

UPDATE COST_CENTER SET COST_CENTER_NAME = 'BRITISH COLUMBIA MULTI SEG REP' WHERE COST_CENTER_CODE = '76Q237';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '76Q237';

UPDATE COST_CENTER SET COST_CENTER_NAME = 'BRITISH COLUMBIA RES REPAINT REP' WHERE COST_CENTER_CODE = '76Q246';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '76Q246';

UPDATE COST_CENTER SET COST_CENTER_NAME = 'NORTHERN ALBERTA MULTI SEG REP' WHERE COST_CENTER_CODE = '76Q255';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '76Q255';

UPDATE COST_CENTER SET COST_CENTER_NAME = 'SASKMAN NEW RES REP' WHERE COST_CENTER_CODE = '76Q236';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'NR' WHERE COST_CENTER_CODE = '76Q236';

COMMIT;