/**************************** 
updating the TERRITORY_TYPE_BUSN_CODE in TERRITORY table           
and cost center name in the cost center table 

Business Rules : The value used in TERRITORY_TYPE_BUSN_CODE column should be present in CODE_DETAIL table 

SELECT * FROM CODE_DETAIL  
WHERE CODE_DETAIL.CODE_HEADER_NAME = 'TERRITORY_TYPE_BUSN_CODE'    
AND CODE_DETAIL.CODE_DETAIL_VALUE IN ('CM','MS','NR','PM','RR'); 

Created : vxv336 02/10/2017

*******************************/

BEGIN
   CCN_BATCH_PKG.LOCK_DATABASE_SP();
END;
/

SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '754789';
UPDATE COST_CENTER SET COST_CENTER_NAME = 'DETROIT COMM REP' WHERE COST_CENTER_CODE = '754789' AND NVL(COST_CENTER_NAME, 'X') <> 'DETROIT COMM REP';

SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '754794';
UPDATE COST_CENTER SET COST_CENTER_NAME = 'DETROIT MULTI SEG REP' WHERE COST_CENTER_CODE = '754794' AND NVL(COST_CENTER_NAME, 'X') <> 'DETROIT MULTI SEG REP';

SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '756078';
UPDATE COST_CENTER SET COST_CENTER_NAME = 'DETROIT RES REPAINT REP' WHERE COST_CENTER_CODE = '756078' AND NVL(COST_CENTER_NAME, 'X') <> 'DETROIT RES REPAINT REP';

SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '756549';
UPDATE COST_CENTER SET COST_CENTER_NAME = 'GRAND RAPIDS RES REPAINT REP' WHERE COST_CENTER_CODE = '756549' AND NVL(COST_CENTER_NAME, 'X') <> 'GRAND RAPIDS RES REPAINT REP';

SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '756705';
UPDATE COST_CENTER SET COST_CENTER_NAME = 'GRAND RAPIDS RES REPAINT REP' WHERE COST_CENTER_CODE = '756705' AND NVL(COST_CENTER_NAME, 'X') <> 'GRAND RAPIDS RES REPAINT REP';

SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '756709';
UPDATE COST_CENTER SET COST_CENTER_NAME = 'GRAND RAPIDS NEW RES REP' WHERE COST_CENTER_CODE = '756709' AND NVL(COST_CENTER_NAME, 'X') <> 'GRAND RAPIDS NEW RES REP';

SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '756864';
UPDATE COST_CENTER SET COST_CENTER_NAME = 'NORTHERN MICHIGAN RES REPAINT REP' WHERE COST_CENTER_CODE = '756864' AND NVL(COST_CENTER_NAME, 'X') <> 'NORTHERN MICHIGAN RES REPAINT REP';

SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '756822';
UPDATE COST_CENTER SET COST_CENTER_NAME = 'MID OHIO RES REPAINT REP' WHERE COST_CENTER_CODE = '756822' AND NVL(COST_CENTER_NAME, 'X') <> 'MID OHIO RES REPAINT REP';

SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '756866';
UPDATE COST_CENTER SET COST_CENTER_NAME = 'MID OHIO RES REPAINT REP' WHERE COST_CENTER_CODE = '756866' AND NVL(COST_CENTER_NAME, 'X') <> 'MID OHIO RES REPAINT REP';

SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '758487';
UPDATE COST_CENTER SET COST_CENTER_NAME = 'MID OHIO MULTI SEG REP' WHERE COST_CENTER_CODE = '758487' AND NVL(COST_CENTER_NAME, 'X') <> 'MID OHIO MULTI SEG REP';

SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q016';
UPDATE COST_CENTER SET COST_CENTER_NAME = 'SEATTLE RES REPAINT REP' WHERE COST_CENTER_CODE = '75Q016' AND NVL(COST_CENTER_NAME, 'X') <> 'SEATTLE RES REPAINT REP';

SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '756586';
UPDATE COST_CENTER SET COST_CENTER_NAME = 'SEATTLE NEW RES REP' WHERE COST_CENTER_CODE = '756586' AND NVL(COST_CENTER_NAME, 'X') <> 'SEATTLE NEW RES REP';

SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '756915';
UPDATE COST_CENTER SET COST_CENTER_NAME = 'SEATTLE COMM REP' WHERE COST_CENTER_CODE = '756915' AND NVL(COST_CENTER_NAME, 'X') <> 'SEATTLE COMM REP';

SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '754161';
UPDATE COST_CENTER SET COST_CENTER_NAME = 'GREEN BAY COMM REP' WHERE COST_CENTER_CODE = '754161' AND NVL(COST_CENTER_NAME, 'X') <> 'GREEN BAY COMM REP';

SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '754168';
UPDATE COST_CENTER SET COST_CENTER_NAME = 'GREEN BAY PROP MAINT REP' WHERE COST_CENTER_CODE = '754168' AND NVL(COST_CENTER_NAME, 'X') <> 'GREEN BAY PROP MAINT REP';

SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q391';
UPDATE COST_CENTER SET COST_CENTER_NAME = 'CHICAGO METRO PROP MAINT REP' WHERE COST_CENTER_CODE = '75Q391' AND NVL(COST_CENTER_NAME, 'X') <> 'CHICAGO METRO PROP MAINT REP';

SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '754485';
UPDATE COST_CENTER SET COST_CENTER_NAME = 'CHICAGO METRO COMM REP' WHERE COST_CENTER_CODE = '754485' AND NVL(COST_CENTER_NAME, 'X') <> 'CHICAGO METRO COMM REP';

SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '754607';
UPDATE COST_CENTER SET COST_CENTER_NAME = 'CHICAGO METRO COMM REP' WHERE COST_CENTER_CODE = '754607' AND NVL(COST_CENTER_NAME, 'X') <> 'CHICAGO METRO COMM REP';

SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '754017';
UPDATE COST_CENTER SET COST_CENTER_NAME = 'MADISON COMM REP' WHERE COST_CENTER_CODE = '754017' AND NVL(COST_CENTER_NAME, 'X') <> 'MADISON COMM REP';

SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '754157';
UPDATE COST_CENTER SET COST_CENTER_NAME = 'MADISON NEW RES REP' WHERE COST_CENTER_CODE = '754157' AND NVL(COST_CENTER_NAME, 'X') <> 'MADISON NEW RES REP';

SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '754929';
UPDATE COST_CENTER SET COST_CENTER_NAME = 'MADISON RES REPAINT REP' WHERE COST_CENTER_CODE = '754929' AND NVL(COST_CENTER_NAME, 'X') <> 'MADISON RES REPAINT REP';

SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '756725';
UPDATE COST_CENTER SET COST_CENTER_NAME = 'INDIANAPOLIS NEW RES REP' WHERE COST_CENTER_CODE = '756725' AND NVL(COST_CENTER_NAME, 'X') <> 'INDIANAPOLIS NEW RES REP';

SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '754812';
UPDATE COST_CENTER SET COST_CENTER_NAME = 'LOUISVILLE MULTI SEG REP' WHERE COST_CENTER_CODE = '754812' AND NVL(COST_CENTER_NAME, 'X') <> 'LOUISVILLE MULTI SEG REP';

SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '756271';
UPDATE COST_CENTER SET COST_CENTER_NAME = 'LOUISVILLE NEW RES REP' WHERE COST_CENTER_CODE = '756271' AND NVL(COST_CENTER_NAME, 'X') <> 'LOUISVILLE NEW RES REP';

SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '754696';
UPDATE COST_CENTER SET COST_CENTER_NAME = 'CINCINNATI COMM REP' WHERE COST_CENTER_CODE = '754696' AND NVL(COST_CENTER_NAME, 'X') <> 'CINCINNATI COMM REP';

SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '754154';
UPDATE COST_CENTER SET COST_CENTER_NAME = 'CEDAR RAPIDS PROP MAINT REP' WHERE COST_CENTER_CODE = '754154' AND NVL(COST_CENTER_NAME, 'X') <> 'CEDAR RAPIDS PROP MAINT REP';

SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '754267';
UPDATE COST_CENTER SET COST_CENTER_NAME = 'CEDAR RAPIDS MULTI SEG REP' WHERE COST_CENTER_CODE = '754267' AND NVL(COST_CENTER_NAME, 'X') <> 'CEDAR RAPIDS MULTI SEG REP';

SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q375';
UPDATE COST_CENTER SET COST_CENTER_NAME = 'MINNESOTA MULTI SEG REP' WHERE COST_CENTER_CODE = '75Q375' AND NVL(COST_CENTER_NAME, 'X') <> 'MINNESOTA MULTI SEG REP';

SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '754268';
UPDATE COST_CENTER SET COST_CENTER_NAME = 'TWIN CITIES RES REPAINT REP' WHERE COST_CENTER_CODE = '754268' AND NVL(COST_CENTER_NAME, 'X') <> 'TWIN CITIES RES REPAINT REP';

SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '754810';
UPDATE COST_CENTER SET COST_CENTER_NAME = 'OMAHA RES REPAINT REP' WHERE COST_CENTER_CODE = '754810' AND NVL(COST_CENTER_NAME, 'X') <> 'OMAHA RES REPAINT REP';

SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '756660';
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WESTERN NEW YORK RES REPAINT REP' WHERE COST_CENTER_CODE = '756660' AND NVL(COST_CENTER_NAME, 'X') <> 'WESTERN NEW YORK RES REPAINT REP';

SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q406';
UPDATE COST_CENTER SET COST_CENTER_NAME = 'BALTIMORE RES REPAINT REP' WHERE COST_CENTER_CODE = '75Q406' AND NVL(COST_CENTER_NAME, 'X') <> 'BALTIMORE RES REPAINT REP';

SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '754036';
UPDATE COST_CENTER SET COST_CENTER_NAME = 'CAPITAL MULTI SEG REP' WHERE COST_CENTER_CODE = '754036' AND NVL(COST_CENTER_NAME, 'X') <> 'CAPITAL MULTI SEG REP';

SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '755555';
UPDATE COST_CENTER SET COST_CENTER_NAME = 'CAPITAL COMM REP' WHERE COST_CENTER_CODE = '755555' AND NVL(COST_CENTER_NAME, 'X') <> 'CAPITAL COMM REP';

SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '755618';
UPDATE COST_CENTER SET COST_CENTER_NAME = 'CAPITAL MULTI SEG REP' WHERE COST_CENTER_CODE = '755618' AND NVL(COST_CENTER_NAME, 'X') <> 'CAPITAL MULTI SEG REP';

SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '754621';
UPDATE COST_CENTER SET COST_CENTER_NAME = 'METRO CONNECTICUT MULTI SEG REP' WHERE COST_CENTER_CODE = '754621' AND NVL(COST_CENTER_NAME, 'X') <> 'METRO CONNECTICUT MULTI SEG REP';

SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q418';
UPDATE COST_CENTER SET COST_CENTER_NAME = 'METRO NEW YORK MULTI SEG REP' WHERE COST_CENTER_CODE = '75Q418' AND NVL(COST_CENTER_NAME, 'X') <> 'METRO NEW YORK MULTI SEG REP';

SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q456';
UPDATE COST_CENTER SET COST_CENTER_NAME = 'METRO NEW YORK MULTI SEG REP' WHERE COST_CENTER_CODE = '75Q456' AND NVL(COST_CENTER_NAME, 'X') <> 'METRO NEW YORK MULTI SEG REP';

SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q428';
UPDATE COST_CENTER SET COST_CENTER_NAME = 'METRO NEW JERSEY MULTI SEG REP' WHERE COST_CENTER_CODE = '75Q428' AND NVL(COST_CENTER_NAME, 'X') <> 'METRO NEW JERSEY MULTI SEG REP';

SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q430';
UPDATE COST_CENTER SET COST_CENTER_NAME = 'METRO NEW JERSEY MULTI SEG REP' WHERE COST_CENTER_CODE = '75Q430' AND NVL(COST_CENTER_NAME, 'X') <> 'METRO NEW JERSEY MULTI SEG REP';

SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q434';
UPDATE COST_CENTER SET COST_CENTER_NAME = 'METRO NEW JERSEY MULTI SEG REP' WHERE COST_CENTER_CODE = '75Q434' AND NVL(COST_CENTER_NAME, 'X') <> 'METRO NEW JERSEY MULTI SEG REP';

SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q450';
UPDATE COST_CENTER SET COST_CENTER_NAME = 'METRO NEW JERSEY MULTI SEG REP' WHERE COST_CENTER_CODE = '75Q450' AND NVL(COST_CENTER_NAME, 'X') <> 'METRO NEW JERSEY MULTI SEG REP';

SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q454';
UPDATE COST_CENTER SET COST_CENTER_NAME = 'LONG ISLAND MULTI SEG REP' WHERE COST_CENTER_CODE = '75Q454' AND NVL(COST_CENTER_NAME, 'X') <> 'LONG ISLAND MULTI SEG REP';

SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q462';
UPDATE COST_CENTER SET COST_CENTER_NAME = 'LONG ISLAND MULTI SEG REP' WHERE COST_CENTER_CODE = '75Q462' AND NVL(COST_CENTER_NAME, 'X') <> 'LONG ISLAND MULTI SEG REP';

SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q466';
UPDATE COST_CENTER SET COST_CENTER_NAME = 'LONG ISLAND MULTI SEG REP' WHERE COST_CENTER_CODE = '75Q466' AND NVL(COST_CENTER_NAME, 'X') <> 'LONG ISLAND MULTI SEG REP';

SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '755986';
UPDATE COST_CENTER SET COST_CENTER_NAME = 'LONG ISLAND MULTI SEG REP' WHERE COST_CENTER_CODE = '755986' AND NVL(COST_CENTER_NAME, 'X') <> 'LONG ISLAND MULTI SEG REP';

SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q408';
UPDATE COST_CENTER SET COST_CENTER_NAME = 'DELMAR RES REPAINT REP' WHERE COST_CENTER_CODE = '75Q408' AND NVL(COST_CENTER_NAME, 'X') <> 'DELMAR RES REPAINT REP';

SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '754512';
UPDATE COST_CENTER SET COST_CENTER_NAME = 'DELMAR MULTI SEG REP' WHERE COST_CENTER_CODE = '754512' AND NVL(COST_CENTER_NAME, 'X') <> 'DELMAR MULTI SEG REP';

SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '755549';
UPDATE COST_CENTER SET COST_CENTER_NAME = 'DELMAR PROP MAINT REP' WHERE COST_CENTER_CODE = '755549' AND NVL(COST_CENTER_NAME, 'X') <> 'DELMAR PROP MAINT REP';

SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '755601';
UPDATE COST_CENTER SET COST_CENTER_NAME = 'DELMAR COMM REP' WHERE COST_CENTER_CODE = '755601' AND NVL(COST_CENTER_NAME, 'X') <> 'DELMAR COMM REP';

SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q442';
UPDATE COST_CENTER SET COST_CENTER_NAME = 'PHILADELPHIA COMM REP' WHERE COST_CENTER_CODE = '75Q442' AND NVL(COST_CENTER_NAME, 'X') <> 'PHILADELPHIA COMM REP';

SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '756922';
UPDATE COST_CENTER SET COST_CENTER_NAME = 'PHILADELPHIA COMM REP' WHERE COST_CENTER_CODE = '756922' AND NVL(COST_CENTER_NAME, 'X') <> 'PHILADELPHIA COMM REP';

SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '754511';
UPDATE COST_CENTER SET COST_CENTER_NAME = 'PITTSBURGH RES REPAINT REP' WHERE COST_CENTER_CODE = '754511' AND NVL(COST_CENTER_NAME, 'X') <> 'PITTSBURGH RES REPAINT REP';

SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '755516';
UPDATE COST_CENTER SET COST_CENTER_NAME = 'PITTSBURGH PROP MAINT REP' WHERE COST_CENTER_CODE = '755516' AND NVL(COST_CENTER_NAME, 'X') <> 'PITTSBURGH PROP MAINT REP';

SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q585';
UPDATE COST_CENTER SET COST_CENTER_NAME = 'CHARLOTTE METRO MULTI SEG REP' WHERE COST_CENTER_CODE = '75Q585' AND NVL(COST_CENTER_NAME, 'X') <> 'CHARLOTTE METRO MULTI SEG REP';

SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '754446';
UPDATE COST_CENTER SET COST_CENTER_NAME = 'CHARLESTON METRO MULTI SEG REP' WHERE COST_CENTER_CODE = '754446' AND NVL(COST_CENTER_NAME, 'X') <> 'CHARLESTON METRO MULTI SEG REP';

SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '754466';
UPDATE COST_CENTER SET COST_CENTER_NAME = 'CHARLESTON METRO COMM REP' WHERE COST_CENTER_CODE = '754466' AND NVL(COST_CENTER_NAME, 'X') <> 'CHARLESTON METRO COMM REP';

SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '754578';
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WILMINGTON COMM REP' WHERE COST_CENTER_CODE = '754578' AND NVL(COST_CENTER_NAME, 'X') <> 'WILMINGTON COMM REP';

SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '754112';
UPDATE COST_CENTER SET COST_CENTER_NAME = 'ATLANTA RES REPAINT REP' WHERE COST_CENTER_CODE = '754112' AND NVL(COST_CENTER_NAME, 'X') <> 'ATLANTA RES REPAINT REP';

SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '754916';
UPDATE COST_CENTER SET COST_CENTER_NAME = 'ATLANTA COMM REP' WHERE COST_CENTER_CODE = '754916' AND NVL(COST_CENTER_NAME, 'X') <> 'ATLANTA COMM REP';

SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '755761';
UPDATE COST_CENTER SET COST_CENTER_NAME = 'ATLANTA NEW RES REP' WHERE COST_CENTER_CODE = '755761' AND NVL(COST_CENTER_NAME, 'X') <> 'ATLANTA NEW RES REP';

SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '756059';
UPDATE COST_CENTER SET COST_CENTER_NAME = 'ATLANTA MULTI SEG REP' WHERE COST_CENTER_CODE = '756059' AND NVL(COST_CENTER_NAME, 'X') <> 'ATLANTA MULTI SEG REP';

SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '756490';
UPDATE COST_CENTER SET COST_CENTER_NAME = 'ATLANTA MULTI SEG REP' WHERE COST_CENTER_CODE = '756490' AND NVL(COST_CENTER_NAME, 'X') <> 'ATLANTA MULTI SEG REP';

-- SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '754444';
-- UPDATE COST_CENTER SET COST_CENTER_NAME = 'SOUTHWEST FLORIDA METRO MULTI SEG REP' WHERE COST_CENTER_CODE = '754444' AND NVL(COST_CENTER_NAME, 'X') <> 'SOUTHWEST FLORIDA METRO MULTI SEG REP';

SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '754451';
UPDATE COST_CENTER SET COST_CENTER_NAME = 'SOUTH FLORIDA METRO MULTI SEG REP' WHERE COST_CENTER_CODE = '754451' AND NVL(COST_CENTER_NAME, 'X') <> 'SOUTH FLORIDA METRO MULTI SEG REP';

SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q220';
UPDATE COST_CENTER SET COST_CENTER_NAME = 'TAMPA MULTI SEG REP' WHERE COST_CENTER_CODE = '75Q220' AND NVL(COST_CENTER_NAME, 'X') <> 'TAMPA MULTI SEG REP';

SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q562';
UPDATE COST_CENTER SET COST_CENTER_NAME = 'FLORIDA PANHANDLE MULTI SEG REP' WHERE COST_CENTER_CODE = '75Q562' AND NVL(COST_CENTER_NAME, 'X') <> 'FLORIDA PANHANDLE MULTI SEG REP';

SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q225';
UPDATE COST_CENTER SET COST_CENTER_NAME = 'ORLANDO NEW RES REP' WHERE COST_CENTER_CODE = '75Q225' AND NVL(COST_CENTER_NAME, 'X') <> 'ORLANDO NEW RES REP';

SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '754041';
UPDATE COST_CENTER SET COST_CENTER_NAME = 'ORLANDO MULTI SEG REP' WHERE COST_CENTER_CODE = '754041' AND NVL(COST_CENTER_NAME, 'X') <> 'ORLANDO MULTI SEG REP';

SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '758356';
UPDATE COST_CENTER SET COST_CENTER_NAME = 'ORLANDO COMM REP' WHERE COST_CENTER_CODE = '758356' AND NVL(COST_CENTER_NAME, 'X') <> 'ORLANDO COMM REP';

SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '758440';
UPDATE COST_CENTER SET COST_CENTER_NAME = 'ORLANDO RES REPAINT REP' WHERE COST_CENTER_CODE = '758440' AND NVL(COST_CENTER_NAME, 'X') <> 'ORLANDO RES REPAINT REP';

SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q191';
UPDATE COST_CENTER SET COST_CENTER_NAME = 'EAST COAST FLORIDA NEW RES REP' WHERE COST_CENTER_CODE = '75Q191' AND NVL(COST_CENTER_NAME, 'X') <> 'EAST COAST FLORIDA NEW RES REP';

SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q213';
UPDATE COST_CENTER SET COST_CENTER_NAME = 'EAST COAST FLORIDA PROP MAINT REP' WHERE COST_CENTER_CODE = '75Q213' AND NVL(COST_CENTER_NAME, 'X') <> 'EAST COAST FLORIDA PROP MAINT REP';

SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q548';
UPDATE COST_CENTER SET COST_CENTER_NAME = 'EAST COAST FLORIDA COMM REP' WHERE COST_CENTER_CODE = '75Q548' AND NVL(COST_CENTER_NAME, 'X') <> 'EAST COAST FLORIDA COMM REP';

SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '754235';
UPDATE COST_CENTER SET COST_CENTER_NAME = 'EAST COAST FLORIDA MULTI SEG REP' WHERE COST_CENTER_CODE = '754235' AND NVL(COST_CENTER_NAME, 'X') <> 'EAST COAST FLORIDA MULTI SEG REP';

SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '754270';
UPDATE COST_CENTER SET COST_CENTER_NAME = 'EAST COAST FLORIDA NEW RES REP' WHERE COST_CENTER_CODE = '754270' AND NVL(COST_CENTER_NAME, 'X') <> 'EAST COAST FLORIDA NEW RES REP';

SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '756028';
UPDATE COST_CENTER SET COST_CENTER_NAME = 'PUERTO RICO PROP MAINT REP' WHERE COST_CENTER_CODE = '756028' AND NVL(COST_CENTER_NAME, 'X') <> 'PUERTO RICO PROP MAINT REP';

SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '756125';
UPDATE COST_CENTER SET COST_CENTER_NAME = 'MEMPHIS PROP MAINT REP' WHERE COST_CENTER_CODE = '756125' AND NVL(COST_CENTER_NAME, 'X') <> 'MEMPHIS PROP MAINT REP';

SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q546';
UPDATE COST_CENTER SET COST_CENTER_NAME = 'LOUISIANA MULTI SEG REP' WHERE COST_CENTER_CODE = '75Q546' AND NVL(COST_CENTER_NAME, 'X') <> 'LOUISIANA MULTI SEG REP';

SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q573';
UPDATE COST_CENTER SET COST_CENTER_NAME = 'LOUISIANA MULTI SEG REP' WHERE COST_CENTER_CODE = '75Q573' AND NVL(COST_CENTER_NAME, 'X') <> 'LOUISIANA MULTI SEG REP';

SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '756520';
UPDATE COST_CENTER SET COST_CENTER_NAME = 'LOUISIANA COMM REP' WHERE COST_CENTER_CODE = '756520' AND NVL(COST_CENTER_NAME, 'X') <> 'LOUISIANA COMM REP';

SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q531';
UPDATE COST_CENTER SET COST_CENTER_NAME = 'NEW ORLEANS MULTI SEG REP' WHERE COST_CENTER_CODE = '75Q531' AND NVL(COST_CENTER_NAME, 'X') <> 'NEW ORLEANS MULTI SEG REP';

SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q147';
UPDATE COST_CENTER SET COST_CENTER_NAME = 'SAN ANTONIO PROP MAINT REP' WHERE COST_CENTER_CODE = '75Q147' AND NVL(COST_CENTER_NAME, 'X') <> 'SAN ANTONIO PROP MAINT REP';

SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '756638';
UPDATE COST_CENTER SET COST_CENTER_NAME = 'SAN ANTONIO MULTI SEG REP' WHERE COST_CENTER_CODE = '756638' AND NVL(COST_CENTER_NAME, 'X') <> 'SAN ANTONIO MULTI SEG REP';

SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q636';
UPDATE COST_CENTER SET COST_CENTER_NAME = 'AUSTIN RES REPAINT REP' WHERE COST_CENTER_CODE = '75Q636' AND NVL(COST_CENTER_NAME, 'X') <> 'AUSTIN RES REPAINT REP';

SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q678';
UPDATE COST_CENTER SET COST_CENTER_NAME = 'AUSTIN MULTI SEG REP' WHERE COST_CENTER_CODE = '75Q678' AND NVL(COST_CENTER_NAME, 'X') <> 'AUSTIN MULTI SEG REP';

SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q157';
UPDATE COST_CENTER SET COST_CENTER_NAME = 'HOUSTON RES REPAINT REP' WHERE COST_CENTER_CODE = '75Q157' AND NVL(COST_CENTER_NAME, 'X') <> 'HOUSTON RES REPAINT REP';

SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q650';
UPDATE COST_CENTER SET COST_CENTER_NAME = 'MID-TEXAS MULTI SEG REP' WHERE COST_CENTER_CODE = '75Q650' AND NVL(COST_CENTER_NAME, 'X') <> 'MID-TEXAS MULTI SEG REP';

SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '754768';
UPDATE COST_CENTER SET COST_CENTER_NAME = 'CALIFORNIA NORTH MULTI SEG REP' WHERE COST_CENTER_CODE = '754768' AND NVL(COST_CENTER_NAME, 'X') <> 'CALIFORNIA NORTH MULTI SEG REP';

SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '756842';
UPDATE COST_CENTER SET COST_CENTER_NAME = 'CALIFORNIA NORTH RES REPAINT REP' WHERE COST_CENTER_CODE = '756842' AND NVL(COST_CENTER_NAME, 'X') <> 'CALIFORNIA NORTH RES REPAINT REP';

SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '757839';
UPDATE COST_CENTER SET COST_CENTER_NAME = 'CALIFORNIA NORTH COMM REP' WHERE COST_CENTER_CODE = '757839' AND NVL(COST_CENTER_NAME, 'X') <> 'CALIFORNIA NORTH COMM REP';

SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q068';
UPDATE COST_CENTER SET COST_CENTER_NAME = 'CALIFORNIA CENTRAL RES REPAINT REP' WHERE COST_CENTER_CODE = '75Q068' AND NVL(COST_CENTER_NAME, 'X') <> 'CALIFORNIA CENTRAL RES REPAINT REP';

SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '756326';
UPDATE COST_CENTER SET COST_CENTER_NAME = 'CALIFORNIA BAY MULTI SEG REP' WHERE COST_CENTER_CODE = '756326' AND NVL(COST_CENTER_NAME, 'X') <> 'CALIFORNIA BAY MULTI SEG REP';

SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '756464';
UPDATE COST_CENTER SET COST_CENTER_NAME = 'CALIFORNIA BAY MULTI SEG REP' WHERE COST_CENTER_CODE = '756464' AND NVL(COST_CENTER_NAME, 'X') <> 'CALIFORNIA BAY MULTI SEG REP';

SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q045';
UPDATE COST_CENTER SET COST_CENTER_NAME = 'LOS ANGELES MULTI SEG REP' WHERE COST_CENTER_CODE = '75Q045' AND NVL(COST_CENTER_NAME, 'X') <> 'LOS ANGELES MULTI SEG REP';

SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q079';
UPDATE COST_CENTER SET COST_CENTER_NAME = 'LOS ANGELES RES REPAINT REP' WHERE COST_CENTER_CODE = '75Q079' AND NVL(COST_CENTER_NAME, 'X') <> 'LOS ANGELES RES REPAINT REP';

SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q096';
UPDATE COST_CENTER SET COST_CENTER_NAME = 'LOS ANGELES PROP MAINT REP' WHERE COST_CENTER_CODE = '75Q096' AND NVL(COST_CENTER_NAME, 'X') <> 'LOS ANGELES PROP MAINT REP';

SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q098';
UPDATE COST_CENTER SET COST_CENTER_NAME = 'LOS ANGELES RES REPAINT REP' WHERE COST_CENTER_CODE = '75Q098' AND NVL(COST_CENTER_NAME, 'X') <> 'LOS ANGELES RES REPAINT REP';

SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q101';
UPDATE COST_CENTER SET COST_CENTER_NAME = 'LOS ANGELES MULTI SEG REP' WHERE COST_CENTER_CODE = '75Q101' AND NVL(COST_CENTER_NAME, 'X') <> 'LOS ANGELES MULTI SEG REP';

SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q612';
UPDATE COST_CENTER SET COST_CENTER_NAME = 'LOS ANGELES COMM REP' WHERE COST_CENTER_CODE = '75Q612' AND NVL(COST_CENTER_NAME, 'X') <> 'LOS ANGELES COMM REP';

SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q635';
UPDATE COST_CENTER SET COST_CENTER_NAME = 'LOS ANGELES RES REPAINT REP' WHERE COST_CENTER_CODE = '75Q635' AND NVL(COST_CENTER_NAME, 'X') <> 'LOS ANGELES RES REPAINT REP';

SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '754951';
UPDATE COST_CENTER SET COST_CENTER_NAME = 'LOS ANGELES MULTI SEG REP' WHERE COST_CENTER_CODE = '754951' AND NVL(COST_CENTER_NAME, 'X') <> 'LOS ANGELES MULTI SEG REP';

SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '754965';
UPDATE COST_CENTER SET COST_CENTER_NAME = 'LOS ANGELES COMM REP' WHERE COST_CENTER_CODE = '754965' AND NVL(COST_CENTER_NAME, 'X') <> 'LOS ANGELES COMM REP';

SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '756734';
UPDATE COST_CENTER SET COST_CENTER_NAME = 'HAWAII MULTI SEG REP' WHERE COST_CENTER_CODE = '756734' AND NVL(COST_CENTER_NAME, 'X') <> 'HAWAII MULTI SEG REP';

SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '757932';
UPDATE COST_CENTER SET COST_CENTER_NAME = 'SAN FERNANDO RES REPAINT REP' WHERE COST_CENTER_CODE = '757932' AND NVL(COST_CENTER_NAME, 'X') <> 'SAN FERNANDO RES REPAINT REP';

SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q118';
UPDATE COST_CENTER SET COST_CENTER_NAME = 'NORTHERN COLORADO RES REPAINT REP' WHERE COST_CENTER_CODE = '75Q118' AND NVL(COST_CENTER_NAME, 'X') <> 'NORTHERN COLORADO RES REPAINT REP';

SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q162';
UPDATE COST_CENTER SET COST_CENTER_NAME = 'SALT LAKE CITY RES REPAINT REP' WHERE COST_CENTER_CODE = '75Q162' AND NVL(COST_CENTER_NAME, 'X') <> 'SALT LAKE CITY RES REPAINT REP';

SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q163';
UPDATE COST_CENTER SET COST_CENTER_NAME = 'SALT LAKE CITY NEW RES REP' WHERE COST_CENTER_CODE = '75Q163' AND NVL(COST_CENTER_NAME, 'X') <> 'SALT LAKE CITY NEW RES REP';

SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q173';
UPDATE COST_CENTER SET COST_CENTER_NAME = 'SALT LAKE CITY RES REPAINT REP' WHERE COST_CENTER_CODE = '75Q173' AND NVL(COST_CENTER_NAME, 'X') <> 'SALT LAKE CITY RES REPAINT REP';

SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q178';
UPDATE COST_CENTER SET COST_CENTER_NAME = 'SALT LAKE CITY RES REPAINT REP' WHERE COST_CENTER_CODE = '75Q178' AND NVL(COST_CENTER_NAME, 'X') <> 'SALT LAKE CITY RES REPAINT REP';

SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '754913';
UPDATE COST_CENTER SET COST_CENTER_NAME = 'SALT LAKE CITY RES REPAINT REP' WHERE COST_CENTER_CODE = '754913' AND NVL(COST_CENTER_NAME, 'X') <> 'SALT LAKE CITY RES REPAINT REP';

SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '755834';
UPDATE COST_CENTER SET COST_CENTER_NAME = 'ARIZONA RES REPAINT REP' WHERE COST_CENTER_CODE = '755834' AND NVL(COST_CENTER_NAME, 'X') <> 'ARIZONA RES REPAINT REP';

SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '754117';
UPDATE COST_CENTER SET COST_CENTER_NAME = 'SPRINGFIELD NEW RES REP' WHERE COST_CENTER_CODE = '754117' AND NVL(COST_CENTER_NAME, 'X') <> 'SPRINGFIELD NEW RES REP';

SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '766823';
UPDATE COST_CENTER SET COST_CENTER_NAME = 'SOUTHWEST ONTARIO MULTI SEG REP' WHERE COST_CENTER_CODE = '766823' AND NVL(COST_CENTER_NAME, 'X') <> 'SOUTHWEST ONTARIO MULTI SEG REP';

SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '76Q856';
UPDATE COST_CENTER SET COST_CENTER_NAME = 'QUEBEC RES REPAINT REP' WHERE COST_CENTER_CODE = '76Q856' AND NVL(COST_CENTER_NAME, 'X') <> 'QUEBEC RES REPAINT REP';

SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '76Q863';
UPDATE COST_CENTER SET COST_CENTER_NAME = 'QUEBEC MULTI SEG REP' WHERE COST_CENTER_CODE = '76Q863' AND NVL(COST_CENTER_NAME, 'X') <> 'QUEBEC MULTI SEG REP';

SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '76Q865';
UPDATE COST_CENTER SET COST_CENTER_NAME = 'QUEBEC MULTI SEG REP' WHERE COST_CENTER_CODE = '76Q865' AND NVL(COST_CENTER_NAME, 'X') <> 'QUEBEC MULTI SEG REP';

SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '76Q867';
UPDATE COST_CENTER SET COST_CENTER_NAME = 'QUEBEC COMM REP' WHERE COST_CENTER_CODE = '76Q867' AND NVL(COST_CENTER_NAME, 'X') <> 'QUEBEC COMM REP';

SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '76Q874';
UPDATE COST_CENTER SET COST_CENTER_NAME = 'QUEBEC MULTI SEG REP' WHERE COST_CENTER_CODE = '76Q874' AND NVL(COST_CENTER_NAME, 'X') <> 'QUEBEC MULTI SEG REP';

SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '76Q873';
UPDATE COST_CENTER SET COST_CENTER_NAME = 'EASTERN CANADA MULTI SEG REP' WHERE COST_CENTER_CODE = '76Q873' AND NVL(COST_CENTER_NAME, 'X') <> 'EASTERN CANADA MULTI SEG REP';

SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '76Q875';
UPDATE COST_CENTER SET COST_CENTER_NAME = 'EASTERN CANADA MULTI SEG REP' WHERE COST_CENTER_CODE = '76Q875' AND NVL(COST_CENTER_NAME, 'X') <> 'EASTERN CANADA MULTI SEG REP';

SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '76Q233';
UPDATE COST_CENTER SET COST_CENTER_NAME = 'BRITISH COLUMBIA COMM REP' WHERE COST_CENTER_CODE = '76Q233' AND NVL(COST_CENTER_NAME, 'X') <> 'BRITISH COLUMBIA COMM REP';

SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '76Q237';
UPDATE COST_CENTER SET COST_CENTER_NAME = 'BRITISH COLUMBIA MULTI SEG REP' WHERE COST_CENTER_CODE = '76Q237' AND NVL(COST_CENTER_NAME, 'X') <> 'BRITISH COLUMBIA MULTI SEG REP';

SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '76Q246';
UPDATE COST_CENTER SET COST_CENTER_NAME = 'BRITISH COLUMBIA RES REPAINT REP' WHERE COST_CENTER_CODE = '76Q246' AND NVL(COST_CENTER_NAME, 'X') <> 'BRITISH COLUMBIA RES REPAINT REP';

SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '76Q255';
UPDATE COST_CENTER SET COST_CENTER_NAME = 'NORTHERN ALBERTA MULTI SEG REP' WHERE COST_CENTER_CODE = '76Q255' AND NVL(COST_CENTER_NAME, 'X') <> 'NORTHERN ALBERTA MULTI SEG REP';

SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '76Q236';
UPDATE COST_CENTER SET COST_CENTER_NAME = 'SASKMAN NEW RES REP' WHERE COST_CENTER_CODE = '76Q236' AND NVL(COST_CENTER_NAME, 'X') <> 'SASKMAN NEW RES REP';

COMMIT;

SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '754789';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'CM' WHERE COST_CENTER_CODE = '754789' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'X') <> 'CM';

SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '754794';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '754794' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'X') <> 'MS';

SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '756078';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '756078' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'X') <> 'RR';

SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '756549';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '756549' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'X') <> 'RR';

SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '756705';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '756705' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'X') <> 'RR';

SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '756709';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'NR' WHERE COST_CENTER_CODE = '756709' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'X') <> 'NR';

SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '756864';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '756864' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'X') <> 'RR';

SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '756822';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '756822' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'X') <> 'RR';

SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '756866';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '756866' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'X') <> 'RR';

SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '758487';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '758487' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'X') <> 'MS';

SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '75Q016';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '75Q016' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'X') <> 'RR';

SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '756586';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'NR' WHERE COST_CENTER_CODE = '756586' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'X') <> 'NR';

SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '756915';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'CM' WHERE COST_CENTER_CODE = '756915' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'X') <> 'CM';

SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '754161';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'CM' WHERE COST_CENTER_CODE = '754161' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'X') <> 'CM';

SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '754168';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'PM' WHERE COST_CENTER_CODE = '754168' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'X') <> 'PM';

SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '75Q391';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'PM' WHERE COST_CENTER_CODE = '75Q391' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'X') <> 'PM';

SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '754485';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'CM' WHERE COST_CENTER_CODE = '754485' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'X') <> 'CM';

SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '754607';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'CM' WHERE COST_CENTER_CODE = '754607' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'X') <> 'CM';

SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '754017';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'CM' WHERE COST_CENTER_CODE = '754017' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'X') <> 'CM';

SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '754157';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'NR' WHERE COST_CENTER_CODE = '754157' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'X') <> 'NR';

SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '754929';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '754929' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'X') <> 'RR';

SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '756725';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'NR' WHERE COST_CENTER_CODE = '756725' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'X') <> 'NR';

SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '754812';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '754812' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'X') <> 'MS';

SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '756271';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'NR' WHERE COST_CENTER_CODE = '756271' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'X') <> 'NR';

SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '754696';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'CM' WHERE COST_CENTER_CODE = '754696' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'X') <> 'CM';

SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '754154';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'PM' WHERE COST_CENTER_CODE = '754154' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'X') <> 'PM';

SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '754267';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '754267' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'X') <> 'MS';

SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '75Q375';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '75Q375' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'X') <> 'MS';

SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '754268';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '754268' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'X') <> 'RR';

SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '754810';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '754810' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'X') <> 'RR';

SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '756660';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '756660' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'X') <> 'RR';

SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '75Q406';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '75Q406' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'X') <> 'RR';

SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '754036';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '754036' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'X') <> 'MS';

SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '755555';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'CM' WHERE COST_CENTER_CODE = '755555' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'X') <> 'CM';

SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '755618';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '755618' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'X') <> 'MS';

SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '754621';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '754621' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'X') <> 'MS';

SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '75Q418';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '75Q418' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'X') <> 'MS';

SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '75Q456';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '75Q456' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'X') <> 'MS';

SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '75Q428';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '75Q428' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'X') <> 'MS';

SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '75Q430';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '75Q430' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'X') <> 'MS';

SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '75Q434';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '75Q434' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'X') <> 'MS';

SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '75Q450';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '75Q450' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'X') <> 'MS';

SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '75Q454';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '75Q454' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'X') <> 'MS';

SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '75Q462';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '75Q462' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'X') <> 'MS';

SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '75Q466';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '75Q466' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'X') <> 'MS';

SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '755986';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '755986' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'X') <> 'MS';

SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '75Q408';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '75Q408' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'X') <> 'RR';

SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '754512';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '754512' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'X') <> 'MS';

SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '755549';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'PM' WHERE COST_CENTER_CODE = '755549' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'X') <> 'PM';

SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '755601';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'CM' WHERE COST_CENTER_CODE = '755601' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'X') <> 'CM';

SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '75Q442';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'CM' WHERE COST_CENTER_CODE = '75Q442' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'X') <> 'CM';

SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '756922';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'CM' WHERE COST_CENTER_CODE = '756922' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'X') <> 'CM';

SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '754511';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '754511' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'X') <> 'RR';

SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '755516';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'PM' WHERE COST_CENTER_CODE = '755516' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'X') <> 'PM';

SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '75Q585';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '75Q585' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'X') <> 'MS';

SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '754446';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '754446' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'X') <> 'MS';

SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '754466';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'CM' WHERE COST_CENTER_CODE = '754466' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'X') <> 'CM';

SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '754578';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'CM' WHERE COST_CENTER_CODE = '754578' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'X') <> 'CM';

SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '754112';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '754112' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'X') <> 'RR';

SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '754916';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'CM' WHERE COST_CENTER_CODE = '754916' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'X') <> 'CM';

SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '755761';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'NR' WHERE COST_CENTER_CODE = '755761' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'X') <> 'NR';

SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '756059';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '756059' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'X') <> 'MS';

SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '756490';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '756490' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'X') <> 'MS';

SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '754444';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '754444' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'X') <> 'MS';

SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '754451';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '754451' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'X') <> 'MS';

SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '75Q220';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '75Q220' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'X') <> 'MS';

SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '75Q562';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '75Q562' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'X') <> 'MS';

SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '75Q225';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'NR' WHERE COST_CENTER_CODE = '75Q225' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'X') <> 'NR';

SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '754041';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '754041' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'X') <> 'MS';

SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '758356';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'CM' WHERE COST_CENTER_CODE = '758356' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'X') <> 'CM';

SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '758440';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '758440' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'X') <> 'RR';

SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '75Q191';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'NR' WHERE COST_CENTER_CODE = '75Q191' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'X') <> 'NR';

SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '75Q213';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'PM' WHERE COST_CENTER_CODE = '75Q213' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'X') <> 'PM';

SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '75Q548';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'CM' WHERE COST_CENTER_CODE = '75Q548' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'X') <> 'CM';

SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '754235';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '754235' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'X') <> 'MS';

SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '754270';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'NR' WHERE COST_CENTER_CODE = '754270' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'X') <> 'NR';

SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '756028';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'PM' WHERE COST_CENTER_CODE = '756028' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'X') <> 'PM';

SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '756125';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'PM' WHERE COST_CENTER_CODE = '756125' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'X') <> 'PM';

SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '75Q546';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '75Q546' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'X') <> 'MS';

SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '75Q573';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '75Q573' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'X') <> 'MS';

SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '756520';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'CM' WHERE COST_CENTER_CODE = '756520' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'X') <> 'CM';

SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '75Q531';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '75Q531' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'X') <> 'MS';

SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '75Q147';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'PM' WHERE COST_CENTER_CODE = '75Q147' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'X') <> 'PM';

SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '756638';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '756638' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'X') <> 'MS';

SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '75Q636';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '75Q636' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'X') <> 'RR';

SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '75Q678';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '75Q678' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'X') <> 'MS';

SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '75Q157';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '75Q157' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'X') <> 'RR';

SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '75Q650';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '75Q650' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'X') <> 'MS';

SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '754768';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '754768' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'X') <> 'MS';

SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '756842';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '756842' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'X') <> 'RR';

SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '757839';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'CM' WHERE COST_CENTER_CODE = '757839' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'X') <> 'CM';

SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '75Q068';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '75Q068' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'X') <> 'RR';

SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '756326';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '756326' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'X') <> 'MS';

SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '756464';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '756464' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'X') <> 'MS';

SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '75Q045';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '75Q045' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'X') <> 'MS';

SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '75Q079';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '75Q079' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'X') <> 'RR';

SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '75Q096';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'PM' WHERE COST_CENTER_CODE = '75Q096' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'X') <> 'PM';

SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '75Q098';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '75Q098' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'X') <> 'RR';

SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '75Q101';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '75Q101' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'X') <> 'MS';

SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '75Q612';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'CM' WHERE COST_CENTER_CODE = '75Q612' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'X') <> 'CM';

SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '75Q635';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '75Q635' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'X') <> 'RR';

SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '754951';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '754951' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'X') <> 'MS';

SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '754965';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'CM' WHERE COST_CENTER_CODE = '754965' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'X') <> 'CM';

SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '756734';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '756734' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'X') <> 'MS';

SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '757932';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '757932' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'X') <> 'RR';

SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '75Q118';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '75Q118' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'X') <> 'RR';

SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '75Q162';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '75Q162' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'X') <> 'RR';

SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '75Q163';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'NR' WHERE COST_CENTER_CODE = '75Q163' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'X') <> 'NR';

SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '75Q173';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '75Q173' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'X') <> 'RR';

SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '75Q178';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '75Q178' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'X') <> 'RR';

SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '754913';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '754913' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'X') <> 'RR';

SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '755834';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '755834' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'X') <> 'RR';

SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '754117';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'NR' WHERE COST_CENTER_CODE = '754117' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'X') <> 'NR';

SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '766823';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '766823' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'X') <> 'MS';

SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '76Q856';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '76Q856' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'X') <> 'RR';

SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '76Q863';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '76Q863' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'X') <> 'MS';

SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '76Q865';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '76Q865' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'X') <> 'MS';

SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '76Q867';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'CM' WHERE COST_CENTER_CODE = '76Q867' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'X') <> 'CM';

SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '76Q874';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '76Q874' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'X') <> 'MS';

SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '76Q873';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '76Q873' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'X') <> 'MS';

SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '76Q875';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '76Q875' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'X') <> 'MS';

SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '76Q233';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'CM' WHERE COST_CENTER_CODE = '76Q233' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'X') <> 'CM';

SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '76Q237';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '76Q237' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'X') <> 'MS';

SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '76Q246';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '76Q246' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'X') <> 'RR';

SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '76Q255';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '76Q255' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'X') <> 'MS';

SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '76Q236';
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'NR' WHERE COST_CENTER_CODE = '76Q236' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'X') <> 'NR';

COMMIT;


BEGIN
   CCN_BATCH_PKG.UNLOCK_DATABASE_SP();
END;
/