/*
created : nxk927 03/31/2017
          Protective and marine territory home store update
*/

BEGIN
   CCN_BATCH_PKG.LOCK_DATABASE_SP();
END;
/
   SELECT * FROM TERRITORY WHERE  COST_CENTER_CODE = '71Q251';
   UPDATE TERRITORY SET HOME_STORE = (SELECT COST_CENTER_CODE FROM COST_CENTER WHERE SUBSTR(COST_CENTER_CODE,3) = '8866' AND ROWNUM =1)
    WHERE COST_CENTER_CODE = '71Q251';
   SELECT * FROM TERRITORY WHERE  COST_CENTER_CODE = '71Q251';

   SELECT * FROM TERRITORY WHERE  COST_CENTER_CODE = '714715';
   UPDATE TERRITORY SET HOME_STORE = (SELECT COST_CENTER_CODE FROM COST_CENTER WHERE SUBSTR(COST_CENTER_CODE,3) = '8738' AND ROWNUM =1)
    WHERE COST_CENTER_CODE = '714715';
   SELECT * FROM TERRITORY WHERE  COST_CENTER_CODE = '714715';

   SELECT * FROM TERRITORY WHERE  COST_CENTER_CODE = '714937';
   UPDATE TERRITORY SET HOME_STORE = (SELECT COST_CENTER_CODE FROM COST_CENTER WHERE SUBSTR(COST_CENTER_CODE,3) = '1680' AND ROWNUM =1)
    WHERE COST_CENTER_CODE = '714937';
   SELECT * FROM TERRITORY WHERE  COST_CENTER_CODE = '714937';

   SELECT * FROM TERRITORY WHERE  COST_CENTER_CODE = '716114';
   UPDATE TERRITORY SET HOME_STORE = (SELECT COST_CENTER_CODE FROM COST_CENTER WHERE SUBSTR(COST_CENTER_CODE,3) = '1680' AND ROWNUM =1)
    WHERE COST_CENTER_CODE = '716114';
   SELECT * FROM TERRITORY WHERE  COST_CENTER_CODE = '716114';

   SELECT * FROM TERRITORY WHERE  COST_CENTER_CODE = '716609';
   UPDATE TERRITORY SET HOME_STORE = (SELECT COST_CENTER_CODE FROM COST_CENTER WHERE SUBSTR(COST_CENTER_CODE,3) = '4342' AND ROWNUM =1)
    WHERE COST_CENTER_CODE = '716609';
   SELECT * FROM TERRITORY WHERE  COST_CENTER_CODE = '716609';

   SELECT * FROM TERRITORY WHERE  COST_CENTER_CODE = '714120';
   UPDATE TERRITORY SET HOME_STORE = (SELECT COST_CENTER_CODE FROM COST_CENTER WHERE SUBSTR(COST_CENTER_CODE,3) = '2221' AND ROWNUM =1)
    WHERE COST_CENTER_CODE = '714120';
   SELECT * FROM TERRITORY WHERE  COST_CENTER_CODE = '714120';

   SELECT * FROM TERRITORY WHERE  COST_CENTER_CODE = '71R113';
   UPDATE TERRITORY SET HOME_STORE = (SELECT COST_CENTER_CODE FROM COST_CENTER WHERE SUBSTR(COST_CENTER_CODE,3) = '2907' AND ROWNUM =1)
    WHERE COST_CENTER_CODE = '71R113';
   SELECT * FROM TERRITORY WHERE  COST_CENTER_CODE = '71R113';

   SELECT * FROM TERRITORY WHERE  COST_CENTER_CODE = '716401';
   UPDATE TERRITORY SET HOME_STORE = (SELECT COST_CENTER_CODE FROM COST_CENTER WHERE SUBSTR(COST_CENTER_CODE,3) = '3527' AND ROWNUM =1)
    WHERE COST_CENTER_CODE = '716401';
   SELECT * FROM TERRITORY WHERE  COST_CENTER_CODE = '716401';

   SELECT * FROM TERRITORY WHERE  COST_CENTER_CODE = '715519';
   UPDATE TERRITORY SET HOME_STORE = (SELECT COST_CENTER_CODE FROM COST_CENTER WHERE SUBSTR(COST_CENTER_CODE,3) = '3275' AND ROWNUM =1)
    WHERE COST_CENTER_CODE = '715519';
   SELECT * FROM TERRITORY WHERE  COST_CENTER_CODE = '715519';

   SELECT * FROM TERRITORY WHERE  COST_CENTER_CODE = '715936';
   UPDATE TERRITORY SET HOME_STORE = (SELECT COST_CENTER_CODE FROM COST_CENTER WHERE SUBSTR(COST_CENTER_CODE,3) = '8420' AND ROWNUM =1)
    WHERE COST_CENTER_CODE = '715936';
   SELECT * FROM TERRITORY WHERE  COST_CENTER_CODE = '715936';

   SELECT * FROM TERRITORY WHERE  COST_CENTER_CODE = '71Q806';
   UPDATE TERRITORY SET HOME_STORE = (SELECT COST_CENTER_CODE FROM COST_CENTER WHERE SUBSTR(COST_CENTER_CODE,3) = '3062' AND ROWNUM =1)
    WHERE COST_CENTER_CODE = '71Q806';
   SELECT * FROM TERRITORY WHERE  COST_CENTER_CODE = '71Q806';

   SELECT * FROM TERRITORY WHERE  COST_CENTER_CODE = '714692';
   UPDATE TERRITORY SET HOME_STORE = (SELECT COST_CENTER_CODE FROM COST_CENTER WHERE SUBSTR(COST_CENTER_CODE,3) = '4390' AND ROWNUM =1)
    WHERE COST_CENTER_CODE = '714692';
   SELECT * FROM TERRITORY WHERE  COST_CENTER_CODE = '714692';

   SELECT * FROM TERRITORY WHERE  COST_CENTER_CODE = '715669';
   UPDATE TERRITORY SET HOME_STORE = (SELECT COST_CENTER_CODE FROM COST_CENTER WHERE SUBSTR(COST_CENTER_CODE,3) = '4384' AND ROWNUM =1)
    WHERE COST_CENTER_CODE = '715669';
   SELECT * FROM TERRITORY WHERE  COST_CENTER_CODE = '715669';

   SELECT * FROM TERRITORY WHERE  COST_CENTER_CODE = '718360';
   UPDATE TERRITORY SET HOME_STORE = (SELECT COST_CENTER_CODE FROM COST_CENTER WHERE SUBSTR(COST_CENTER_CODE,3) = '1293' AND ROWNUM =1)
    WHERE COST_CENTER_CODE = '718360';
   SELECT * FROM TERRITORY WHERE  COST_CENTER_CODE = '718360';

   SELECT * FROM TERRITORY WHERE  COST_CENTER_CODE = '715767';
   UPDATE TERRITORY SET HOME_STORE = (SELECT COST_CENTER_CODE FROM COST_CENTER WHERE SUBSTR(COST_CENTER_CODE,3) = '5413' AND ROWNUM =1)
    WHERE COST_CENTER_CODE = '715767';
   SELECT * FROM TERRITORY WHERE  COST_CENTER_CODE = '715767';

   SELECT * FROM TERRITORY WHERE  COST_CENTER_CODE = '717780';
   UPDATE TERRITORY SET HOME_STORE = (SELECT COST_CENTER_CODE FROM COST_CENTER WHERE SUBSTR(COST_CENTER_CODE,3) = '5413' AND ROWNUM =1)
    WHERE COST_CENTER_CODE = '717780';
   SELECT * FROM TERRITORY WHERE  COST_CENTER_CODE = '717780';

   SELECT * FROM TERRITORY WHERE  COST_CENTER_CODE = '715570';
   UPDATE TERRITORY SET HOME_STORE = (SELECT COST_CENTER_CODE FROM COST_CENTER WHERE SUBSTR(COST_CENTER_CODE,3) = '5320' AND ROWNUM =1)
    WHERE COST_CENTER_CODE = '715570';
   SELECT * FROM TERRITORY WHERE  COST_CENTER_CODE = '715570';

   SELECT * FROM TERRITORY WHERE  COST_CENTER_CODE = '714445';
   UPDATE TERRITORY SET HOME_STORE = (SELECT COST_CENTER_CODE FROM COST_CENTER WHERE SUBSTR(COST_CENTER_CODE,3) = '3163' AND ROWNUM =1)
    WHERE COST_CENTER_CODE = '714445';
   SELECT * FROM TERRITORY WHERE  COST_CENTER_CODE = '714445';

   SELECT * FROM TERRITORY WHERE  COST_CENTER_CODE = '715634';
   UPDATE TERRITORY SET HOME_STORE = (SELECT COST_CENTER_CODE FROM COST_CENTER WHERE SUBSTR(COST_CENTER_CODE,3) = '3237' AND ROWNUM =1)
    WHERE COST_CENTER_CODE = '715634';
   SELECT * FROM TERRITORY WHERE  COST_CENTER_CODE = '715634';

   SELECT * FROM TERRITORY WHERE  COST_CENTER_CODE = '714736';
   UPDATE TERRITORY SET HOME_STORE = (SELECT COST_CENTER_CODE FROM COST_CENTER WHERE SUBSTR(COST_CENTER_CODE,3) = '3807' AND ROWNUM =1)
    WHERE COST_CENTER_CODE = '714736';
   SELECT * FROM TERRITORY WHERE  COST_CENTER_CODE = '714736';

   SELECT * FROM TERRITORY WHERE  COST_CENTER_CODE = '716157';
   UPDATE TERRITORY SET HOME_STORE = (SELECT COST_CENTER_CODE FROM COST_CENTER WHERE SUBSTR(COST_CENTER_CODE,3) = '5781' AND ROWNUM =1)
    WHERE COST_CENTER_CODE = '716157';
   SELECT * FROM TERRITORY WHERE  COST_CENTER_CODE = '716157';

   SELECT * FROM TERRITORY WHERE  COST_CENTER_CODE = '716605';
   UPDATE TERRITORY SET HOME_STORE = (SELECT COST_CENTER_CODE FROM COST_CENTER WHERE SUBSTR(COST_CENTER_CODE,3) = '5142' AND ROWNUM =1)
    WHERE COST_CENTER_CODE = '716605';
   SELECT * FROM TERRITORY WHERE  COST_CENTER_CODE = '716605';

   SELECT * FROM TERRITORY WHERE  COST_CENTER_CODE = '714841';
   UPDATE TERRITORY SET HOME_STORE = (SELECT COST_CENTER_CODE FROM COST_CENTER WHERE SUBSTR(COST_CENTER_CODE,3) = '5299' AND ROWNUM =1)
    WHERE COST_CENTER_CODE = '714841';
   SELECT * FROM TERRITORY WHERE  COST_CENTER_CODE = '714841';

   SELECT * FROM TERRITORY WHERE  COST_CENTER_CODE = '716905';
   UPDATE TERRITORY SET HOME_STORE = (SELECT COST_CENTER_CODE FROM COST_CENTER WHERE SUBSTR(COST_CENTER_CODE,3) = '1106' AND ROWNUM =1)
    WHERE COST_CENTER_CODE = '716905';
   SELECT * FROM TERRITORY WHERE  COST_CENTER_CODE = '716905';

   SELECT * FROM TERRITORY WHERE  COST_CENTER_CODE = '714823';
   UPDATE TERRITORY SET HOME_STORE = (SELECT COST_CENTER_CODE FROM COST_CENTER WHERE SUBSTR(COST_CENTER_CODE,3) = '4306' AND ROWNUM =1)
    WHERE COST_CENTER_CODE = '714823';
   SELECT * FROM TERRITORY WHERE  COST_CENTER_CODE = '714823';

   SELECT * FROM TERRITORY WHERE  COST_CENTER_CODE = '715952';
   UPDATE TERRITORY SET HOME_STORE = (SELECT COST_CENTER_CODE FROM COST_CENTER WHERE SUBSTR(COST_CENTER_CODE,3) = '1109' AND ROWNUM =1)
    WHERE COST_CENTER_CODE = '715952';
   SELECT * FROM TERRITORY WHERE  COST_CENTER_CODE = '715952';

   SELECT * FROM TERRITORY WHERE  COST_CENTER_CODE = '716037';
   UPDATE TERRITORY SET HOME_STORE = (SELECT COST_CENTER_CODE FROM COST_CENTER WHERE SUBSTR(COST_CENTER_CODE,3) = '4389' AND ROWNUM =1)
    WHERE COST_CENTER_CODE = '716037';
   SELECT * FROM TERRITORY WHERE  COST_CENTER_CODE = '716037';

   SELECT * FROM TERRITORY WHERE  COST_CENTER_CODE = '714710';
   UPDATE TERRITORY SET HOME_STORE = (SELECT COST_CENTER_CODE FROM COST_CENTER WHERE SUBSTR(COST_CENTER_CODE,3) = '8239' AND ROWNUM =1)
    WHERE COST_CENTER_CODE = '714710';
   SELECT * FROM TERRITORY WHERE  COST_CENTER_CODE = '714710'; 

   SELECT * FROM TERRITORY WHERE  COST_CENTER_CODE = '717963';
   UPDATE TERRITORY SET HOME_STORE = (SELECT COST_CENTER_CODE FROM COST_CENTER WHERE SUBSTR(COST_CENTER_CODE,3) = '8239' AND ROWNUM =1)
    WHERE COST_CENTER_CODE = '717963';
   SELECT * FROM TERRITORY WHERE  COST_CENTER_CODE = '717963';

   SELECT * FROM TERRITORY WHERE  COST_CENTER_CODE = '71R116';
   UPDATE TERRITORY SET HOME_STORE = (SELECT COST_CENTER_CODE FROM COST_CENTER WHERE SUBSTR(COST_CENTER_CODE,3) = '8239' AND ROWNUM =1)
    WHERE COST_CENTER_CODE = '71R116';
   SELECT * FROM TERRITORY WHERE  COST_CENTER_CODE = '71R116';

   SELECT * FROM TERRITORY WHERE  COST_CENTER_CODE = '714857';
   UPDATE TERRITORY SET HOME_STORE = (SELECT COST_CENTER_CODE FROM COST_CENTER WHERE SUBSTR(COST_CENTER_CODE,3) = '1165' AND ROWNUM =1)
    WHERE COST_CENTER_CODE = '714857';
   SELECT * FROM TERRITORY WHERE  COST_CENTER_CODE = '714857';

   SELECT * FROM TERRITORY WHERE  COST_CENTER_CODE = '716678';
   UPDATE TERRITORY SET HOME_STORE = (SELECT COST_CENTER_CODE FROM COST_CENTER WHERE SUBSTR(COST_CENTER_CODE,3) = '1103' AND ROWNUM =1)
    WHERE COST_CENTER_CODE = '716678';
   SELECT * FROM TERRITORY WHERE  COST_CENTER_CODE = '716678';

   SELECT * FROM TERRITORY WHERE  COST_CENTER_CODE = '716792';
   UPDATE TERRITORY SET HOME_STORE = (SELECT COST_CENTER_CODE FROM COST_CENTER WHERE SUBSTR(COST_CENTER_CODE,3) = '4359' AND ROWNUM =1)
    WHERE COST_CENTER_CODE = '716792';
   SELECT * FROM TERRITORY WHERE  COST_CENTER_CODE = '716792';

   SELECT * FROM TERRITORY WHERE  COST_CENTER_CODE = '71Q805';
   UPDATE TERRITORY SET HOME_STORE = (SELECT COST_CENTER_CODE FROM COST_CENTER WHERE SUBSTR(COST_CENTER_CODE,3) = '3801' AND ROWNUM =1)
    WHERE COST_CENTER_CODE = '71Q805';
   SELECT * FROM TERRITORY WHERE  COST_CENTER_CODE = '71Q805';

   SELECT * FROM TERRITORY WHERE  COST_CENTER_CODE = '714515';
   UPDATE TERRITORY SET HOME_STORE = (SELECT COST_CENTER_CODE FROM COST_CENTER WHERE SUBSTR(COST_CENTER_CODE,3) = '3320' AND ROWNUM =1)
    WHERE COST_CENTER_CODE = '714515';
   SELECT * FROM TERRITORY WHERE  COST_CENTER_CODE = '714515';

   SELECT * FROM TERRITORY WHERE  COST_CENTER_CODE = '718330';
   UPDATE TERRITORY SET HOME_STORE = (SELECT COST_CENTER_CODE FROM COST_CENTER WHERE SUBSTR(COST_CENTER_CODE,3) = '3735' AND ROWNUM =1)
    WHERE COST_CENTER_CODE = '718330';
   SELECT * FROM TERRITORY WHERE  COST_CENTER_CODE = '718330';

   SELECT * FROM TERRITORY WHERE  COST_CENTER_CODE = '718344';
   UPDATE TERRITORY SET HOME_STORE = (SELECT COST_CENTER_CODE FROM COST_CENTER WHERE SUBSTR(COST_CENTER_CODE,3) = '5020' AND ROWNUM =1)
    WHERE COST_CENTER_CODE = '718344';
   SELECT * FROM TERRITORY WHERE  COST_CENTER_CODE = '718344';

   SELECT * FROM TERRITORY WHERE  COST_CENTER_CODE = '714403';
   UPDATE TERRITORY SET HOME_STORE = (SELECT COST_CENTER_CODE FROM COST_CENTER WHERE SUBSTR(COST_CENTER_CODE,3) = '2735' AND ROWNUM =1)
    WHERE COST_CENTER_CODE = '714403';
   SELECT * FROM TERRITORY WHERE  COST_CENTER_CODE = '714403';

   SELECT * FROM TERRITORY WHERE  COST_CENTER_CODE = '716510';
   UPDATE TERRITORY SET HOME_STORE = (SELECT COST_CENTER_CODE FROM COST_CENTER WHERE SUBSTR(COST_CENTER_CODE,3) = '8699' AND ROWNUM =1)
    WHERE COST_CENTER_CODE = '716510';
   SELECT * FROM TERRITORY WHERE  COST_CENTER_CODE = '716510';

   SELECT * FROM TERRITORY WHERE  COST_CENTER_CODE = '716852';
   UPDATE TERRITORY SET HOME_STORE = (SELECT COST_CENTER_CODE FROM COST_CENTER WHERE SUBSTR(COST_CENTER_CODE,3) = '8699' AND ROWNUM =1)
    WHERE COST_CENTER_CODE = '716852';
   SELECT * FROM TERRITORY WHERE  COST_CENTER_CODE = '716852';

   SELECT * FROM TERRITORY WHERE  COST_CENTER_CODE = '714920';
   UPDATE TERRITORY SET HOME_STORE = (SELECT COST_CENTER_CODE FROM COST_CENTER WHERE SUBSTR(COST_CENTER_CODE,3) = '4300' AND ROWNUM =1)
    WHERE COST_CENTER_CODE = '714920';
   SELECT * FROM TERRITORY WHERE  COST_CENTER_CODE = '714920';

   SELECT * FROM TERRITORY WHERE  COST_CENTER_CODE = '71R114';
   UPDATE TERRITORY SET HOME_STORE = (SELECT COST_CENTER_CODE FROM COST_CENTER WHERE SUBSTR(COST_CENTER_CODE,3) = '7719' AND ROWNUM =1)
    WHERE COST_CENTER_CODE = '71R114';
   SELECT * FROM TERRITORY WHERE  COST_CENTER_CODE = '71R114';

   SELECT * FROM TERRITORY WHERE  COST_CENTER_CODE = '716422';
   UPDATE TERRITORY SET HOME_STORE = (SELECT COST_CENTER_CODE FROM COST_CENTER WHERE SUBSTR(COST_CENTER_CODE,3) = '8546' AND ROWNUM =1)
    WHERE COST_CENTER_CODE = '716422';
   SELECT * FROM TERRITORY WHERE  COST_CENTER_CODE = '716422';

   SELECT * FROM TERRITORY WHERE  COST_CENTER_CODE = '716691';
   UPDATE TERRITORY SET HOME_STORE = (SELECT COST_CENTER_CODE FROM COST_CENTER WHERE SUBSTR(COST_CENTER_CODE,3) = '4307' AND ROWNUM =1)
    WHERE COST_CENTER_CODE = '716691';
   SELECT * FROM TERRITORY WHERE  COST_CENTER_CODE = '716691';

   SELECT * FROM TERRITORY WHERE  COST_CENTER_CODE = '71R109';
   UPDATE TERRITORY SET HOME_STORE = (SELECT COST_CENTER_CODE FROM COST_CENTER WHERE SUBSTR(COST_CENTER_CODE,3) = '4324' AND ROWNUM =1)
    WHERE COST_CENTER_CODE = '71R109';
   SELECT * FROM TERRITORY WHERE  COST_CENTER_CODE = '71R109';

   SELECT * FROM TERRITORY WHERE  COST_CENTER_CODE = '714922';
   UPDATE TERRITORY SET HOME_STORE = (SELECT COST_CENTER_CODE FROM COST_CENTER WHERE SUBSTR(COST_CENTER_CODE,3) = '4349' AND ROWNUM =1)
    WHERE COST_CENTER_CODE = '714922';
   SELECT * FROM TERRITORY WHERE  COST_CENTER_CODE = '714922';

   SELECT * FROM TERRITORY WHERE  COST_CENTER_CODE = '716127';
   UPDATE TERRITORY SET HOME_STORE = (SELECT COST_CENTER_CODE FROM COST_CENTER WHERE SUBSTR(COST_CENTER_CODE,3) = '1254' AND ROWNUM =1)
    WHERE COST_CENTER_CODE = '716127';
   SELECT * FROM TERRITORY WHERE  COST_CENTER_CODE = '716127';

   SELECT * FROM TERRITORY WHERE  COST_CENTER_CODE = '716534';
   UPDATE TERRITORY SET HOME_STORE = (SELECT COST_CENTER_CODE FROM COST_CENTER WHERE SUBSTR(COST_CENTER_CODE,3) = '8960' AND ROWNUM =1)
    WHERE COST_CENTER_CODE = '716534';
   SELECT * FROM TERRITORY WHERE  COST_CENTER_CODE = '716534';

COMMIT;


BEGIN
   CCN_BATCH_PKG.UNLOCK_DATABASE_SP();
END;
/