/*
Created : nxk927 05/24/2018
          Deleting the duplciate record for HRCHY_DTL_CURR_ROW_VAL 1000
          SELECT */*insert*/ FROM HIERARCHY_DETAIL WHERE HRCHY_HDR_NAME = 'ADMINORG_HIERARCHY' AND HRCHY_DTL_CURR_LVL_VAL = '000010001000' AND HRCHY_DTL_NEXT_LVL_VAL = '~~';
*/
SELECT * FROM HIERARCHY_DETAIL WHERE HRCHY_HDR_NAME = 'ADMINORG_HIERARCHY' AND HRCHY_DTL_CURR_LVL_VAL = '000010001000' AND HRCHY_DTL_NEXT_LVL_VAL = '~~';

DELETE FROM HIERARCHY_DETAIL WHERE HRCHY_HDR_NAME = 'ADMINORG_HIERARCHY' AND HRCHY_DTL_CURR_LVL_VAL = '000010001000' AND HRCHY_DTL_NEXT_LVL_VAL = '~~';

COMMIT;