/*
Created : 06/25/2018 nxk927
          Updating Open_date as begin date for the cost centers with 3 characters as K.

SELECT */*insert*/ from FROM COST_CENTER WHERE SUBSTR(COST_CENTER_CODE,3) LIKE 'K%';
*/


SELECT COST_CENTER_CODE, COST_CENTER_NAME, CATEGORY, BEGIN_DATE, OPEN_DATE, CLOSE_DATE FROM COST_CENTER WHERE SUBSTR(COST_CENTER_CODE,3) LIKE 'K%';

UPDATE COST_CENTER SET OPEN_DATE = BEGIN_DATE WHERE SUBSTR(COST_CENTER_CODE,3) LIKE 'K%';


COMMIT;
