BEGIN
    CCN_BATCH_PKG.LOCK_DATABASE_SP(); -- PRAGMA AUTONOMOUS_TRANSACTION;
        
END;
/
DELETE FROM TAXWARE WHERE COST_CENTER_CODE = '80U145 ';
DELETE FROM MARKETING WHERE COST_CENTER_CODE = '80U145 ';
DELETE FROM TERRITORY WHERE COST_CENTER_CODE = '80U145 ';
DELETE FROM TERMINAL WHERE COST_CENTER_CODE = '80U145';
DELETE FROM POLLING_DWLD_RSN_HIST WHERE COST_CENTER_CODE = '80U145';
DELETE FROM BANK_CARD WHERE COST_CENTER_CODE = '80U145';
DELETE FROM TYPE WHERE COST_CENTER_CODE = '80U145';
DELETE FROM POLLING WHERE COST_CENTER_CODE = '80U145';
DELETE FROM STORE WHERE COST_CENTER_CODE = '80U145';
DELETE FROM STATUS WHERE COST_CENTER_CODE = '80U145';
DELETE FROM REAL_ESTATE WHERE COST_CENTER_CODE = '80U145';
DELETE FROM PHONE WHERE COST_CENTER_CODE = '80U145';
DELETE FROM OTHER WHERE COST_CENTER_CODE = '80U145';
DELETE FROM ADMINISTRATION WHERE COST_CENTER_CODE = '80U145';
DELETE FROM ADDRESS_USA WHERE COST_CENTER_CODE = '80U145';
DELETE FROM ADDRESS_OTHER WHERE COST_CENTER_CODE = '80U145';
DELETE FROM ADDRESS_MEX WHERE COST_CENTER_CODE = '80U145';
DELETE FROM ADDRESS_CAN WHERE COST_CENTER_CODE = '80U145';
DELETE FROM COST_CENTER WHERE COST_CENTER_CODE = '80U145';
DELETE FROM HIERARCHY_DETAIL  WHERE HRCHY_DTL_CURR_LVL_VAL LIKE '%80U145%'     OR HRCHY_DTL_NEXT_LVL_VAL LIKE '%80U145%';
DELETE FROM AUDIT_LOG  WHERE TRANSACTION_ID  LIKE '%80U145%';
COMMIT;

BEGIN
    	CCN_BATCH_PKG.UNLOCK_DATABASE_SP(); -- PRAGMA AUTONOMOUS_TRANSACTION; 
END;
/
