BEGIN
    CCN_BATCH_PKG.LOCK_DATABASE_SP(); -- PRAGMA AUTONOMOUS_TRANSACTION;
    common_tools.alter_all_triggers('DISABLE');
END;
/

DELETE FROM territory where COST_CENTER_CODE IN ('755806','758349');
DELETE FROM phone where COST_CENTER_CODE IN ('755806','758349');
DELETE FROM Status where COST_CENTER_CODE IN ('755806','758349');
DELETE FROM TYPE where COST_CENTER_CODE IN ('755806','758349');
DELETE FROM COST_CENTER WHERE COST_CENTER_CODE IN ('755806','758349'); 
DELETE FROM AUDIT_LOG WHERE TRANSACTION_ID LIKE ('%755806%');
DELETE FROM AUDIT_LOG WHERE TRANSACTION_ID LIKE ('%758349%');


BEGIN
    common_tools.alter_all_triggers('ENABLE');
    CCN_BATCH_PKG.UNLOCK_DATABASE_SP(); -- PRAGMA AUTONOMOUS_TRANSACTION; 
END;
/