/****************************
Created : nxk927 09/21/2016 
          updating the TERRITORY HOME COST CENTER FOR COST CENTER 75Q926  TO 702835 in TERRITORY table
          and updating the statement type to have BB and country code to BRB

SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '75Q926';
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q926';
*******************************/

BEGIN
    CCN_BATCH_PKG.LOCK_DATABASE_SP();
END;
/
----UPDATING THE TERRITORY HOME_STORE

UPDATE TERRITORY SET HOME_STORE = '702835' WHERE COST_CENTER_CODE ='75Q926';
UPDATE COST_CENTER 
   SET STATEMENT_TYPE = 'BB',
       ACQUISITION_CODE = 'BB',
       COUNTRY_CODE = 'BRB',
       CURRENCY_CODE = 'BBD'
 WHERE COST_CENTER_CODE ='75Q926';
COMMIT;

BEGIN
    CCN_BATCH_PKG.UNLOCK_DATABASE_SP();
END;
/