-- created by rxv940 on 02/08/2018
-- Based on data provided in Jira ASP-999
-- Run this in COSTCNTR

-- Updates for COST_CENTER table

UPDATE COST_CENTER 
   SET COST_CENTER_NAME= 'MOUNTAIN MULTI SEG REP' 
 WHERE COST_CENTER_CODE = '754005';
 
UPDATE COST_CENTER 
   SET COST_CENTER_NAME= 'JACKSON NEW RES REP' 
 WHERE COST_CENTER_CODE = '754048';
 
UPDATE COST_CENTER 
   SET COST_CENTER_NAME= 'SOUTH FLORIDA METRO MULTI SEG REP' 
 WHERE COST_CENTER_CODE = '754061';
 
UPDATE COST_CENTER 
   SET COST_CENTER_NAME= 'SOUTH FLORIDA METRO PROP MAINT REP' 
 WHERE COST_CENTER_CODE = '754093';
 
UPDATE COST_CENTER
   SET COST_CENTER_NAME= 'ORLANDO PROP MAINT REP'
 WHERE COST_CENTER_CODE = '754095';

UPDATE COST_CENTER
   SET COST_CENTER_NAME= 'PHILADELPHIA RES REPAINT REP'
 WHERE COST_CENTER_CODE = '754119';

UPDATE COST_CENTER
   SET COST_CENTER_NAME= 'GREEN BAY MULTI SEG REP'
 WHERE COST_CENTER_CODE = '754161';

UPDATE COST_CENTER
   SET COST_CENTER_NAME= 'MANITOBA COMM REP'
 WHERE COST_CENTER_CODE = '764201';

UPDATE COST_CENTER
   SET COST_CENTER_NAME= 'METRO NEW YORK MULTI SEG REP'
 WHERE COST_CENTER_CODE = '754232';

UPDATE COST_CENTER
   SET COST_CENTER_NAME= 'SOUTH FLORIDA METRO PROP MAINT REP'
 WHERE COST_CENTER_CODE = '754296';

UPDATE COST_CENTER
   SET COST_CENTER_NAME= 'NEW ORLEANS NEW RES REP'
 WHERE COST_CENTER_CODE = '754471';

UPDATE COST_CENTER
   SET COST_CENTER_NAME= 'UPSTATE NY MULTI SEG REP'
 WHERE COST_CENTER_CODE = '754502';

UPDATE COST_CENTER
   SET COST_CENTER_NAME= 'TAMPA NEW RES REP'
 WHERE COST_CENTER_CODE = '754563';

UPDATE COST_CENTER
   SET COST_CENTER_NAME= 'WILMINGTON NEW RES REP'
 WHERE COST_CENTER_CODE = '754576';

UPDATE COST_CENTER
   SET COST_CENTER_NAME= 'LOS ANGELES RES REPAINT REP'
 WHERE COST_CENTER_CODE = '754646';

UPDATE COST_CENTER
   SET COST_CENTER_NAME= 'SEATTLE MULTI SEG REP'
 WHERE COST_CENTER_CODE = '754754';

UPDATE COST_CENTER
   SET COST_CENTER_NAME= 'CALIFORNIA NORTH MULTI SEG REP'
 WHERE COST_CENTER_CODE = '754768';

UPDATE COST_CENTER
   SET COST_CENTER_NAME= 'DETROIT MULTI SEG REP'
 WHERE COST_CENTER_CODE = '754789';

UPDATE COST_CENTER
   SET COST_CENTER_NAME= 'LEXINGTON MULTI SEG REP'
 WHERE COST_CENTER_CODE = '754814';

UPDATE COST_CENTER
   SET COST_CENTER_NAME= 'ATLANTA COMM REP'
 WHERE COST_CENTER_CODE = '754916';

UPDATE COST_CENTER
   SET COST_CENTER_NAME= 'CHARLESTON WV PROP MAINT REP'
 WHERE COST_CENTER_CODE = '754966';

UPDATE COST_CENTER
   SET COST_CENTER_NAME= 'CALIFORNIA BAY COMM REP'
 WHERE COST_CENTER_CODE = '754972';

UPDATE COST_CENTER
   SET COST_CENTER_NAME= 'DELMAR RES REPAINT REP'
 WHERE COST_CENTER_CODE = '755507';

UPDATE COST_CENTER
   SET COST_CENTER_NAME= 'CENTRAL PENNSYLVANIA NEW RES REP'
 WHERE COST_CENTER_CODE = '755523';

UPDATE COST_CENTER
   SET COST_CENTER_NAME= 'NY CAPITAL RES REPAINT REP'
 WHERE COST_CENTER_CODE = '755535';

UPDATE COST_CENTER
   SET COST_CENTER_NAME= 'BALTIMORE MULTI SEG REP'
 WHERE COST_CENTER_CODE = '755584';

UPDATE COST_CENTER
   SET COST_CENTER_NAME= 'DELMAR MULTI SEG REP'
 WHERE COST_CENTER_CODE = '755601';

UPDATE COST_CENTER
   SET COST_CENTER_NAME= 'NORFOLK RES REPAINT REP'
 WHERE COST_CENTER_CODE = '755639';

UPDATE COST_CENTER
   SET COST_CENTER_NAME= 'CHARLOTTE METRO COMM REP'
 WHERE COST_CENTER_CODE = '755727';

UPDATE COST_CENTER
   SET COST_CENTER_NAME= 'ATLANTA RES REPAINT REP'
 WHERE COST_CENTER_CODE = '755770';

UPDATE COST_CENTER
   SET COST_CENTER_NAME= 'ATLANTA MULTI SEG REP'
 WHERE COST_CENTER_CODE = '755793';

UPDATE COST_CENTER
   SET COST_CENTER_NAME= 'CAPITAL PROP MAINT REP'
 WHERE COST_CENTER_CODE = '755848';

UPDATE COST_CENTER
   SET COST_CENTER_NAME= 'FLORIDA PANHANDLE COMM REP'
 WHERE COST_CENTER_CODE = '755886';

UPDATE COST_CENTER
   SET COST_CENTER_NAME= 'CALIFORNIA BAY PROP MAINT REP'
 WHERE COST_CENTER_CODE = '755975';

UPDATE COST_CENTER
   SET COST_CENTER_NAME= 'CHARLESTON METRO NEW RES REP'
 WHERE COST_CENTER_CODE = '756027';

UPDATE COST_CENTER
   SET COST_CENTER_NAME= 'BOSTON MULTI SEG REP'
 WHERE COST_CENTER_CODE = '756032';

UPDATE COST_CENTER
   SET COST_CENTER_NAME= 'TWIN CITIES NEW RES REP'
 WHERE COST_CENTER_CODE = '756073';

UPDATE COST_CENTER
   SET COST_CENTER_NAME= 'DETROIT MULTI SEG REP'
 WHERE COST_CENTER_CODE = '756078';

UPDATE COST_CENTER
   SET COST_CENTER_NAME= 'BRITISH COLUMBIA RES REPAINT REP'
 WHERE COST_CENTER_CODE = '766098';

UPDATE COST_CENTER
   SET COST_CENTER_NAME= 'ROANOKE RES REPAINT REP'
 WHERE COST_CENTER_CODE = '756150';

UPDATE COST_CENTER
   SET COST_CENTER_NAME= 'MISSOURI PROP MAINT REP'
 WHERE COST_CENTER_CODE = '756233';

UPDATE COST_CENTER
   SET COST_CENTER_NAME= 'SEATTLE COMM REP'
 WHERE COST_CENTER_CODE = '756283';

UPDATE COST_CENTER
   SET COST_CENTER_NAME= 'EL PASO MULTI SEG REP'
 WHERE COST_CENTER_CODE = '756297';

UPDATE COST_CENTER
   SET COST_CENTER_NAME= 'ATLANTIC CANADA COMM REP'
 WHERE COST_CENTER_CODE = '766310';

UPDATE COST_CENTER
   SET COST_CENTER_NAME= 'CALIFORNIA BAY RES REPAINT REP'
 WHERE COST_CENTER_CODE = '756336';

UPDATE COST_CENTER
   SET COST_CENTER_NAME= 'DALLAS-FT WORTH COMM REP'
 WHERE COST_CENTER_CODE = '756426';

UPDATE COST_CENTER
   SET COST_CENTER_NAME= 'WEST TEXAS COMM REP'
 WHERE COST_CENTER_CODE = '756498';

UPDATE COST_CENTER
   SET COST_CENTER_NAME= 'DALLAS-FT WORTH MULTI SEG REP'
 WHERE COST_CENTER_CODE = '756499';

UPDATE COST_CENTER
   SET COST_CENTER_NAME= 'RALEIGH METRO MULTI SEG REP'
 WHERE COST_CENTER_CODE = '756512';

UPDATE COST_CENTER
   SET COST_CENTER_NAME= 'MILWAUKEE COMM REP'
 WHERE COST_CENTER_CODE = '756514';

UPDATE COST_CENTER
   SET COST_CENTER_NAME= 'TEXARKANA MULTI SEG REP'
 WHERE COST_CENTER_CODE = '756521';

UPDATE COST_CENTER
   SET COST_CENTER_NAME= 'CINCINNATI MULTI SEG REP'
 WHERE COST_CENTER_CODE = '756589';

UPDATE COST_CENTER
   SET COST_CENTER_NAME= 'SAN ANTONIO RES REPAINT REP'
 WHERE COST_CENTER_CODE = '756638';

UPDATE COST_CENTER
   SET COST_CENTER_NAME= 'CARIBBEAN MULTI SEG REP'
 WHERE COST_CENTER_CODE = '756716';

UPDATE COST_CENTER
   SET COST_CENTER_NAME= 'ATLANTA PROP MAINT REP'
 WHERE COST_CENTER_CODE = '756785';

UPDATE COST_CENTER
   SET COST_CENTER_NAME= 'GREEN BAY NEW RES REP'
 WHERE COST_CENTER_CODE = '756881';

UPDATE COST_CENTER
   SET COST_CENTER_NAME= 'CASCADE NEW RES REP'
 WHERE COST_CENTER_CODE = '756929';

UPDATE COST_CENTER
   SET COST_CENTER_NAME= 'HOUSTON RES REPAINT REP'
 WHERE COST_CENTER_CODE = '756952';

UPDATE COST_CENTER
   SET COST_CENTER_NAME= 'DALLAS-FT WORTH MULTI SEG REP'
 WHERE COST_CENTER_CODE = '756953';

UPDATE COST_CENTER
   SET COST_CENTER_NAME= 'TORONTO METRO COMM REP'
 WHERE COST_CENTER_CODE = '766986';

UPDATE COST_CENTER
   SET COST_CENTER_NAME= 'TOLEDO RES REPAINT REP'
 WHERE COST_CENTER_CODE = '758361';

UPDATE COST_CENTER
   SET COST_CENTER_NAME= 'SOUTH BEND MULTI SEG REP'
 WHERE COST_CENTER_CODE = '758362';

UPDATE COST_CENTER
   SET COST_CENTER_NAME= 'HAWAII RES REPAINT REP'
 WHERE COST_CENTER_CODE = '758379';

UPDATE COST_CENTER
   SET COST_CENTER_NAME= 'TORONTO METRO MULTI SEG REP'
 WHERE COST_CENTER_CODE = '768391';

UPDATE COST_CENTER
   SET COST_CENTER_NAME= 'BOISE MULTI SEG REP'
 WHERE COST_CENTER_CODE = '758406';

UPDATE COST_CENTER
   SET COST_CENTER_NAME= 'CALIFORNIA CENTRAL RES REPAINT REP'
 WHERE COST_CENTER_CODE = '75Q036';

UPDATE COST_CENTER
   SET COST_CENTER_NAME= 'SAN FERNANDO COMM REP'
 WHERE COST_CENTER_CODE = '75Q047';

UPDATE COST_CENTER
   SET COST_CENTER_NAME= 'LOS ANGELES RES REPAINT REP'
 WHERE COST_CENTER_CODE = '75Q078';

UPDATE COST_CENTER
   SET COST_CENTER_NAME= 'LOS ANGELES MULTI SEG REP'
 WHERE COST_CENTER_CODE = '75Q102';

UPDATE COST_CENTER
   SET COST_CENTER_NAME= 'LOS ANGELES RES REPAINT REP'
 WHERE COST_CENTER_CODE = '75Q107';

UPDATE COST_CENTER
   SET COST_CENTER_NAME= 'LOS ANGELES NEW RES REP'
 WHERE COST_CENTER_CODE = '75Q108';

UPDATE COST_CENTER
   SET COST_CENTER_NAME= 'DALLAS-FT WORTH RES REPAINT REP'
 WHERE COST_CENTER_CODE = '75Q137';

UPDATE COST_CENTER
   SET COST_CENTER_NAME= 'DALLAS-FT WORTH MULTI SEG REP'
 WHERE COST_CENTER_CODE = '75Q138';

UPDATE COST_CENTER
   SET COST_CENTER_NAME= 'HOUSTON MULTI SEG REP'
 WHERE COST_CENTER_CODE = '75Q157';

UPDATE COST_CENTER
   SET COST_CENTER_NAME= 'SALT LAKE CITY PROP MAINT REP'
 WHERE COST_CENTER_CODE = '75Q163';

UPDATE COST_CENTER
   SET COST_CENTER_NAME= 'SOUTH FLORIDA METRO COMM REP'
 WHERE COST_CENTER_CODE = '75Q210';

UPDATE COST_CENTER
   SET COST_CENTER_NAME= 'BRITISH COLUMBIA MULTI SEG REP'
 WHERE COST_CENTER_CODE = '76Q232';

UPDATE COST_CENTER
   SET COST_CENTER_NAME= 'CHARLESTON WV MULTI SEG REP'
 WHERE COST_CENTER_CODE = '75Q417';

UPDATE COST_CENTER
   SET COST_CENTER_NAME= 'METRO NEW YORK MULTI SEG REP'
 WHERE COST_CENTER_CODE = '75Q418';

UPDATE COST_CENTER
   SET COST_CENTER_NAME= 'METRO CONNECTICUT MULTI SEG REP'
 WHERE COST_CENTER_CODE = '75Q427';

UPDATE COST_CENTER
   SET COST_CENTER_NAME= 'METRO NEW YORK RES REPAINT REP'
 WHERE COST_CENTER_CODE = '75Q431';

UPDATE COST_CENTER
   SET COST_CENTER_NAME= 'NEW JERSEY COASTAL MULTI SEG REP'
 WHERE COST_CENTER_CODE = '75Q478';

UPDATE COST_CENTER
   SET COST_CENTER_NAME= 'BOSTON MULTI SEG REP'
 WHERE COST_CENTER_CODE = '75Q480';

UPDATE COST_CENTER
   SET COST_CENTER_NAME= 'METRO NEW JERSEY MULTI SEG REP'
 WHERE COST_CENTER_CODE = '75Q497';

UPDATE COST_CENTER
   SET COST_CENTER_NAME= 'NORTHERN MULTI SEG REP'
 WHERE COST_CENTER_CODE = '75Q498';

UPDATE COST_CENTER
   SET COST_CENTER_NAME= 'SOUTHERN ALABAMA RES REPAINT REP'
 WHERE COST_CENTER_CODE = '75Q500';

UPDATE COST_CENTER
   SET COST_CENTER_NAME= 'SOUTH FLORIDA METRO PROP MAINT REP'
 WHERE COST_CENTER_CODE = '75Q519';

UPDATE COST_CENTER
   SET COST_CENTER_NAME= 'TAMPA MULTI SEG REP'
 WHERE COST_CENTER_CODE = '75Q524';

UPDATE COST_CENTER
   SET COST_CENTER_NAME= 'LOUISIANA MULTI SEG REP'
 WHERE COST_CENTER_CODE = '75Q573';

UPDATE COST_CENTER
   SET COST_CENTER_NAME= 'FLORIDA PANHANDLE MULTI SEG REP'
 WHERE COST_CENTER_CODE = '75Q582';

UPDATE COST_CENTER
   SET COST_CENTER_NAME= 'SOUTHERN ALABAMA RES REPAINT REP'
 WHERE COST_CENTER_CODE = '75Q589';

UPDATE COST_CENTER
   SET COST_CENTER_NAME= 'CAL COAST MULTI SEG REP'
 WHERE COST_CENTER_CODE = '75Q605';

UPDATE COST_CENTER
   SET COST_CENTER_NAME= 'CALIFORNIA NORTH RES REPAINT REP'
 WHERE COST_CENTER_CODE = '75Q629';

UPDATE COST_CENTER
   SET COST_CENTER_NAME= 'CALIFORNIA CENTRAL MULTI SEG REP'
 WHERE COST_CENTER_CODE = '75Q663';

UPDATE COST_CENTER
   SET COST_CENTER_NAME= 'HOUSTON RES REPAINT REP'
 WHERE COST_CENTER_CODE = '75Q670';

UPDATE COST_CENTER
   SET COST_CENTER_NAME= 'DALLAS-FT WORTH MULTI SEG REP'
 WHERE COST_CENTER_CODE = '75Q714';

UPDATE COST_CENTER
   SET COST_CENTER_NAME= 'DAKOTAS MULTI SEG REP'
 WHERE COST_CENTER_CODE = '75Q759';

UPDATE COST_CENTER
   SET COST_CENTER_NAME= 'MINNESOTA MULTI SEG REP'
 WHERE COST_CENTER_CODE = '75Q779';

UPDATE COST_CENTER
   SET COST_CENTER_NAME= 'TRI-CITIES MULTI SEG REP'
 WHERE COST_CENTER_CODE = '75Q783';

UPDATE COST_CENTER
   SET COST_CENTER_NAME= 'MONTREAL RES REPAINT REP'
 WHERE COST_CENTER_CODE = '76Q856';

UPDATE COST_CENTER
   SET COST_CENTER_NAME= 'MONTREAL MULTI SEG REP'
 WHERE COST_CENTER_CODE = '76Q863';

UPDATE COST_CENTER
   SET COST_CENTER_NAME= 'QUEBEC MULTI SEG REP'
 WHERE COST_CENTER_CODE = '76Q886';

UPDATE COST_CENTER
   SET COST_CENTER_NAME= 'ATLANTIC CANADA MULTI SEG REP'
 WHERE COST_CENTER_CODE = '76Q889';

UPDATE COST_CENTER
   SET COST_CENTER_NAME= 'MONTREAL RES REPAINT REP'
 WHERE COST_CENTER_CODE = '76Q899';

UPDATE COST_CENTER
   SET COST_CENTER_NAME= 'SOUTH FLORIDA METRO MULTI SEG REP'
 WHERE COST_CENTER_CODE = '75Q900';

UPDATE COST_CENTER
   SET COST_CENTER_NAME= 'CHARLOTTE METRO MULTI SEG REP'
 WHERE COST_CENTER_CODE = '75Q907';

UPDATE COST_CENTER
   SET COST_CENTER_NAME= 'SOUTHWEST FLORIDA METRO RES REPAINT REP'
 WHERE COST_CENTER_CODE = '75Q928';

UPDATE COST_CENTER
   SET COST_CENTER_NAME= 'LOUISIANA MULTI SEG REP'
 WHERE COST_CENTER_CODE = '75Q935';

UPDATE COST_CENTER
   SET COST_CENTER_NAME= 'SASKATCHEWAN MULTI SEG REP'
 WHERE COST_CENTER_CODE = '76Q959';

UPDATE COST_CENTER
   SET COST_CENTER_NAME= 'UPSTATE NY MULTI SEG REP'
 WHERE COST_CENTER_CODE = '75Q989';

UPDATE COST_CENTER
   SET COST_CENTER_NAME= 'BOSTON MULTI SEG REP'
 WHERE COST_CENTER_CODE = '75Q996';


COMMIT;


-- UPDATES for TERRITORY table

UPDATE TERRITORY
   SET TERRITORY_TYPE_BUSN_CODE= 'MS'
 WHERE COST_CENTER_CODE = '754005';

UPDATE TERRITORY
   SET TERRITORY_TYPE_BUSN_CODE= 'NR'
 WHERE COST_CENTER_CODE = '754048';

UPDATE TERRITORY
   SET TERRITORY_TYPE_BUSN_CODE= 'MS'
 WHERE COST_CENTER_CODE = '754061';

UPDATE TERRITORY
   SET TERRITORY_TYPE_BUSN_CODE= 'PM'
 WHERE COST_CENTER_CODE = '754093';

UPDATE TERRITORY
   SET TERRITORY_TYPE_BUSN_CODE= 'PM'
 WHERE COST_CENTER_CODE = '754095';

UPDATE TERRITORY
   SET TERRITORY_TYPE_BUSN_CODE= 'RR'
 WHERE COST_CENTER_CODE = '754119';

UPDATE TERRITORY
   SET TERRITORY_TYPE_BUSN_CODE= 'MS'
 WHERE COST_CENTER_CODE = '754161';

UPDATE TERRITORY
   SET TERRITORY_TYPE_BUSN_CODE= 'CM'
 WHERE COST_CENTER_CODE = '764201';

UPDATE TERRITORY
   SET TERRITORY_TYPE_BUSN_CODE= 'MS'
 WHERE COST_CENTER_CODE = '754232';

UPDATE TERRITORY
   SET TERRITORY_TYPE_BUSN_CODE= 'PM'
 WHERE COST_CENTER_CODE = '754296';

UPDATE TERRITORY
   SET TERRITORY_TYPE_BUSN_CODE= 'NR'
 WHERE COST_CENTER_CODE = '754471';

UPDATE TERRITORY
   SET TERRITORY_TYPE_BUSN_CODE= 'MS'
 WHERE COST_CENTER_CODE = '754502';

UPDATE TERRITORY
   SET TERRITORY_TYPE_BUSN_CODE= 'NR'
 WHERE COST_CENTER_CODE = '754563';

UPDATE TERRITORY
   SET TERRITORY_TYPE_BUSN_CODE= 'NR'
 WHERE COST_CENTER_CODE = '754576';

UPDATE TERRITORY
   SET TERRITORY_TYPE_BUSN_CODE= 'RR'
 WHERE COST_CENTER_CODE = '754646';

UPDATE TERRITORY
   SET TERRITORY_TYPE_BUSN_CODE= 'MS'
 WHERE COST_CENTER_CODE = '754754';

UPDATE TERRITORY
   SET TERRITORY_TYPE_BUSN_CODE= 'MS'
 WHERE COST_CENTER_CODE = '754768';

UPDATE TERRITORY
   SET TERRITORY_TYPE_BUSN_CODE= 'MS'
 WHERE COST_CENTER_CODE = '754789';

UPDATE TERRITORY
   SET TERRITORY_TYPE_BUSN_CODE= 'MS'
 WHERE COST_CENTER_CODE = '754814';

UPDATE TERRITORY
   SET TERRITORY_TYPE_BUSN_CODE= 'CM'
 WHERE COST_CENTER_CODE = '754916';

UPDATE TERRITORY
   SET TERRITORY_TYPE_BUSN_CODE= 'PM'
 WHERE COST_CENTER_CODE = '754966';

UPDATE TERRITORY
   SET TERRITORY_TYPE_BUSN_CODE= 'CM'
 WHERE COST_CENTER_CODE = '754972';

UPDATE TERRITORY
   SET TERRITORY_TYPE_BUSN_CODE= 'RR'
 WHERE COST_CENTER_CODE = '755507';

UPDATE TERRITORY
   SET TERRITORY_TYPE_BUSN_CODE= 'NR'
 WHERE COST_CENTER_CODE = '755523';

UPDATE TERRITORY
   SET TERRITORY_TYPE_BUSN_CODE= 'RR'
 WHERE COST_CENTER_CODE = '755535';

UPDATE TERRITORY
   SET TERRITORY_TYPE_BUSN_CODE= 'MS'
 WHERE COST_CENTER_CODE = '755584';

UPDATE TERRITORY
   SET TERRITORY_TYPE_BUSN_CODE= 'MS'
 WHERE COST_CENTER_CODE = '755601';

UPDATE TERRITORY
   SET TERRITORY_TYPE_BUSN_CODE= 'RR'
 WHERE COST_CENTER_CODE = '755639';

UPDATE TERRITORY
   SET TERRITORY_TYPE_BUSN_CODE= 'CM'
 WHERE COST_CENTER_CODE = '755727';

UPDATE TERRITORY
   SET TERRITORY_TYPE_BUSN_CODE= 'RR'
 WHERE COST_CENTER_CODE = '755770';

UPDATE TERRITORY
   SET TERRITORY_TYPE_BUSN_CODE= 'MS'
 WHERE COST_CENTER_CODE = '755793';

UPDATE TERRITORY
   SET TERRITORY_TYPE_BUSN_CODE= 'PM'
 WHERE COST_CENTER_CODE = '755848';

UPDATE TERRITORY
   SET TERRITORY_TYPE_BUSN_CODE= 'CM'
 WHERE COST_CENTER_CODE = '755886';

UPDATE TERRITORY
   SET TERRITORY_TYPE_BUSN_CODE= 'PM'
 WHERE COST_CENTER_CODE = '755975';

UPDATE TERRITORY
   SET TERRITORY_TYPE_BUSN_CODE= 'NR'
 WHERE COST_CENTER_CODE = '756027';

UPDATE TERRITORY
   SET TERRITORY_TYPE_BUSN_CODE= 'MS'
 WHERE COST_CENTER_CODE = '756032';

UPDATE TERRITORY
   SET TERRITORY_TYPE_BUSN_CODE= 'NR'
 WHERE COST_CENTER_CODE = '756073';

UPDATE TERRITORY
   SET TERRITORY_TYPE_BUSN_CODE= 'MS'
 WHERE COST_CENTER_CODE = '756078';

UPDATE TERRITORY
   SET TERRITORY_TYPE_BUSN_CODE= 'RR'
 WHERE COST_CENTER_CODE = '766098';

UPDATE TERRITORY
   SET TERRITORY_TYPE_BUSN_CODE= 'RR'
 WHERE COST_CENTER_CODE = '756150';

UPDATE TERRITORY
   SET TERRITORY_TYPE_BUSN_CODE= 'PM'
 WHERE COST_CENTER_CODE = '756233';

UPDATE TERRITORY
   SET TERRITORY_TYPE_BUSN_CODE= 'CM'
 WHERE COST_CENTER_CODE = '756283';

UPDATE TERRITORY
   SET TERRITORY_TYPE_BUSN_CODE= 'MS'
 WHERE COST_CENTER_CODE = '756297';

UPDATE TERRITORY
   SET TERRITORY_TYPE_BUSN_CODE= 'CM'
 WHERE COST_CENTER_CODE = '766310';

UPDATE TERRITORY
   SET TERRITORY_TYPE_BUSN_CODE= 'RR'
 WHERE COST_CENTER_CODE = '756336';

UPDATE TERRITORY
   SET TERRITORY_TYPE_BUSN_CODE= 'CM'
 WHERE COST_CENTER_CODE = '756426';

UPDATE TERRITORY
   SET TERRITORY_TYPE_BUSN_CODE= 'CM'
 WHERE COST_CENTER_CODE = '756498';

UPDATE TERRITORY
   SET TERRITORY_TYPE_BUSN_CODE= 'MS'
 WHERE COST_CENTER_CODE = '756499';

UPDATE TERRITORY
   SET TERRITORY_TYPE_BUSN_CODE= 'MS'
 WHERE COST_CENTER_CODE = '756512';

UPDATE TERRITORY
   SET TERRITORY_TYPE_BUSN_CODE= 'CM'
 WHERE COST_CENTER_CODE = '756514';

UPDATE TERRITORY
   SET TERRITORY_TYPE_BUSN_CODE= 'MS'
 WHERE COST_CENTER_CODE = '756521';

UPDATE TERRITORY
   SET TERRITORY_TYPE_BUSN_CODE= 'MS'
 WHERE COST_CENTER_CODE = '756589';

UPDATE TERRITORY
   SET TERRITORY_TYPE_BUSN_CODE= 'RR'
 WHERE COST_CENTER_CODE = '756638';

UPDATE TERRITORY
   SET TERRITORY_TYPE_BUSN_CODE= 'MS'
 WHERE COST_CENTER_CODE = '756716';

UPDATE TERRITORY
   SET TERRITORY_TYPE_BUSN_CODE= 'PM'
 WHERE COST_CENTER_CODE = '756785';

UPDATE TERRITORY
   SET TERRITORY_TYPE_BUSN_CODE= 'NR'
 WHERE COST_CENTER_CODE = '756881';

UPDATE TERRITORY
   SET TERRITORY_TYPE_BUSN_CODE= 'NR'
 WHERE COST_CENTER_CODE = '756929';

UPDATE TERRITORY
   SET TERRITORY_TYPE_BUSN_CODE= 'RR'
 WHERE COST_CENTER_CODE = '756952';

UPDATE TERRITORY
   SET TERRITORY_TYPE_BUSN_CODE= 'MS'
 WHERE COST_CENTER_CODE = '756953';

UPDATE TERRITORY
   SET TERRITORY_TYPE_BUSN_CODE= 'CM'
 WHERE COST_CENTER_CODE = '766986';

UPDATE TERRITORY
   SET TERRITORY_TYPE_BUSN_CODE= 'RR'
 WHERE COST_CENTER_CODE = '758361';

UPDATE TERRITORY
   SET TERRITORY_TYPE_BUSN_CODE= 'MS'
 WHERE COST_CENTER_CODE = '758362';

UPDATE TERRITORY
   SET TERRITORY_TYPE_BUSN_CODE= 'RR'
 WHERE COST_CENTER_CODE = '758379';

UPDATE TERRITORY
   SET TERRITORY_TYPE_BUSN_CODE= 'MS'
 WHERE COST_CENTER_CODE = '768391';

UPDATE TERRITORY
   SET TERRITORY_TYPE_BUSN_CODE= 'MS'
 WHERE COST_CENTER_CODE = '758406';

UPDATE TERRITORY
   SET TERRITORY_TYPE_BUSN_CODE= 'RR'
 WHERE COST_CENTER_CODE = '75Q036';

UPDATE TERRITORY
   SET TERRITORY_TYPE_BUSN_CODE= 'CM'
 WHERE COST_CENTER_CODE = '75Q047';

UPDATE TERRITORY
   SET TERRITORY_TYPE_BUSN_CODE= 'RR'
 WHERE COST_CENTER_CODE = '75Q078';

UPDATE TERRITORY
   SET TERRITORY_TYPE_BUSN_CODE= 'MS'
 WHERE COST_CENTER_CODE = '75Q102';

UPDATE TERRITORY
   SET TERRITORY_TYPE_BUSN_CODE= 'RR'
 WHERE COST_CENTER_CODE = '75Q107';

UPDATE TERRITORY
   SET TERRITORY_TYPE_BUSN_CODE= 'NR'
 WHERE COST_CENTER_CODE = '75Q108';

UPDATE TERRITORY
   SET TERRITORY_TYPE_BUSN_CODE= 'RR'
 WHERE COST_CENTER_CODE = '75Q137';

UPDATE TERRITORY
   SET TERRITORY_TYPE_BUSN_CODE= 'MS'
 WHERE COST_CENTER_CODE = '75Q138';

UPDATE TERRITORY
   SET TERRITORY_TYPE_BUSN_CODE= 'MS'
 WHERE COST_CENTER_CODE = '75Q157';

UPDATE TERRITORY
   SET TERRITORY_TYPE_BUSN_CODE= 'PM'
 WHERE COST_CENTER_CODE = '75Q163';

UPDATE TERRITORY
   SET TERRITORY_TYPE_BUSN_CODE= 'CM'
 WHERE COST_CENTER_CODE = '75Q210';

UPDATE TERRITORY
   SET TERRITORY_TYPE_BUSN_CODE= 'MS'
 WHERE COST_CENTER_CODE = '76Q232';

UPDATE TERRITORY
   SET TERRITORY_TYPE_BUSN_CODE= 'MS'
 WHERE COST_CENTER_CODE = '75Q417';

UPDATE TERRITORY
   SET TERRITORY_TYPE_BUSN_CODE= 'MS'
 WHERE COST_CENTER_CODE = '75Q418';

UPDATE TERRITORY
   SET TERRITORY_TYPE_BUSN_CODE= 'MS'
 WHERE COST_CENTER_CODE = '75Q427';

UPDATE TERRITORY
   SET TERRITORY_TYPE_BUSN_CODE= 'RR'
 WHERE COST_CENTER_CODE = '75Q431';

UPDATE TERRITORY
   SET TERRITORY_TYPE_BUSN_CODE= 'MS'
 WHERE COST_CENTER_CODE = '75Q478';

UPDATE TERRITORY
   SET TERRITORY_TYPE_BUSN_CODE= 'MS'
 WHERE COST_CENTER_CODE = '75Q480';

UPDATE TERRITORY
   SET TERRITORY_TYPE_BUSN_CODE= 'MS'
 WHERE COST_CENTER_CODE = '75Q497';

UPDATE TERRITORY
   SET TERRITORY_TYPE_BUSN_CODE= 'MS'
 WHERE COST_CENTER_CODE = '75Q498';

UPDATE TERRITORY
   SET TERRITORY_TYPE_BUSN_CODE= 'RR'
 WHERE COST_CENTER_CODE = '75Q500';

UPDATE TERRITORY
   SET TERRITORY_TYPE_BUSN_CODE= 'PM'
 WHERE COST_CENTER_CODE = '75Q519';

UPDATE TERRITORY
   SET TERRITORY_TYPE_BUSN_CODE= 'MS'
 WHERE COST_CENTER_CODE = '75Q524';

UPDATE TERRITORY
   SET TERRITORY_TYPE_BUSN_CODE= 'MS'
 WHERE COST_CENTER_CODE = '75Q573';

UPDATE TERRITORY
   SET TERRITORY_TYPE_BUSN_CODE= 'MS'
 WHERE COST_CENTER_CODE = '75Q582';

UPDATE TERRITORY
   SET TERRITORY_TYPE_BUSN_CODE= 'RR'
 WHERE COST_CENTER_CODE = '75Q589';

UPDATE TERRITORY
   SET TERRITORY_TYPE_BUSN_CODE= 'MS'
 WHERE COST_CENTER_CODE = '75Q605';

UPDATE TERRITORY
   SET TERRITORY_TYPE_BUSN_CODE= 'RR'
 WHERE COST_CENTER_CODE = '75Q629';

UPDATE TERRITORY
   SET TERRITORY_TYPE_BUSN_CODE= 'MS'
 WHERE COST_CENTER_CODE = '75Q663';

UPDATE TERRITORY
   SET TERRITORY_TYPE_BUSN_CODE= 'RR'
 WHERE COST_CENTER_CODE = '75Q670';

UPDATE TERRITORY
   SET TERRITORY_TYPE_BUSN_CODE= 'MS'
 WHERE COST_CENTER_CODE = '75Q714';

UPDATE TERRITORY
   SET TERRITORY_TYPE_BUSN_CODE= 'MS'
 WHERE COST_CENTER_CODE = '75Q759';

UPDATE TERRITORY
   SET TERRITORY_TYPE_BUSN_CODE= 'MS'
 WHERE COST_CENTER_CODE = '75Q779';

UPDATE TERRITORY
   SET TERRITORY_TYPE_BUSN_CODE= 'MS'
 WHERE COST_CENTER_CODE = '75Q783';

UPDATE TERRITORY
   SET TERRITORY_TYPE_BUSN_CODE= 'RR'
 WHERE COST_CENTER_CODE = '76Q856';

UPDATE TERRITORY
   SET TERRITORY_TYPE_BUSN_CODE= 'MS'
 WHERE COST_CENTER_CODE = '76Q863';

UPDATE TERRITORY
   SET TERRITORY_TYPE_BUSN_CODE= 'MS'
 WHERE COST_CENTER_CODE = '76Q886';

UPDATE TERRITORY
   SET TERRITORY_TYPE_BUSN_CODE= 'MS'
 WHERE COST_CENTER_CODE = '76Q889';

UPDATE TERRITORY
   SET TERRITORY_TYPE_BUSN_CODE= 'RR'
 WHERE COST_CENTER_CODE = '76Q899';

UPDATE TERRITORY
   SET TERRITORY_TYPE_BUSN_CODE= 'MS'
 WHERE COST_CENTER_CODE = '75Q900';

UPDATE TERRITORY
   SET TERRITORY_TYPE_BUSN_CODE= 'MS'
 WHERE COST_CENTER_CODE = '75Q907';

UPDATE TERRITORY
   SET TERRITORY_TYPE_BUSN_CODE= 'RR'
 WHERE COST_CENTER_CODE = '75Q928';

UPDATE TERRITORY
   SET TERRITORY_TYPE_BUSN_CODE= 'MS'
 WHERE COST_CENTER_CODE = '75Q935';

UPDATE TERRITORY
   SET TERRITORY_TYPE_BUSN_CODE= 'MS'
 WHERE COST_CENTER_CODE = '76Q959';

UPDATE TERRITORY
   SET TERRITORY_TYPE_BUSN_CODE= 'MS'
 WHERE COST_CENTER_CODE = '75Q989';

UPDATE TERRITORY
   SET TERRITORY_TYPE_BUSN_CODE= 'MS'
 WHERE COST_CENTER_CODE = '75Q996';


COMMIT;

