
--Script to insert the column details
  INSERT INTO CCN_ADDITIONAL_AUDIT_FIELDS VALUES('HIERARCHY_DETAIL','STATEMENT_TYPE','VARCHAR2',3,100);
  INSERT INTO CCN_ADDITIONAL_AUDIT_FIELDS VALUES('HIERARCHY_DETAIL','EMPLOYEE_NAME','VARCHAR2',97,101);

--Script to insert the table details
  INSERT INTO CCN_AUDIT_EXCLUDED_TABLES VALUES('HIERARCHY_DESCRIPTION','Y');
  INSERT INTO CCN_AUDIT_EXCLUDED_TABLES VALUES('HIERARCHY_HEADER','Y');