/*
Below script will update the marketing mission code as per the excel provided by Jeffrey
Note* Init load process inserted marketing information for the belw Costcenters with MKT_SESSION Is NULL. Updating  MKT_MISSION which missing in the earlier update script(CC_MKT_MISSION_Update_ASP_1173.sql).

Created : sxg151 12/17/2018 CCN Project Team ASP-1173
Changed:
*/

SELECT * FROM MARKETING WHERE COST_CENTER_CODE = '708504' AND (MKT_MISSION <> 'FLR' OR MKT_MISSION IS NULL);
--1 Row(s) Selected
UPDATE MARKETING SET MKT_MISSION = 'FLR' WHERE COST_CENTER_CODE = '708504' AND (MKT_MISSION <> 'FLR' OR MKT_MISSION IS NULL);
--1 Row(s) Updated
SELECT * FROM MARKETING WHERE COST_CENTER_CODE = '708506' AND (MKT_MISSION <> 'FLR' OR MKT_MISSION IS NULL);
--1 Row(s) Selected
UPDATE MARKETING SET MKT_MISSION = 'FLR' WHERE COST_CENTER_CODE = '708506' AND (MKT_MISSION <> 'FLR' OR MKT_MISSION IS NULL);
--1 Row(s) Updated
SELECT * FROM MARKETING WHERE COST_CENTER_CODE = '701680' AND (MKT_MISSION <> 'IND' OR MKT_MISSION IS NULL);
--1 Row(s) Selected
UPDATE MARKETING SET MKT_MISSION = 'IND' WHERE COST_CENTER_CODE = '701680' AND (MKT_MISSION <> 'IND' OR MKT_MISSION IS NULL);
--1 Row(s) Updated
SELECT * FROM MARKETING WHERE COST_CENTER_CODE = '701766' AND (MKT_MISSION <> 'FLR' OR MKT_MISSION IS NULL);
--1 Row(s) Selected
UPDATE MARKETING SET MKT_MISSION = 'FLR' WHERE COST_CENTER_CODE = '701766' AND (MKT_MISSION <> 'FLR' OR MKT_MISSION IS NULL);
--1 Row(s) Updated
SELECT * FROM MARKETING WHERE COST_CENTER_CODE = '701836' AND (MKT_MISSION <> 'FLR' OR MKT_MISSION IS NULL);
--1 Row(s) Selected
UPDATE MARKETING SET MKT_MISSION = 'FLR' WHERE COST_CENTER_CODE = '701836' AND (MKT_MISSION <> 'FLR' OR MKT_MISSION IS NULL);
--1 Row(s) Updated
SELECT * FROM MARKETING WHERE COST_CENTER_CODE = '702607' AND (MKT_MISSION <> 'FLR' OR MKT_MISSION IS NULL);
--1 Row(s) Selected
UPDATE MARKETING SET MKT_MISSION = 'FLR' WHERE COST_CENTER_CODE = '702607' AND (MKT_MISSION <> 'FLR' OR MKT_MISSION IS NULL);
--1 Row(s) Updated
SELECT * FROM MARKETING WHERE COST_CENTER_CODE = '702822' AND (MKT_MISSION <> 'FLR' OR MKT_MISSION IS NULL);
--1 Row(s) Selected
UPDATE MARKETING SET MKT_MISSION = 'FLR' WHERE COST_CENTER_CODE = '702822' AND (MKT_MISSION <> 'FLR' OR MKT_MISSION IS NULL);
--1 Row(s) Updated
SELECT * FROM MARKETING WHERE COST_CENTER_CODE = '702926' AND (MKT_MISSION <> 'FLR' OR MKT_MISSION IS NULL);
--1 Row(s) Selected
UPDATE MARKETING SET MKT_MISSION = 'FLR' WHERE COST_CENTER_CODE = '702926' AND (MKT_MISSION <> 'FLR' OR MKT_MISSION IS NULL);
--1 Row(s) Updated
SELECT * FROM MARKETING WHERE COST_CENTER_CODE = '703421' AND (MKT_MISSION <> 'IND' OR MKT_MISSION IS NULL);
--1 Row(s) Selected
UPDATE MARKETING SET MKT_MISSION = 'IND' WHERE COST_CENTER_CODE = '703421' AND (MKT_MISSION <> 'IND' OR MKT_MISSION IS NULL);
--1 Row(s) Updated
SELECT * FROM MARKETING WHERE COST_CENTER_CODE = '703434' AND (MKT_MISSION <> 'IND' OR MKT_MISSION IS NULL);
--1 Row(s) Selected
UPDATE MARKETING SET MKT_MISSION = 'IND' WHERE COST_CENTER_CODE = '703434' AND (MKT_MISSION <> 'IND' OR MKT_MISSION IS NULL);
--1 Row(s) Updated
SELECT * FROM MARKETING WHERE COST_CENTER_CODE = '703456' AND (MKT_MISSION <> 'FLR' OR MKT_MISSION IS NULL);
--1 Row(s) Selected
UPDATE MARKETING SET MKT_MISSION = 'FLR' WHERE COST_CENTER_CODE = '703456' AND (MKT_MISSION <> 'FLR' OR MKT_MISSION IS NULL);
--1 Row(s) Updated
SELECT * FROM MARKETING WHERE COST_CENTER_CODE = '703492' AND (MKT_MISSION <> 'FLR' OR MKT_MISSION IS NULL);
--1 Row(s) Selected
UPDATE MARKETING SET MKT_MISSION = 'FLR' WHERE COST_CENTER_CODE = '703492' AND (MKT_MISSION <> 'FLR' OR MKT_MISSION IS NULL);
--1 Row(s) Updated
SELECT * FROM MARKETING WHERE COST_CENTER_CODE = '703500' AND (MKT_MISSION <> 'FLR' OR MKT_MISSION IS NULL);
--1 Row(s) Selected
UPDATE MARKETING SET MKT_MISSION = 'FLR' WHERE COST_CENTER_CODE = '703500' AND (MKT_MISSION <> 'FLR' OR MKT_MISSION IS NULL);
--1 Row(s) Updated
SELECT * FROM MARKETING WHERE COST_CENTER_CODE = '703580' AND (MKT_MISSION <> 'FLR' OR MKT_MISSION IS NULL);
--1 Row(s) Selected
UPDATE MARKETING SET MKT_MISSION = 'FLR' WHERE COST_CENTER_CODE = '703580' AND (MKT_MISSION <> 'FLR' OR MKT_MISSION IS NULL);
--1 Row(s) Updated
SELECT * FROM MARKETING WHERE COST_CENTER_CODE = '703946' AND (MKT_MISSION <> 'FLR' OR MKT_MISSION IS NULL);
--1 Row(s) Selected
UPDATE MARKETING SET MKT_MISSION = 'FLR' WHERE COST_CENTER_CODE = '703946' AND (MKT_MISSION <> 'FLR' OR MKT_MISSION IS NULL);
--1 Row(s) Updated
SELECT * FROM MARKETING WHERE COST_CENTER_CODE = '705388' AND (MKT_MISSION <> 'FLR' OR MKT_MISSION IS NULL);
--1 Row(s) Selected
UPDATE MARKETING SET MKT_MISSION = 'FLR' WHERE COST_CENTER_CODE = '705388' AND (MKT_MISSION <> 'FLR' OR MKT_MISSION IS NULL);
--1 Row(s) Updated
SELECT * FROM MARKETING WHERE COST_CENTER_CODE = '708576' AND (MKT_MISSION <> 'FLR' OR MKT_MISSION IS NULL);
--1 Row(s) Selected
UPDATE MARKETING SET MKT_MISSION = 'FLR' WHERE COST_CENTER_CODE = '708576' AND (MKT_MISSION <> 'FLR' OR MKT_MISSION IS NULL);
--1 Row(s) Updated
SELECT * FROM MARKETING WHERE COST_CENTER_CODE = '708596' AND (MKT_MISSION <> 'FLR' OR MKT_MISSION IS NULL);
--1 Row(s) Selected
UPDATE MARKETING SET MKT_MISSION = 'FLR' WHERE COST_CENTER_CODE = '708596' AND (MKT_MISSION <> 'FLR' OR MKT_MISSION IS NULL);
--1 Row(s) Updated
SELECT * FROM MARKETING WHERE COST_CENTER_CODE = '708663' AND (MKT_MISSION <> 'FLR' OR MKT_MISSION IS NULL);
--1 Row(s) Selected
UPDATE MARKETING SET MKT_MISSION = 'FLR' WHERE COST_CENTER_CODE = '708663' AND (MKT_MISSION <> 'FLR' OR MKT_MISSION IS NULL);
--1 Row(s) Updated
SELECT * FROM MARKETING WHERE COST_CENTER_CODE = '708677' AND (MKT_MISSION <> 'FLR' OR MKT_MISSION IS NULL);
--1 Row(s) Selected
UPDATE MARKETING SET MKT_MISSION = 'FLR' WHERE COST_CENTER_CODE = '708677' AND (MKT_MISSION <> 'FLR' OR MKT_MISSION IS NULL);
--1 Row(s) Updated
SELECT * FROM MARKETING WHERE COST_CENTER_CODE = '708699' AND (MKT_MISSION <> 'IND' OR MKT_MISSION IS NULL);
--1 Row(s) Selected
UPDATE MARKETING SET MKT_MISSION = 'IND' WHERE COST_CENTER_CODE = '708699' AND (MKT_MISSION <> 'IND' OR MKT_MISSION IS NULL);
--1 Row(s) Updated
SELECT * FROM MARKETING WHERE COST_CENTER_CODE = '708960' AND (MKT_MISSION <> 'IND' OR MKT_MISSION IS NULL);
--1 Row(s) Selected
UPDATE MARKETING SET MKT_MISSION = 'IND' WHERE COST_CENTER_CODE = '708960' AND (MKT_MISSION <> 'IND' OR MKT_MISSION IS NULL);
--1 Row(s) Updated
SELECT * FROM MARKETING WHERE COST_CENTER_CODE = '708978' AND (MKT_MISSION <> 'FLR' OR MKT_MISSION IS NULL);
--1 Row(s) Selected
UPDATE MARKETING SET MKT_MISSION = 'FLR' WHERE COST_CENTER_CODE = '708978' AND (MKT_MISSION <> 'FLR' OR MKT_MISSION IS NULL);
--1 Row(s) Updated
SELECT * FROM MARKETING WHERE COST_CENTER_CODE = '722307' AND (MKT_MISSION <> 'IND' OR MKT_MISSION IS NULL);
--1 Row(s) Selected
UPDATE MARKETING SET MKT_MISSION = 'IND' WHERE COST_CENTER_CODE = '722307' AND (MKT_MISSION <> 'IND' OR MKT_MISSION IS NULL);
--1 Row(s) Updated
SELECT * FROM MARKETING WHERE COST_CENTER_CODE = '724333' AND (MKT_MISSION <> 'IND' OR MKT_MISSION IS NULL);
--1 Row(s) Selected
UPDATE MARKETING SET MKT_MISSION = 'IND' WHERE COST_CENTER_CODE = '724333' AND (MKT_MISSION <> 'IND' OR MKT_MISSION IS NULL);
--1 Row(s) Updated

COMMIT;