/*******************************************************************************************************************************************
COST_CENTER_TERR_NAME_CHANGE_SEP_16.sql
Created:  09/29/2016 AXK326
          This script is executed to UPDATE the following:
          1. COST_CENTER_NAME column from COST_CENTER table
          2. TERRITORY_TYPE_BUSN_CODE column from TERRITOPRY table
*******************************************************************************************************************************************/
BEGIN
    CCN_BATCH_PKG.LOCK_DATABASE_SP();
END;
/

-- COST_CENTER table COST_CENTER_NAME column update
/*
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = '' WHERE COST_CENTER_CODE = '';
--1 Row(s) Updated
*/

SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '754819';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'CLEVELAND COMM REP' WHERE COST_CENTER_CODE = '754819';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '756618';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'CLEVELAND MULTI SEG REP' WHERE COST_CENTER_CODE = '756618';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '756078';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'DETROIT MULTI SEG REP' WHERE COST_CENTER_CODE = '756078';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '756864';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'NORTHERN MICHIGAN MULTI SEG REP' WHERE COST_CENTER_CODE = '756864';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '754174';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'SEATTLE COMM REP' WHERE COST_CENTER_CODE = '754174';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '756287';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'SEATTLE COMM REP' WHERE COST_CENTER_CODE = '756287';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '756874';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'SEATTLE COMM REP' WHERE COST_CENTER_CODE = '756874';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '757922';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'SEATTLE COMM REP' WHERE COST_CENTER_CODE = '757922';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '754171';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'PORTLAND MULTI SEG REP' WHERE COST_CENTER_CODE = '754171';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '756875';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'PORTLAND MULTI SEG REP' WHERE COST_CENTER_CODE = '756875';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '754229';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'MONTANA MULTI SEG REP' WHERE COST_CENTER_CODE = '754229';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '756677';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'CASCADE RES REPAINT REP' WHERE COST_CENTER_CODE = '756677';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q008';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'TRI-CITIES MULTI SEG REP' WHERE COST_CENTER_CODE = '75Q008';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '756039';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'TRI-CITIES COMM REP' WHERE COST_CENTER_CODE = '756039';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q326';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'GREEN BAY MULTI SEG REP' WHERE COST_CENTER_CODE = '75Q326';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '756089';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'MILWAUKEE COMM REP' WHERE COST_CENTER_CODE = '756089';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '754169';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'CHICAGO METRO MULTI SEG REP' WHERE COST_CENTER_CODE = '754169';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '754607';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'CHICAGO METRO MULTI SEG REP' WHERE COST_CENTER_CODE = '754607';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '756006';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'CENTRAL IL RES REPAINT REP' WHERE COST_CENTER_CODE = '756006';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '756457';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'INDIANAPOLIS RES REPAINT REP' WHERE COST_CENTER_CODE = '756457';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '756794';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'INDIANAPOLIS MULTI SEG REP' WHERE COST_CENTER_CODE = '756794';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '756120';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'FORT WAYNE COMM REP' WHERE COST_CENTER_CODE = '756120';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '754154';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'CEDAR RAPIDS MULTI SEG REP' WHERE COST_CENTER_CODE = '754154';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q424';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'BOSTON MULTI SEG REP' WHERE COST_CENTER_CODE = '75Q424';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q422';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'NORTHEAST PA RES REPAINT REP' WHERE COST_CENTER_CODE = '75Q422';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '754064';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'NORTHEAST PA PROP MGMT REP' WHERE COST_CENTER_CODE = '754064';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '758311';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'NORTHEAST PA RES REPAINT REP' WHERE COST_CENTER_CODE = '758311';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '756607';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'UPSTATE NY PROP MGMT REP' WHERE COST_CENTER_CODE = '756607';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '755623';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'RICHMOND MULTI SEG REP' WHERE COST_CENTER_CODE = '755623';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '754506';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'BALTIMORE MULTI SEG REP' WHERE COST_CENTER_CODE = '754506';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '754036';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'CAPITAL COMM REP' WHERE COST_CENTER_CODE = '754036';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '755553';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'CAPITAL RES REPAINT REP' WHERE COST_CENTER_CODE = '755553';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '755555';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'CAPITAL MULTI SEG REP' WHERE COST_CENTER_CODE = '755555';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '754621';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'METRO CONNECTICUT COMM REP' WHERE COST_CENTER_CODE = '754621';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '755911';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'METRO NEW YORK PROP MGMT REP' WHERE COST_CENTER_CODE = '755911';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '756523';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'METRO NEW YORK MULTI SEG REP' WHERE COST_CENTER_CODE = '756523';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '756919';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'METRO NEW YORK MULTI SEG REP' WHERE COST_CENTER_CODE = '756919';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '756066';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'LONG ISLAND MULTI SEG REP' WHERE COST_CENTER_CODE = '756066';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '758462';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'LONG ISLAND MULTI SEG REP' WHERE COST_CENTER_CODE = '758462';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q408';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'DELMAR MULTI SEG REP' WHERE COST_CENTER_CODE = '75Q408';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '754507';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'DELMAR RES REPAINT REP' WHERE COST_CENTER_CODE = '754507';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '755542';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'DELMAR MULTI SEG REP' WHERE COST_CENTER_CODE = '755542';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '756832';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'NEW JERSEY COASTAL MULTI SEG REP' WHERE COST_CENTER_CODE = '756832';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '754119';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'PHILADELPHIA MULTI SEG REP' WHERE COST_CENTER_CODE = '754119';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '754497';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'PHILADELPHIA PROP MGMT REP' WHERE COST_CENTER_CODE = '754497';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '755901';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'PHILADELPHIA RES REPAINT REP' WHERE COST_CENTER_CODE = '755901';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '756922';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'PHILADELPHIA MULTI SEG REP' WHERE COST_CENTER_CODE = '756922';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '758494';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'PHILADELPHIA RES REPAINT REP' WHERE COST_CENTER_CODE = '758494';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '754511';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'PITTSBURGH MULTI SEG REP' WHERE COST_CENTER_CODE = '754511';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '754853';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'PITTSBURGH NEW RES REP' WHERE COST_CENTER_CODE = '754853';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '754216';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'RALEIGH METRO MULTI SEG REP' WHERE COST_CENTER_CODE = '754216';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '756512';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'RALEIGH METRO COMM REP' WHERE COST_CENTER_CODE = '756512';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '755727';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'CHARLOTTE METRO MULTI SEG REP' WHERE COST_CENTER_CODE = '755727';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '757834';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'COLUMBIA COMM REP' WHERE COST_CENTER_CODE = '757834';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '757871';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'COLUMBIA MULTI SEG REP' WHERE COST_CENTER_CODE = '757871';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '754058';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'CHARLESTON METRO NEW RES REP' WHERE COST_CENTER_CODE = '754058';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '754446';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'CHARLESTON METRO COMM REP' WHERE COST_CENTER_CODE = '754446';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '754554';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'CHARLESTON METRO COMM REP' WHERE COST_CENTER_CODE = '754554';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '755652';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'GREENSBORO MULTI SEG REP' WHERE COST_CENTER_CODE = '755652';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '754578';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WILMINGTON MULTI SEG REP' WHERE COST_CENTER_CODE = '754578';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '756479';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WILMINGTON MULTI SEG REP' WHERE COST_CENTER_CODE = '756479';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q543';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'ATLANTA MULTI SEG REP' WHERE COST_CENTER_CODE = '75Q543';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '754219';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'ATLANTA MULTI SEG REP' WHERE COST_CENTER_CODE = '754219';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '754957';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'ATLANTA MULTI SEG REP' WHERE COST_CENTER_CODE = '754957';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '755743';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'ATLANTA NEW RES REP' WHERE COST_CENTER_CODE = '755743';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '755774';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'ATLANTA MULTI SEG REP' WHERE COST_CENTER_CODE = '755774';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '755793';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'ATLANTA PROP MGMT REP' WHERE COST_CENTER_CODE = '755793';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '755913';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'GULF COAST PROP MGMT REP' WHERE COST_CENTER_CODE = '755913';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '756049';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'GULF COAST NEW RES REP' WHERE COST_CENTER_CODE = '756049';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q211';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'SOUTHWEST FL METRO PROP MGMT REP' WHERE COST_CENTER_CODE = '75Q211';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '754444';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'SOUTHWEST FL METRO RES REPAINT REP' WHERE COST_CENTER_CODE = '754444';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '756176';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'SOUTHWEST FL METRO MULTI SEG REP' WHERE COST_CENTER_CODE = '756176';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '758374';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'SOUTHWEST FLORIDA METRO NEW RES REP' WHERE COST_CENTER_CODE = '758374';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q539';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'SOUTH FLORIDA METRO MULTI SEG REP' WHERE COST_CENTER_CODE = '75Q539';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '754061';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'SOUTH FLORIDA METRO COMM REP' WHERE COST_CENTER_CODE = '754061';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '756808';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'SOUTH FLORIDA METRO MULTI SEG REP' WHERE COST_CENTER_CODE = '756808';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q209';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'TAMPA PROP MGMT REP' WHERE COST_CENTER_CODE = '75Q209';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q220';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'TAMPA PROP MGMT REP' WHERE COST_CENTER_CODE = '75Q220';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q524';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'TAMPA PROP MGMT REP' WHERE COST_CENTER_CODE = '75Q524';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '754425';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'TAMPA PROP MGMT REP' WHERE COST_CENTER_CODE = '754425';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '754400';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'FLORIDA PANHANDLE MULTI SEG REP' WHERE COST_CENTER_CODE = '754400';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '757815';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'JACKSONVILLE PROP MGMT REP' WHERE COST_CENTER_CODE = '757815';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '754095';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'ORLANDO COMM REP' WHERE COST_CENTER_CODE = '754095';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '758440';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'ORLANDO MULTI SEG REP' WHERE COST_CENTER_CODE = '758440';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '754421';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'PUERTO RICO PROP MGMT REP' WHERE COST_CENTER_CODE = '754421';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '754599';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'PUERTO RICO RES REPAINT REP' WHERE COST_CENTER_CODE = '754599';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '754688';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'PUERTO RICO RES REPAINT REP' WHERE COST_CENTER_CODE = '754688';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '754903';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'PUERTO RICO COMM REP' WHERE COST_CENTER_CODE = '754903';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '755791';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'PUERTO RICO PROP MGMT REP' WHERE COST_CENTER_CODE = '755791';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '756026';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'PUERTO RICO PROP MGMT REP' WHERE COST_CENTER_CODE = '756026';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '756779';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'PUERTO RICO PROP MGMT REP' WHERE COST_CENTER_CODE = '756779';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q510';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'CARIBBEAN MULTI SEG REP' WHERE COST_CENTER_CODE = '75Q510';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '756716';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'CARIBBEAN COMM REP' WHERE COST_CENTER_CODE = '756716';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '757930';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'CARIBBEAN COMM REP' WHERE COST_CENTER_CODE = '757930';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '757958';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'CARIBBEAN MULTI SEG REP' WHERE COST_CENTER_CODE = '757958';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '754864';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'MEMPHIS COMM REP' WHERE COST_CENTER_CODE = '754864';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '756125';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'MEMPHIS MULTI SEG REP' WHERE COST_CENTER_CODE = '756125';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '756363';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'JACKSON MULTI SEG REP' WHERE COST_CENTER_CODE = '756363';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '756643';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'LOUISIANA MULTI SEG REP' WHERE COST_CENTER_CODE = '756643';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q636';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'AUSTIN MULTI SEG REP' WHERE COST_CENTER_CODE = '75Q636';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '758396';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'AUSTIN RES REPAINT REP' WHERE COST_CENTER_CODE = '758396';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '754469';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'HOUSTON RES REPAINT REP' WHERE COST_CENTER_CODE = '754469';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q064';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'CALIFORNIA NORTH COMM REP' WHERE COST_CENTER_CODE = '75Q064';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '754768';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'CALIFORNIA NORTH RES REPAINT REP' WHERE COST_CENTER_CODE = '754768';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q068';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'CALIFORNIA CENTRAL MULTI SEG REP' WHERE COST_CENTER_CODE = '75Q068';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q601';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'CALIFORNIA CENTRAL MULTI SEG REP' WHERE COST_CENTER_CODE = '75Q601';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q611';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'CALIFORNIA BAY RES REPAINT REP' WHERE COST_CENTER_CODE = '75Q611';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '754776';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'CALIFORNIA BAY COMM REP' WHERE COST_CENTER_CODE = '754776';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '755889';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'CALIFORNIA BAY PROP MGMT REP' WHERE COST_CENTER_CODE = '755889';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '755893';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'CALIFORNIA BAY MULTI SEG REP' WHERE COST_CENTER_CODE = '755893';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '756336';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'CALIFORNIA BAY MULTI SEG REP' WHERE COST_CENTER_CODE = '756336';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q045';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'LOS ANGELES RES REPAINT REP' WHERE COST_CENTER_CODE = '75Q045';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q096';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'LOS ANGELES MULTI SEG REP' WHERE COST_CENTER_CODE = '75Q096';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q105';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'LOS ANGELES MULTI SEG REP' WHERE COST_CENTER_CODE = '75Q105';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '754965';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'LOS ANGELES MULTI SEG REP' WHERE COST_CENTER_CODE = '754965';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '757873';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'HAWAII MULTI SEG REP' WHERE COST_CENTER_CODE = '757873';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q033';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'CAL COAST MULTI SEG REP' WHERE COST_CENTER_CODE = '75Q033';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q644';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'CAL COAST MULTI SEG REP' WHERE COST_CENTER_CODE = '75Q644';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q044';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'SAN FERNANDO RES REPAINT REP' WHERE COST_CENTER_CODE = '75Q044';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q055';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'SAN FERNANDO PROP MGMT REP' WHERE COST_CENTER_CODE = '75Q055';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '757932';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'SAN FERNANDO MULTI SEG REP' WHERE COST_CENTER_CODE = '757932';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q138';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'DALLAS-FT WORTH RES REPAINT REP' WHERE COST_CENTER_CODE = '75Q138';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q181';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'NEW MEXICO RES REPAINT REP' WHERE COST_CENTER_CODE = '75Q181';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q182';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'EL PASO NEW RES REP' WHERE COST_CENTER_CODE = '75Q182';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q185';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'EL PASO RES REPAINT REP' WHERE COST_CENTER_CODE = '75Q185';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q112';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'NORTHERN COLORADO COMM REP' WHERE COST_CENTER_CODE = '75Q112';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q117';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'NORTHERN COLORADO PROP MGMT REP' WHERE COST_CENTER_CODE = '75Q117';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '754665';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'NORTHERN COLORADO COMM REP' WHERE COST_CENTER_CODE = '754665';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '754669';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'NORTHERN COLORADO RES REPAINT REP' WHERE COST_CENTER_CODE = '754669';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q113';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'DENVER RES REPAINT REP' WHERE COST_CENTER_CODE = '75Q113';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q119';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'DENVER COMM REP' WHERE COST_CENTER_CODE = '75Q119';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q131';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'DENVER MULTI SEG REP' WHERE COST_CENTER_CODE = '75Q131';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q134';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'DENVER RES REPAINT REP' WHERE COST_CENTER_CODE = '75Q134';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '754261';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'DENVER PROP MGMT REP' WHERE COST_CENTER_CODE = '754261';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q174';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'SALT LAKE CITY RES REPAINT REP' WHERE COST_CENTER_CODE = '75Q174';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '754651';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'SALT LAKE CITY MULTI SEG REP' WHERE COST_CENTER_CODE = '754651';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '757773';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'SALT LAKE CITY NEW RES REP' WHERE COST_CENTER_CODE = '757773';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '755853';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'PHOENIX COMM REP' WHERE COST_CENTER_CODE = '755853';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q056';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'LAS VEGAS RES REPAINT REP' WHERE COST_CENTER_CODE = '75Q056';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q024';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'ARIZONA MULTI SEG REP' WHERE COST_CENTER_CODE = '75Q024';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '756817';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'MIDWEST MULTI SEG REP' WHERE COST_CENTER_CODE = '756817';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '756521';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'TEXARKANA MULTI SEG REP' WHERE COST_CENTER_CODE = '756521';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '76Q284';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'SOUTHWEST ONTARIO PROP MGMT REP' WHERE COST_CENTER_CODE = '76Q284';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '768340';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'QUEBEC MULTI SEG REP' WHERE COST_CENTER_CODE = '768340';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '76Q859';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'EASTERN CANADA MULTI SEG REP' WHERE COST_CENTER_CODE = '76Q859';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '766310';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'EASTERN CANADA COMM REP' WHERE COST_CENTER_CODE = '766310';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '76Q273';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'TORONTO METRO NEW RES REP' WHERE COST_CENTER_CODE = '76Q273';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '766185';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'TORONTO METRO RES REPAINT REP' WHERE COST_CENTER_CODE = '766185';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '768312';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'TORONTO METRO MULTI SEG REP' WHERE COST_CENTER_CODE = '768312';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '76Q233';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'VANCOUVER MULTI SEG REP' WHERE COST_CENTER_CODE = '76Q233';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '76Q242';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'VANCOUVER COMM REP' WHERE COST_CENTER_CODE = '76Q242';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '76Q252';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'NORTHERN ALBERTA COMM REP' WHERE COST_CENTER_CODE = '76Q252';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '76Q254';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'NORTHERN ALBERTA RES REPAINT REP' WHERE COST_CENTER_CODE = '76Q254';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '76Q255';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'NORTHERN ALBERTA RES REPAINT REP' WHERE COST_CENTER_CODE = '76Q255';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '764226';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'NORTHERN ALBERTA RES REPAINT REP' WHERE COST_CENTER_CODE = '764226';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '766590';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'NORTHERN ALBERTA NEW RES REP' WHERE COST_CENTER_CODE = '766590';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '76Q259';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'SOUTHERN ALBERTA PROP MGMT REP' WHERE COST_CENTER_CODE = '76Q259';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '76Q323';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'SASKMAN COMM REP' WHERE COST_CENTER_CODE = '76Q323';
--1 Row(s) Updated
SELECT COST_CENTER_NAME FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q659';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'CAL COAST PROP MGMT REP' WHERE COST_CENTER_CODE = '75Q659';
--1 Row(s) Updated
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
-- TERRITORY table TERRITORY_TYPE_BUSN_CODE column update
/*
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = '' WHERE COST_CENTER_CODE = '';
--1 Row(s) Updated

Business Rules : The value used in TERRITORY_TYPE_BUSN_CODE column should be present in CODE_DETAIL table
SELECT *
  FROM CODE_DETAIL
 WHERE CODE_DETAIL.CODE_HEADER_NAME  = 'TERRITORY_TYPE_BUSN_CODE'
   AND CODE_DETAIL.CODE_DETAIL_VALUE IN ('CM', 'MS', 'RR', 'PM', 'NR');
*/

SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '754819';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'CM' WHERE COST_CENTER_CODE = '754819';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '756618';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '756618';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '756078';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '756078';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '756864';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '756864';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '754174';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'CM' WHERE COST_CENTER_CODE = '754174';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '756287';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'CM' WHERE COST_CENTER_CODE = '756287';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '756874';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'CM' WHERE COST_CENTER_CODE = '756874';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '757922';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'CM' WHERE COST_CENTER_CODE = '757922';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '754171';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '754171';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '756875';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '756875';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '754229';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '754229';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '756677';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '756677';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '75Q008';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '75Q008';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '756039';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'CM' WHERE COST_CENTER_CODE = '756039';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '75Q326';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '75Q326';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '756089';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'CM' WHERE COST_CENTER_CODE = '756089';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '754169';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '754169';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '754607';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '754607';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '756006';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '756006';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '756457';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '756457';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '756794';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '756794';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '756120';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'CM' WHERE COST_CENTER_CODE = '756120';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '754154';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '754154';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '75Q424';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '75Q424';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '75Q422';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '75Q422';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '754064';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'PM' WHERE COST_CENTER_CODE = '754064';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '758311';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '758311';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '756607';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'PM' WHERE COST_CENTER_CODE = '756607';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '755623';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '755623';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '754506';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '754506';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '754036';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'CM' WHERE COST_CENTER_CODE = '754036';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '755553';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '755553';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '755555';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '755555';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '754621';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'CM' WHERE COST_CENTER_CODE = '754621';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '755911';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'PM' WHERE COST_CENTER_CODE = '755911';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '756523';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '756523';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '756919';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '756919';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '756066';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '756066';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '758462';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '758462';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '75Q408';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '75Q408';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '754507';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '754507';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '755542';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '755542';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '756832';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '756832';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '754119';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '754119';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '754497';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'PM' WHERE COST_CENTER_CODE = '754497';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '755901';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '755901';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '756922';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '756922';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '758494';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '758494';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '754511';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '754511';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '754853';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'NR' WHERE COST_CENTER_CODE = '754853';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '754216';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '754216';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '756512';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'CM' WHERE COST_CENTER_CODE = '756512';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '755727';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '755727';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '757834';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'CM' WHERE COST_CENTER_CODE = '757834';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '757871';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '757871';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '754058';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'NR' WHERE COST_CENTER_CODE = '754058';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '754446';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'CM' WHERE COST_CENTER_CODE = '754446';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '754554';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'CM' WHERE COST_CENTER_CODE = '754554';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '755652';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '755652';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '754578';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '754578';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '756479';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '756479';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '75Q543';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '75Q543';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '754219';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '754219';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '754957';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '754957';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '755743';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'NR' WHERE COST_CENTER_CODE = '755743';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '755774';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '755774';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '755793';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'PM' WHERE COST_CENTER_CODE = '755793';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '755913';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'PM' WHERE COST_CENTER_CODE = '755913';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '756049';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'NR' WHERE COST_CENTER_CODE = '756049';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '75Q211';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'PM' WHERE COST_CENTER_CODE = '75Q211';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '754444';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '754444';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '756176';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '756176';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '758374';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'NR' WHERE COST_CENTER_CODE = '758374';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '75Q539';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '75Q539';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '754061';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'CM' WHERE COST_CENTER_CODE = '754061';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '756808';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '756808';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '75Q209';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'PM' WHERE COST_CENTER_CODE = '75Q209';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '75Q220';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'PM' WHERE COST_CENTER_CODE = '75Q220';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '75Q524';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'PM' WHERE COST_CENTER_CODE = '75Q524';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '754425';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'PM' WHERE COST_CENTER_CODE = '754425';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '754400';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '754400';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '757815';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'PM' WHERE COST_CENTER_CODE = '757815';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '754095';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'CM' WHERE COST_CENTER_CODE = '754095';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '758440';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '758440';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '754421';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'PM' WHERE COST_CENTER_CODE = '754421';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '754599';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '754599';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '754688';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '754688';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '754903';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'CM' WHERE COST_CENTER_CODE = '754903';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '755791';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'PM' WHERE COST_CENTER_CODE = '755791';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '756026';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'PM' WHERE COST_CENTER_CODE = '756026';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '756779';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'PM' WHERE COST_CENTER_CODE = '756779';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '75Q510';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '75Q510';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '756716';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'CM' WHERE COST_CENTER_CODE = '756716';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '757930';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'CM' WHERE COST_CENTER_CODE = '757930';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '757958';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '757958';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '754864';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'CM' WHERE COST_CENTER_CODE = '754864';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '756125';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '756125';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '756363';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '756363';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '756643';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '756643';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '75Q636';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '75Q636';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '758396';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '758396';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '754469';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '754469';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '75Q064';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'CM' WHERE COST_CENTER_CODE = '75Q064';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '754768';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '754768';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '75Q068';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '75Q068';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '75Q601';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '75Q601';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '75Q611';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '75Q611';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '754776';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'CM' WHERE COST_CENTER_CODE = '754776';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '755889';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'PM' WHERE COST_CENTER_CODE = '755889';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '755893';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '755893';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '756336';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '756336';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '75Q045';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '75Q045';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '75Q096';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '75Q096';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '75Q105';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '75Q105';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '754965';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '754965';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '757873';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '757873';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '75Q033';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '75Q033';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '75Q644';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '75Q644';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '75Q044';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '75Q044';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '75Q055';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'PM' WHERE COST_CENTER_CODE = '75Q055';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '757932';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '757932';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '75Q138';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '75Q138';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '75Q181';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '75Q181';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '75Q182';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'NR' WHERE COST_CENTER_CODE = '75Q182';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '75Q185';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '75Q185';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '75Q112';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'CM' WHERE COST_CENTER_CODE = '75Q112';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '75Q117';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'PM' WHERE COST_CENTER_CODE = '75Q117';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '754665';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'CM' WHERE COST_CENTER_CODE = '754665';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '754669';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '754669';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '75Q113';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '75Q113';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '75Q119';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'CM' WHERE COST_CENTER_CODE = '75Q119';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '75Q131';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '75Q131';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '75Q134';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '75Q134';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '754261';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'PM' WHERE COST_CENTER_CODE = '754261';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '75Q174';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '75Q174';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '754651';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '754651';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '757773';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'NR' WHERE COST_CENTER_CODE = '757773';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '755853';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'CM' WHERE COST_CENTER_CODE = '755853';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '75Q056';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '75Q056';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '75Q024';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '75Q024';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '756817';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '756817';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '756521';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '756521';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '76Q284';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'PM' WHERE COST_CENTER_CODE = '76Q284';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '768340';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '768340';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '76Q859';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '76Q859';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '766310';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'CM' WHERE COST_CENTER_CODE = '766310';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '76Q273';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'NR' WHERE COST_CENTER_CODE = '76Q273';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '766185';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '766185';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '768312';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '768312';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '76Q233';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '76Q233';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '76Q242';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'CM' WHERE COST_CENTER_CODE = '76Q242';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '76Q252';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'CM' WHERE COST_CENTER_CODE = '76Q252';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '76Q254';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '76Q254';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '76Q255';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '76Q255';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '764226';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '764226';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '766590';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'NR' WHERE COST_CENTER_CODE = '766590';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '76Q259';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'PM' WHERE COST_CENTER_CODE = '76Q259';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '76Q323';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'CM' WHERE COST_CENTER_CODE = '76Q323';
--1 Row(s) Updated
SELECT TERRITORY_TYPE_BUSN_CODE FROM TERRITORY WHERE COST_CENTER_CODE = '75Q659';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'PM' WHERE COST_CENTER_CODE = '75Q659';
--1 Row(s) Updated

COMMIT;

BEGIN
    CCN_BATCH_PKG.UNLOCK_DATABASE_SP();
END;
/
