--Create a new code header : STATE_CODE_INT
INSERT INTO CODE_HEADER VALUES('STATE_CODE_INT','COD','STATE CODE INTERNATIONAL',NULL,NULL,NULL,2,NULL,NULL,NULL);

--Create a new code details for header STATE_CODE_INT
--INSERT INTO CODE_DETAIL VALUES('STATE_CODE_INT','COD','99999','',NULL,NULL,NULL,1,NULL,NULL);
INSERT INTO CODE_DETAIL VALUES('STATE_CODE_INT','COD','AN','NETHERLANDS ANTILLES',NULL,NULL,NULL,1,NULL,NULL);
INSERT INTO CODE_DETAIL VALUES('STATE_CODE_INT','COD','AW','ARUBA',NULL,NULL,NULL,2,NULL,NULL);
INSERT INTO CODE_DETAIL VALUES('STATE_CODE_INT','COD','CW','CURACAO',NULL,NULL,NULL,3,NULL,NULL);
INSERT INTO CODE_DETAIL VALUES('STATE_CODE_INT','COD','FL','FLORIDA',NULL,NULL,NULL,4,NULL,NULL);
INSERT INTO CODE_DETAIL VALUES('STATE_CODE_INT','COD','GD','GRENADA',NULL,NULL,NULL,5,NULL,NULL);
INSERT INTO CODE_DETAIL VALUES('STATE_CODE_INT','COD','JM','JAMAICA',NULL,NULL,NULL,6,NULL,NULL);
INSERT INTO CODE_DETAIL VALUES('STATE_CODE_INT','COD','TR','TRINIDAD',NULL,NULL,NULL,7,NULL,NULL);

COMMIT;