--Correcting the special characters that creeped into the hierarchy_detail description
SET DEFINE OFF;
SELECT * FROM HIERARCHY_DETAIL WHERE HRCHY_DTL_DESC LIKE '%&amp%';
SELECT * FROM HIERARCHY_DETAIL WHERE HRCHY_DTL_CURR_LVL_VAL = '0101080710';
UPDATE HIERARCHY_DETAIL SET HRCHY_DTL_DESC = 'P&M CANADA  EASTERN REPS' WHERE HRCHY_DTL_CURR_LVL_VAL = '0101080710';
SELECT * FROM HIERARCHY_DETAIL WHERE HRCHY_DTL_CURR_LVL_VAL = '0101080711';
UPDATE HIERARCHY_DETAIL SET HRCHY_DTL_DESC = 'P&M CANADA WESTERN REPS' WHERE HRCHY_DTL_CURR_LVL_VAL = '0101080711';