/********************************************************************************
Below script will insert new code_header and code_detail values for
STANDARD and PRIMARY cost center 

Created : 08/25/2016 AXK326 CCN Project Team....
Modified: 
********************************************************************************/
-- CODE_HEADER
REM INSERTING into CODE_HEADER
SET DEFINE OFF;
Insert into CODE_HEADER (CODE_HEADER_NAME,CODE_HEADER_TYPE,CODE_HEADER_DESCRIPTION,CODE_HEADER_EXPIRE_FLAG,CODE_HEADER_EXPIRE_USER,CODE_HEADER_EXPIRE_EFF_DATE,CODE_HEADER_DTL_VAL_SIZE,CODE_HEADER_DTL_VAL_DEFAULT,CODE_HEADER_CREATE_USER,CODE_HEADER_EFF_DATE,CODE_HEADER_IDENTIFIER) values ('STD_COST_IDENTIFIER','COD','STANDARD COST IDENTIFIER',null,null,null,2,null,null,null,null);
Insert into CODE_HEADER (CODE_HEADER_NAME,CODE_HEADER_TYPE,CODE_HEADER_DESCRIPTION,CODE_HEADER_EXPIRE_FLAG,CODE_HEADER_EXPIRE_USER,CODE_HEADER_EXPIRE_EFF_DATE,CODE_HEADER_DTL_VAL_SIZE,CODE_HEADER_DTL_VAL_DEFAULT,CODE_HEADER_CREATE_USER,CODE_HEADER_EFF_DATE,CODE_HEADER_IDENTIFIER) values ('PRIM_COST_IDENTIFIER','COD','PRIMARY COST IDENTIFIER',null,null,null,2,null,null,null,null);
COMMIT;

-- CODE_DETAIL
REM INSERTING into CODE_DETAIL
SET DEFINE OFF;
Insert into CODE_DETAIL (CODE_HEADER_NAME,CODE_HEADER_TYPE,CODE_DETAIL_VALUE,CODE_DETAIL_DESCRIPTION,CODE_DETAIL_EXPIRE_FLAG,CODE_DETAIL_EXPIRE_USER,CODE_DETAIL_EXPIRE_EFF_DATE,CODE_DETAIL_ID,CODE_DETAIL_CREATE_USER,CODE_DETAIL_EFF_DATE) values ('STD_COST_IDENTIFIER','COD','01','STANDARD COST IDENTIFIER',null,null,null,1,null,null);
Insert into CODE_DETAIL (CODE_HEADER_NAME,CODE_HEADER_TYPE,CODE_DETAIL_VALUE,CODE_DETAIL_DESCRIPTION,CODE_DETAIL_EXPIRE_FLAG,CODE_DETAIL_EXPIRE_USER,CODE_DETAIL_EXPIRE_EFF_DATE,CODE_DETAIL_ID,CODE_DETAIL_CREATE_USER,CODE_DETAIL_EFF_DATE) values ('STD_COST_IDENTIFIER','COD','08','STANDARD COST IDENTIFIER',null,null,null,2,null,null);
Insert into CODE_DETAIL (CODE_HEADER_NAME,CODE_HEADER_TYPE,CODE_DETAIL_VALUE,CODE_DETAIL_DESCRIPTION,CODE_DETAIL_EXPIRE_FLAG,CODE_DETAIL_EXPIRE_USER,CODE_DETAIL_EXPIRE_EFF_DATE,CODE_DETAIL_ID,CODE_DETAIL_CREATE_USER,CODE_DETAIL_EFF_DATE) values ('PRIM_COST_IDENTIFIER','COD','01','PRIMARY COST IDENTIFIER',null,null,null,1,null,null);
Insert into CODE_DETAIL (CODE_HEADER_NAME,CODE_HEADER_TYPE,CODE_DETAIL_VALUE,CODE_DETAIL_DESCRIPTION,CODE_DETAIL_EXPIRE_FLAG,CODE_DETAIL_EXPIRE_USER,CODE_DETAIL_EXPIRE_EFF_DATE,CODE_DETAIL_ID,CODE_DETAIL_CREATE_USER,CODE_DETAIL_EFF_DATE) values ('PRIM_COST_IDENTIFIER','COD','08','PRIMARY COST IDENTIFIER',null,null,null,2,null,null);
COMMIT;

