/*
Below scripts will reopen the closed admin cost centers as we found an issue that is 
not allowing users to complete the transaction from UI

Created : jxc517 CCN Project Team....
*/
SELECT COST_CENTER_CODE, COST_CENTER_NAME, OPEN_DATE, CLOSE_DATE, CURRENCY_CODE FROM COST_CENTER WHERE COST_CENTER_CODE = '820286';
SELECT COST_CENTER_CODE, COST_CENTER_NAME, OPEN_DATE, CLOSE_DATE, CURRENCY_CODE FROM COST_CENTER WHERE COST_CENTER_CODE = '76A286';
SELECT * FROM STATUS WHERE COST_CENTER_CODE = '820286' AND EXPIRATION_DATE IS NULL;
SELECT * FROM STATUS WHERE COST_CENTER_CODE = '76A286' AND EXPIRATION_DATE IS NULL;

UPDATE COST_CENTER SET COST_CENTER_NAME = 'ONTARIO DRIVER SPECIALIST', OPEN_DATE = '13-SEP-2019', CLOSE_DATE = NULL, CURRENCY_CODE = 'CAD' WHERE COST_CENTER_CODE = '820286';
UPDATE COST_CENTER SET COST_CENTER_NAME = 'ONTARIO DRIVER SPECIALIST', OPEN_DATE = '13-SEP-2019', CLOSE_DATE = NULL, CURRENCY_CODE = 'CAD' WHERE COST_CENTER_CODE = '76A286';
UPDATE STATUS SET EXPIRATION_DATE = '12-SEP-2019' WHERE COST_CENTER_CODE = '820286' AND EXPIRATION_DATE IS NULL;
INSERT INTO STATUS VALUES ('820286','9','13-SEP-2019',NULL);
UPDATE STATUS SET EXPIRATION_DATE = '12-SEP-2019' WHERE COST_CENTER_CODE = '76A286' AND EXPIRATION_DATE IS NULL;
INSERT INTO STATUS VALUES ('76A286','9','13-SEP-2019',NULL);

SELECT COST_CENTER_CODE, COST_CENTER_NAME, OPEN_DATE, CLOSE_DATE FROM COST_CENTER WHERE COST_CENTER_CODE = '820286';
SELECT COST_CENTER_CODE, COST_CENTER_NAME, OPEN_DATE, CLOSE_DATE FROM COST_CENTER WHERE COST_CENTER_CODE = '76A286';
SELECT * FROM STATUS WHERE COST_CENTER_CODE = '820286' AND EXPIRATION_DATE IS NULL;
SELECT * FROM STATUS WHERE COST_CENTER_CODE = '76A286' AND EXPIRATION_DATE IS NULL;

COMMIT;