/*
Created : nxk927 04/17/2018
          Closing cost center 707144 with the status code of 5 and closed date of 26-DEC-2017.

*/

SET SERVEROUTPUT ON;
BEGIN
    CCN_BATCH_PKG.LOCK_DATABASE_SP();
    COMMON_TOOLS.ALTER_ALL_TRIGGERS('DISABLE');
END;
/

SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '707144';

UPDATE COST_CENTER
   SET CLOSE_DATE = '26-DEC-2017'
 WHERE COST_CENTER_CODE = '707144';
/

SELECT * FROM STATUS WHERE COST_CENTER_CODE = '707144';

UPDATE STATUS
   SET STATUS_CODE = '5', 
       EXPIRATION_DATE = '26-DEC-2017'
 WHERE COST_CENTER_CODE = '707144';

COMMIT;
/
BEGIN
    COMMON_TOOLS.ALTER_ALL_TRIGGERS('ENABLE');
    CCN_BATCH_PKG.UNLOCK_DATABASE_SP();
END;
/
