/********************************************************************************
Below script will insert into CODE_HEADER for Credit Hierarchy

Created : 03/14/2016 sxh487 CCN Project Team....
Modified:
********************************************************************************/
SET DEFINE OFF;
Insert into CODE_HEADER (CODE_HEADER_NAME,CODE_HEADER_TYPE,CODE_HEADER_DESCRIPTION,CODE_HEADER_EXPIRE_FLAG,CODE_HEADER_EXPIRE_USER,CODE_HEADER_EXPIRE_EFF_DATE,CODE_HEADER_DTL_VAL_SIZE,CODE_HEADER_DTL_VAL_DEFAULT,CODE_HEADER_CREATE_USER,CODE_HEADER_EFF_DATE) values ('RCM','COD','CREDIT HIERARCHY RCM NUMBER','N',null,null,2,null,null,trunc(SYSDATE));
Insert into CODE_HEADER (CODE_HEADER_NAME,CODE_HEADER_TYPE,CODE_HEADER_DESCRIPTION,CODE_HEADER_EXPIRE_FLAG,CODE_HEADER_EXPIRE_USER,CODE_HEADER_EXPIRE_EFF_DATE,CODE_HEADER_DTL_VAL_SIZE,CODE_HEADER_DTL_VAL_DEFAULT,CODE_HEADER_CREATE_USER,CODE_HEADER_EFF_DATE) values ('DCM','COD','CREDIT HIERARCHY DCM NUMBER','N',null,null,2,null,null,trunc(SYSDATE));
Insert into CODE_HEADER (CODE_HEADER_NAME,CODE_HEADER_TYPE,CODE_HEADER_DESCRIPTION,CODE_HEADER_EXPIRE_FLAG,CODE_HEADER_EXPIRE_USER,CODE_HEADER_EXPIRE_EFF_DATE,CODE_HEADER_DTL_VAL_SIZE,CODE_HEADER_DTL_VAL_DEFAULT,CODE_HEADER_CREATE_USER,CODE_HEADER_EFF_DATE) values ('ACM','COD','CREDIT HIERARCHY ACM NUMBER','N',null,null,2,null,null,trunc(SYSDATE));
Insert into CODE_HEADER (CODE_HEADER_NAME,CODE_HEADER_TYPE,CODE_HEADER_DESCRIPTION,CODE_HEADER_EXPIRE_FLAG,CODE_HEADER_EXPIRE_USER,CODE_HEADER_EXPIRE_EFF_DATE,CODE_HEADER_DTL_VAL_SIZE,CODE_HEADER_DTL_VAL_DEFAULT,CODE_HEADER_CREATE_USER,CODE_HEADER_EFF_DATE) values ('SYSOUT','COD','CREDIT HIERARCHY SYSOUT CODE','N',null,null,6,null,null,trunc(SYSDATE));

COMMIT;
