/********************************************************************************
Below script will insert into CRDT_HIER_DCM_LOOKUP for Credit Hierarchy

Created : 03/14/2016 sxh487 CCN Project Team....
Modified:
********************************************************************************/
SET DEFINE OFF;
Insert into CRDT_HIER_DCM_LOOKUP (DCM_NBR,DCM_NAME,DCM_VAL) values ('01','CLEVELAND I','D.J. Ash');
Insert into CRDT_HIER_DCM_LOOKUP (DCM_NBR,DCM_NAME,DCM_VAL) values ('02','ENFIELD I','G.M. Patterson');
Insert into CRDT_HIER_DCM_LOOKUP (DCM_NBR,DCM_NAME,DCM_VAL) values ('04','CHICAGO I','W.A. Zimmer');
Insert into CRDT_HIER_DCM_LOOKUP (DCM_NBR,DCM_NAME,DCM_VAL) values ('05','SOUTH BEND','T.E. Peterson');
Insert into CRDT_HIER_DCM_LOOKUP (DCM_NBR,DCM_NAME,DCM_VAL) values ('06','GENERAL POLYMERS-CLOSED','R.P. Draper');
Insert into CRDT_HIER_DCM_LOOKUP (DCM_NBR,DCM_NAME,DCM_VAL) values ('07','DENVER','B.M. Delgado');
Insert into CRDT_HIER_DCM_LOOKUP (DCM_NBR,DCM_NAME,DCM_VAL) values ('08','HOUSTON-SOUTH','B.E. Kolterjahn');
Insert into CRDT_HIER_DCM_LOOKUP (DCM_NBR,DCM_NAME,DCM_VAL) values ('09','BELTSVILLE I','L.R. Ramus');
Insert into CRDT_HIER_DCM_LOOKUP (DCM_NBR,DCM_NAME,DCM_VAL) values ('10','NEW ORLEANS','E.A. Pennington');
Insert into CRDT_HIER_DCM_LOOKUP (DCM_NBR,DCM_NAME,DCM_VAL) values ('12','SACRAMENTO','N.L. Williams');
Insert into CRDT_HIER_DCM_LOOKUP (DCM_NBR,DCM_NAME,DCM_VAL) values ('13','BELTSVILLE II','M.L. Edwards');
Insert into CRDT_HIER_DCM_LOOKUP (DCM_NBR,DCM_NAME,DCM_VAL) values ('14','TENNESSEE','B.N. Holden');
Insert into CRDT_HIER_DCM_LOOKUP (DCM_NBR,DCM_NAME,DCM_VAL) values ('15','CHARLOTTE','M.E. Kimmer');
Insert into CRDT_HIER_DCM_LOOKUP (DCM_NBR,DCM_NAME,DCM_VAL) values ('16','FLOORCOVERING','L.M. Joyner');
Insert into CRDT_HIER_DCM_LOOKUP (DCM_NBR,DCM_NAME,DCM_VAL) values ('17','ATLANTA II','J.C. Moore');
Insert into CRDT_HIER_DCM_LOOKUP (DCM_NBR,DCM_NAME,DCM_VAL) values ('18','ATLANTA I','A.R. Lockett');
Insert into CRDT_HIER_DCM_LOOKUP (DCM_NBR,DCM_NAME,DCM_VAL) values ('19','NORTH FLORIDA','J. Nappi');
Insert into CRDT_HIER_DCM_LOOKUP (DCM_NBR,DCM_NAME,DCM_VAL) values ('20','RALEIGH','E.A. Coats');
Insert into CRDT_HIER_DCM_LOOKUP (DCM_NBR,DCM_NAME,DCM_VAL) values ('22','ENFIELD II','D.W. Dolbow');
Insert into CRDT_HIER_DCM_LOOKUP (DCM_NBR,DCM_NAME,DCM_VAL) values ('23','DURON POT B/D 0187','L.R. Ramus');
Insert into CRDT_HIER_DCM_LOOKUP (DCM_NBR,DCM_NAME,DCM_VAL) values ('24','BETHLEHEM I','R.C. McDevitt');
Insert into CRDT_HIER_DCM_LOOKUP (DCM_NBR,DCM_NAME,DCM_VAL) values ('26','BELTSVILLE III','P.F. Childress');
Insert into CRDT_HIER_DCM_LOOKUP (DCM_NBR,DCM_NAME,DCM_VAL) values ('28','BETHLEHEM IV','K.J. Russell');
Insert into CRDT_HIER_DCM_LOOKUP (DCM_NBR,DCM_NAME,DCM_VAL) values ('30','LESSER ANTILLES','R.M. Johnson');
Insert into CRDT_HIER_DCM_LOOKUP (DCM_NBR,DCM_NAME,DCM_VAL) values ('32','CC CANADA 0850','E.J. Thibodeau');
Insert into CRDT_HIER_DCM_LOOKUP (DCM_NBR,DCM_NAME,DCM_VAL) values ('33','CC 0860','R.A. Paul');
Insert into CRDT_HIER_DCM_LOOKUP (DCM_NBR,DCM_NAME,DCM_VAL) values ('34','CC 0868','S.S. Gerardot');
Insert into CRDT_HIER_DCM_LOOKUP (DCM_NBR,DCM_NAME,DCM_VAL) values ('35','CC CAN-DURACOAT 0869','E.J. Thibodeau');
Insert into CRDT_HIER_DCM_LOOKUP (DCM_NBR,DCM_NAME,DCM_VAL) values ('36','PORTLAND I','C.D. Andresen');
Insert into CRDT_HIER_DCM_LOOKUP (DCM_NBR,DCM_NAME,DCM_VAL) values ('37','OKLAHOMA','L.A. Jones');
Insert into CRDT_HIER_DCM_LOOKUP (DCM_NBR,DCM_NAME,DCM_VAL) values ('38','CC 0870','R.C. McDevitt');
Insert into CRDT_HIER_DCM_LOOKUP (DCM_NBR,DCM_NAME,DCM_VAL) values ('39','CC 0878','L.R. Ramus');
Insert into CRDT_HIER_DCM_LOOKUP (DCM_NBR,DCM_NAME,DCM_VAL) values ('40','KING OF PRUSSIA I','S.L. Getz');
Insert into CRDT_HIER_DCM_LOOKUP (DCM_NBR,DCM_NAME,DCM_VAL) values ('42','HOUSTON-CENTRAL','A.C. Kebodeaux');
Insert into CRDT_HIER_DCM_LOOKUP (DCM_NBR,DCM_NAME,DCM_VAL) values ('43','CC 0858','R.L. Cullins');
Insert into CRDT_HIER_DCM_LOOKUP (DCM_NBR,DCM_NAME,DCM_VAL) values ('44','MINNEAPOLIS I','M.T. Pommier');
Insert into CRDT_HIER_DCM_LOOKUP (DCM_NBR,DCM_NAME,DCM_VAL) values ('45','EAST LOS ANGELES','C.R. Bottero');
Insert into CRDT_HIER_DCM_LOOKUP (DCM_NBR,DCM_NAME,DCM_VAL) values ('46','CC 0889','R.L. Cullins');
Insert into CRDT_HIER_DCM_LOOKUP (DCM_NBR,DCM_NAME,DCM_VAL) values ('48','CC 0890','L.L. Van Fleet');
Insert into CRDT_HIER_DCM_LOOKUP (DCM_NBR,DCM_NAME,DCM_VAL) values ('49','CC 0898','T.F. Knapp');
Insert into CRDT_HIER_DCM_LOOKUP (DCM_NBR,DCM_NAME,DCM_VAL) values ('50','AUTOMOTIVE','P.R. Campbell');
Insert into CRDT_HIER_DCM_LOOKUP (DCM_NBR,DCM_NAME,DCM_VAL) values ('51','AUTOMOTIVE CANADA','K.L. Hensley');
Insert into CRDT_HIER_DCM_LOOKUP (DCM_NBR,DCM_NAME,DCM_VAL) values ('52','NATIONAL ACCTG CNTR','K.M. Fein');
Insert into CRDT_HIER_DCM_LOOKUP (DCM_NBR,DCM_NAME,DCM_VAL) values ('53','KANSAS CITY','OPEN');
Insert into CRDT_HIER_DCM_LOOKUP (DCM_NBR,DCM_NAME,DCM_VAL) values ('54','LEXINGTON','S.G. Young');
Insert into CRDT_HIER_DCM_LOOKUP (DCM_NBR,DCM_NAME,DCM_VAL) values ('55','CLEVELAND III','D.E. Bransford');
Insert into CRDT_HIER_DCM_LOOKUP (DCM_NBR,DCM_NAME,DCM_VAL) values ('56','VANCOUVER','L. Botten');
Insert into CRDT_HIER_DCM_LOOKUP (DCM_NBR,DCM_NAME,DCM_VAL) values ('57','MISSISSAUGA','E.J. Thibodeau');
Insert into CRDT_HIER_DCM_LOOKUP (DCM_NBR,DCM_NAME,DCM_VAL) values ('58','SAN ANTONIO','G.A. Francis');
Insert into CRDT_HIER_DCM_LOOKUP (DCM_NBR,DCM_NAME,DCM_VAL) values ('59','TAMPA','C.D. Nickens');
Insert into CRDT_HIER_DCM_LOOKUP (DCM_NBR,DCM_NAME,DCM_VAL) values ('60','DALLAS SOUTH','P.P. Reed');
Insert into CRDT_HIER_DCM_LOOKUP (DCM_NBR,DCM_NAME,DCM_VAL) values ('61','PHOENIX','K. Oswald');
Insert into CRDT_HIER_DCM_LOOKUP (DCM_NBR,DCM_NAME,DCM_VAL) values ('62','CHEM CTGS DIRECT 0160','S.J. Schirripa');
Insert into CRDT_HIER_DCM_LOOKUP (DCM_NBR,DCM_NAME,DCM_VAL) values ('63','COOK PAINT 0159-CLOSED','R.P. Draper');
Insert into CRDT_HIER_DCM_LOOKUP (DCM_NBR,DCM_NAME,DCM_VAL) values ('64','MILWAUKEE','D.W. Van Hoorne');
Insert into CRDT_HIER_DCM_LOOKUP (DCM_NBR,DCM_NAME,DCM_VAL) values ('65','DETROIT','M.E. Kline');
Insert into CRDT_HIER_DCM_LOOKUP (DCM_NBR,DCM_NAME,DCM_VAL) values ('66','BETHLEHEM III','A.E. Schmidt');
Insert into CRDT_HIER_DCM_LOOKUP (DCM_NBR,DCM_NAME,DCM_VAL) values ('67','BETHLEHEM II','J.A. Gutekunst');
Insert into CRDT_HIER_DCM_LOOKUP (DCM_NBR,DCM_NAME,DCM_VAL) values ('69','ALABAMA','S. Gittons');
Insert into CRDT_HIER_DCM_LOOKUP (DCM_NBR,DCM_NAME,DCM_VAL) values ('71','PAINT & COATINGS','P.C. Waugh');
Insert into CRDT_HIER_DCM_LOOKUP (DCM_NBR,DCM_NAME,DCM_VAL) values ('72','CENTRAL FLORIDA','M.R. Mumey');
Insert into CRDT_HIER_DCM_LOOKUP (DCM_NBR,DCM_NAME,DCM_VAL) values ('75','COMEX US','T.F. Knapp');
Insert into CRDT_HIER_DCM_LOOKUP (DCM_NBR,DCM_NAME,DCM_VAL) values ('77','CAL BAY/CENTRAL','C.E. Gonzales');
Insert into CRDT_HIER_DCM_LOOKUP (DCM_NBR,DCM_NAME,DCM_VAL) values ('78','PITTSBURGH II','E.M. Peters');
Insert into CRDT_HIER_DCM_LOOKUP (DCM_NBR,DCM_NAME,DCM_VAL) values ('79','CHARLESTON','S.A. Engstrom');
Insert into CRDT_HIER_DCM_LOOKUP (DCM_NBR,DCM_NAME,DCM_VAL) values ('80','SAN DIEGO','L.D. Chappell');
Insert into CRDT_HIER_DCM_LOOKUP (DCM_NBR,DCM_NAME,DCM_VAL) values ('81','MW DIV-DIRECT SALES','R.P. Draper');
Insert into CRDT_HIER_DCM_LOOKUP (DCM_NBR,DCM_NAME,DCM_VAL) values ('82','E DIV -DIRECT SALES','R.P. Draper');
Insert into CRDT_HIER_DCM_LOOKUP (DCM_NBR,DCM_NAME,DCM_VAL) values ('83','SE DIV-DIRECT SALES','R.P. Draper');
Insert into CRDT_HIER_DCM_LOOKUP (DCM_NBR,DCM_NAME,DCM_VAL) values ('84','SW DIV-DIRECT SALES','R.P. Draper');
Insert into CRDT_HIER_DCM_LOOKUP (DCM_NBR,DCM_NAME,DCM_VAL) values ('85','SEATTLE','S. Read');
Insert into CRDT_HIER_DCM_LOOKUP (DCM_NBR,DCM_NAME,DCM_VAL) values ('86','MISSISSIPPI','F.E. Harris');
Insert into CRDT_HIER_DCM_LOOKUP (DCM_NBR,DCM_NAME,DCM_VAL) values ('87','HIGHWAY DIRECT SALES','R.P. Draper');
Insert into CRDT_HIER_DCM_LOOKUP (DCM_NBR,DCM_NAME,DCM_VAL) values ('88','AUTOMOTIVE AIRCRAFT','K.L. Hensley');
Insert into CRDT_HIER_DCM_LOOKUP (DCM_NBR,DCM_NAME,DCM_VAL) values ('89','EAST USA POWDER BUS','E.J. Thibodeau');
Insert into CRDT_HIER_DCM_LOOKUP (DCM_NBR,DCM_NAME,DCM_VAL) values ('91','ARIZONA','J.C. Barnes');
Insert into CRDT_HIER_DCM_LOOKUP (DCM_NBR,DCM_NAME,DCM_VAL) values ('92','WEST LOS ANGELES','C. Bitzer');
Insert into CRDT_HIER_DCM_LOOKUP (DCM_NBR,DCM_NAME,DCM_VAL) values ('93','DALLAS N/FT WORTH','D.R. Amidon');
Insert into CRDT_HIER_DCM_LOOKUP (DCM_NBR,DCM_NAME,DCM_VAL) values ('95','CEDAR FALLS II','A.L. Johnson');
Insert into CRDT_HIER_DCM_LOOKUP (DCM_NBR,DCM_NAME,DCM_VAL) values ('96','S FLORIDA/PR','V.I. Vizcarra (Moran)');

COMMIT;
