/********************************************************************************
Below script will insert into CRDT_HIER_ACM_LOOKUP for Credit Hierarchy

Created : 03/14/2016 sxh487 CCN Project Team....
Modified:
********************************************************************************/
SET DEFINE OFF;
Insert into CRDT_HIER_ACM_LOOKUP (ACM_NBR,ACM_NAME,ACM_VAL) values ('11','MW CREDIT AREA','GERARDOT');
Insert into CRDT_HIER_ACM_LOOKUP (ACM_NBR,ACM_NAME,ACM_VAL) values ('13','MW CREDIT AREA','PAUL');
Insert into CRDT_HIER_ACM_LOOKUP (ACM_NBR,ACM_NAME,ACM_VAL) values ('15','MID-WESTERN-DIV CTL','DIRECT');
Insert into CRDT_HIER_ACM_LOOKUP (ACM_NBR,ACM_NAME,ACM_VAL) values ('21','EA CREDIT AREA','MCDEVITT');
Insert into CRDT_HIER_ACM_LOOKUP (ACM_NBR,ACM_NAME,ACM_VAL) values ('23','EA CREDIT AREA','RAMUS');
Insert into CRDT_HIER_ACM_LOOKUP (ACM_NBR,ACM_NAME,ACM_VAL) values ('24','EASTERN-DIV CTL','DIRECT');
Insert into CRDT_HIER_ACM_LOOKUP (ACM_NBR,ACM_NAME,ACM_VAL) values ('28','EASTERN-FLOORCVR AREA',null);
Insert into CRDT_HIER_ACM_LOOKUP (ACM_NBR,ACM_NAME,ACM_VAL) values ('32','SE CREDIT AREA','CULLINS');
Insert into CRDT_HIER_ACM_LOOKUP (ACM_NBR,ACM_NAME,ACM_VAL) values ('34','SE DURON POTENTIAL B/D',null);
Insert into CRDT_HIER_ACM_LOOKUP (ACM_NBR,ACM_NAME,ACM_VAL) values ('35','SOUTHEASTERN-FLOORCVR AREA',null);
Insert into CRDT_HIER_ACM_LOOKUP (ACM_NBR,ACM_NAME,ACM_VAL) values ('37','SOUTHEASTERN-UNITED AREA',null);
Insert into CRDT_HIER_ACM_LOOKUP (ACM_NBR,ACM_NAME,ACM_VAL) values ('38','SOUTHEASTERN-DIV CTL','DIRECT');
Insert into CRDT_HIER_ACM_LOOKUP (ACM_NBR,ACM_NAME,ACM_VAL) values ('39','SE CREDIT AREA','LOUISIANA');
Insert into CRDT_HIER_ACM_LOOKUP (ACM_NBR,ACM_NAME,ACM_VAL) values ('42','SW CREDIT AREA','LEEPER');
Insert into CRDT_HIER_ACM_LOOKUP (ACM_NBR,ACM_NAME,ACM_VAL) values ('45','SOUTHWESTERN-DIV CTL','DIRECT');
Insert into CRDT_HIER_ACM_LOOKUP (ACM_NBR,ACM_NAME,ACM_VAL) values ('47','SW CREDIT AREA','KNAPP');
Insert into CRDT_HIER_ACM_LOOKUP (ACM_NBR,ACM_NAME,ACM_VAL) values ('51','CC CREDIT AREA','GERARDOT');
Insert into CRDT_HIER_ACM_LOOKUP (ACM_NBR,ACM_NAME,ACM_VAL) values ('52','CC CREDIT AREA','MCDEVITT');
Insert into CRDT_HIER_ACM_LOOKUP (ACM_NBR,ACM_NAME,ACM_VAL) values ('53','CC CREDIT AREA','CULLINS');
Insert into CRDT_HIER_ACM_LOOKUP (ACM_NBR,ACM_NAME,ACM_VAL) values ('54','CC CREDIT AREA','KNAPP');
Insert into CRDT_HIER_ACM_LOOKUP (ACM_NBR,ACM_NAME,ACM_VAL) values ('55','CC CREDIT AREA','LEEPER');
Insert into CRDT_HIER_ACM_LOOKUP (ACM_NBR,ACM_NAME,ACM_VAL) values ('56','CC CREDIT AREA','GERARDOT');
Insert into CRDT_HIER_ACM_LOOKUP (ACM_NBR,ACM_NAME,ACM_VAL) values ('57','CC CREDIT AREA','RAMUS');
Insert into CRDT_HIER_ACM_LOOKUP (ACM_NBR,ACM_NAME,ACM_VAL) values ('61','NATIONAL BILLED ACCTS AREA',null);
Insert into CRDT_HIER_ACM_LOOKUP (ACM_NBR,ACM_NAME,ACM_VAL) values ('65','COMEX US','DRAPER');
Insert into CRDT_HIER_ACM_LOOKUP (ACM_NBR,ACM_NAME,ACM_VAL) values ('67','COMEX CAN','DRAPER');
Insert into CRDT_HIER_ACM_LOOKUP (ACM_NBR,ACM_NAME,ACM_VAL) values ('69','HWY DIRECT SALES AREA',null);
Insert into CRDT_HIER_ACM_LOOKUP (ACM_NBR,ACM_NAME,ACM_VAL) values ('71','CHEM CTGS DIRECT',null);
Insert into CRDT_HIER_ACM_LOOKUP (ACM_NBR,ACM_NAME,ACM_VAL) values ('72','AUTOMOTIVE','CARUSO');
Insert into CRDT_HIER_ACM_LOOKUP (ACM_NBR,ACM_NAME,ACM_VAL) values ('73','GENERAL POLYMERS',null);
Insert into CRDT_HIER_ACM_LOOKUP (ACM_NBR,ACM_NAME,ACM_VAL) values ('74','PAINT & COATINGS','WAUGH');
Insert into CRDT_HIER_ACM_LOOKUP (ACM_NBR,ACM_NAME,ACM_VAL) values ('75','CAN DURACOAT CREDIT AREA',null);
Insert into CRDT_HIER_ACM_LOOKUP (ACM_NBR,ACM_NAME,ACM_VAL) values ('76','EAST USA POWDER BUSINESS',null);
Insert into CRDT_HIER_ACM_LOOKUP (ACM_NBR,ACM_NAME,ACM_VAL) values ('77','AUTO CANADA','CARUSO');
Insert into CRDT_HIER_ACM_LOOKUP (ACM_NBR,ACM_NAME,ACM_VAL) values ('81','CANADA-CREDIT AREA','WANSACK');
Insert into CRDT_HIER_ACM_LOOKUP (ACM_NBR,ACM_NAME,ACM_VAL) values ('82','CANADA-MW CREDIT AREA CLOSED',null);
Insert into CRDT_HIER_ACM_LOOKUP (ACM_NBR,ACM_NAME,ACM_VAL) values ('85','CAN CC CREDIT AREA','WANSACK');
Insert into CRDT_HIER_ACM_LOOKUP (ACM_NBR,ACM_NAME,ACM_VAL) values ('91','COOK PAINT & VARNISH',null);

COMMIT;
