/********************************************************************************
Below script will insert into CRDT_HIER_DCM_LOOKUP for Credit Hierarchy

Created : 03/14/2016 sxh487 CCN Project Team....
Modified: 07/27/2016 vxv336
********************************************************************************/
SET DEFINE OFF;
insert into CRDT_HIER_DCM_LOOKUP values(1,'01','ASH - CLEVELAND I','D.J. Ash');
insert into CRDT_HIER_DCM_LOOKUP values(2,'02','PATTERSON - ENFIELD I','G.M. Patterson');
insert into CRDT_HIER_DCM_LOOKUP values(3,'04','ZIMMER - CHICAGO I','W.A. Zimmer');
insert into CRDT_HIER_DCM_LOOKUP values(4,'05','PETERSON - SOUTH BEND','T.E. Peterson');
insert into CRDT_HIER_DCM_LOOKUP values(5,'06','CLOSED - GENERAL POLYMERS','R.P. Draper');
insert into CRDT_HIER_DCM_LOOKUP values(6,'07','BOTTERO - DENVER','C.R. BOTTERO');
insert into CRDT_HIER_DCM_LOOKUP values(7,'08','KOLTERJAHN - HOUSTON-SOUTH','B.E. Kolterjahn');
insert into CRDT_HIER_DCM_LOOKUP values(8,'09','RAMUS - BELTSVILLE I','L.R. Ramus');
insert into CRDT_HIER_DCM_LOOKUP values(9,'10','PENNINGTON - NEW ORLEANS','E.A. Pennington');
insert into CRDT_HIER_DCM_LOOKUP values(10,'12','WILLIAMS - SACRAMENTO','N.L. Williams');
insert into CRDT_HIER_DCM_LOOKUP values(11,'13','EDWARDS - BELTSVILLE II','M.L. Edwards');
insert into CRDT_HIER_DCM_LOOKUP values(12,'14','HOLDEN - TENNESSEE','B.N. Holden');
insert into CRDT_HIER_DCM_LOOKUP values(13,'15','KIMMER - CHARLOTTE','M.E. Kimmer');
insert into CRDT_HIER_DCM_LOOKUP values(14,'16','GITTONS - FLOORCOVERING','S. GITTONS');
insert into CRDT_HIER_DCM_LOOKUP values(15,'17','MOORE - ATLANTA II','J.C. Moore');
insert into CRDT_HIER_DCM_LOOKUP values(16,'18','LOCKETT - ATLANTA I','A.R. Lockett');
insert into CRDT_HIER_DCM_LOOKUP values(17,'19','NAPPI - NORTH FLORIDA','J. Nappi');
insert into CRDT_HIER_DCM_LOOKUP values(18,'20','COATS - RALEIGH','E.A. Coats');
insert into CRDT_HIER_DCM_LOOKUP values(19,'22','DOLBOW - ENFIELD II','D.W. Dolbow');
insert into CRDT_HIER_DCM_LOOKUP values(20,'23','RAMUS - DURON POT B/D 0187','L.R. Ramus');
insert into CRDT_HIER_DCM_LOOKUP values(21,'24','MCDEVITT - BETHLEHEM I','R.C. McDevitt');
insert into CRDT_HIER_DCM_LOOKUP values(22,'26','CHILDRESS - BELTSVILLE III','P.F. Childress');
insert into CRDT_HIER_DCM_LOOKUP values(23,'28','RUSSELL - BETHLEHEM IV','K.J. Russell');
insert into CRDT_HIER_DCM_LOOKUP values(24,'30','JOHNSON - LESSER ANTILLES','R.M. Johnson');
insert into CRDT_HIER_DCM_LOOKUP values(25,'32','THIBODEAU - CC CANADA 0850','E.J. Thibodeau');
insert into CRDT_HIER_DCM_LOOKUP values(26,'33','PAUL - CC 0860','R.A. Paul');
insert into CRDT_HIER_DCM_LOOKUP values(27,'34','GERARDOT - CC 0868','S.S. Gerardot');
insert into CRDT_HIER_DCM_LOOKUP values(28,'35','THIBODEAU-CC CAN-DURACOAT 0869','E.J. Thibodeau');
insert into CRDT_HIER_DCM_LOOKUP values(29,'36','ANDRESEN - PORTLAND I','C.D. Andresen');
insert into CRDT_HIER_DCM_LOOKUP values(30,'37','GREEN - OKLAHOMA','L.H. GREEN');
insert into CRDT_HIER_DCM_LOOKUP values(31,'38','MCDEVITT - CC 0870','R.C. McDevitt');
insert into CRDT_HIER_DCM_LOOKUP values(32,'39','RAMUS - CC 0878','L.R. Ramus');
insert into CRDT_HIER_DCM_LOOKUP values(33,'40','GETZ - KING OF PRUSSIA I','S.L. Getz');
insert into CRDT_HIER_DCM_LOOKUP values(34,'42','KEBODEAUX - HOUSTON-CENTRAL','A.C. Kebodeaux');
insert into CRDT_HIER_DCM_LOOKUP values(35,'43','CULLINS - CC 0858','R.L. Cullins');
insert into CRDT_HIER_DCM_LOOKUP values(36,'44','POMMIER - MINNEAPOLIS I','M.T. Pommier');
insert into CRDT_HIER_DCM_LOOKUP values(37,'46','CULLINS - CC 0889','R.L. Cullins');
insert into CRDT_HIER_DCM_LOOKUP values(38,'48','VAN FLEET - CC 0890','L.L. Van Fleet');
insert into CRDT_HIER_DCM_LOOKUP values(39,'49','KNAPP - CC 0898','T.F. Knapp');
insert into CRDT_HIER_DCM_LOOKUP values(40,'50','CAMPBELL - AUTOMOTIVE','P.R. Campbell');
insert into CRDT_HIER_DCM_LOOKUP values(41,'51','HENSLEY - AUTOMOTIVE CANADA','K.L. Hensley');
insert into CRDT_HIER_DCM_LOOKUP values(42,'52','NATIONAL ACCTG CNTR','K.M. Fein');
insert into CRDT_HIER_DCM_LOOKUP values(43,'53','WACHTLER - KANSAS CITY','P.J. Wachtler');
insert into CRDT_HIER_DCM_LOOKUP values(44,'54','YOUNG - LEXINGTON','S.G. Young');
insert into CRDT_HIER_DCM_LOOKUP values(45,'55','BRANSFORD - CLEVELAND III','D.E. Bransford');
insert into CRDT_HIER_DCM_LOOKUP values(46,'56','BOTTEN - VANCOUVER','L. Botten');
insert into CRDT_HIER_DCM_LOOKUP values(47,'57','THIBODEAU - MISSISSAUGA','E.J. Thibodeau');
insert into CRDT_HIER_DCM_LOOKUP values(48,'58','FRANCIS - SAN ANTONIO','G.A. Francis');
insert into CRDT_HIER_DCM_LOOKUP values(49,'59','NICKENS - TAMPA','C.D. Nickens');
insert into CRDT_HIER_DCM_LOOKUP values(50,'60','REED - DALLAS SOUTH','P.P. Reed');
insert into CRDT_HIER_DCM_LOOKUP values(51,'61','OSWALD - PHOENIX','K. Oswald');
insert into CRDT_HIER_DCM_LOOKUP values(52,'62','CHEM CTGS DIRECT 0160','S.J. Schirripa');
insert into CRDT_HIER_DCM_LOOKUP values(53,'63','CLOSED - COOK PAINT 0159','R.P. Draper');
insert into CRDT_HIER_DCM_LOOKUP values(54,'64','VAN HOORNE - MILWAUKEE','D.W. Van Hoorne');
insert into CRDT_HIER_DCM_LOOKUP values(55,'65','KLINE - DETROIT','M.E. Kline');
insert into CRDT_HIER_DCM_LOOKUP values(56,'66','SCHMIDT - BETHLEHEM III','A.E. Schmidt');
insert into CRDT_HIER_DCM_LOOKUP values(57,'67','GUTEKUNST - BETHLEHEM II','J.A. Gutekunst');
insert into CRDT_HIER_DCM_LOOKUP values(58,'69','TURRENS - ALABAMA','R. TURRENS');
insert into CRDT_HIER_DCM_LOOKUP values(59,'71','WAUGH - PAINT & COATINGS','P.C. Waugh');
insert into CRDT_HIER_DCM_LOOKUP values(60,'72','HARRIS - CENTRAL FLORIDA','F.E. HARRIS');
insert into CRDT_HIER_DCM_LOOKUP values(61,'75','KNAPP - COMEX US','T.F. Knapp');
insert into CRDT_HIER_DCM_LOOKUP values(62,'77','GONZALES - CAL BAY/CENTRAL','C.E. Gonzales');
insert into CRDT_HIER_DCM_LOOKUP values(63,'78','PETERS - PITTSBURGH II','E.M. Peters');
insert into CRDT_HIER_DCM_LOOKUP values(64,'79','ENGSTROM - CHARLESTON','S.A. Engstrom');
insert into CRDT_HIER_DCM_LOOKUP values(65,'80','CHAPPELL - SAN DIEGO','L.D. Chappell');
insert into CRDT_HIER_DCM_LOOKUP values(66,'81','MW DIV-DIRECT SALES','R.P. Draper');
insert into CRDT_HIER_DCM_LOOKUP values(67,'82','E DIV -DIRECT SALES','R.P. Draper');
insert into CRDT_HIER_DCM_LOOKUP values(68,'83','SE DIV-DIRECT SALES','R.P. Draper');
insert into CRDT_HIER_DCM_LOOKUP values(69,'84','SW DIV-DIRECT SALES','R.P. Draper');
insert into CRDT_HIER_DCM_LOOKUP values(70,'85','READ - SEATTLE','S. Read');
insert into CRDT_HIER_DCM_LOOKUP values(71,'86','LE - MISSISSIPPI','T. LE');
insert into CRDT_HIER_DCM_LOOKUP values(72,'87','HIGHWAY DIRECT SALES','R.P. Draper');
insert into CRDT_HIER_DCM_LOOKUP values(73,'88','HENSLEY - AUTOMOTIVE AIRCRAFT','K.L. Hensley');
insert into CRDT_HIER_DCM_LOOKUP values(74,'89','THIBODEAU-EAST USA POWDER BUS','E.J. Thibodeau');
insert into CRDT_HIER_DCM_LOOKUP values(75,'91','BARNES - ARIZONA','J.C. Barnes');
insert into CRDT_HIER_DCM_LOOKUP values(76,'92','BITZER - WEST LOS ANGELES','C. Bitzer');
insert into CRDT_HIER_DCM_LOOKUP values(77,'93','AMIDON - DALLAS N/FT WORTH','D.R. Amidon');
insert into CRDT_HIER_DCM_LOOKUP values(78,'95','JOHNSON - CEDAR FALLS II','A.L. Johnson');
insert into CRDT_HIER_DCM_LOOKUP values(79,'96','VIZCARRA-MORAN - S FLORIDA/PR','V.I. Vizcarra');

COMMIT;
