/*
Below script will delete cost center '75R425' from CCN

Created : 04/16/2019 jxc517 CCN Project Team....
*/
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE LIKE '%R425';

EXEC COMMON_TOOLS.DELETE_COST_CENTER('75R425'); 

SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE LIKE '%R425';

COMMIT;
