/*
Below script to delete HIERARCHY_DETAIL price district levels which are cost centers are not attached to them.

Created : 05/16/2017 sxp130 : ASP-788 Price district hierarchy : cleanup of unattached levels
Approx execution Time : 2 to 3 minutes based on the volume
*/

BEGIN
    CCN_BATCH_PKG.LOCK_DATABASE_SP();
END;
/

SET DEFINE OFF;  

BEGIN
 EXECUTE IMMEDIATE 'DROP TABLE HIERARCHY_DETAIL_BKP1';
EXCEPTION
WHEN OTHERS THEN
NULL;
END;
/

BEGIN
 EXECUTE IMMEDIATE 
'
CREATE TABLE HIERARCHY_DETAIL_BKP1 AS 
SELECT *   
FROM HIERARCHY_DETAIL A
WHERE HRCHY_HDR_NAME =''PRICE_DISTRICT''
  AND EXISTS
    (SELECT 1
     FROM
       (SELECT *
        FROM
          (SELECT HD.*,
                  CONNECT_BY_ISLEAF ISLEAF
           FROM HIERARCHY_DETAIL HD
           WHERE HRCHY_HDR_NAME =''PRICE_DISTRICT''
             AND CONNECT_BY_ISLEAF = 1
             START WITH HRCHY_DTL_LEVEL =1 
			 CONNECT BY PRIOR HRCHY_DTL_NEXT_LVL_VAL = HRCHY_DTL_CURR_LVL_VAL ) HD1
        WHERE NOT EXISTS
            (SELECT 1
             FROM COST_CENTER
             WHERE COST_CENTER.COST_CENTER_CODE = HD1.HRCHY_DTL_CURR_ROW_VAL) ) B
     WHERE 1=1
       AND NVL(A.HRCHY_HDR_NAME,''X'')         = NVL(B.HRCHY_HDR_NAME,''X'')
       AND NVL(A.HRCHY_DTL_LEVEL,''X'')        = NVL(B.HRCHY_DTL_LEVEL,''X'')
       AND NVL(A.HRCHY_DTL_PREV_LVL_VAL,''X'') = NVL(B.HRCHY_DTL_PREV_LVL_VAL,''X'')
       AND NVL(A.HRCHY_DTL_CURR_LVL_VAL,''X'') = NVL(B.HRCHY_DTL_CURR_LVL_VAL,''X'')
       AND NVL(A.HRCHY_DTL_NEXT_LVL_VAL,''X'') = NVL(B.HRCHY_DTL_NEXT_LVL_VAL,''X'')
       AND NVL(A.HRCHY_DTL_EFF_DATE,SYSDATE) = NVL(B.HRCHY_DTL_EFF_DATE,SYSDATE)
       AND NVL(A.HRCHY_DTL_EXP_DATE,SYSDATE) = NVL(B.HRCHY_DTL_EXP_DATE,SYSDATE)
       AND NVL(A.HRCHY_DTL_DESC,''X'')         = NVL(B.HRCHY_DTL_DESC,''X'')
       AND NVL(A.HRCHY_DTL_CURR_ROW_VAL,''X'') = NVL(B.HRCHY_DTL_CURR_ROW_VAL,''X'') )
';
EXCEPTION
WHEN OTHERS THEN
NULL;
END;
/

DELETE  
FROM HIERARCHY_DETAIL A
WHERE HRCHY_HDR_NAME ='PRICE_DISTRICT'
  AND EXISTS
    (SELECT 1
     FROM
       (SELECT *
        FROM
          (SELECT HD.*,
                  CONNECT_BY_ISLEAF ISLEAF
           FROM HIERARCHY_DETAIL HD
           WHERE HRCHY_HDR_NAME ='PRICE_DISTRICT'
             AND CONNECT_BY_ISLEAF = 1
             START WITH HRCHY_DTL_LEVEL =1 
			 CONNECT BY PRIOR HRCHY_DTL_NEXT_LVL_VAL = HRCHY_DTL_CURR_LVL_VAL ) HD1
        WHERE NOT EXISTS
            (SELECT 1
             FROM COST_CENTER
             WHERE COST_CENTER.COST_CENTER_CODE = HD1.HRCHY_DTL_CURR_ROW_VAL) ) B
     WHERE 1=1
       AND NVL(A.HRCHY_HDR_NAME,'X')         = NVL(B.HRCHY_HDR_NAME,'X')
       AND NVL(A.HRCHY_DTL_LEVEL,'X')        = NVL(B.HRCHY_DTL_LEVEL,'X')
       AND NVL(A.HRCHY_DTL_PREV_LVL_VAL,'X') = NVL(B.HRCHY_DTL_PREV_LVL_VAL,'X')
       AND NVL(A.HRCHY_DTL_CURR_LVL_VAL,'X') = NVL(B.HRCHY_DTL_CURR_LVL_VAL,'X')
       AND NVL(A.HRCHY_DTL_NEXT_LVL_VAL,'X') = NVL(B.HRCHY_DTL_NEXT_LVL_VAL,'X')
       AND NVL(A.HRCHY_DTL_EFF_DATE,SYSDATE) = NVL(B.HRCHY_DTL_EFF_DATE,SYSDATE)
       AND NVL(A.HRCHY_DTL_EXP_DATE,SYSDATE) = NVL(B.HRCHY_DTL_EXP_DATE,SYSDATE)
       AND NVL(A.HRCHY_DTL_DESC,'X')         = NVL(B.HRCHY_DTL_DESC,'X')
       AND NVL(A.HRCHY_DTL_CURR_ROW_VAL,'X') = NVL(B.HRCHY_DTL_CURR_ROW_VAL,'X') );

COMMIT;

BEGIN
    CCN_BATCH_PKG.UNLOCK_DATABASE_SP();
END;
/

