SELECT * FROM CODE_DETAIL WHERE CODE_HEADER_NAME = 'NON_TW_TAXTYPE';

DELETE FROM CODE_DETAIL WHERE CODE_HEADER_NAME = 'NON_TW_TAXTYPE';

SELECT * FROM CODE_HEADER WHERE CODE_HEADER_NAME = 'NON_TW_TAXTYPE';

DELETE FROM CODE_HEADER WHERE CODE_HEADER_NAME = 'NON_TW_TAXTYPE';