/*
This Script updates the TAX_RATE and TAX_RATE_DESCRIPTION in NON_TAXWARE_RATES Table.
Created : 06/29/2018 sxg151 CCN Project Team....
        : ASP-
*/

SELECT * FROM NON_TAXWARE_RATES  WHERE COUNTRY_CODE = 'ABW';

--Update tax_rate
UPDATE NON_TAXWARE_RATES
   SET TAX_RATE = 3,
       EFFECTIVE_DATE = SYSDATE
 WHERE COUNTRY_CODE = 'ABW'
  AND  TAX_TYPE = 'Health Care'
  AND  STATEMENT_TYPE = 'AW'
  AND  TAX_RATE = 2
  AND  TAX_CODE = 'H';
  
-- update tax_rate and tax_rate_description    
UPDATE NON_TAXWARE_RATES
   SET TAX_RATE = 3,
       TAX_RATE_DESCRIPTION = '3.000%',
       EFFECTIVE_DATE = SYSDATE
 WHERE COUNTRY_CODE = 'ABW'
  AND  TAX_TYPE = 'VAT'
  AND  STATEMENT_TYPE = 'AW'
  AND  TAX_RATE = 1.5
  AND  TAX_CODE = '70001';

COMMIT;

SELECT * FROM NON_TAXWARE_RATES  WHERE COUNTRY_CODE = 'ABW';  