/*
This Script updates the TAX_RATE and TAX_RATE_DESCRIPTION in NON_TAXWARE_RATES Table.
Created : 06/29/2018 sxg151 CCN Project Team....
        : ASP-
*/

SELECT * FROM NON_TAXWARE_RATES  
 WHERE COUNTRY_CODE = 'ABW'
  AND  TAX_TYPE = 'Health Care'
  AND  STATEMENT_TYPE = 'AW';
 

UPDATE NON_TAXWARE_RATES
   SET EXPIRATION_DATE = TRUNC(SYSDATE)
 WHERE COUNTRY_CODE = 'ABW'
  AND  TAX_TYPE = 'Health Care'
  AND  STATEMENT_TYPE = 'AW'
  ANd  EXPIRATION_DATE IS NULL;
  
INSERT INTO NON_TAXWARE_RATES VALUES('ABW','AW','Health Care','H' ,3 ,'HEALTH TAX',        NULL      ,To_Date('2018/07/01','yyyy/mm/dd'),null,'INITLOAD');

SELECT * FROM NON_TAXWARE_RATES  
 WHERE COUNTRY_CODE = 'ABW'
  AND  TAX_TYPE = 'VAT'
  AND  STATEMENT_TYPE = 'AW';

UPDATE NON_TAXWARE_RATES
   SET EXPIRATION_DATE = TRUNC(SYSDATE)
 WHERE COUNTRY_CODE = 'ABW'
  AND  TAX_TYPE = 'VAT'
  AND  STATEMENT_TYPE = 'AW'
  ANd  EXPIRATION_DATE IS NULL;  

INSERT INTO NON_TAXWARE_RATES VALUES('ABW','AW','VAT','70001' ,3 ,'3.000%',        NULL      ,To_Date('2018/07/01','yyyy/mm/dd'),null,'INITLOAD');

COMMIT;

SELECT * FROM NON_TAXWARE_RATES  WHERE COUNTRY_CODE = 'ABW'