/*
Created : dxv848 02/26/2016 updating the TERRITORY_TYPE_BUSN_CODE in TERRITORY table 
*/

BEGIN
    CCN_BATCH_PKG.LOCK_DATABASE_SP();
END;
/ 
/*
Business Rules : The value used in TERRITORY_TYPE_BUSN_CODE column should be present in CODE_DETAIL table
 SELECT *
   FROM CODE_DETAIL
  WHERE CODE_DETAIL.CODE_HEADER_NAME  = 'TERRITORY_TYPE_BUSN_CODE'
    AND CODE_DETAIL.CODE_DETAIL_VALUE IN ('RR','NR','CM','PM','MS'); 
*/


Select * from TERRITORY WHERE COST_CENTER_CODE='756705' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'MS';
--1 Row(s) Selected   
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE='MS' WHERE COST_CENTER_CODE='756705' AND NVL(TERRITORY_TYPE_BUSN_CODE,'XX') <> 'MS';
--1 Row(s) Updated   
Select * from TERRITORY WHERE COST_CENTER_CODE='758358' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'CM';
--1 Row(s) Selected   
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE='CM' WHERE COST_CENTER_CODE='758358' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'CM';
--1 Row(s) Updated 
Select * from TERRITORY WHERE COST_CENTER_CODE='756864' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'RR';
--1 Row(s) Selected          
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE='RR' WHERE COST_CENTER_CODE='756864' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'RR';
--1 Row(s) Updated 
Select * from TERRITORY WHERE COST_CENTER_CODE='756089' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'MS';
--1 Row(s) Selected               
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE='MS' WHERE COST_CENTER_CODE='756089' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'MS';
--1 Row(s) Updated 
Select * from TERRITORY WHERE COST_CENTER_CODE='754299' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'RR';
--1 Row(s) Selected                         
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE='RR' WHERE COST_CENTER_CODE='754299' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'RR';
--1 Row(s) Updated 
Select * from TERRITORY WHERE COST_CENTER_CODE='756120' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'MS'; 
--1 Row(s) Selected                    
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE='MS' WHERE COST_CENTER_CODE='756120' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'MS';
--1 Row(s) Updated 
Select * from TERRITORY WHERE COST_CENTER_CODE='756271' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'MS'; 
--1 Row(s) Selected                       
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE='MS' WHERE COST_CENTER_CODE='756271' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'MS';
--1 Row(s) Updated 
Select * from TERRITORY WHERE COST_CENTER_CODE='757850' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'MS';
--1 Row(s) Selected                        
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE='MS' WHERE COST_CENTER_CODE='757850' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'MS';
--1 Row(s) Updated 
Select * from TERRITORY WHERE COST_CENTER_CODE='755831' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'MS';
--1 Row(s) Selected                           
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE='MS' WHERE COST_CENTER_CODE='755831' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'MS';
--1 Row(s) Updated 
Select * from TERRITORY WHERE COST_CENTER_CODE='754506' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'RR';  
--1 Row(s) Selected                        
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE='RR' WHERE COST_CENTER_CODE='754506' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'RR';
--1 Row(s) Updated 
Select * from TERRITORY WHERE COST_CENTER_CODE='755598' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'PM'; 
--1 Row(s) Selected                     
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE='PM' WHERE COST_CENTER_CODE='755598' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'PM';
--1 Row(s) Updated 
Select * from TERRITORY WHERE COST_CENTER_CODE='756163' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'MS'; 
--1 Row(s) Selected                        
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE='MS' WHERE COST_CENTER_CODE='756163' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'MS';
--1 Row(s) Updated 
Select * from TERRITORY WHERE COST_CENTER_CODE='755928' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'MS';   
--1 Row(s) Selected             
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE='MS' WHERE COST_CENTER_CODE='755928' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'MS';
--1 Row(s) Selected
Select * from TERRITORY WHERE COST_CENTER_CODE='756838' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'MS'; 
--1 Row(s) Selected                 
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE='MS' WHERE COST_CENTER_CODE='756838' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'MS';
--1 Row(s) Updated 
Select * from TERRITORY WHERE COST_CENTER_CODE='756832' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'NR';  
--1 Row(s) Selected                     
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE='NR' WHERE COST_CENTER_CODE='756832' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'NR';
--1 Row(s) Updated 
Select * from TERRITORY WHERE COST_CENTER_CODE='754119' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'RR';
--1 Row(s) Selected                  
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE='RR' WHERE COST_CENTER_CODE='754119' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'RR';
--1 Row(s) Updated 
Select * from TERRITORY WHERE COST_CENTER_CODE='75Q417' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'RR'; 
--1 Row(s) Selected                   
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE='RR' WHERE COST_CENTER_CODE='75Q417' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'RR';
--1 Row(s) Updated 
Select * from TERRITORY WHERE COST_CENTER_CODE='754493' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'PM'; 
--1 Row(s) Selected                  
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE='PM' WHERE COST_CENTER_CODE='754493' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'PM';
--1 Row(s) Updated 
Select * from TERRITORY WHERE COST_CENTER_CODE='754529' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'PM';
--1 Row(s) Selected                  
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE='PM' WHERE COST_CENTER_CODE='754529' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'PM';
--1 Row(s) Updated 
Select * from TERRITORY WHERE COST_CENTER_CODE='755658' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'PM'; 
--1 Row(s) Selected                
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE='PM' WHERE COST_CENTER_CODE='755658' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'PM';
--1 Row(s) Updated 
Select * from TERRITORY WHERE COST_CENTER_CODE='757834' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'MS';
--1 Row(s) Selected                  
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE='MS' WHERE COST_CENTER_CODE='757834' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'MS';
--1 Row(s) Updated 
Select * from TERRITORY WHERE COST_CENTER_CODE='754446' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'MS';
--1 Row(s) Selected                          
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE='MS' WHERE COST_CENTER_CODE='754446' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'MS';
--1 Row(s) Updated 
Select * from TERRITORY WHERE COST_CENTER_CODE='754078' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'RR';
--1 Row(s) Selected                  
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE='RR' WHERE COST_CENTER_CODE='754078' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'RR';
--1 Row(s) Updated 
Select * from TERRITORY WHERE COST_CENTER_CODE='754112' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'MS'; 
--1 Row(s) Selected                        
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE='MS' WHERE COST_CENTER_CODE='754112' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'MS';
--1 Row(s) Updated 
Select * from TERRITORY WHERE COST_CENTER_CODE='754957' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'CM';
--1 Row(s) Selected                           
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE='CM' WHERE COST_CENTER_CODE='754957' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'CM';
--1 Row(s) Updated 
Select * from TERRITORY WHERE COST_CENTER_CODE='755691' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'PM';
--1 Row(s) Selected                                
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE='PM' WHERE COST_CENTER_CODE='755691' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'PM';
--1 Row(s) Updated 
Select * from TERRITORY WHERE COST_CENTER_CODE='755728' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'NR'; 
--1 Row(s) Selected                         
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE='NR' WHERE COST_CENTER_CODE='755728' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'NR';
--1 Row(s) Updated 
Select * from TERRITORY WHERE COST_CENTER_CODE='755739' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'RR'; 
--1 Row(s) Selected                            
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE='RR' WHERE COST_CENTER_CODE='755739' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'RR';
--1 Row(s) Updated 
Select * from TERRITORY WHERE COST_CENTER_CODE='756059' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'RR';
--1 Row(s) Selected                         
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE='RR' WHERE COST_CENTER_CODE='756059' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'RR';
--1 Row(s) Updated 
Select * from TERRITORY WHERE COST_CENTER_CODE='756490' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'RR'; 
--1 Row(s) Selected                        
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE='RR' WHERE COST_CENTER_CODE='756490' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'RR';
--1 Row(s) Updated 
Select * from TERRITORY WHERE COST_CENTER_CODE='756785' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'PM'; 
--1 Row(s) Selected                        
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE='PM' WHERE COST_CENTER_CODE='756785' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'PM';
--1 Row(s) Updated 
Select * from TERRITORY WHERE COST_CENTER_CODE='757840' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'RR';
--1 Row(s) Selected                          
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE='RR' WHERE COST_CENTER_CODE='757840' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'RR';
--1 Row(s) Updated 
Select * from TERRITORY WHERE COST_CENTER_CODE='756260' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'CM';
--1 Row(s) Selected                     
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE='CM' WHERE COST_CENTER_CODE='756260' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'CM';
--1 Row(s) Updated 
Select * from TERRITORY WHERE COST_CENTER_CODE='754444' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'MS';
--1 Row(s) Selected                       
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE='MS' WHERE COST_CENTER_CODE='754444' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'MS';
--1 Row(s) Updated 
Select * from TERRITORY WHERE COST_CENTER_CODE='754425' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'MS'; 
--1 Row(s) Selected          
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE='MS' WHERE COST_CENTER_CODE='754425' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'MS';
--1 Row(s) Updated 
Select * from TERRITORY WHERE COST_CENTER_CODE='756997' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'NR'; 
--1 Row(s) Selected                           
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE='NR' WHERE COST_CENTER_CODE='756997' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'NR';
--1 Row(s) Updated 
Select * from TERRITORY WHERE COST_CENTER_CODE='757815' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'MS'; 
--1 Row(s) Selected                  
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE='MS' WHERE COST_CENTER_CODE='757815' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'MS';
--1 Row(s) Updated 
Select * from TERRITORY WHERE COST_CENTER_CODE='754688' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'MS';
--1 Row(s) Selected                      
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE='MS' WHERE COST_CENTER_CODE='754688' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'MS';
--1 Row(s) Updated 
Select * from TERRITORY WHERE COST_CENTER_CODE='754903' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'MS';  
--1 Row(s) Selected                     
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE='MS' WHERE COST_CENTER_CODE='754903' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'MS';
--1 Row(s) Updated 
Select * from TERRITORY WHERE COST_CENTER_CODE='756028' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'MS';
--1 Row(s) Selected                       
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE='MS' WHERE COST_CENTER_CODE='756028' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'MS';
--1 Row(s) Updated 
Select * from TERRITORY WHERE COST_CENTER_CODE='756819' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'RR';
--1 Row(s) Selected                       
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE='RR' WHERE COST_CENTER_CODE='756819' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'RR';
--1 Row(s) Updated 
Select * from TERRITORY WHERE COST_CENTER_CODE='75Q510' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'CM'; 
--1 Row(s) Selected                    
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE='CM' WHERE COST_CENTER_CODE='75Q510' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'CM';
--1 Row(s) Updated 
Select * from TERRITORY WHERE COST_CENTER_CODE='75Q544' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'CM'; 
--1 Row(s) Selected                             
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE='CM' WHERE COST_CENTER_CODE='75Q544' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'CM';
--1 Row(s) Updated 
Select * from TERRITORY WHERE COST_CENTER_CODE='756125' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'PM';
--1 Row(s) Selected                              
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE='PM' WHERE COST_CENTER_CODE='756125' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'PM';
--1 Row(s) Updated 
Select * from TERRITORY WHERE COST_CENTER_CODE='756363' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'CM'; 
--1 Row(s) Selected                         
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE='CM' WHERE COST_CENTER_CODE='756363' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'CM';
--1 Row(s) Updated 
Select * from TERRITORY WHERE COST_CENTER_CODE='757903' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'RR'; 
--1 Row(s) Selected                               
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE='RR' WHERE COST_CENTER_CODE='757903' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'RR';
--1 Row(s) Updated 
Select * from TERRITORY WHERE COST_CENTER_CODE='75Q636' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'RR'; 
--1 Row(s) Selected                      
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE='RR' WHERE COST_CENTER_CODE='75Q636' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'RR';
--1 Row(s) Updated 
Select * from TERRITORY WHERE COST_CENTER_CODE='754776' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'MS';
--1 Row(s) Selected                          
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE='MS' WHERE COST_CENTER_CODE='754776' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'MS';
--1 Row(s) Updated 
Select * from TERRITORY WHERE COST_CENTER_CODE='75Q611' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'MS'; 
--1 Row(s) Selected                   
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE='MS' WHERE COST_CENTER_CODE='75Q611' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'MS';
--1 Row(s) Updated 
Select * from TERRITORY WHERE COST_CENTER_CODE='754646' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'MS';
--1 Row(s) Selected                    
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE='MS' WHERE COST_CENTER_CODE='754646' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'MS';
--1 Row(s) Updated 
Select * from TERRITORY WHERE COST_CENTER_CODE='754965' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'CM';
--1 Row(s) Selected                       
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE='CM' WHERE COST_CENTER_CODE='754965' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'CM';
--1 Row(s) Updated 
Select * from TERRITORY WHERE COST_CENTER_CODE='756146' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'RR';  
--1 Row(s) Selected                          
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE='RR' WHERE COST_CENTER_CODE='756146' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'RR';
--1 Row(s) Updated 
Select * from TERRITORY WHERE COST_CENTER_CODE='756442' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'CM'; 
--1 Row(s) Selected                    
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE='CM' WHERE COST_CENTER_CODE='756442' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'CM';
--1 Row(s) Updated 
Select * from TERRITORY WHERE COST_CENTER_CODE='75Q646' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'RR';
--1 Row(s) Selected                           
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE='RR' WHERE COST_CENTER_CODE='75Q646' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'RR';
--1 Row(s) Updated 
Select * from TERRITORY WHERE COST_CENTER_CODE='754669' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'MS';
--1 Row(s) Selected                     
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE='MS' WHERE COST_CENTER_CODE='754669' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'MS';
--1 Row(s) Updated 
Select * from TERRITORY WHERE COST_CENTER_CODE='755853' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'MS';
--1 Row(s) Selected                 
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE='MS' WHERE COST_CENTER_CODE='755853' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'MS';
--1 Row(s) Updated 
Select * from TERRITORY WHERE COST_CENTER_CODE='755857' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'NR';
--1 Row(s) Selected                           
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE='NR' WHERE COST_CENTER_CODE='755857' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'NR';
--1 Row(s) Updated 
Select * from TERRITORY WHERE COST_CENTER_CODE='754742' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'MS'; 
--1 Row(s) Selected                            
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE='MS' WHERE COST_CENTER_CODE='754742' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'MS';
--1 Row(s) Updated 
Select * from TERRITORY WHERE COST_CENTER_CODE='766310' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'MS';
--1 Row(s) Selected                           
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE='MS' WHERE COST_CENTER_CODE='766310' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'MS';
--1 Row(s) Updated 
Select * from TERRITORY WHERE COST_CENTER_CODE='764138' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'CM';
--1 Row(s) Selected                    
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE='CM' WHERE COST_CENTER_CODE='764138' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'CM';
--1 Row(s) Updated 
Select * from TERRITORY WHERE COST_CENTER_CODE='764266' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'RR';
--1 Row(s) Selected                              
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE='RR' WHERE COST_CENTER_CODE='764266' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'RR';
--1 Row(s) Updated 
Select * from TERRITORY WHERE COST_CENTER_CODE='766168' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'RR';
--1 Row(s) Selected                       
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE='RR' WHERE COST_CENTER_CODE='766168' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'RR';
--1 Row(s) Updated 
Select * from TERRITORY WHERE COST_CENTER_CODE='767770' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'RR';
--1 Row(s) Selected                       
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE='RR' WHERE COST_CENTER_CODE='767770' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'RR';
--1 Row(s) Updated 
Select * from TERRITORY WHERE COST_CENTER_CODE='768393' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'RR';
--1 Row(s) Selected                
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE='RR' WHERE COST_CENTER_CODE='768393' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'RR';
--1 Row(s) Updated 
Select * from TERRITORY WHERE COST_CENTER_CODE='768394' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'CM';
--1 Row(s) Selected                
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE='CM' WHERE COST_CENTER_CODE='768394' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'CM';
--1 Row(s) Updated 
Select * from TERRITORY WHERE COST_CENTER_CODE='764281' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'RR'; 
--1 Row(s) Selected                      
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE='RR' WHERE COST_CENTER_CODE='764281' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'RR';
--1 Row(s) Updated 
Select * from TERRITORY WHERE COST_CENTER_CODE='768495' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'PM';
--1 Row(s) Selected                
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE='PM' WHERE COST_CENTER_CODE='768495' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'PM';
--1 Row(s) Updated 
Select * from TERRITORY WHERE COST_CENTER_CODE='76Q861' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'RR';
--1 Row(s) Selected                 
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE='RR' WHERE COST_CENTER_CODE='76Q861' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'RR';
--1 Row(s) Updated 
Select * from TERRITORY WHERE COST_CENTER_CODE='764201' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'MS'; 
--1 Row(s) Selected              
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE='MS' WHERE COST_CENTER_CODE='764201' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'MS';
--1 Row(s) Updated 
Select * from TERRITORY WHERE COST_CENTER_CODE='75Q006' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'RR'; 
--1 Row(s) Selected                          
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE='RR' WHERE COST_CENTER_CODE='75Q006' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'RR';
--1 Row(s) Updated 
Select * from TERRITORY WHERE COST_CENTER_CODE='75Q016' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'MS'; 
--1 Row(s) Selected                        
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE='MS' WHERE COST_CENTER_CODE='75Q016' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'MS';
--1 Row(s) Updated 
Select * from TERRITORY WHERE COST_CENTER_CODE='75Q223' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'MS';  
--1 Row(s) Selected                         
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE='MS' WHERE COST_CENTER_CODE='75Q223' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'MS';
--1 Row(s) Updated 
Select * from TERRITORY WHERE COST_CENTER_CODE='75Q200' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'NR';  
--1 Row(s) Selected                           
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE='NR' WHERE COST_CENTER_CODE='75Q200' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'NR';
--1 Row(s) Updated 
Select * from TERRITORY WHERE COST_CENTER_CODE='75Q068' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'RR';  
--1 Row(s) Selected                      
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE='RR' WHERE COST_CENTER_CODE='75Q068' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'RR';
--1 Row(s) Updated 
Select * from TERRITORY WHERE COST_CENTER_CODE='75Q096' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'NR';  
--1 Row(s) Selected            
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE='NR' WHERE COST_CENTER_CODE='75Q096' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'NR';
--1 Row(s) Updated 
Select * from TERRITORY WHERE COST_CENTER_CODE='75Q141' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'RR'; 
--1 Row(s) Selected                        
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE='RR' WHERE COST_CENTER_CODE='75Q141' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'RR';
--1 Row(s) Updated 
Select * from TERRITORY WHERE COST_CENTER_CODE='75Q021' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'PM'; 
--1 Row(s) Selected                
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE='PM' WHERE COST_CENTER_CODE='75Q021' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'PM';
--1 Row(s) Updated 
Select * from TERRITORY WHERE COST_CENTER_CODE='75Q122' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'RR';
--1 Row(s) Selected                          
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE='RR' WHERE COST_CENTER_CODE='75Q122' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'RR';
--1 Row(s) Updated 
Select * from TERRITORY WHERE COST_CENTER_CODE='75Q024' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'RR';  
--1 Row(s) Selected             
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE='RR' WHERE COST_CENTER_CODE='75Q024' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'RR';
--1 Row(s) Updated 
Select * from TERRITORY WHERE COST_CENTER_CODE='76Q273' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'MS';   
--1 Row(s) Selected                      
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE='MS' WHERE COST_CENTER_CODE='76Q273' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'MS';
--1 Row(s) Updated 
Select * from TERRITORY WHERE COST_CENTER_CODE='76Q230' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'RR';  
--1 Row(s) Selected                   
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE='RR' WHERE COST_CENTER_CODE='76Q230' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'RR';
--1 Row(s) Updated 
Select * from TERRITORY WHERE COST_CENTER_CODE='76Q232' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'RR'; 
--1 Row(s) Selected                      
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE='RR' WHERE COST_CENTER_CODE='76Q232' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'RR';
--1 Row(s) Updated 
Select * from TERRITORY WHERE COST_CENTER_CODE='76Q233' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'CM';  
--1 Row(s) Selected                     
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE='CM' WHERE COST_CENTER_CODE='76Q233' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'CM';
--1 Row(s) Updated 
Select * from TERRITORY WHERE COST_CENTER_CODE='76Q235' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'CM'; 
--1 Row(s) Selected                            
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE='CM' WHERE COST_CENTER_CODE='76Q235' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'CM';
--1 Row(s) Updated 
Select * from TERRITORY WHERE COST_CENTER_CODE='76Q227' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'NR'; 
--1 Row(s) Selected                             
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE='NR' WHERE COST_CENTER_CODE='76Q227' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'NR';
--1 Row(s) Updated 
Select * from TERRITORY WHERE COST_CENTER_CODE='76Q234' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'MS'; 
--1 Row(s) Selected                   
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE='MS' WHERE COST_CENTER_CODE='76Q234' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'MS';
--1 Row(s) Updated 
Select * from TERRITORY WHERE COST_CENTER_CODE='76Q237' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'NR';
--1 Row(s) Selected                  
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE='NR' WHERE COST_CENTER_CODE='76Q237' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'NR';
--1 Row(s) Updated 
Select * from TERRITORY WHERE COST_CENTER_CODE='76Q238' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'CM'; 
--1 Row(s) Selected                   
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE='CM' WHERE COST_CENTER_CODE='76Q238' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'CM';
--1 Row(s) Updated 
Select * from TERRITORY WHERE COST_CENTER_CODE='76Q260' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'CM';
--1 Row(s) Selected                       
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE='CM' WHERE COST_CENTER_CODE='76Q260' AND NVL(TERRITORY_TYPE_BUSN_CODE, 'XX') <> 'CM';
--1 Row(s) Updated 
               
COMMIT;

BEGIN
    CCN_BATCH_PKG.UNLOCK_DATABASE_SP();
END;
/