/***************************************************************************** 
Below script is created to insert data into CCN_AUDIT_EXCLUDED_FIELDS table.
This table holds the table names and fields that are not part of the CCN audit.

Created : 02/16/2017 gxg192 CCN Project....
Modified: 02/21/2017 gxg192 Changes for Store

*****************************************************************************/

SET DEFINE OFF;

--BANK_CARD
INSERT INTO CCN_AUDIT_EXCLUDED_FIELDS (TABLE_NAME,COLUMN_NAME,EXCLUDED_INDICATOR) 
VALUES ('BANK_CARD','PCI_DISCOVER_ID','Y');

INSERT INTO CCN_AUDIT_EXCLUDED_FIELDS (TABLE_NAME,COLUMN_NAME,EXCLUDED_INDICATOR) 
VALUES ('BANK_CARD','PCI_MERCHANT_ID','Y');

--HIERARCHY_DESCRIPTION
INSERT INTO CCN_AUDIT_EXCLUDED_FIELDS (TABLE_NAME,COLUMN_NAME,EXCLUDED_INDICATOR) 
VALUES ('HIERARCHY_DESCRIPTION','HRCHY_GLOBAL_LVL_NBR','Y');

INSERT INTO CCN_AUDIT_EXCLUDED_FIELDS (TABLE_NAME,COLUMN_NAME,EXCLUDED_INDICATOR) 
VALUES ('HIERARCHY_DESCRIPTION','LVL_VALUE_SIZE','Y');

INSERT INTO CCN_AUDIT_EXCLUDED_FIELDS (TABLE_NAME,COLUMN_NAME,EXCLUDED_INDICATOR) 
VALUES ('HIERARCHY_DESCRIPTION','UPPER_LVL_VER_VALUE','Y');

--POLLING
INSERT INTO CCN_AUDIT_EXCLUDED_FIELDS (TABLE_NAME,COLUMN_NAME,EXCLUDED_INDICATOR) 
VALUES ('POLLING','EFFECTIVE_DATE','Y');

INSERT INTO CCN_AUDIT_EXCLUDED_FIELDS (TABLE_NAME,COLUMN_NAME,EXCLUDED_INDICATOR) 
VALUES ('POLLING','EXPIRATION_DATE','Y');

INSERT INTO CCN_AUDIT_EXCLUDED_FIELDS (TABLE_NAME,COLUMN_NAME,EXCLUDED_INDICATOR) 
VALUES ('POLLING','CURRENT_FLAG','Y');

--STORE
INSERT INTO CCN_AUDIT_EXCLUDED_FIELDS (TABLE_NAME,COLUMN_NAME,EXCLUDED_INDICATOR) 
VALUES ('STORE','SALES_VOL_CLASS_CODE','Y');

--TERMINAL
INSERT INTO CCN_AUDIT_EXCLUDED_FIELDS (TABLE_NAME,COLUMN_NAME,EXCLUDED_INDICATOR) 
VALUES ('TERMINAL','PCI_TERMINAL_ID','Y');

INSERT INTO CCN_AUDIT_EXCLUDED_FIELDS (TABLE_NAME,COLUMN_NAME,EXCLUDED_INDICATOR) 
VALUES ('TERMINAL','PCI_VAL_LINK_ALT_MID','Y');

INSERT INTO CCN_AUDIT_EXCLUDED_FIELDS (TABLE_NAME,COLUMN_NAME,EXCLUDED_INDICATOR) 
VALUES ('TERMINAL','PCI_VALUE_LINK_MID','Y');

COMMIT;