/***************************************************************************************
Bulk Upload process to add and update for new field TERRITORY_TYP_OF_BUSN_SGMNT_CD
Created : 06/27/2019 akj899 CCNCC-4 CCN project Team..

***************************************************************************************/
INSERT INTO BULK_LOAD_PRCS_CLM_MPING VALUES('TERRITORY', 'TERRITORY_TYP_OF_BUSN_SGMNT_CD', 'TERRITORY_TYP_OF_BUSN_SGMNT_CD', NULL, NULL);

COMMIT;
