/* 
This script will update the inactive date for the cost center
Created : nxk927 02/19/2018*/
UPDATE COST_CENTER
   SET INACTIVE_DATE = CLOSE_DATE
 WHERE CLOSE_DATE IS NOT NULL;
 
/*
Run below script to generate the update script in prod

SELECT 'UPDATE COST_CENTER SET INACTIVE_DATE = '''||   TO_DATE('01'||REPLACE(INACTIVE_DATE,'/',''),'DDMMRRRR') || ''' WHERE COST_CENTER_CODE = ''' ||  COST_CENTER_CODE  || ''' AND INACTIVE_DATE IS NULL AND CLOSE_DATE IS NULL;' 
  FROM (SELECT COST_CENTER_CODE,COST_CENTER_NAME, TRIM(TRANSLATE(UPPER(SUBSTR(COST_CENTER_NAME,1,5)),'ABCDEFGHIJKLMNOPQRSTUVWXYZ',' '))  INACTIVE_DATE, CLOSE_DATE
          FROM COST_CENTER 
         WHERE CLOSE_DATE IS NULL) C
 WHERE C.INACTIVE_DATE IS NOT NULL
   AND LENGTH(C.INACTIVE_DATE) >= 4
   AND INACTIVE_DATE <> COST_CENTER_NAME
   AND COST_CENTER_CODE <> '40F205'; */
 
 
UPDATE COST_CENTER SET INACTIVE_DATE = '01-JAN-09' WHERE COST_CENTER_CODE = '78506A';
UPDATE COST_CENTER SET INACTIVE_DATE = '01-AUG-12' WHERE COST_CENTER_CODE = '784028';
UPDATE COST_CENTER SET INACTIVE_DATE = '01-JUN-14' WHERE COST_CENTER_CODE = '757879';
UPDATE COST_CENTER SET INACTIVE_DATE = '01-JUN-14' WHERE COST_CENTER_CODE = '757880';
UPDATE COST_CENTER SET INACTIVE_DATE = '01-JUN-14' WHERE COST_CENTER_CODE = '756511';
UPDATE COST_CENTER SET INACTIVE_DATE = '01-SEP-15' WHERE COST_CENTER_CODE = '756355';
UPDATE COST_CENTER SET INACTIVE_DATE = '01-JUN-14' WHERE COST_CENTER_CODE = '756932';
UPDATE COST_CENTER SET INACTIVE_DATE = '01-JAN-15' WHERE COST_CENTER_CODE = '75Q154';
UPDATE COST_CENTER SET INACTIVE_DATE = '01-DEC-14' WHERE COST_CENTER_CODE = '701709';
UPDATE COST_CENTER SET INACTIVE_DATE = '01-JUL-15' WHERE COST_CENTER_CODE = '779040';
UPDATE COST_CENTER SET INACTIVE_DATE = '01-JUN-14' WHERE COST_CENTER_CODE = '756613';
UPDATE COST_CENTER SET INACTIVE_DATE = '01-SEP-12' WHERE COST_CENTER_CODE = '755777';
UPDATE COST_CENTER SET INACTIVE_DATE = '01-DEC-17' WHERE COST_CENTER_CODE = '707144';
UPDATE COST_CENTER SET INACTIVE_DATE = '01-FEB-13' WHERE COST_CENTER_CODE = '717784';
UPDATE COST_CENTER SET INACTIVE_DATE = '01-FEB-13' WHERE COST_CENTER_CODE = '717959';
UPDATE COST_CENTER SET INACTIVE_DATE = '01-JUN-14' WHERE COST_CENTER_CODE = '757950';
UPDATE COST_CENTER SET INACTIVE_DATE = '01-SEP-15' WHERE COST_CENTER_CODE = '75Q149';
UPDATE COST_CENTER SET INACTIVE_DATE = '01-MAR-16' WHERE COST_CENTER_CODE = '70074T';
UPDATE COST_CENTER SET INACTIVE_DATE = '01-SEP-17' WHERE COST_CENTER_CODE = '70083T';
UPDATE COST_CENTER SET INACTIVE_DATE = '01-MAR-16' WHERE COST_CENTER_CODE = '70337T';
UPDATE COST_CENTER SET INACTIVE_DATE = '01-SEP-17' WHERE COST_CENTER_CODE = '70211T';
UPDATE COST_CENTER SET INACTIVE_DATE = '01-DEC-17' WHERE COST_CENTER_CODE = '70410T';
UPDATE COST_CENTER SET INACTIVE_DATE = '01-OCT-16' WHERE COST_CENTER_CODE = '70431T';
UPDATE COST_CENTER SET INACTIVE_DATE = '01-OCT-16' WHERE COST_CENTER_CODE = '70433T';
UPDATE COST_CENTER SET INACTIVE_DATE = '01-SEP-15' WHERE COST_CENTER_CODE = '75Q641';
UPDATE COST_CENTER SET INACTIVE_DATE = '01-OCT-16' WHERE COST_CENTER_CODE = '70565T';
UPDATE COST_CENTER SET INACTIVE_DATE = '01-JAN-18' WHERE COST_CENTER_CODE = '779008';
UPDATE COST_CENTER SET INACTIVE_DATE = '01-MAR-08' WHERE COST_CENTER_CODE = '789510';
UPDATE COST_CENTER SET INACTIVE_DATE = '01-MAY-16' WHERE COST_CENTER_CODE = '76781T';
UPDATE COST_CENTER SET INACTIVE_DATE = '01-SEP-17' WHERE COST_CENTER_CODE = '70836T';
UPDATE COST_CENTER SET INACTIVE_DATE = '01-MAY-16' WHERE COST_CENTER_CODE = '76773T';
UPDATE COST_CENTER SET INACTIVE_DATE = '01-MAY-16' WHERE COST_CENTER_CODE = '76787T';
UPDATE COST_CENTER SET INACTIVE_DATE = '01-MAY-16' WHERE COST_CENTER_CODE = '76775T';
UPDATE COST_CENTER SET INACTIVE_DATE = '01-MAY-16' WHERE COST_CENTER_CODE = '76776T';
UPDATE COST_CENTER SET INACTIVE_DATE = '01-MAY-16' WHERE COST_CENTER_CODE = '76788T';
UPDATE COST_CENTER SET INACTIVE_DATE = '01-SEP-15' WHERE COST_CENTER_CODE = '75Q623';
UPDATE COST_CENTER SET INACTIVE_DATE = '01-MAY-16' WHERE COST_CENTER_CODE = '76774T';
UPDATE COST_CENTER SET INACTIVE_DATE = '01-OCT-17' WHERE COST_CENTER_CODE = '70458T';
UPDATE COST_CENTER SET INACTIVE_DATE = '01-OCT-16' WHERE COST_CENTER_CODE = '70563T';
UPDATE COST_CENTER SET INACTIVE_DATE = '01-DEC-07' WHERE COST_CENTER_CODE = '789868';
UPDATE COST_CENTER SET INACTIVE_DATE = '01-SEP-15' WHERE COST_CENTER_CODE = '80U607';
UPDATE COST_CENTER SET INACTIVE_DATE = '01-JAN-17' WHERE COST_CENTER_CODE = '799985';
UPDATE COST_CENTER SET INACTIVE_DATE = '01-DEC-07' WHERE COST_CENTER_CODE = '789527';
UPDATE COST_CENTER SET INACTIVE_DATE = '01-DEC-17' WHERE COST_CENTER_CODE = '792892';
UPDATE COST_CENTER SET INACTIVE_DATE = '01-DEC-17' WHERE COST_CENTER_CODE = '799276';

COMMIT;