/*
Created : dxv848 02/26/2016 updating the cost_center name in cost_center table 
*/

BEGIN
    CCN_BATCH_PKG.LOCK_DATABASE_SP();
END;
/ 

Select * from cost_center WHERE COST_CENTER_CODE='756705' AND COST_CENTER_NAME<>'GRAND RAPIDS MULTI SEG REP';
--1 Row(s) Selected   
UPDATE COST_CENTER SET COST_CENTER_NAME='GRAND RAPIDS MULTI SEG REP' WHERE COST_CENTER_CODE='756705' AND COST_CENTER_NAME<>'GRAND RAPIDS MULTI SEG REP';
--1 Row(s) Updated   
Select * from cost_center WHERE COST_CENTER_CODE='758358' AND COST_CENTER_NAME<>'GRAND RAPIDS COMM REP';
--1 Row(s) Selected   
UPDATE COST_CENTER SET COST_CENTER_NAME='GRAND RAPIDS COMM REP' WHERE COST_CENTER_CODE='758358' AND COST_CENTER_NAME<>'GRAND RAPIDS COMM REP';
--1 Row(s) Updated 
Select * from cost_center WHERE COST_CENTER_CODE='756864' AND COST_CENTER_NAME<>'NORTHERN MICHIGAN RES REPAINT REP';
--1 Row(s) Selected          
UPDATE COST_CENTER SET COST_CENTER_NAME='NORTHERN MICHIGAN RES REPAINT REP' WHERE COST_CENTER_CODE='756864' AND COST_CENTER_NAME<>'NORTHERN MICHIGAN RES REPAINT REP';
--1 Row(s) Updated 
Select * from cost_center WHERE COST_CENTER_CODE='756089' AND COST_CENTER_NAME<>'MILWAUKEE MULTI SEG REP';
--1 Row(s) Selected               
UPDATE COST_CENTER SET COST_CENTER_NAME='MILWAUKEE MULTI SEG REP' WHERE COST_CENTER_CODE='756089' AND COST_CENTER_NAME<>'MILWAUKEE MULTI SEG REP';
--1 Row(s) Updated 
Select * from cost_center WHERE COST_CENTER_CODE='754299' AND COST_CENTER_NAME<>'FORT WAYNE RES REPAINT REP';
--1 Row(s) Selected                         
UPDATE COST_CENTER SET COST_CENTER_NAME='FORT WAYNE RES REPAINT REP' WHERE COST_CENTER_CODE='754299' AND COST_CENTER_NAME<>'FORT WAYNE RES REPAINT REP';
--1 Row(s) Updated 
Select * from cost_center WHERE COST_CENTER_CODE='756120' AND COST_CENTER_NAME<>'FORT WAYNE MULTI SEG REP'; 
--1 Row(s) Selected                    
UPDATE COST_CENTER SET COST_CENTER_NAME='FORT WAYNE MULTI SEG REP' WHERE COST_CENTER_CODE='756120' AND COST_CENTER_NAME<>'FORT WAYNE MULTI SEG REP';
--1 Row(s) Updated 
Select * from cost_center WHERE COST_CENTER_CODE='756271' AND COST_CENTER_NAME<>'LOUISVILLE MULTI SEG REP'; 
--1 Row(s) Selected                       
UPDATE COST_CENTER SET COST_CENTER_NAME='LOUISVILLE MULTI SEG REP' WHERE COST_CENTER_CODE='756271' AND COST_CENTER_NAME<>'LOUISVILLE MULTI SEG REP';
--1 Row(s) Updated 
Select * from cost_center WHERE COST_CENTER_CODE='757850' AND COST_CENTER_NAME<>'DAKOTAS MULTI SEG REP';
--1 Row(s) Selected                        
UPDATE COST_CENTER SET COST_CENTER_NAME='DAKOTAS MULTI SEG REP' WHERE COST_CENTER_CODE='757850' AND COST_CENTER_NAME<>'DAKOTAS MULTI SEG REP';
--1 Row(s) Updated 
Select * from cost_center WHERE COST_CENTER_CODE='755831' AND COST_CENTER_NAME<>'ROANOKE MULTI SEG REP';
--1 Row(s) Selected                           
UPDATE COST_CENTER SET COST_CENTER_NAME='ROANOKE MULTI SEG REP' WHERE COST_CENTER_CODE='755831' AND COST_CENTER_NAME<>'ROANOKE MULTI SEG REP';
--1 Row(s) Updated 
Select * from cost_center WHERE COST_CENTER_CODE='754506' AND COST_CENTER_NAME<>'BALTIMORE RES REPAINT REP';  
--1 Row(s) Selected                        
UPDATE COST_CENTER SET COST_CENTER_NAME='BALTIMORE RES REPAINT REP' WHERE COST_CENTER_CODE='754506' AND COST_CENTER_NAME<>'BALTIMORE RES REPAINT REP';
--1 Row(s) Updated 
Select * from cost_center WHERE COST_CENTER_CODE='755598' AND COST_CENTER_NAME<>'CAPITAL PROP MAINT REP'; 
--1 Row(s) Selected                     
UPDATE COST_CENTER SET COST_CENTER_NAME='CAPITAL PROP MAINT REP' WHERE COST_CENTER_CODE='755598' AND COST_CENTER_NAME<>'CAPITAL PROP MAINT REP';
--1 Row(s) Updated 
Select * from cost_center WHERE COST_CENTER_CODE='756163' AND COST_CENTER_NAME<>'METRO CONNECTICUT MULTI SEG REP'; 
--1 Row(s) Selected                        
UPDATE COST_CENTER SET COST_CENTER_NAME='METRO CONNECTICUT MULTI SEG REP' WHERE COST_CENTER_CODE='756163' AND COST_CENTER_NAME<>'METRO CONNECTICUT MULTI SEG REP';
--1 Row(s) Updated 
Select * from cost_center WHERE COST_CENTER_CODE='755928' AND COST_CENTER_NAME<>'METRO NEW JERSEY MULTI SEG REP';   
--1 Row(s) Selected             
UPDATE COST_CENTER SET COST_CENTER_NAME='METRO NEW JERSEY MULTI SEG REP' WHERE COST_CENTER_CODE='755928' AND COST_CENTER_NAME<>'METRO NEW JERSEY MULTI SEG REP';
--1 Row(s) Selected
Select * from cost_center WHERE COST_CENTER_CODE='756838' AND COST_CENTER_NAME<>'LONG ISLAND MULTI SEG REP'; 
--1 Row(s) Selected                 
UPDATE COST_CENTER SET COST_CENTER_NAME='LONG ISLAND MULTI SEG REP' WHERE COST_CENTER_CODE='756838' AND COST_CENTER_NAME<>'LONG ISLAND MULTI SEG REP';
--1 Row(s) Updated 
Select * from cost_center WHERE COST_CENTER_CODE='756832' AND COST_CENTER_NAME<>'NEW JERSEY COASTAL NEW RES REP';  
--1 Row(s) Selected                     
UPDATE COST_CENTER SET COST_CENTER_NAME='NEW JERSEY COASTAL NEW RES REP' WHERE COST_CENTER_CODE='756832' AND COST_CENTER_NAME<>'NEW JERSEY COASTAL NEW RES REP';
--1 Row(s) Updated 
Select * from cost_center WHERE COST_CENTER_CODE='754119' AND COST_CENTER_NAME<>'PHILADELPHIA RES REPAINT REP';
--1 Row(s) Selected                  
UPDATE COST_CENTER SET COST_CENTER_NAME='PHILADELPHIA RES REPAINT REP' WHERE COST_CENTER_CODE='754119' AND COST_CENTER_NAME<>'PHILADELPHIA RES REPAINT REP';
--1 Row(s) Updated 
Select * from cost_center WHERE COST_CENTER_CODE='75Q417' AND COST_CENTER_NAME<>'CHARLESTON WV RES REPAINT REP'; 
--1 Row(s) Selected                   
UPDATE COST_CENTER SET COST_CENTER_NAME='CHARLESTON WV RES REPAINT REP' WHERE COST_CENTER_CODE='75Q417' AND COST_CENTER_NAME<>'CHARLESTON WV RES REPAINT REP';
--1 Row(s) Updated 
Select * from cost_center WHERE COST_CENTER_CODE='754493' AND COST_CENTER_NAME<>'NEW JERSEY WEST PROP MAINT REP'; 
--1 Row(s) Selected                  
UPDATE COST_CENTER SET COST_CENTER_NAME='NEW JERSEY WEST PROP MAINT REP' WHERE COST_CENTER_CODE='754493' AND COST_CENTER_NAME<>'NEW JERSEY WEST PROP MAINT REP';
--1 Row(s) Updated 
Select * from cost_center WHERE COST_CENTER_CODE='754529' AND COST_CENTER_NAME<>'CHARLOTTE METRO PROP MAINT REP';
--1 Row(s) Selected                  
UPDATE COST_CENTER SET COST_CENTER_NAME='CHARLOTTE METRO PROP MAINT REP' WHERE COST_CENTER_CODE='754529' AND COST_CENTER_NAME<>'CHARLOTTE METRO PROP MAINT REP';
--1 Row(s) Updated 
Select * from cost_center WHERE COST_CENTER_CODE='755658' AND COST_CENTER_NAME<>'CHARLOTTE METRO PROP MAINT REP'; 
--1 Row(s) Selected                
UPDATE COST_CENTER SET COST_CENTER_NAME='CHARLOTTE METRO PROP MAINT REP' WHERE COST_CENTER_CODE='755658' AND COST_CENTER_NAME<>'CHARLOTTE METRO PROP MAINT REP';
--1 Row(s) Updated 
Select * from cost_center WHERE COST_CENTER_CODE='757834' AND COST_CENTER_NAME<>'COLUMBIA MULTI SEG REP';
--1 Row(s) Selected                  
UPDATE COST_CENTER SET COST_CENTER_NAME='COLUMBIA MULTI SEG REP' WHERE COST_CENTER_CODE='757834' AND COST_CENTER_NAME<>'COLUMBIA MULTI SEG REP';
--1 Row(s) Updated 
Select * from cost_center WHERE COST_CENTER_CODE='754446' AND COST_CENTER_NAME<>'CHARLESTON METRO MULTI SEG REP';
--1 Row(s) Selected                          
UPDATE COST_CENTER SET COST_CENTER_NAME='CHARLESTON METRO MULTI SEG REP' WHERE COST_CENTER_CODE='754446' AND COST_CENTER_NAME<>'CHARLESTON METRO MULTI SEG REP';
--1 Row(s) Updated 
Select * from cost_center WHERE COST_CENTER_CODE='754078' AND COST_CENTER_NAME<>'ATLANTA RES REPAINT REP';
--1 Row(s) Selected                  
UPDATE COST_CENTER SET COST_CENTER_NAME='ATLANTA RES REPAINT REP' WHERE COST_CENTER_CODE='754078' AND COST_CENTER_NAME<>'ATLANTA RES REPAINT REP';
--1 Row(s) Updated 
Select * from cost_center WHERE COST_CENTER_CODE='754112' AND COST_CENTER_NAME<>'ATLANTA MULTI SEG REP'; 
--1 Row(s) Selected                        
UPDATE COST_CENTER SET COST_CENTER_NAME='ATLANTA MULTI SEG REP' WHERE COST_CENTER_CODE='754112' AND COST_CENTER_NAME<>'ATLANTA MULTI SEG REP';
--1 Row(s) Updated 
Select * from cost_center WHERE COST_CENTER_CODE='754957' AND COST_CENTER_NAME<>'ATLANTA COMM REP';
--1 Row(s) Selected                           
UPDATE COST_CENTER SET COST_CENTER_NAME='ATLANTA COMM REP' WHERE COST_CENTER_CODE='754957' AND COST_CENTER_NAME<>'ATLANTA COMM REP';
--1 Row(s) Updated 
Select * from cost_center WHERE COST_CENTER_CODE='755691' AND COST_CENTER_NAME<>'ATLANTA PROP MAINT REP';
--1 Row(s) Selected                                
UPDATE COST_CENTER SET COST_CENTER_NAME='ATLANTA PROP MAINT REP' WHERE COST_CENTER_CODE='755691' AND COST_CENTER_NAME<>'ATLANTA PROP MAINT REP';
--1 Row(s) Updated 
Select * from cost_center WHERE COST_CENTER_CODE='755728' AND COST_CENTER_NAME<>'ATLANTA NEW RES REP'; 
--1 Row(s) Selected                         
UPDATE COST_CENTER SET COST_CENTER_NAME='ATLANTA NEW RES REP' WHERE COST_CENTER_CODE='755728' AND COST_CENTER_NAME<>'ATLANTA NEW RES REP';
--1 Row(s) Updated 
Select * from cost_center WHERE COST_CENTER_CODE='755739' AND COST_CENTER_NAME<>'ATLANTA RES REPAINT REP'; 
--1 Row(s) Selected                            
UPDATE COST_CENTER SET COST_CENTER_NAME='ATLANTA RES REPAINT REP' WHERE COST_CENTER_CODE='755739' AND COST_CENTER_NAME<>'ATLANTA RES REPAINT REP';
--1 Row(s) Updated 
Select * from cost_center WHERE COST_CENTER_CODE='756059' AND COST_CENTER_NAME<>'ATLANTA RES REPAINT REP';
--1 Row(s) Selected                         
UPDATE COST_CENTER SET COST_CENTER_NAME='ATLANTA RES REPAINT REP' WHERE COST_CENTER_CODE='756059' AND COST_CENTER_NAME<>'ATLANTA RES REPAINT REP';
--1 Row(s) Updated 
Select * from cost_center WHERE COST_CENTER_CODE='756490' AND COST_CENTER_NAME<>'ATLANTA RES REPAINT REP'; 
--1 Row(s) Selected                        
UPDATE COST_CENTER SET COST_CENTER_NAME='ATLANTA RES REPAINT REP' WHERE COST_CENTER_CODE='756490' AND COST_CENTER_NAME<>'ATLANTA RES REPAINT REP';
--1 Row(s) Updated 
Select * from cost_center WHERE COST_CENTER_CODE='756785' AND COST_CENTER_NAME<>'ATLANTA PROP MAINT REP'; 
--1 Row(s) Selected                        
UPDATE COST_CENTER SET COST_CENTER_NAME='ATLANTA PROP MAINT REP' WHERE COST_CENTER_CODE='756785' AND COST_CENTER_NAME<>'ATLANTA PROP MAINT REP';
--1 Row(s) Updated 
Select * from cost_center WHERE COST_CENTER_CODE='757840' AND COST_CENTER_NAME<>'CHATTANOOGA RES REPAINT REP';
--1 Row(s) Selected                          
UPDATE COST_CENTER SET COST_CENTER_NAME='CHATTANOOGA RES REPAINT REP' WHERE COST_CENTER_CODE='757840' AND COST_CENTER_NAME<>'CHATTANOOGA RES REPAINT REP';
--1 Row(s) Updated 
Select * from cost_center WHERE COST_CENTER_CODE='756260' AND COST_CENTER_NAME<>'SOUTHERN ALABAMA COMM REP';
--1 Row(s) Selected                     
UPDATE COST_CENTER SET COST_CENTER_NAME='SOUTHERN ALABAMA COMM REP' WHERE COST_CENTER_CODE='756260' AND COST_CENTER_NAME<>'SOUTHERN ALABAMA COMM REP';
--1 Row(s) Updated 
Select * from cost_center WHERE COST_CENTER_CODE='754444' AND COST_CENTER_NAME<>'SOUTHWEST FLORIDA METRO MULTI SEG R';
--1 Row(s) Selected                       
UPDATE COST_CENTER SET COST_CENTER_NAME='SOUTHWEST FLORIDA METRO MULTI SEG R' WHERE COST_CENTER_CODE='754444' AND COST_CENTER_NAME<>'SOUTHWEST FLORIDA METRO MULTI SEG R';
--1 Row(s) Updated 
Select * from cost_center WHERE COST_CENTER_CODE='754425' AND COST_CENTER_NAME<>'TAMPA MULTI SEG REP'; 
--1 Row(s) Selected          
UPDATE COST_CENTER SET COST_CENTER_NAME='TAMPA MULTI SEG REP' WHERE COST_CENTER_CODE='754425' AND COST_CENTER_NAME<>'TAMPA MULTI SEG REP';
--1 Row(s) Updated 
Select * from cost_center WHERE COST_CENTER_CODE='756997' AND COST_CENTER_NAME<>'FLORIDA PANHANDLE NEW RES REP'; 
--1 Row(s) Selected                           
UPDATE COST_CENTER SET COST_CENTER_NAME='FLORIDA PANHANDLE NEW RES REP' WHERE COST_CENTER_CODE='756997' AND COST_CENTER_NAME<>'FLORIDA PANHANDLE NEW RES REP';
--1 Row(s) Updated 
Select * from cost_center WHERE COST_CENTER_CODE='757815' AND COST_CENTER_NAME<>'JACKSONVILLE MULTI SEG REP'; 
--1 Row(s) Selected                  
UPDATE COST_CENTER SET COST_CENTER_NAME='JACKSONVILLE MULTI SEG REP' WHERE COST_CENTER_CODE='757815' AND COST_CENTER_NAME<>'JACKSONVILLE MULTI SEG REP';
--1 Row(s) Updated 
Select * from cost_center WHERE COST_CENTER_CODE='754688' AND COST_CENTER_NAME<>'PUERTO RICO MULTI SEG REP';
--1 Row(s) Selected                      
UPDATE COST_CENTER SET COST_CENTER_NAME='PUERTO RICO MULTI SEG REP' WHERE COST_CENTER_CODE='754688' AND COST_CENTER_NAME<>'PUERTO RICO MULTI SEG REP';
--1 Row(s) Updated 
Select * from cost_center WHERE COST_CENTER_CODE='754903' AND COST_CENTER_NAME<>'PUERTO RICO MULTI SEG REP';  
--1 Row(s) Selected                     
UPDATE COST_CENTER SET COST_CENTER_NAME='PUERTO RICO MULTI SEG REP' WHERE COST_CENTER_CODE='754903' AND COST_CENTER_NAME<>'PUERTO RICO MULTI SEG REP';
--1 Row(s) Updated 
Select * from cost_center WHERE COST_CENTER_CODE='756028' AND COST_CENTER_NAME<>'PUERTO RICO MULTI SEG REP';
--1 Row(s) Selected                       
UPDATE COST_CENTER SET COST_CENTER_NAME='PUERTO RICO MULTI SEG REP' WHERE COST_CENTER_CODE='756028' AND COST_CENTER_NAME<>'PUERTO RICO MULTI SEG REP';
--1 Row(s) Updated 
Select * from cost_center WHERE COST_CENTER_CODE='756819' AND COST_CENTER_NAME<>'PUERTO RICO RES REPAINT REP';
--1 Row(s) Selected                       
UPDATE COST_CENTER SET COST_CENTER_NAME='PUERTO RICO RES REPAINT REP' WHERE COST_CENTER_CODE='756819' AND COST_CENTER_NAME<>'PUERTO RICO RES REPAINT REP';
--1 Row(s) Updated 
Select * from cost_center WHERE COST_CENTER_CODE='75Q510' AND COST_CENTER_NAME<>'CARIBBEAN COMM REP'; 
--1 Row(s) Selected                    
UPDATE COST_CENTER SET COST_CENTER_NAME='CARIBBEAN COMM REP' WHERE COST_CENTER_CODE='75Q510' AND COST_CENTER_NAME<>'CARIBBEAN COMM REP';
--1 Row(s) Updated 
Select * from cost_center WHERE COST_CENTER_CODE='75Q544' AND COST_CENTER_NAME<>'CARIBBEAN COMM REP'; 
--1 Row(s) Selected                             
UPDATE COST_CENTER SET COST_CENTER_NAME='CARIBBEAN COMM REP' WHERE COST_CENTER_CODE='75Q544' AND COST_CENTER_NAME<>'CARIBBEAN COMM REP';
--1 Row(s) Updated 
Select * from cost_center WHERE COST_CENTER_CODE='756125' AND COST_CENTER_NAME<>'MEMPHIS PROP MAINT REP';
--1 Row(s) Selected                              
UPDATE COST_CENTER SET COST_CENTER_NAME='MEMPHIS PROP MAINT REP' WHERE COST_CENTER_CODE='756125' AND COST_CENTER_NAME<>'MEMPHIS PROP MAINT REP';
--1 Row(s) Updated 
Select * from cost_center WHERE COST_CENTER_CODE='756363' AND COST_CENTER_NAME<>'JACKSON COMM REP'; 
--1 Row(s) Selected                         
UPDATE COST_CENTER SET COST_CENTER_NAME='JACKSON COMM REP' WHERE COST_CENTER_CODE='756363' AND COST_CENTER_NAME<>'JACKSON COMM REP';
--1 Row(s) Updated 
Select * from cost_center WHERE COST_CENTER_CODE='757903' AND COST_CENTER_NAME<>'KNOXVILLE RES REPAINT REP'; 
--1 Row(s) Selected                               
UPDATE COST_CENTER SET COST_CENTER_NAME='KNOXVILLE RES REPAINT REP' WHERE COST_CENTER_CODE='757903' AND COST_CENTER_NAME<>'KNOXVILLE RES REPAINT REP';
--1 Row(s) Updated 
Select * from cost_center WHERE COST_CENTER_CODE='75Q636' AND COST_CENTER_NAME<>'AUSTIN RES REPAINT REP'; 
--1 Row(s) Selected                      
UPDATE COST_CENTER SET COST_CENTER_NAME='AUSTIN RES REPAINT REP' WHERE COST_CENTER_CODE='75Q636' AND COST_CENTER_NAME<>'AUSTIN RES REPAINT REP';
--1 Row(s) Updated 
Select * from cost_center WHERE COST_CENTER_CODE='754776' AND COST_CENTER_NAME<>'CALIFORNIA BAY MULTI SEG REP';
--1 Row(s) Selected                          
UPDATE COST_CENTER SET COST_CENTER_NAME='CALIFORNIA BAY MULTI SEG REP' WHERE COST_CENTER_CODE='754776' AND COST_CENTER_NAME<>'CALIFORNIA BAY MULTI SEG REP';
--1 Row(s) Updated 
Select * from cost_center WHERE COST_CENTER_CODE='75Q611' AND COST_CENTER_NAME<>'CALIFORNIA BAY MULTI SEG REP'; 
--1 Row(s) Selected                   
UPDATE COST_CENTER SET COST_CENTER_NAME='CALIFORNIA BAY MULTI SEG REP' WHERE COST_CENTER_CODE='75Q611' AND COST_CENTER_NAME<>'CALIFORNIA BAY MULTI SEG REP';
--1 Row(s) Updated 
Select * from cost_center WHERE COST_CENTER_CODE='754646' AND COST_CENTER_NAME<>'LOS ANGELES MULTI SEG REP';
--1 Row(s) Selected                    
UPDATE COST_CENTER SET COST_CENTER_NAME='LOS ANGELES MULTI SEG REP' WHERE COST_CENTER_CODE='754646' AND COST_CENTER_NAME<>'LOS ANGELES MULTI SEG REP';
--1 Row(s) Updated 
Select * from cost_center WHERE COST_CENTER_CODE='754965' AND COST_CENTER_NAME<>'LOS ANGELES COMM REP';
--1 Row(s) Selected                       
UPDATE COST_CENTER SET COST_CENTER_NAME='LOS ANGELES COMM REP' WHERE COST_CENTER_CODE='754965' AND COST_CENTER_NAME<>'LOS ANGELES COMM REP';
--1 Row(s) Updated 
Select * from cost_center WHERE COST_CENTER_CODE='756146' AND COST_CENTER_NAME<>'LOS ANGELES RES REPAINT REP';  
--1 Row(s) Selected                          
UPDATE COST_CENTER SET COST_CENTER_NAME='LOS ANGELES RES REPAINT REP' WHERE COST_CENTER_CODE='756146' AND COST_CENTER_NAME<>'LOS ANGELES RES REPAINT REP';
--1 Row(s) Updated 
Select * from cost_center WHERE COST_CENTER_CODE='756442' AND COST_CENTER_NAME<>'LOS ANGELES COMM REP'; 
--1 Row(s) Selected                    
UPDATE COST_CENTER SET COST_CENTER_NAME='LOS ANGELES COMM REP' WHERE COST_CENTER_CODE='756442' AND COST_CENTER_NAME<>'LOS ANGELES COMM REP';
--1 Row(s) Updated 
Select * from cost_center WHERE COST_CENTER_CODE='75Q646' AND COST_CENTER_NAME<>'LOS ANGELES RES REPAINT REP';
--1 Row(s) Selected                           
UPDATE COST_CENTER SET COST_CENTER_NAME='LOS ANGELES RES REPAINT REP' WHERE COST_CENTER_CODE='75Q646' AND COST_CENTER_NAME<>'LOS ANGELES RES REPAINT REP';
--1 Row(s) Updated 
Select * from cost_center WHERE COST_CENTER_CODE='754669' AND COST_CENTER_NAME<>'NORTHERN COLORADO MULTI SEG REP';
--1 Row(s) Selected                     
UPDATE COST_CENTER SET COST_CENTER_NAME='NORTHERN COLORADO MULTI SEG REP' WHERE COST_CENTER_CODE='754669' AND COST_CENTER_NAME<>'NORTHERN COLORADO MULTI SEG REP';
--1 Row(s) Updated 
Select * from cost_center WHERE COST_CENTER_CODE='755853' AND COST_CENTER_NAME<>'PHOENIX MULTI SEG REP';
--1 Row(s) Selected                 
UPDATE COST_CENTER SET COST_CENTER_NAME='PHOENIX MULTI SEG REP' WHERE COST_CENTER_CODE='755853' AND COST_CENTER_NAME<>'PHOENIX MULTI SEG REP';
--1 Row(s) Updated 
Select * from cost_center WHERE COST_CENTER_CODE='755857' AND COST_CENTER_NAME<>'PHOENIX NEW RES REP';
--1 Row(s) Selected                           
UPDATE COST_CENTER SET COST_CENTER_NAME='PHOENIX NEW RES REP' WHERE COST_CENTER_CODE='755857' AND COST_CENTER_NAME<>'PHOENIX NEW RES REP';
--1 Row(s) Updated 
Select * from cost_center WHERE COST_CENTER_CODE='754742' AND COST_CENTER_NAME<>'MIDWEST MULTI SEG REP'; 
--1 Row(s) Selected                            
UPDATE COST_CENTER SET COST_CENTER_NAME='MIDWEST MULTI SEG REP' WHERE COST_CENTER_CODE='754742' AND COST_CENTER_NAME<>'MIDWEST MULTI SEG REP';
--1 Row(s) Updated 
Select * from cost_center WHERE COST_CENTER_CODE='766310' AND COST_CENTER_NAME<>'EASTERN CANADA MULTI SEG REP';
--1 Row(s) Selected                           
UPDATE COST_CENTER SET COST_CENTER_NAME='EASTERN CANADA MULTI SEG REP' WHERE COST_CENTER_CODE='766310' AND COST_CENTER_NAME<>'EASTERN CANADA MULTI SEG REP';
--1 Row(s) Updated 
Select * from cost_center WHERE COST_CENTER_CODE='764138' AND COST_CENTER_NAME<>'VANCOUVER COMM REP';
--1 Row(s) Selected                    
UPDATE COST_CENTER SET COST_CENTER_NAME='VANCOUVER COMM REP' WHERE COST_CENTER_CODE='764138' AND COST_CENTER_NAME<>'VANCOUVER COMM REP';
--1 Row(s) Updated 
Select * from cost_center WHERE COST_CENTER_CODE='764266' AND COST_CENTER_NAME<>'VANCOUVER RES REPAINT REP';
--1 Row(s) Selected                              
UPDATE COST_CENTER SET COST_CENTER_NAME='VANCOUVER RES REPAINT REP' WHERE COST_CENTER_CODE='764266' AND COST_CENTER_NAME<>'VANCOUVER RES REPAINT REP';
--1 Row(s) Updated 
Select * from cost_center WHERE COST_CENTER_CODE='766168' AND COST_CENTER_NAME<>'VANCOUVER RES REPAINT REP';
--1 Row(s) Selected                       
UPDATE COST_CENTER SET COST_CENTER_NAME='VANCOUVER RES REPAINT REP' WHERE COST_CENTER_CODE='766168' AND COST_CENTER_NAME<>'VANCOUVER RES REPAINT REP';
--1 Row(s) Updated 
Select * from cost_center WHERE COST_CENTER_CODE='767770' AND COST_CENTER_NAME<>'BRITISH COLUMBIA RES REPAINT REP';
--1 Row(s) Selected                       
UPDATE COST_CENTER SET COST_CENTER_NAME='BRITISH COLUMBIA RES REPAINT REP' WHERE COST_CENTER_CODE='767770' AND COST_CENTER_NAME<>'BRITISH COLUMBIA RES REPAINT REP';
--1 Row(s) Updated 
Select * from cost_center WHERE COST_CENTER_CODE='768393' AND COST_CENTER_NAME<>'BRITISH COLUMBIA RES REPAINT REP';
--1 Row(s) Selected                
UPDATE COST_CENTER SET COST_CENTER_NAME='BRITISH COLUMBIA RES REPAINT REP' WHERE COST_CENTER_CODE='768393' AND COST_CENTER_NAME<>'BRITISH COLUMBIA RES REPAINT REP';
--1 Row(s) Updated 
Select * from cost_center WHERE COST_CENTER_CODE='768394' AND COST_CENTER_NAME<>'BRITISH COLUMBIA COMM REP';
--1 Row(s) Selected                
UPDATE COST_CENTER SET COST_CENTER_NAME='BRITISH COLUMBIA COMM REP' WHERE COST_CENTER_CODE='768394' AND COST_CENTER_NAME<>'BRITISH COLUMBIA COMM REP';
--1 Row(s) Updated 
Select * from cost_center WHERE COST_CENTER_CODE='764281' AND COST_CENTER_NAME<>'SOUTHERN ALBERTA RES REPAINT REP'; 
--1 Row(s) Selected                      
UPDATE COST_CENTER SET COST_CENTER_NAME='SOUTHERN ALBERTA RES REPAINT REP' WHERE COST_CENTER_CODE='764281' AND COST_CENTER_NAME<>'SOUTHERN ALBERTA RES REPAINT REP';
--1 Row(s) Updated 
Select * from cost_center WHERE COST_CENTER_CODE='768495' AND COST_CENTER_NAME<>'SOUTHERN ALBERTA PROP MAINT REP';
--1 Row(s) Selected                
UPDATE COST_CENTER SET COST_CENTER_NAME='SOUTHERN ALBERTA PROP MAINT REP' WHERE COST_CENTER_CODE='768495' AND COST_CENTER_NAME<>'SOUTHERN ALBERTA PROP MAINT REP';
--1 Row(s) Updated 
Select * from cost_center WHERE COST_CENTER_CODE='76Q861' AND COST_CENTER_NAME<>'SOUTHERN ALBERTA RES REPAINT REP';
--1 Row(s) Selected                 
UPDATE COST_CENTER SET COST_CENTER_NAME='SOUTHERN ALBERTA RES REPAINT REP' WHERE COST_CENTER_CODE='76Q861' AND COST_CENTER_NAME<>'SOUTHERN ALBERTA RES REPAINT REP';
--1 Row(s) Updated 
Select * from cost_center WHERE COST_CENTER_CODE='764201' AND COST_CENTER_NAME<>'SASKMAN MULTI SEG REP'; 
--1 Row(s) Selected              
UPDATE COST_CENTER SET COST_CENTER_NAME='SASKMAN MULTI SEG REP' WHERE COST_CENTER_CODE='764201' AND COST_CENTER_NAME<>'SASKMAN MULTI SEG REP';
--1 Row(s) Updated 
Select * from cost_center WHERE COST_CENTER_CODE='75Q006' AND COST_CENTER_NAME<>'SEATTLE RES REPAINT REP'; 
--1 Row(s) Selected                          
UPDATE COST_CENTER SET COST_CENTER_NAME='SEATTLE RES REPAINT REP' WHERE COST_CENTER_CODE='75Q006' AND COST_CENTER_NAME<>'SEATTLE RES REPAINT REP';
--1 Row(s) Updated 
Select * from cost_center WHERE COST_CENTER_CODE='75Q016' AND COST_CENTER_NAME<>'SEATTLE MULTI SEG REP'; 
--1 Row(s) Selected                        
UPDATE COST_CENTER SET COST_CENTER_NAME='SEATTLE MULTI SEG REP' WHERE COST_CENTER_CODE='75Q016' AND COST_CENTER_NAME<>'SEATTLE MULTI SEG REP';
--1 Row(s) Updated 
Select * from cost_center WHERE COST_CENTER_CODE='75Q223' AND COST_CENTER_NAME<>'TAMPA MULTI SEG REP';  
--1 Row(s) Selected                         
UPDATE COST_CENTER SET COST_CENTER_NAME='TAMPA MULTI SEG REP' WHERE COST_CENTER_CODE='75Q223' AND COST_CENTER_NAME<>'TAMPA MULTI SEG REP';
--1 Row(s) Updated 
Select * from cost_center WHERE COST_CENTER_CODE='75Q200' AND COST_CENTER_NAME<>'JACKSONVILLE NEW RES REP';  
--1 Row(s) Selected                           
UPDATE COST_CENTER SET COST_CENTER_NAME='JACKSONVILLE NEW RES REP' WHERE COST_CENTER_CODE='75Q200' AND COST_CENTER_NAME<>'JACKSONVILLE NEW RES REP';
--1 Row(s) Updated 
Select * from cost_center WHERE COST_CENTER_CODE='75Q068' AND COST_CENTER_NAME<>'CALIFORNIA CENTRAL RES REPAINT REP';  
--1 Row(s) Selected                      
UPDATE COST_CENTER SET COST_CENTER_NAME='CALIFORNIA CENTRAL RES REPAINT REP' WHERE COST_CENTER_CODE='75Q068' AND COST_CENTER_NAME<>'CALIFORNIA CENTRAL RES REPAINT REP';
--1 Row(s) Updated 
Select * from cost_center WHERE COST_CENTER_CODE='75Q096' AND COST_CENTER_NAME<>'LOS ANGELES NEW RES REP';  
--1 Row(s) Selected            
UPDATE COST_CENTER SET COST_CENTER_NAME='LOS ANGELES NEW RES REP' WHERE COST_CENTER_CODE='75Q096' AND COST_CENTER_NAME<>'LOS ANGELES NEW RES REP';
--1 Row(s) Updated 
Select * from cost_center WHERE COST_CENTER_CODE='75Q141' AND COST_CENTER_NAME<>'DALLAS-FT WORTH RES REPAINT REP';
--1 Row(s) Selected                        
UPDATE COST_CENTER SET COST_CENTER_NAME='DALLAS-FT WORTH RES REPAINT REP' WHERE COST_CENTER_CODE='75Q141' AND COST_CENTER_NAME<>'DALLAS-FT WORTH RES REPAINT REP';
--1 Row(s) Updated 
Select * from cost_center WHERE COST_CENTER_CODE='75Q021' AND COST_CENTER_NAME<>'PHOENIX PROP MAINT REP'; 
--1 Row(s) Selected                
UPDATE COST_CENTER SET COST_CENTER_NAME='PHOENIX PROP MAINT REP' WHERE COST_CENTER_CODE='75Q021' AND COST_CENTER_NAME<>'PHOENIX PROP MAINT REP';
--1 Row(s) Updated 
Select * from cost_center WHERE COST_CENTER_CODE='75Q122' AND COST_CENTER_NAME<>'SOUTHERN COLORADO RES REPAINT REP';
--1 Row(s) Selected                          
UPDATE COST_CENTER SET COST_CENTER_NAME='SOUTHERN COLORADO RES REPAINT REP' WHERE COST_CENTER_CODE='75Q122' AND COST_CENTER_NAME<>'SOUTHERN COLORADO RES REPAINT REP';
--1 Row(s) Updated 
Select * from cost_center WHERE COST_CENTER_CODE='75Q024' AND COST_CENTER_NAME<>'ARIZONA RES REPAINT REP';  
--1 Row(s) Selected             
UPDATE COST_CENTER SET COST_CENTER_NAME='ARIZONA RES REPAINT REP' WHERE COST_CENTER_CODE='75Q024' AND COST_CENTER_NAME<>'ARIZONA RES REPAINT REP';
--1 Row(s) Updated 
Select * from cost_center WHERE COST_CENTER_CODE='76Q273' AND COST_CENTER_NAME<>'TORONTO METRO MULTI SEG REP';   
--1 Row(s) Selected                      
UPDATE COST_CENTER SET COST_CENTER_NAME='TORONTO METRO MULTI SEG REP' WHERE COST_CENTER_CODE='76Q273' AND COST_CENTER_NAME<>'TORONTO METRO MULTI SEG REP';
--1 Row(s) Updated 
Select * from cost_center WHERE COST_CENTER_CODE='76Q230' AND COST_CENTER_NAME<>'VANCOUVER RES REPAINT REP';  
--1 Row(s) Selected                   
UPDATE COST_CENTER SET COST_CENTER_NAME='VANCOUVER RES REPAINT REP' WHERE COST_CENTER_CODE='76Q230' AND COST_CENTER_NAME<>'VANCOUVER RES REPAINT REP';
--1 Row(s) Updated 
Select * from cost_center WHERE COST_CENTER_CODE='76Q232' AND COST_CENTER_NAME<>'VANCOUVER RES REPAINT REP'; 
--1 Row(s) Selected                      
UPDATE COST_CENTER SET COST_CENTER_NAME='VANCOUVER RES REPAINT REP' WHERE COST_CENTER_CODE='76Q232' AND COST_CENTER_NAME<>'VANCOUVER RES REPAINT REP';
--1 Row(s) Updated 
Select * from cost_center WHERE COST_CENTER_CODE='76Q233' AND COST_CENTER_NAME<>'VANCOUVER COMM REP';  
--1 Row(s) Selected                     
UPDATE COST_CENTER SET COST_CENTER_NAME='VANCOUVER COMM REP' WHERE COST_CENTER_CODE='76Q233' AND COST_CENTER_NAME<>'VANCOUVER COMM REP';
--1 Row(s) Updated 
Select * from cost_center WHERE COST_CENTER_CODE='76Q235' AND COST_CENTER_NAME<>'VANCOUVER COMM REP'; 
--1 Row(s) Selected                            
UPDATE COST_CENTER SET COST_CENTER_NAME='VANCOUVER COMM REP' WHERE COST_CENTER_CODE='76Q235' AND COST_CENTER_NAME<>'VANCOUVER COMM REP';
--1 Row(s) Updated 
Select * from cost_center WHERE COST_CENTER_CODE='76Q227' AND COST_CENTER_NAME<>'BRITISH COLUMBIA NEW RES REP'; 
--1 Row(s) Selected                             
UPDATE COST_CENTER SET COST_CENTER_NAME='BRITISH COLUMBIA NEW RES REP' WHERE COST_CENTER_CODE='76Q227' AND COST_CENTER_NAME<>'BRITISH COLUMBIA NEW RES REP';
--1 Row(s) Updated 
Select * from cost_center WHERE COST_CENTER_CODE='76Q234' AND COST_CENTER_NAME<>'BRITISH COLUMBIA MULTI SEG REP'; 
--1 Row(s) Selected                   
UPDATE COST_CENTER SET COST_CENTER_NAME='BRITISH COLUMBIA MULTI SEG REP' WHERE COST_CENTER_CODE='76Q234' AND COST_CENTER_NAME<>'BRITISH COLUMBIA MULTI SEG REP';
--1 Row(s) Updated 
Select * from cost_center WHERE COST_CENTER_CODE='76Q237' AND COST_CENTER_NAME<>'BRITISH COLUMBIA NEW RES REP';
--1 Row(s) Selected                  
UPDATE COST_CENTER SET COST_CENTER_NAME='BRITISH COLUMBIA NEW RES REP' WHERE COST_CENTER_CODE='76Q237' AND COST_CENTER_NAME<>'BRITISH COLUMBIA NEW RES REP';
--1 Row(s) Updated 
Select * from cost_center WHERE COST_CENTER_CODE='76Q238' AND COST_CENTER_NAME<>'BRITISH COLUMBIA COMM REP'; 
--1 Row(s) Selected                   
UPDATE COST_CENTER SET COST_CENTER_NAME='BRITISH COLUMBIA COMM REP' WHERE COST_CENTER_CODE='76Q238' AND COST_CENTER_NAME<>'BRITISH COLUMBIA COMM REP';
--1 Row(s) Updated 
Select * from cost_center WHERE COST_CENTER_CODE='76Q260' AND COST_CENTER_NAME<>'SOUTHERN ALBERTA COMM REP';
--1 Row(s) Selected                       
UPDATE COST_CENTER SET COST_CENTER_NAME='SOUTHERN ALBERTA COMM REP' WHERE COST_CENTER_CODE='76Q260' AND COST_CENTER_NAME<>'SOUTHERN ALBERTA COMM REP';
--1 Row(s) Updated 
               
COMMIT;

BEGIN
    CCN_BATCH_PKG.UNLOCK_DATABASE_SP();
END;
/