/*******************************************************************************
Grant select permission to utility for each hierarchy detail view.

Permission needs to be granted to utility on all hierarchy details views to generate excel spreadsheet.

Create synonyms to all hierarchy views in utility database.

  CREATED : 07/12/2018 pxa852 CCN Project...
*******************************************************************************/

GRANT SELECT ON ADMINORG_HIERARCHY_ATTRBT_VW TO CCN_UTILITY;
CREATE OR REPLACE SYNONYM CCN_UTILITY.ADMINORG_HIERARCHY_ATTRBT_VW FOR COSTCNTR.ADMINORG_HIERARCHY_ATTRBT_VW;

GRANT SELECT ON ADMIN_TO_SALES_AREA_HRCHY_VW TO CCN_UTILITY;
CREATE OR REPLACE SYNONYM CCN_UTILITY.ADMIN_TO_SALES_AREA_HRCHY_VW FOR COSTCNTR.ADMIN_TO_SALES_AREA_HRCHY_VW;

GRANT SELECT ON ADMIN_TO_SALES_DIST_HRCHY_VW TO CCN_UTILITY;
CREATE OR REPLACE SYNONYM CCN_UTILITY.ADMIN_TO_SALES_DIST_HRCHY_VW FOR COSTCNTR.ADMIN_TO_SALES_DIST_HRCHY_VW;

GRANT SELECT ON ADMIN_TO_SALES_DIV_HRCHY_VW TO CCN_UTILITY;
CREATE OR REPLACE SYNONYM CCN_UTILITY.ADMIN_TO_SALES_DIV_HRCHY_VW FOR COSTCNTR.ADMIN_TO_SALES_DIV_HRCHY_VW;

GRANT SELECT ON ALTERNATE_DAD_DETAIL_VIEW TO CCN_UTILITY;
CREATE OR REPLACE SYNONYM CCN_UTILITY.ALTERNATE_DAD_DETAIL_VIEW FOR COSTCNTR.ALTERNATE_DAD_DETAIL_VIEW;

GRANT SELECT ON CREDIT_HIERARCHY_DETAIL_VIEW TO CCN_UTILITY;
CREATE OR REPLACE SYNONYM CCN_UTILITY.CREDIT_HIERARCHY_DETAIL_VIEW FOR COSTCNTR.CREDIT_HIERARCHY_DETAIL_VIEW;

GRANT SELECT ON GLOBAL_HIERARCHY_ATTRBT_VW TO CCN_UTILITY;
CREATE OR REPLACE SYNONYM CCN_UTILITY.GLOBAL_HIERARCHY_ATTRBT_VW FOR COSTCNTR.GLOBAL_HIERARCHY_ATTRBT_VW;

GRANT SELECT ON LEGACY_GL_DIVISION_DETAIL_VIEW TO CCN_UTILITY;
CREATE OR REPLACE SYNONYM CCN_UTILITY.LEGACY_GL_DIVISION_DETAIL_VIEW FOR COSTCNTR.LEGACY_GL_DIVISION_DETAIL_VIEW;

GRANT SELECT ON PRICE_DISTRICT_DETAIL_VIEW TO CCN_UTILITY; 
CREATE OR REPLACE SYNONYM CCN_UTILITY.PRICE_DISTRICT_DETAIL_VIEW FOR COSTCNTR.PRICE_DISTRICT_DETAIL_VIEW;

GRANT SELECT ON FACTS_DIVISION_DETAIL_VIEW TO CCN_UTILITY; 
CREATE OR REPLACE SYNONYM CCN_UTILITY.FACTS_DIVISION_DETAIL_VIEW FOR COSTCNTR.FACTS_DIVISION_DETAIL_VIEW;


commit;