BEGIN
    CCN_BATCH_PKG.LOCK_DATABASE_SP();
END;
/
DECLARE
V_HRCHY_DTL_EXP_DATE  HIERARCHY_DETAIL_HST.HRCHY_DTL_EXP_DATE%TYPE;
IN_HRCHY_DTL_EXP_DATE HIERARCHY_DETAIL_HST.HRCHY_DTL_EXP_DATE%TYPE;
IN_HRCHY_DTL_EFF_DATE HIERARCHY_DETAIL.HRCHY_DTL_EFF_DATE%TYPE;

 CURSOR CC_CUR IS 
    SELECT DISTINCT HRCHY_HDR_NAME, HRCHY_DTL_LEVEL, HRCHY_DTL_CURR_ROW_VAL, HRCHY_DTL_EFF_DATE, HRCHY_DTL_PREV_LVL_VAL
      FROM HIERARCHY_DETAIL_HST 
     WHERE LENGTH(HRCHY_DTL_CURR_ROW_VAL) = '6'
       AND HRCHY_DTL_EXP_DATE IS NULL
     ORDER BY HRCHY_DTL_EFF_DATE;
  
BEGIN
  FOR REC IN CC_CUR LOOP
             
         SELECT (SELECT HRCHY_DTL_EFF_DATE 
                   FROM HIERARCHY_DETAIL_HST
                  WHERE HRCHY_HDR_NAME = REC.HRCHY_HDR_NAME
                    AND HRCHY_DTL_LEVEL = REC.HRCHY_DTL_LEVEL
                    AND HRCHY_DTL_CURR_ROW_VAL = REC.HRCHY_DTL_CURR_ROW_VAL
					AND HRCHY_DTL_PREV_LVL_VAL = REC.HRCHY_DTL_PREV_LVL_VAL
                    AND HRCHY_DTL_EFF_DATE > REC.HRCHY_DTL_EFF_DATE
                    AND HRCHY_DTL_EFF_DATE < sysdate
                    AND ROWNUM = 1) as HRCHY_DTL_EFF_DATE
           INTO IN_HRCHY_DTL_EXP_DATE
           FROM HIERARCHY_DETAIL_HST 
          WHERE HRCHY_HDR_NAME = REC.HRCHY_HDR_NAME
            AND HRCHY_DTL_LEVEL = REC.HRCHY_DTL_LEVEL
            AND HRCHY_DTL_CURR_ROW_VAL = REC.HRCHY_DTL_CURR_ROW_VAL
            AND HRCHY_DTL_EFF_DATE = REC.HRCHY_DTL_EFF_DATE
            AND HRCHY_DTL_PREV_LVL_VAL = REC.HRCHY_DTL_PREV_LVL_VAL
            AND ROWNUM = 1;

         SELECT DISTINCT HRCHY_DTL_EFF_DATE
           INTO IN_HRCHY_DTL_EFF_DATE
           FROM HIERARCHY_DETAIL
          WHERE HRCHY_HDR_NAME = REC.HRCHY_HDR_NAME
            AND HRCHY_DTL_LEVEL = REC.HRCHY_DTL_LEVEL
            AND HRCHY_DTL_CURR_ROW_VAL = REC.HRCHY_DTL_CURR_ROW_VAL
            AND ROWNUM < 2;
         

        UPDATE HIERARCHY_DETAIL_HST 
           SET HRCHY_DTL_EXP_DATE     = NVL(IN_HRCHY_DTL_EXP_DATE,IN_HRCHY_DTL_EFF_DATE) 
         WHERE HRCHY_HDR_NAME         = REC.HRCHY_HDR_NAME
           AND HRCHY_DTL_LEVEL        = REC.HRCHY_DTL_LEVEL
           AND HRCHY_DTL_CURR_ROW_VAL = REC.HRCHY_DTL_CURR_ROW_VAL
           AND HRCHY_DTL_EFF_DATE     = REC.HRCHY_DTL_EFF_DATE
           AND HRCHY_DTL_PREV_LVL_VAL = REC.HRCHY_DTL_PREV_LVL_VAL
           AND HRCHY_DTL_EXP_DATE IS NULL;
   
Commit;
--DBMS_OUTPUT.PUT_LINE(REC.HRCHY_DTL_CURR_ROW_VAL || '-' || NVL(IN_HRCHY_DTL_EXP_DATE,IN_HRCHY_DTL_EFF_DATE) );
END LOOP;

END;

/
BEGIN
    CCN_BATCH_PKG.UNLOCK_DATABASE_SP();
END;
/