/* 
DML to remove TERRITORY_SALES_MGR, TERRITORY_ASSIGNMENT tables from INSERTORDER table as these tables no longer exist
*/
DELETE FROM INSERTORDER WHERE TABLE_NAME IN ('TERRITORY_SALES_MGR','TERRITORY_ASSIGNMENT');
COMMIT;