SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE IN (
'754005','754013','754026','754036','754048','754051','754061','754073','754146','754161','754173','754216','754251','754296','754298','754446','754447','754451','754465','754470','754529','754554','754582','754604','754612','754697','754709','754745','754753','754768','754776','754794','754814','754815','754819','754842','754890','754892','754916','754925','754926','754948','754970','754981','755516','755549','755584','755618','755791','755793','755801','755838','755850','755880','755886','755975','756001','756026','756027','756028','756030','756032','756060','756093','756150','756162','756164','756260','756269','756283','756375','756396','756421','756432','756437','756438','756441','756479','756499','756527','756582','756589','756594','756618','756638','756650','756660','756702','756713','756716','756726','756740','756760','756771','756785','756808','756827','756857','756859','756919','757839','757871','757888','757889','757932','757981','758346','758396','764552','766098','766317','766823','768391','75Q031','75Q036','75Q037','75Q047','75Q101','75Q102','75Q112','75Q124','75Q157','75Q160','75Q181','75Q185','75Q197','75Q210','75Q223','75Q353','75Q427','75Q431','75Q442','75Q452','75Q466','75Q467','75Q478','75Q480','75Q508','75Q509','75Q517','75Q524','75Q543','75Q547','75Q549','75Q573','75Q604','75Q615','75Q629','75Q663','75Q714','75Q734','75Q765','75Q906','75Q907','75Q996','76Q255','76Q261','76Q271','76Q796','76Q866'
) ORDER BY 1;

SELECT * FROM TERRITORY WHERE COST_CENTER_CODE IN (
'754005','754013','754026','754036','754048','754051','754061','754073','754146','754161','754173','754216','754251','754296','754298','754446','754447','754451','754465','754470','754529','754554','754582','754604','754612','754697','754709','754745','754753','754768','754776','754794','754814','754815','754819','754842','754890','754892','754916','754925','754926','754948','754970','754981','755516','755549','755584','755618','755791','755793','755801','755838','755850','755880','755886','755975','756001','756026','756027','756028','756030','756032','756060','756093','756150','756162','756164','756260','756269','756283','756375','756396','756421','756432','756437','756438','756441','756479','756499','756527','756582','756589','756594','756618','756638','756650','756660','756702','756713','756716','756726','756740','756760','756771','756785','756808','756827','756857','756859','756919','757839','757871','757888','757889','757932','757981','758346','758396','764552','766098','766317','766823','768391','75Q031','75Q036','75Q037','75Q047','75Q101','75Q102','75Q112','75Q124','75Q157','75Q160','75Q181','75Q185','75Q197','75Q210','75Q223','75Q353','75Q427','75Q431','75Q442','75Q452','75Q466','75Q467','75Q478','75Q480','75Q508','75Q509','75Q517','75Q524','75Q543','75Q547','75Q549','75Q573','75Q604','75Q615','75Q629','75Q663','75Q714','75Q734','75Q765','75Q906','75Q907','75Q996','76Q255','76Q261','76Q271','76Q796','76Q866'
) ORDER BY 1;

/*
Below script will update the description of 278 cost centers as requested by Pat Malloy

Created : 9/19/2018 jxc517 CCN Project Team....
Changed :
*/
SET SERVEROUTPUT ON;

DECLARE
    V_BULK_LOAD_LKUP_ID     NUMBER;
BEGIN
    POS_DATA_GENERATION.SET_FLAG_POLLING_BULK_LOADS('MANUAL_CC_DESC_UPDATE', V_BULK_LOAD_LKUP_ID);
    DBMS_OUTPUT.PUT_LINE(V_BULK_LOAD_LKUP_ID);
END;

--SELECT * FROM POS_DOWNLOADS_BULK_LOADS_LKUP;

SET SCAN OFF;

SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '754005';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'MOUNTAIN RES REPAINT REP' WHERE COST_CENTER_CODE = '754005';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '754005';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '754005';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '754013';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'SAN FERNANDO RES REPAINT REP' WHERE COST_CENTER_CODE = '754013';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '754013';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '754013';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '754026';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'LONG ISLAND COMM REP' WHERE COST_CENTER_CODE = '754026';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '754026';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'CM' WHERE COST_CENTER_CODE = '754026';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '754036';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'CAPITAL COMM REP' WHERE COST_CENTER_CODE = '754036';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '754036';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'CM' WHERE COST_CENTER_CODE = '754036';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '754048';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'JACKSON MULTI SEG REP' WHERE COST_CENTER_CODE = '754048';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '754048';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '754048';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '754051';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WESTERN NEW YORK RES REPAINT REP' WHERE COST_CENTER_CODE = '754051';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '754051';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '754051';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '754061';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'SOUTH FLORIDA METRO COMM REP' WHERE COST_CENTER_CODE = '754061';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '754061';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'CM' WHERE COST_CENTER_CODE = '754061';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '754073';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'SOUTHERN ALABAMA MULTI SEG REP' WHERE COST_CENTER_CODE = '754073';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '754073';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '754073';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '754146';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'CENTRAL IL MULTI SEG REP' WHERE COST_CENTER_CODE = '754146';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '754146';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '754146';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '754161';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'GREEN BAY COMM REP' WHERE COST_CENTER_CODE = '754161';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '754161';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'CM' WHERE COST_CENTER_CODE = '754161';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '754173';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'PORTLAND MULTI SEG REP' WHERE COST_CENTER_CODE = '754173';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '754173';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '754173';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '754216';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'RALEIGH METRO RES REPAINT REP' WHERE COST_CENTER_CODE = '754216';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '754216';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '754216';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '754251';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'MEMPHIS NEW RES REP' WHERE COST_CENTER_CODE = '754251';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '754251';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'NR' WHERE COST_CENTER_CODE = '754251';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '754296';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'SOUTH FLORIDA METRO MULTI SEG REP' WHERE COST_CENTER_CODE = '754296';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '754296';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '754296';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '754298';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'BOSTON RES REPAINT REP' WHERE COST_CENTER_CODE = '754298';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '754298';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '754298';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '754446';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'CHARLESTON METRO COMM REP' WHERE COST_CENTER_CODE = '754446';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '754446';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'CM' WHERE COST_CENTER_CODE = '754446';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '754447';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'FLORIDA PANHANDLE NEW RES REP' WHERE COST_CENTER_CODE = '754447';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '754447';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'NR' WHERE COST_CENTER_CODE = '754447';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '754451';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'SOUTH FLORIDA METRO MULTI SEG REP' WHERE COST_CENTER_CODE = '754451';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '754451';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '754451';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '754465';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'GEORGIA SOUTH MULTI SEG REP' WHERE COST_CENTER_CODE = '754465';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '754465';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '754465';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '754470';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'GEORGIA SOUTH MULTI SEG REP' WHERE COST_CENTER_CODE = '754470';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '754470';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '754470';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '754529';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'ASHEVILLE MULTI SEG REP' WHERE COST_CENTER_CODE = '754529';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '754529';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '754529';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '754554';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'CHARLESTON METRO MULTI SEG REP' WHERE COST_CENTER_CODE = '754554';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '754554';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '754554';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '754582';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'ROANOKE MULTI SEG REP' WHERE COST_CENTER_CODE = '754582';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '754582';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '754582';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '754604';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'BOSTON MULTI SEG REP' WHERE COST_CENTER_CODE = '754604';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '754604';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '754604';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '754612';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'NORTHERN MULTI SEG REP' WHERE COST_CENTER_CODE = '754612';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '754612';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '754612';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '754697';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'CINCINNATI-DAYTON RES REPAINT REP' WHERE COST_CENTER_CODE = '754697';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '754697';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '754697';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '754709';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'OMAHA MULTI SEG REP' WHERE COST_CENTER_CODE = '754709';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '754709';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '754709';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '754745';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'OKLAHOMA CITY MULTI SEG REP' WHERE COST_CENTER_CODE = '754745';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '754745';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '754745';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '754753';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'LAS VEGAS MULTI SEG REP' WHERE COST_CENTER_CODE = '754753';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '754753';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '754753';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '754768';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'CALIFORNIA NORTH RES REPAINT REP' WHERE COST_CENTER_CODE = '754768';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '754768';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '754768';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '754776';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'CALIFORNIA BAY MULTI SEG REP' WHERE COST_CENTER_CODE = '754776';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '754776';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '754776';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '754794';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'DETROIT COMM REP' WHERE COST_CENTER_CODE = '754794';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '754794';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'CM' WHERE COST_CENTER_CODE = '754794';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '754814';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'LEXINGTON COMM REP' WHERE COST_CENTER_CODE = '754814';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '754814';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'CM' WHERE COST_CENTER_CODE = '754814';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '754815';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'CLEVELAND COMM REP' WHERE COST_CENTER_CODE = '754815';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '754815';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'CM' WHERE COST_CENTER_CODE = '754815';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '754819';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'CLEVELAND COMM REP' WHERE COST_CENTER_CODE = '754819';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '754819';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'CM' WHERE COST_CENTER_CODE = '754819';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '754842';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'COLUMBUS MULTI SEG REP' WHERE COST_CENTER_CODE = '754842';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '754842';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '754842';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '754890';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'ARKANSAS NEW RES REP' WHERE COST_CENTER_CODE = '754890';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '754890';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'NR' WHERE COST_CENTER_CODE = '754890';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '754892';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'DETROIT MULTI SEG REP' WHERE COST_CENTER_CODE = '754892';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '754892';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '754892';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '754916';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'ATLANTA MULTI SEG REP' WHERE COST_CENTER_CODE = '754916';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '754916';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '754916';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '754925';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'HOUSTON MULTI SEG REP' WHERE COST_CENTER_CODE = '754925';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '754925';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '754925';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '754926';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'VALLEY MULTI SEG REP' WHERE COST_CENTER_CODE = '754926';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '754926';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '754926';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '754948';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'NEW ORLEANS RES REPAINT REP' WHERE COST_CENTER_CODE = '754948';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '754948';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '754948';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '754970';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'CHARLESTON METRO MULTI SEG REP' WHERE COST_CENTER_CODE = '754970';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '754970';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '754970';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '754981';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'EL PASO MULTI SEG REP' WHERE COST_CENTER_CODE = '754981';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '754981';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '754981';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '755516';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'PITTSBURGH MULTI SEG REP' WHERE COST_CENTER_CODE = '755516';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '755516';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '755516';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '755549';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'DELMAR NEW RES REP' WHERE COST_CENTER_CODE = '755549';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '755549';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'NR' WHERE COST_CENTER_CODE = '755549';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '755584';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'BALTIMORE PROP MAINT REP' WHERE COST_CENTER_CODE = '755584';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '755584';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'PM' WHERE COST_CENTER_CODE = '755584';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '755618';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'CAPITAL COMM REP' WHERE COST_CENTER_CODE = '755618';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '755618';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'CM' WHERE COST_CENTER_CODE = '755618';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '755791';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'PUERTO RICO MULTI SEG REP' WHERE COST_CENTER_CODE = '755791';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '755791';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '755791';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '755793';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'ATLANTA PROP MAINT REP' WHERE COST_CENTER_CODE = '755793';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '755793';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'PM' WHERE COST_CENTER_CODE = '755793';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '755801';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'ATLANTA MULTI SEG REP' WHERE COST_CENTER_CODE = '755801';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '755801';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '755801';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '755838';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'NEW MEXICO MULTI SEG REP' WHERE COST_CENTER_CODE = '755838';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '755838';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '755838';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '755850';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'ASHEVILLE MULTI SEG REP' WHERE COST_CENTER_CODE = '755850';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '755850';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '755850';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '755880';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'LOS ANGELES RES REPAINT REP' WHERE COST_CENTER_CODE = '755880';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '755880';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '755880';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '755886';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'FLORIDA PANHANDLE MULTI SEG REP' WHERE COST_CENTER_CODE = '755886';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '755886';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '755886';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '755975';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'CALIFORNIA BAY MULTI SEG REP' WHERE COST_CENTER_CODE = '755975';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '755975';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '755975';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '756001';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'CLEVELAND COMM REP' WHERE COST_CENTER_CODE = '756001';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '756001';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'CM' WHERE COST_CENTER_CODE = '756001';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '756026';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'PUERTO RICO PROP MAINT REP' WHERE COST_CENTER_CODE = '756026';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '756026';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'PM' WHERE COST_CENTER_CODE = '756026';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '756027';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'CHARLESTON METRO MULTI SEG REP' WHERE COST_CENTER_CODE = '756027';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '756027';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '756027';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '756028';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'PUERTO RICO MULTI SEG REP' WHERE COST_CENTER_CODE = '756028';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '756028';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '756028';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '756030';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'BOSTON RES REPAINT REP' WHERE COST_CENTER_CODE = '756030';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '756030';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '756030';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '756032';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'BOSTON RES REPAINT REP' WHERE COST_CENTER_CODE = '756032';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '756032';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '756032';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '756060';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'GREENVILLE MULTI SEG REP' WHERE COST_CENTER_CODE = '756060';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '756060';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '756060';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '756093';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'SOUTH BEND MULTI SEG REP' WHERE COST_CENTER_CODE = '756093';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '756093';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '756093';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '756150';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'ROANOKE MULTI SEG REP' WHERE COST_CENTER_CODE = '756150';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '756150';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '756150';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '756162';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'CHARLOTTE METRO MULTI SEG REP' WHERE COST_CENTER_CODE = '756162';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '756162';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '756162';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '756164';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'AUSTIN MULTI SEG REP' WHERE COST_CENTER_CODE = '756164';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '756164';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '756164';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '756260';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'SOUTHERN ALABAMA MULTI SEG REP' WHERE COST_CENTER_CODE = '756260';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '756260';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '756260';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '756269';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'METRO NEW JERSEY MULTI SEG REP' WHERE COST_CENTER_CODE = '756269';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '756269';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '756269';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '756283';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'SEATTLE MULTI SEG REP' WHERE COST_CENTER_CODE = '756283';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '756283';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '756283';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '756375';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'RALEIGH METRO MULTI SEG REP' WHERE COST_CENTER_CODE = '756375';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '756375';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '756375';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '756396';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'NY CAPITAL COMM REP' WHERE COST_CENTER_CODE = '756396';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '756396';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'CM' WHERE COST_CENTER_CODE = '756396';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '756421';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'TULSA RES REPAINT REP' WHERE COST_CENTER_CODE = '756421';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '756421';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '756421';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '756432';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'NEW ORLEANS MULTI SEG REP' WHERE COST_CENTER_CODE = '756432';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '756432';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '756432';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '756437';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'CALIFORNIA BAY MULTI SEG REP' WHERE COST_CENTER_CODE = '756437';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '756437';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '756437';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '756438';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'ASHEVILLE MULTI SEG REP' WHERE COST_CENTER_CODE = '756438';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '756438';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '756438';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '756441';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'CLEVELAND NEW RES REP' WHERE COST_CENTER_CODE = '756441';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '756441';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'NR' WHERE COST_CENTER_CODE = '756441';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '756479';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WILMINGTON RES REPAINT REP' WHERE COST_CENTER_CODE = '756479';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '756479';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '756479';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '756499';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'DALLAS-FT WORTH COMM REP' WHERE COST_CENTER_CODE = '756499';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '756499';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'CM' WHERE COST_CENTER_CODE = '756499';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '756527';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'SPRINGFIELD NEW RES REP' WHERE COST_CENTER_CODE = '756527';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '756527';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'NR' WHERE COST_CENTER_CODE = '756527';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '756582';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'SEATTLE MULTI SEG REP' WHERE COST_CENTER_CODE = '756582';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '756582';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '756582';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '756589';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'CINCINNATI-DAYTON RES REPAINT REP' WHERE COST_CENTER_CODE = '756589';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '756589';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '756589';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '756594';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'TOLEDO MULTI SEG REP' WHERE COST_CENTER_CODE = '756594';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '756594';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '756594';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '756618';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'CLEVELAND MULTI SEG REP' WHERE COST_CENTER_CODE = '756618';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '756618';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '756618';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '756638';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'SAN ANTONIO MULTI SEG REP' WHERE COST_CENTER_CODE = '756638';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '756638';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '756638';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '756650';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'BIRMINGHAM COMM REP' WHERE COST_CENTER_CODE = '756650';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '756650';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'CM' WHERE COST_CENTER_CODE = '756650';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '756660';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WESTERN NEW YORK RES REPAINT REP' WHERE COST_CENTER_CODE = '756660';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '756660';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '756660';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '756702';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'DALLAS-FT WORTH MULTI SEG REP' WHERE COST_CENTER_CODE = '756702';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '756702';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '756702';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '756713';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'LONG ISLAND RES REPAINT REP' WHERE COST_CENTER_CODE = '756713';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '756713';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '756713';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '756716';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'CARIBBEAN COMM REP' WHERE COST_CENTER_CODE = '756716';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '756716';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'CM' WHERE COST_CENTER_CODE = '756716';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '756726';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'DETROIT MULTI SEG REP' WHERE COST_CENTER_CODE = '756726';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '756726';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '756726';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '756740';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'CAL COAST MULTI SEG REP' WHERE COST_CENTER_CODE = '756740';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '756740';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '756740';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '756760';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'SPRINGFIELD MULTI SEG REP' WHERE COST_CENTER_CODE = '756760';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '756760';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '756760';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '756771';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'RALEIGH METRO MULTI SEG REP' WHERE COST_CENTER_CODE = '756771';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '756771';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '756771';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '756785';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'ATLANTA MULTI SEG REP' WHERE COST_CENTER_CODE = '756785';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '756785';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '756785';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '756808';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'SOUTH FLORIDA METRO RES REPAINT REP' WHERE COST_CENTER_CODE = '756808';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '756808';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '756808';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '756827';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'SOUTH FLORIDA METRO MULTI SEG REP' WHERE COST_CENTER_CODE = '756827';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '756827';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '756827';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '756857';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'GREENVILLE MULTI SEG REP' WHERE COST_CENTER_CODE = '756857';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '756857';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '756857';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '756859';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'SOUTH FLORIDA METRO MULTI SEG REP' WHERE COST_CENTER_CODE = '756859';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '756859';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '756859';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '756919';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'METRO NEW YORK COMM REP' WHERE COST_CENTER_CODE = '756919';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '756919';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'CM' WHERE COST_CENTER_CODE = '756919';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '757839';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'CALIFORNIA NORTH MULTI SEG REP' WHERE COST_CENTER_CODE = '757839';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '757839';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '757839';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '757871';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'COLUMBIA NEW RES REP' WHERE COST_CENTER_CODE = '757871';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '757871';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'NR' WHERE COST_CENTER_CODE = '757871';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '757888';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'SOUTHWEST FL METRO MULTI SEG REP' WHERE COST_CENTER_CODE = '757888';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '757888';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '757888';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '757889';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'PUERTO RICO MULTI SEG REP' WHERE COST_CENTER_CODE = '757889';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '757889';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '757889';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '757932';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'SAN FERNANDO MULTI SEG REP' WHERE COST_CENTER_CODE = '757932';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '757932';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '757932';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '757981';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'DAKOTAS MULTI SEG REP' WHERE COST_CENTER_CODE = '757981';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '757981';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '757981';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '758346';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'LOUISIANA RES REPAINT REP' WHERE COST_CENTER_CODE = '758346';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '758346';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '758346';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '758396';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'AUSTIN MULTI SEG REP' WHERE COST_CENTER_CODE = '758396';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '758396';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '758396';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '764552';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'OTTAWA MULTI SEG REP' WHERE COST_CENTER_CODE = '764552';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '764552';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '764552';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '766098';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'BRITISH COLUMBIA MULTI SEG REP' WHERE COST_CENTER_CODE = '766098';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '766098';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '766098';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '766317';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'TORONTO METRO RES REPAINT REP' WHERE COST_CENTER_CODE = '766317';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '766317';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '766317';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '766823';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'SOUTHWEST ONTARIO RES REPAINT REP' WHERE COST_CENTER_CODE = '766823';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '766823';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '766823';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '768391';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'TORONTO METRO PROP MAINT REP' WHERE COST_CENTER_CODE = '768391';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '768391';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'PM' WHERE COST_CENTER_CODE = '768391';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q031';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'CAL COAST RES REPAINT REP' WHERE COST_CENTER_CODE = '75Q031';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '75Q031';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '75Q031';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q036';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'CALIFORNIA CENTRAL MULTI SEG REP' WHERE COST_CENTER_CODE = '75Q036';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '75Q036';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '75Q036';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q037';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'CALIFORNIA CENTRAL RES REPAINT REP' WHERE COST_CENTER_CODE = '75Q037';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '75Q037';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '75Q037';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q047';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'SAN FERNANDO MULTI SEG REP' WHERE COST_CENTER_CODE = '75Q047';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '75Q047';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '75Q047';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q101';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'LOS ANGELES RES REPAINT REP' WHERE COST_CENTER_CODE = '75Q101';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '75Q101';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '75Q101';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q102';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'LOS ANGELES PROP MAINT REP' WHERE COST_CENTER_CODE = '75Q102';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '75Q102';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'PM' WHERE COST_CENTER_CODE = '75Q102';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q112';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'NORTHERN COLORADO MULTI SEG REP' WHERE COST_CENTER_CODE = '75Q112';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '75Q112';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '75Q112';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q124';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'SOUTHERN COLORADO MULTI SEG REP' WHERE COST_CENTER_CODE = '75Q124';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '75Q124';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '75Q124';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q157';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'HOUSTON RES REPAINT REP' WHERE COST_CENTER_CODE = '75Q157';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '75Q157';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '75Q157';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q160';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'HOUSTON RES REPAINT REP' WHERE COST_CENTER_CODE = '75Q160';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '75Q160';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '75Q160';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q181';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'NEW MEXICO MULTI SEG REP' WHERE COST_CENTER_CODE = '75Q181';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '75Q181';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '75Q181';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q185';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'EL PASO MULTI SEG REP' WHERE COST_CENTER_CODE = '75Q185';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '75Q185';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '75Q185';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q197';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'ORLANDO PROP MAINT REP' WHERE COST_CENTER_CODE = '75Q197';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '75Q197';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'PM' WHERE COST_CENTER_CODE = '75Q197';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q210';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'SOUTH FLORIDA METRO RES REPAINT REP' WHERE COST_CENTER_CODE = '75Q210';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '75Q210';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '75Q210';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q223';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'TAMPA RES REPAINT REP' WHERE COST_CENTER_CODE = '75Q223';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '75Q223';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '75Q223';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q353';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'CENTRAL IL MULTI SEG REP' WHERE COST_CENTER_CODE = '75Q353';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '75Q353';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '75Q353';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q427';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'METRO CONNECTICUT RES REPAINT REP' WHERE COST_CENTER_CODE = '75Q427';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '75Q427';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '75Q427';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q431';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'METRO NEW YORK MULTI SEG REP' WHERE COST_CENTER_CODE = '75Q431';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '75Q431';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '75Q431';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q442';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'PHILADELPHIA MULTI SEG REP' WHERE COST_CENTER_CODE = '75Q442';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '75Q442';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '75Q442';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q452';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'METRO NEW JERSEY MULTI SEG REP' WHERE COST_CENTER_CODE = '75Q452';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '75Q452';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '75Q452';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q466';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'LONG ISLAND MULTI SEG REP' WHERE COST_CENTER_CODE = '75Q466';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '75Q466';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '75Q466';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q467';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'METRO NEW YORK MULTI SEG REP' WHERE COST_CENTER_CODE = '75Q467';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '75Q467';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '75Q467';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q478';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'NEW JERSEY COASTAL RES REPAINT REP' WHERE COST_CENTER_CODE = '75Q478';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '75Q478';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '75Q478';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q480';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'BOSTON RES REPAINT REP' WHERE COST_CENTER_CODE = '75Q480';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '75Q480';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '75Q480';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q508';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'PUERTO RICO MULTI SEG REP' WHERE COST_CENTER_CODE = '75Q508';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '75Q508';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '75Q508';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q509';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'ASHEVILLE MULTI SEG REP' WHERE COST_CENTER_CODE = '75Q509';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '75Q509';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '75Q509';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q517';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'LOUISIANA RES REPAINT REP' WHERE COST_CENTER_CODE = '75Q517';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '75Q517';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '75Q517';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q524';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'TAMPA PROP MAINT REP' WHERE COST_CENTER_CODE = '75Q524';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '75Q524';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'PM' WHERE COST_CENTER_CODE = '75Q524';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q543';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'ATLANTA COMM REP' WHERE COST_CENTER_CODE = '75Q543';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '75Q543';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'CM' WHERE COST_CENTER_CODE = '75Q543';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q547';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'ATLANTA MULTI SEG REP' WHERE COST_CENTER_CODE = '75Q547';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '75Q547';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '75Q547';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q549';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'EAST COAST FLORIDA MULTI SEG REP' WHERE COST_CENTER_CODE = '75Q549';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '75Q549';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '75Q549';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q573';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'LOUISIANA RES REPAINT REP' WHERE COST_CENTER_CODE = '75Q573';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '75Q573';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '75Q573';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q604';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'KANSAS CITY RES REPAINT REP' WHERE COST_CENTER_CODE = '75Q604';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '75Q604';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '75Q604';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q615';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'CALIFORNIA BAY MULTI SEG REP' WHERE COST_CENTER_CODE = '75Q615';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '75Q615';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '75Q615';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q629';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'CALIFORNIA NORTH MULTI SEG REP' WHERE COST_CENTER_CODE = '75Q629';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '75Q629';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '75Q629';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q663';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'CALIFORNIA CENTRAL RES REPAINT REP' WHERE COST_CENTER_CODE = '75Q663';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '75Q663';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '75Q663';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q714';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'DALLAS-FT WORTH COMM REP' WHERE COST_CENTER_CODE = '75Q714';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '75Q714';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'CM' WHERE COST_CENTER_CODE = '75Q714';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q734';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'ORLANDO MULTI SEG REP' WHERE COST_CENTER_CODE = '75Q734';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '75Q734';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '75Q734';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q765';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'GREEN BAY MULTI SEG REP' WHERE COST_CENTER_CODE = '75Q765';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '75Q765';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '75Q765';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q906';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'CHARLESTON METRO MULTI SEG REP' WHERE COST_CENTER_CODE = '75Q906';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '75Q906';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '75Q906';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q907';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'CHARLOTTE METRO NEW RES REP' WHERE COST_CENTER_CODE = '75Q907';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '75Q907';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'NR' WHERE COST_CENTER_CODE = '75Q907';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q996';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'BOSTON RES REPAINT REP' WHERE COST_CENTER_CODE = '75Q996';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '75Q996';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '75Q996';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '76Q255';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'NORTHERN ALBERTA MULTI SEG REP' WHERE COST_CENTER_CODE = '76Q255';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '76Q255';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '76Q255';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '76Q261';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'SOUTHERN ALBERTA COMM REP' WHERE COST_CENTER_CODE = '76Q261';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '76Q261';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'CM' WHERE COST_CENTER_CODE = '76Q261';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '76Q271';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'SOUTHWEST ONTARIO PROP MAINT REP' WHERE COST_CENTER_CODE = '76Q271';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '76Q271';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'PM' WHERE COST_CENTER_CODE = '76Q271';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '76Q796';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'MONTREAL COMM REP' WHERE COST_CENTER_CODE = '76Q796';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '76Q796';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'CM' WHERE COST_CENTER_CODE = '76Q796';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '76Q866';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'MONTREAL MULTI SEG REP' WHERE COST_CENTER_CODE = '76Q866';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '76Q866';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '76Q866';
--1 Row(s) Updated

COMMIT;

DECLARE
    V_BULK_LOAD_LKUP_ID     NUMBER := 141;
BEGIN
    POS_DATA_GENERATION.RESET_FLAG_POLLING_BULK_LOADS(V_BULK_LOAD_LKUP_ID);
END;
