/*
Created : 02/13/2018 mxv711 CCN Project Team....
          Below script will insert a new address type for LATIN AMERICAN COST CENTERS
*/

INSERT INTO CODE_DETAIL VALUES ('CATEGORY', 'COD', 'C', 'LAD CUSTOMER', 'N', NULL, NULL, 8, NULL, NULL);
            
INSERT INTO INSERTORDER
SELECT 'LAD_CUSTOMER', 22 FROM DUAL
 UNION
SELECT TABLE_NAME, TABLE_ORDER + 1 FROM INSERTORDER WHERE TABLE_ORDER > 21;

COMMIT;