/*
Created : 02/13/2018 mxv711 CCN Project Team....
          Below script will insert a new address type for LATIN AMERICAN COST CENTERS
*/
      INSERT INTO CODE_DETAIL (CODE_HEADER_NAME,CODE_HEADER_TYPE,CODE_DETAIL_VALUE,CODE_DETAIL_DESCRIPTION,CODE_DETAIL_EXPIRE_FLAG,
                               CODE_DETAIL_EXPIRE_USER,CODE_DETAIL_EXPIRE_EFF_DATE,CODE_DETAIL_ID,CODE_DETAIL_CREATE_USER,CODE_DETAIL_EFF_DATE)
            VALUES('CATEGORY', 'COD', 'C', 'LAD CUSTOMER', 'N', NULL, NULL, 9, NULL, NULL);
            
      Insert into INSERTORDER (TABLE_NAME,TABLE_ORDER) values ('LAD_CUSTOMER',36);

COMMIT;