SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE IN (
'754014','754036','754061','764072','754095','754171','754173','754190','764201','754209','754232','764284','754293','754296','754472','754512','754529','754554','754583','754601','754637','754664','754679','754682','754698','754744','754745','754793','754850','754876','754892','754903','754929','755516','755524','755535','755594','755838','755893','755908','755911','755962','755969','756059','756060','756073','756121','756149','756150','756161','756176','756204','756260','756380','756398','756429','756433','756479','756490','756568','756570','756585','756606','756650','756658','756660','756687','756716','756731','756794','756812','756819','756828','756902','756922','756930','756955','756983','766989','757838','757839','757846','757872','757932','757975','758311','768312','758319','758321','758356','758364','758379','758389','758401','758418','75Q009','75Q037','75Q060','75Q105','75Q138','75Q164','75Q185','75Q201','76Q241','76Q261','76Q273','76Q276','76Q323','75Q382','75Q452','75Q499','75Q500','75Q538','75Q589','75Q597','75Q691','76Q720','75Q734','75Q839','76Q854','76Q865','76Q866','76Q876','76Q886','76Q890','76Q896','75Q906','75Q926','75Q927','76Q959','75Q988','75Q994','75Q995','75Q997','75R022','76R084','76R086','75R149','75R176','75R180','75R183','75R206'
) ORDER BY 1;


SELECT * FROM TERRITORY WHERE COST_CENTER_CODE IN (
'754014','754036','754061','764072','754095','754171','754173','754190','764201','754209','754232','764284','754293','754296','754472','754512','754529','754554','754583','754601','754637','754664','754679','754682','754698','754744','754745','754793','754850','754876','754892','754903','754929','755516','755524','755535','755594','755838','755893','755908','755911','755962','755969','756059','756060','756073','756121','756149','756150','756161','756176','756204','756260','756380','756398','756429','756433','756479','756490','756568','756570','756585','756606','756650','756658','756660','756687','756716','756731','756794','756812','756819','756828','756902','756922','756930','756955','756983','766989','757838','757839','757846','757872','757932','757975','758311','768312','758319','758321','758356','758364','758379','758389','758401','758418','75Q009','75Q037','75Q060','75Q105','75Q138','75Q164','75Q185','75Q201','76Q241','76Q261','76Q273','76Q276','76Q323','75Q382','75Q452','75Q499','75Q500','75Q538','75Q589','75Q597','75Q691','76Q720','75Q734','75Q839','76Q854','76Q865','76Q866','76Q876','76Q886','76Q890','76Q896','75Q906','75Q926','75Q927','76Q959','75Q988','75Q994','75Q995','75Q997','75R022','76R084','76R086','75R149','75R176','75R180','75R183','75R206'
) ORDER BY 1;

/*
Below script will update the description of 142 cost centers as requested by Pat Malloy

Created : 9/9/2019 jxc517 CCN Project Team....CCNCC-187
Changed : 9/9/2019 axm868 CCN Project Team....CCNCC-187
          Updated the Names of the Cost Center Codes :
          754209, 754296, 754583, 755524, 75Q597, and 75Q988 
*/
SET SERVEROUTPUT ON;
DECLARE
    V_BULK_LOAD_LKUP_ID     NUMBER;
BEGIN
    POS_DATA_GENERATION.SET_FLAG_POLLING_BULK_LOADS('CCNCC-187', V_BULK_LOAD_LKUP_ID);
    DBMS_OUTPUT.PUT_LINE(V_BULK_LOAD_LKUP_ID);
END;


SET SCAN OFF;

SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '754014';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'LOS ANGELES  RES REPAINT REP' WHERE COST_CENTER_CODE = '754014';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '754014';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '754014';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '754036';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'CAPITAL  MULTI SEG REP' WHERE COST_CENTER_CODE = '754036';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '754036';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '754036';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '754061';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'SOUTH FLORIDA METRO  COMM REP' WHERE COST_CENTER_CODE = '754061';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '754061';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'CM' WHERE COST_CENTER_CODE = '754061';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '764072';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'TORONTO METRO  COMM REP' WHERE COST_CENTER_CODE = '764072';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '764072';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'CM' WHERE COST_CENTER_CODE = '764072';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '754095';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'ORLANDO  MULTI SEG REP' WHERE COST_CENTER_CODE = '754095';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '754095';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '754095';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '754171';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'PORTLAND  RES REPAINT REP' WHERE COST_CENTER_CODE = '754171';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '754171';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '754171';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '754173';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'PORTLAND  RES REPAINT REP' WHERE COST_CENTER_CODE = '754173';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '754173';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '754173';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '754190';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'METRO NEW JERSEY  RES REPAINT REP' WHERE COST_CENTER_CODE = '754190';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '754190';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '754190';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '764201';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'MANITOBA  COMM REP' WHERE COST_CENTER_CODE = '764201';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '764201';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'CM' WHERE COST_CENTER_CODE = '764201';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '754209';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'SOUTHWEST FL METRO MULTI SEG REP' WHERE COST_CENTER_CODE = '754209';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '754209';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '754209';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '754232';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'METRO NEW YORK  PROP MAINT REP' WHERE COST_CENTER_CODE = '754232';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '754232';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'PM' WHERE COST_CENTER_CODE = '754232';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '764284';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'SOUTHWEST ONTARIO  PROP MAINT REP' WHERE COST_CENTER_CODE = '764284';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '764284';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'PM' WHERE COST_CENTER_CODE = '764284';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '754293';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'METRO NEW YORK  COMM REP' WHERE COST_CENTER_CODE = '754293';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '754293';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'CM' WHERE COST_CENTER_CODE = '754293';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '754296';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'SOUTH FL METRO PROP MGMT REP' WHERE COST_CENTER_CODE = '754296';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '754296';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'PM' WHERE COST_CENTER_CODE = '754296';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '754472';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'METRO NEW YORK  PROP MAINT REP' WHERE COST_CENTER_CODE = '754472';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '754472';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'PM' WHERE COST_CENTER_CODE = '754472';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '754512';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'DELMAR  MULTI SEG REP' WHERE COST_CENTER_CODE = '754512';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '754512';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '754512';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '754529';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'ASHEVILLE  PROP MAINT REP' WHERE COST_CENTER_CODE = '754529';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '754529';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'PM' WHERE COST_CENTER_CODE = '754529';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '754554';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'CHARLESTON METRO  COMM REP' WHERE COST_CENTER_CODE = '754554';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '754554';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'CM' WHERE COST_CENTER_CODE = '754554';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '754583';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'SOUTHWEST FL METRO RES REPAINT REP' WHERE COST_CENTER_CODE = '754583';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '754583';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '754583';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '754601';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'METRO CONNECTICUT  RES REPAINT REP' WHERE COST_CENTER_CODE = '754601';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '754601';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '754601';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '754637';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'PORTLAND  MULTI SEG REP' WHERE COST_CENTER_CODE = '754637';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '754637';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '754637';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '754664';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'CALIFORNIA NORTH  COMM REP' WHERE COST_CENTER_CODE = '754664';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '754664';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'CM' WHERE COST_CENTER_CODE = '754664';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '754679';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'ARIZONA  COMM REP' WHERE COST_CENTER_CODE = '754679';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '754679';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'CM' WHERE COST_CENTER_CODE = '754679';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '754682';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'CALIFORNIA NORTH  MULTI SEG REP' WHERE COST_CENTER_CODE = '754682';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '754682';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '754682';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '754698';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'CHICAGO METRO  COMM REP' WHERE COST_CENTER_CODE = '754698';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '754698';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'CM' WHERE COST_CENTER_CODE = '754698';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '754744';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'PHOENIX  COMM REP' WHERE COST_CENTER_CODE = '754744';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '754744';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'CM' WHERE COST_CENTER_CODE = '754744';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '754745';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'OKLAHOMA CITY  COMM REP' WHERE COST_CENTER_CODE = '754745';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '754745';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'CM' WHERE COST_CENTER_CODE = '754745';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '754793';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'CHICAGO METRO  NEW RES REP' WHERE COST_CENTER_CODE = '754793';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '754793';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'NR' WHERE COST_CENTER_CODE = '754793';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '754850';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'CENTRAL PENNSYLVANIA  COMM REP' WHERE COST_CENTER_CODE = '754850';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '754850';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'CM' WHERE COST_CENTER_CODE = '754850';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '754876';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'CENTRAL FLORIDA  COMM REP' WHERE COST_CENTER_CODE = '754876';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '754876';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'CM' WHERE COST_CENTER_CODE = '754876';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '754892';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'DETROIT  COMM REP' WHERE COST_CENTER_CODE = '754892';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '754892';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'CM' WHERE COST_CENTER_CODE = '754892';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '754903';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'PUERTO RICO  MULTI SEG REP' WHERE COST_CENTER_CODE = '754903';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '754903';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '754903';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '754929';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'MADISON  MULTI SEG REP' WHERE COST_CENTER_CODE = '754929';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '754929';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '754929';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '755516';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'PITTSBURGH  PROP MAINT REP' WHERE COST_CENTER_CODE = '755516';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '755516';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'PM' WHERE COST_CENTER_CODE = '755516';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '755524';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'CENTRAL PA MULTI SEG REP' WHERE COST_CENTER_CODE = '755524';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '755524';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '755524';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '755535';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'NY CAPITAL  MULTI SEG REP' WHERE COST_CENTER_CODE = '755535';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '755535';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '755535';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '755594';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'DELMAR  RES REPAINT REP' WHERE COST_CENTER_CODE = '755594';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '755594';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '755594';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '755838';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'NEW MEXICO  PROP MAINT REP' WHERE COST_CENTER_CODE = '755838';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '755838';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'PM' WHERE COST_CENTER_CODE = '755838';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '755893';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'CALIFORNIA BAY  RES REPAINT REP' WHERE COST_CENTER_CODE = '755893';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '755893';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '755893';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '755908';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'ROANOKE  RES REPAINT REP' WHERE COST_CENTER_CODE = '755908';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '755908';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '755908';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '755911';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'METRO NEW YORK  MULTI SEG REP' WHERE COST_CENTER_CODE = '755911';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '755911';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '755911';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '755962';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'NORTH CONNECTICUT  MULTI SEG REP' WHERE COST_CENTER_CODE = '755962';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '755962';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '755962';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '755969';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'CAL COAST  MULTI SEG REP' WHERE COST_CENTER_CODE = '755969';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '755969';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '755969';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '756059';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'ATLANTA  RES REPAINT REP' WHERE COST_CENTER_CODE = '756059';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '756059';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '756059';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '756060';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'GREENVILLE  NEW RES REP' WHERE COST_CENTER_CODE = '756060';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '756060';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'NR' WHERE COST_CENTER_CODE = '756060';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '756073';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'TWIN CITIES  MULTI SEG REP' WHERE COST_CENTER_CODE = '756073';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '756073';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '756073';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '756121';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'CAPITAL  MULTI SEG REP' WHERE COST_CENTER_CODE = '756121';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '756121';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '756121';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '756149';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'PITTSBURGH  COMM REP' WHERE COST_CENTER_CODE = '756149';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '756149';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'CM' WHERE COST_CENTER_CODE = '756149';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '756150';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'ROANOKE  MULTI SEG REP' WHERE COST_CENTER_CODE = '756150';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '756150';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '756150';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '756161';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'RALEIGH METRO  PROP MAINT REP' WHERE COST_CENTER_CODE = '756161';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '756161';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'PM' WHERE COST_CENTER_CODE = '756161';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '756176';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'SOUTHWEST FLORIDA METRO  COMM REP' WHERE COST_CENTER_CODE = '756176';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '756176';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'CM' WHERE COST_CENTER_CODE = '756176';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '756204';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'GRAND RAPIDS  COMM REP' WHERE COST_CENTER_CODE = '756204';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '756204';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'CM' WHERE COST_CENTER_CODE = '756204';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '756260';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'SOUTHERN ALABAMA  COMM REP' WHERE COST_CENTER_CODE = '756260';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '756260';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'CM' WHERE COST_CENTER_CODE = '756260';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '756380';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'CAPITAL  RES REPAINT REP' WHERE COST_CENTER_CODE = '756380';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '756380';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '756380';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '756398';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'MONTANA  NEW RES REP' WHERE COST_CENTER_CODE = '756398';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '756398';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'NR' WHERE COST_CENTER_CODE = '756398';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '756429';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'NORFOLK  MULTI SEG REP' WHERE COST_CENTER_CODE = '756429';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '756429';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '756429';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '756433';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'RICHMOND  RES REPAINT REP' WHERE COST_CENTER_CODE = '756433';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '756433';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '756433';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '756479';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WILMINGTON  MULTI SEG REP' WHERE COST_CENTER_CODE = '756479';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '756479';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '756479';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '756490';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'ATLANTA  RES REPAINT REP' WHERE COST_CENTER_CODE = '756490';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '756490';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '756490';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '756568';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'NORTHEAST PA  MULTI SEG REP' WHERE COST_CENTER_CODE = '756568';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '756568';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '756568';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '756570';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'CHARLESTON WV  COMM REP' WHERE COST_CENTER_CODE = '756570';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '756570';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'CM' WHERE COST_CENTER_CODE = '756570';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '756585';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'PORTLAND  MULTI SEG REP' WHERE COST_CENTER_CODE = '756585';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '756585';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '756585';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '756606';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'METRO NEW JERSEY  COMM REP' WHERE COST_CENTER_CODE = '756606';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '756606';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'CM' WHERE COST_CENTER_CODE = '756606';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '756650';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'BIRMINGHAM  MULTI SEG REP' WHERE COST_CENTER_CODE = '756650';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '756650';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '756650';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '756658';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'LONG ISLAND  PROP MAINT REP' WHERE COST_CENTER_CODE = '756658';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '756658';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'PM' WHERE COST_CENTER_CODE = '756658';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '756660';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WESTERN NEW YORK  MULTI SEG REP' WHERE COST_CENTER_CODE = '756660';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '756660';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '756660';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '756687';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'ARIZONA  MULTI SEG REP' WHERE COST_CENTER_CODE = '756687';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '756687';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '756687';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '756716';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'CARIBBEAN  COMM REP' WHERE COST_CENTER_CODE = '756716';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '756716';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'CM' WHERE COST_CENTER_CODE = '756716';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '756731';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'HOUSTON  MULTI SEG REP' WHERE COST_CENTER_CODE = '756731';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '756731';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '756731';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '756794';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'INDIANAPOLIS  COMM REP' WHERE COST_CENTER_CODE = '756794';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '756794';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'CM' WHERE COST_CENTER_CODE = '756794';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '756812';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'HAWAII  MULTI SEG REP' WHERE COST_CENTER_CODE = '756812';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '756812';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '756812';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '756819';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'PUERTO RICO  MULTI SEG REP' WHERE COST_CENTER_CODE = '756819';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '756819';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '756819';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '756828';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'RICHMOND  RES REPAINT REP' WHERE COST_CENTER_CODE = '756828';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '756828';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '756828';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '756902';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'NEW MEXICO  COMM REP' WHERE COST_CENTER_CODE = '756902';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '756902';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'CM' WHERE COST_CENTER_CODE = '756902';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '756922';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'PHILADELPHIA  MULTI SEG REP' WHERE COST_CENTER_CODE = '756922';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '756922';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '756922';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '756930';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'PITTSBURGH  RES REPAINT REP' WHERE COST_CENTER_CODE = '756930';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '756930';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '756930';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '756955';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'MONTANA  NEW RES REP' WHERE COST_CENTER_CODE = '756955';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '756955';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'NR' WHERE COST_CENTER_CODE = '756955';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '756983';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'MONTANA  MULTI SEG REP' WHERE COST_CENTER_CODE = '756983';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '756983';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '756983';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '766989';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'SOUTHWEST ONTARIO  MULTI SEG REP' WHERE COST_CENTER_CODE = '766989';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '766989';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '766989';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '757838';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'ATLANTA  MULTI SEG REP' WHERE COST_CENTER_CODE = '757838';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '757838';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '757838';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '757839';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'CALIFORNIA NORTH  COMM REP' WHERE COST_CENTER_CODE = '757839';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '757839';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'CM' WHERE COST_CENTER_CODE = '757839';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '757846';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'RALEIGH METRO  MULTI SEG REP' WHERE COST_CENTER_CODE = '757846';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '757846';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '757846';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '757872';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'SAN DIEGO  MULTI SEG REP' WHERE COST_CENTER_CODE = '757872';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '757872';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '757872';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '757932';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'SAN FERNANDO  RES REPAINT REP' WHERE COST_CENTER_CODE = '757932';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '757932';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '757932';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '757975';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'METRO NEW JERSEY  COMM REP' WHERE COST_CENTER_CODE = '757975';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '757975';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'CM' WHERE COST_CENTER_CODE = '757975';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '758311';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'NORTHEAST PA  RES REPAINT REP' WHERE COST_CENTER_CODE = '758311';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '758311';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '758311';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '768312';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'TORONTO METRO  COMM REP' WHERE COST_CENTER_CODE = '768312';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '768312';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'CM' WHERE COST_CENTER_CODE = '768312';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '758319';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'NORTHEAST PA  MULTI SEG REP' WHERE COST_CENTER_CODE = '758319';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '758319';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '758319';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '758321';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'NASHVILLE  COMM REP' WHERE COST_CENTER_CODE = '758321';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '758321';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'CM' WHERE COST_CENTER_CODE = '758321';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '758356';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'ORLANDO  COMM REP' WHERE COST_CENTER_CODE = '758356';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '758356';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'CM' WHERE COST_CENTER_CODE = '758356';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '758364';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'ST LOUIS  PROP MAINT REP' WHERE COST_CENTER_CODE = '758364';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '758364';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'PM' WHERE COST_CENTER_CODE = '758364';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '758379';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'HAWAII  MULTI SEG REP' WHERE COST_CENTER_CODE = '758379';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '758379';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '758379';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '758389';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'SOUTH FLORIDA METRO  COMM REP' WHERE COST_CENTER_CODE = '758389';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '758389';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'CM' WHERE COST_CENTER_CODE = '758389';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '758401';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'MONTANA  RES REPAINT REP' WHERE COST_CENTER_CODE = '758401';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '758401';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '758401';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '758418';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'SPOKANE  NEW RES REP' WHERE COST_CENTER_CODE = '758418';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '758418';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'NR' WHERE COST_CENTER_CODE = '758418';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q009';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'SPOKANE  MULTI SEG REP' WHERE COST_CENTER_CODE = '75Q009';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '75Q009';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '75Q009';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q037';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'CALIFORNIA CENTRAL  MULTI SEG REP' WHERE COST_CENTER_CODE = '75Q037';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '75Q037';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '75Q037';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q060';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'LAS VEGAS  PROP MAINT REP' WHERE COST_CENTER_CODE = '75Q060';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '75Q060';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'PM' WHERE COST_CENTER_CODE = '75Q060';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q105';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'LOS ANGELES  MULTI SEG REP' WHERE COST_CENTER_CODE = '75Q105';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '75Q105';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '75Q105';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q138';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'DALLAS-FT WORTH  RES REPAINT REP' WHERE COST_CENTER_CODE = '75Q138';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '75Q138';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '75Q138';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q164';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'SALT LAKE CITY  NEW RES REP' WHERE COST_CENTER_CODE = '75Q164';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '75Q164';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'NR' WHERE COST_CENTER_CODE = '75Q164';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q185';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'EL PASO  RES REPAINT REP' WHERE COST_CENTER_CODE = '75Q185';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '75Q185';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '75Q185';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q201';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'FLORIDA PANHANDLE  MULTI SEG REP' WHERE COST_CENTER_CODE = '75Q201';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '75Q201';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '75Q201';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '76Q241';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'BRITISH COLUMBIA  MULTI SEG REP' WHERE COST_CENTER_CODE = '76Q241';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '76Q241';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '76Q241';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '76Q261';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'SOUTHERN ALBERTA  MULTI SEG REP' WHERE COST_CENTER_CODE = '76Q261';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '76Q261';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '76Q261';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '76Q273';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'TORONTO METRO  MULTI SEG REP' WHERE COST_CENTER_CODE = '76Q273';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '76Q273';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '76Q273';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '76Q276';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'SOUTHWEST ONTARIO  PROP MAINT REP' WHERE COST_CENTER_CODE = '76Q276';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '76Q276';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'PM' WHERE COST_CENTER_CODE = '76Q276';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '76Q323';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'SASKATCHEWAN  COMM REP' WHERE COST_CENTER_CODE = '76Q323';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '76Q323';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'CM' WHERE COST_CENTER_CODE = '76Q323';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q382';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'CHICAGO METRO  PROP MAINT REP' WHERE COST_CENTER_CODE = '75Q382';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '75Q382';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'PM' WHERE COST_CENTER_CODE = '75Q382';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q452';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'METRO NEW JERSEY  RES REPAINT REP' WHERE COST_CENTER_CODE = '75Q452';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '75Q452';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '75Q452';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q499';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'NORTHERN  MULTI SEG REP' WHERE COST_CENTER_CODE = '75Q499';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '75Q499';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '75Q499';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q500';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'SOUTHERN ALABAMA  RES REPAINT REP' WHERE COST_CENTER_CODE = '75Q500';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '75Q500';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '75Q500';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q538';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'FLORIDA PANHANDLE  MULTI SEG REP' WHERE COST_CENTER_CODE = '75Q538';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '75Q538';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '75Q538';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q589';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'SOUTHERN ALABAMA  MULTI SEG REP' WHERE COST_CENTER_CODE = '75Q589';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '75Q589';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '75Q589';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q597';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'SOUTHWEST FL METRO MULTI SEG REP' WHERE COST_CENTER_CODE = '75Q597';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '75Q597';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '75Q597';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q691';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'CALIFORNIA BAY  MULTI SEG REP' WHERE COST_CENTER_CODE = '75Q691';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '75Q691';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '75Q691';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '76Q720';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'TORONTO METRO  RES REPAINT REP' WHERE COST_CENTER_CODE = '76Q720';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '76Q720';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '76Q720';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q734';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'CENTRAL FLORIDA  RES REPAINT REP' WHERE COST_CENTER_CODE = '75Q734';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '75Q734';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '75Q734';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q839';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'NORTHERN MICHIGAN  MULTI SEG REP' WHERE COST_CENTER_CODE = '75Q839';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '75Q839';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '75Q839';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '76Q854';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'MONTREAL  MULTI SEG REP' WHERE COST_CENTER_CODE = '76Q854';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '76Q854';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '76Q854';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '76Q865';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'QUEBEC  MULTI SEG REP' WHERE COST_CENTER_CODE = '76Q865';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '76Q865';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '76Q865';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '76Q866';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'MONTREAL  MULTI SEG REP' WHERE COST_CENTER_CODE = '76Q866';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '76Q866';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '76Q866';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '76Q876';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'ATLANTIC CANADA  COMM REP' WHERE COST_CENTER_CODE = '76Q876';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '76Q876';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'CM' WHERE COST_CENTER_CODE = '76Q876';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '76Q886';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'QUEBEC  MULTI SEG REP' WHERE COST_CENTER_CODE = '76Q886';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '76Q886';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '76Q886';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '76Q890';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'BRITISH COLUMBIA  PROP MAINT REP' WHERE COST_CENTER_CODE = '76Q890';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '76Q890';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'PM' WHERE COST_CENTER_CODE = '76Q890';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '76Q896';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'BRITISH COLUMBIA  PROP MAINT REP' WHERE COST_CENTER_CODE = '76Q896';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '76Q896';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'PM' WHERE COST_CENTER_CODE = '76Q896';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q906';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'CHARLESTON METRO  NEW RES REP' WHERE COST_CENTER_CODE = '75Q906';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '75Q906';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'NR' WHERE COST_CENTER_CODE = '75Q906';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q926';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'CARIBBEAN  MULTI SEG REP' WHERE COST_CENTER_CODE = '75Q926';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '75Q926';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '75Q926';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q927';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'CARIBBEAN  MULTI SEG REP' WHERE COST_CENTER_CODE = '75Q927';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '75Q927';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '75Q927';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '76Q959';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'SASKATCHEWAN  RES REPAINT REP' WHERE COST_CENTER_CODE = '76Q959';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '76Q959';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '76Q959';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q988';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'CENTRAL PA RES REPAINT REP' WHERE COST_CENTER_CODE = '75Q988';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '75Q988';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '75Q988';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q994';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'METRO NEW YORK  RES REPAINT REP' WHERE COST_CENTER_CODE = '75Q994';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '75Q994';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '75Q994';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q995';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'PHILADELPHIA  MULTI SEG REP' WHERE COST_CENTER_CODE = '75Q995';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '75Q995';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '75Q995';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '75Q997';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'LONG ISLAND  MULTI SEG REP' WHERE COST_CENTER_CODE = '75Q997';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '75Q997';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '75Q997';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '75R022';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'METRO NEW YORK  COMM REP' WHERE COST_CENTER_CODE = '75R022';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '75R022';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'CM' WHERE COST_CENTER_CODE = '75R022';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '76R084';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'QUEBEC  COMM REP' WHERE COST_CENTER_CODE = '76R084';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '76R084';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'CM' WHERE COST_CENTER_CODE = '76R084';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '76R086';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'TORONTO METRO  RES REPAINT REP' WHERE COST_CENTER_CODE = '76R086';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '76R086';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '76R086';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '75R149';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'CARIBBEAN  COMM REP' WHERE COST_CENTER_CODE = '75R149';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '75R149';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'CM' WHERE COST_CENTER_CODE = '75R149';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '75R176';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'CLEVELAND  PROP MAINT REP' WHERE COST_CENTER_CODE = '75R176';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '75R176';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'PM' WHERE COST_CENTER_CODE = '75R176';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '75R180';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'CLEVELAND  RES REPAINT REP' WHERE COST_CENTER_CODE = '75R180';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '75R180';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'RR' WHERE COST_CENTER_CODE = '75R180';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '75R183';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'PORTLAND  MULTI SEG REP' WHERE COST_CENTER_CODE = '75R183';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '75R183';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '75R183';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '75R206';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'CARIBBEAN  MULTI SEG REP' WHERE COST_CENTER_CODE = '75R206';
--1 Row(s) Updated
SELECT * FROM TERRITORY WHERE COST_CENTER_CODE = '75R206';
--1 Row(s) Selected
UPDATE TERRITORY SET TERRITORY_TYPE_BUSN_CODE = 'MS' WHERE COST_CENTER_CODE = '75R206';
--1 Row(s) Updated

COMMIT;

SET SERVEROUTPUT ON;
DECLARE
    V_BULK_LOAD_LKUP_ID     NUMBER := 4760;
BEGIN
    POS_DATA_GENERATION.RESET_FLAG_POLLING_BULK_LOADS(V_BULK_LOAD_LKUP_ID);
END;