SELECT COST_CENTER_CODE, COST_CENTER_NAME, CATEGORY FROM COST_CENTER WHERE COST_CENTER_CODE IN (
'784030','784047','784105','784233','784475','784547','784564','784572','784573','784652','784659','784680','784716','784738','784774','784796','784797','784818','784834','784839','784851','784884','784955','784961','784973','784987','785930','785959','786013','786021','786038','786124','786172','786195','786403','786419','786452','786463','786641','786642','786672','786676','786735','786756','786788','786810','786831','786848','786855','786884','786900','786978','786980','787827','787935','788392','78Q790','78Q791','78Q793','78Q794','78R270','78R271','79A324','79A332','79A599','79A615','79A689','79BX08','79BX09','79BX10','79BX11','79BX12','79BX13','79BX15','79BX16','79BX17','79BX18','79BX20','79V552','79V553','79V557','79V558','79V562','79V579','79V580','79V581','79X102','79X106','79X108','79X109','79X111','79X112','79X115','79X118','79X119','79X123','79X126','79X129','79X131','79X133','79X134','79X136','79X137','79X142','79X143','79X146','79X147','79X148','79X156','79X158','79X159','79X161','79X164','79X165','79X166','79X171','79X174','79X175','79X176','79X179','79X184','79X187','79X188','79X190','79X191','79X193','79X195','79X196','79X205','79X206','79X207','79X208','79X212','79X223','79X224','79X227','79X237','79X238','79X240','79X515','79X523','79X525','79X527','79X534','79X555','79X784','79X794','7P8217','830324','830332','830421','830470','830599','830600','830602','830614','830615','830689','830710','830792','830797','83BA07','83BA08','83BA09','83BA10','83BA11','83BA12','83BA13','83BA15','83BA16','83BA17','83BA18','83BA20','83BA40','83BA41','83BA42','83BA60','83BA65','83N102','83N106','83N108','83N109','83N111','83N112','83N115','83N118','83N119','83N123','83N126','83N129','83N131','83N133','83N134','83N136','83N137','83N142','83N143','83N146','83N147','83N148','83N153','83N156','83N158','83N159','83N161','83N164','83N165','83N166','83N171','83N172','83N174','83N175','83N176','83N179','83N184','83N187','83N188','83N190','83N191','83N193','83N195','83N196','83N202','83N205','83N206','83N207','83N208','83N212','83N217','83N218','83N223','83N224','83N227','83N228','83N234','83N237','83N238','83N240','83N269','83N342','83N494','83N500','83N515','83N517','83N523','83N524','83N525','83N527','83N534','83N555','83N710','83N730','83N750','83N751','83N752','83N777','83N780','83N781','83N784','83N791','83N792','83N793','83N794','83N796','83U551','83U552','83U553','83U557','83U558','83U562','83U579','83U580','83U581','83U748','83W012','83W016','83W030','8AU263'
) ORDER BY 1;

/*
Below script will update the description of 278 cost centers as requested by Pat Malloy

Created : 9/18/2018 jxc517 CCN Project Team....
Changed :
*/
SET SERVEROUTPUT ON;

DECLARE
    V_BULK_LOAD_LKUP_ID     NUMBER;
BEGIN
    POS_DATA_GENERATION.SET_FLAG_POLLING_BULK_LOADS('MANUAL_CC_DESC_UPDATE', V_BULK_LOAD_LKUP_ID);
    DBMS_OUTPUT.PUT_LINE(V_BULK_LOAD_LKUP_ID);
END;

SELECT * FROM POS_DOWNLOADS_BULK_LOADS_LKUP;

SET SCAN OFF;

SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '784030';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD EAST SALES REP' WHERE COST_CENTER_CODE = '784030';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '784047';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD EAST SALES REP' WHERE COST_CENTER_CODE = '784047';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '784105';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD WEST SALES REP' WHERE COST_CENTER_CODE = '784105';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '784233';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD EAST SALES REP' WHERE COST_CENTER_CODE = '784233';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '784475';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD EAST SALES REP' WHERE COST_CENTER_CODE = '784475';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '784547';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD EAST SALES REP' WHERE COST_CENTER_CODE = '784547';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '784564';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD EAST SALES REP' WHERE COST_CENTER_CODE = '784564';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '784572';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD WEST SALES REP' WHERE COST_CENTER_CODE = '784572';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '784573';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD EAST SALES REP' WHERE COST_CENTER_CODE = '784573';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '784652';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD WEST SALES REP' WHERE COST_CENTER_CODE = '784652';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '784659';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD WEST SALES REP' WHERE COST_CENTER_CODE = '784659';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '784680';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD WEST SALES REP' WHERE COST_CENTER_CODE = '784680';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '784716';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD EAST SALES REP' WHERE COST_CENTER_CODE = '784716';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '784738';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD EAST SALES REP' WHERE COST_CENTER_CODE = '784738';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '784774';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD WEST SALES REP' WHERE COST_CENTER_CODE = '784774';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '784796';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD WEST SALES REP' WHERE COST_CENTER_CODE = '784796';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '784797';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD WEST SALES REP' WHERE COST_CENTER_CODE = '784797';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '784818';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD WEST SALES REP' WHERE COST_CENTER_CODE = '784818';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '784834';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD WEST SALES REP' WHERE COST_CENTER_CODE = '784834';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '784839';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD WEST SALES REP' WHERE COST_CENTER_CODE = '784839';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '784851';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD EAST SALES REP' WHERE COST_CENTER_CODE = '784851';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '784884';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD EAST SALES REP' WHERE COST_CENTER_CODE = '784884';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '784955';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD WEST SALES REP' WHERE COST_CENTER_CODE = '784955';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '784961';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD WEST SALES REP' WHERE COST_CENTER_CODE = '784961';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '784973';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD WEST SALES REP' WHERE COST_CENTER_CODE = '784973';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '784987';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD WEST SALES REP' WHERE COST_CENTER_CODE = '784987';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '785930';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD EAST SALES REP' WHERE COST_CENTER_CODE = '785930';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '785959';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD WEST SALES REP' WHERE COST_CENTER_CODE = '785959';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '786013';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD EAST SALES REP' WHERE COST_CENTER_CODE = '786013';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '786021';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD WEST SALES REP' WHERE COST_CENTER_CODE = '786021';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '786038';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD WEST SALES REP' WHERE COST_CENTER_CODE = '786038';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '786124';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD EAST SALES REP' WHERE COST_CENTER_CODE = '786124';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '786172';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD WEST SALES REP' WHERE COST_CENTER_CODE = '786172';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '786195';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD WEST SALES REP' WHERE COST_CENTER_CODE = '786195';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '786403';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD WEST SALES REP' WHERE COST_CENTER_CODE = '786403';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '786419';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD EAST SALES REP' WHERE COST_CENTER_CODE = '786419';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '786452';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD EAST SALES REP' WHERE COST_CENTER_CODE = '786452';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '786463';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD EAST SALES REP' WHERE COST_CENTER_CODE = '786463';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '786641';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD WEST SALES REP' WHERE COST_CENTER_CODE = '786641';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '786642';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD WEST SALES REP' WHERE COST_CENTER_CODE = '786642';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '786672';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD EAST SALES REP' WHERE COST_CENTER_CODE = '786672';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '786676';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD EAST SALES REP' WHERE COST_CENTER_CODE = '786676';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '786735';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD WEST SALES REP' WHERE COST_CENTER_CODE = '786735';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '786756';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD WEST SALES REP' WHERE COST_CENTER_CODE = '786756';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '786788';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD EAST SALES REP' WHERE COST_CENTER_CODE = '786788';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '786810';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD WEST SALES REP' WHERE COST_CENTER_CODE = '786810';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '786831';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD EAST SALES REP' WHERE COST_CENTER_CODE = '786831';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '786848';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD EAST SALES REP' WHERE COST_CENTER_CODE = '786848';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '786855';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD WEST SALES REP' WHERE COST_CENTER_CODE = '786855';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '786884';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD EAST SALES REP' WHERE COST_CENTER_CODE = '786884';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '786900';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD WEST SALES REP' WHERE COST_CENTER_CODE = '786900';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '786978';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD EAST SALES REP' WHERE COST_CENTER_CODE = '786978';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '786980';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD WEST SALES REP' WHERE COST_CENTER_CODE = '786980';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '787827';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD WEST SALES REP' WHERE COST_CENTER_CODE = '787827';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '787935';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD WEST SALES REP' WHERE COST_CENTER_CODE = '787935';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '788392';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD WEST SALES REP' WHERE COST_CENTER_CODE = '788392';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '78Q790';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD EAST SALES REP' WHERE COST_CENTER_CODE = '78Q790';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '78Q791';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD WEST SALES REP' WHERE COST_CENTER_CODE = '78Q791';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '78Q793';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD EAST SALES REP' WHERE COST_CENTER_CODE = '78Q793';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '78Q794';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD WEST SALES REP' WHERE COST_CENTER_CODE = '78Q794';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '78R270';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD WEST SALES REP' WHERE COST_CENTER_CODE = '78R270';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '78R271';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD WEST SALES REP' WHERE COST_CENTER_CODE = '78R271';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '79A324';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD EAST SALES MGR ALLOC' WHERE COST_CENTER_CODE = '79A324';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '79A332';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD EAST SALES MGR ALLOC' WHERE COST_CENTER_CODE = '79A332';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '79A599';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD EAST TECH SVC REP ALLOC' WHERE COST_CENTER_CODE = '79A599';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '79A615';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD EAST TECH SVC REP ALLOC' WHERE COST_CENTER_CODE = '79A615';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '79A689';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD EAST TECH SVC REP ALLOC' WHERE COST_CENTER_CODE = '79A689';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '79BX08';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD EAST TECH SVC REP ALLOC' WHERE COST_CENTER_CODE = '79BX08';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '79BX09';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD SAM TECH SVC REP ALLOC' WHERE COST_CENTER_CODE = '79BX09';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '79BX10';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD SAM TECH SVC REP ALLOC' WHERE COST_CENTER_CODE = '79BX10';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '79BX11';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD SAM TECH SVC REP ALLOC' WHERE COST_CENTER_CODE = '79BX11';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '79BX12';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD SAM TECH SVC REP ALLOC' WHERE COST_CENTER_CODE = '79BX12';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '79BX13';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD SAM TECH SVC REP ALLOC' WHERE COST_CENTER_CODE = '79BX13';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '79BX15';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD SAM TECH SVC REP ALLOC' WHERE COST_CENTER_CODE = '79BX15';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '79BX16';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD SAM TECH SVC REP ALLOC' WHERE COST_CENTER_CODE = '79BX16';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '79BX17';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD SAM TECH SVC REP ALLOC' WHERE COST_CENTER_CODE = '79BX17';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '79BX18';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD SAM TECH SVC REP ALLOC' WHERE COST_CENTER_CODE = '79BX18';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '79BX20';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD SAM TECH SVC REP ALLOC' WHERE COST_CENTER_CODE = '79BX20';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '79V552';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD EAST TECH SVC REP ALLOC' WHERE COST_CENTER_CODE = '79V552';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '79V553';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD WEST TECH REP ALLOC' WHERE COST_CENTER_CODE = '79V553';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '79V557';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD EAST TECH SVC REP ALLOC' WHERE COST_CENTER_CODE = '79V557';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '79V558';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD WEST TECH REP ALLOC' WHERE COST_CENTER_CODE = '79V558';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '79V562';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD WEST SALES MGR ALLOC' WHERE COST_CENTER_CODE = '79V562';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '79V579';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD EAST TECH SVC REP ALLOC' WHERE COST_CENTER_CODE = '79V579';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '79V580';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD EAST TECH SVC REP ALLOC' WHERE COST_CENTER_CODE = '79V580';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '79V581';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD EAST TECH SVC REP ALLOC' WHERE COST_CENTER_CODE = '79V581';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '79X102';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD WEST TECH REP ALLOC' WHERE COST_CENTER_CODE = '79X102';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '79X106';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD WEST TECH REP ALLOC' WHERE COST_CENTER_CODE = '79X106';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '79X108';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD WEST TECH REP ALLOC' WHERE COST_CENTER_CODE = '79X108';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '79X109';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD WEST TECH REP ALLOC' WHERE COST_CENTER_CODE = '79X109';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '79X111';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD EAST TECH SVC REP ALLOC' WHERE COST_CENTER_CODE = '79X111';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '79X112';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD EAST TECH SVC REP ALLOC' WHERE COST_CENTER_CODE = '79X112';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '79X115';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD EAST SALES DIR ALLOC' WHERE COST_CENTER_CODE = '79X115';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '79X118';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD WEST TECH REP ALLOC' WHERE COST_CENTER_CODE = '79X118';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '79X119';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD WEST TECH REP ALLOC' WHERE COST_CENTER_CODE = '79X119';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '79X123';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD EAST SALES MGR ALLOC' WHERE COST_CENTER_CODE = '79X123';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '79X126';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD EAST TECH SVC REP ALLOC' WHERE COST_CENTER_CODE = '79X126';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '79X129';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD WEST TECH REP ALLOC' WHERE COST_CENTER_CODE = '79X129';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '79X131';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD WEST SALES MGR ALLOC' WHERE COST_CENTER_CODE = '79X131';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '79X133';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD SAM TECH SVC REP ALLOC' WHERE COST_CENTER_CODE = '79X133';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '79X134';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD WEST TECH REP ALLOC' WHERE COST_CENTER_CODE = '79X134';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '79X136';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD WEST SALES MGR ALLOC' WHERE COST_CENTER_CODE = '79X136';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '79X137';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD WEST TECH REP ALLOC' WHERE COST_CENTER_CODE = '79X137';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '79X142';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD WEST TECH MGR ALLOC' WHERE COST_CENTER_CODE = '79X142';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '79X143';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD WEST SALES DIR ALLOC' WHERE COST_CENTER_CODE = '79X143';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '79X146';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD EAST TECH SVC REP ALLOC' WHERE COST_CENTER_CODE = '79X146';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '79X147';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD EAST TECH SVC REP ALLOC' WHERE COST_CENTER_CODE = '79X147';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '79X148';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD EAST TECH SVC REP ALLOC' WHERE COST_CENTER_CODE = '79X148';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '79X156';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD EAST TECH SVC REP ALLOC' WHERE COST_CENTER_CODE = '79X156';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '79X158';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD EAST TECH SVC REP ALLOC' WHERE COST_CENTER_CODE = '79X158';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '79X159';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD EAST TECH SVC REP ALLOC' WHERE COST_CENTER_CODE = '79X159';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '79X161';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD EAST TECH SVC REP ALLOC' WHERE COST_CENTER_CODE = '79X161';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '79X164';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD WEST TECH REP ALLOC' WHERE COST_CENTER_CODE = '79X164';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '79X165';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD WEST TECH REP ALLOC' WHERE COST_CENTER_CODE = '79X165';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '79X166';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD EAST TECH SVC REP ALLOC' WHERE COST_CENTER_CODE = '79X166';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '79X171';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD WEST TECH REP ALLOC' WHERE COST_CENTER_CODE = '79X171';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '79X174';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD WEST TECH REP ALLOC' WHERE COST_CENTER_CODE = '79X174';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '79X175';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD WEST TECH REP ALLOC' WHERE COST_CENTER_CODE = '79X175';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '79X176';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD WEST TECH REP ALLOC' WHERE COST_CENTER_CODE = '79X176';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '79X179';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD WEST TECH REP ALLOC' WHERE COST_CENTER_CODE = '79X179';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '79X184';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD WEST TECH REP ALLOC' WHERE COST_CENTER_CODE = '79X184';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '79X187';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD WEST TECH REP ALLOC' WHERE COST_CENTER_CODE = '79X187';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '79X188';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD EAST TECH SVC REP ALLOC' WHERE COST_CENTER_CODE = '79X188';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '79X190';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD EAST TECH SVC REP ALLOC' WHERE COST_CENTER_CODE = '79X190';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '79X191';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD WEST TECH REP ALLOC' WHERE COST_CENTER_CODE = '79X191';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '79X193';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD WEST TECH REP ALLOC' WHERE COST_CENTER_CODE = '79X193';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '79X195';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD WEST TECH REP ALLOC' WHERE COST_CENTER_CODE = '79X195';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '79X196';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD WEST TECH REP ALLOC' WHERE COST_CENTER_CODE = '79X196';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '79X205';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD WEST SALES DIR ALLOC' WHERE COST_CENTER_CODE = '79X205';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '79X206';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD EAST TECH SVC REP ALLOC' WHERE COST_CENTER_CODE = '79X206';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '79X207';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD EAST TECH SVC REP ALLOC' WHERE COST_CENTER_CODE = '79X207';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '79X208';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD SAM TECH SVC REP ALLOC' WHERE COST_CENTER_CODE = '79X208';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '79X212';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD EAST SALES MGR ALLOC' WHERE COST_CENTER_CODE = '79X212';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '79X223';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD WEST TECH REP ALLOC' WHERE COST_CENTER_CODE = '79X223';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '79X224';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD EAST TECH SVC REP ALLOC' WHERE COST_CENTER_CODE = '79X224';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '79X227';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD EAST TECH SVC REP ALLOC' WHERE COST_CENTER_CODE = '79X227';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '79X237';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD WEST TECH REP ALLOC' WHERE COST_CENTER_CODE = '79X237';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '79X238';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD WEST TECH REP ALLOC' WHERE COST_CENTER_CODE = '79X238';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '79X240';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD WEST TECH REP ALLOC' WHERE COST_CENTER_CODE = '79X240';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '79X515';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD EAST TECH SVC REP ALLOC' WHERE COST_CENTER_CODE = '79X515';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '79X523';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD WEST TECH REP ALLOC' WHERE COST_CENTER_CODE = '79X523';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '79X525';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD WEST TECH REP ALLOC' WHERE COST_CENTER_CODE = '79X525';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '79X527';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD WEST TECH REP ALLOC' WHERE COST_CENTER_CODE = '79X527';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '79X534';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD EAST TECH SVC REP ALLOC' WHERE COST_CENTER_CODE = '79X534';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '79X555';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD EAST TECH SVC REP ALLOC' WHERE COST_CENTER_CODE = '79X555';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '79X784';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD EAST TECH SVC REP ALLOC' WHERE COST_CENTER_CODE = '79X784';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '79X794';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD WEST TECH REP ALLOC' WHERE COST_CENTER_CODE = '79X794';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '7P8217';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD FACTORY FINISH-AOM SALES' WHERE COST_CENTER_CODE = '7P8217';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '830324';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD EAST SALES MGR' WHERE COST_CENTER_CODE = '830324';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '830332';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD EAST SALES MGR' WHERE COST_CENTER_CODE = '830332';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '830421';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD NSM-BLDG PROD' WHERE COST_CENTER_CODE = '830421';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '830470';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD EAST TECH SVC REP' WHERE COST_CENTER_CODE = '830470';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '830599';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD EAST TECH SVC REP' WHERE COST_CENTER_CODE = '830599';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '830600';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD WEST TECH REP' WHERE COST_CENTER_CODE = '830600';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '830602';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD MKTG PROD MGR-KITCHEN WCBP' WHERE COST_CENTER_CODE = '830602';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '830614';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD WEST TECH REP' WHERE COST_CENTER_CODE = '830614';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '830615';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD EAST TECH SVC REP' WHERE COST_CENTER_CODE = '830615';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '830689';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD EAST TECH SVC REP' WHERE COST_CENTER_CODE = '830689';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '830710';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD MKTG BUS DIR-KITCHEN CAB' WHERE COST_CENTER_CODE = '830710';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '830792';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD MKTG DIR-NEW PROD DEV' WHERE COST_CENTER_CODE = '830792';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '830797';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD MKTG BUS DIR-FURNITURE' WHERE COST_CENTER_CODE = '830797';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '83BA07';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD SAM-FURNITURE' WHERE COST_CENTER_CODE = '83BA07';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '83BA08';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD EAST TECH SVC REP' WHERE COST_CENTER_CODE = '83BA08';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '83BA09';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD SAM TECH SVC REP' WHERE COST_CENTER_CODE = '83BA09';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '83BA10';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD SAM TECH SVC REP' WHERE COST_CENTER_CODE = '83BA10';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '83BA11';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD SAM TECH SVC REP' WHERE COST_CENTER_CODE = '83BA11';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '83BA12';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD SAM TECH SVC REP' WHERE COST_CENTER_CODE = '83BA12';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '83BA13';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD SAM TECH SVC REP-FURNITURE' WHERE COST_CENTER_CODE = '83BA13';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '83BA15';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD SAM TECH SVC REP-FURNITURE' WHERE COST_CENTER_CODE = '83BA15';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '83BA16';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD SAM TECH SVC REP' WHERE COST_CENTER_CODE = '83BA16';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '83BA17';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD SAM TECH SVC REP' WHERE COST_CENTER_CODE = '83BA17';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '83BA18';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD SAM TECH SVC REP-FURNITURE' WHERE COST_CENTER_CODE = '83BA18';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '83BA20';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD SAM TECH SVC REP-FURNITURE' WHERE COST_CENTER_CODE = '83BA20';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '83BA40';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD SAM-SPECIALTY' WHERE COST_CENTER_CODE = '83BA40';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '83BA41';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD NSM-KITCHEN CAB' WHERE COST_CENTER_CODE = '83BA41';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '83BA42';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD SAM' WHERE COST_CENTER_CODE = '83BA42';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '83BA60';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD SALES DIR-SAM' WHERE COST_CENTER_CODE = '83BA60';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '83BA65';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD NSM-FLOORING' WHERE COST_CENTER_CODE = '83BA65';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '83N102';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD WEST TECH REP' WHERE COST_CENTER_CODE = '83N102';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '83N106';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD WEST TECH REP' WHERE COST_CENTER_CODE = '83N106';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '83N108';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD WEST TECH REP' WHERE COST_CENTER_CODE = '83N108';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '83N109';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD WEST TECH REP' WHERE COST_CENTER_CODE = '83N109';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '83N111';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD EAST TECH SVC REP' WHERE COST_CENTER_CODE = '83N111';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '83N112';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD EAST SALES MGR' WHERE COST_CENTER_CODE = '83N112';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '83N115';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD EAST SALES DIR' WHERE COST_CENTER_CODE = '83N115';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '83N118';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD WEST TECH REP' WHERE COST_CENTER_CODE = '83N118';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '83N119';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD WEST TECH REP' WHERE COST_CENTER_CODE = '83N119';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '83N123';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = '07/16 WOOD EAST SALES MGR' WHERE COST_CENTER_CODE = '83N123';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '83N126';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD EAST TECH SVC REP' WHERE COST_CENTER_CODE = '83N126';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '83N129';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD WEST TECH REP' WHERE COST_CENTER_CODE = '83N129';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '83N131';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD WEST SALES MGR' WHERE COST_CENTER_CODE = '83N131';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '83N133';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD SAM TECH SVC REP' WHERE COST_CENTER_CODE = '83N133';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '83N134';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD WEST TECH REP' WHERE COST_CENTER_CODE = '83N134';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '83N136';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD WEST SALES MGR' WHERE COST_CENTER_CODE = '83N136';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '83N137';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD WEST TECH REP' WHERE COST_CENTER_CODE = '83N137';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '83N142';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD WEST TECH REP MGR' WHERE COST_CENTER_CODE = '83N142';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '83N143';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD WEST SALES DIR' WHERE COST_CENTER_CODE = '83N143';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '83N146';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD EAST TECH SVC REP' WHERE COST_CENTER_CODE = '83N146';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '83N147';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD EAST TECH SVC REP' WHERE COST_CENTER_CODE = '83N147';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '83N148';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD EAST TECH SVC REP' WHERE COST_CENTER_CODE = '83N148';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '83N153';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD EAST TECH SVC REP' WHERE COST_CENTER_CODE = '83N153';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '83N156';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD EAST TECH SVC REP' WHERE COST_CENTER_CODE = '83N156';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '83N158';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD EAST TECH SVC REP' WHERE COST_CENTER_CODE = '83N158';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '83N159';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD EAST TECH SVC REP' WHERE COST_CENTER_CODE = '83N159';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '83N161';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD EAST TECH SVC REP' WHERE COST_CENTER_CODE = '83N161';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '83N164';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD WEST TECH REP' WHERE COST_CENTER_CODE = '83N164';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '83N165';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD WEST TECH REP' WHERE COST_CENTER_CODE = '83N165';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '83N166';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD EAST TECH SVC REP' WHERE COST_CENTER_CODE = '83N166';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '83N171';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD WEST TECH REP' WHERE COST_CENTER_CODE = '83N171';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '83N172';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD WEST TECH REP' WHERE COST_CENTER_CODE = '83N172';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '83N174';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD WEST TECH REP' WHERE COST_CENTER_CODE = '83N174';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '83N175';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD WEST TECH REP' WHERE COST_CENTER_CODE = '83N175';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '83N176';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD WEST TECH REP' WHERE COST_CENTER_CODE = '83N176';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '83N179';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD WEST TECH REP' WHERE COST_CENTER_CODE = '83N179';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '83N184';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD WEST TECH REP' WHERE COST_CENTER_CODE = '83N184';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '83N187';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD WEST TECH REP' WHERE COST_CENTER_CODE = '83N187';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '83N188';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD EAST TECH SVC REP' WHERE COST_CENTER_CODE = '83N188';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '83N190';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD EAST TECH SVC REP' WHERE COST_CENTER_CODE = '83N190';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '83N191';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD WEST TECH REP' WHERE COST_CENTER_CODE = '83N191';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '83N193';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD WEST TECH REP' WHERE COST_CENTER_CODE = '83N193';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '83N195';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD WEST TECH REP' WHERE COST_CENTER_CODE = '83N195';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '83N196';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD WEST TECH REP' WHERE COST_CENTER_CODE = '83N196';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '83N202';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD MKTG PROD MGR-KITCHEN CAB' WHERE COST_CENTER_CODE = '83N202';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '83N205';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD WEST SALES MGR' WHERE COST_CENTER_CODE = '83N205';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '83N206';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD EAST TECH SVC REP' WHERE COST_CENTER_CODE = '83N206';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '83N207';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD EAST TECH SVC REP' WHERE COST_CENTER_CODE = '83N207';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '83N208';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD SAM TECH SVC REP' WHERE COST_CENTER_CODE = '83N208';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '83N212';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD EAST SALES MGR' WHERE COST_CENTER_CODE = '83N212';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '83N217';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD MKTG MGR-SPECIALTY' WHERE COST_CENTER_CODE = '83N217';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '83N218';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD SAM-BLDG PROD' WHERE COST_CENTER_CODE = '83N218';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '83N223';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD WEST TECH REP' WHERE COST_CENTER_CODE = '83N223';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '83N224';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD EAST TECH SVC REP' WHERE COST_CENTER_CODE = '83N224';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '83N227';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD EAST TECH SVC REP' WHERE COST_CENTER_CODE = '83N227';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '83N228';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD SAM' WHERE COST_CENTER_CODE = '83N228';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '83N234';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD SAM-KITCHEN CAB' WHERE COST_CENTER_CODE = '83N234';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '83N237';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD WEST TECH REP' WHERE COST_CENTER_CODE = '83N237';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '83N238';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD WEST TECH REP' WHERE COST_CENTER_CODE = '83N238';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '83N240';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD WEST TECH REP' WHERE COST_CENTER_CODE = '83N240';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '83N269';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD SAM-BLDG PROD' WHERE COST_CENTER_CODE = '83N269';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '83N342';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD TECH SVC REP-US DIST' WHERE COST_CENTER_CODE = '83N342';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '83N494';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD SAM TECH SVC REP-BLDG PROD' WHERE COST_CENTER_CODE = '83N494';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '83N500';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD SAM-FURNITURE' WHERE COST_CENTER_CODE = '83N500';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '83N515';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD EAST TECH SVC MGR' WHERE COST_CENTER_CODE = '83N515';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '83N517';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD SAM-FLOORING' WHERE COST_CENTER_CODE = '83N517';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '83N523';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD WEST TECH REP' WHERE COST_CENTER_CODE = '83N523';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '83N524';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD SAM-SPECIALTY' WHERE COST_CENTER_CODE = '83N524';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '83N525';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD WEST TECH MGR' WHERE COST_CENTER_CODE = '83N525';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '83N527';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD WEST TECH REP' WHERE COST_CENTER_CODE = '83N527';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '83N534';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD EAST TECH SVC REP' WHERE COST_CENTER_CODE = '83N534';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '83N555';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD EAST TECH SVC REP' WHERE COST_CENTER_CODE = '83N555';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '83N710';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD SAM-KITCHEN CAB' WHERE COST_CENTER_CODE = '83N710';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '83N730';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD MKTG BUS DIR-STRATEGY & COLOR' WHERE COST_CENTER_CODE = '83N730';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '83N750';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD SAM-KITCHEN CAB' WHERE COST_CENTER_CODE = '83N750';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '83N751';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD NSM-FURNITURE' WHERE COST_CENTER_CODE = '83N751';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '83N752';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = '07/18 WOOD RES FURNITURE BD' WHERE COST_CENTER_CODE = '83N752';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '83N777';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD MKTG MGR-GCDC & COLOR' WHERE COST_CENTER_CODE = '83N777';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '83N780';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD MKTG GCDC COLOR & DESIGN' WHERE COST_CENTER_CODE = '83N780';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '83N781';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD WEST TECH REP' WHERE COST_CENTER_CODE = '83N781';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '83N784';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD EAST TECH SVC REP' WHERE COST_CENTER_CODE = '83N784';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '83N791';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD MKTG BUS DIR-WCBP' WHERE COST_CENTER_CODE = '83N791';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '83N792';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD MKTG DIR-PRODUCT DEV' WHERE COST_CENTER_CODE = '83N792';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '83N793';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD MKTG PROD MGR' WHERE COST_CENTER_CODE = '83N793';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '83N794';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD WEST TECH REP' WHERE COST_CENTER_CODE = '83N794';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '83N796';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD MKTG TECH CUST SERV' WHERE COST_CENTER_CODE = '83N796';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '83U551';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD MKTG MGR-FURNITURE' WHERE COST_CENTER_CODE = '83U551';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '83U552';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD EAST TECH SVC REP' WHERE COST_CENTER_CODE = '83U552';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '83U553';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD WEST TECH REP' WHERE COST_CENTER_CODE = '83U553';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '83U557';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD EAST TECH SVC REP' WHERE COST_CENTER_CODE = '83U557';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '83U558';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD WEST TECH REP' WHERE COST_CENTER_CODE = '83U558';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '83U562';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD WEST SALES MGR' WHERE COST_CENTER_CODE = '83U562';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '83U579';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD EAST TECH SVC REP' WHERE COST_CENTER_CODE = '83U579';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '83U580';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD EAST TECH SVC REP' WHERE COST_CENTER_CODE = '83U580';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '83U581';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD EAST TECH SVC REP' WHERE COST_CENTER_CODE = '83U581';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '83U748';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'ML CAMPBELL-SALES DIR' WHERE COST_CENTER_CODE = '83U748';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '83W012';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD MKTG VP' WHERE COST_CENTER_CODE = '83W012';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '83W016';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD MKTG MGR-MARCOM' WHERE COST_CENTER_CODE = '83W016';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '83W030';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD SAM-BLDG PROD' WHERE COST_CENTER_CODE = '83W030';
--1 Row(s) Updated
SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '8AU263';
--1 Row(s) Selected
UPDATE COST_CENTER SET COST_CENTER_NAME = 'WOOD MKTG DIR-DIST BRANDS' WHERE COST_CENTER_CODE = '8AU263';
--1 Row(s) Updated

COMMIT;

DECLARE
    V_BULK_LOAD_LKUP_ID     NUMBER := 141;
BEGIN
    POS_DATA_GENERATION.RESET_FLAG_POLLING_BULK_LOADS(V_BULK_LOAD_LKUP_ID);
END;

