/*
Below DMLs will insert the pick list values for two new fields added in COST_CENTER Table
    SPRAY_EQP_RPR_IND, BOOK_PLN_PROFILE_CD fields

Created : 11/11/2016 jxc517 CCN Project Team....
*/

DELETE FROM CODE_DETAIL WHERE CODE_HEADER_NAME = 'BOOK_PLAN_PROFILE_CODE';
DELETE FROM CODE_DETAIL WHERE CODE_HEADER_NAME = 'SPRAY_EQUIP_RPR_CODE';

REM INSERTING into CODE_HEADER
SET DEFINE OFF;
INSERT INTO CODE_HEADER (CODE_HEADER_NAME,CODE_HEADER_TYPE,CODE_HEADER_DESCRIPTION,CODE_HEADER_EXPIRE_FLAG,CODE_HEADER_EXPIRE_USER,CODE_HEADER_EXPIRE_EFF_DATE,CODE_HEADER_DTL_VAL_SIZE,CODE_HEADER_DTL_VAL_DEFAULT,CODE_HEADER_CREATE_USER,CODE_HEADER_EFF_DATE,CODE_HEADER_IDENTIFIER) values ('BOOK_PLAN_PROFILE_CODE','COD','THE BOOK PLAN PROFILE CODES','N',null,null,2,null,'jxc517',TRUNC(SYSDATE),null);

REM INSERTING INTO CODE_DETAIL
SET DEFINE OFF;
INSERT INTO CODE_DETAIL (CODE_HEADER_NAME,CODE_HEADER_TYPE,CODE_DETAIL_VALUE,CODE_DETAIL_DESCRIPTION,CODE_DETAIL_EXPIRE_FLAG,CODE_DETAIL_EXPIRE_USER,CODE_DETAIL_EXPIRE_EFF_DATE,CODE_DETAIL_ID,CODE_DETAIL_CREATE_USER,CODE_DETAIL_EFF_DATE) values ('BOOK_PLAN_PROFILE_CODE','COD','A','Book Plan A',null,null,null,1,'jxc517',TRUNC(SYSDATE));
INSERT INTO CODE_DETAIL (CODE_HEADER_NAME,CODE_HEADER_TYPE,CODE_DETAIL_VALUE,CODE_DETAIL_DESCRIPTION,CODE_DETAIL_EXPIRE_FLAG,CODE_DETAIL_EXPIRE_USER,CODE_DETAIL_EXPIRE_EFF_DATE,CODE_DETAIL_ID,CODE_DETAIL_CREATE_USER,CODE_DETAIL_EFF_DATE) values ('BOOK_PLAN_PROFILE_CODE','COD','AU','Book Plan A-UPSCALE',null,null,null,2,'jxc517',TRUNC(SYSDATE));
INSERT INTO CODE_DETAIL (CODE_HEADER_NAME,CODE_HEADER_TYPE,CODE_DETAIL_VALUE,CODE_DETAIL_DESCRIPTION,CODE_DETAIL_EXPIRE_FLAG,CODE_DETAIL_EXPIRE_USER,CODE_DETAIL_EXPIRE_EFF_DATE,CODE_DETAIL_ID,CODE_DETAIL_CREATE_USER,CODE_DETAIL_EFF_DATE) values ('BOOK_PLAN_PROFILE_CODE','COD','B','BASIC',null,null,null,3,'jxc517',TRUNC(SYSDATE));
INSERT INTO CODE_DETAIL (CODE_HEADER_NAME,CODE_HEADER_TYPE,CODE_DETAIL_VALUE,CODE_DETAIL_DESCRIPTION,CODE_DETAIL_EXPIRE_FLAG,CODE_DETAIL_EXPIRE_USER,CODE_DETAIL_EXPIRE_EFF_DATE,CODE_DETAIL_ID,CODE_DETAIL_CREATE_USER,CODE_DETAIL_EFF_DATE) values ('BOOK_PLAN_PROFILE_CODE','COD','BU','Book Plan B-UPSCALE',null,null,null,4,'jxc517',TRUNC(SYSDATE));
INSERT INTO CODE_DETAIL (CODE_HEADER_NAME,CODE_HEADER_TYPE,CODE_DETAIL_VALUE,CODE_DETAIL_DESCRIPTION,CODE_DETAIL_EXPIRE_FLAG,CODE_DETAIL_EXPIRE_USER,CODE_DETAIL_EXPIRE_EFF_DATE,CODE_DETAIL_ID,CODE_DETAIL_CREATE_USER,CODE_DETAIL_EFF_DATE) values ('BOOK_PLAN_PROFILE_CODE','COD','C','Book Plan C',null,null,null,5,'jxc517',TRUNC(SYSDATE));
INSERT INTO CODE_DETAIL (CODE_HEADER_NAME,CODE_HEADER_TYPE,CODE_DETAIL_VALUE,CODE_DETAIL_DESCRIPTION,CODE_DETAIL_EXPIRE_FLAG,CODE_DETAIL_EXPIRE_USER,CODE_DETAIL_EXPIRE_EFF_DATE,CODE_DETAIL_ID,CODE_DETAIL_CREATE_USER,CODE_DETAIL_EFF_DATE) values ('BOOK_PLAN_PROFILE_CODE','COD','CU','Book Plan C-UPSCALE',null,null,null,6,'jxc517',TRUNC(SYSDATE));
INSERT INTO CODE_DETAIL (CODE_HEADER_NAME,CODE_HEADER_TYPE,CODE_DETAIL_VALUE,CODE_DETAIL_DESCRIPTION,CODE_DETAIL_EXPIRE_FLAG,CODE_DETAIL_EXPIRE_USER,CODE_DETAIL_EXPIRE_EFF_DATE,CODE_DETAIL_ID,CODE_DETAIL_CREATE_USER,CODE_DETAIL_EFF_DATE) values ('BOOK_PLAN_PROFILE_CODE','COD','D','DESIGN BY COLOR',null,null,null,7,'jxc517',TRUNC(SYSDATE));
INSERT INTO CODE_DETAIL (CODE_HEADER_NAME,CODE_HEADER_TYPE,CODE_DETAIL_VALUE,CODE_DETAIL_DESCRIPTION,CODE_DETAIL_EXPIRE_FLAG,CODE_DETAIL_EXPIRE_USER,CODE_DETAIL_EXPIRE_EFF_DATE,CODE_DETAIL_ID,CODE_DETAIL_CREATE_USER,CODE_DETAIL_EFF_DATE) values ('BOOK_PLAN_PROFILE_CODE','COD','DU','Book Plan D-UPSCALE',null,null,null,8,'jxc517',TRUNC(SYSDATE));
INSERT INTO CODE_DETAIL (CODE_HEADER_NAME,CODE_HEADER_TYPE,CODE_DETAIL_VALUE,CODE_DETAIL_DESCRIPTION,CODE_DETAIL_EXPIRE_FLAG,CODE_DETAIL_EXPIRE_USER,CODE_DETAIL_EXPIRE_EFF_DATE,CODE_DETAIL_ID,CODE_DETAIL_CREATE_USER,CODE_DETAIL_EFF_DATE) values ('BOOK_PLAN_PROFILE_CODE','COD','S','STANDARD',null,null,null,9,'jxc517',TRUNC(SYSDATE));
INSERT INTO CODE_DETAIL (CODE_HEADER_NAME,CODE_HEADER_TYPE,CODE_DETAIL_VALUE,CODE_DETAIL_DESCRIPTION,CODE_DETAIL_EXPIRE_FLAG,CODE_DETAIL_EXPIRE_USER,CODE_DETAIL_EXPIRE_EFF_DATE,CODE_DETAIL_ID,CODE_DETAIL_CREATE_USER,CODE_DETAIL_EFF_DATE) values ('BOOK_PLAN_PROFILE_CODE','COD','U','UPSCALE',null,null,null,10,'jxc517',TRUNC(SYSDATE));
INSERT INTO CODE_DETAIL (CODE_HEADER_NAME,CODE_HEADER_TYPE,CODE_DETAIL_VALUE,CODE_DETAIL_DESCRIPTION,CODE_DETAIL_EXPIRE_FLAG,CODE_DETAIL_EXPIRE_USER,CODE_DETAIL_EXPIRE_EFF_DATE,CODE_DETAIL_ID,CODE_DETAIL_CREATE_USER,CODE_DETAIL_EFF_DATE) values ('BOOK_PLAN_PROFILE_CODE','COD','ZZ','NOT ON BOOK PLAN',null,null,null,11,'jxc517',TRUNC(SYSDATE));

SET DEFINE OFF;
INSERT INTO CODE_HEADER (CODE_HEADER_NAME,CODE_HEADER_TYPE,CODE_HEADER_DESCRIPTION,CODE_HEADER_EXPIRE_FLAG,CODE_HEADER_EXPIRE_USER,CODE_HEADER_EXPIRE_EFF_DATE,CODE_HEADER_DTL_VAL_SIZE,CODE_HEADER_DTL_VAL_DEFAULT,CODE_HEADER_CREATE_USER,CODE_HEADER_EFF_DATE,CODE_HEADER_IDENTIFIER) values ('SPRAY_EQUIP_RPR_CODE','COD','SPRAY EQUIPMENT REPAIR CODES','N',null,null,1,null,'jxc517',TRUNC(SYSDATE),null);

REM INSERTING INTO CODE_DETAIL
SET DEFINE OFF;
INSERT INTO CODE_DETAIL (CODE_HEADER_NAME,CODE_HEADER_TYPE,CODE_DETAIL_VALUE,CODE_DETAIL_DESCRIPTION,CODE_DETAIL_EXPIRE_FLAG,CODE_DETAIL_EXPIRE_USER,CODE_DETAIL_EXPIRE_EFF_DATE,CODE_DETAIL_ID,CODE_DETAIL_CREATE_USER,CODE_DETAIL_EFF_DATE) values ('SPRAY_EQUIP_RPR_CODE','COD','B','Spray Equip Repair Code B',null,null,null,1,'jxc517',TRUNC(SYSDATE));
INSERT INTO CODE_DETAIL (CODE_HEADER_NAME,CODE_HEADER_TYPE,CODE_DETAIL_VALUE,CODE_DETAIL_DESCRIPTION,CODE_DETAIL_EXPIRE_FLAG,CODE_DETAIL_EXPIRE_USER,CODE_DETAIL_EXPIRE_EFF_DATE,CODE_DETAIL_ID,CODE_DETAIL_CREATE_USER,CODE_DETAIL_EFF_DATE) values ('SPRAY_EQUIP_RPR_CODE','COD','N','Spray Equip Repair Code N',null,null,null,2,'jxc517',TRUNC(SYSDATE));
INSERT INTO CODE_DETAIL (CODE_HEADER_NAME,CODE_HEADER_TYPE,CODE_DETAIL_VALUE,CODE_DETAIL_DESCRIPTION,CODE_DETAIL_EXPIRE_FLAG,CODE_DETAIL_EXPIRE_USER,CODE_DETAIL_EXPIRE_EFF_DATE,CODE_DETAIL_ID,CODE_DETAIL_CREATE_USER,CODE_DETAIL_EFF_DATE) values ('SPRAY_EQUIP_RPR_CODE','COD','S','Spray Equip Repair Code S',null,null,null,3,'jxc517',TRUNC(SYSDATE));
INSERT INTO CODE_DETAIL (CODE_HEADER_NAME,CODE_HEADER_TYPE,CODE_DETAIL_VALUE,CODE_DETAIL_DESCRIPTION,CODE_DETAIL_EXPIRE_FLAG,CODE_DETAIL_EXPIRE_USER,CODE_DETAIL_EXPIRE_EFF_DATE,CODE_DETAIL_ID,CODE_DETAIL_CREATE_USER,CODE_DETAIL_EFF_DATE) values ('SPRAY_EQUIP_RPR_CODE','COD','U','Spray Equip Repair Code U',null,null,null,4,'jxc517',TRUNC(SYSDATE));

COMMIT;

/*
SELECT * FROM CODE_DETAIL WHERE CODE_HEADER_NAME = 'BOOK_PLAN_PROFILE_CODE';
SELECT * FROM CODE_DETAIL WHERE CODE_HEADER_NAME = 'SPRAY_EQUIP_RPR_CODE';
*/
