/*
created : nxk927 04/18/2018
          Updating Pos last transaction date and last tran number
*/

DECLARE
CURSOR CUR IS
  SELECT COST_CENTER_CODE, 
         TERMINAL_NUMBER, 
         EFFECTIVE_DATE, 
         EXPIRATION_DATE,
         TO_DATE(LTRIM(POS_LAST_TRAN_DATE, '0'),'YYYYMMDD') POS_LAST_TRAN_DATE, 
         POS_LAST_TRAN_NUMBER,
         POLLING_STATUS_CODE
    FROM TEMP_TERMINAL
    WHERE (COST_CENTER_CODE, TERMINAL_NUMBER) IN (SELECT COST_CENTER_CODE, TERMINAL_NUMBER 
                                                 FROM TERMINAL
                                                WHERE EXPIRATION_DATE IS NULL)
      AND EXPIRATION_DATE = '00000000';
BEGIN
  FOR REC IN CUR LOOP
      DBMS_OUTPUT.put_line(REC.POS_LAST_TRAN_DATE);
      UPDATE TERMINAL
         SET POS_LAST_TRAN_DATE   =   REC.POS_LAST_TRAN_DATE,
             POS_LAST_TRAN_NUMBER =   REC.POS_LAST_TRAN_NUMBER
       WHERE COST_CENTER_CODE     = REC.COST_CENTER_CODE
         AND TERMINAL_NUMBER      = REC.TERMINAL_NUMBER
         AND EXPIRATION_DATE IS NULL;
  END LOOP;
  COMMIT;
END;