/*******************************************************************************
Scripts to insert prime sub accounts in GENERAL_LEDGER_ACCOUNTS and PRGM_GL_ACCNT_RLTN_DTLS  
as per Pat Malloy

CREATED : 06/26/2018 sxh487
*******************************************************************************/

select * from programs where PROGRAM_NAME ='STOREXP';
select * from GENERAL_LEDGER_ACCOUNTS where GL_ACCOUNT_NUMBER IN ('3700101','3700122','3700123');
select * from PRGM_GL_ACCNT_RLTN_DTLS where GL_PS_ACCOUNT_NUMBER IN ('3700101','3700122','3700123');

INSERT INTO GENERAL_LEDGER_ACCOUNTS(GL_ACCOUNT_NUMBER, DESCRIPTION, PROFIT_OR_LOSS, EFFECTIVE_DATE, CREATED_BY)
VALUES ('3700101', 'AUTO OBSOLETE PT', '034', TRUNC(SYSDATE), 'pmm4br');

INSERT INTO GENERAL_LEDGER_ACCOUNTS(GL_ACCOUNT_NUMBER, DESCRIPTION, PROFIT_OR_LOSS, EFFECTIVE_DATE, CREATED_BY)
VALUES ('3700122', 'AUTO OBSOLETE AP', '034', TRUNC(SYSDATE), 'pmm4br');

INSERT INTO GENERAL_LEDGER_ACCOUNTS(GL_ACCOUNT_NUMBER, DESCRIPTION, PROFIT_OR_LOSS, EFFECTIVE_DATE, CREATED_BY)
VALUES ('3700123', 'AUTO OBSOLETE SE', '034', TRUNC(SYSDATE), 'pmm4br');

---PRGM_GL_ACCNT_RLTN_DTLS
INSERT INTO PRGM_GL_ACCNT_RLTN_DTLS(GL_PS_ACCOUNT_NUMBER, PROGRAM_NAME, SORTED_SEQUENCE, SHARED, EFFECTIVE_DATE, CREATED_BY) 
VALUES ('3700101', 'STOREXP', '0', 'false', TRUNC(SYSDATE), 'pmm4br');

INSERT INTO PRGM_GL_ACCNT_RLTN_DTLS(GL_PS_ACCOUNT_NUMBER, PROGRAM_NAME, SORTED_SEQUENCE, SHARED, EFFECTIVE_DATE, CREATED_BY) 
VALUES ('3700122', 'STOREXP', '0', 'false', '30-JUN-2018', 'pmm4br');

INSERT INTO PRGM_GL_ACCNT_RLTN_DTLS(GL_PS_ACCOUNT_NUMBER, PROGRAM_NAME, SORTED_SEQUENCE, SHARED, EFFECTIVE_DATE, CREATED_BY) 
VALUES ('3700123', 'STOREXP', '0', 'false', TRUNC(SYSDATE), 'pmm4br'); 

COMMIT;