/*
Below scripts will insert the processor related reference data

Created : 10/14/2016 jxc517 CCN Project Team....
*/

INSERT INTO PROCESSORS VALUES (1, 'Andreia Beca', '2165661621');
INSERT INTO PROCESSORS VALUES (2, 'Arlene Johnson', '2165662937');
INSERT INTO PROCESSORS VALUES (3, 'Camia Brown', '2165661751');
INSERT INTO PROCESSORS VALUES (4, 'DaNita Van-Leer Nicholson', '2165662217');
INSERT INTO PROCESSORS VALUES (5, 'Helen Kelley', '2165663206');
INSERT INTO PROCESSORS VALUES (6, 'Janice Denman', '2165661649');
INSERT INTO PROCESSORS VALUES (7, 'Lori Howell', '2165663207');
INSERT INTO PROCESSORS VALUES (8, 'Mariana Lukic', '2165664096');
INSERT INTO PROCESSORS VALUES (9, 'Paula Martin', '2165663761');
INSERT INTO PROCESSORS VALUES (10, 'Regina Smith','2165663211');
INSERT INTO PROCESSORS VALUES (11, 'Sylvia Davis','2165661640');

COMMIT;

INSERT INTO PROCESSOR_STATES VALUES ('GA', 1 );
INSERT INTO PROCESSOR_STATES VALUES ('IA', 1 );
INSERT INTO PROCESSOR_STATES VALUES ('ND', 1 );
INSERT INTO PROCESSOR_STATES VALUES ('RI', 1 );
INSERT INTO PROCESSOR_STATES VALUES ('DC', 2 );
INSERT INTO PROCESSOR_STATES VALUES ('HI', 2 );
INSERT INTO PROCESSOR_STATES VALUES ('MS', 2 );
INSERT INTO PROCESSOR_STATES VALUES ('NH', 2 );
INSERT INTO PROCESSOR_STATES VALUES ('NM', 2 );
INSERT INTO PROCESSOR_STATES VALUES ('NY', 2 );
INSERT INTO PROCESSOR_STATES VALUES ('UT', 2 );
INSERT INTO PROCESSOR_STATES VALUES ('WA', 2 );
INSERT INTO PROCESSOR_STATES VALUES ('WV', 2 );
INSERT INTO PROCESSOR_STATES VALUES ('IL', 3 );
INSERT INTO PROCESSOR_STATES VALUES ('CT', 4 );
INSERT INTO PROCESSOR_STATES VALUES ('FL', 4 );
INSERT INTO PROCESSOR_STATES VALUES ('KY', 4 );
INSERT INTO PROCESSOR_STATES VALUES ('MA', 4 );
INSERT INTO PROCESSOR_STATES VALUES ('NE', 4 );
INSERT INTO PROCESSOR_STATES VALUES ('AR', 5 );
INSERT INTO PROCESSOR_STATES VALUES ('KS', 5 );
INSERT INTO PROCESSOR_STATES VALUES ('TX', 5 );
INSERT INTO PROCESSOR_STATES VALUES ('AL', 6 );
INSERT INTO PROCESSOR_STATES VALUES ('IN', 6 );
INSERT INTO PROCESSOR_STATES VALUES ('ME', 6 );
INSERT INTO PROCESSOR_STATES VALUES ('MI', 6 );
INSERT INTO PROCESSOR_STATES VALUES ('PR', 6 );
INSERT INTO PROCESSOR_STATES VALUES ('SD', 6 );
INSERT INTO PROCESSOR_STATES VALUES ('VA', 6 );
INSERT INTO PROCESSOR_STATES VALUES ('CO', 7 );
INSERT INTO PROCESSOR_STATES VALUES ('OH', 7 );
INSERT INTO PROCESSOR_STATES VALUES ('OR', 7 );
INSERT INTO PROCESSOR_STATES VALUES ('VT', 7 );
INSERT INTO PROCESSOR_STATES VALUES ('WY', 7 );
INSERT INTO PROCESSOR_STATES VALUES ('DE', 8 );
INSERT INTO PROCESSOR_STATES VALUES ('LA', 8 );
INSERT INTO PROCESSOR_STATES VALUES ('WI', 8 );
INSERT INTO PROCESSOR_STATES VALUES ('CA', 9 );
INSERT INTO PROCESSOR_STATES VALUES ('MO', 9 );
INSERT INTO PROCESSOR_STATES VALUES ('TN', 9 );
INSERT INTO PROCESSOR_STATES VALUES ('AK', 10);
INSERT INTO PROCESSOR_STATES VALUES ('ID', 10);
INSERT INTO PROCESSOR_STATES VALUES ('MN', 10);
INSERT INTO PROCESSOR_STATES VALUES ('MT', 10);
INSERT INTO PROCESSOR_STATES VALUES ('NC', 10);
INSERT INTO PROCESSOR_STATES VALUES ('NJ', 10);
INSERT INTO PROCESSOR_STATES VALUES ('NV', 10);
INSERT INTO PROCESSOR_STATES VALUES ('OK', 10);
INSERT INTO PROCESSOR_STATES VALUES ('AZ', 11);
INSERT INTO PROCESSOR_STATES VALUES ('MD', 11);
INSERT INTO PROCESSOR_STATES VALUES ('PA', 11);
INSERT INTO PROCESSOR_STATES VALUES ('SC', 11);

COMMIT;
