/*
Below scripts will insert the processor related reference data

Created : 10/14/2016 jxc517 CCN Project Team....
*/

INSERT INTO PROCESSOR_GROUPS VALUES (1, 'Stores - Seperated by States', TRUNC(SYSDATE), 'jxc517');
INSERT INTO PROCESSOR_GROUPS VALUES (2, 'Stores Admin', TRUNC(SYSDATE), 'jxc517');
INSERT INTO PROCESSOR_GROUPS VALUES (3, 'Canada', TRUNC(SYSDATE), 'jxc517');
INSERT INTO PROCESSOR_GROUPS VALUES (4, 'Headquarters', TRUNC(SYSDATE), 'jxc517');
INSERT INTO PROCESSOR_GROUPS VALUES (5, 'Retirees', TRUNC(SYSDATE), 'jxc517');
INSERT INTO PROCESSOR_GROUPS VALUES (6, 'Automotive', TRUNC(SYSDATE), 'jxc517');
INSERT INTO PROCESSOR_GROUPS VALUES (7, 'International', TRUNC(SYSDATE), 'jxc517');
COMMIT;

INSERT INTO PROCESSORS VALUES (1, 'Camia Brown', '2165661751', TRUNC(SYSDATE), 'jxc517');
INSERT INTO PROCESSORS VALUES (2, 'DaNita Van-Leer Nicholson', '2165662217', TRUNC(SYSDATE), 'jxc517');
INSERT INTO PROCESSORS VALUES (3, 'Dolly Collado', '2165663202', TRUNC(SYSDATE), 'jxc517');
INSERT INTO PROCESSORS VALUES (4, 'Helen Kelly', '2165663206', TRUNC(SYSDATE), 'jxc517');
INSERT INTO PROCESSORS VALUES (5, 'Janice Denman', '2165661469', TRUNC(SYSDATE), 'jxc517');
INSERT INTO PROCESSORS VALUES (6, 'Michelle Sparks', '2165661634', TRUNC(SYSDATE), 'jxc517');
INSERT INTO PROCESSORS VALUES (7, 'Paula Martin', '2165663761', TRUNC(SYSDATE), 'jxc517');
INSERT INTO PROCESSORS VALUES (8, 'Regina Smith', '2165663211', TRUNC(SYSDATE), 'jxc517');
INSERT INTO PROCESSORS VALUES (9, 'Rob Dickson', '2165661621', TRUNC(SYSDATE), 'jxc517');
INSERT INTO PROCESSORS VALUES (10, 'Sylvia Davis', '2165661640', TRUNC(SYSDATE), 'jxc517');
INSERT INTO PROCESSORS VALUES (11, 'Mariana Lukic', '2165154096', TRUNC(SYSDATE), 'jxc517');
INSERT INTO PROCESSORS VALUES (12, 'Lori Howell', '2165663207', TRUNC(SYSDATE), 'jxc517');
COMMIT;

INSERT INTO PRCSR_STR_GRP_DTLS VALUES (1, 1, TRUNC(SYSDATE), 'jxc517', 'IL');
INSERT INTO PRCSR_STR_GRP_DTLS VALUES (1, 1, TRUNC(SYSDATE), 'jxc517', 'WI');
INSERT INTO PRCSR_STR_GRP_DTLS VALUES (1, 2, TRUNC(SYSDATE), 'jxc517', 'CT');
INSERT INTO PRCSR_STR_GRP_DTLS VALUES (1, 2, TRUNC(SYSDATE), 'jxc517', 'FL');
INSERT INTO PRCSR_STR_GRP_DTLS VALUES (1, 2, TRUNC(SYSDATE), 'jxc517', 'KY');
INSERT INTO PRCSR_STR_GRP_DTLS VALUES (1, 2, TRUNC(SYSDATE), 'jxc517', 'MA');
INSERT INTO PRCSR_STR_GRP_DTLS VALUES (1, 2, TRUNC(SYSDATE), 'jxc517', 'NE');
INSERT INTO PRCSR_STR_GRP_DTLS VALUES (1, 2, TRUNC(SYSDATE), 'jxc517', 'WV');
INSERT INTO PRCSR_STR_GRP_DTLS VALUES (1, 3, TRUNC(SYSDATE), 'jxc517', 'OR');
INSERT INTO PRCSR_STR_GRP_DTLS VALUES (1, 4, TRUNC(SYSDATE), 'jxc517', 'KS');
INSERT INTO PRCSR_STR_GRP_DTLS VALUES (1, 4, TRUNC(SYSDATE), 'jxc517', 'LA');
INSERT INTO PRCSR_STR_GRP_DTLS VALUES (1, 4, TRUNC(SYSDATE), 'jxc517', 'TX');
INSERT INTO PRCSR_STR_GRP_DTLS VALUES (1, 4, TRUNC(SYSDATE), 'jxc517', 'WA');
INSERT INTO PRCSR_STR_GRP_DTLS VALUES (1, 5, TRUNC(SYSDATE), 'jxc517', 'AL');
INSERT INTO PRCSR_STR_GRP_DTLS VALUES (1, 5, TRUNC(SYSDATE), 'jxc517', 'IN');
INSERT INTO PRCSR_STR_GRP_DTLS VALUES (1, 5, TRUNC(SYSDATE), 'jxc517', 'ME');
INSERT INTO PRCSR_STR_GRP_DTLS VALUES (1, 5, TRUNC(SYSDATE), 'jxc517', 'MI');
INSERT INTO PRCSR_STR_GRP_DTLS VALUES (1, 5, TRUNC(SYSDATE), 'jxc517', 'MS');
INSERT INTO PRCSR_STR_GRP_DTLS VALUES (1, 5, TRUNC(SYSDATE), 'jxc517', 'ND');
INSERT INTO PRCSR_STR_GRP_DTLS VALUES (1, 5, TRUNC(SYSDATE), 'jxc517', 'PR');
INSERT INTO PRCSR_STR_GRP_DTLS VALUES (1, 5, TRUNC(SYSDATE), 'jxc517', 'RI');
INSERT INTO PRCSR_STR_GRP_DTLS VALUES (1, 5, TRUNC(SYSDATE), 'jxc517', 'SD');
INSERT INTO PRCSR_STR_GRP_DTLS VALUES (1, 5, TRUNC(SYSDATE), 'jxc517', 'VA');
INSERT INTO PRCSR_STR_GRP_DTLS VALUES (1, 6, TRUNC(SYSDATE), 'jxc517', 'AR');
INSERT INTO PRCSR_STR_GRP_DTLS VALUES (1, 6, TRUNC(SYSDATE), 'jxc517', 'DE');
INSERT INTO PRCSR_STR_GRP_DTLS VALUES (1, 6, TRUNC(SYSDATE), 'jxc517', 'NM');
INSERT INTO PRCSR_STR_GRP_DTLS VALUES (1, 6, TRUNC(SYSDATE), 'jxc517', 'OH');
INSERT INTO PRCSR_STR_GRP_DTLS VALUES (1, 6, TRUNC(SYSDATE), 'jxc517', 'UT');
INSERT INTO PRCSR_STR_GRP_DTLS VALUES (1, 6, TRUNC(SYSDATE), 'jxc517', 'VT');
INSERT INTO PRCSR_STR_GRP_DTLS VALUES (1, 6, TRUNC(SYSDATE), 'jxc517', 'WY');
INSERT INTO PRCSR_STR_GRP_DTLS VALUES (1, 7, TRUNC(SYSDATE), 'jxc517', 'CA');
INSERT INTO PRCSR_STR_GRP_DTLS VALUES (1, 7, TRUNC(SYSDATE), 'jxc517', 'CO');
INSERT INTO PRCSR_STR_GRP_DTLS VALUES (1, 7, TRUNC(SYSDATE), 'jxc517', 'DC');
INSERT INTO PRCSR_STR_GRP_DTLS VALUES (1, 7, TRUNC(SYSDATE), 'jxc517', 'HI');
INSERT INTO PRCSR_STR_GRP_DTLS VALUES (1, 7, TRUNC(SYSDATE), 'jxc517', 'MO');
INSERT INTO PRCSR_STR_GRP_DTLS VALUES (1, 7, TRUNC(SYSDATE), 'jxc517', 'TN');
INSERT INTO PRCSR_STR_GRP_DTLS VALUES (1, 8, TRUNC(SYSDATE), 'jxc517', 'AK');
INSERT INTO PRCSR_STR_GRP_DTLS VALUES (1, 8, TRUNC(SYSDATE), 'jxc517', 'ID');
INSERT INTO PRCSR_STR_GRP_DTLS VALUES (1, 8, TRUNC(SYSDATE), 'jxc517', 'MN');
INSERT INTO PRCSR_STR_GRP_DTLS VALUES (1, 8, TRUNC(SYSDATE), 'jxc517', 'MT');
INSERT INTO PRCSR_STR_GRP_DTLS VALUES (1, 8, TRUNC(SYSDATE), 'jxc517', 'NC');
INSERT INTO PRCSR_STR_GRP_DTLS VALUES (1, 8, TRUNC(SYSDATE), 'jxc517', 'NJ');
INSERT INTO PRCSR_STR_GRP_DTLS VALUES (1, 8, TRUNC(SYSDATE), 'jxc517', 'NV');
INSERT INTO PRCSR_STR_GRP_DTLS VALUES (1, 8, TRUNC(SYSDATE), 'jxc517', 'NY');
INSERT INTO PRCSR_STR_GRP_DTLS VALUES (1, 8, TRUNC(SYSDATE), 'jxc517', 'OK');
INSERT INTO PRCSR_STR_GRP_DTLS VALUES (1, 9, TRUNC(SYSDATE), 'jxc517', 'GA');
INSERT INTO PRCSR_STR_GRP_DTLS VALUES (1, 10, TRUNC(SYSDATE), 'jxc517', 'AZ');
INSERT INTO PRCSR_STR_GRP_DTLS VALUES (1, 10, TRUNC(SYSDATE), 'jxc517', 'IA');
INSERT INTO PRCSR_STR_GRP_DTLS VALUES (1, 10, TRUNC(SYSDATE), 'jxc517', 'MD');
INSERT INTO PRCSR_STR_GRP_DTLS VALUES (1, 10, TRUNC(SYSDATE), 'jxc517', 'NH');
INSERT INTO PRCSR_STR_GRP_DTLS VALUES (1, 10, TRUNC(SYSDATE), 'jxc517', 'PA');
INSERT INTO PRCSR_STR_GRP_DTLS VALUES (1, 10, TRUNC(SYSDATE), 'jxc517', 'SC');
COMMIT;

INSERT INTO PRCSR_STR_ADMN_GRP_DTLS VALUES (2, 9, TRUNC(SYSDATE), 'jxc517');
COMMIT;

INSERT INTO PRCSR_CANADA_GRP_DTLS VALUES (3, 12, TRUNC(SYSDATE), 'jxc517');
COMMIT;

INSERT INTO PRCSR_HEADQRTS_GRP_DTLS VALUES (4, 11, TRUNC(SYSDATE), 'jxc517');
COMMIT;

INSERT INTO PRCSR_RETIREES_GRP_DTLS VALUES (5, 11, TRUNC(SYSDATE), 'jxc517');
COMMIT;

INSERT INTO PRCSR_AUTO_GRP_DTLS VALUES (6, 9, TRUNC(SYSDATE), 'jxc517');
COMMIT;

INSERT INTO PRCSR_INTRNTL_GRP_DTLS VALUES (7, 11, TRUNC(SYSDATE), 'jxc517');
COMMIT;

/*
SELECT * FROM PROCESSOR_GROUPS;
SELECT * FROM PROCESSORS;
SELECT * FROM PRCSR_STR_GRP_DTLS;
SELECT * FROM PRCSR_STR_ADMN_GRP_DTLS;
SELECT * FROM PRCSR_CANADA_GRP_DTLS;
SELECT * FROM PRCSR_HEADQRTS_GRP_DTLS;
SELECT * FROM PRCSR_RETIREES_GRP_DTLS;
SELECT * FROM PRCSR_AUTO_GRP_DTLS;
SELECT * FROM PRCSR_INTRNTL_GRP_DTLS;
*/