/*
Created : nxk927 04/18/2018
          updating status expiration date for cost center 707144 as 25-DEC-2017.

*/

SET SERVEROUTPUT ON;
BEGIN
    CCN_BATCH_PKG.LOCK_DATABASE_SP();
    EXECUTE IMMEDIATE 'ALTER TRIGGER TR_STATUS_UPD DISABLE';
END;
/
SELECT * FROM STATUS WHERE COST_CENTER_CODE = '707144';

UPDATE STATUS
   SET EXPIRATION_DATE = '25-DEC-2017'
 WHERE COST_CENTER_CODE = '707144'
   AND STATUS_CODE = 1
   AND EFFECTIVE_DATE = '01-JAN-1982';

COMMIT;
/
BEGIN
    EXECUTE IMMEDIATE 'ALTER TRIGGER TR_STATUS_UPD ENABLE';
    CCN_BATCH_PKG.UNLOCK_DATABASE_SP();
END;
/
