/*
Created : 10/31/2016 CCN Project Team....
          Below script will update the STD_COST_IDENTIFIER and PRIM_COST_IDENTIFIER columns in the table COST_CENTER to NULL
*/
BEGIN
    CCN_BATCH_PKG.LOCK_DATABASE_SP();
END;
/

SELECT * FROM COST_CENTER WHERE COST_CENTER_CODE = '702937';
--1 Row(s) Selected
UPDATE COST_CENTER 
   SET STD_COST_IDENTIFIER = NULL,
       PRIM_COST_IDENTIFIER = NULL
 WHERE COST_CENTER_CODE ='702937';
--1 Row(s) Updated
COMMIT;

BEGIN
    CCN_BATCH_PKG.UNLOCK_DATABASE_SP();
END;
/