/*
This is script To Create External table and update the "TERMINAL" table POS_LAST_TRAN_DATE, POS_LAST_TRAN_NUMBER, POS_VERSION_NBR fields.
created  : 08/21/2018 sxg151 CCN project.... ASP-1122

*/

--CREATE a External TEMP "TERMINAL_TEMP" TABLE TO IMPORT THE DATA FROM Excel

DROP TABLE TERMINAL_TEMP;

CREATE TABLE TERMINAL_TEMP
   (COST_CENTER_CODE VARCHAR2(6),
    COST_CENTER_NAME VARCHAR2(35),
    POS_TERM_NO      VARCHAR2(5),
    STATUS_CODE      VARCHAR2(1),
    DAD              VARCHAR2(10),
    MAX_TRAN_DT      DATE,
    TRAN_NO_LAST     VARCHAR(5)
    )
ORGANIZATION EXTERNAL 
   (TYPE ORACLE_LOADER
    DEFAULT DIRECTORY "CCN_LOAD_FILES"
    ACCESS PARAMETERS
   (RECORDS DELIMITED BY NEWLINE SKIP 1
    badfile "CCN_LOAD_FILES":'TERMINAL_TEMP.bad'
    logfile "CCN_LOAD_FILES":'TERMINAL_TEMP.log'
   FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' LRTRIM
   MISSING FIELD VALUES ARE NULL
   REJECT ROWS WITH ALL NULL FIELDS
   (COST_CENTER_CODE,
    COST_CENTER_NAME,
    POS_TERM_NO,
    STATUS_CODE,
    DAD,
    MAX_TRAN_DT,
    TRAN_NO_LAST
   ))
LOCATION
   ('Terminal_temp.csv'
    )
    )
   REJECT LIMIT UNLIMITED ;

SELECT * FROM  TERMINAL_TEMP;

-- Move the csv file to CCN_LOAD_FILES DIRECTORY


-- Run the below anonymous block to update the TERMINAL Table.

DECLARE
CURSOR CUR IS
  SELECT COST_CENTER_CODE, 
         POS_TERM_NO,
         MAX_TRAN_DT, 
         TRAN_NO_LAST
    FROM TERMINAL_TEMP;

BEGIN
  FOR REC IN CUR LOOP
      UPDATE TERMINAL
         SET POS_LAST_TRAN_DATE   = REC.MAX_TRAN_DT,
             POS_LAST_TRAN_NUMBER = REC.TRAN_NO_LAST
       WHERE SUBSTR(COST_CENTER_CODE,3) = REC.COST_CENTER_CODE
         AND TERMINAL_NUMBER            = REC.POS_TERM_NO;
         COMMIT;
  END LOOP;
  COMMIT;
END;
