/*
created : nxk927 05/09/2018
          Updating the description for the adminorg_hierarchy as requested by Pat
          This update is only for dev/test
          
*/
SELECT * FROM HIERARCHY_DESCRIPTION WHERE HRCHY_HDR_NAME = 'ADMINORG_HIERARCHY' AND HRCHY_HDR_LVL_NBR = 2;

UPDATE HIERARCHY_DESCRIPTION
   SET HRCHY_HDR_LVL_DESC = 'Division'
 WHERE HRCHY_HDR_NAME = 'ADMINORG_HIERARCHY'
   AND HRCHY_HDR_LVL_NBR = 2;

SELECT * FROM HIERARCHY_DESCRIPTION WHERE HRCHY_HDR_NAME = 'ADMINORG_HIERARCHY' AND HRCHY_HDR_LVL_NBR = 3;
   UPDATE HIERARCHY_DESCRIPTION
   SET HRCHY_HDR_LVL_DESC = 'Control'
 WHERE HRCHY_HDR_NAME = 'ADMINORG_HIERARCHY'
   AND HRCHY_HDR_LVL_NBR = 3;

SELECT * FROM HIERARCHY_DESCRIPTION WHERE HRCHY_HDR_NAME = 'ADMINORG_HIERARCHY' AND HRCHY_HDR_LVL_NBR = 4;
UPDATE HIERARCHY_DESCRIPTION
   SET HRCHY_HDR_LVL_DESC = 'Budget'
 WHERE HRCHY_HDR_NAME = 'ADMINORG_HIERARCHY'
   AND HRCHY_HDR_LVL_NBR = 4;

SELECT * FROM HIERARCHY_DESCRIPTION WHERE HRCHY_HDR_NAME = 'ADMINORG_HIERARCHY' AND HRCHY_HDR_LVL_NBR = 5;
UPDATE HIERARCHY_DESCRIPTION
   SET HRCHY_HDR_LVL_DESC = 'Functional 1'
 WHERE HRCHY_HDR_NAME = 'ADMINORG_HIERARCHY'
   AND HRCHY_HDR_LVL_NBR = 5;

SELECT * FROM HIERARCHY_DESCRIPTION WHERE HRCHY_HDR_NAME = 'ADMINORG_HIERARCHY' AND HRCHY_HDR_LVL_NBR = 6;
UPDATE HIERARCHY_DESCRIPTION
   SET HRCHY_HDR_LVL_DESC = 'Functional 2'
 WHERE HRCHY_HDR_NAME = 'ADMINORG_HIERARCHY'
   AND HRCHY_HDR_LVL_NBR = 6;

SELECT * FROM HIERARCHY_DESCRIPTION WHERE HRCHY_HDR_NAME = 'ADMINORG_HIERARCHY' AND HRCHY_HDR_LVL_NBR = 7;
UPDATE HIERARCHY_DESCRIPTION
   SET HRCHY_HDR_LVL_DESC = 'Functional 3'
 WHERE HRCHY_HDR_NAME = 'ADMINORG_HIERARCHY'
   AND HRCHY_HDR_LVL_NBR = 7;

COMMIT;