/*

Created : 01/04/2018 axt754 CCN Project Team....
Changed :
*/

SELECT * FROM CURRENCY_CONVERSION WHERE COUNTRY_CODE = 'CUW';
UPDATE CURRENCY_CONVERSION SET TAXID_DESCRIPTION = 'CRIB NUMBER:' WHERE COUNTRY_CODE = 'CUW';
SELECT * FROM CURRENCY_CONVERSION WHERE COUNTRY_CODE = 'CUW';

-- Commit The changes
COMMIT;

-- Excecute in CCN_UTILITY if any issues
DELETE FROM POS_DOWNLOADS_NON_TAXWARE WHERE COST_CENTER_CODE IN ('75Q504','75R062','757853');
