  -- Create table MAILING_FILE_DETAILS
  CREATE TABLE MAILING_FILE_DETAILS
   (FILE_ID NUMBER, 
	GROUP_ID VARCHAR2(3), 
	FILE_NAME VARCHAR2(100), 
	DIRECTORY_NAME VARCHAR2(100), 
	IS_ACTIVE VARCHAR2(1), 
	CONSTRAINT FILE_ID_PK PRIMARY KEY (FILE_ID),
	CONSTRAINT MAILING_FILE_DETAILS_FK1 FOREIGN KEY (GROUP_ID)
	REFERENCES CCN_UTILITY.MAILING_GROUP (GROUP_ID) ENABLE
   );