-- Grant EXECUTE on CCN_BATCH_PKG to CSTMR_DPSTS And Grant on BATCH_JOB Table 

-- created by sxg151 on 01/15/2019

GRANT EXECUTE ON CCN_BATCH_PKG TO CSTMR_DPSTS;

GRANT SELECT ON BATCH_JOB TO CSTMR_DPSTS;