/*
Below script will provide access on POS_DATA_GENERATION package to STORDRFT

Created : 10/08/2019 jxc517 CCN Project Team....
Changed :
*/
GRANT EXECUTE ON POS_DATA_GENERATION TO STORDRFT;
CREATE OR REPLACE SYNONYM STORDRFT.POS_DATA_GENERATION FOR CCN_UTILITY.POS_DATA_GENERATION;