/*
     Revoke_Batch_Job_ASP_1207.sql
     This Script REVOKES all access on BATCH_JOB table from all CCN users

     Created : 03/20/2019 mxs216 ASP-1207 CCN Project Team....
*/
REVOKE ALL PRIVILEGES ON BATCH_JOB FROM BANKING;
REVOKE ALL PRIVILEGES ON BATCH_JOB FROM COSTCNTR;
REVOKE ALL PRIVILEGES ON BATCH_JOB FROM CSTMR_DPSTS;
REVOKE ALL PRIVILEGES ON BATCH_JOB FROM STORDRFT;
