/*
     This is a rollback script for Revoke_Batch_Job_ASP_1207.sql
     This Script GRANTS all access back on BATCH_JOB table which was revocked by executing Revoke_Batch_Job_ASP_1207.sql 

     Created : 03/20/2019 mxs216 ASP-1207 CCN Project Team....
*/

GRANT INSERT, DELETE, SELECT, UPDATE ON BATCH_JOB TO BANKING;
GRANT UPDATE, REFERENCES, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK, SELECT, INSERT, INDEX, ALTER, DELETE ON BATCH_JOB TO COSTCNTR;
GRANT SELECT ON BATCH_JOB TO CSTMR_DPSTS;
GRANT SELECT ON BATCH_JOB TO STORDRFT;
