CREATE TABLE "CCN_UTILITY"."FILE_SET" 
   ("FILE_SET_ID" NUMBER, 
	"FILE_SET_NAME" VARCHAR2(50 BYTE), 
	"FILE_DESCRIPTION" VARCHAR2(100 BYTE), 
	"IS_ACTIVE" VARCHAR2(1 BYTE) NOT NULL ENABLE, 
	CONSTRAINT "FILE_SET_PK" PRIMARY KEY ("FILE_SET_ID")
   );

  
CREATE TABLE "CCN_UTILITY"."FILE_SET_DETAILS" 
   ("FILE_SET_DETAIL_ID" NUMBER, 
	"FILE_SET_ID" NUMBER, 
	"FILE_NAME" VARCHAR2(100 BYTE), 
	CONSTRAINT "FK_FILE_SET" FOREIGN KEY ("FILE_SET_ID")
	REFERENCES "CCN_UTILITY"."FILE_SET" ("FILE_SET_ID") ENABLE
    );
