/*******************************************************************************
Create synonym for each hierarchy detail view in utility database schema.

Permission needs to be granted to utility on all hierarchy details views to generate excel spreadsheet.

  CREATED : 07/12/2018 pxa852 CCN Project...
*******************************************************************************/


CREATE OR REPLACE SYNONYM ADMINORG_HIERARCHY_ATTRBT_VW FOR COSTCNTR.ADMINORG_HIERARCHY_ATTRBT_VW;


CREATE OR REPLACE SYNONYM ADMIN_TO_SALES_AREA_HRCHY_VW FOR COSTCNTR.ADMIN_TO_SALES_AREA_HRCHY_VW;


CREATE OR REPLACE SYNONYM ADMIN_TO_SALES_DIST_HRCHY_VW FOR COSTCNTR.ADMIN_TO_SALES_DIST_HRCHY_VW;


CREATE OR REPLACE SYNONYM ADMIN_TO_SALES_DIV_HRCHY_VW FOR COSTCNTR.ADMIN_TO_SALES_DIV_HRCHY_VW;


CREATE OR REPLACE SYNONYM ALTERNATE_DAD_DETAIL_VIEW FOR COSTCNTR.ALTERNATE_DAD_DETAIL_VIEW;


CREATE OR REPLACE SYNONYM CREDIT_HIERARCHY_DETAIL_VIEW FOR COSTCNTR.CREDIT_HIERARCHY_DETAIL_VIEW;


CREATE OR REPLACE SYNONYM GLOBAL_HIERARCHY_ATTRBT_VW FOR COSTCNTR.GLOBAL_HIERARCHY_ATTRBT_VW;


CREATE OR REPLACE SYNONYM LEGACY_GL_DIVISION_DETAIL_VIEW FOR COSTCNTR.LEGACY_GL_DIVISION_DETAIL_VIEW; 


CREATE OR REPLACE SYNONYM PRICE_DISTRICT_DETAIL_VIEW FOR COSTCNTR.PRICE_DISTRICT_DETAIL_VIEW; 

 
CREATE OR REPLACE SYNONYM FACTS_DIVISION_DETAIL_VIEW FOR COSTCNTR.FACTS_DIVISION_DETAIL_VIEW;

commit;