/*
Created : 06/09/2017 jxc517 CCN Project Team....
*/
CREATE OR REPLACE SYNONYM ADDRESS_MEX FOR COSTCNTR.ADDRESS_MEX;
CREATE OR REPLACE SYNONYM ADDRESS_BRB FOR COSTCNTR.ADDRESS_BRB;
CREATE OR REPLACE SYNONYM ADDRESS_OTHER FOR COSTCNTR.ADDRESS_OTHER;
CREATE OR REPLACE SYNONYM CANADA_FIPS_CODE FOR COSTCNTR.CANADA_FIPS_CODE;