-- Created by bxa919 on 02/20/2018


CREATE OR REPLACE SYNONYM CCN_PRICING_DISTRICT_USA FOR COSTCNTR.CCN_PRICING_DISTRICT_USA;
CREATE OR REPLACE SYNONYM CCN_PRICING_DISTRICT_CAN FOR COSTCNTR.CCN_PRICING_DISTRICT_CAN;