-- Synonym on CCN_SPREADSHEET_PKG
-- run this in CCN_UTILITY
-- created by axm868 on 08/07/2019 for CCNBN-12

CREATE OR REPLACE SYNONYM BANKING.CCN_SPREADSHEET_PKG FOR CCN_UTILITY.CCN_SPREADSHEET_PKG;