--Hierarchy History Tables
--ADMIN_SALES_AREA_E_DETAIL_H
---------------------------
  CREATE TABLE "COSTCNTR"."ADMIN_SALES_AREA_E_DETAIL_H" 
   (	"HRCHY_HDR_NAME" VARCHAR2(100),
	"HRCHY_DTL_LEVEL" VARCHAR2(2),
	"HRCHY_DTL_PREV_LVL_VAL" VARCHAR2(1000),
	"HRCHY_DTL_CURR_LVL_VAL" VARCHAR2(1000),
	"HRCHY_DTL_NEXT_LVL_VAL" VARCHAR2(1000),
	"HRCHY_DTL_EFF_DATE" DATE,
	"HRCHY_DTL_EXP_DATE" DATE,
	"HRCHY_DTL_DESC" VARCHAR2(100),
	"UPPER_LVL_VER_VALUE" VARCHAR2(100)
   ) ORGANIZATION EXTERNAL
  ( TYPE ORACLE_LOADER
    DEFAULT DIRECTORY "CCN_DATAFILES"
    ACCESS PARAMETERS 
    ( records delimited by newline 
         FIELDS TERMINATED BY '~'
         LRTRIM
         missing field values are null 
         ( 
           HRCHY_HDR_NAME,
	   HRCHY_DTL_LEVEL,
	   HRCHY_DTL_PREV_LVL_VAL,
	   HRCHY_DTL_CURR_LVL_VAL,
	   HRCHY_DTL_NEXT_LVL_VAL,
	   HRCHY_DTL_EFF_DATE DATE 'YYYYMMDD',
	   HRCHY_DTL_EXP_DATE DATE 'YYYYMMDD',
	   HRCHY_DTL_DESC,
           UPPER_LVL_VER_VALUE
         ) 
           ) 
    LOCATION 
    ( 'admin_to_sales_area_h.txt'
    ) 
  ) 
  REJECT LIMIT UNLIMITED
  PARALLEL ;

--CITY_MANAGER_DAD_E_DETAIL_H
---------------------------
  CREATE TABLE "COSTCNTR"."CITY_MANAGER_DAD_E_DETAIL_H" 
   (	"HRCHY_HDR_NAME" VARCHAR2(100),
	"HRCHY_DTL_LEVEL" VARCHAR2(2),
	"HRCHY_DTL_PREV_LVL_VAL" VARCHAR2(1000),
	"HRCHY_DTL_CURR_LVL_VAL" VARCHAR2(1000),
	"HRCHY_DTL_NEXT_LVL_VAL" VARCHAR2(1000),
	"HRCHY_DTL_EFF_DATE" DATE,
	"HRCHY_DTL_EXP_DATE" DATE,
	"HRCHY_DTL_DESC" VARCHAR2(100),
	"UPPER_LVL_VER_VALUE" VARCHAR2(1000)
   ) ORGANIZATION EXTERNAL
  ( TYPE ORACLE_LOADER
    DEFAULT DIRECTORY "CCN_DATAFILES"
    ACCESS PARAMETERS 
    ( records delimited by newline 
         FIELDS TERMINATED BY '~'
         LRTRIM
         missing field values are null 
         ( 
           HRCHY_HDR_NAME,
	   HRCHY_DTL_LEVEL,
	   HRCHY_DTL_PREV_LVL_VAL,
	   HRCHY_DTL_CURR_LVL_VAL,
	   HRCHY_DTL_NEXT_LVL_VAL,
	   HRCHY_DTL_EFF_DATE DATE 'YYYYMMDD',
	   HRCHY_DTL_EXP_DATE DATE 'YYYYMMDD',
	   HRCHY_DTL_DESC,
           UPPER_LVL_VER_VALUE
         ) 
           ) 
    LOCATION 
    ( 'city_manager_dad_h.txt'
    ) 
  ) 
  REJECT LIMIT UNLIMITED
  PARALLEL ;

--GLOBAL_HIERARCHY_E_DETAIL_H
---------------------------
  CREATE TABLE "COSTCNTR"."GLOBAL_HIERARCHY_E_DETAIL_H" 
   (	"HRCHY_HDR_NAME" VARCHAR2(100),
	"HRCHY_DTL_LEVEL" VARCHAR2(2),
	"HRCHY_DTL_PREV_LVL_VAL" VARCHAR2(1000),
	"HRCHY_DTL_CURR_LVL_VAL" VARCHAR2(1000),
	"HRCHY_DTL_NEXT_LVL_VAL" VARCHAR2(1000),
	"HRCHY_DTL_EFF_DATE" DATE,
	"HRCHY_DTL_EXP_DATE" DATE,
	"HRCHY_DTL_DESC" VARCHAR2(100),
	"UPPER_LVL_VER_VALUE" VARCHAR2(100)
   ) ORGANIZATION EXTERNAL
  ( TYPE ORACLE_LOADER
    DEFAULT DIRECTORY "CCN_DATAFILES"
    ACCESS PARAMETERS 
    ( records delimited by newline 
         FIELDS TERMINATED BY '~'
         LRTRIM
         missing field values are null 
         ( 
           HRCHY_HDR_NAME,
	   HRCHY_DTL_LEVEL,
	   HRCHY_DTL_PREV_LVL_VAL,
	   HRCHY_DTL_CURR_LVL_VAL,
	   HRCHY_DTL_NEXT_LVL_VAL,
	   HRCHY_DTL_EFF_DATE DATE 'YYYYMMDD',
	   HRCHY_DTL_EXP_DATE DATE 'YYYYMMDD',
	   HRCHY_DTL_DESC,
           UPPER_LVL_VER_VALUE
         ) 
           ) 
    LOCATION 
    ( 'global_hierarchy_h.txt'
    ) 
  ) 
  REJECT LIMIT UNLIMITED
  PARALLEL ;

--FACTS_DIVISION_E_DETAIL_H
---------------------------
  CREATE TABLE "COSTCNTR"."FACTS_DIVISION_E_DETAIL_H" 
   (	"HRCHY_HDR_NAME" VARCHAR2(20),
	"HRCHY_DTL_LEVEL" VARCHAR2(2),
	"HRCHY_DTL_PREV_LVL_VAL" VARCHAR2(1000),
	"HRCHY_DTL_CURR_LVL_VAL" VARCHAR2(1000),
	"HRCHY_DTL_NEXT_LVL_VAL" VARCHAR2(1000),
	"HRCHY_DTL_EFF_DATE" DATE,
	"HRCHY_DTL_EXP_DATE" DATE,
	"HRCHY_DTL_DESC" VARCHAR2(100),
	"UPPER_LVL_VER_VALUE" VARCHAR2(1000)
   ) ORGANIZATION EXTERNAL
  ( TYPE ORACLE_LOADER
    DEFAULT DIRECTORY "CCN_DATAFILES"
    ACCESS PARAMETERS 
    ( records delimited by newline 
         FIELDS TERMINATED BY '~'
         LRTRIM
         missing field values are null 
         ( 
           HRCHY_HDR_NAME,
	   HRCHY_DTL_LEVEL,
	   HRCHY_DTL_PREV_LVL_VAL,
	   HRCHY_DTL_CURR_LVL_VAL,
	   HRCHY_DTL_NEXT_LVL_VAL,
	   HRCHY_DTL_EFF_DATE DATE 'YYYYMMDD',
	   HRCHY_DTL_EXP_DATE DATE 'YYYYMMDD',
	   HRCHY_DTL_DESC,
	   UPPER_LVL_VER_VALUE 
         ) 
           ) 
    LOCATION 
    ( 'facts_division_h.txt'
    ) 
  ) 
  REJECT LIMIT UNLIMITED
  PARALLEL ;

--LEGACY_GL_DIVISION_E_DTL_H
---------------------------
  CREATE TABLE "COSTCNTR"."LEGACY_GL_DIVISION_E_DTL_H" 
   (	"HRCHY_HDR_NAME" VARCHAR2(20),
	"HRCHY_DTL_LEVEL" VARCHAR2(2),
	"HRCHY_DTL_PREV_LVL_VAL" VARCHAR2(1000),
	"HRCHY_DTL_CURR_LVL_VAL" VARCHAR2(1000),
	"HRCHY_DTL_NEXT_LVL_VAL" VARCHAR2(1000),
	"HRCHY_DTL_EFF_DATE" DATE,
	"HRCHY_DTL_EXP_DATE" DATE,
	"HRCHY_DTL_DESC" VARCHAR2(100),
	"UPPER_LVL_VER_VALUE" VARCHAR2(1000)
   ) ORGANIZATION EXTERNAL
  ( TYPE ORACLE_LOADER
    DEFAULT DIRECTORY "CCN_DATAFILES"
    ACCESS PARAMETERS 
    ( records delimited by newline 
         FIELDS TERMINATED BY '~'
         LRTRIM
         missing field values are null 
         ( 
           HRCHY_HDR_NAME,
	   HRCHY_DTL_LEVEL,
	   HRCHY_DTL_PREV_LVL_VAL,
	   HRCHY_DTL_CURR_LVL_VAL,
	   HRCHY_DTL_NEXT_LVL_VAL,
	   HRCHY_DTL_EFF_DATE DATE 'YYYYMMDD',
	   HRCHY_DTL_EXP_DATE DATE 'YYYYMMDD',
	   HRCHY_DTL_DESC,
	   UPPER_LVL_VER_VALUE 
         ) 
           ) 
    LOCATION 
    ( 'legacy_gl_division_h.txt'
    ) 
  ) 
  REJECT LIMIT UNLIMITED
  PARALLEL ;

--ADMIN_SALES_DIV_E_DETAIL_H
---------------------------
  CREATE TABLE "COSTCNTR"."ADMIN_SALES_DIV_E_DETAIL_H" 
   (	"HRCHY_HDR_NAME" VARCHAR2(100),
	"HRCHY_DTL_LEVEL" VARCHAR2(2),
	"HRCHY_DTL_PREV_LVL_VAL" VARCHAR2(1000),
	"HRCHY_DTL_CURR_LVL_VAL" VARCHAR2(1000),
	"HRCHY_DTL_NEXT_LVL_VAL" VARCHAR2(1000),
	"HRCHY_DTL_EFF_DATE" DATE,
	"HRCHY_DTL_EXP_DATE" DATE,
	"HRCHY_DTL_DESC" VARCHAR2(100),
	"UPPER_LVL_VER_VALUE" VARCHAR2(100)
   ) ORGANIZATION EXTERNAL
  ( TYPE ORACLE_LOADER
    DEFAULT DIRECTORY "CCN_DATAFILES"
    ACCESS PARAMETERS 
    ( records delimited by newline 
         FIELDS TERMINATED BY '~'
         LRTRIM
         missing field values are null 
         ( 
           HRCHY_HDR_NAME,
	   HRCHY_DTL_LEVEL,
	   HRCHY_DTL_PREV_LVL_VAL,
	   HRCHY_DTL_CURR_LVL_VAL,
	   HRCHY_DTL_NEXT_LVL_VAL,
	   HRCHY_DTL_EFF_DATE DATE 'YYYYMMDD',
	   HRCHY_DTL_EXP_DATE DATE 'YYYYMMDD',
	   HRCHY_DTL_DESC,
           UPPER_LVL_VER_VALUE
         ) 
           ) 
    LOCATION 
    ( 'admin_to_sales_division_h.txt'
    ) 
  ) 
  REJECT LIMIT UNLIMITED
  PARALLEL ;

--ALTERNATE_DAD_E_DETAIL_H
---------------------------
  CREATE TABLE "COSTCNTR"."ALTERNATE_DAD_E_DETAIL_H" 
   (	"HRCHY_HDR_NAME" VARCHAR2(100),
	"HRCHY_DTL_LEVEL" VARCHAR2(2),
	"HRCHY_DTL_PREV_LVL_VAL" VARCHAR2(1000),
	"HRCHY_DTL_CURR_LVL_VAL" VARCHAR2(1000),
	"HRCHY_DTL_NEXT_LVL_VAL" VARCHAR2(1000),
	"HRCHY_DTL_EFF_DATE" DATE,
	"HRCHY_DTL_EXP_DATE" DATE,
	"HRCHY_DTL_DESC" VARCHAR2(100),
	"UPPER_LVL_VER_VALUE" VARCHAR2(1000)
   ) ORGANIZATION EXTERNAL
  ( TYPE ORACLE_LOADER
    DEFAULT DIRECTORY "CCN_DATAFILES"
    ACCESS PARAMETERS 
    ( records delimited by newline 
         FIELDS TERMINATED BY '~'
         LRTRIM
         missing field values are null 
         ( 
           HRCHY_HDR_NAME,
	   HRCHY_DTL_LEVEL,
	   HRCHY_DTL_PREV_LVL_VAL,
	   HRCHY_DTL_CURR_LVL_VAL,
	   HRCHY_DTL_NEXT_LVL_VAL,
	   HRCHY_DTL_EFF_DATE DATE 'YYYYMMDD',
	   HRCHY_DTL_EXP_DATE DATE 'YYYYMMDD',
	   HRCHY_DTL_DESC,
           UPPER_LVL_VER_VALUE
         ) 
           ) 
    LOCATION 
    ( 'alternate_dad_h.txt'
    ) 
  ) 
  REJECT LIMIT UNLIMITED
  PARALLEL ;

--ADMIN_SALES_DIST_E_DETAIL_H
---------------------------
  CREATE TABLE "COSTCNTR"."ADMIN_SALES_DIST_E_DETAIL_H" 
   (	"HRCHY_HDR_NAME" VARCHAR2(100),
	"HRCHY_DTL_LEVEL" VARCHAR2(2),
	"HRCHY_DTL_PREV_LVL_VAL" VARCHAR2(1000),
	"HRCHY_DTL_CURR_LVL_VAL" VARCHAR2(1000),
	"HRCHY_DTL_NEXT_LVL_VAL" VARCHAR2(1000),
	"HRCHY_DTL_EFF_DATE" DATE,
	"HRCHY_DTL_EXP_DATE" DATE,
	"HRCHY_DTL_DESC" VARCHAR2(100),
	"UPPER_LVL_VER_VALUE" VARCHAR2(100)
   ) ORGANIZATION EXTERNAL
  ( TYPE ORACLE_LOADER
    DEFAULT DIRECTORY "CCN_DATAFILES"
    ACCESS PARAMETERS 
    ( records delimited by newline 
         FIELDS TERMINATED BY '~'
         LRTRIM
         missing field values are null 
         ( 
           HRCHY_HDR_NAME,
	   HRCHY_DTL_LEVEL,
	   HRCHY_DTL_PREV_LVL_VAL,
	   HRCHY_DTL_CURR_LVL_VAL,
	   HRCHY_DTL_NEXT_LVL_VAL,
	   HRCHY_DTL_EFF_DATE DATE 'YYYYMMDD',
	   HRCHY_DTL_EXP_DATE DATE 'YYYYMMDD',
	   HRCHY_DTL_DESC,
           UPPER_LVL_VER_VALUE
         ) 
           ) 
    LOCATION 
    ( 'admin_to_sales_district_h.txt'
    ) 
  ) 
  REJECT LIMIT UNLIMITED
  PARALLEL ;
