--TEMP_TERR_PHONE
---------------------------
DROP TABLE "COSTCNTR"."TEMP_TERR_PHONE";
  CREATE TABLE "COSTCNTR"."TEMP_TERR_PHONE" 
   (	"FILLER_1" VARCHAR2(7),
	"COST_CENTER_CODE" VARCHAR2(4),
	"MAINT_FUNCTION" VARCHAR2(2),
	"MAINTENANCE_TYPE" VARCHAR2(2),
	"MAINTENANCE_CODE" VARCHAR2(1),
	"PHONE_AREA_CODE" VARCHAR2(3),
	"PHONE_NUMBER" VARCHAR2(7),
	"PHONE_EXTENSION" VARCHAR2(4),
	"PHONE_AREA_CODE_2" VARCHAR2(3),
	"PHONE_NUMBER_2" VARCHAR2(7),
	"PHONE_EXTENSION_2" VARCHAR2(4),
	"CONTROL_CLERK" VARCHAR2(2),
	"OPEN_TIME" VARCHAR2(4),
	"CLOSE_TIME" VARCHAR2(4),
	"ACT_FT_EMP_COUNT" VARCHAR2(3),
	"BGT_FT_EMP_COUNT" VARCHAR2(3),
	"PERP_INV_START_DATE" VARCHAR2(6),
	"LAST_MOVE_DATE" VARCHAR2(6),
	"ACT_PT_EMP_COUNT" VARCHAR2(3),
	"BGT_PT_EMP_COUNT" VARCHAR2(3),
	"FILLER_2" VARCHAR2(2)
   ) ORGANIZATION EXTERNAL
  ( TYPE ORACLE_LOADER
    DEFAULT DIRECTORY "CCN_LOAD_FILES"
    ACCESS PARAMETERS 
    ( RECORDS FIXED 81 FIELDS( FILLER_1 CHAR(7), COST_CENTER_CODE CHAR(4), MAINT_FUNCTION CHAR(2), 
    MAINTENANCE_TYPE CHAR(2), MAINTENANCE_CODE CHAR(1), PHONE_AREA_CODE CHAR(3), PHONE_NUMBER CHAR(7), PHONE_EXTENSION CHAR(4), 
    PHONE_AREA_CODE_2 CHAR(3), PHONE_NUMBER_2 CHAR(7), PHONE_EXTENSION_2 CHAR(4), CONTROL_CLERK CHAR(2), OPEN_TIME CHAR(4),
    CLOSE_TIME CHAR(4), ACT_FT_EMP_COUNT CHAR(3), BGT_FT_EMP_COUNT CHAR(3), PERP_INV_START_DATE CHAR(6), LAST_MOVE_DATE CHAR(6), 
    ACT_PT_EMP_COUNT CHAR(3), BGT_PT_EMP_COUNT CHAR(3), FILLER_2 CHAR(2)) ) 
    LOCATION 
    ( 'phone_update_file.txt'
    ) 
  ) 
 ;

--TEMP_FIPS_CODE_UPDATE
---------------------------
DROP TABLE "COSTCNTR"."TEMP_FIPS_CODE_UPDATE";
  CREATE TABLE "COSTCNTR"."TEMP_FIPS_CODE_UPDATE" 
   (	"FIPS_CODE" VARCHAR2(10),
	"FIPS_STORE_PRE" VARCHAR2(1),
	"FIPS_STORE_NBR" VARCHAR2(4),
	"FIPS_STORE_SUF" VARCHAR2(1),
	"FIPS_COUNTY" VARCHAR2(16),
	"FIPS_CITY" VARCHAR2(16),
	"FIPS_STATE" VARCHAR2(2),
	"FIPS_ZIP_CODE" VARCHAR2(6)
   ) ORGANIZATION EXTERNAL
  ( TYPE ORACLE_LOADER
    DEFAULT DIRECTORY "CCN_LOAD_FILES"
    ACCESS PARAMETERS 
    ( RECORDS FIXED 081
  
fields ( 
    fips_code                  char(10) ,
    filler_01                  char(06) ,
    fips_store_pre             char(01) ,
    fips_store_nbr             char(04) ,
    fips_store_suf             char(01) ,
    filler_02                  char(02) ,
    fips_county                char(16) ,
    fips_city                  char(16) ,
    fips_state                 char(02) ,
    filler_03                  char(06) ,
    fips_zip_code              char(06) ,
    filler_04                  char(10) ,
    carr_return                char(01)
)  
) 
    LOCATION 
    ( "CCN_LOAD_FILES":'fips_update_file.txt'
    ) 
  ) 
 ;
