CREATE TABLE "COSTCNTR"."COST_CENTER_HIERARCHY_TRNSFR" 
   (	"COST_CENTER_CODE" VARCHAR2(6 BYTE), 
	"MANAGER_ID" VARCHAR2(20 BYTE), 
	"HIERARCHY_NAME" VARCHAR2(100 BYTE), 
	"FROM_HIERARCHY" VARCHAR2(100 BYTE), 
	"TO_HIERARCHY" VARCHAR2(100 BYTE)
   ) 
   ORGANIZATION EXTERNAL 
    ( TYPE ORACLE_LOADER
      DEFAULT DIRECTORY "CCN_LOAD_FILES"
      ACCESS PARAMETERS
      ( RECORDS DELIMITED BY NEWLINE SKIP 1 badfile "CCN_LOAD_FILES":'
    COST_CENTER_HIERARCHY_TRNSFR.bad' logfile "CCN_LOAD_FILES":'
    COST_CENTER_HIERARCHY_TRNSFR.log' FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY
    '"' LDRTRIM MISSING FIELD VALUES ARE NULL(COST_CENTER_CODE ,MANAGER_ID,
    HIERARCHY_NAME, FROM_HIERARCHY, TO_HIERARCHY)
          )
      LOCATION
       ( 'COST_CENTER_HIERARCHY_TRNSFR.csv'
       )
    )
   REJECT LIMIT UNLIMITED;