/*
select '	"OTHER_'||column_name||'" VARCHAR2('||data_length||' BYTE),'
from all_tab_columns where table_name = 'ADDRESS_OTHER' order by column_id;

select '                                        OTHER_'||column_name||','
from all_tab_columns where table_name = 'ADDRESS_OTHER' order by column_id;

*/
DROP TABLE COST_CENTER_STORE;
DROP TABLE COST_CENTER_TERRITORY;
DROP TABLE COST_CENTER_ADMINISTRATION;
DROP TABLE COST_CENTER_REAL_ESTATE;
DROP TABLE COST_CENTER_OTHER;

--COST_CENTER_STORE external table creation
CREATE TABLE "COSTCNTR"."COST_CENTER_STORE" 
   (	"COST_CENTER_CODE" VARCHAR2(6 BYTE), 
	"COST_CENTER_NAME" VARCHAR2(35 BYTE), 
	"CATEGORY" VARCHAR2(1 BYTE), 
	"ENTITY_TYPE" VARCHAR2(2 BYTE), 
	"STATEMENT_TYPE" VARCHAR2(2 BYTE), 
	"COUNTRY_CODE" VARCHAR2(3 BYTE), 
	"TRANSPORT_TYPE" VARCHAR2(5 BYTE), 
	"BEGIN_DATE" VARCHAR2(8 BYTE), 
	"OPEN_DATE" VARCHAR2(8 BYTE), 
	"MOVE_DATE" VARCHAR2(8 BYTE), 
	"CLOSE_DATE" VARCHAR2(8 BYTE), 
	"FINANCIAL_CLOSE_DATE" VARCHAR2(8 BYTE), 
	"POS_PROG_VER_EFF_DATE" VARCHAR2(8 BYTE), 
	"UPS_ZONE_CODE" VARCHAR2(1 BYTE), 
	"RPS_ZONE_CODE" VARCHAR2(1 BYTE), 
	"CURRENCY_CODE" VARCHAR2(3 BYTE), 
	"POS_PROG_VER_NBR" VARCHAR2(5 BYTE), 
	"LEASE_OWN_CODE" VARCHAR2(1 BYTE), 
	"MISSION_TYPE_CODE" VARCHAR2(2 BYTE), 
	"DUNS_NUMBER" VARCHAR2(9 BYTE), 
	"PRI_LOGO_GROUP_IND" VARCHAR2(3 BYTE), 
	"SCD_LOGO_GROUP_IND" VARCHAR2(3 BYTE), 
	"BANKING_TYPE" VARCHAR2(1 BYTE), 
	"DEPOSIT_BAG_REORDER" VARCHAR2(1 BYTE), 
	"DEPOSIT_TICKET_REORDER" VARCHAR2(1 BYTE), 
	"POP_KIT_CODE" VARCHAR2(1 BYTE), 
	"GLOBAL_HIERARCHY_IND" VARCHAR2(1 BYTE), 
	"STD_COST_IDENTIFIER" VARCHAR2(1 BYTE),
	"PRIM_COST_IDENTIFIER" VARCHAR2(1 BYTE),
	"STATUS_CODE" VARCHAR2(1 BYTE), 
	"STATUS_EFFECTIVE_DATE" VARCHAR2(8 BYTE), 
	"STATUS_EXPIRATION_DATE" VARCHAR2(8 BYTE), 
	"TYPE_CODE" VARCHAR2(2 BYTE), 
	"TYPE_EFFECTIVE_DATE" VARCHAR2(8 BYTE), 
	"TYPE_EXPIRATION_DATE" VARCHAR2(8 BYTE), 
	"STORE_CATEGORY" VARCHAR2(1 BYTE),
	"PERP_INV_START_DATE" VARCHAR2(8 BYTE),
	"CLASSIFICATION_CODE" VARCHAR2(2 BYTE),
	"INVENTORY_INDICATOR" VARCHAR2(1 BYTE),
	"RURAL_METRO_ZONE_CODE" VARCHAR2(1 BYTE),
	"SELLING_STORE_FLAG" VARCHAR2(1 BYTE),
	"MARKETING_CATEGORY" VARCHAR2(1 BYTE),
	"MARKETING_TYPE" VARCHAR2(2 BYTE),
	"MKT_EFFECTIVE_DATE" VARCHAR2(8 BYTE),
	"MKT_EXPIRATION_DATE" VARCHAR2(8 BYTE),
	"MKT_BRAND" VARCHAR2(1 BYTE),
	"MKT_MISSION" VARCHAR2(3 BYTE),
	"MKT_SALES_FLOOR_SIZE" VARCHAR2(1 BYTE),
	"MKT_WAREHOUSE_SIZE" VARCHAR2(1 BYTE),
	"MKT_REAL_ESTATE_SETTING" VARCHAR2(1 BYTE),
	"TWJ_STATE" VARCHAR2(2 BYTE),
	"TWJ_ZIP" VARCHAR2(10 BYTE),
	"TWJ_GEO" VARCHAR2(2 BYTE),
	"TWJ_MAINTENANCE_DATE" VARCHAR2(8 BYTE),
	"TWJ_COUNTRY" VARCHAR2(2 BYTE),
	"TWJ_COMPANY" VARCHAR2(2 BYTE),
	"LAST_MAINT_DATE" VARCHAR2(8 BYTE),
	"LAST_MAINT_METHOD_ID" VARCHAR2(8 BYTE),
	"LAST_MAINT_USER_ID" VARCHAR2(8 BYTE),
	"USA_ADDRESS_TYPE" VARCHAR2(2 BYTE),
	"USA_EFFECTIVE_DATE" VARCHAR2(8 BYTE),
	"USA_EXPIRATION_DATE" VARCHAR2(8 BYTE),
	"USA_ADDRESS_LINE_1" VARCHAR2(35 BYTE),
	"USA_ADDRESS_LINE_2" VARCHAR2(35 BYTE),
	"USA_ADDRESS_LINE_3" VARCHAR2(35 BYTE),
	"USA_CITY" VARCHAR2(25 BYTE),
	"USA_STATE_CODE" VARCHAR2(2 BYTE),
	"USA_ZIP_CODE" VARCHAR2(5 BYTE),
	"USA_ZIP_CODE_4" VARCHAR2(4 BYTE),
	"USA_COUNTY" VARCHAR2(30 BYTE),
	"USA_FIPS_CODE" VARCHAR2(10 BYTE),
	"USA_DESTINATION_POINT" VARCHAR2(2 BYTE),
	"USA_CHECK_DIGIT" VARCHAR2(1 BYTE),
	"USA_VALID_ADDRESS" VARCHAR2(1 BYTE),
	"USA_COUNTRY_CODE" VARCHAR2(3 BYTE),
	"CAN_ADDRESS_TYPE" VARCHAR2(2 BYTE),
	"CAN_EFFECTIVE_DATE" VARCHAR2(8 BYTE),
	"CAN_EXPIRATION_DATE" VARCHAR2(8 BYTE),
	"CAN_ADDRESS_LINE_1" VARCHAR2(35 BYTE),
	"CAN_ADDRESS_LINE_2" VARCHAR2(35 BYTE),
	"CAN_ADDRESS_LINE_3" VARCHAR2(35 BYTE),
	"CAN_CITY" VARCHAR2(25 BYTE),
	"CAN_PROVINCE_CODE" VARCHAR2(2 BYTE),
	"CAN_POSTAL_CODE" VARCHAR2(6 BYTE),
	"CAN_VALID_ADDRESS" VARCHAR2(1 BYTE),
	"CAN_COUNTRY_CODE" VARCHAR2(3 BYTE), 
	"MEX_ADDRESS_TYPE" VARCHAR2(2 BYTE),
	"MEX_EFFECTIVE_DATE" VARCHAR2(8 BYTE),
	"MEX_EXPIRATION_DATE" VARCHAR2(8 BYTE),
	"MEX_ADDRESS_LINE_1" VARCHAR2(35 BYTE),
	"MEX_ADDRESS_LINE_2" VARCHAR2(35 BYTE),
	"MEX_ADDRESS_LINE_3" VARCHAR2(35 BYTE),
	"MEX_CITY" VARCHAR2(25 BYTE),
	"MEX_PROVINCE_CODE" VARCHAR2(5 BYTE),
	"MEX_POSTAL_CODE" VARCHAR2(5 BYTE),
	"MEX_VALID_ADDRESS" VARCHAR2(1 BYTE),
	"MEX_COUNTRY_CODE" VARCHAR2(3 BYTE),
	"OTHER_ADDRESS_TYPE" VARCHAR2(2 BYTE),
	"OTHER_EFFECTIVE_DATE" VARCHAR2(8 BYTE),
	"OTHER_EXPIRATION_DATE" VARCHAR2(8 BYTE),
	"OTHER_ADDRESS_LINE_1" VARCHAR2(35 BYTE),
	"OTHER_ADDRESS_LINE_2" VARCHAR2(35 BYTE),
	"OTHER_ADDRESS_LINE_3" VARCHAR2(35 BYTE),
	"OTHER_CITY" VARCHAR2(25 BYTE),
	"OTHER_PROVINCE_CODE" VARCHAR2(25 BYTE),
	"OTHER_STATE_CODE" VARCHAR2(25 BYTE),
	"OTHER_POSTAL_CODE" VARCHAR2(10 BYTE),
	"OTHER_VALID_ADDRESS" VARCHAR2(1 BYTE),
	"OTHER_COUNTRY_CODE" VARCHAR2(3 BYTE),
	"PRI_PHONE_NUMBER_TYPE" VARCHAR2(5 BYTE), 
	"PRI_PHONE_AREA_CODE" VARCHAR2(4 BYTE), 
	"PRI_PHONE_NUMBER" VARCHAR2(7 BYTE), 
	"PRI_PHONE_EXTENSION" VARCHAR2(6 BYTE), 
	"SCD_PHONE_NUMBER_TYPE" VARCHAR2(5 BYTE), 
	"SCD_PHONE_AREA_CODE" VARCHAR2(4 BYTE), 
	"SCD_PHONE_NUMBER" VARCHAR2(7 BYTE), 
	"SCD_PHONE_EXTENSION" VARCHAR2(6 BYTE), 
	"FAX_PHONE_NUMBER_TYPE" VARCHAR2(5 BYTE), 
	"FAX_PHONE_AREA_CODE" VARCHAR2(4 BYTE), 
	"FAX_PHONE_NUMBER" VARCHAR2(7 BYTE), 
	"FAX_PHONE_EXTENSION" VARCHAR2(6 BYTE),
	"ADMIN_TO_SALES_AREA" VARCHAR2(100 BYTE),
	"ADMIN_TO_SALES_DISTRICT" VARCHAR2(100 BYTE),
	"ADMIN_TO_SALES_DIVISION" VARCHAR2(100 BYTE),
	"ALTERNATE_DAD" VARCHAR2(100 BYTE),
	"FACTS_DIVISION" VARCHAR2(100 BYTE),
	"LEGACY_GL_DIVISION" VARCHAR2(100 BYTE),
	"GLOBAL_HIERARCHY" VARCHAR2(100 BYTE),
	"MANAGER_ID" VARCHAR2(20 BYTE)
) 
ORGANIZATION EXTERNAL(
         TYPE ORACLE_LOADER
         DEFAULT DIRECTORY "CCN_LOAD_FILES"
         ACCESS PARAMETERS
         (RECORDS DELIMITED BY NEWLINE SKIP 1
          badfile "CCN_LOAD_FILES":'COST_CENTER_STORE.bad'
          logfile "CCN_LOAD_FILES":'COST_CENTER_STORE.log'
          FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' LDRTRIM
          MISSING FIELD VALUES ARE NULL(COST_CENTER_CODE,
                                        COST_CENTER_NAME,
                                        CATEGORY,
                                        ENTITY_TYPE,
                                        STATEMENT_TYPE,
                                        COUNTRY_CODE,
                                        TRANSPORT_TYPE,
                                        BEGIN_DATE,
                                        OPEN_DATE,
                                        MOVE_DATE,
                                        CLOSE_DATE,
                                        FINANCIAL_CLOSE_DATE,
                                        POS_PROG_VER_EFF_DATE,
                                        UPS_ZONE_CODE,
                                        RPS_ZONE_CODE,
                                        CURRENCY_CODE,
                                        POS_PROG_VER_NBR,
                                        LEASE_OWN_CODE,
                                        MISSION_TYPE_CODE,
                                        DUNS_NUMBER,
                                        PRI_LOGO_GROUP_IND,
                                        SCD_LOGO_GROUP_IND,
                                        BANKING_TYPE,
                                        DEPOSIT_BAG_REORDER,
                                        DEPOSIT_TICKET_REORDER,
                                        POP_KIT_CODE,
                                        GLOBAL_HIERARCHY_IND,
                                        STD_COST_IDENTIFIER,
	                                    PRIM_COST_IDENTIFIER,
                                        STATUS_CODE,
                                        STATUS_EFFECTIVE_DATE,
                                        STATUS_EXPIRATION_DATE,
                                        TYPE_CODE,
                                        TYPE_EFFECTIVE_DATE,
                                        TYPE_EXPIRATION_DATE,
                                        STORE_CATEGORY,
                                        PERP_INV_START_DATE,
                                        CLASSIFICATION_CODE,
                                        INVENTORY_INDICATOR,
                                        RURAL_METRO_ZONE_CODE,
                                        SELLING_STORE_FLAG,
                                        MARKETING_CATEGORY,
                                        MARKETING_TYPE,
                                        MKT_EFFECTIVE_DATE,
                                        MKT_EXPIRATION_DATE,
                                        MKT_BRAND,
                                        MKT_MISSION,
                                        MKT_SALES_FLOOR_SIZE,
                                        MKT_WAREHOUSE_SIZE,
                                        MKT_REAL_ESTATE_SETTING,
                                        TWJ_STATE,
                                        TWJ_ZIP,
                                        TWJ_GEO,
                                        TWJ_MAINTENANCE_DATE,
                                        TWJ_COUNTRY,
                                        TWJ_COMPANY,
                                        LAST_MAINT_DATE,
                                        LAST_MAINT_METHOD_ID,
                                        LAST_MAINT_USER_ID,
                                        USA_ADDRESS_TYPE,
                                        USA_EFFECTIVE_DATE,
                                        USA_EXPIRATION_DATE,
                                        USA_ADDRESS_LINE_1,
                                        USA_ADDRESS_LINE_2,
                                        USA_ADDRESS_LINE_3,
                                        USA_CITY,
                                        USA_STATE_CODE,
                                        USA_ZIP_CODE,
                                        USA_ZIP_CODE_4,
                                        USA_COUNTY,
                                        USA_FIPS_CODE,
                                        USA_DESTINATION_POINT,
                                        USA_CHECK_DIGIT,
                                        USA_VALID_ADDRESS,
                                        USA_COUNTRY_CODE,
                                        CAN_ADDRESS_TYPE,
                                        CAN_EFFECTIVE_DATE,
                                        CAN_EXPIRATION_DATE,
                                        CAN_ADDRESS_LINE_1,
                                        CAN_ADDRESS_LINE_2,
                                        CAN_ADDRESS_LINE_3,
                                        CAN_CITY,
                                        CAN_PROVINCE_CODE,
                                        CAN_POSTAL_CODE,
                                        CAN_VALID_ADDRESS,
                                        CAN_COUNTRY_CODE, 
                                        MEX_ADDRESS_TYPE,
                                        MEX_EFFECTIVE_DATE,
                                        MEX_EXPIRATION_DATE,
                                        MEX_ADDRESS_LINE_1,
                                        MEX_ADDRESS_LINE_2,
                                        MEX_ADDRESS_LINE_3,
                                        MEX_CITY,
                                        MEX_PROVINCE_CODE,
                                        MEX_POSTAL_CODE,
                                        MEX_VALID_ADDRESS,
                                        MEX_COUNTRY_CODE,
                                        OTHER_ADDRESS_TYPE,
                                        OTHER_EFFECTIVE_DATE,
                                        OTHER_EXPIRATION_DATE,
                                        OTHER_ADDRESS_LINE_1,
                                        OTHER_ADDRESS_LINE_2,
                                        OTHER_ADDRESS_LINE_3,
                                        OTHER_CITY,
                                        OTHER_PROVINCE_CODE,
                                        OTHER_STATE_CODE,
                                        OTHER_POSTAL_CODE,
                                        OTHER_VALID_ADDRESS,
                                        OTHER_COUNTRY_CODE,
                                        PRI_PHONE_NUMBER_TYPE,
                                        PRI_PHONE_AREA_CODE,
                                        PRI_PHONE_NUMBER,
                                        PRI_PHONE_EXTENSION,
                                        SCD_PHONE_NUMBER_TYPE,
                                        SCD_PHONE_AREA_CODE,
                                        SCD_PHONE_NUMBER,
                                        SCD_PHONE_EXTENSION,
                                        FAX_PHONE_NUMBER_TYPE,
                                        FAX_PHONE_AREA_CODE,
                                        FAX_PHONE_NUMBER,
                                        FAX_PHONE_EXTENSION,
                                        ADMIN_TO_SALES_AREA,
                                        ADMIN_TO_SALES_DISTRICT,
                                        ADMIN_TO_SALES_DIVISION,
                                        ALTERNATE_DAD,
                                        FACTS_DIVISION,
                                        LEGACY_GL_DIVISION,
                                        GLOBAL_HIERARCHY,
                                        MANAGER_ID)
         )
         LOCATION ('COST_CENTER_STORE.csv')
)REJECT LIMIT UNLIMITED;

--COST_CENTER_TERRITORY external table creation
CREATE TABLE "COSTCNTR"."COST_CENTER_TERRITORY" 
   (	"COST_CENTER_CODE" VARCHAR2(6 BYTE), 
	"COST_CENTER_NAME" VARCHAR2(35 BYTE), 
	"CATEGORY" VARCHAR2(1 BYTE), 
	"ENTITY_TYPE" VARCHAR2(2 BYTE), 
	"STATEMENT_TYPE" VARCHAR2(2 BYTE), 
	"COUNTRY_CODE" VARCHAR2(3 BYTE), 
	"TRANSPORT_TYPE" VARCHAR2(5 BYTE), 
	"BEGIN_DATE" VARCHAR2(8 BYTE), 
	"OPEN_DATE" VARCHAR2(8 BYTE), 
	"MOVE_DATE" VARCHAR2(8 BYTE), 
	"CLOSE_DATE" VARCHAR2(8 BYTE), 
	"FINANCIAL_CLOSE_DATE" VARCHAR2(8 BYTE), 
	"POS_PROG_VER_EFF_DATE" VARCHAR2(8 BYTE), 
	"UPS_ZONE_CODE" VARCHAR2(1 BYTE), 
	"RPS_ZONE_CODE" VARCHAR2(1 BYTE), 
	"CURRENCY_CODE" VARCHAR2(3 BYTE), 
	"POS_PROG_VER_NBR" VARCHAR2(5 BYTE), 
	"LEASE_OWN_CODE" VARCHAR2(1 BYTE), 
	"MISSION_TYPE_CODE" VARCHAR2(2 BYTE), 
	"DUNS_NUMBER" VARCHAR2(9 BYTE), 
	"PRI_LOGO_GROUP_IND" VARCHAR2(3 BYTE), 
	"SCD_LOGO_GROUP_IND" VARCHAR2(3 BYTE), 
	"BANKING_TYPE" VARCHAR2(1 BYTE), 
	"DEPOSIT_BAG_REORDER" VARCHAR2(1 BYTE), 
	"DEPOSIT_TICKET_REORDER" VARCHAR2(1 BYTE), 
	"POP_KIT_CODE" VARCHAR2(1 BYTE), 
	"GLOBAL_HIERARCHY_IND" VARCHAR2(1 BYTE), 
	"STD_COST_IDENTIFIER" VARCHAR2(1 BYTE),
	"PRIM_COST_IDENTIFIER" VARCHAR2(1 BYTE),
	"STATUS_CODE" VARCHAR2(1 BYTE), 
	"STATUS_EFFECTIVE_DATE" VARCHAR2(8 BYTE), 
	"STATUS_EXPIRATION_DATE" VARCHAR2(8 BYTE), 
	"TYPE_CODE" VARCHAR2(2 BYTE), 
	"TYPE_EFFECTIVE_DATE" VARCHAR2(8 BYTE), 
	"TYPE_EXPIRATION_DATE" VARCHAR2(8 BYTE), 
	"TERRITORY_SLS_MGR_CODE" VARCHAR2(6 BYTE), 
	"TERRITORY_CATEGORY" VARCHAR2(1 BYTE), 
	"LEASE_CAR_INDICATOR" VARCHAR2(1 BYTE), 
	"TERRITORY_TYPE_BUSN_CODE" VARCHAR2(2 BYTE), 
	"HOME_STORE" VARCHAR2(6 BYTE), 
	"PRI_PHONE_NUMBER_TYPE" VARCHAR2(5 BYTE), 
	"PRI_PHONE_AREA_CODE" VARCHAR2(4 BYTE), 
	"PRI_PHONE_NUMBER" VARCHAR2(7 BYTE), 
	"PRI_PHONE_EXTENSION" VARCHAR2(6 BYTE), 
	"SCD_PHONE_NUMBER_TYPE" VARCHAR2(5 BYTE), 
	"SCD_PHONE_AREA_CODE" VARCHAR2(4 BYTE), 
	"SCD_PHONE_NUMBER" VARCHAR2(7 BYTE), 
	"SCD_PHONE_EXTENSION" VARCHAR2(6 BYTE), 
	"FAX_PHONE_NUMBER_TYPE" VARCHAR2(5 BYTE), 
	"FAX_PHONE_AREA_CODE" VARCHAR2(4 BYTE), 
	"FAX_PHONE_NUMBER" VARCHAR2(7 BYTE), 
	"FAX_PHONE_EXTENSION" VARCHAR2(6 BYTE),
	"ADMIN_TO_SALES_AREA" VARCHAR2(100 BYTE),
	"ADMIN_TO_SALES_DISTRICT" VARCHAR2(100 BYTE),
	"ADMIN_TO_SALES_DIVISION" VARCHAR2(100 BYTE),
	"ALTERNATE_DAD" VARCHAR2(100 BYTE),
	"FACTS_DIVISION" VARCHAR2(100 BYTE),
	"LEGACY_GL_DIVISION" VARCHAR2(100 BYTE),
	"GLOBAL_HIERARCHY" VARCHAR2(100 BYTE),
	"MANAGER_ID" VARCHAR2(20 BYTE)
) 
ORGANIZATION EXTERNAL(
         TYPE ORACLE_LOADER
         DEFAULT DIRECTORY "CCN_LOAD_FILES"
         ACCESS PARAMETERS
         (RECORDS DELIMITED BY NEWLINE SKIP 1
          badfile "CCN_LOAD_FILES":'COST_CENTER_TERRITORY.bad'
          logfile "CCN_LOAD_FILES":'COST_CENTER_TERRITORY.log'
          FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' LDRTRIM
          MISSING FIELD VALUES ARE NULL(COST_CENTER_CODE,
                                        COST_CENTER_NAME,
                                        CATEGORY,
                                        ENTITY_TYPE,
                                        STATEMENT_TYPE,
                                        COUNTRY_CODE,
                                        TRANSPORT_TYPE,
                                        BEGIN_DATE,
                                        OPEN_DATE,
                                        MOVE_DATE,
                                        CLOSE_DATE,
                                        FINANCIAL_CLOSE_DATE,
                                        POS_PROG_VER_EFF_DATE,
                                        UPS_ZONE_CODE,
                                        RPS_ZONE_CODE,
                                        CURRENCY_CODE,
                                        POS_PROG_VER_NBR,
                                        LEASE_OWN_CODE,
                                        MISSION_TYPE_CODE,
                                        DUNS_NUMBER,
                                        PRI_LOGO_GROUP_IND,
                                        SCD_LOGO_GROUP_IND,
                                        BANKING_TYPE,
                                        DEPOSIT_BAG_REORDER,
                                        DEPOSIT_TICKET_REORDER,
                                        POP_KIT_CODE,
                                        GLOBAL_HIERARCHY_IND,
                                        STD_COST_IDENTIFIER,
	                                    PRIM_COST_IDENTIFIER,
                                        STATUS_CODE,
                                        STATUS_EFFECTIVE_DATE,
                                        STATUS_EXPIRATION_DATE,
                                        TYPE_CODE,
                                        TYPE_EFFECTIVE_DATE,
                                        TYPE_EXPIRATION_DATE,
                                        TERRITORY_SLS_MGR_CODE,
                                        TERRITORY_CATEGORY,
                                        LEASE_CAR_INDICATOR,
                                        TERRITORY_TYPE_BUSN_CODE,
                                        HOME_STORE,
                                        PRI_PHONE_NUMBER_TYPE,
                                        PRI_PHONE_AREA_CODE,
                                        PRI_PHONE_NUMBER,
                                        PRI_PHONE_EXTENSION,
                                        SCD_PHONE_NUMBER_TYPE,
                                        SCD_PHONE_AREA_CODE,
                                        SCD_PHONE_NUMBER,
                                        SCD_PHONE_EXTENSION,
                                        FAX_PHONE_NUMBER_TYPE,
                                        FAX_PHONE_AREA_CODE,
                                        FAX_PHONE_NUMBER,
                                        FAX_PHONE_EXTENSION,
                                        ADMIN_TO_SALES_AREA,
                                        ADMIN_TO_SALES_DISTRICT,
                                        ADMIN_TO_SALES_DIVISION,
                                        ALTERNATE_DAD,
                                        FACTS_DIVISION,
                                        LEGACY_GL_DIVISION,
                                        GLOBAL_HIERARCHY,
                                        MANAGER_ID)
         )
         LOCATION ('COST_CENTER_TERRITORY.csv')
)REJECT LIMIT UNLIMITED;

--COST_CENTER_ADMINISTRATION external table creation
CREATE TABLE "COSTCNTR"."COST_CENTER_ADMINISTRATION" 
   (	"COST_CENTER_CODE" VARCHAR2(6 BYTE), 
	"COST_CENTER_NAME" VARCHAR2(35 BYTE), 
	"CATEGORY" VARCHAR2(1 BYTE), 
	"ENTITY_TYPE" VARCHAR2(2 BYTE), 
	"STATEMENT_TYPE" VARCHAR2(2 BYTE), 
	"COUNTRY_CODE" VARCHAR2(3 BYTE), 
	"TRANSPORT_TYPE" VARCHAR2(5 BYTE), 
	"BEGIN_DATE" VARCHAR2(8 BYTE), 
	"OPEN_DATE" VARCHAR2(8 BYTE), 
	"MOVE_DATE" VARCHAR2(8 BYTE), 
	"CLOSE_DATE" VARCHAR2(8 BYTE), 
	"FINANCIAL_CLOSE_DATE" VARCHAR2(8 BYTE), 
	"POS_PROG_VER_EFF_DATE" VARCHAR2(8 BYTE), 
	"UPS_ZONE_CODE" VARCHAR2(1 BYTE), 
	"RPS_ZONE_CODE" VARCHAR2(1 BYTE), 
	"CURRENCY_CODE" VARCHAR2(3 BYTE), 
	"POS_PROG_VER_NBR" VARCHAR2(5 BYTE), 
	"LEASE_OWN_CODE" VARCHAR2(1 BYTE), 
	"MISSION_TYPE_CODE" VARCHAR2(2 BYTE), 
	"DUNS_NUMBER" VARCHAR2(9 BYTE), 
	"PRI_LOGO_GROUP_IND" VARCHAR2(3 BYTE), 
	"SCD_LOGO_GROUP_IND" VARCHAR2(3 BYTE), 
	"BANKING_TYPE" VARCHAR2(1 BYTE), 
	"DEPOSIT_BAG_REORDER" VARCHAR2(1 BYTE), 
	"DEPOSIT_TICKET_REORDER" VARCHAR2(1 BYTE), 
	"POP_KIT_CODE" VARCHAR2(1 BYTE), 
	"GLOBAL_HIERARCHY_IND" VARCHAR2(1 BYTE), 
	"STD_COST_IDENTIFIER" VARCHAR2(1 BYTE),
	"PRIM_COST_IDENTIFIER" VARCHAR2(1 BYTE),
	"STATUS_CODE" VARCHAR2(1 BYTE), 
	"STATUS_EFFECTIVE_DATE" VARCHAR2(8 BYTE), 
	"STATUS_EXPIRATION_DATE" VARCHAR2(8 BYTE), 
	"TYPE_CODE" VARCHAR2(2 BYTE), 
	"TYPE_EFFECTIVE_DATE" VARCHAR2(8 BYTE), 
	"TYPE_EXPIRATION_DATE" VARCHAR2(8 BYTE), 
	"ADMINISTRATION_CATEGORY" VARCHAR2(1 BYTE), 
	"INTERNAL_MAIL_NUMBER" VARCHAR2(3 BYTE), 
	"ADMIN_COST_CNTR_TYPE" VARCHAR2(5 BYTE), 
	"USA_ADDRESS_TYPE" VARCHAR2(2 BYTE),
	"USA_EFFECTIVE_DATE" VARCHAR2(8 BYTE),
	"USA_EXPIRATION_DATE" VARCHAR2(8 BYTE),
	"USA_ADDRESS_LINE_1" VARCHAR2(35 BYTE),
	"USA_ADDRESS_LINE_2" VARCHAR2(35 BYTE),
	"USA_ADDRESS_LINE_3" VARCHAR2(35 BYTE),
	"USA_CITY" VARCHAR2(25 BYTE),
	"USA_STATE_CODE" VARCHAR2(2 BYTE),
	"USA_ZIP_CODE" VARCHAR2(5 BYTE),
	"USA_ZIP_CODE_4" VARCHAR2(4 BYTE),
	"USA_COUNTY" VARCHAR2(30 BYTE),
	"USA_FIPS_CODE" VARCHAR2(10 BYTE),
	"USA_DESTINATION_POINT" VARCHAR2(2 BYTE),
	"USA_CHECK_DIGIT" VARCHAR2(1 BYTE),
	"USA_VALID_ADDRESS" VARCHAR2(1 BYTE),
	"USA_COUNTRY_CODE" VARCHAR2(3 BYTE),
	"CAN_ADDRESS_TYPE" VARCHAR2(2 BYTE),
	"CAN_EFFECTIVE_DATE" VARCHAR2(8 BYTE),
	"CAN_EXPIRATION_DATE" VARCHAR2(8 BYTE),
	"CAN_ADDRESS_LINE_1" VARCHAR2(35 BYTE),
	"CAN_ADDRESS_LINE_2" VARCHAR2(35 BYTE),
	"CAN_ADDRESS_LINE_3" VARCHAR2(35 BYTE),
	"CAN_CITY" VARCHAR2(25 BYTE),
	"CAN_PROVINCE_CODE" VARCHAR2(2 BYTE),
	"CAN_POSTAL_CODE" VARCHAR2(6 BYTE),
	"CAN_VALID_ADDRESS" VARCHAR2(1 BYTE),
	"CAN_COUNTRY_CODE" VARCHAR2(3 BYTE), 
	"MEX_ADDRESS_TYPE" VARCHAR2(2 BYTE),
	"MEX_EFFECTIVE_DATE" VARCHAR2(8 BYTE),
	"MEX_EXPIRATION_DATE" VARCHAR2(8 BYTE),
	"MEX_ADDRESS_LINE_1" VARCHAR2(35 BYTE),
	"MEX_ADDRESS_LINE_2" VARCHAR2(35 BYTE),
	"MEX_ADDRESS_LINE_3" VARCHAR2(35 BYTE),
	"MEX_CITY" VARCHAR2(25 BYTE),
	"MEX_PROVINCE_CODE" VARCHAR2(5 BYTE),
	"MEX_POSTAL_CODE" VARCHAR2(5 BYTE),
	"MEX_VALID_ADDRESS" VARCHAR2(1 BYTE),
	"MEX_COUNTRY_CODE" VARCHAR2(3 BYTE),
	"OTHER_ADDRESS_TYPE" VARCHAR2(2 BYTE),
	"OTHER_EFFECTIVE_DATE" VARCHAR2(8 BYTE),
	"OTHER_EXPIRATION_DATE" VARCHAR2(8 BYTE),
	"OTHER_ADDRESS_LINE_1" VARCHAR2(35 BYTE),
	"OTHER_ADDRESS_LINE_2" VARCHAR2(35 BYTE),
	"OTHER_ADDRESS_LINE_3" VARCHAR2(35 BYTE),
	"OTHER_CITY" VARCHAR2(25 BYTE),
	"OTHER_PROVINCE_CODE" VARCHAR2(25 BYTE),
	"OTHER_STATE_CODE" VARCHAR2(25 BYTE),
	"OTHER_POSTAL_CODE" VARCHAR2(10 BYTE),
	"OTHER_VALID_ADDRESS" VARCHAR2(1 BYTE),
	"OTHER_COUNTRY_CODE" VARCHAR2(3 BYTE),
	"PRI_PHONE_NUMBER_TYPE" VARCHAR2(5 BYTE), 
	"PRI_PHONE_AREA_CODE" VARCHAR2(4 BYTE), 
	"PRI_PHONE_NUMBER" VARCHAR2(7 BYTE), 
	"PRI_PHONE_EXTENSION" VARCHAR2(6 BYTE), 
	"SCD_PHONE_NUMBER_TYPE" VARCHAR2(5 BYTE), 
	"SCD_PHONE_AREA_CODE" VARCHAR2(4 BYTE), 
	"SCD_PHONE_NUMBER" VARCHAR2(7 BYTE), 
	"SCD_PHONE_EXTENSION" VARCHAR2(6 BYTE), 
	"FAX_PHONE_NUMBER_TYPE" VARCHAR2(5 BYTE), 
	"FAX_PHONE_AREA_CODE" VARCHAR2(4 BYTE), 
	"FAX_PHONE_NUMBER" VARCHAR2(7 BYTE), 
	"FAX_PHONE_EXTENSION" VARCHAR2(6 BYTE),
	"ADMIN_TO_SALES_AREA" VARCHAR2(100 BYTE),
	"ADMIN_TO_SALES_DISTRICT" VARCHAR2(100 BYTE),
	"ADMIN_TO_SALES_DIVISION" VARCHAR2(100 BYTE),
	"ALTERNATE_DAD" VARCHAR2(100 BYTE),
	"FACTS_DIVISION" VARCHAR2(100 BYTE),
	"LEGACY_GL_DIVISION" VARCHAR2(100 BYTE),
	"GLOBAL_HIERARCHY" VARCHAR2(100 BYTE),
	"MANAGER_ID" VARCHAR2(20 BYTE)
) 
ORGANIZATION EXTERNAL(
         TYPE ORACLE_LOADER
         DEFAULT DIRECTORY "CCN_LOAD_FILES"
         ACCESS PARAMETERS
         (RECORDS DELIMITED BY NEWLINE SKIP 1
          badfile "CCN_LOAD_FILES":'COST_CENTER_ADMINISTRATION.bad'
          logfile "CCN_LOAD_FILES":'COST_CENTER_ADMINISTRATION.log'
          FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' LDRTRIM
          MISSING FIELD VALUES ARE NULL(COST_CENTER_CODE,
                                        COST_CENTER_NAME,
                                        CATEGORY,
                                        ENTITY_TYPE,
                                        STATEMENT_TYPE,
                                        COUNTRY_CODE,
                                        TRANSPORT_TYPE,
                                        BEGIN_DATE,
                                        OPEN_DATE,
                                        MOVE_DATE,
                                        CLOSE_DATE,
                                        FINANCIAL_CLOSE_DATE,
                                        POS_PROG_VER_EFF_DATE,
                                        UPS_ZONE_CODE,
                                        RPS_ZONE_CODE,
                                        CURRENCY_CODE,
                                        POS_PROG_VER_NBR,
                                        LEASE_OWN_CODE,
                                        MISSION_TYPE_CODE,
                                        DUNS_NUMBER,
                                        PRI_LOGO_GROUP_IND,
                                        SCD_LOGO_GROUP_IND,
                                        BANKING_TYPE,
                                        DEPOSIT_BAG_REORDER,
                                        DEPOSIT_TICKET_REORDER,
                                        POP_KIT_CODE,
                                        GLOBAL_HIERARCHY_IND,
                                        STD_COST_IDENTIFIER,
	                                    PRIM_COST_IDENTIFIER,
                                        STATUS_CODE,
                                        STATUS_EFFECTIVE_DATE,
                                        STATUS_EXPIRATION_DATE,
                                        TYPE_CODE,
                                        TYPE_EFFECTIVE_DATE,
                                        TYPE_EXPIRATION_DATE,
                                        ADMINISTRATION_CATEGORY,
                                        INTERNAL_MAIL_NUMBER,
                                        ADMIN_COST_CNTR_TYPE,
                                        USA_ADDRESS_TYPE,
                                        USA_EFFECTIVE_DATE,
                                        USA_EXPIRATION_DATE,
                                        USA_ADDRESS_LINE_1,
                                        USA_ADDRESS_LINE_2,
                                        USA_ADDRESS_LINE_3,
                                        USA_CITY,
                                        USA_STATE_CODE,
                                        USA_ZIP_CODE,
                                        USA_ZIP_CODE_4,
                                        USA_COUNTY,
                                        USA_FIPS_CODE,
                                        USA_DESTINATION_POINT,
                                        USA_CHECK_DIGIT,
                                        USA_VALID_ADDRESS,
                                        USA_COUNTRY_CODE,
                                        CAN_ADDRESS_TYPE,
                                        CAN_EFFECTIVE_DATE,
                                        CAN_EXPIRATION_DATE,
                                        CAN_ADDRESS_LINE_1,
                                        CAN_ADDRESS_LINE_2,
                                        CAN_ADDRESS_LINE_3,
                                        CAN_CITY,
                                        CAN_PROVINCE_CODE,
                                        CAN_POSTAL_CODE,
                                        CAN_VALID_ADDRESS,
                                        CAN_COUNTRY_CODE, 
                                        MEX_ADDRESS_TYPE,
                                        MEX_EFFECTIVE_DATE,
                                        MEX_EXPIRATION_DATE,
                                        MEX_ADDRESS_LINE_1,
                                        MEX_ADDRESS_LINE_2,
                                        MEX_ADDRESS_LINE_3,
                                        MEX_CITY,
                                        MEX_PROVINCE_CODE,
                                        MEX_POSTAL_CODE,
                                        MEX_VALID_ADDRESS,
                                        MEX_COUNTRY_CODE,
                                        OTHER_ADDRESS_TYPE,
                                        OTHER_EFFECTIVE_DATE,
                                        OTHER_EXPIRATION_DATE,
                                        OTHER_ADDRESS_LINE_1,
                                        OTHER_ADDRESS_LINE_2,
                                        OTHER_ADDRESS_LINE_3,
                                        OTHER_CITY,
                                        OTHER_PROVINCE_CODE,
                                        OTHER_STATE_CODE,
                                        OTHER_POSTAL_CODE,
                                        OTHER_VALID_ADDRESS,
                                        OTHER_COUNTRY_CODE,
                                        PRI_PHONE_NUMBER_TYPE,
                                        PRI_PHONE_AREA_CODE,
                                        PRI_PHONE_NUMBER,
                                        PRI_PHONE_EXTENSION,
                                        SCD_PHONE_NUMBER_TYPE,
                                        SCD_PHONE_AREA_CODE,
                                        SCD_PHONE_NUMBER,
                                        SCD_PHONE_EXTENSION,
                                        FAX_PHONE_NUMBER_TYPE,
                                        FAX_PHONE_AREA_CODE,
                                        FAX_PHONE_NUMBER,
                                        FAX_PHONE_EXTENSION,
                                        ADMIN_TO_SALES_AREA,
                                        ADMIN_TO_SALES_DISTRICT,
                                        ADMIN_TO_SALES_DIVISION,
                                        ALTERNATE_DAD,
                                        FACTS_DIVISION,
                                        LEGACY_GL_DIVISION,
                                        GLOBAL_HIERARCHY,
                                        MANAGER_ID)
         )
         LOCATION ('COST_CENTER_ADMINISTRATION.csv')
)REJECT LIMIT UNLIMITED;

--COST_CENTER_REAL_ESTATE external table creation
CREATE TABLE "COSTCNTR"."COST_CENTER_REAL_ESTATE" 
   (	"COST_CENTER_CODE" VARCHAR2(6 BYTE), 
	"COST_CENTER_NAME" VARCHAR2(35 BYTE), 
	"CATEGORY" VARCHAR2(1 BYTE), 
	"ENTITY_TYPE" VARCHAR2(2 BYTE), 
	"STATEMENT_TYPE" VARCHAR2(2 BYTE), 
	"COUNTRY_CODE" VARCHAR2(3 BYTE), 
	"TRANSPORT_TYPE" VARCHAR2(5 BYTE), 
	"BEGIN_DATE" VARCHAR2(8 BYTE), 
	"OPEN_DATE" VARCHAR2(8 BYTE), 
	"MOVE_DATE" VARCHAR2(8 BYTE), 
	"CLOSE_DATE" VARCHAR2(8 BYTE), 
	"FINANCIAL_CLOSE_DATE" VARCHAR2(8 BYTE), 
	"POS_PROG_VER_EFF_DATE" VARCHAR2(8 BYTE), 
	"UPS_ZONE_CODE" VARCHAR2(1 BYTE), 
	"RPS_ZONE_CODE" VARCHAR2(1 BYTE), 
	"CURRENCY_CODE" VARCHAR2(3 BYTE), 
	"POS_PROG_VER_NBR" VARCHAR2(5 BYTE), 
	"LEASE_OWN_CODE" VARCHAR2(1 BYTE), 
	"MISSION_TYPE_CODE" VARCHAR2(2 BYTE), 
	"DUNS_NUMBER" VARCHAR2(9 BYTE), 
	"PRI_LOGO_GROUP_IND" VARCHAR2(3 BYTE), 
	"SCD_LOGO_GROUP_IND" VARCHAR2(3 BYTE), 
	"BANKING_TYPE" VARCHAR2(1 BYTE), 
	"DEPOSIT_BAG_REORDER" VARCHAR2(1 BYTE), 
	"DEPOSIT_TICKET_REORDER" VARCHAR2(1 BYTE), 
	"POP_KIT_CODE" VARCHAR2(1 BYTE), 
	"GLOBAL_HIERARCHY_IND" VARCHAR2(1 BYTE), 
	"STD_COST_IDENTIFIER" VARCHAR2(1 BYTE),
	"PRIM_COST_IDENTIFIER" VARCHAR2(1 BYTE),
	"STATUS_CODE" VARCHAR2(1 BYTE), 
	"STATUS_EFFECTIVE_DATE" VARCHAR2(8 BYTE), 
	"STATUS_EXPIRATION_DATE" VARCHAR2(8 BYTE), 
	"TYPE_CODE" VARCHAR2(2 BYTE), 
	"TYPE_EFFECTIVE_DATE" VARCHAR2(8 BYTE), 
	"TYPE_EXPIRATION_DATE" VARCHAR2(8 BYTE), 
	"REAL_ESTATE_CATEGORY" VARCHAR2(1 BYTE), 
	"USA_ADDRESS_TYPE" VARCHAR2(2 BYTE),
	"USA_EFFECTIVE_DATE" VARCHAR2(8 BYTE),
	"USA_EXPIRATION_DATE" VARCHAR2(8 BYTE),
	"USA_ADDRESS_LINE_1" VARCHAR2(35 BYTE),
	"USA_ADDRESS_LINE_2" VARCHAR2(35 BYTE),
	"USA_ADDRESS_LINE_3" VARCHAR2(35 BYTE),
	"USA_CITY" VARCHAR2(25 BYTE),
	"USA_STATE_CODE" VARCHAR2(2 BYTE),
	"USA_ZIP_CODE" VARCHAR2(5 BYTE),
	"USA_ZIP_CODE_4" VARCHAR2(4 BYTE),
	"USA_COUNTY" VARCHAR2(30 BYTE),
	"USA_FIPS_CODE" VARCHAR2(10 BYTE),
	"USA_DESTINATION_POINT" VARCHAR2(2 BYTE),
	"USA_CHECK_DIGIT" VARCHAR2(1 BYTE),
	"USA_VALID_ADDRESS" VARCHAR2(1 BYTE),
	"USA_COUNTRY_CODE" VARCHAR2(3 BYTE),
	"CAN_ADDRESS_TYPE" VARCHAR2(2 BYTE),
	"CAN_EFFECTIVE_DATE" VARCHAR2(8 BYTE),
	"CAN_EXPIRATION_DATE" VARCHAR2(8 BYTE),
	"CAN_ADDRESS_LINE_1" VARCHAR2(35 BYTE),
	"CAN_ADDRESS_LINE_2" VARCHAR2(35 BYTE),
	"CAN_ADDRESS_LINE_3" VARCHAR2(35 BYTE),
	"CAN_CITY" VARCHAR2(25 BYTE),
	"CAN_PROVINCE_CODE" VARCHAR2(2 BYTE),
	"CAN_POSTAL_CODE" VARCHAR2(6 BYTE),
	"CAN_VALID_ADDRESS" VARCHAR2(1 BYTE),
	"CAN_COUNTRY_CODE" VARCHAR2(3 BYTE), 
	"MEX_ADDRESS_TYPE" VARCHAR2(2 BYTE),
	"MEX_EFFECTIVE_DATE" VARCHAR2(8 BYTE),
	"MEX_EXPIRATION_DATE" VARCHAR2(8 BYTE),
	"MEX_ADDRESS_LINE_1" VARCHAR2(35 BYTE),
	"MEX_ADDRESS_LINE_2" VARCHAR2(35 BYTE),
	"MEX_ADDRESS_LINE_3" VARCHAR2(35 BYTE),
	"MEX_CITY" VARCHAR2(25 BYTE),
	"MEX_PROVINCE_CODE" VARCHAR2(5 BYTE),
	"MEX_POSTAL_CODE" VARCHAR2(5 BYTE),
	"MEX_VALID_ADDRESS" VARCHAR2(1 BYTE),
	"MEX_COUNTRY_CODE" VARCHAR2(3 BYTE),
	"OTHER_ADDRESS_TYPE" VARCHAR2(2 BYTE),
	"OTHER_EFFECTIVE_DATE" VARCHAR2(8 BYTE),
	"OTHER_EXPIRATION_DATE" VARCHAR2(8 BYTE),
	"OTHER_ADDRESS_LINE_1" VARCHAR2(35 BYTE),
	"OTHER_ADDRESS_LINE_2" VARCHAR2(35 BYTE),
	"OTHER_ADDRESS_LINE_3" VARCHAR2(35 BYTE),
	"OTHER_CITY" VARCHAR2(25 BYTE),
	"OTHER_PROVINCE_CODE" VARCHAR2(25 BYTE),
	"OTHER_STATE_CODE" VARCHAR2(25 BYTE),
	"OTHER_POSTAL_CODE" VARCHAR2(10 BYTE),
	"OTHER_VALID_ADDRESS" VARCHAR2(1 BYTE),
	"OTHER_COUNTRY_CODE" VARCHAR2(3 BYTE),
	"PRI_PHONE_NUMBER_TYPE" VARCHAR2(5 BYTE), 
	"PRI_PHONE_AREA_CODE" VARCHAR2(4 BYTE), 
	"PRI_PHONE_NUMBER" VARCHAR2(7 BYTE), 
	"PRI_PHONE_EXTENSION" VARCHAR2(6 BYTE), 
	"SCD_PHONE_NUMBER_TYPE" VARCHAR2(5 BYTE), 
	"SCD_PHONE_AREA_CODE" VARCHAR2(4 BYTE), 
	"SCD_PHONE_NUMBER" VARCHAR2(7 BYTE), 
	"SCD_PHONE_EXTENSION" VARCHAR2(6 BYTE), 
	"FAX_PHONE_NUMBER_TYPE" VARCHAR2(5 BYTE), 
	"FAX_PHONE_AREA_CODE" VARCHAR2(4 BYTE), 
	"FAX_PHONE_NUMBER" VARCHAR2(7 BYTE), 
	"FAX_PHONE_EXTENSION" VARCHAR2(6 BYTE),
	"ADMIN_TO_SALES_AREA" VARCHAR2(100 BYTE),
	"ADMIN_TO_SALES_DISTRICT" VARCHAR2(100 BYTE),
	"ADMIN_TO_SALES_DIVISION" VARCHAR2(100 BYTE),
	"ALTERNATE_DAD" VARCHAR2(100 BYTE),
	"FACTS_DIVISION" VARCHAR2(100 BYTE),
	"LEGACY_GL_DIVISION" VARCHAR2(100 BYTE),
	"GLOBAL_HIERARCHY" VARCHAR2(100 BYTE),
	"MANAGER_ID" VARCHAR2(20 BYTE)
) 
ORGANIZATION EXTERNAL(
         TYPE ORACLE_LOADER
         DEFAULT DIRECTORY "CCN_LOAD_FILES"
         ACCESS PARAMETERS
         (RECORDS DELIMITED BY NEWLINE SKIP 1
          badfile "CCN_LOAD_FILES":'COST_CENTER_REAL_ESTATE.bad'
          logfile "CCN_LOAD_FILES":'COST_CENTER_REAL_ESTATE.log'
          FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' LDRTRIM
          MISSING FIELD VALUES ARE NULL(COST_CENTER_CODE,
                                        COST_CENTER_NAME,
                                        CATEGORY,
                                        ENTITY_TYPE,
                                        STATEMENT_TYPE,
                                        COUNTRY_CODE,
                                        TRANSPORT_TYPE,
                                        BEGIN_DATE,
                                        OPEN_DATE,
                                        MOVE_DATE,
                                        CLOSE_DATE,
                                        FINANCIAL_CLOSE_DATE,
                                        POS_PROG_VER_EFF_DATE,
                                        UPS_ZONE_CODE,
                                        RPS_ZONE_CODE,
                                        CURRENCY_CODE,
                                        POS_PROG_VER_NBR,
                                        LEASE_OWN_CODE,
                                        MISSION_TYPE_CODE,
                                        DUNS_NUMBER,
                                        PRI_LOGO_GROUP_IND,
                                        SCD_LOGO_GROUP_IND,
                                        BANKING_TYPE,
                                        DEPOSIT_BAG_REORDER,
                                        DEPOSIT_TICKET_REORDER,
                                        POP_KIT_CODE,
                                        GLOBAL_HIERARCHY_IND,
                                        STD_COST_IDENTIFIER,
	                                    PRIM_COST_IDENTIFIER,
                                        STATUS_CODE,
                                        STATUS_EFFECTIVE_DATE,
                                        STATUS_EXPIRATION_DATE,
                                        TYPE_CODE,
                                        TYPE_EFFECTIVE_DATE,
                                        TYPE_EXPIRATION_DATE,
                                        REAL_ESTATE_CATEGORY,
                                        USA_ADDRESS_TYPE,
                                        USA_EFFECTIVE_DATE,
                                        USA_EXPIRATION_DATE,
                                        USA_ADDRESS_LINE_1,
                                        USA_ADDRESS_LINE_2,
                                        USA_ADDRESS_LINE_3,
                                        USA_CITY,
                                        USA_STATE_CODE,
                                        USA_ZIP_CODE,
                                        USA_ZIP_CODE_4,
                                        USA_COUNTY,
                                        USA_FIPS_CODE,
                                        USA_DESTINATION_POINT,
                                        USA_CHECK_DIGIT,
                                        USA_VALID_ADDRESS,
                                        USA_COUNTRY_CODE,
                                        CAN_ADDRESS_TYPE,
                                        CAN_EFFECTIVE_DATE,
                                        CAN_EXPIRATION_DATE,
                                        CAN_ADDRESS_LINE_1,
                                        CAN_ADDRESS_LINE_2,
                                        CAN_ADDRESS_LINE_3,
                                        CAN_CITY,
                                        CAN_PROVINCE_CODE,
                                        CAN_POSTAL_CODE,
                                        CAN_VALID_ADDRESS,
                                        CAN_COUNTRY_CODE, 
                                        MEX_ADDRESS_TYPE,
                                        MEX_EFFECTIVE_DATE,
                                        MEX_EXPIRATION_DATE,
                                        MEX_ADDRESS_LINE_1,
                                        MEX_ADDRESS_LINE_2,
                                        MEX_ADDRESS_LINE_3,
                                        MEX_CITY,
                                        MEX_PROVINCE_CODE,
                                        MEX_POSTAL_CODE,
                                        MEX_VALID_ADDRESS,
                                        MEX_COUNTRY_CODE,
                                        OTHER_ADDRESS_TYPE,
                                        OTHER_EFFECTIVE_DATE,
                                        OTHER_EXPIRATION_DATE,
                                        OTHER_ADDRESS_LINE_1,
                                        OTHER_ADDRESS_LINE_2,
                                        OTHER_ADDRESS_LINE_3,
                                        OTHER_CITY,
                                        OTHER_PROVINCE_CODE,
                                        OTHER_STATE_CODE,
                                        OTHER_POSTAL_CODE,
                                        OTHER_VALID_ADDRESS,
                                        OTHER_COUNTRY_CODE,
                                        PRI_PHONE_NUMBER_TYPE,
                                        PRI_PHONE_AREA_CODE,
                                        PRI_PHONE_NUMBER,
                                        PRI_PHONE_EXTENSION,
                                        SCD_PHONE_NUMBER_TYPE,
                                        SCD_PHONE_AREA_CODE,
                                        SCD_PHONE_NUMBER,
                                        SCD_PHONE_EXTENSION,
                                        FAX_PHONE_NUMBER_TYPE,
                                        FAX_PHONE_AREA_CODE,
                                        FAX_PHONE_NUMBER,
                                        FAX_PHONE_EXTENSION,
                                        ADMIN_TO_SALES_AREA,
                                        ADMIN_TO_SALES_DISTRICT,
                                        ADMIN_TO_SALES_DIVISION,
                                        ALTERNATE_DAD,
                                        FACTS_DIVISION,
                                        LEGACY_GL_DIVISION,
                                        GLOBAL_HIERARCHY,
                                        MANAGER_ID)
         )
         LOCATION ('COST_CENTER_REAL_ESTATE.csv')
)REJECT LIMIT UNLIMITED;

--COST_CENTER_OTHER external table creation
CREATE TABLE "COSTCNTR"."COST_CENTER_OTHER" 
   (	"COST_CENTER_CODE" VARCHAR2(6 BYTE), 
	"COST_CENTER_NAME" VARCHAR2(35 BYTE), 
	"CATEGORY" VARCHAR2(1 BYTE), 
	"ENTITY_TYPE" VARCHAR2(2 BYTE), 
	"STATEMENT_TYPE" VARCHAR2(2 BYTE), 
	"COUNTRY_CODE" VARCHAR2(3 BYTE), 
	"TRANSPORT_TYPE" VARCHAR2(5 BYTE), 
	"BEGIN_DATE" VARCHAR2(8 BYTE), 
	"OPEN_DATE" VARCHAR2(8 BYTE), 
	"MOVE_DATE" VARCHAR2(8 BYTE), 
	"CLOSE_DATE" VARCHAR2(8 BYTE), 
	"FINANCIAL_CLOSE_DATE" VARCHAR2(8 BYTE), 
	"POS_PROG_VER_EFF_DATE" VARCHAR2(8 BYTE), 
	"UPS_ZONE_CODE" VARCHAR2(1 BYTE), 
	"RPS_ZONE_CODE" VARCHAR2(1 BYTE), 
	"CURRENCY_CODE" VARCHAR2(3 BYTE), 
	"POS_PROG_VER_NBR" VARCHAR2(5 BYTE), 
	"LEASE_OWN_CODE" VARCHAR2(1 BYTE), 
	"MISSION_TYPE_CODE" VARCHAR2(2 BYTE), 
	"DUNS_NUMBER" VARCHAR2(9 BYTE), 
	"PRI_LOGO_GROUP_IND" VARCHAR2(3 BYTE), 
	"SCD_LOGO_GROUP_IND" VARCHAR2(3 BYTE), 
	"BANKING_TYPE" VARCHAR2(1 BYTE), 
	"DEPOSIT_BAG_REORDER" VARCHAR2(1 BYTE), 
	"DEPOSIT_TICKET_REORDER" VARCHAR2(1 BYTE), 
	"POP_KIT_CODE" VARCHAR2(1 BYTE), 
	"GLOBAL_HIERARCHY_IND" VARCHAR2(1 BYTE), 
	"STD_COST_IDENTIFIER" VARCHAR2(1 BYTE),
	"PRIM_COST_IDENTIFIER" VARCHAR2(1 BYTE),
	"STATUS_CODE" VARCHAR2(1 BYTE), 
	"STATUS_EFFECTIVE_DATE" VARCHAR2(8 BYTE), 
	"STATUS_EXPIRATION_DATE" VARCHAR2(8 BYTE), 
	"TYPE_CODE" VARCHAR2(2 BYTE), 
	"TYPE_EFFECTIVE_DATE" VARCHAR2(8 BYTE), 
	"TYPE_EXPIRATION_DATE" VARCHAR2(8 BYTE), 
	"OTHER_CATEGORY" VARCHAR2(1 BYTE), 
	"USA_ADDRESS_TYPE" VARCHAR2(2 BYTE),
	"USA_EFFECTIVE_DATE" VARCHAR2(8 BYTE),
	"USA_EXPIRATION_DATE" VARCHAR2(8 BYTE),
	"USA_ADDRESS_LINE_1" VARCHAR2(35 BYTE),
	"USA_ADDRESS_LINE_2" VARCHAR2(35 BYTE),
	"USA_ADDRESS_LINE_3" VARCHAR2(35 BYTE),
	"USA_CITY" VARCHAR2(25 BYTE),
	"USA_STATE_CODE" VARCHAR2(2 BYTE),
	"USA_ZIP_CODE" VARCHAR2(5 BYTE),
	"USA_ZIP_CODE_4" VARCHAR2(4 BYTE),
	"USA_COUNTY" VARCHAR2(30 BYTE),
	"USA_FIPS_CODE" VARCHAR2(10 BYTE),
	"USA_DESTINATION_POINT" VARCHAR2(2 BYTE),
	"USA_CHECK_DIGIT" VARCHAR2(1 BYTE),
	"USA_VALID_ADDRESS" VARCHAR2(1 BYTE),
	"USA_COUNTRY_CODE" VARCHAR2(3 BYTE),
	"CAN_ADDRESS_TYPE" VARCHAR2(2 BYTE),
	"CAN_EFFECTIVE_DATE" VARCHAR2(8 BYTE),
	"CAN_EXPIRATION_DATE" VARCHAR2(8 BYTE),
	"CAN_ADDRESS_LINE_1" VARCHAR2(35 BYTE),
	"CAN_ADDRESS_LINE_2" VARCHAR2(35 BYTE),
	"CAN_ADDRESS_LINE_3" VARCHAR2(35 BYTE),
	"CAN_CITY" VARCHAR2(25 BYTE),
	"CAN_PROVINCE_CODE" VARCHAR2(2 BYTE),
	"CAN_POSTAL_CODE" VARCHAR2(6 BYTE),
	"CAN_VALID_ADDRESS" VARCHAR2(1 BYTE),
	"CAN_COUNTRY_CODE" VARCHAR2(3 BYTE), 
	"MEX_ADDRESS_TYPE" VARCHAR2(2 BYTE),
	"MEX_EFFECTIVE_DATE" VARCHAR2(8 BYTE),
	"MEX_EXPIRATION_DATE" VARCHAR2(8 BYTE),
	"MEX_ADDRESS_LINE_1" VARCHAR2(35 BYTE),
	"MEX_ADDRESS_LINE_2" VARCHAR2(35 BYTE),
	"MEX_ADDRESS_LINE_3" VARCHAR2(35 BYTE),
	"MEX_CITY" VARCHAR2(25 BYTE),
	"MEX_PROVINCE_CODE" VARCHAR2(5 BYTE),
	"MEX_POSTAL_CODE" VARCHAR2(5 BYTE),
	"MEX_VALID_ADDRESS" VARCHAR2(1 BYTE),
	"MEX_COUNTRY_CODE" VARCHAR2(3 BYTE),
	"OTHER_ADDRESS_TYPE" VARCHAR2(2 BYTE),
	"OTHER_EFFECTIVE_DATE" VARCHAR2(8 BYTE),
	"OTHER_EXPIRATION_DATE" VARCHAR2(8 BYTE),
	"OTHER_ADDRESS_LINE_1" VARCHAR2(35 BYTE),
	"OTHER_ADDRESS_LINE_2" VARCHAR2(35 BYTE),
	"OTHER_ADDRESS_LINE_3" VARCHAR2(35 BYTE),
	"OTHER_CITY" VARCHAR2(25 BYTE),
	"OTHER_PROVINCE_CODE" VARCHAR2(25 BYTE),
	"OTHER_STATE_CODE" VARCHAR2(25 BYTE),
	"OTHER_POSTAL_CODE" VARCHAR2(10 BYTE),
	"OTHER_VALID_ADDRESS" VARCHAR2(1 BYTE),
	"OTHER_COUNTRY_CODE" VARCHAR2(3 BYTE),
	"PRI_PHONE_NUMBER_TYPE" VARCHAR2(5 BYTE), 
	"PRI_PHONE_AREA_CODE" VARCHAR2(4 BYTE), 
	"PRI_PHONE_NUMBER" VARCHAR2(7 BYTE), 
	"PRI_PHONE_EXTENSION" VARCHAR2(6 BYTE), 
	"SCD_PHONE_NUMBER_TYPE" VARCHAR2(5 BYTE), 
	"SCD_PHONE_AREA_CODE" VARCHAR2(4 BYTE), 
	"SCD_PHONE_NUMBER" VARCHAR2(7 BYTE), 
	"SCD_PHONE_EXTENSION" VARCHAR2(6 BYTE), 
	"FAX_PHONE_NUMBER_TYPE" VARCHAR2(5 BYTE), 
	"FAX_PHONE_AREA_CODE" VARCHAR2(4 BYTE), 
	"FAX_PHONE_NUMBER" VARCHAR2(7 BYTE), 
	"FAX_PHONE_EXTENSION" VARCHAR2(6 BYTE),
	"ADMIN_TO_SALES_AREA" VARCHAR2(100 BYTE),
	"ADMIN_TO_SALES_DISTRICT" VARCHAR2(100 BYTE),
	"ADMIN_TO_SALES_DIVISION" VARCHAR2(100 BYTE),
	"ALTERNATE_DAD" VARCHAR2(100 BYTE),
	"FACTS_DIVISION" VARCHAR2(100 BYTE),
	"LEGACY_GL_DIVISION" VARCHAR2(100 BYTE),
	"GLOBAL_HIERARCHY" VARCHAR2(100 BYTE),
	"MANAGER_ID" VARCHAR2(20 BYTE)
) 
ORGANIZATION EXTERNAL(
         TYPE ORACLE_LOADER
         DEFAULT DIRECTORY "CCN_LOAD_FILES"
         ACCESS PARAMETERS
         (RECORDS DELIMITED BY NEWLINE SKIP 1
          badfile "CCN_LOAD_FILES":'COST_CENTER_OTHER.bad'
          logfile "CCN_LOAD_FILES":'COST_CENTER_OTHER.log'
          FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' LDRTRIM
          MISSING FIELD VALUES ARE NULL(COST_CENTER_CODE,
                                        COST_CENTER_NAME,
                                        CATEGORY,
                                        ENTITY_TYPE,
                                        STATEMENT_TYPE,
                                        COUNTRY_CODE,
                                        TRANSPORT_TYPE,
                                        BEGIN_DATE,
                                        OPEN_DATE,
                                        MOVE_DATE,
                                        CLOSE_DATE,
                                        FINANCIAL_CLOSE_DATE,
                                        POS_PROG_VER_EFF_DATE,
                                        UPS_ZONE_CODE,
                                        RPS_ZONE_CODE,
                                        CURRENCY_CODE,
                                        POS_PROG_VER_NBR,
                                        LEASE_OWN_CODE,
                                        MISSION_TYPE_CODE,
                                        DUNS_NUMBER,
                                        PRI_LOGO_GROUP_IND,
                                        SCD_LOGO_GROUP_IND,
                                        BANKING_TYPE,
                                        DEPOSIT_BAG_REORDER,
                                        DEPOSIT_TICKET_REORDER,
                                        POP_KIT_CODE,
                                        GLOBAL_HIERARCHY_IND,
                                        STD_COST_IDENTIFIER,
                                        PRIM_COST_IDENTIFIER,
                                        STATUS_CODE,
                                        STATUS_EFFECTIVE_DATE,
                                        STATUS_EXPIRATION_DATE,
                                        TYPE_CODE,
                                        TYPE_EFFECTIVE_DATE,
                                        TYPE_EXPIRATION_DATE,
                                        OTHER_CATEGORY,
                                        USA_ADDRESS_TYPE,
                                        USA_EFFECTIVE_DATE,
                                        USA_EXPIRATION_DATE,
                                        USA_ADDRESS_LINE_1,
                                        USA_ADDRESS_LINE_2,
                                        USA_ADDRESS_LINE_3,
                                        USA_CITY,
                                        USA_STATE_CODE,
                                        USA_ZIP_CODE,
                                        USA_ZIP_CODE_4,
                                        USA_COUNTY,
                                        USA_FIPS_CODE,
                                        USA_DESTINATION_POINT,
                                        USA_CHECK_DIGIT,
                                        USA_VALID_ADDRESS,
                                        USA_COUNTRY_CODE,
                                        CAN_ADDRESS_TYPE,
                                        CAN_EFFECTIVE_DATE,
                                        CAN_EXPIRATION_DATE,
                                        CAN_ADDRESS_LINE_1,
                                        CAN_ADDRESS_LINE_2,
                                        CAN_ADDRESS_LINE_3,
                                        CAN_CITY,
                                        CAN_PROVINCE_CODE,
                                        CAN_POSTAL_CODE,
                                        CAN_VALID_ADDRESS,
                                        CAN_COUNTRY_CODE, 
                                        MEX_ADDRESS_TYPE,
                                        MEX_EFFECTIVE_DATE,
                                        MEX_EXPIRATION_DATE,
                                        MEX_ADDRESS_LINE_1,
                                        MEX_ADDRESS_LINE_2,
                                        MEX_ADDRESS_LINE_3,
                                        MEX_CITY,
                                        MEX_PROVINCE_CODE,
                                        MEX_POSTAL_CODE,
                                        MEX_VALID_ADDRESS,
                                        MEX_COUNTRY_CODE,
                                        OTHER_ADDRESS_TYPE,
                                        OTHER_EFFECTIVE_DATE,
                                        OTHER_EXPIRATION_DATE,
                                        OTHER_ADDRESS_LINE_1,
                                        OTHER_ADDRESS_LINE_2,
                                        OTHER_ADDRESS_LINE_3,
                                        OTHER_CITY,
                                        OTHER_PROVINCE_CODE,
                                        OTHER_STATE_CODE,
                                        OTHER_POSTAL_CODE,
                                        OTHER_VALID_ADDRESS,
                                        OTHER_COUNTRY_CODE,
                                        PRI_PHONE_NUMBER_TYPE,
                                        PRI_PHONE_AREA_CODE,
                                        PRI_PHONE_NUMBER,
                                        PRI_PHONE_EXTENSION,
                                        SCD_PHONE_NUMBER_TYPE,
                                        SCD_PHONE_AREA_CODE,
                                        SCD_PHONE_NUMBER,
                                        SCD_PHONE_EXTENSION,
                                        FAX_PHONE_NUMBER_TYPE,
                                        FAX_PHONE_AREA_CODE,
                                        FAX_PHONE_NUMBER,
                                        FAX_PHONE_EXTENSION,
                                        ADMIN_TO_SALES_AREA,
                                        ADMIN_TO_SALES_DISTRICT,
                                        ADMIN_TO_SALES_DIVISION,
                                        ALTERNATE_DAD,
                                        FACTS_DIVISION,
                                        LEGACY_GL_DIVISION,
                                        GLOBAL_HIERARCHY,
                                        MANAGER_ID)
         )
         LOCATION ('COST_CENTER_OTHER.csv')
)REJECT LIMIT UNLIMITED;