/*
Created :dxv848 09/28/2015 DDL for TERR_CCN_NAME_CHG table.
*/
  CREATE TABLE TERR_CCN_NAME_CHG
      ( COST_CENTER_CODE VARCHAR2(6),
        COST_CENTER_NAME VARCHAR2(35),
                CATEGORY VARCHAR2(1)
      );