CREATE TABLE PRCCNTR_EXT_DETAIL
   (	PRICE_DIST_NBR VARCHAR2(5), 
	COST_CENTER_CODE VARCHAR2(6), 
	EFFECTIVE_DATE VARCHAR2(8), 
	EXPIRATION_DATE VARCHAR2(8), 
	LAST_MAINT_AUTH_ID VARCHAR2(6)
   ) 
   ORGANIZATION EXTERNAL 
    ( TYPE ORACLE_LOADER
      DEFAULT DIRECTORY CCN_DATAFILES
      ACCESS PARAMETERS
      ( RECORDS DELIMITED BY NEWLINE
        badfile CCN_DATAFILES:'PRCCNTR_EXT_DETAIL.bad'
        logfile CCN_DATAFILES:'PRCCNTR_EXT_DETAIL.log'
        discardfile CCN_DATAFILES:'PRCCNTR_EXT_DETAIL.dsc'
        FIELDS MISSING FIELD VALUES ARE NULL
      (
        PRICE_DIST_NBR CHAR(5),
        COST_CENTER_CODE   CHAR(6), 
        EFFECTIVE_DATE   CHAR(8), 
        EXPIRATION_DATE  CHAR(8), 
        LAST_MAINT_AUTH_ID CHAR(6)
        )
                 )
      LOCATION
       ( 'CCN99CTR_PRCCNTR.TXT'
       )
    );