  CREATE TABLE TEMP_PCI_VAL_LINK_MID
   (PCI_VAL_LINK_MID VARCHAR2(50), 
	  COST_CENTER_CODE VARCHAR2(4)
   ) 
   ORGANIZATION EXTERNAL 
    ( TYPE ORACLE_LOADER
      DEFAULT DIRECTORY "CCN_DATAFILES"
      ACCESS PARAMETERS
      ( RECORDS delimited by NEWLINE
        badfile CCN_LOAD_FILES:'TEMP_PCI_VAL_LINK_MID.bad'
        logfile CCN_LOAD_FILES:'TEMP_PCI_VAL_LINK_MID.log'
        discardfile CCN_LOAD_FILES:'TEMP_PCI_VAL_LINK_MID.dsc'
        FIELDS TERMINATED BY ','
        MISSING FIELD VALUES ARE NULL
        (PCI_VAL_LINK_MID      CHAR(50),
         COST_CENTER_CODE      CHAR(4)))
      LOCATION
       ( 'PCI_VAL_LINK_MID.csv'
       )
    );
