CREATE TABLE "COSTCNTR"."TEMP_PHONE"
  (
    "COST_CENTER_CODE"      VARCHAR2(6 BYTE),
    "PHONE_TYPE"            VARCHAR2(5 BYTE),
    "PHONE_AREA_CODE"       VARCHAR2(3 BYTE),
    "PHONE_NUMBER"          VARCHAR2(7 BYTE),
    "PHONE_EXTENSION"       VARCHAR2(4 BYTE),
    "CARR_RETURN"           VARCHAR2(1 BYTE)
  )
  ORGANIZATION EXTERNAL
  (
    TYPE ORACLE_LOADER DEFAULT DIRECTORY "CCN_LOAD_FILES" ACCESS PARAMETERS ( RECORDS FIXED 27 FIELDS( COST_CENTER_CODE CHAR(6), PHONE_TYPE CHAR(5), PHONE_AREA_CODE CHAR(3), PHONE_NUMBER CHAR(7), PHONE_EXTENSION CHAR(4), CARR_RETURN CHAR(1)) ) LOCATION ( 'CCN99CTR_PHONE.TXT')
   ) ;