CREATE TABLE TEMP_PCI_MID 
   (PCI_MERCHANT_ID	VARCHAR2(20),
    COST_CENTER_CODE VARCHAR2(4)) 
   ORGANIZATION EXTERNAL 
    ( TYPE ORACLE_LOADER
      DEFAULT DIRECTORY "CCN_DATAFILES"
      ACCESS PARAMETERS
      ( RECORDS delimited by NEWLINE
        badfile CCN_LOAD_FILES:'TEMP_PCI_MID.bad'
        logfile CCN_LOAD_FILES:'TEMP_PCI_MID.log'
        discardfile CCN_LOAD_FILES:'TEMP_PCI_MID.dsc'
        FIELDS TERMINATED BY ','
        MISSING FIELD VALUES ARE NULL
        (PCI_MERCHANT_ID      CHAR(20),
         COST_CENTER_CODE     CHAR(4)))
      LOCATION
       ('PAX_MID.csv'
       )
    );
	
