  CREATE TABLE TEMP_COST_CENTER_HIERARCHY
   (COST_CENTER_CODE VARCHAR2(6), 
	MANAGER_ID       VARCHAR2(20), 
	HIERARCHY_NAME   VARCHAR2(100), 
	HIERARCHY_VALUE  VARCHAR2(100)
   ) 
   ORGANIZATION EXTERNAL 
    ( TYPE ORACLE_LOADER
      DEFAULT DIRECTORY "CCN_LOAD_FILES"
      ACCESS PARAMETERS
      ( RECORDS DELIMITED BY NEWLINE SKIP 1 
      badfile CCN_LOAD_FILES:'TEMP_COST_CENTER_HIERARCHY.bad' 
      logfile CCN_LOAD_FILES:'TEMP_COST_CENTER_HIERARCHY.log' 
      FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
      LDRTRIM MISSING FIELD VALUES ARE NULL
      REJECT ROWS WITH ALL NULL FIELDS
      (COST_CENTER_CODE,
       MANAGER_ID,
       HIERARCHY_NAME,
       HIERARCHY_VALUE)
                      )
      LOCATION
       ( 'COST_CENTER_HIERARCHY.csv'
       )
    )
   REJECT LIMIT UNLIMITED ;