CREATE TABLE "COSTCNTR"."TEMP_ADDRESS_CAN"
  (
    "COST_CENTER_CODE"      VARCHAR2(6 BYTE),
    "ADDRESS_TYPE"          VARCHAR2(2 BYTE),
    "EFFECTIVE_DATE"        VARCHAR2(8 BYTE),
    "EXPIRATION_DATE"       VARCHAR2(8 BYTE),
    "ADDRESS_LINE_1"        VARCHAR2(35 BYTE),
    "ADDRESS_LINE_2"        VARCHAR2(35 BYTE),
    "ADDRESS_LINE_3"        VARCHAR2(35 BYTE),
    "CITY"                  VARCHAR2(25 BYTE),
    "STATE_CODE"            VARCHAR2(2 BYTE),
    "ZIP_PREFIX"            VARCHAR2(6 BYTE),
    "ZIP_SUFFIX"            VARCHAR2(4 BYTE),
    "DESTINATION_POINT"     VARCHAR2(2 BYTE),
    "CHECK_DIGIT"           VARCHAR2(1 BYTE),
    "COUNTY_CODE"           VARCHAR2(3 BYTE),
    "COUNTY_NAME"           VARCHAR2(20 BYTE),  
    "COUNTRY_CODE"          VARCHAR2(10 BYTE),
    "FIPS_CODE"             VARCHAR2(10 BYTE),
    "CARR_RETURN"           VARCHAR2(1 BYTE)
  )
  ORGANIZATION EXTERNAL
  (
    TYPE ORACLE_LOADER DEFAULT DIRECTORY "CCN_LOAD_FILES" ACCESS PARAMETERS ( RECORDS FIXED 214 FIELDS( COST_CENTER_CODE CHAR(6), ADDRESS_TYPE CHAR(2), EFFECTIVE_DATE CHAR(8), EXPIRATION_DATE CHAR(8), ADDRESS_LINE_1 CHAR(35), ADDRESS_LINE_2 CHAR(35), ADDRESS_LINE_3 CHAR(35), CITY CHAR(25), STATE_CODE CHAR(2), ZIP_PREFIX CHAR(6), ZIP_SUFFIX CHAR(4), DESTINATION_POINT CHAR(2), CHECK_DIGIT CHAR(1), 
                                                                                                        COUNTY_CODE CHAR(3), COUNTY_NAME CHAR(20), COUNTRY_CODE CHAR(10), FIPS_CODE CHAR(10), CARR_RETURN CHAR(1)) ) LOCATION ( 'CCN99CTR_ADRCA.TXT')
   ) ;