CREATE TABLE "COSTCNTR"."TEMP_CODE_DETAIL"
  (
    "CODE_TABLE_NAME"       VARCHAR2(8   BYTE),
    "CODE_ARGUMENT"         VARCHAR2(32  BYTE),
    "CODE_RESULT"           VARCHAR2(100 BYTE),
    "CARR_RETURN"           VARCHAR2(1   BYTE)
  )
  ORGANIZATION EXTERNAL
  (
    TYPE ORACLE_LOADER DEFAULT DIRECTORY "CCN_LOAD_FILES" ACCESS PARAMETERS ( RECORDS FIXED 142 FIELDS( CODE_TABLE_NAME CHAR(8), CODE_ARGUMENT CHAR(32), CODE_RESULT CHAR(100), CARR_RETURN CHAR(1)) ) LOCATION ( 'CCN99CTR_TABLE.TXT')
   ) ;