CREATE TABLE TEMP_PCI_DISCOVER_ID 
   (PCI_DISCOVER_ID	VARCHAR2(20),
    COST_CENTER_CODE VARCHAR2(4)) 
   ORGANIZATION EXTERNAL 
    ( TYPE ORACLE_LOADER
      DEFAULT DIRECTORY "CCN_DATAFILES"
      ACCESS PARAMETERS
      ( RECORDS delimited by NEWLINE
        badfile CCN_LOAD_FILES:'TEMP_PCI_DISCOVER_ID.bad'
        logfile CCN_LOAD_FILES:'TEMP_PCI_DISCOVER_ID.log'
        discardfile CCN_LOAD_FILES:'TEMP_PCI_DISCOVER_ID.dsc'
        FIELDS TERMINATED BY ','
        MISSING FIELD VALUES ARE NULL
        (PCI_DISCOVER_ID      CHAR(20),
         COST_CENTER_CODE     CHAR(4)))
      LOCATION
       ('PAX_DISCOVER_ID.csv'
       )
    );