  CREATE TABLE TEMP_PCI_TERMINAL_ID
   (PCI_TERMINAL_ID VARCHAR2(50), 
	  COST_CENTER_CODE VARCHAR2(4)
   ) 
   ORGANIZATION EXTERNAL 
    ( TYPE ORACLE_LOADER
      DEFAULT DIRECTORY "CCN_DATAFILES"
      ACCESS PARAMETERS
      ( RECORDS delimited by NEWLINE
        badfile CCN_LOAD_FILES:'TEMP_PCI_TERMINAL_ID.bad'
        logfile CCN_LOAD_FILES:'TEMP_PCI_TERMINAL_ID.log'
        discardfile CCN_LOAD_FILES:'TEMP_PCI_TERMINAL_ID.dsc'
        FIELDS TERMINATED BY ','
        MISSING FIELD VALUES ARE NULL
        (PCI_TERMINAL_ID      CHAR(50),
         COST_CENTER_CODE     CHAR(4)))
      LOCATION
       ( 'PCI_TERMINAL_ID.csv'
       )
    );
