
-- Define TEMP_POLLING_DWLD_RSN
-- Updated: tal 08/29/2012

DROP   TABLE "COSTCNTR"."TEMP_POLLING_DWLD_RSN"  ;

CREATE TABLE "COSTCNTR"."TEMP_POLLING_DWLD_RSN"
  (
    COST_CENTER_CODE           VARCHAR2(06 BYTE) ,
    POLLING_STATUS_CODE        VARCHAR2(01 BYTE) ,
    EFFECTIVE_DATE             VARCHAR2(08 BYTE) ,
    DOWNLOAD_DATE              VARCHAR2(08 BYTE) ,
    DOWNLOAD_REASON            VARCHAR2(04 BYTE)  
  )
  
ORGANIZATION EXTERNAL

  ( TYPE ORACLE_LOADER DEFAULT DIRECTORY CCN_LOAD_FILES ACCESS PARAMETERS 
  ( RECORDS FIXED 035

FIELDS ( 
    COST_CENTER_CODE           CHAR(06) ,
    SPACES_01                  CHAR(01) ,
    COST_CENTER_CODE_OLD       CHAR(04) ,
    SPACES_02                  CHAR(01) ,
    POLLING_STATUS_CODE        CHAR(01) ,
    EFFECTIVE_DATE             CHAR(08) ,
    DOWNLOAD_DATE              CHAR(08) ,
    DOWNLOAD_REASON            CHAR(04) ,
    END_MARKER_X               CHAR(01) ,
    CARR_RETURN                CHAR(01)  
) 
) 

LOCATION ( CCN_LOAD_FILES: 'COSTCTR_DATA5113.TXT' )
  )
  REJECT LIMIT 0