
-- Define TEMP_TERMINAL
-- Updated: tal 08/29/2012

DROP   TABLE "COSTCNTR"."TEMP_TERMINAL" ;

CREATE TABLE "COSTCNTR"."TEMP_TERMINAL"
  (
    COST_CENTER_CODE           VARCHAR2(06 BYTE) ,
    POLLING_STATUS_CODE        VARCHAR2(01 BYTE) ,
    PROCESSOR_SERIAL_NUMBER    VARCHAR2(15 BYTE) ,
    TERMINAL_SERIAL_NUMBER     VARCHAR2(15 BYTE) ,
    TERMINAL_NUMBER            VARCHAR2(05 BYTE) ,
    TERMINAL_TYPE              VARCHAR2(02 BYTE) ,
    EFFECTIVE_DATE             VARCHAR2(08 BYTE) ,
    EXPIRATION_DATE            VARCHAR2(08 BYTE) ,
    POS_LAST_TRAN_DATE         VARCHAR2(08 BYTE) ,
    POS_LAST_TRAN_NUMBER       VARCHAR2(05 BYTE)  
  )
  
ORGANIZATION EXTERNAL

  ( TYPE ORACLE_LOADER DEFAULT DIRECTORY CCN_LOAD_FILES ACCESS PARAMETERS 
  ( RECORDS FIXED 086

FIELDS ( 
    COST_CENTER_CODE           CHAR(06) ,
    SPACES_01                  CHAR(01) ,
    COST_CENTER_CODE_OLD       CHAR(04) ,
    SPACES_02                  CHAR(01) ,
    POLLING_STATUS_CODE        CHAR(01) ,
    PROCESSOR_SERIAL_NUMBER    CHAR(15) ,
    TERMINAL_SERIAL_NUMBER     CHAR(15) ,
    TERMINAL_NUMBER            CHAR(05) ,
    TERMINAL_TYPE              CHAR(02) ,
    EFFECTIVE_DATE             CHAR(08) ,
    EXPIRATION_DATE            CHAR(08) ,
    POS_LAST_TRAN_DATE         CHAR(08) ,
    POS_LAST_TRAN_FILLER       CHAR(05) ,
    POS_LAST_TRAN_NUMBER       CHAR(05) ,
    END_MARKER_X               CHAR(01) ,
    CARR_RETURN                CHAR(01)  

) 
) 

LOCATION ( CCN_LOAD_FILES: 'COSTCTR_DATA5125.TXT' )

  )
  REJECT LIMIT 0