
-- Define TEMP_BANK_CARD
-- Updated: tal 08/29/2012

DROP   TABLE "COSTCNTR"."TEMP_BANK_CARD"  ;

CREATE TABLE "COSTCNTR"."TEMP_BANK_CARD"
  (
    COST_CENTER_CODE           VARCHAR2(06 BYTE) ,
    POLLING_STATUS_CODE        VARCHAR2(01 BYTE) ,
    MERCHANT_ID                VARCHAR2(11 BYTE) ,
    EFFECTIVE_DATE             VARCHAR2(08 BYTE) ,
    EXPIRATION_DATE            VARCHAR2(08 BYTE) ,
    LAST_CHANGE_DATE           VARCHAR2(08 BYTE) ,
    LAST_MAINTENANCE_AUTH_ID   VARCHAR2(08 BYTE) ,
    LAST_MAINTENANCE_USER_ID   VARCHAR2(08 BYTE) ,
    DISCOVER_ID                VARCHAR2(15 BYTE) ,
    QUALITY_CODE               VARCHAR2(06 BYTE) ,
    NETACC_PHONE_1             VARCHAR2(15 BYTE) ,
    NETACC_PHONE_2             VARCHAR2(15 BYTE) ,
    AMEX_SE_ID                 VARCHAR2(10 BYTE)  
  )
  
ORGANIZATION EXTERNAL

  ( TYPE ORACLE_LOADER DEFAULT DIRECTORY CCN_LOAD_FILES ACCESS PARAMETERS 
  ( RECORDS FIXED 131

FIELDS ( 
    COST_CENTER_CODE           CHAR(06) ,
    SPACES_01                  CHAR(01) ,
    COST_CENTER_CODE_OLD       CHAR(04) ,
    SPACES_02                  CHAR(01) ,
    POLLING_STATUS_CODE        CHAR(01) ,
    MERCHANT_ID                CHAR(11) ,
    MERCHANT_ID_FILLER         CHAR(04) ,
    EFFECTIVE_DATE             CHAR(08) ,
    EXPIRATION_DATE            CHAR(08) ,
    LAST_CHANGE_DATE           CHAR(08) ,
    LAST_MAINTENANCE_AUTH_ID   CHAR(08) ,
    LAST_MAINTENANCE_USER_ID   CHAR(08) ,
    DISCOVER_ID                CHAR(15) ,
    QUALITY_CODE               CHAR(06) ,
    NETACC_PHONE_1             CHAR(15) ,
    NETACC_PHONE_2             CHAR(15) ,
    AMEX_SE_ID                 CHAR(10) ,
    END_MARKER_X               CHAR(01) ,
    CARR_RETURN                CHAR(01)  
) 
) 

LOCATION ( CCN_LOAD_FILES: 'COSTCTR_DATA5084.TXT' )
  )
  REJECT LIMIT 0