/*
Script Name : TEMP_STR_DSPTH_SRV_TYP_CD_UPD.sql
Purpose     : For creating TEMP_STR_DSPTH_SRV_TYP_CD_UPD table.
              This is an external table which is used for storing data from STORE_DISPATCH_SERVICES_TYPE_CODE_UPDATE.csv
              loaded through batch process.

Created : 06/14/2019 akj899  CCNCC-13 CCN Project....
*/

DROP TABLE TEMP_STR_DSPTH_SRV_TYP_CD_UPD;

CREATE TABLE TEMP_STR_DSPTH_SRV_TYP_CD_UPD
   (COST_CENTER_CODE VARCHAR2(6),
    DISPATCH_SERVICES_TYPE_CODE VARCHAR2(1)
   )
   ORGANIZATION EXTERNAL
    (TYPE ORACLE_LOADER
      DEFAULT DIRECTORY "CCN_LOAD_FILES"
      ACCESS PARAMETERS
      (RECORDS DELIMITED BY NEWLINE SKIP 1
          badfile "CCN_LOAD_FILES":'STORE_DISPATCH_SERVICES_TYPE_CODE_UPDATE.bad'
          logfile "CCN_LOAD_FILES":'STORE_DISPATCH_SERVICES_TYPE_CODE_UPDATE.log'
             FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
             LRTRIM
             MISSING FIELD VALUES ARE NULL
             (COST_CENTER_CODE,
              DISPATCH_SERVICES_TYPE_CODE
              )
       )
      LOCATION
       ( 'STORE_DISPATCH_SERVICES_TYPE_CODE_UPDATE.csv'
       )
    ) REJECT LIMIT UNLIMITED;