CREATE TABLE "COSTCNTR"."TEMP_STATUS"
  (
    "COST_CENTER_CODE"      VARCHAR2(6 BYTE),
    "STATUS_CODE"           VARCHAR2(1 BYTE),
    "EFFECTIVE_DATE"        VARCHAR2(8 BYTE),
    "EXPIRATION_DATE"       VARCHAR2(8 BYTE),
    "CARR_RETURN"           VARCHAR2(1 BYTE)
  )
  ORGANIZATION EXTERNAL
  (
    TYPE ORACLE_LOADER DEFAULT DIRECTORY "CCN_LOAD_FILES" ACCESS PARAMETERS ( RECORDS FIXED 25 FIELDS( COST_CENTER_CODE CHAR(6), STATUS_CODE CHAR(1), EFFECTIVE_DATE CHAR(8), EXPIRATION_DATE CHAR(8), CARR_RETURN CHAR(1)) ) LOCATION ( 'CCN99CTR_STATS.TXT')
   ) ;