/*
created : 12/12/2016 jxc517/nxk CCN Project Team....
          Below script will default the DEPBAG_REORDER_QTY to 20 always
		  Updating the order date with LAST_MAINTENANCE_DATE
*/
SELECT * FROM BANK_DEP_BAG_TICK WHERE DEPBAG_REORDER_QTY <> 200;
UPDATE BANK_DEP_BAG_TICK SET DEPBAG_REORDER_QTY = 200 WHERE DEPBAG_REORDER_QTY <> 200;

SELECT * FROM BANK_DEP_BAG_TICK_FUTURE WHERE DEPBAG_REORDER_QTY <> 200;
UPDATE BANK_DEP_BAG_TICK_FUTURE SET DEPBAG_REORDER_QTY = 200 WHERE DEPBAG_REORDER_QTY <> 200;

COMMIT;


/
UPDATE BANK_DEP_BAG_TICKORD
   SET ORDER_DATE = LAST_MAINTENANCE_DATE;

UPDATE BANK_DEP_BAG_TICKORD_FUTURE
   SET ORDER_DATE = LAST_MAINTENANCE_DATE;

UPDATE BANK_DEP_BAG_TICKORD_HIST
   SET ORDER_DATE = LAST_MAINTENANCE_DATE;

UPDATE BANK_DEP_TICKORD
   SET ORDER_DATE = LAST_MAINTENANCE_DATE;

UPDATE BANK_DEP_TICKORD_FUTURE
   SET ORDER_DATE = LAST_MAINTENANCE_DATE;

UPDATE BANK_DEP_TICKORD_HIST
   SET ORDER_DATE = LAST_MAINTENANCE_DATE;
   

COMMIT;
/