/**************************************************
Created : nxk927 07/26/2017
          deleting the data to rerun the 13-JUL-2017 load
          update the UAR_SUMMARY_EXTRCT_CNTRL_FL with correct bank account number
****************************************************/

DELETE FROM UAR_SUMMARY_EXTRCT_CNTRL_FL WHERE LOAD_DATE = '13-JUL-2017';
DELETE FROM SUMMARY_EXTRCT_CNTRL_FL WHERE LOAD_DATE = '13-JUL-2017';

DELETE FROM UAR_ACH_DRFTS_EXT_CTRL WHERE LOAD_DATE = '13-JUL-2017';
DELETE FROM ACH_DRFTS_EXT_CTRL WHERE LOAD_DATE = '13-JUL-2017';

DELETE FROM MISCTRAN WHERE LOAD_DATE = '13-JUL-2017';
DELETE FROM UAR_MISCTRAN WHERE LOAD_DATE = '13-JUL-2017';
Commit;



/


DECLARE
BEGIN
FOR REC IN (SELECT U.* , FL.ORIGINATED_BANK_ACCNT_NBR
              FROM UAR_SUMMARY_EXTRCT_CNTRL_FL  U, SUMMARY_EXTRCT_CNTRL_FL FL
             WHERE U.LOAD_DATE > '22-MAY-2017'
               AND FL.COST_CENTER_CODE = U.COST_CENTER_CODE
               AND FL.BANK_DEP_AMT     = U.BANK_DEP_AMT
               AND FL.TRANSACTION_DATE = U.TRANSACTION_DATE
               AND FL.LOAD_DATE        = U.LOAD_DATE
               AND U.BANK_ACCOUNT_NBR  <> FL.ORIGINATED_BANK_ACCNT_NBR) LOOP
    UPDATE UAR_SUMMARY_EXTRCT_CNTRL_FL
       SET BANK_ACCOUNT_NBR = REC.ORIGINATED_BANK_ACCNT_NBR
     WHERE LOAD_DATE        = REC.LOAD_DATE
       AND COST_CENTER_CODE = REC.COST_CENTER_CODE
       AND BANK_DEP_AMT     = REC.BANK_DEP_AMT
       AND TRANSACTION_DATE = REC.TRANSACTION_DATE
       AND LOAD_DATE        = REC.LOAD_DATE
       AND BANK_ACCOUNT_NBR  <> REC.ORIGINATED_BANK_ACCNT_NBR;
    
END LOOP;
END;

Commit;