/*
Below script will make sure cost center 702763 will not show up in SRA11000 as it is closed in 2009

Created : 3/27/2019 jxc517 CCN Project Team....
Changed
*/
--Insert current record into history expiring as of 31-Dec-2009
INSERT INTO MEMBER_BANK_CC_HIST
SELECT LEAD_BANK_ACCOUNT_NBR, LEAD_STORE_NBR, MEMBER_STORE_NBR, EFFECTIVE_DATE, TO_DATE('31-DEC-2009') EXPIRATION_DATE, MEMBER_BANK_ACCOUNT_NBR, BANK_BRANCH_NBR, UPDATE_DATE, LAST_UPD_USER_ID
FROM MEMBER_BANK_CC WHERE MEMBER_STORE_NBR = '702763';
SELECT * FROM MEMBER_BANK_CC_HIST WHERE MEMBER_STORE_NBR = '702763';

--Delete current record
SELECT * FROM MEMBER_BANK_CC WHERE MEMBER_STORE_NBR = '702763';
DELETE FROM MEMBER_BANK_CC WHERE MEMBER_STORE_NBR = '702763';
SELECT * FROM MEMBER_BANK_CC WHERE MEMBER_STORE_NBR = '702763';
COMMIT;
