INSERT INTO AUDIT_COMPARE_IGNORE_COLUMNS VALUES('LAST_MAINTENANCE_DATE');
INSERT INTO AUDIT_COMPARE_IGNORE_COLUMNS VALUES('LAST_MAINT_AUTH_ID');
INSERT INTO AUDIT_COMPARE_IGNORE_COLUMNS VALUES('LAST_MAINT_USER_ID');
INSERT INTO AUDIT_COMPARE_IGNORE_COLUMNS VALUES('LAST_UPD_USER_ID');
INSERT INTO AUDIT_COMPARE_IGNORE_COLUMNS VALUES('UPDATE_DATE');
COMMIT;