/*
created : 12/07/2016 jxc517 CCN Project Team
          Below script will update the missing values in deposit ticket table
*/

/*
below query is to get the part number for stores : usually will be 2

SELECT * FROM BANK_MICR_FORMAT WHERE (BANK_ACCOUNT_NBR, MICR_FORMAT_ID) IN (
SELECT BANK_ACCOUNT_NBR, MICR_FORMAT_ID FROM STORE_MICR_FORMAT_DTLS WHERE COST_CENTER_CODE IN (
SELECT MEMBER_STORE_NBR FROM MEMBER_BANK_CC WHERE MEMBER_STORE_NBR IN (SELECT COST_CENTER_CODE FROM BANK_DEP_TICK WHERE PART_PAPER_PER_FORM IS NULL))
UNION
SELECT BANK_ACCOUNT_NBR, MICR_FORMAT_ID FROM STORE_MICR_FORMAT_DTLS WHERE COST_CENTER_CODE IN (
SELECT LEAD_STORE_NBR FROM MEMBER_BANK_CC WHERE MEMBER_STORE_NBR IN (SELECT COST_CENTER_CODE FROM BANK_DEP_TICK WHERE PART_PAPER_PER_FORM IS NULL))
);


SELECT * FROM BANK_DEP_TICK_FUTURE WHERE PART_PAPER_PER_FORM IS NULL;
SELECT * FROM STORE_MICR_FORMAT_DTLS_FUTURE WHERE COST_CENTER_CODE = '702334';
SELECT * FROM BANK_MICR_FORMAT_FUTURE WHERE BANK_ACCOUNT_NBR = '1002421866' AND MICR_FORMAT_ID = 9;

*/

SELECT * FROM BANK_DEP_TICK WHERE REORDER_NUMBER_BKS IS NULL;
UPDATE BANK_DEP_TICK SET REORDER_NUMBER_BKS = 1 WHERE REORDER_NUMBER_BKS IS NULL;

SELECT * FROM BANK_DEP_TICK WHERE PART_PAPER_PER_FORM IS NULL;
UPDATE BANK_DEP_TICK SET PART_PAPER_PER_FORM = 2 WHERE PART_PAPER_PER_FORM IS NULL;

SELECT * FROM BANK_DEP_TICK_FUTURE WHERE REORDER_NUMBER_BKS IS NULL;
UPDATE BANK_DEP_TICK_FUTURE SET REORDER_NUMBER_BKS = 1 WHERE REORDER_NUMBER_BKS IS NULL;

SELECT * FROM BANK_DEP_TICK_FUTURE WHERE PART_PAPER_PER_FORM IS NULL;
UPDATE BANK_DEP_TICK_FUTURE SET PART_PAPER_PER_FORM = 2 WHERE PART_PAPER_PER_FORM IS NULL;

COMMIT;
