/*
Created : nxk927 10/18/2017
          This will update the DEP_BAG_REORDER_POINT to 21 if it is null.
          This will also update DEPBAG_ONHAND_QTY/DEP_TKTS_ONHAND_QTY to 0 if its less than 0
*/
UPDATE BANK_DEP_BAG_TICK
   SET DEP_BAG_REORDER_POINT = 21
  WHERE DEP_BAG_REORDER_POINT IS NULL;
   
UPDATE BANK_DEP_BAG_TICK
   SET DEPBAG_ONHAND_QTY = 0
 WHERE DEPBAG_ONHAND_QTY < 0;
 
UPDATE BANK_DEP_TICK
   SET DEP_TKTS_ONHAND_QTY = 0
 WHERE DEP_TKTS_ONHAND_QTY < 0;
  
COMMIT;


