/*
Created : dxv848 11/21/2015 INSERTS for  CODE_HEADER table.
*/

INSERT INTO CODE_HEADER VALUES ('ADD_ON_QUANTITY','COD','ADD ON QUALITY TYPE',null,null,null,1,null,null,null);
INSERT INTO CODE_HEADER VALUES ('BAG_TYPE','COD','BAG TYPE',null,null,null,1,null,null,null);
INSERT INTO CODE_HEADER VALUES ('BAG_REORDER_SWITCH','COD','BAG REORDER SWITCH TYPE',null,null,null,1,null,null,null);
INSERT INTO CODE_HEADER VALUES ('REORDER_SWTICH','COD','REORDER SWTICH TYPE',null,null,null,1,null,null,null);
INSERT INTO CODE_HEADER VALUES ('BANK_TYPE','COD','BANK TYPE',null,null,null,1,null,null,null);
INSERT INTO CODE_HEADER VALUES ('RECONCELLATION_SWITCH','COD','RECONCELLATION SWTICH TYPE',null,null,null,1,null,null,null);
INSERT INTO CODE_HEADER VALUES ('BOOK_KEEPER','COD','BOOKKEEPER TYPE',null,null,null,2,null,null,null);

COMMIT;
