/*
   script name: DML_TEMP_DEP_TICK_EXCLUDED.sql
   Created by : 03/07/2018 axt754 CCN Project Team...
                This Script Inserts data into TEMP_DEP_TICK_EXCLUDED table
*/


-- BEGIN UPDATES 
SET DEFINE OFF;
SET SERVEROUTPUT ON;
BEGIN
for rec in (SELECT '701414'as COST_CENTER_CODE , 'SHERLINK ONLINE PAYMENTS' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'USA' as COUNTRY_CODE , '35955' as OPEN_DATE from Dual Union
SELECT '701427'as COST_CENTER_CODE , 'DUNKIRK' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'USA' as COUNTRY_CODE , '39072' as OPEN_DATE from Dual Union
SELECT '702751'as COST_CENTER_CODE , 'M/W DIV-P&L DIRECT SALES' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'USA' as COUNTRY_CODE , '35163' as OPEN_DATE from Dual Union
SELECT '702752'as COST_CENTER_CODE , 'EAST DIV - P&L DIRECT SALES' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'USA' as COUNTRY_CODE , '35156' as OPEN_DATE from Dual Union
SELECT '702753'as COST_CENTER_CODE , 'S/E DIV - P&L DIRECT SALES' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'USA' as COUNTRY_CODE , '35163' as OPEN_DATE from Dual Union
SELECT '702754'as COST_CENTER_CODE , 'S/W DIV - P&L DIRECT SALES' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'USA' as COUNTRY_CODE , '35163' as OPEN_DATE from Dual Union
SELECT '702755'as COST_CENTER_CODE , 'HIGHWAY DIRECT SLS' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'USA' as COUNTRY_CODE , '35851' as OPEN_DATE from Dual Union
SELECT '702879'as COST_CENTER_CODE , 'ST MAARTEN-COLE BAY' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'ANT' as COUNTRY_CODE , '40008' as OPEN_DATE from Dual Union
SELECT '708517'as COST_CENTER_CODE , 'CAMPBELL' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'USA' as COUNTRY_CODE , '28611' as OPEN_DATE from Dual Union
SELECT '761453'as COST_CENTER_CODE , 'TROIS-RIVIERES-EAST' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '43083' as OPEN_DATE from Dual Union
SELECT '761456'as COST_CENTER_CODE , 'CHICOUTIMI' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '42971' as OPEN_DATE from Dual Union
SELECT '761491'as COST_CENTER_CODE , 'KELOWNA-COMMERCIAL' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '42915' as OPEN_DATE from Dual Union
SELECT '761833'as COST_CENTER_CODE , 'SYDNEY' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '42999' as OPEN_DATE from Dual Union
SELECT '763493'as COST_CENTER_CODE , 'CALGARY-SOUTH TRAIL' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '42912' as OPEN_DATE from Dual Union
SELECT '763494'as COST_CENTER_CODE , 'SURREY-NEWTON' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '42859' as OPEN_DATE from Dual Union
SELECT '763495'as COST_CENTER_CODE , 'ST CATHARINES-SOUTH' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '42859' as OPEN_DATE from Dual Union
SELECT '763496'as COST_CENTER_CODE , 'LONDON-NORTH EAST' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '42704' as OPEN_DATE from Dual Union
SELECT '763575'as COST_CENTER_CODE , 'ST JEROME' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '42719' as OPEN_DATE from Dual Union
SELECT '763576'as COST_CENTER_CODE , 'CHARLOTTETOWN-PEI' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '42692' as OPEN_DATE from Dual Union
SELECT '763577'as COST_CENTER_CODE , 'BARRIE-NORTH' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '42825' as OPEN_DATE from Dual Union
SELECT '763579'as COST_CENTER_CODE , 'OKOTOKS' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '42704' as OPEN_DATE from Dual Union
SELECT '763581'as COST_CENTER_CODE , 'GEORGETOWN' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '42718' as OPEN_DATE from Dual Union
SELECT '763582'as COST_CENTER_CODE , 'HAMILTON-EAST' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '42685' as OPEN_DATE from Dual Union
SELECT '763583'as COST_CENTER_CODE , 'WINNIPEG-NORTH' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '42719' as OPEN_DATE from Dual Union
SELECT '763584'as COST_CENTER_CODE , 'LAVAL-ST DOROTHEE' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '43006' as OPEN_DATE from Dual Union
SELECT '763590'as COST_CENTER_CODE , 'CAMBRIDGE-SOUTH' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '42545' as OPEN_DATE from Dual Union
SELECT '763591'as COST_CENTER_CODE , 'BARRHAVEN' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '42629' as OPEN_DATE from Dual Union
SELECT '763592'as COST_CENTER_CODE , 'GATINEAU-HULL' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '43013' as OPEN_DATE from Dual Union
SELECT '763593'as COST_CENTER_CODE , 'ANCASTER' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '42613' as OPEN_DATE from Dual Union
SELECT '763594'as COST_CENTER_CODE , 'PORT COQUITLAM' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '42674' as OPEN_DATE from Dual Union
SELECT '763595'as COST_CENTER_CODE , 'TORONTO-NORTH YORK' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '42580' as OPEN_DATE from Dual Union
SELECT '763596'as COST_CENTER_CODE , 'CHATEAUGUAY' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '42580' as OPEN_DATE from Dual Union
SELECT '763597'as COST_CENTER_CODE , 'AIRDRIE' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '42613' as OPEN_DATE from Dual Union
SELECT '763598'as COST_CENTER_CODE , 'BURLINGTON-NORTH' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '42977' as OPEN_DATE from Dual Union
SELECT '768129'as COST_CENTER_CODE , 'SAINT-JEAN RICHELIEU' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '43048' as OPEN_DATE from Dual Union
SELECT '768502'as COST_CENTER_CODE , 'CHATHAM' as COST_CENTER_NAME , 'Q' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '' as OPEN_DATE from Dual Union
SELECT '768503'as COST_CENTER_CODE , 'NEPEAN-OTTAWA' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '43069' as OPEN_DATE from Dual Union
SELECT '768612'as COST_CENTER_CODE , 'GUELPH-SOUTH' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '43076' as OPEN_DATE from Dual Union
SELECT '768614'as COST_CENTER_CODE , 'ORILLIA' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '43036' as OPEN_DATE from Dual Union
SELECT '768681'as COST_CENTER_CODE , 'COLE HARBOUR-DARTMOUTH' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '42627' as OPEN_DATE from Dual Union
SELECT '768702'as COST_CENTER_CODE , 'MISSISSAUGA-COMMERCIAL' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '33347' as OPEN_DATE from Dual Union
SELECT '768704'as COST_CENTER_CODE , 'TORONTO CARLAW-COMMERCIAL' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '33413' as OPEN_DATE from Dual Union
SELECT '768705'as COST_CENTER_CODE , 'WATERLOO' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '33469' as OPEN_DATE from Dual Union
SELECT '768706'as COST_CENTER_CODE , 'SCARBOROUGH-COMMERCIAL' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '33413' as OPEN_DATE from Dual Union
SELECT '768707'as COST_CENTER_CODE , 'HAMILTON-COMMERCIAL' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '33499' as OPEN_DATE from Dual Union
SELECT '768708'as COST_CENTER_CODE , 'LONDON-SOUTH' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '33562' as OPEN_DATE from Dual Union
SELECT '768709'as COST_CENTER_CODE , 'OTTAWA COMMERCIAL' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '33823' as OPEN_DATE from Dual Union
SELECT '768712'as COST_CENTER_CODE , 'MONTREAL VILLE D-ANJOU' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '34121' as OPEN_DATE from Dual Union
SELECT '768713'as COST_CENTER_CODE , 'MOUNT ROYAL MONTREAL' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '34212' as OPEN_DATE from Dual Union
SELECT '768714'as COST_CENTER_CODE , 'QUEBEC CITY SAINTE-FOY' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '34183' as OPEN_DATE from Dual Union
SELECT '768715'as COST_CENTER_CODE , 'LAVAL' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '34281' as OPEN_DATE from Dual Union
SELECT '768717'as COST_CENTER_CODE , 'SURREY-PORT KELLS' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '34618' as OPEN_DATE from Dual Union
SELECT '768720'as COST_CENTER_CODE , 'ST CATHARINES' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '34828' as OPEN_DATE from Dual Union
SELECT '768721'as COST_CENTER_CODE , 'RICHMOND-BRIDGEPORT' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '34870' as OPEN_DATE from Dual Union
SELECT '768723'as COST_CENTER_CODE , 'TORONTO-CALEDONIA' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '35093' as OPEN_DATE from Dual Union
SELECT '768724'as COST_CENTER_CODE , 'DARTMOUTH' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '35215' as OPEN_DATE from Dual Union
SELECT '768725'as COST_CENTER_CODE , 'SHERBROOKE-COMMERCIAL' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '35513' as OPEN_DATE from Dual Union
SELECT '768726'as COST_CENTER_CODE , 'OAKVILLE-SOUTH' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '35562' as OPEN_DATE from Dual Union
SELECT '768727'as COST_CENTER_CODE , 'WINDSOR' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '35760' as OPEN_DATE from Dual Union
SELECT '768728'as COST_CENTER_CODE , 'BROSSARD' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '36103' as OPEN_DATE from Dual Union
SELECT '768729'as COST_CENTER_CODE , 'OSHAWA-SOUTH' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '36102' as OPEN_DATE from Dual Union
SELECT '768732'as COST_CENTER_CODE , 'OTTAWA-EAST' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '36696' as OPEN_DATE from Dual Union
SELECT '768734'as COST_CENTER_CODE , 'DIEPPE' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '36836' as OPEN_DATE from Dual Union
SELECT '768735'as COST_CENTER_CODE , 'SUDBURY' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '37111' as OPEN_DATE from Dual Union
SELECT '768736'as COST_CENTER_CODE , 'SURREY COMMERCIAL' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '37242' as OPEN_DATE from Dual Union
SELECT '768738'as COST_CENTER_CODE , 'CALGARY COMMERCIAL' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '37462' as OPEN_DATE from Dual Union
SELECT '768740'as COST_CENTER_CODE , 'BARRIE-SOUTH' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '37602' as OPEN_DATE from Dual Union
SELECT '768742'as COST_CENTER_CODE , 'NIAGARA FALLS' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '37880' as OPEN_DATE from Dual Union
SELECT '768743'as COST_CENTER_CODE , 'HAMILTON-MOUNTAIN' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '37970' as OPEN_DATE from Dual Union
SELECT '768744'as COST_CENTER_CODE , 'HALIFAX' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '38194' as OPEN_DATE from Dual Union
SELECT '768745'as COST_CENTER_CODE , 'MISSISSAUGA-PORT CREDIT' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '38331' as OPEN_DATE from Dual Union
SELECT '768746'as COST_CENTER_CODE , 'BURLINGTON-SOUTH' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '38322' as OPEN_DATE from Dual Union
SELECT '768747'as COST_CENTER_CODE , 'CALGARY-EAST HILLS' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '38503' as OPEN_DATE from Dual Union
SELECT '768748'as COST_CENTER_CODE , 'AURORA' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '38525' as OPEN_DATE from Dual Union
SELECT '768749'as COST_CENTER_CODE , 'THORNHILL' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '38611' as OPEN_DATE from Dual Union
SELECT '768750'as COST_CENTER_CODE , 'WOODBRIDGE-COMMERCIAL' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '38561' as OPEN_DATE from Dual Union
SELECT '768753'as COST_CENTER_CODE , 'EDMONTON SOUTH' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '38705' as OPEN_DATE from Dual Union
SELECT '768754'as COST_CENTER_CODE , 'KITCHENER' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '38775' as OPEN_DATE from Dual Union
SELECT '768755'as COST_CENTER_CODE , 'AJAX' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '39423' as OPEN_DATE from Dual Union
SELECT '768756'as COST_CENTER_CODE , 'PITT MEADOWS' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '39106' as OPEN_DATE from Dual Union
SELECT '768759'as COST_CENTER_CODE , 'ETOBICOKE-SOUTH' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '39438' as OPEN_DATE from Dual Union
SELECT '768761'as COST_CENTER_CODE , 'WHISTLER' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '39082' as OPEN_DATE from Dual Union
SELECT '768762'as COST_CENTER_CODE , 'OAKVILLE-NORTH' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '39444' as OPEN_DATE from Dual Union
SELECT '768763'as COST_CENTER_CODE , 'TORONTO-LEASIDE' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '39078' as OPEN_DATE from Dual Union
SELECT '768764'as COST_CENTER_CODE , 'HAMILTON-MAIN ST' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '39409' as OPEN_DATE from Dual Union
SELECT '768765'as COST_CENTER_CODE , 'VANCOUVER FALSE CREEK' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '39444' as OPEN_DATE from Dual Union
SELECT '768766'as COST_CENTER_CODE , 'GUELPH' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '39079' as OPEN_DATE from Dual Union
SELECT '768767'as COST_CENTER_CODE , 'VANCOUVER KERRISDALE' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '39444' as OPEN_DATE from Dual Union
SELECT '768768'as COST_CENTER_CODE , 'SURREY CLOVERDALE' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '39440' as OPEN_DATE from Dual Union
SELECT '768769'as COST_CENTER_CODE , 'PETERBOROUGH' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '39770' as OPEN_DATE from Dual Union
SELECT '768770'as COST_CENTER_CODE , 'BRAMPTON-NORTH' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '39693' as OPEN_DATE from Dual Union
SELECT '768771'as COST_CENTER_CODE , 'MARKHAM-NORTH' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '39701' as OPEN_DATE from Dual Union
SELECT '768772'as COST_CENTER_CODE , 'BRANTFORD' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '39805' as OPEN_DATE from Dual Union
SELECT '768773'as COST_CENTER_CODE , 'MONTREAL ST LEONARD' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '39797' as OPEN_DATE from Dual Union
SELECT '768774'as COST_CENTER_CODE , 'REPENTIGNY' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '39916' as OPEN_DATE from Dual Union
SELECT '768775'as COST_CENTER_CODE , 'TROIS-RIVIERES' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '39811' as OPEN_DATE from Dual Union
SELECT '768776'as COST_CENTER_CODE , 'MISSISSAUGA-MEADOWVALE' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '39805' as OPEN_DATE from Dual Union
SELECT '768777'as COST_CENTER_CODE , 'NORTH VANCOUVER' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '39843' as OPEN_DATE from Dual Union
SELECT '768778'as COST_CENTER_CODE , 'WINNIPEG-REGENT' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '40056' as OPEN_DATE from Dual Union
SELECT '768779'as COST_CENTER_CODE , 'GATINEAU' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '40169' as OPEN_DATE from Dual Union
SELECT '768780'as COST_CENTER_CODE , 'TORONTO-CORKTOWN' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '40154' as OPEN_DATE from Dual Union
SELECT '768781'as COST_CENTER_CODE , 'ROYAL OAK' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '40147' as OPEN_DATE from Dual Union
SELECT '768782'as COST_CENTER_CODE , 'MONTREAL-WEST ISLAND' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '40168' as OPEN_DATE from Dual Union
SELECT '768784'as COST_CENTER_CODE , 'BURNABY' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '40493' as OPEN_DATE from Dual Union
SELECT '768785'as COST_CENTER_CODE , 'OTTAWA-ORLEANS' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '40679' as OPEN_DATE from Dual Union
SELECT '768786'as COST_CENTER_CODE , 'LEVIS' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '40660' as OPEN_DATE from Dual Union
SELECT '768790'as COST_CENTER_CODE , 'MILTON' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '40529' as OPEN_DATE from Dual Union
SELECT '768791'as COST_CENTER_CODE , 'BELLEFEUILLE-ST JEROME' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '40541' as OPEN_DATE from Dual Union
SELECT '768792'as COST_CENTER_CODE , 'VICTORIA-DOWNTOWN' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '40625' as OPEN_DATE from Dual Union
SELECT '768793'as COST_CENTER_CODE , 'MASCOUCHE' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '40533' as OPEN_DATE from Dual Union
SELECT '768794'as COST_CENTER_CODE , 'BRAMPTON' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '40795' as OPEN_DATE from Dual Union
SELECT '768795'as COST_CENTER_CODE , 'SURREY-WHITE ROCK' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '40869' as OPEN_DATE from Dual Union
SELECT '768796'as COST_CENTER_CODE , 'KINGSTON' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '40868' as OPEN_DATE from Dual Union
SELECT '768797'as COST_CENTER_CODE , 'ABBOTSFORD-S FRASER' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '40842' as OPEN_DATE from Dual Union
SELECT '768804'as COST_CENTER_CODE , 'OTTAWA-KANATA' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '40891' as OPEN_DATE from Dual Union
SELECT '768806'as COST_CENTER_CODE , 'MISSISSAUGA-ERINDALE' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '40872' as OPEN_DATE from Dual Union
SELECT '768807'as COST_CENTER_CODE , 'TORONTO-KEELE ST' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '40897' as OPEN_DATE from Dual Union
SELECT '768808'as COST_CENTER_CODE , 'WINNIPEG-SOUTH' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '41017' as OPEN_DATE from Dual Union
SELECT '768809'as COST_CENTER_CODE , 'WHITBY-NORTH' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '41037' as OPEN_DATE from Dual Union
SELECT '768810'as COST_CENTER_CODE , 'KITCHENER-WEST' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '41081' as OPEN_DATE from Dual Union
SELECT '768811'as COST_CENTER_CODE , 'SASKATOON' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '41071' as OPEN_DATE from Dual Union
SELECT '768812'as COST_CENTER_CODE , 'OTTAWA-BANK STREET' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '41479' as OPEN_DATE from Dual Union
SELECT '768813'as COST_CENTER_CODE , 'TORONTO-SCARBOROUGH EAST' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '41179' as OPEN_DATE from Dual Union
SELECT '768815'as COST_CENTER_CODE , 'EAST GWILLIMBURY-NEWMARKET' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '41130' as OPEN_DATE from Dual Union
SELECT '768816'as COST_CENTER_CODE , 'LONDON-NORTH' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '41253' as OPEN_DATE from Dual Union
SELECT '768817'as COST_CENTER_CODE , 'BURNABY-NORTH' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '41264' as OPEN_DATE from Dual Union
SELECT '768818'as COST_CENTER_CODE , 'VAUGHAN' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '41242' as OPEN_DATE from Dual Union
SELECT '768819'as COST_CENTER_CODE , 'WATERDOWN' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '41234' as OPEN_DATE from Dual Union
SELECT '768820'as COST_CENTER_CODE , 'LONGUEUIL' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '41254' as OPEN_DATE from Dual Union
SELECT '768821'as COST_CENTER_CODE , 'SAINTE JULIE' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '41254' as OPEN_DATE from Dual Union
SELECT '768822'as COST_CENTER_CODE , 'WINNIPEG-CENTRAL' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '41260' as OPEN_DATE from Dual Union
SELECT '768823'as COST_CENTER_CODE , 'LOWER SACKVILLE-HALIFAX' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '41239' as OPEN_DATE from Dual Union
SELECT '768824'as COST_CENTER_CODE , 'COURTICE' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '41423' as OPEN_DATE from Dual Union
SELECT '768825'as COST_CENTER_CODE , 'MISSISSAUGA-DUNDAS' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '41572' as OPEN_DATE from Dual Union
SELECT '768826'as COST_CENTER_CODE , 'TORONTO-ETOBICOKE' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '41466' as OPEN_DATE from Dual Union
SELECT '768827'as COST_CENTER_CODE , 'ST THERESE' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '41653' as OPEN_DATE from Dual Union
SELECT '768828'as COST_CENTER_CODE , 'BELLEVILLE' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '41589' as OPEN_DATE from Dual Union
SELECT '768829'as COST_CENTER_CODE , 'MONCTON' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '41600' as OPEN_DATE from Dual Union
SELECT '768830'as COST_CENTER_CODE , 'MONTREAL-ST ANTOINE WEST' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '41820' as OPEN_DATE from Dual Union
SELECT '768831'as COST_CENTER_CODE , 'BRAMPTON-WEST' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '41643' as OPEN_DATE from Dual Union
SELECT '768832'as COST_CENTER_CODE , 'TORONTO-WILLOWDALE' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '41644' as OPEN_DATE from Dual Union
SELECT '768835'as COST_CENTER_CODE , 'QUEBEC CITY' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '41988' as OPEN_DATE from Dual Union
SELECT '768836'as COST_CENTER_CODE , 'LAVAL-WEST' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '42121' as OPEN_DATE from Dual Union
SELECT '768837'as COST_CENTER_CODE , 'BROSSARD' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '41982' as OPEN_DATE from Dual Union
SELECT '768838'as COST_CENTER_CODE , 'VILLE ST-LAURENT' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '41982' as OPEN_DATE from Dual Union
SELECT '768839'as COST_CENTER_CODE , 'ST EUSTACHE' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '41985' as OPEN_DATE from Dual Union
SELECT '768840'as COST_CENTER_CODE , 'LASALLE' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '41989' as OPEN_DATE from Dual Union
SELECT '768841'as COST_CENTER_CODE , 'MOUNT PEARL' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '42054' as OPEN_DATE from Dual Union
SELECT '768843'as COST_CENTER_CODE , 'ST JOHN''S' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '42219' as OPEN_DATE from Dual Union
SELECT '768844'as COST_CENTER_CODE , 'VAUDREUIL-DORION' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '42332' as OPEN_DATE from Dual Union
SELECT '768845'as COST_CENTER_CODE , 'ABBOTSFORD-RIVERSIDE' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '41760' as OPEN_DATE from Dual Union
SELECT '768846'as COST_CENTER_CODE , 'VANCOUVER-ARBUTUS' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '41760' as OPEN_DATE from Dual Union
SELECT '768849'as COST_CENTER_CODE , 'BRANDON' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '41760' as OPEN_DATE from Dual Union
SELECT '768850'as COST_CENTER_CODE , 'BURNABY' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '41760' as OPEN_DATE from Dual Union
SELECT '768851'as COST_CENTER_CODE , 'CALGARY COMMERCIAL' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '41760' as OPEN_DATE from Dual Union
SELECT '768852'as COST_CENTER_CODE , 'CALGARY CENTRAL' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '41760' as OPEN_DATE from Dual Union
SELECT '768853'as COST_CENTER_CODE , 'CALGARY HUNTERHORN' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '41760' as OPEN_DATE from Dual Union
SELECT '768854'as COST_CENTER_CODE , 'CALGARY NORTH' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '41760' as OPEN_DATE from Dual Union
SELECT '768855'as COST_CENTER_CODE , 'CALGARY NORTHEAST' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '41760' as OPEN_DATE from Dual Union
SELECT '768856'as COST_CENTER_CODE , 'CALGARY-RANCHLANDS' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '41760' as OPEN_DATE from Dual Union
SELECT '768857'as COST_CENTER_CODE , 'CALGARY-SOUTH' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '41760' as OPEN_DATE from Dual Union
SELECT '768858'as COST_CENTER_CODE , 'CAMBRIDGE BRANCH' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '41760' as OPEN_DATE from Dual Union
SELECT '768859'as COST_CENTER_CODE , 'CAMPBELL RIVER' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '41760' as OPEN_DATE from Dual Union
SELECT '768860'as COST_CENTER_CODE , 'CHILLIWACK' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '41760' as OPEN_DATE from Dual Union
SELECT '768861'as COST_CENTER_CODE , 'COQUITLAM' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '41760' as OPEN_DATE from Dual Union
SELECT '768862'as COST_CENTER_CODE , 'COURTENAY' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '41760' as OPEN_DATE from Dual Union
SELECT '768863'as COST_CENTER_CODE , 'CRANBROOK' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '41760' as OPEN_DATE from Dual Union
SELECT '768864'as COST_CENTER_CODE , 'TORONTO-FRONT ST' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '41760' as OPEN_DATE from Dual Union
SELECT '768865'as COST_CENTER_CODE , 'DUNCAN' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '41760' as OPEN_DATE from Dual Union
SELECT '768866'as COST_CENTER_CODE , 'EDMONTON' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '41760' as OPEN_DATE from Dual Union
SELECT '768867'as COST_CENTER_CODE , 'EDMONTON NORTH' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '41760' as OPEN_DATE from Dual Union
SELECT '768868'as COST_CENTER_CODE , 'EDMONTON-SE COMMERCIAL' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '41760' as OPEN_DATE from Dual Union
SELECT '768869'as COST_CENTER_CODE , 'EDMONTON SOUTHPOINT' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '41760' as OPEN_DATE from Dual Union
SELECT '768870'as COST_CENTER_CODE , 'EDMONTON WESTGATE' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '41760' as OPEN_DATE from Dual Union
SELECT '768871'as COST_CENTER_CODE , 'VANCOUVER COMMERCIAL' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '41760' as OPEN_DATE from Dual Union
SELECT '768872'as COST_CENTER_CODE , 'FLEETWOOD' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '41760' as OPEN_DATE from Dual Union
SELECT '768873'as COST_CENTER_CODE , 'FORT MCMURRAY' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '41760' as OPEN_DATE from Dual Union
SELECT '768874'as COST_CENTER_CODE , 'GOLDSTREAM' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '41760' as OPEN_DATE from Dual Union
SELECT '768875'as COST_CENTER_CODE , 'GRANDE PRAIRIE' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '41760' as OPEN_DATE from Dual Union
SELECT '768876'as COST_CENTER_CODE , 'HAMILTON-UPPER OTTAWA' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '41760' as OPEN_DATE from Dual Union
SELECT '768877'as COST_CENTER_CODE , 'KAMLOOPS' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '41760' as OPEN_DATE from Dual Union
SELECT '768878'as COST_CENTER_CODE , 'KELOWNA' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '41760' as OPEN_DATE from Dual Union
SELECT '768879'as COST_CENTER_CODE , 'LANGLEY' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '41760' as OPEN_DATE from Dual Union
SELECT '768880'as COST_CENTER_CODE , 'LETHBRIDGE' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '41760' as OPEN_DATE from Dual Union
SELECT '768881'as COST_CENTER_CODE , 'LLOYDMINSTER' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '41760' as OPEN_DATE from Dual Union
SELECT '768882'as COST_CENTER_CODE , 'LONDON-STANELY ST' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '41760' as OPEN_DATE from Dual Union
SELECT '768883'as COST_CENTER_CODE , 'LONDON SOUTH' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '41760' as OPEN_DATE from Dual Union
SELECT '768884'as COST_CENTER_CODE , 'MAPLE RIDGE' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '41760' as OPEN_DATE from Dual Union
SELECT '768886'as COST_CENTER_CODE , 'MISSISSAUGA-RIDGEWAY' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '41760' as OPEN_DATE from Dual Union
SELECT '768887'as COST_CENTER_CODE , 'MONTREAL-ST LAURENT' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '41760' as OPEN_DATE from Dual Union
SELECT '768888'as COST_CENTER_CODE , 'MOOSE JAW' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '41760' as OPEN_DATE from Dual Union
SELECT '768889'as COST_CENTER_CODE , 'NANAIMO' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '41760' as OPEN_DATE from Dual Union
SELECT '768890'as COST_CENTER_CODE , 'NEW WESTMINSTER' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '41760' as OPEN_DATE from Dual Union
SELECT '768892'as COST_CENTER_CODE , 'NORTH VANCOUVER-MARINE DR' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '41760' as OPEN_DATE from Dual Union
SELECT '768893'as COST_CENTER_CODE , 'PENTICTON' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '41760' as OPEN_DATE from Dual Union
SELECT '768894'as COST_CENTER_CODE , 'PICKERING' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '41760' as OPEN_DATE from Dual Union
SELECT '768896'as COST_CENTER_CODE , 'PRINCE ALBERT' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '41760' as OPEN_DATE from Dual Union
SELECT '768897'as COST_CENTER_CODE , 'PRINCE GEORGE' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '41760' as OPEN_DATE from Dual Union
SELECT '768901'as COST_CENTER_CODE , 'PRINCE RUPERT' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '41760' as OPEN_DATE from Dual Union
SELECT '768903'as COST_CENTER_CODE , 'RED DEER' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '41760' as OPEN_DATE from Dual Union
SELECT '768904'as COST_CENTER_CODE , 'REGINA COMMERCIAL' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '41760' as OPEN_DATE from Dual Union
SELECT '768905'as COST_CENTER_CODE , 'REGINA EAST' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '41760' as OPEN_DATE from Dual Union
SELECT '768906'as COST_CENTER_CODE , 'ETOBICOKE-REXDALE' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '41760' as OPEN_DATE from Dual Union
SELECT '768907'as COST_CENTER_CODE , 'RICHMOND HILL' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '41760' as OPEN_DATE from Dual Union
SELECT '768908'as COST_CENTER_CODE , 'RICHMOND SOUTH' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '41760' as OPEN_DATE from Dual Union
SELECT '768909'as COST_CENTER_CODE , 'SARNIA' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '41760' as OPEN_DATE from Dual Union
SELECT '768910'as COST_CENTER_CODE , 'SASKATOON' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '41760' as OPEN_DATE from Dual Union
SELECT '768911'as COST_CENTER_CODE , 'SASKATOON-EAST' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '41760' as OPEN_DATE from Dual Union
SELECT '768913'as COST_CENTER_CODE , 'SHERWOOD PARK' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '41760' as OPEN_DATE from Dual Union
SELECT '768914'as COST_CENTER_CODE , 'ST ALBERT' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '41760' as OPEN_DATE from Dual Union
SELECT '768916'as COST_CENTER_CODE , 'WINNIPEG-ST VITAL' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '41760' as OPEN_DATE from Dual Union
SELECT '768917'as COST_CENTER_CODE , 'RICHMOND' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '41760' as OPEN_DATE from Dual Union
SELECT '768918'as COST_CENTER_CODE , 'SURREY-CENTRAL' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '41760' as OPEN_DATE from Dual Union
SELECT '768919'as COST_CENTER_CODE , 'SURREY-DELTA' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '41760' as OPEN_DATE from Dual Union
SELECT '768920'as COST_CENTER_CODE , 'THUNDER BAY' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '41760' as OPEN_DATE from Dual Union
SELECT '768921'as COST_CENTER_CODE , 'VERNON' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '41760' as OPEN_DATE from Dual Union
SELECT '768922'as COST_CENTER_CODE , 'VICTORIA COMMERCIAL' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '41760' as OPEN_DATE from Dual Union
SELECT '768923'as COST_CENTER_CODE , 'VANCOUVER-VICTORIA DR' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '41760' as OPEN_DATE from Dual Union
SELECT '768924'as COST_CENTER_CODE , 'VICTORIA-GORDON HEAD' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '41760' as OPEN_DATE from Dual Union
SELECT '768925'as COST_CENTER_CODE , 'WATERLOO' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '41760' as OPEN_DATE from Dual Union
SELECT '768926'as COST_CENTER_CODE , 'WEST KELOWNA' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '41760' as OPEN_DATE from Dual Union
SELECT '768930'as COST_CENTER_CODE , 'WINNIPEG COMMERCIAL' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '41760' as OPEN_DATE from Dual Union
SELECT '768931'as COST_CENTER_CODE , 'WINNIPEG EAST' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '41760' as OPEN_DATE from Dual Union
SELECT '768935'as COST_CENTER_CODE , 'HALIFAX-BAYER''S LAKE' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '42275' as OPEN_DATE from Dual Union
SELECT '768936'as COST_CENTER_CODE , 'BRAMPTON-COMMERCIAL' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '42305' as OPEN_DATE from Dual Union
SELECT '768937'as COST_CENTER_CODE , 'MONTREAL-COMMERCIAL' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '42359' as OPEN_DATE from Dual Union
SELECT '768938'as COST_CENTER_CODE , 'RED DEER-NORTH-COMMERCIAL' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '42338' as OPEN_DATE from Dual Union
SELECT '768940'as COST_CENTER_CODE , 'SAINT JOHN' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '42307' as OPEN_DATE from Dual Union
SELECT '768941'as COST_CENTER_CODE , 'SHERBROOKE' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '42321' as OPEN_DATE from Dual Union
SELECT '768942'as COST_CENTER_CODE , 'TORONTO-DANFORTH' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '42359' as OPEN_DATE from Dual Union
SELECT '768943'as COST_CENTER_CODE , 'MARKHAM-SOUTH' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '42472' as OPEN_DATE from Dual Union
SELECT '768944'as COST_CENTER_CODE , 'SCARBOROUGH-GOLDEN MILE' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '42349' as OPEN_DATE from Dual Union
SELECT '768945'as COST_CENTER_CODE , 'FREDERICTON-NORTH' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '42445' as OPEN_DATE from Dual Union
SELECT '768946'as COST_CENTER_CODE , 'L''ANCIENNE-LORETTE-QUEBEC CITY' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '42494' as OPEN_DATE from Dual Union
SELECT '768947'as COST_CENTER_CODE , 'WHITBY' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '42548' as OPEN_DATE from Dual Union
SELECT '768948'as COST_CENTER_CODE , 'DOLLARD-DES-ORMEAUX' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '42499' as OPEN_DATE from Dual Union
SELECT '768953'as COST_CENTER_CODE , 'WINDSOR' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '42538' as OPEN_DATE from Dual Union
SELECT '771493'as COST_CENTER_CODE , 'MONCTON-PRODUCT FINISHES' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '42646' as OPEN_DATE from Dual Union
SELECT '771494'as COST_CENTER_CODE , 'LONDON-PRODUCT FINISHES' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '42646' as OPEN_DATE from Dual Union
SELECT '778703'as COST_CENTER_CODE , 'BRAMPTON PF' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '33415' as OPEN_DATE from Dual Union
SELECT '778716'as COST_CENTER_CODE , 'MONTREAL-NORD' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '34360' as OPEN_DATE from Dual Union
SELECT '778718'as COST_CENTER_CODE , 'LANGLEY-VANCOUVER FACILITY' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '34660' as OPEN_DATE from Dual Union
SELECT '778737'as COST_CENTER_CODE , 'WINNIPEG-PRODUCT FINISHES' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '37652' as OPEN_DATE from Dual Union
SELECT '778739'as COST_CENTER_CODE , 'CALGARY PRODUCT FINISHES' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '37526' as OPEN_DATE from Dual Union
SELECT '778842'as COST_CENTER_CODE , 'WINNIPEG-PF LARGE EQUIPMENT ' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '42123' as OPEN_DATE from Dual Union
SELECT '779001'as COST_CENTER_CODE , 'AUTO SCARBOROUGH' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '38869' as OPEN_DATE from Dual Union
SELECT '779002'as COST_CENTER_CODE , 'AUTO MISSISSAUGA' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '38869' as OPEN_DATE from Dual Union
SELECT '779003'as COST_CENTER_CODE , 'AUTO CALGARY' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '38869' as OPEN_DATE from Dual Union
SELECT '779004'as COST_CENTER_CODE , 'AUTO SAINT CATHERINE' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '38869' as OPEN_DATE from Dual Union
SELECT '779005'as COST_CENTER_CODE , 'AUTO LANGLEY' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '38869' as OPEN_DATE from Dual Union
SELECT '779007'as COST_CENTER_CODE , 'AUTO LONDON' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '38869' as OPEN_DATE from Dual Union
SELECT '779008'as COST_CENTER_CODE , '01/18 AUTO VICTORIA' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '41334' as OPEN_DATE from Dual Union
SELECT '779009'as COST_CENTER_CODE , 'AUTO KITCHENER' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '38869' as OPEN_DATE from Dual Union
SELECT '779010'as COST_CENTER_CODE , 'AUTO DARTMOUTH' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '38869' as OPEN_DATE from Dual Union
SELECT '779011'as COST_CENTER_CODE , 'AUTO EDMONTON' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '38869' as OPEN_DATE from Dual Union
SELECT '779012'as COST_CENTER_CODE , 'AUTO HAMILTON' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '38869' as OPEN_DATE from Dual Union
SELECT '779015'as COST_CENTER_CODE , 'AUTO VILLE D''ANJOU' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '38869' as OPEN_DATE from Dual Union
SELECT '779016'as COST_CENTER_CODE , 'AUTO REGINA' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '42023' as OPEN_DATE from Dual Union
SELECT '779018'as COST_CENTER_CODE , 'AUTO QUEBEC CITY' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '42360' as OPEN_DATE from Dual Union
SELECT '779022'as COST_CENTER_CODE , 'AUTO WINNIPEG' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '40140' as OPEN_DATE from Dual Union
SELECT '779024'as COST_CENTER_CODE , 'AUTO OTTAWA' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '39713' as OPEN_DATE from Dual Union
SELECT '779026'as COST_CENTER_CODE , 'AUTO BARRIE' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '38869' as OPEN_DATE from Dual Union
SELECT '779029'as COST_CENTER_CODE , 'AUTO ST HYACINTHE' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '38869' as OPEN_DATE from Dual Union
SELECT '779081'as COST_CENTER_CODE , 'AUTO MONCTON' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'CAN' as COUNTRY_CODE , '39090' as OPEN_DATE from Dual Union
SELECT '791431'as COST_CENTER_CODE , 'ELKHART FACILITY' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'USA' as COUNTRY_CODE , '40665' as OPEN_DATE from Dual Union
SELECT '792760'as COST_CENTER_CODE , 'PF FINANCIAL SERVICES POS' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'USA' as COUNTRY_CODE , '38175' as OPEN_DATE from Dual Union
SELECT '799162'as COST_CENTER_CODE , 'AUTO CHERRY HILL' as COST_CENTER_NAME , 'P' as POLLING_STATUS_CODE , 'S' as CATEGORY , 'USA' as COUNTRY_CODE , '39419' as OPEN_DATE from Dual
) LOOP

    INSERT INTO TEMP_DEP_TICK_EXCLUDED VALUES(rec.COST_CENTER_CODE, rec.COST_CENTER_NAME, rec.POLLING_STATUS_CODE, rec.CATEGORY, rec.COUNTRY_CODE, rec.OPEN_DATE);
END LOOP;
-- Commit the complete transaction
COMMIT;
END;
/
SELECT * FROM TEMP_DEP_TICK_EXCLUDED;