/*
Created : 01/18/2017 nxk927 CCN Project Team....
          This script will delete all the concertration from the
          banking which are not present in the cost center database

*/
SET SERVEROUTPUT ON;
DECLARE
BEGIN
   FOR REC IN (SELECT *
                 FROM MEMBER_BANK_CC
                WHERE SUBSTR(MEMBER_STORE_NBR,3) NOT IN (SELECT SUBSTR(COST_CENTER_CODE,3)
                                                           FROM COST_CENTER)) LOOP
       DELETE FROM STORE_MICR_FORMAT_DTLS WHERE COST_CENTER_CODE = REC.MEMBER_STORE_NBR;
       DELETE FROM STORE_MICR_FORMAT_DTLS_FUTURE WHERE COST_CENTER_CODE = REC.MEMBER_STORE_NBR;
       DELETE FROM BANK_DEP_TICKORD WHERE COST_CENTER_CODE = REC.MEMBER_STORE_NBR;
       DELETE FROM BANK_DEP_TICKORD_FUTURE WHERE COST_CENTER_CODE = REC.MEMBER_STORE_NBR;
       DELETE FROM BANK_DEP_BAG_TICKORD WHERE COST_CENTER_CODE = REC.MEMBER_STORE_NBR;
       DELETE FROM BANK_DEP_BAG_TICKORD_FUTURE WHERE COST_CENTER_CODE = REC.MEMBER_STORE_NBR;
       DELETE FROM BANK_DEP_TICK WHERE COST_CENTER_CODE = REC.MEMBER_STORE_NBR;
       DELETE FROM BANK_DEP_TICK_FUTURE WHERE COST_CENTER_CODE = REC.MEMBER_STORE_NBR;
       DELETE FROM BANK_DEP_BAG_TICK WHERE COST_CENTER_CODE = REC.MEMBER_STORE_NBR;
       DELETE FROM BANK_DEP_BAG_TICK_FUTURE WHERE COST_CENTER_CODE = REC.MEMBER_STORE_NBR;
       DELETE FROM MEMBER_BANK_CC WHERE MEMBER_STORE_NBR = REC.MEMBER_STORE_NBR;
       DELETE FROM MEMBER_BANK_CC_FUTURE WHERE MEMBER_STORE_NBR = REC.MEMBER_STORE_NBR;
   END LOOP;
COMMIT;
END;

/


ALTER TRIGGER TR_MEMBER_BANK_CC_UPD DISABLE;

UPDATE MEMBER_BANK_CC
   SET MEMBER_STORE_NBR = '768945'
   where MEMBER_STORE_NBR ='8945';

COMMIT;
ALTER TRIGGER TR_MEMBER_BANK_CC_UPD ENABLE;
/