/*
created : 08/09/2018 sxg151 update PRIME_SUB
*/

SELECT * FROM PRIME_SUB_DETAIL WHERE TCODE = '2997' AND DB_CR_CODE = 'OD';

UPDATE PRIME_SUB_DETAIL
   SET PRIME_SUB  = '7405004'
 WHERE TCODE      = '2997' 
   AND DB_CR_CODE = 'OD';   

COMMIT;

SELECT * FROM PRIME_SUB_DETAIL WHERE TCODE = '2997' AND DB_CR_CODE = 'OD';