/* 
This script will cleanup the customer account numbers 426790507, 298895327, 520501818 ,297615460,309739944 (as per chris greve email (12/28/2016 >> 01/04/2017))
from the store_drafts and store_drafts_detail tables.
Created : 01/04/2017 nxk927 CCN Project Team....
*/
SELECT * FROM STORE_DRAFTS_DETAIL WHERE  (COST_CENTER_CODE,CHECK_SERIAL_NUMBER,TRANSACTION_DATE)
IN (SELECT COST_CENTER_CODE,CHECK_SERIAL_NUMBER,TRANSACTION_DATE FROM STORE_DRAFTS WHERE CUSTOMER_ACCOUNT_NUMBER IN ('426790507'));
--1 Row Selected
DELETE FROM STORE_DRAFTS_DETAIL WHERE  (COST_CENTER_CODE,CHECK_SERIAL_NUMBER,TRANSACTION_DATE)
IN (SELECT COST_CENTER_CODE,CHECK_SERIAL_NUMBER,TRANSACTION_DATE FROM STORE_DRAFTS WHERE CUSTOMER_ACCOUNT_NUMBER IN ('426790507'));
--1 Row Deleted
SELECT * FROM STORE_DRAFTS WHERE CUSTOMER_ACCOUNT_NUMBER IN ('426790507');
--1 Row Selected
DELETE FROM STORE_DRAFTS WHERE CUSTOMER_ACCOUNT_NUMBER IN ('426790507');
--1 Row Deleted

SELECT * FROM STORE_DRAFTS_DETAIL WHERE  (COST_CENTER_CODE,CHECK_SERIAL_NUMBER,TRANSACTION_DATE)
IN (SELECT COST_CENTER_CODE,CHECK_SERIAL_NUMBER,TRANSACTION_DATE FROM STORE_DRAFTS WHERE CUSTOMER_ACCOUNT_NUMBER IN ('298895327'));
--1 Row Selected
DELETE  FROM STORE_DRAFTS_DETAIL WHERE  (COST_CENTER_CODE,CHECK_SERIAL_NUMBER,TRANSACTION_DATE)
IN (SELECT COST_CENTER_CODE,CHECK_SERIAL_NUMBER,TRANSACTION_DATE FROM STORE_DRAFTS WHERE CUSTOMER_ACCOUNT_NUMBER IN ('298895327'));
--1 Row Deleted
SELECT * FROM STORE_DRAFTS WHERE CUSTOMER_ACCOUNT_NUMBER IN ('298895327');
--1 Row Selected
DELETE FROM STORE_DRAFTS WHERE CUSTOMER_ACCOUNT_NUMBER IN ('298895327');
--1 Row Deleted

SELECT * FROM STORE_DRAFTS_DETAIL WHERE  (COST_CENTER_CODE,CHECK_SERIAL_NUMBER,TRANSACTION_DATE)
IN (SELECT COST_CENTER_CODE,CHECK_SERIAL_NUMBER,TRANSACTION_DATE FROM STORE_DRAFTS WHERE CUSTOMER_ACCOUNT_NUMBER IN ('520501818'));
--1 Row Selected
DELETE FROM STORE_DRAFTS_DETAIL WHERE  (COST_CENTER_CODE,CHECK_SERIAL_NUMBER,TRANSACTION_DATE)
IN (SELECT COST_CENTER_CODE,CHECK_SERIAL_NUMBER,TRANSACTION_DATE FROM STORE_DRAFTS WHERE CUSTOMER_ACCOUNT_NUMBER IN ('520501818'));
--1 Row Deleted
SELECT * FROM STORE_DRAFTS WHERE CUSTOMER_ACCOUNT_NUMBER IN ('520501818');
--1 Row Selected
DELETE FROM STORE_DRAFTS WHERE CUSTOMER_ACCOUNT_NUMBER IN ('520501818');
--1 Row Deleted


SELECT * FROM STORE_DRAFTS_DETAIL WHERE  (COST_CENTER_CODE,CHECK_SERIAL_NUMBER,TRANSACTION_DATE)
IN (SELECT COST_CENTER_CODE,CHECK_SERIAL_NUMBER,TRANSACTION_DATE FROM STORE_DRAFTS WHERE CUSTOMER_ACCOUNT_NUMBER IN ('297615460'));
--1 Row Selected
DELETE FROM STORE_DRAFTS_DETAIL WHERE  (COST_CENTER_CODE,CHECK_SERIAL_NUMBER,TRANSACTION_DATE)
IN (SELECT COST_CENTER_CODE,CHECK_SERIAL_NUMBER,TRANSACTION_DATE FROM STORE_DRAFTS WHERE CUSTOMER_ACCOUNT_NUMBER IN ('297615460'));
--1 Row Deleted
SELECT * FROM STORE_DRAFTS WHERE CUSTOMER_ACCOUNT_NUMBER IN ('297615460');
--1 Row Selected
DELETE FROM STORE_DRAFTS WHERE CUSTOMER_ACCOUNT_NUMBER IN ('297615460');
--1 Row Deleted

SELECT * FROM STORE_DRAFTS_DETAIL WHERE  (COST_CENTER_CODE,CHECK_SERIAL_NUMBER,TRANSACTION_DATE)
IN (SELECT COST_CENTER_CODE,CHECK_SERIAL_NUMBER,TRANSACTION_DATE FROM STORE_DRAFTS WHERE CUSTOMER_ACCOUNT_NUMBER IN ('309739944'));
--1 Row Selected
DELETE FROM STORE_DRAFTS_DETAIL WHERE  (COST_CENTER_CODE,CHECK_SERIAL_NUMBER,TRANSACTION_DATE)
IN (SELECT COST_CENTER_CODE,CHECK_SERIAL_NUMBER,TRANSACTION_DATE FROM STORE_DRAFTS WHERE CUSTOMER_ACCOUNT_NUMBER IN ('309739944'));
--1 Row Deleted
SELECT * FROM STORE_DRAFTS WHERE CUSTOMER_ACCOUNT_NUMBER IN ('309739944');
--1 Row Selected
DELETE FROM STORE_DRAFTS WHERE CUSTOMER_ACCOUNT_NUMBER IN ('309739944');
--1 Row Deleted

COMMIT;