/*---------------------------------------
Below script will manually mark the drafts as paid as per email sent by Christopher T. Greve
(Not to be sent to the Bank as maintenance)

--MARK AS PAID
Store	Draft	Paid Date
708061	2104-2	1/30/2017
702263	6328-1	1/11/2017
701171	1405-8	1/10/2017
702604	1110-3	1/3/2017
708058	1729-3	3/22/2017
701911	2213-4	3/14/2017

--REMOVE STOP AND MARK AS PAID
Store	Draft	Paid Date
705272	7472-4	1/12/2017
707046	3411-2	1/25/2017
701301	1600-7	1/3/2017
702296	1570-3	1/17/2017
707166	1442-5	1/20/2017
708596	1484-4	1/3/2017
705030	2358-2	1/4/2017
702263	6139-2	1/3/2017
708596	1520-5	3/1/2017

Created: 04/11/2017 sxh487
------------------------------------------*/

-- MARK AS PAID
   
SELECT * FROM STORE_DRAFTS WHERE COST_CENTER_CODE = '708061' AND CHECK_SERIAL_NUMBER = '0806121042';
UPDATE STORE_DRAFTS 
   SET PAID_DATE = '30-JAN-2017', 
       PAY_INDICATOR = 'Y', 
       BANK_PAID_AMOUNT = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT), 
       GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT), 
       NET_AMOUNT = NVL(NET_AMOUNT, ORIGINAL_NET_AMOUNT) 
 WHERE COST_CENTER_CODE = '708061' 
   AND CHECK_SERIAL_NUMBER = '0806121042';

SELECT * FROM STORE_DRAFTS WHERE COST_CENTER_CODE = '702263' AND CHECK_SERIAL_NUMBER = '0226363281';
UPDATE STORE_DRAFTS SET PAID_DATE = '11-JAN-2017', 
       PAY_INDICATOR = 'Y', 
       BANK_PAID_AMOUNT = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT), 
       GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT), 
       NET_AMOUNT = NVL(NET_AMOUNT, ORIGINAL_NET_AMOUNT)  
 WHERE COST_CENTER_CODE = '702263' 
   AND CHECK_SERIAL_NUMBER = '0226363281';

SELECT * FROM STORE_DRAFTS WHERE COST_CENTER_CODE = '701171' AND CHECK_SERIAL_NUMBER = '0117114058';
UPDATE STORE_DRAFTS 
   SET PAID_DATE = '10-JAN-2017', 
       PAY_INDICATOR = 'Y',
       BANK_PAID_AMOUNT = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT), 
       GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT), 
       NET_AMOUNT = NVL(NET_AMOUNT, ORIGINAL_NET_AMOUNT) 
 WHERE COST_CENTER_CODE = '701171' 
   AND CHECK_SERIAL_NUMBER = '0117114058';

SELECT * FROM STORE_DRAFTS WHERE COST_CENTER_CODE = '702604' AND CHECK_SERIAL_NUMBER = '0260411103';
UPDATE STORE_DRAFTS 
   SET PAID_DATE = '03-JAN-2017', 
       PAY_INDICATOR = 'Y', 
       BANK_PAID_AMOUNT = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT), 
       GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT), 
       NET_AMOUNT = NVL(NET_AMOUNT, ORIGINAL_NET_AMOUNT)  
 WHERE COST_CENTER_CODE = '702604' 
   AND CHECK_SERIAL_NUMBER = '0260411103';

SELECT * FROM STORE_DRAFTS WHERE COST_CENTER_CODE = '708058' AND CHECK_SERIAL_NUMBER = '0805817293';
UPDATE STORE_DRAFTS 
   SET PAID_DATE = '22-MAR-2017', 
       PAY_INDICATOR = 'Y', 
       BANK_PAID_AMOUNT = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT), 
       GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT), 
       NET_AMOUNT = NVL(NET_AMOUNT, ORIGINAL_NET_AMOUNT)  
 WHERE COST_CENTER_CODE = '708058' 
   AND CHECK_SERIAL_NUMBER = '0805817293';

SELECT * FROM STORE_DRAFTS WHERE COST_CENTER_CODE = '701911' AND CHECK_SERIAL_NUMBER = '0191122134';
UPDATE STORE_DRAFTS 
   SET PAID_DATE = '14-MAR-2017', 
       PAY_INDICATOR = 'Y', 
       BANK_PAID_AMOUNT = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT), 
       GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT), 
       NET_AMOUNT = NVL(NET_AMOUNT, ORIGINAL_NET_AMOUNT)  
 WHERE COST_CENTER_CODE = '701911' 
   AND CHECK_SERIAL_NUMBER = '0191122134';

-- REMOVE STOP DATE AND MARK AS PAID
   
SELECT * FROM STORE_DRAFTS WHERE COST_CENTER_CODE = '705272' AND CHECK_SERIAL_NUMBER = '0527274724';
UPDATE STORE_DRAFTS 
   SET PAID_DATE = '12-JAN-2017', 
       PAY_INDICATOR = 'Y', 
       STOP_INDICATOR = 'N',
       OPEN_INDICATOR = 'Y',
       STOP_PAY_MARKED_BY_CCN_IND = NULL,
       BANK_PAID_AMOUNT = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT), 
       GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT), 
       NET_AMOUNT = NVL(NET_AMOUNT, ORIGINAL_NET_AMOUNT),
       STOP_PAY_DATE = NULL
 WHERE COST_CENTER_CODE = '705272' 
   AND CHECK_SERIAL_NUMBER = '0527274724';

SELECT * FROM STORE_DRAFTS WHERE COST_CENTER_CODE = '707046' AND CHECK_SERIAL_NUMBER = '0704634112';
UPDATE STORE_DRAFTS 
   SET PAID_DATE = '25-JAN-2017', 
       PAY_INDICATOR = 'Y', 
       STOP_INDICATOR = 'N',
       OPEN_INDICATOR = 'Y',
       STOP_PAY_MARKED_BY_CCN_IND = NULL,
       BANK_PAID_AMOUNT = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT), 
       GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT), 
       NET_AMOUNT = NVL(NET_AMOUNT, ORIGINAL_NET_AMOUNT),
       STOP_PAY_DATE = NULL
 WHERE COST_CENTER_CODE = '707046' 
   AND CHECK_SERIAL_NUMBER = '0704634112';

SELECT * FROM STORE_DRAFTS WHERE COST_CENTER_CODE = '701301' AND CHECK_SERIAL_NUMBER = '0130116007';
UPDATE STORE_DRAFTS 
   SET PAID_DATE = '03-JAN-2017', 
       PAY_INDICATOR = 'Y', 
       STOP_INDICATOR = 'N',
       OPEN_INDICATOR = 'Y',
       STOP_PAY_MARKED_BY_CCN_IND = NULL,
       BANK_PAID_AMOUNT = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT), 
       GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT), 
       NET_AMOUNT = NVL(NET_AMOUNT, ORIGINAL_NET_AMOUNT),
       STOP_PAY_DATE = NULL
 WHERE COST_CENTER_CODE = '701301' 
   AND CHECK_SERIAL_NUMBER = '0130116007';

SELECT * FROM STORE_DRAFTS WHERE COST_CENTER_CODE = '702296' AND CHECK_SERIAL_NUMBER = '0229615703';
UPDATE STORE_DRAFTS 
   SET PAID_DATE = '17-JAN-2017', 
       PAY_INDICATOR = 'Y', 
       STOP_INDICATOR = 'N',
       OPEN_INDICATOR = 'Y',
       STOP_PAY_MARKED_BY_CCN_IND = NULL,
       BANK_PAID_AMOUNT = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT), 
       GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT), 
       NET_AMOUNT = NVL(NET_AMOUNT, ORIGINAL_NET_AMOUNT),
       STOP_PAY_DATE = NULL
 WHERE COST_CENTER_CODE = '702296' 
   AND CHECK_SERIAL_NUMBER = '0229615703';
   
SELECT * FROM STORE_DRAFTS WHERE COST_CENTER_CODE = '707166' AND CHECK_SERIAL_NUMBER = '0716614425';
UPDATE STORE_DRAFTS 
   SET PAID_DATE = '20-JAN-2017', 
       PAY_INDICATOR = 'Y', 
       STOP_INDICATOR = 'N',
       OPEN_INDICATOR = 'Y',
       STOP_PAY_MARKED_BY_CCN_IND = NULL,
       BANK_PAID_AMOUNT = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT), 
       GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT), 
       NET_AMOUNT = NVL(NET_AMOUNT, ORIGINAL_NET_AMOUNT),
       STOP_PAY_DATE = NULL
 WHERE COST_CENTER_CODE = '707166' 
   AND CHECK_SERIAL_NUMBER = '0716614425';
   
SELECT * FROM STORE_DRAFTS WHERE COST_CENTER_CODE = '708596' AND CHECK_SERIAL_NUMBER = '0859614844';
UPDATE STORE_DRAFTS 
   SET PAID_DATE = '03-JAN-2017', 
       PAY_INDICATOR = 'Y', 
       STOP_INDICATOR = 'N',
       OPEN_INDICATOR = 'Y',
       STOP_PAY_MARKED_BY_CCN_IND = NULL,
       BANK_PAID_AMOUNT = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT), 
       GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT), 
       NET_AMOUNT = NVL(NET_AMOUNT, ORIGINAL_NET_AMOUNT),
       STOP_PAY_DATE = NULL
 WHERE COST_CENTER_CODE = '708596' 
   AND CHECK_SERIAL_NUMBER = '0859614844';
   
SELECT * FROM STORE_DRAFTS WHERE COST_CENTER_CODE = '705030' AND CHECK_SERIAL_NUMBER = '0503023582';
UPDATE STORE_DRAFTS 
   SET PAID_DATE = '04-JAN-2017', 
       PAY_INDICATOR = 'Y', 
       STOP_INDICATOR = 'N',
       OPEN_INDICATOR = 'Y',
       STOP_PAY_MARKED_BY_CCN_IND = NULL,
       BANK_PAID_AMOUNT = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT), 
       GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT), 
       NET_AMOUNT = NVL(NET_AMOUNT, ORIGINAL_NET_AMOUNT),
       STOP_PAY_DATE = NULL
 WHERE COST_CENTER_CODE = '705030' 
   AND CHECK_SERIAL_NUMBER = '0503023582';
   
SELECT * FROM STORE_DRAFTS WHERE COST_CENTER_CODE = '702263' AND CHECK_SERIAL_NUMBER = '0226361392';
UPDATE STORE_DRAFTS 
   SET PAID_DATE = '03-JAN-2017', 
       PAY_INDICATOR = 'Y',
       STOP_INDICATOR = 'N',
       OPEN_INDICATOR = 'Y',
       STOP_PAY_MARKED_BY_CCN_IND = NULL,
       BANK_PAID_AMOUNT = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT), 
       GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT), 
       NET_AMOUNT = NVL(NET_AMOUNT, ORIGINAL_NET_AMOUNT),
       STOP_PAY_DATE = NULL
 WHERE COST_CENTER_CODE = '702263' 
   AND CHECK_SERIAL_NUMBER = '0226361392';
   
SELECT * FROM STORE_DRAFTS WHERE COST_CENTER_CODE = '708596' AND CHECK_SERIAL_NUMBER = '0859615205';
UPDATE STORE_DRAFTS 
   SET PAID_DATE = '01-MAR-2017', 
       PAY_INDICATOR = 'Y', 
       STOP_INDICATOR = 'N',
       OPEN_INDICATOR = 'Y',
       STOP_PAY_MARKED_BY_CCN_IND = NULL,
       BANK_PAID_AMOUNT = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT), 
       GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT), 
       NET_AMOUNT = NVL(NET_AMOUNT, ORIGINAL_NET_AMOUNT),
       STOP_PAY_DATE = NULL
 WHERE COST_CENTER_CODE = '708596' 
   AND CHECK_SERIAL_NUMBER = '0859615205';   
   
COMMIT;