/*
Below script will update the store drafts to be marked as paid
CREATED : 04/25/2018 nxk927
          0812910065 on 03/19/2018 8058-1983-6 paid on 3/14/18 and 2845-6672-6 paid on 3/13/18.
*/


--This has a pay indicator marked as Y
SELECT * FROM STORE_DRAFTS WHERE CHECK_SERIAL_NUMBER = '0812910065';


UPDATE STORE_DRAFTS
   SET PAID_DATE = '19-MAR-2018',
       BANK_PAID_AMOUNT = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT), 
       GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT), 
       NET_AMOUNT = NVL(NET_AMOUNT, ORIGINAL_NET_AMOUNT)
WHERE CHECK_SERIAL_NUMBER = '0812910065';


SELECT * FROM STORE_DRAFTS WHERE CHECK_SERIAL_NUMBER = '0805819836';
--This has a stop_paid_indicator and stop_paid_date
UPDATE STORE_DRAFTS
   SET PAID_DATE = '14-MAR-2018',
       PAY_INDICATOR = 'Y', 
       STOP_INDICATOR = 'N',
       OPEN_INDICATOR = 'Y',
       STOP_PAY_DATE = NULL,
       BANK_PAID_AMOUNT = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT), 
       GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT), 
       NET_AMOUNT = NVL(NET_AMOUNT, ORIGINAL_NET_AMOUNT)
WHERE CHECK_SERIAL_NUMBER = '0805819836';

SELECT * FROM STORE_DRAFTS WHERE CHECK_SERIAL_NUMBER = '0284566726';

UPDATE STORE_DRAFTS
   SET PAID_DATE = '13-MAR-2018',
       PAY_INDICATOR = 'Y', 
       BANK_PAID_AMOUNT = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT), 
       GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT), 
       NET_AMOUNT = NVL(NET_AMOUNT, ORIGINAL_NET_AMOUNT)
WHERE CHECK_SERIAL_NUMBER = '0284566726';


COMMIT;
