/*
Below script will update the store drafts 10065 associated with store 768129 with the amount paid was $295.93. 
CREATED : 04/25/2018 nxk927
   
*/


--This has a pay indicator marked as Y
SELECT * FROM STORE_DRAFTS WHERE CHECK_SERIAL_NUMBER = '0812910065';


UPDATE STORE_DRAFTS 
   SET PAID_DATE = '19-MAR-2018',
       BANK_PAID_AMOUNT = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT), 
       GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT), 
       NET_AMOUNT = NVL(NET_AMOUNT, ORIGINAL_NET_AMOUNT)
WHERE CHECK_SERIAL_NUMBER = '0812910065';

COMMIT;
