/*---------------------------------------
Below script will manually mark the drafts as paid as per email sent by Mary F. Kirkpatrick

--REMOVE STOP AND MARK AS PAID
Store	Draft	Paid Date
703154	1787-3	7/18/17

Created: 04/27/2017 sxg151
------------------------------------------*/

-- REMOVE STOP DATE AND MARK AS PAID

SELECT * FROM STORE_DRAFTS WHERE COST_CENTER_CODE = '703154' AND CHECK_SERIAL_NUMBER = '0315417873';
UPDATE STORE_DRAFTS 
   SET PAID_DATE = '18-JUL-2017',
       PAY_INDICATOR = 'Y',
       STOP_INDICATOR = 'N',
       OPEN_INDICATOR = 'Y',
       STOP_PAY_MARKED_BY_CCN_IND = NULL,
       BANK_PAID_AMOUNT = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT), 
       GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT), 
       NET_AMOUNT = NVL(NET_AMOUNT, ORIGINAL_NET_AMOUNT),
       STOP_PAY_DATE = NULL
 WHERE COST_CENTER_CODE = '703154'
   AND CHECK_SERIAL_NUMBER = '0315417873';

COMMIT;