/*---------------------------------------
Below script will manually mark the drafts as paid as per email sent by Marissa Papas
--MARK AS PAID
Store	Draft	Paid Date
708226	4479-8	5/31/2018 - reverse Stop Payment and Mark as paid.
708064  1437-1  7/18/2018 - reverse Stop Payment and Mark as paid.
707725  1208-3  7/31/2018 - reverse Stop Payment and Mark as paid.
702112  9281-8  9/07/2018 - Mark AS Paid.
703406  6677-5  9/05/2018 - Mark AS Paid.
702688  1028-0  7/02/2018 - Mark AS Paid.
703461  1066-1  9/06/2018 - Mark AS Paid.
702530  1954-1  7/13/2018 - Mark AS Paid.
705645  3670-4  8/08/2018 - Mark AS Paid.
708026  2048-4  7/10/2018 - Mark AS Paid.
708573  6653-8  7/12/2018 - Mark AS Paid.
702263  8779-3  6/30/2018 - reverse Stop Payment and Mark as paid.

Created: 09/26/2018 sxg151
------------------------------------------*/

-- reverse Stop Payment and Mark as paid.


SELECT * FROM STORE_DRAFTS WHERE COST_CENTER_CODE = '708226' AND CHECK_SERIAL_NUMBER = '0822647798';
UPDATE STORE_DRAFTS 
   SET PAID_DATE = '31-MAY-2018',
       PAY_INDICATOR = 'Y',
       STOP_INDICATOR = 'N',
       OPEN_INDICATOR = 'Y',
       STOP_PAY_MARKED_BY_CCN_IND = NULL,
       BANK_PAID_AMOUNT = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT), 
       GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT), 
       NET_AMOUNT = NVL(NET_AMOUNT, ORIGINAL_NET_AMOUNT),
       STOP_PAY_DATE = NULL
 WHERE COST_CENTER_CODE = '708226' 
   AND CHECK_SERIAL_NUMBER = '0822647798';
 
 SELECT * FROM STORE_DRAFTS WHERE COST_CENTER_CODE = '708064' AND CHECK_SERIAL_NUMBER = '0806414371';
 UPDATE STORE_DRAFTS 
   SET PAID_DATE = '18-JUL-2018',
       PAY_INDICATOR = 'Y',
       STOP_INDICATOR = 'N',
       OPEN_INDICATOR = 'Y',
       VOID_INDICATOR = 'N',
       VOID_DATE      = NULL,
       STOP_PAY_MARKED_BY_CCN_IND = NULL,
       BANK_PAID_AMOUNT = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT),
       GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT), 
       NET_AMOUNT = NVL(NET_AMOUNT, ORIGINAL_NET_AMOUNT),
       STOP_PAY_DATE = NULL
 WHERE COST_CENTER_CODE = '708064'
   AND CHECK_SERIAL_NUMBER = '0806414371';
   
SELECT * FROM STORE_DRAFTS WHERE COST_CENTER_CODE = '707725'  AND CHECK_SERIAL_NUMBER = '0772512083';
 UPDATE STORE_DRAFTS 
   SET PAID_DATE = '31-JUL-2018',
       PAY_INDICATOR = 'Y',
       STOP_INDICATOR = 'N',
       OPEN_INDICATOR = 'Y',
       STOP_PAY_MARKED_BY_CCN_IND = NULL,
       BANK_PAID_AMOUNT = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT),
       GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT), 
       NET_AMOUNT = NVL(NET_AMOUNT, ORIGINAL_NET_AMOUNT),
       STOP_PAY_DATE = NULL
 WHERE COST_CENTER_CODE = '707725'
   AND CHECK_SERIAL_NUMBER = '0772512083';
   
SELECT * FROM STORE_DRAFTS WHERE COST_CENTER_CODE = '702112' AND CHECK_SERIAL_NUMBER = '0211292818';

UPDATE STORE_DRAFTS
   SET PAID_DATE = '07-SEP-2018',
       PAY_INDICATOR = 'Y',
       BANK_PAID_AMOUNT = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT),
       GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT),
       NET_AMOUNT = NVL(NET_AMOUNT, ORIGINAL_NET_AMOUNT)
 WHERE COST_CENTER_CODE = '702112'
   AND CHECK_SERIAL_NUMBER = '0211292818';
   
SELECT * FROM STORE_DRAFTS WHERE COST_CENTER_CODE = '703406' AND CHECK_SERIAL_NUMBER = '0340666775';
UPDATE STORE_DRAFTS
   SET PAID_DATE = '05-SEP-2018',
       PAY_INDICATOR = 'Y',
       BANK_PAID_AMOUNT = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT),
       GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT), 
       NET_AMOUNT = NVL(NET_AMOUNT, ORIGINAL_NET_AMOUNT)
 WHERE COST_CENTER_CODE = '703406' 
   AND CHECK_SERIAL_NUMBER = '0340666775';

SELECT * FROM STORE_DRAFTS WHERE COST_CENTER_CODE = '702688' AND CHECK_SERIAL_NUMBER = '0268810280';
UPDATE STORE_DRAFTS
   SET PAID_DATE = '02-JUL-2018',
       PAY_INDICATOR = 'Y',
       BANK_PAID_AMOUNT = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT),
       GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT),
       NET_AMOUNT = NVL(NET_AMOUNT, ORIGINAL_NET_AMOUNT)
 WHERE COST_CENTER_CODE = '702688'
   AND CHECK_SERIAL_NUMBER = '0268810280';

SELECT * FROM STORE_DRAFTS WHERE COST_CENTER_CODE = '703461' AND CHECK_SERIAL_NUMBER = '0346110661';
UPDATE STORE_DRAFTS
   SET PAID_DATE = '06-SEP-2018',
       PAY_INDICATOR = 'Y',
       BANK_PAID_AMOUNT = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT),
       GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT),
       NET_AMOUNT = NVL(NET_AMOUNT, ORIGINAL_NET_AMOUNT)
 WHERE COST_CENTER_CODE = '703461'
   AND CHECK_SERIAL_NUMBER = '0346110661';

SELECT * FROM STORE_DRAFTS WHERE COST_CENTER_CODE = '702530' AND CHECK_SERIAL_NUMBER = '0253019541';
UPDATE STORE_DRAFTS
   SET PAID_DATE = '13-JUL-2018',
       PAY_INDICATOR = 'Y',
       BANK_PAID_AMOUNT = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT),
       GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT),
       NET_AMOUNT = NVL(NET_AMOUNT, ORIGINAL_NET_AMOUNT)
 WHERE COST_CENTER_CODE = '702530'
   AND CHECK_SERIAL_NUMBER = '0253019541';

SELECT * FROM STORE_DRAFTS WHERE COST_CENTER_CODE = '705645' AND CHECK_SERIAL_NUMBER = '0564536704';
UPDATE STORE_DRAFTS
   SET PAID_DATE = '08-AUG-2018',
       PAY_INDICATOR = 'Y',
       BANK_PAID_AMOUNT = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT),
       GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT),
       NET_AMOUNT = NVL(NET_AMOUNT, ORIGINAL_NET_AMOUNT)
 WHERE COST_CENTER_CODE = '705645'
   AND CHECK_SERIAL_NUMBER = '0564536704';

SELECT * FROM STORE_DRAFTS WHERE COST_CENTER_CODE = '708026' AND CHECK_SERIAL_NUMBER = '0802620484';
UPDATE STORE_DRAFTS
   SET PAID_DATE = '10-JUL-2018',
       PAY_INDICATOR = 'Y',
       BANK_PAID_AMOUNT = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT),
       GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT),
       NET_AMOUNT = NVL(NET_AMOUNT, ORIGINAL_NET_AMOUNT)
 WHERE COST_CENTER_CODE = '708026'
   AND CHECK_SERIAL_NUMBER = '0802620484';

SELECT * FROM STORE_DRAFTS WHERE COST_CENTER_CODE = '708573' AND CHECK_SERIAL_NUMBER = '0857366538';
UPDATE STORE_DRAFTS
   SET PAID_DATE = '12-JUL-2018',
       PAY_INDICATOR = 'Y',
       BANK_PAID_AMOUNT = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT),
       GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT),
       NET_AMOUNT = NVL(NET_AMOUNT, ORIGINAL_NET_AMOUNT)
 WHERE COST_CENTER_CODE = '708573'
   AND CHECK_SERIAL_NUMBER = '0857366538';

--reverse Stop Payment and Mark as paid.

SELECT * FROM STORE_DRAFTS WHERE COST_CENTER_CODE = '702263'  AND CHECK_SERIAL_NUMBER = '0226387793';
 UPDATE STORE_DRAFTS
   SET PAID_DATE = '30-JUN-2018',
       PAY_INDICATOR = 'Y',
       STOP_INDICATOR = 'N',
       OPEN_INDICATOR = 'Y',
       STOP_PAY_MARKED_BY_CCN_IND = NULL,
       BANK_PAID_AMOUNT = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT),
       GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT),
       NET_AMOUNT = NVL(NET_AMOUNT, ORIGINAL_NET_AMOUNT),
       STOP_PAY_DATE = NULL
 WHERE COST_CENTER_CODE = '702263'
   AND CHECK_SERIAL_NUMBER = '0226387793';

COMMIT;