/*
Below scripts will manually update the paid details with the details provided below
Created : 09/16/2016 sxh487  CCN Project team.... 

CC	Draft	Date Paid
768830	10134	10/30/2015
768830	10167	10/30/2015
768768	10730	3/28/2015
768768	10748	3/28/2015
778739	10582	1/29/2016

all the indicators are N besides Open indicator which is 'Y'
*/

SELECT * FROM STORE_DRAFTS WHERE CHECK_SERIAL_NUMBER = '0883010134';
--1 Row(s) SELECTed
UPDATE STORE_DRAFTS
   SET PAY_INDICATOR = 'Y', 
       PAID_DATE = '30-OCT-2015', 
       BANK_PAID_AMOUNT = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT,NET_AMOUNT),
       GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT),
       NET_AMOUNT   = NVL(NET_AMOUNT,ORIGINAL_NET_AMOUNT)
 WHERE CHECK_SERIAL_NUMBER = '0883010134';
--1 Row(s) Updated
 
SELECT * FROM STORE_DRAFTS WHERE CHECK_SERIAL_NUMBER = '0883010167';
--1 Row(s) SELECTed
UPDATE STORE_DRAFTS
   SET PAY_INDICATOR = 'Y', 
       PAID_DATE = '30-OCT-2015', 
       BANK_PAID_AMOUNT = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT),
       GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT),
       NET_AMOUNT   = NVL(NET_AMOUNT,ORIGINAL_NET_AMOUNT)
 WHERE CHECK_SERIAL_NUMBER = '0883010167';
--1 Row(s) Updated

SELECT * FROM STORE_DRAFTS WHERE CHECK_SERIAL_NUMBER = '0876810730';
--1 Row(s) SELECTed
UPDATE STORE_DRAFTS
   SET PAY_INDICATOR = 'Y', 
       PAID_DATE = '28-MAR-2015', 
       BANK_PAID_AMOUNT = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT),
       GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT),
       NET_AMOUNT   = NVL(NET_AMOUNT,ORIGINAL_NET_AMOUNT)
 WHERE CHECK_SERIAL_NUMBER = '0876810730';
--1 Row(s) Updated

SELECT * FROM STORE_DRAFTS WHERE CHECK_SERIAL_NUMBER = '0876810748';
--1 Row(s) SELECTed
UPDATE STORE_DRAFTS
   SET PAY_INDICATOR = 'Y', 
       PAID_DATE = '28-MAR-2015', 
       BANK_PAID_AMOUNT = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT),
       GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT),
       NET_AMOUNT   = NVL(NET_AMOUNT,ORIGINAL_NET_AMOUNT)
 WHERE CHECK_SERIAL_NUMBER = '0876810748';
--1 Row(s) Updated

SELECT * FROM STORE_DRAFTS WHERE CHECK_SERIAL_NUMBER = '0873910582';
--1 Row(s) SELECTed
UPDATE STORE_DRAFTS
   SET PAY_INDICATOR = 'Y', 
       PAID_DATE = '29-JAN-2016', 
       BANK_PAID_AMOUNT = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT),
       GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT),
       NET_AMOUNT   = NVL(NET_AMOUNT,ORIGINAL_NET_AMOUNT)
 WHERE CHECK_SERIAL_NUMBER = '0873910582';
 --1 Row(s) Updated
 
 COMMIT;