/*
Below script will update the store drafts paid details as requested by Chris

Created : 10/19/2016 jxc517 CCN Project Team....
*/

/*
--Mark as Paid:
708173	9312-7	8/18/2016
708678	1040-0	8/8/2016
703468	1007-0	8/8/2016
701758	1011-8	8/8/2016
708200	1278-9	8/31/2016 (ignore as per latest email)
703226	1154-2	9/15/2016
701946	1039-0	9/1/2016
707689	3107-3	9/7/2016
705442	1011-5	9/9/2016
708200	1278-9	9/1/2016
*/
SELECT * FROM STORE_DRAFTS WHERE COST_CENTER_CODE = '708173' AND DRAFT_NUMBER = '9312';
--1 Row(s) Selected
UPDATE STORE_DRAFTS 
   SET PAID_DATE = '18-AUG-2016',
       PAY_INDICATOR = 'Y',
       BANK_PAID_AMOUNT = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT),
       GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT),
       NET_AMOUNT   = NVL(NET_AMOUNT, ORIGINAL_NET_AMOUNT)
 WHERE COST_CENTER_CODE = '708173' AND DRAFT_NUMBER = '9312';
--1 Row(s) Updated

SELECT * FROM STORE_DRAFTS WHERE COST_CENTER_CODE = '708678' AND DRAFT_NUMBER = '1040';
--1 Row(s) Selected
UPDATE STORE_DRAFTS 
   SET PAID_DATE = '08-AUG-2016',
       PAY_INDICATOR = 'Y',
       BANK_PAID_AMOUNT = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT),
       GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT),
       NET_AMOUNT   = NVL(NET_AMOUNT, ORIGINAL_NET_AMOUNT)
 WHERE COST_CENTER_CODE = '708678' AND DRAFT_NUMBER = '1040';
--1 Row(s) Updated

SELECT * FROM STORE_DRAFTS WHERE COST_CENTER_CODE = '703468' AND DRAFT_NUMBER = '1007';
--1 Row(s) Selected
UPDATE STORE_DRAFTS 
   SET PAID_DATE = '08-AUG-2016',
       PAY_INDICATOR = 'Y',
       BANK_PAID_AMOUNT = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT),
       GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT),
       NET_AMOUNT   = NVL(NET_AMOUNT, ORIGINAL_NET_AMOUNT)
 WHERE COST_CENTER_CODE = '703468' AND DRAFT_NUMBER = '1007';
--1 Row(s) Updated

SELECT * FROM STORE_DRAFTS WHERE COST_CENTER_CODE = '701758' AND DRAFT_NUMBER = '1011';
--1 Row(s) Selected
UPDATE STORE_DRAFTS 
   SET PAID_DATE = '08-AUG-2016',
       PAY_INDICATOR = 'Y',
       BANK_PAID_AMOUNT = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT),
       GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT),
       NET_AMOUNT   = NVL(NET_AMOUNT, ORIGINAL_NET_AMOUNT)
 WHERE COST_CENTER_CODE = '701758' AND DRAFT_NUMBER = '1011';
--1 Row(s) Updated

SELECT * FROM STORE_DRAFTS WHERE COST_CENTER_CODE = '708200' AND DRAFT_NUMBER = '1278';
--1 Row(s) Selected
UPDATE STORE_DRAFTS 
   SET PAID_DATE = '01-SEP-2016',
       PAY_INDICATOR = 'Y',
       BANK_PAID_AMOUNT = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT),
       GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT),
       NET_AMOUNT   = NVL(NET_AMOUNT, ORIGINAL_NET_AMOUNT)
 WHERE COST_CENTER_CODE = '708200' AND DRAFT_NUMBER = '1278';
--1 Row(s) Updated

SELECT * FROM STORE_DRAFTS WHERE COST_CENTER_CODE = '703226' AND DRAFT_NUMBER = '1154';
--1 Row(s) Selected
UPDATE STORE_DRAFTS 
   SET PAID_DATE = '15-SEP-2016',
       PAY_INDICATOR = 'Y',
       BANK_PAID_AMOUNT = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT),
       GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT),
       NET_AMOUNT   = NVL(NET_AMOUNT, ORIGINAL_NET_AMOUNT)
 WHERE COST_CENTER_CODE = '703226' AND DRAFT_NUMBER = '1154';
--1 Row(s) Updated

SELECT * FROM STORE_DRAFTS WHERE COST_CENTER_CODE = '701946' AND DRAFT_NUMBER = '1039';
--1 Row(s) Selected
UPDATE STORE_DRAFTS 
   SET PAID_DATE = '01-SEP-2016',
       PAY_INDICATOR = 'Y',
       BANK_PAID_AMOUNT = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT),
       GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT),
       NET_AMOUNT   = NVL(NET_AMOUNT, ORIGINAL_NET_AMOUNT)
 WHERE COST_CENTER_CODE = '701946' AND DRAFT_NUMBER = '1039';
--1 Row(s) Updated

SELECT * FROM STORE_DRAFTS WHERE COST_CENTER_CODE = '707689' AND DRAFT_NUMBER = '3107';
--1 Row(s) Selected
UPDATE STORE_DRAFTS 
   SET PAID_DATE = '07-SEP-2016',
       PAY_INDICATOR = 'Y',
       BANK_PAID_AMOUNT = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT),
       GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT),
       NET_AMOUNT   = NVL(NET_AMOUNT, ORIGINAL_NET_AMOUNT)
 WHERE COST_CENTER_CODE = '707689' AND DRAFT_NUMBER = '3107';
--1 Row(s) Updated

SELECT * FROM STORE_DRAFTS WHERE COST_CENTER_CODE = '705442' AND DRAFT_NUMBER = '1011';
--1 Row(s) Selected
UPDATE STORE_DRAFTS 
   SET PAID_DATE = '09-SEP-2016',
       PAY_INDICATOR = 'Y',
       BANK_PAID_AMOUNT = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT),
       GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT),
       NET_AMOUNT   = NVL(NET_AMOUNT, ORIGINAL_NET_AMOUNT)
 WHERE COST_CENTER_CODE = '705442' AND DRAFT_NUMBER = '1011';
--1 Row(s) Updated

/*
--Remove Stop Dates and Mark as Paid
703500	2001-2	9/15/2016
708460	2168-1	9/20/2016
703016	3724-5	9/8/2016
*/


SELECT * FROM STORE_DRAFTS WHERE COST_CENTER_CODE = '703500' AND DRAFT_NUMBER = '2001';
--1 Row(s) Selected
UPDATE STORE_DRAFTS 
   SET PAID_DATE = '15-SEP-2016',
       PAY_INDICATOR = 'Y',
       BANK_PAID_AMOUNT = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT),
       GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT),
       NET_AMOUNT   = NVL(NET_AMOUNT, ORIGINAL_NET_AMOUNT),
       STOP_INDICATOR = 'N',
       OPEN_INDICATOR = 'Y',
       STOP_PAY_DATE = NULL
 WHERE COST_CENTER_CODE = '703500' AND DRAFT_NUMBER = '2001';
--1 Row(s) Updated

SELECT * FROM STORE_DRAFTS WHERE COST_CENTER_CODE = '708460' AND DRAFT_NUMBER = '2168';
--1 Row(s) Selected
UPDATE STORE_DRAFTS 
   SET PAID_DATE = '20-SEP-2016',
       PAY_INDICATOR = 'Y',
       BANK_PAID_AMOUNT = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT),
       GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT),
       NET_AMOUNT   = NVL(NET_AMOUNT, ORIGINAL_NET_AMOUNT),
       STOP_INDICATOR = 'N',
       OPEN_INDICATOR = 'Y',
       STOP_PAY_DATE = NULL
 WHERE COST_CENTER_CODE = '708460' AND DRAFT_NUMBER = '2168';
--1 Row(s) Updated

SELECT * FROM STORE_DRAFTS WHERE COST_CENTER_CODE = '703016' AND DRAFT_NUMBER = '3724';
--1 Row(s) Selected
UPDATE STORE_DRAFTS 
   SET PAID_DATE = '08-SEP-2016',
       PAY_INDICATOR = 'Y',
       BANK_PAID_AMOUNT = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT),
       GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT),
       NET_AMOUNT   = NVL(NET_AMOUNT, ORIGINAL_NET_AMOUNT),
       STOP_INDICATOR = 'N',
       OPEN_INDICATOR = 'Y',
       STOP_PAY_DATE = NULL
 WHERE COST_CENTER_CODE = '703016' AND DRAFT_NUMBER = '3724';
--1 Row(s) Updated

/*
--Remove Pay Dates
707324	1577-3	9/13/2016
702230	2411-8	9/13/2016
707486	1411-2	9/13/2016
705495	5585-2	9/13/2016
703410	1014-8	9/13/2016
702696	1040-8	9/13/2016
*/
SELECT * FROM STORE_DRAFTS WHERE COST_CENTER_CODE = '707324' AND DRAFT_NUMBER = '1577';
--1 Row(s) Selected
UPDATE STORE_DRAFTS 
   SET PAID_DATE = NULL,
       PAY_INDICATOR = 'N',
       BANK_PAID_AMOUNT = NULL
 WHERE COST_CENTER_CODE = '707324' AND DRAFT_NUMBER = '1577';
--1 Row(s) Updated

SELECT * FROM STORE_DRAFTS WHERE COST_CENTER_CODE = '702230' AND DRAFT_NUMBER = '2411';
--1 Row(s) Selected
UPDATE STORE_DRAFTS 
   SET PAID_DATE = NULL,
       PAY_INDICATOR = 'N',
       BANK_PAID_AMOUNT = NULL
 WHERE COST_CENTER_CODE = '702230' AND DRAFT_NUMBER = '2411';
--1 Row(s) Updated

SELECT * FROM STORE_DRAFTS WHERE COST_CENTER_CODE = '707486' AND DRAFT_NUMBER = '1411';
--1 Row(s) Selected
UPDATE STORE_DRAFTS 
   SET PAID_DATE = NULL,
       PAY_INDICATOR = 'N',
       BANK_PAID_AMOUNT = NULL
 WHERE COST_CENTER_CODE = '707486' AND DRAFT_NUMBER = '1411';
--1 Row(s) Updated

SELECT * FROM STORE_DRAFTS WHERE COST_CENTER_CODE = '705495' AND DRAFT_NUMBER = '5585';
--1 Row(s) Selected
UPDATE STORE_DRAFTS 
   SET PAID_DATE = NULL,
       PAY_INDICATOR = 'N',
       BANK_PAID_AMOUNT = NULL
 WHERE COST_CENTER_CODE = '705495' AND DRAFT_NUMBER = '5585';
--1 Row(s) Updated

SELECT * FROM STORE_DRAFTS WHERE COST_CENTER_CODE = '703410' AND DRAFT_NUMBER = '1014';
--1 Row(s) Selected
UPDATE STORE_DRAFTS 
   SET PAID_DATE = NULL,
       PAY_INDICATOR = 'N',
       BANK_PAID_AMOUNT = NULL
 WHERE COST_CENTER_CODE = '703410' AND DRAFT_NUMBER = '1014';
--1 Row(s) Updated

SELECT * FROM STORE_DRAFTS WHERE COST_CENTER_CODE = '702696' AND DRAFT_NUMBER = '1040';
--1 Row(s) Selected
UPDATE STORE_DRAFTS 
   SET PAID_DATE = NULL,
       PAY_INDICATOR = 'N',
       BANK_PAID_AMOUNT = NULL
 WHERE COST_CENTER_CODE = '702696' AND DRAFT_NUMBER = '1040';
--1 Row(s) Updated

COMMIT;
