
-- 'Mark as paid' as per EMAIL sent by mary   
SELECT * FROM STORE_DRAFTS WHERE COST_CENTER_CODE = '702825' AND CHECK_SERIAL_NUMBER = '0282510304';

UPDATE STORE_DRAFTS 
   SET PAID_DATE = '19-OCT-2017', 
       PAY_INDICATOR = 'Y', 
	   BANK_PAID_AMOUNT = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT), 
	   GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT), 
	   NET_AMOUNT = NVL(NET_AMOUNT, ORIGINAL_NET_AMOUNT) 
 WHERE COST_CENTER_CODE = '702825' 
   AND CHECK_SERIAL_NUMBER = '0282510304';
   
SELECT * FROM STORE_DRAFTS WHERE COST_CENTER_CODE = '705254' AND CHECK_SERIAL_NUMBER = '0525410486';

UPDATE STORE_DRAFTS 
   SET PAID_DATE = '02-OCT-2017', 
       PAY_INDICATOR = 'Y', 
	   BANK_PAID_AMOUNT = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT), 
	   GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT), 
	   NET_AMOUNT = NVL(NET_AMOUNT, ORIGINAL_NET_AMOUNT) 
 WHERE COST_CENTER_CODE = '705254' 
   AND CHECK_SERIAL_NUMBER = '0525410486';
   

SELECT * FROM STORE_DRAFTS WHERE COST_CENTER_CODE = '701836' AND CHECK_SERIAL_NUMBER = '0183613793';

UPDATE STORE_DRAFTS 
   SET PAID_DATE = '17-OCT-2017', 
       PAY_INDICATOR = 'Y', 
	   BANK_PAID_AMOUNT = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT), 
	   GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT), 
	   NET_AMOUNT = NVL(NET_AMOUNT, ORIGINAL_NET_AMOUNT) 
 WHERE COST_CENTER_CODE = '701836' 
   AND CHECK_SERIAL_NUMBER = '0183613793';
   
SELECT * FROM STORE_DRAFTS WHERE COST_CENTER_CODE = '707368' AND CHECK_SERIAL_NUMBER = '0736815861';

UPDATE STORE_DRAFTS 
   SET PAID_DATE = '21-SEP-2017', 
       PAY_INDICATOR = 'Y', 
	   BANK_PAID_AMOUNT = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT), 
	   GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT), 
	   NET_AMOUNT = NVL(NET_AMOUNT, ORIGINAL_NET_AMOUNT) 
 WHERE COST_CENTER_CODE = '707368' 
   AND CHECK_SERIAL_NUMBER = '0736815861';
   
SELECT * FROM STORE_DRAFTS WHERE COST_CENTER_CODE = '703860' AND CHECK_SERIAL_NUMBER = '0386016604';

UPDATE STORE_DRAFTS 
   SET PAID_DATE = '09-AUG-2017', 
       PAY_INDICATOR = 'Y', 
	   BANK_PAID_AMOUNT = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT), 
	   GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT), 
	   NET_AMOUNT = NVL(NET_AMOUNT, ORIGINAL_NET_AMOUNT) 
 WHERE COST_CENTER_CODE = '703860' 
   AND CHECK_SERIAL_NUMBER = '0386016604';
   
SELECT * FROM STORE_DRAFTS WHERE COST_CENTER_CODE = '703527' AND CHECK_SERIAL_NUMBER = '0352716781';

UPDATE STORE_DRAFTS 
   SET PAID_DATE = '28-AUG-2017', 
       PAY_INDICATOR = 'Y', 
	   BANK_PAID_AMOUNT = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT), 
	   GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT), 
	   NET_AMOUNT = NVL(NET_AMOUNT, ORIGINAL_NET_AMOUNT) 
 WHERE COST_CENTER_CODE = '703527' 
   AND CHECK_SERIAL_NUMBER = '0352716781';
   
   
SELECT * FROM STORE_DRAFTS WHERE COST_CENTER_CODE = '707317' AND CHECK_SERIAL_NUMBER = '0731718698';

UPDATE STORE_DRAFTS 
   SET PAID_DATE = '19-OCT-2017', 
       PAY_INDICATOR = 'Y', 
	   BANK_PAID_AMOUNT = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT), 
	   GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT), 
	   NET_AMOUNT = NVL(NET_AMOUNT, ORIGINAL_NET_AMOUNT) 
 WHERE COST_CENTER_CODE = '707317' 
   AND CHECK_SERIAL_NUMBER = '0731718698';
   
SELECT * FROM STORE_DRAFTS WHERE COST_CENTER_CODE = '703826' AND CHECK_SERIAL_NUMBER = '0382625275';

UPDATE STORE_DRAFTS 
   SET PAID_DATE = '03-OCT-2017', 
       PAY_INDICATOR = 'Y', 
	   BANK_PAID_AMOUNT = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT), 
	   GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT), 
	   NET_AMOUNT = NVL(NET_AMOUNT, ORIGINAL_NET_AMOUNT) 
 WHERE COST_CENTER_CODE = '703826' 
   AND CHECK_SERIAL_NUMBER = '0382625275';

   
SELECT * FROM STORE_DRAFTS WHERE COST_CENTER_CODE = '703204' AND CHECK_SERIAL_NUMBER = '0320413214';

UPDATE STORE_DRAFTS 
   SET PAID_DATE = '17-OCT-2017', 
       PAY_INDICATOR = 'Y', 
	   BANK_PAID_AMOUNT = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT), 
	   GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT), 
	   NET_AMOUNT = NVL(NET_AMOUNT, ORIGINAL_NET_AMOUNT) 
 WHERE COST_CENTER_CODE = '703204' 
   AND CHECK_SERIAL_NUMBER = '0320413214';
   
   
SELECT * FROM STORE_DRAFTS WHERE COST_CENTER_CODE = '701131' AND CHECK_SERIAL_NUMBER = '0113117030';

UPDATE STORE_DRAFTS 
   SET PAID_DATE = '03-OCT-2017', 
       PAY_INDICATOR = 'Y', 
	   BANK_PAID_AMOUNT = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT), 
	   GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT), 
	   NET_AMOUNT = NVL(NET_AMOUNT, ORIGINAL_NET_AMOUNT) 
 WHERE COST_CENTER_CODE = '701131' 
   AND CHECK_SERIAL_NUMBER = '0113117030';
   
SELECT * FROM STORE_DRAFTS WHERE COST_CENTER_CODE = '703110' AND CHECK_SERIAL_NUMBER = '0311036461';

UPDATE STORE_DRAFTS 
   SET PAID_DATE = '31-AUG-2017', 
       PAY_INDICATOR = 'Y', 
	   BANK_PAID_AMOUNT = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT), 
	   GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT), 
	   NET_AMOUNT = NVL(NET_AMOUNT, ORIGINAL_NET_AMOUNT) 
 WHERE COST_CENTER_CODE = '703110' 
   AND CHECK_SERIAL_NUMBER = '0311036461';
   
SELECT * FROM STORE_DRAFTS WHERE COST_CENTER_CODE = '708226' AND CHECK_SERIAL_NUMBER = '0822648614';

UPDATE STORE_DRAFTS 
   SET PAID_DATE = '31-JUL-2017', 
       PAY_INDICATOR = 'Y', 
	   BANK_PAID_AMOUNT = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT), 
	   GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT), 
	   NET_AMOUNT = NVL(NET_AMOUNT, ORIGINAL_NET_AMOUNT) 
 WHERE COST_CENTER_CODE = '708226' 
   AND CHECK_SERIAL_NUMBER = '0822648614';
   
SELECT * FROM STORE_DRAFTS WHERE COST_CENTER_CODE = '701891' AND CHECK_SERIAL_NUMBER = '0189161722';

UPDATE STORE_DRAFTS 
   SET PAID_DATE = '31-JUL-2017', 
       PAY_INDICATOR = 'Y', 
	   BANK_PAID_AMOUNT = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT), 
	   GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT), 
	   NET_AMOUNT = NVL(NET_AMOUNT, ORIGINAL_NET_AMOUNT) 
 WHERE COST_CENTER_CODE = '701891' 
   AND CHECK_SERIAL_NUMBER = '0189161722';
   
SELECT * FROM STORE_DRAFTS WHERE COST_CENTER_CODE = '705239' AND CHECK_SERIAL_NUMBER = '0523972024';

UPDATE STORE_DRAFTS 
   SET PAID_DATE = '03-OCT-2017', 
       PAY_INDICATOR = 'Y', 
	   BANK_PAID_AMOUNT = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT), 
	   GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT), 
	   NET_AMOUNT = NVL(NET_AMOUNT, ORIGINAL_NET_AMOUNT) 
 WHERE COST_CENTER_CODE = '705239' 
   AND CHECK_SERIAL_NUMBER = '0523972024';
   
SELECT * FROM STORE_DRAFTS WHERE COST_CENTER_CODE = '703208' AND CHECK_SERIAL_NUMBER = '0320892391';

UPDATE STORE_DRAFTS 
   SET PAID_DATE = '17-OCT-2017', 
       PAY_INDICATOR = 'Y', 
	   BANK_PAID_AMOUNT = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT), 
	   GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT), 
	   NET_AMOUNT = NVL(NET_AMOUNT, ORIGINAL_NET_AMOUNT) 
 WHERE COST_CENTER_CODE = '703208' 
   AND CHECK_SERIAL_NUMBER = '0320892391';
   

-- Already Marked as paid, just update pay date as per Email sent by Mary   
SELECT * FROM STORE_DRAFTS WHERE COST_CENTER_CODE = '708506' AND CHECK_SERIAL_NUMBER = '0850613738';

UPDATE STORE_DRAFTS 
   SET PAID_DATE = '29-SEP-2017'
 WHERE COST_CENTER_CODE = '708506' 
   AND CHECK_SERIAL_NUMBER = '0850613738';
   
SELECT * FROM STORE_DRAFTS WHERE COST_CENTER_CODE = '703825' AND CHECK_SERIAL_NUMBER = '0382528669';

UPDATE STORE_DRAFTS 
   SET PAID_DATE = '29-SEP-2017'
 WHERE COST_CENTER_CODE = '703825' 
   AND CHECK_SERIAL_NUMBER = '0382528669';
   
-- Donot Mark as Paid    
SELECT * FROM STORE_DRAFTS WHERE COST_CENTER_CODE = '703154' AND CHECK_SERIAL_NUMBER = '0315417873';

UPDATE STORE_DRAFTS 
   SET PAID_DATE = NULL, 
       PAY_INDICATOR = 'N' 
 WHERE COST_CENTER_CODE = '703154' 
   AND CHECK_SERIAL_NUMBER = '0315417873';
   
--Update amounts for "Change Amount in CCN to match check amount on this file" as per Email from Mary 
SELECT * FROM STORE_DRAFTS WHERE COST_CENTER_CODE = '702105' AND CHECK_SERIAL_NUMBER = '0210513644';

UPDATE STORE_DRAFTS 
   SET NET_AMOUNT = 252.26
 WHERE COST_CENTER_CODE = '702105' 
   AND CHECK_SERIAL_NUMBER = '0210513644';
   
SELECT * FROM STORE_DRAFTS WHERE COST_CENTER_CODE = '705342' AND CHECK_SERIAL_NUMBER = '0534261029';

UPDATE STORE_DRAFTS 
   SET NET_AMOUNT = 2000.00
 WHERE COST_CENTER_CODE = '705342' 
   AND CHECK_SERIAL_NUMBER = '0534261029';
   
SELECT * FROM STORE_DRAFTS WHERE COST_CENTER_CODE = '701648' AND CHECK_SERIAL_NUMBER = '0164815128';

UPDATE STORE_DRAFTS 
   SET NET_AMOUNT = 8883.66
 WHERE COST_CENTER_CODE = '701648' 
   AND CHECK_SERIAL_NUMBER = '0164815128';
   
 COMMIT;