/*
Below script will update the store drafts paid details as requested by Chris

Can you please mark the first check (727317018) as paid on 8/5/16 and the second (203517131) as paid on 8/18/16.

Created : 10/25/2016 jxc517 CCN Project Team....
*/

SELECT * FROM STORE_DRAFTS WHERE CHECK_SERIAL_NUMBER = '0727317018';
--1 Row(s) Selected
UPDATE STORE_DRAFTS 
   SET PAID_DATE = '05-AUG-2016',
       PAY_INDICATOR = 'Y',
       BANK_PAID_AMOUNT = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT),
       OPEN_INDICATOR = 'Y',
       STOP_INDICATOR = 'N',
       STOP_PAY_DATE = NULL,
       GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT),
       NET_AMOUNT   = NVL(NET_AMOUNT, ORIGINAL_NET_AMOUNT)
 WHERE CHECK_SERIAL_NUMBER = '0727317018';
--1 Row(s) Updated

SELECT * FROM STORE_DRAFTS WHERE CHECK_SERIAL_NUMBER = '0203517131';
--1 Row(s) Selected
UPDATE STORE_DRAFTS 
   SET PAID_DATE = '18-AUG-2016',
       PAY_INDICATOR = 'Y',
       BANK_PAID_AMOUNT = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT),
       OPEN_INDICATOR = 'Y',
       STOP_INDICATOR = 'N',
       STOP_PAY_DATE = NULL,
       GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT),
       NET_AMOUNT   = NVL(NET_AMOUNT, ORIGINAL_NET_AMOUNT)
 WHERE CHECK_SERIAL_NUMBER = '0203517131';
--1 Row(s) Updated

COMMIT;
