/*---------------------------------------
Below script will manually mark the drafts as paid as per email sent by Marissa Papas
--MARK AS PAID
Store	Draft	Paid Date
702816	1002-2	9/27/2018 - reverse Stop Payment and Mark as paid.
702816  1003-0  9/27/2018 - reverse Stop Payment and Mark as paid.
701722  1921-4  9/05/2018 - Mark AS Paid.
702514  3155-7  9/02/2018 - Mark AS Paid.
768333  1003-0  9/20/2018 - Mark AS Paid.
708018  2174-5  9/12/2018 - Mark AS Paid.
767691  1000-8  9/18/2018 - Mark AS Paid.
705741  2217-2  9/28/2018 - Mark AS Paid.

Created: 10/12/2018 sxg151
------------------------------------------*/

-- reverse Stop Payment and Mark as paid.


SELECT * FROM STORE_DRAFTS WHERE CHECK_SERIAL_NUMBER = '0281610022';
UPDATE STORE_DRAFTS
   SET PAID_DATE = '27-SEP-2018',
       PAY_INDICATOR = 'Y',
       OPEN_INDICATOR = 'Y',
       STOP_INDICATOR = 'N',
       STOP_PAY_MARKED_BY_CCN_IND = NULL,
       BANK_PAID_AMOUNT = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT),
       GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT),
       NET_AMOUNT = NVL(NET_AMOUNT, ORIGINAL_NET_AMOUNT),
       STOP_PAY_DATE = NULL
 WHERE CHECK_SERIAL_NUMBER = '0281610022';

 SELECT * FROM STORE_DRAFTS WHERE CHECK_SERIAL_NUMBER = '0281610030';
 UPDATE STORE_DRAFTS
   SET PAID_DATE = '27-SEP-2018',
       PAY_INDICATOR = 'Y',
       STOP_PAY_MARKED_BY_CCN_IND = NULL,
       BANK_PAID_AMOUNT = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT),
       GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT),
       NET_AMOUNT = NVL(NET_AMOUNT, ORIGINAL_NET_AMOUNT),
       STOP_PAY_DATE = NULL
 WHERE CHECK_SERIAL_NUMBER = '0281610030';

-- Mark as paid

SELECT * FROM STORE_DRAFTS WHERE CHECK_SERIAL_NUMBER = '0172219214';

UPDATE STORE_DRAFTS
   SET PAID_DATE = '05-SEP-2018',
       PAY_INDICATOR = 'Y',
       BANK_PAID_AMOUNT = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT),
       GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT),
       NET_AMOUNT = NVL(NET_AMOUNT, ORIGINAL_NET_AMOUNT)
 WHERE CHECK_SERIAL_NUMBER = '0172219214';

SELECT * FROM STORE_DRAFTS WHERE CHECK_SERIAL_NUMBER = '0251431557';
UPDATE STORE_DRAFTS
   SET PAID_DATE = '02-SEP-2018',
       PAY_INDICATOR = 'Y',
       BANK_PAID_AMOUNT = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT),
       GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT),
       NET_AMOUNT = NVL(NET_AMOUNT, ORIGINAL_NET_AMOUNT)
 WHERE CHECK_SERIAL_NUMBER = '0251431557';

SELECT * FROM STORE_DRAFTS WHERE CHECK_SERIAL_NUMBER = '0833310030';
UPDATE STORE_DRAFTS
   SET PAID_DATE = '20-SEP-2018',
       PAY_INDICATOR = 'Y',
       BANK_PAID_AMOUNT = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT),
       GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT),
       NET_AMOUNT = NVL(NET_AMOUNT, ORIGINAL_NET_AMOUNT)
 WHERE CHECK_SERIAL_NUMBER = '0833310030';

SELECT * FROM STORE_DRAFTS WHERE CHECK_SERIAL_NUMBER = '0801821745';
UPDATE STORE_DRAFTS
   SET PAID_DATE = '12-SEP-2018',
       PAY_INDICATOR = 'Y',
       BANK_PAID_AMOUNT = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT),
       GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT),
       NET_AMOUNT = NVL(NET_AMOUNT, ORIGINAL_NET_AMOUNT)
 WHERE CHECK_SERIAL_NUMBER = '0801821745';

SELECT * FROM STORE_DRAFTS WHERE CHECK_SERIAL_NUMBER = '0769110008';
UPDATE STORE_DRAFTS
   SET PAID_DATE = '18-SEP-2018',
       PAY_INDICATOR = 'Y',
       BANK_PAID_AMOUNT = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT),
       GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT),
       NET_AMOUNT = NVL(NET_AMOUNT, ORIGINAL_NET_AMOUNT)
 WHERE CHECK_SERIAL_NUMBER = '0769110008';

SELECT * FROM STORE_DRAFTS WHERE CHECK_SERIAL_NUMBER = '0574122172';
UPDATE STORE_DRAFTS
   SET PAID_DATE = '28-SEP-2018',
       PAY_INDICATOR = 'Y',
       BANK_PAID_AMOUNT = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT),
       GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT),
       NET_AMOUNT = NVL(NET_AMOUNT, ORIGINAL_NET_AMOUNT)
 WHERE CHECK_SERIAL_NUMBER = '0574122172';

COMMIT;