/*
Below script is to update Paid Data and Amount in CCN as per Lee's request

Created : 9/13/2019 jxc517 CCN Project Team....
Changed : 
*/
SELECT * FROM STORE_DRAFTS WHERE CHECK_SERIAL_NUMBER = '0359210036';
UPDATE STORE_DRAFTS 
   SET PAID_DATE = '15-AUG-2019', 
       PAY_INDICATOR = 'Y',
       BANK_PAID_AMOUNT = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT), 
       GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT), 
       NET_AMOUNT = NVL(NET_AMOUNT, ORIGINAL_NET_AMOUNT)
 WHERE CHECK_SERIAL_NUMBER = '0359210036';
SELECT * FROM STORE_DRAFTS WHERE CHECK_SERIAL_NUMBER = '0359210036';
COMMIT;