/*
CREATED : 10/22/2018 kxm302 Script to update the PAID_DATE for the check number 0895310084
*/

SELECT * FROM STORE_DRAFTS WHERE CHECK_SERIAL_NUMBER = '0895310084';
--1 Row(s) SELECTed
UPDATE STORE_DRAFTS
   SET PAY_INDICATOR = 'Y', 
       PAID_DATE = '30-JUL-2018',
       BANK_PAID_AMOUNT = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT),
       GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT),
       NET_AMOUNT   = NVL(NET_AMOUNT,ORIGINAL_NET_AMOUNT)
 WHERE CHECK_SERIAL_NUMBER = '0895310084';
 --1 Row(s) Updated

COMMIT;