/*---------------------------------------
Below script will manually mark the drafts as paid as per email sent by Marissa Papas

768732	1625-3	10/31/2018  - Mark AS Paid.
768732	1626-1	10/31/2018  - Mark AS Paid.
768732	1627-9	10/31/2018  - Mark AS Paid.
768732	1629-5	10/31/2018  - Mark AS Paid.
768732	1631-1	10/31/2018  - Mark AS Paid.
768732	1632-9	10/31/2018  - Mark AS Paid.
768732	1633-7	10/31/2018  - Mark AS Paid.
768732	1634-5	10/31/2018  - Mark AS Paid.
768732	1635-2	10/31/2018  - Mark AS Paid.
768732	1638-6	10/31/2018  - Mark AS Paid.
768732	1639-4	10/31/2018  - Mark AS Paid.
768732	1640-2	10/31/2018  - Mark AS Paid.

Created: 11/28/2018 kxm302
------------------------------------------*/


SELECT * FROM STORE_DRAFTS WHERE CHECK_SERIAL_NUMBER ='0873216253';
--1 Row(s) SELECTed
UPDATE STORE_DRAFTS 
   SET PAID_DATE = '31-OCT-18',
       PAY_INDICATOR = 'Y',
       BANK_PAID_AMOUNT = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT),
       GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT),
       NET_AMOUNT   = NVL(NET_AMOUNT,ORIGINAL_NET_AMOUNT)
 WHERE CHECK_SERIAL_NUMBER ='0873216253';
--1 Row(s) Updated


SELECT * FROM STORE_DRAFTS WHERE CHECK_SERIAL_NUMBER ='0873216261';
--1 Row(s) SELECTed
UPDATE STORE_DRAFTS 
   SET PAID_DATE = '31-OCT-18',
       PAY_INDICATOR = 'Y',
       BANK_PAID_AMOUNT = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT),
       GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT),
       NET_AMOUNT   = NVL(NET_AMOUNT,ORIGINAL_NET_AMOUNT)
 WHERE CHECK_SERIAL_NUMBER ='0873216261';
--1 Row(s) Updated


SELECT * FROM STORE_DRAFTS WHERE CHECK_SERIAL_NUMBER ='0873216279';
--1 Row(s) SELECTed
UPDATE STORE_DRAFTS 
   SET PAID_DATE = '31-OCT-18',
       PAY_INDICATOR = 'Y',
       BANK_PAID_AMOUNT = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT),
       GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT),
       NET_AMOUNT   = NVL(NET_AMOUNT,ORIGINAL_NET_AMOUNT)
 WHERE CHECK_SERIAL_NUMBER ='0873216279';
--1 Row(s) Updated


SELECT * FROM STORE_DRAFTS WHERE CHECK_SERIAL_NUMBER ='0873216295';
--1 Row(s) SELECTed
UPDATE STORE_DRAFTS 
   SET PAID_DATE = '31-OCT-18',
       PAY_INDICATOR = 'Y',
       BANK_PAID_AMOUNT = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT),
       GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT),
       NET_AMOUNT   = NVL(NET_AMOUNT,ORIGINAL_NET_AMOUNT)
 WHERE CHECK_SERIAL_NUMBER ='0873216295';
--1 Row(s) Updated


SELECT * FROM STORE_DRAFTS WHERE CHECK_SERIAL_NUMBER ='0873216311';
--1 Row(s) SELECTed
UPDATE STORE_DRAFTS 
   SET PAID_DATE = '31-OCT-18',
       PAY_INDICATOR = 'Y',
       BANK_PAID_AMOUNT = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT),
       GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT),
       NET_AMOUNT   = NVL(NET_AMOUNT,ORIGINAL_NET_AMOUNT)
 WHERE CHECK_SERIAL_NUMBER ='0873216311';
--1 Row(s) Updated


SELECT * FROM STORE_DRAFTS WHERE CHECK_SERIAL_NUMBER ='0873216329';
--1 Row(s) SELECTed
UPDATE STORE_DRAFTS 
   SET PAID_DATE = '31-OCT-18',
       PAY_INDICATOR = 'Y',
       BANK_PAID_AMOUNT = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT),
       GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT),
       NET_AMOUNT   = NVL(NET_AMOUNT,ORIGINAL_NET_AMOUNT)
 WHERE CHECK_SERIAL_NUMBER ='0873216329';
--1 Row(s) Updated


SELECT * FROM STORE_DRAFTS WHERE CHECK_SERIAL_NUMBER ='076873216337';
--1 Row(s) SELECTed
UPDATE STORE_DRAFTS 
   SET PAID_DATE = '31-OCT-18',
       PAY_INDICATOR = 'Y',
       BANK_PAID_AMOUNT = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT),
       GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT),
       NET_AMOUNT   = NVL(NET_AMOUNT,ORIGINAL_NET_AMOUNT)
 WHERE CHECK_SERIAL_NUMBER ='076873216337';
--1 Row(s) Updated


SELECT * FROM STORE_DRAFTS WHERE CHECK_SERIAL_NUMBER ='0873216345';
--1 Row(s) SELECTed
UPDATE STORE_DRAFTS 
   SET PAID_DATE = '31-OCT-18',
       PAY_INDICATOR = 'Y',
       BANK_PAID_AMOUNT = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT),
       GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT),
       NET_AMOUNT   = NVL(NET_AMOUNT,ORIGINAL_NET_AMOUNT)
 WHERE CHECK_SERIAL_NUMBER ='0873216345';
--1 Row(s) Updated


SELECT * FROM STORE_DRAFTS WHERE CHECK_SERIAL_NUMBER ='0873216352';
--1 Row(s) SELECTed
UPDATE STORE_DRAFTS 
   SET PAID_DATE = '31-OCT-18',
       PAY_INDICATOR = 'Y',
       BANK_PAID_AMOUNT = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT),
       GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT),
       NET_AMOUNT   = NVL(NET_AMOUNT,ORIGINAL_NET_AMOUNT)
 WHERE CHECK_SERIAL_NUMBER ='0873216352';
--1 Row(s) Updated


SELECT * FROM STORE_DRAFTS WHERE CHECK_SERIAL_NUMBER ='0873216386';
--1 Row(s) SELECTed
UPDATE STORE_DRAFTS 
   SET PAID_DATE = '31-OCT-18',
       PAY_INDICATOR = 'Y',
       BANK_PAID_AMOUNT = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT),
       GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT),
       NET_AMOUNT   = NVL(NET_AMOUNT,ORIGINAL_NET_AMOUNT)
 WHERE CHECK_SERIAL_NUMBER ='0873216386';
--1 Row(s) Updated


SELECT * FROM STORE_DRAFTS WHERE CHECK_SERIAL_NUMBER ='0873216394';
--1 Row(s) SELECTed
UPDATE STORE_DRAFTS 
   SET PAID_DATE = '31-OCT-18',
       PAY_INDICATOR = 'Y',
       BANK_PAID_AMOUNT = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT),
       GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT),
       NET_AMOUNT   = NVL(NET_AMOUNT,ORIGINAL_NET_AMOUNT)
 WHERE CHECK_SERIAL_NUMBER ='0873216394';
--1 Row(s) Updated


SELECT * FROM STORE_DRAFTS WHERE CHECK_SERIAL_NUMBER ='0873216402';
--1 Row(s) SELECTed
UPDATE STORE_DRAFTS 
   SET PAID_DATE = '31-OCT-18',
       PAY_INDICATOR = 'Y',
       BANK_PAID_AMOUNT = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT),
       GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT),
       NET_AMOUNT   = NVL(NET_AMOUNT,ORIGINAL_NET_AMOUNT)
 WHERE CHECK_SERIAL_NUMBER ='0873216402';
--1 Row(s) Updated

COMMIT;