/*---------------------------------------
Below script will manually mark the drafts as paid as per email sent by Marissa Papas

Store	Draft	Paid Date
702119	1672-1	9/30/2018  - reverse Stop Payment and Mark as paid.  
705494	1600-6	8/5/2018   - Mark AS Paid.  
705259	1476-8	7/15/2018  - Mark AS Paid.  
702374	2233-2	7/12/2018  - Mark AS Paid.  
708577	1069-3	8/4/2018   - Mark AS Paid.  
708126	1755-3	8/15/2018  - Mark AS Paid.  
701342	1280-2	8/10/2018  - Mark AS Paid.  
702413	1236-2	7/8/2018   - reverse Stop Payment and Mark as paid.  
707217	1511-8	8/14/2018  - reverse Stop Payment and Mark as paid.  
702250	1668-2	8/19/2018  - Mark AS Paid.  
703546	1018-0	8/17/2018  - Mark AS Paid.  
701079	2450-8	7/10/2018  - Mark AS Paid.  
704332	2220-5	8/28/2018  - Mark AS Paid.  
703721	8772-4	8/11/2018  - Mark AS Paid.  
705248	4659-9	9/9/2018   - Mark AS Paid.  
702273	7314-9	8/27/2018  - Mark AS Paid.  
705191	9400-5	8/15/2018  - Mark AS Paid.  
701121	3912-6	8/15/2018  - Mark AS Paid.  
702456	7741-4	6/30/2018  - reverse void and Mark as paid. 

Created: 10/29/2018 kxm302
------------------------------------------*/
SELECT * FROM STORE_DRAFTS WHERE COST_CENTER_CODE = '702119' AND CHECK_SERIAL_NUMBER = '0211916721';
UPDATE STORE_DRAFTS 
   SET PAID_DATE = '30-SEP-2018',
       PAY_INDICATOR = 'Y',
       STOP_INDICATOR = 'N',
       OPEN_INDICATOR = 'Y',
       STOP_PAY_MARKED_BY_CCN_IND = NULL,
       BANK_PAID_AMOUNT = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT), 
       GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT), 
       NET_AMOUNT = NVL(NET_AMOUNT, ORIGINAL_NET_AMOUNT),
       STOP_PAY_DATE = NULL
 WHERE COST_CENTER_CODE = '702119' 
   AND CHECK_SERIAL_NUMBER = '0211916721';
 
SELECT * FROM UNATTACHED_MNL_DRFT_DTL WHERE CHECK_SERIAL_NUMBER = '0549416006';
--1 Row(s) SELECTed
UPDATE UNATTACHED_MNL_DRFT_DTL
   SET PAY_INDICATOR = 'Y', 
       PAID_DATE = '5-AUG-2018', 
       BANK_PAID_AMOUNT = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT),
       GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT),
       NET_AMOUNT   = NVL(NET_AMOUNT,ORIGINAL_NET_AMOUNT)
 WHERE CHECK_SERIAL_NUMBER = '0549416006';
 --1 Row(s) Updated

SELECT * FROM STORE_DRAFTS WHERE CHECK_SERIAL_NUMBER = '0525914768';
--1 Row(s) SELECTed
UPDATE STORE_DRAFTS
   SET PAY_INDICATOR = 'Y', 
       PAID_DATE = '15-JUL-2018', 
       BANK_PAID_AMOUNT = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT),
       GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT),
       NET_AMOUNT   = NVL(NET_AMOUNT,ORIGINAL_NET_AMOUNT)
 WHERE CHECK_SERIAL_NUMBER = '0525914768';
 --1 Row(s) Updated 
 
SELECT * FROM UNATTACHED_MNL_DRFT_DTL WHERE CHECK_SERIAL_NUMBER = '0237422332';
--1 Row(s) SELECTed
UPDATE UNATTACHED_MNL_DRFT_DTL
   SET PAY_INDICATOR = 'Y', 
       PAID_DATE = '12-JUL-2018', 
       BANK_PAID_AMOUNT = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT),
       GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT),
       NET_AMOUNT   = NVL(NET_AMOUNT,ORIGINAL_NET_AMOUNT)
 WHERE CHECK_SERIAL_NUMBER = '0237422332';
 --1 Row(s) Updated
 
SELECT * FROM STORE_DRAFTS WHERE CHECK_SERIAL_NUMBER = '0857710693';
--1 Row(s) SELECTed
UPDATE STORE_DRAFTS
   SET PAY_INDICATOR = 'Y', 
       PAID_DATE = '4-AUG-2018', 
       BANK_PAID_AMOUNT = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT),
       GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT),
       NET_AMOUNT   = NVL(NET_AMOUNT,ORIGINAL_NET_AMOUNT)
 WHERE CHECK_SERIAL_NUMBER = '0857710693';
 --1 Row(s) Updated

--change amount as per Mary

SELECT * FROM STORE_DRAFTS WHERE CHECK_SERIAL_NUMBER = '0812617553';
--1 Row(s) SELECTed
UPDATE STORE_DRAFTS 
   SET PAID_DATE = '15-AUG-2018', 
       PAY_INDICATOR = 'Y',
       NET_AMOUNT = 200.10,
       BANK_PAID_AMOUNT = 200.10,
       GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT)
 WHERE CHECK_SERIAL_NUMBER = '0812617553';
 --1 Row(s) Updated  
 
SELECT * FROM UNATTACHED_MNL_DRFT_DTL WHERE CHECK_SERIAL_NUMBER = '0134212802';
--1 Row(s) SELECTed
UPDATE UNATTACHED_MNL_DRFT_DTL
   SET PAY_INDICATOR = 'Y', 
       PAID_DATE = '10-AUG-2018', 
       BANK_PAID_AMOUNT = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT),
       GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT),
       NET_AMOUNT   = NVL(NET_AMOUNT,ORIGINAL_NET_AMOUNT)
 WHERE CHECK_SERIAL_NUMBER = '0134212802';
 --1 Row(s) Updated
 
-- reverse Stop Payment and Mark as paid.

SELECT * FROM STORE_DRAFTS WHERE COST_CENTER_CODE = '702413' AND CHECK_SERIAL_NUMBER = '0241312362';
UPDATE STORE_DRAFTS 
   SET PAID_DATE = '08-JUL-2018',
       PAY_INDICATOR = 'Y',
       STOP_INDICATOR = 'N',
       OPEN_INDICATOR = 'Y',
       STOP_PAY_MARKED_BY_CCN_IND = NULL,
       BANK_PAID_AMOUNT = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT), 
       GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT), 
       NET_AMOUNT = NVL(NET_AMOUNT, ORIGINAL_NET_AMOUNT),
       STOP_PAY_DATE = NULL
 WHERE COST_CENTER_CODE = '702413' 
   AND CHECK_SERIAL_NUMBER = '0241312362';

-- reverse Stop Payment and Mark as paid.

SELECT * FROM STORE_DRAFTS WHERE COST_CENTER_CODE = '707217' AND CHECK_SERIAL_NUMBER = '0721715118';
UPDATE STORE_DRAFTS 
   SET PAID_DATE = '14-AUG-2018',
       PAY_INDICATOR = 'Y',
       STOP_INDICATOR = 'N',
       OPEN_INDICATOR = 'Y',
       STOP_PAY_MARKED_BY_CCN_IND = NULL,
       BANK_PAID_AMOUNT = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT), 
       GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT), 
       NET_AMOUNT = NVL(NET_AMOUNT, ORIGINAL_NET_AMOUNT),
       STOP_PAY_DATE = NULL
 WHERE COST_CENTER_CODE = '707217' 
   AND CHECK_SERIAL_NUMBER = '0721715118'; 
 
--change amount as per Mary

SELECT * FROM STORE_DRAFTS WHERE CHECK_SERIAL_NUMBER = '0225016682';
--1 Row(s) SELECTed
UPDATE STORE_DRAFTS 
   SET PAID_DATE = '19-AUG-2018', 
       PAY_INDICATOR = 'Y',
       NET_AMOUNT = 400,
       BANK_PAID_AMOUNT = 400,
       GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT)
 WHERE CHECK_SERIAL_NUMBER = '0225016682';
 --1 Row(s) Updated
 
SELECT * FROM UNATTACHED_MNL_DRFT_DTL WHERE CHECK_SERIAL_NUMBER = '0354610180';
--1 Row(s) SELECTed
UPDATE UNATTACHED_MNL_DRFT_DTL
   SET PAY_INDICATOR = 'Y', 
       PAID_DATE = '17-AUG-2018', 
       BANK_PAID_AMOUNT = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT),
       GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT),
       NET_AMOUNT   = NVL(NET_AMOUNT,ORIGINAL_NET_AMOUNT)
 WHERE CHECK_SERIAL_NUMBER = '0354610180';
 --1 Row(s) Updated

SELECT * FROM UNATTACHED_MNL_DRFT_DTL WHERE CHECK_SERIAL_NUMBER = '0107924508';
--1 Row(s) SELECTed
UPDATE UNATTACHED_MNL_DRFT_DTL
   SET PAY_INDICATOR = 'Y', 
       PAID_DATE = '10-JUL-2018', 
       BANK_PAID_AMOUNT = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT),
       GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT),
       NET_AMOUNT   = NVL(NET_AMOUNT,ORIGINAL_NET_AMOUNT)
 WHERE CHECK_SERIAL_NUMBER = '0107924508';
 --1 Row(s) Updated 

--change amount as per Mary
 
SELECT * FROM STORE_DRAFTS WHERE CHECK_SERIAL_NUMBER = '0433222205';
--1 Row(s) SELECTed
UPDATE STORE_DRAFTS 
   SET PAID_DATE = '28-AUG-2018', 
       PAY_INDICATOR = 'Y',
       NET_AMOUNT = 829.57,
       BANK_PAID_AMOUNT = 829.57,
       GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT)
 WHERE CHECK_SERIAL_NUMBER = '0433222205';
 --1 Row(s) Updated
 
SELECT * FROM STORE_DRAFTS WHERE CHECK_SERIAL_NUMBER = '0372187724';
--1 Row(s) SELECTed
UPDATE STORE_DRAFTS
   SET PAY_INDICATOR = 'Y', 
       PAID_DATE = '11-AUG-2018', 
       BANK_PAID_AMOUNT = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT),
       GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT),
       NET_AMOUNT   = NVL(NET_AMOUNT,ORIGINAL_NET_AMOUNT)
 WHERE CHECK_SERIAL_NUMBER = '0372187724';
 --1 Row(s) Updated

SELECT * FROM STORE_DRAFTS WHERE CHECK_SERIAL_NUMBER = '0524846599';
--1 Row(s) SELECTed
UPDATE STORE_DRAFTS
   SET PAY_INDICATOR = 'Y', 
       PAID_DATE = '9-SEP-2018', 
       BANK_PAID_AMOUNT = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT),
       GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT),
       NET_AMOUNT   = NVL(NET_AMOUNT,ORIGINAL_NET_AMOUNT)
 WHERE CHECK_SERIAL_NUMBER = '0524846599';
 --1 Row(s) Updated 
 
SELECT * FROM STORE_DRAFTS WHERE CHECK_SERIAL_NUMBER = '0227373149';
--1 Row(s) SELECTed
UPDATE STORE_DRAFTS
   SET PAY_INDICATOR = 'Y', 
       PAID_DATE = '27-AUG-2018', 
       BANK_PAID_AMOUNT = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT),
       GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT),
       NET_AMOUNT   = NVL(NET_AMOUNT,ORIGINAL_NET_AMOUNT)
 WHERE CHECK_SERIAL_NUMBER = '0227373149';
 --1 Row(s) Updated 

--change amount as per Mary
 
SELECT * FROM STORE_DRAFTS WHERE CHECK_SERIAL_NUMBER = '0519194005';
--1 Row(s) SELECTed
UPDATE STORE_DRAFTS 
   SET PAID_DATE = '15-AUG-2018', 
       PAY_INDICATOR = 'Y',
       NET_AMOUNT = 3568.5,
       BANK_PAID_AMOUNT = 3568.5,
       GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT)
 WHERE CHECK_SERIAL_NUMBER = '0519194005';
 --1 Row(s) Updated
 
SELECT * FROM STORE_DRAFTS WHERE CHECK_SERIAL_NUMBER = '0112139126';
--1 Row(s) SELECTed
UPDATE STORE_DRAFTS
   SET PAY_INDICATOR = 'Y', 
       PAID_DATE = '15-AUG-2018', 
       BANK_PAID_AMOUNT = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT),
       GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT),
       NET_AMOUNT   = NVL(NET_AMOUNT,ORIGINAL_NET_AMOUNT)
 WHERE CHECK_SERIAL_NUMBER = '0112139126';
 --1 Row(s) Updated

--Reverse void payment
 
 
SELECT * FROM STORE_DRAFTS WHERE COST_CENTER_CODE = '702456' AND CHECK_SERIAL_NUMBER = '0245677414';
--1 Row(s) SELECTed
  UPDATE STORE_DRAFTS 
   SET PAID_DATE = '18-JUL-2018',
       PAY_INDICATOR = 'Y',
       OPEN_INDICATOR = 'Y',
       VOID_INDICATOR = 'N',
       VOID_DATE      = NULL,
       VOID_MARKED_BY_CCN = NULL,
       BANK_PAID_AMOUNT = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT),
       GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT), 
       NET_AMOUNT = NVL(NET_AMOUNT, ORIGINAL_NET_AMOUNT)
 WHERE COST_CENTER_CODE = '702456'
   AND CHECK_SERIAL_NUMBER = '0245677414';
 --1 Row(s) Updated 
 
 
COMMIT;