SELECT * FROM STORE_DRAFTS WHERE COST_CENTER_CODE = '708506' AND CHECK_SERIAL_NUMBER = '0850613928';

UPDATE STORE_DRAFTS    
   SET PAID_DATE = '15-DEC-2017',
       PAY_INDICATOR = 'Y',
       BANK_PAID_AMOUNT = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT),
       GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT),
       NET_AMOUNT = NVL(NET_AMOUNT, ORIGINAL_NET_AMOUNT)
 WHERE COST_CENTER_CODE = '708506'
   AND CHECK_SERIAL_NUMBER = '0850613928';
   
SELECT * FROM STORE_DRAFTS WHERE COST_CENTER_CODE = '705239' AND CHECK_SERIAL_NUMBER = '0523972677';

UPDATE STORE_DRAFTS    
   SET PAID_DATE = '10-JAN-2018',
       PAY_INDICATOR = 'Y',
       BANK_PAID_AMOUNT = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT),
       GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT),
       NET_AMOUNT = NVL(NET_AMOUNT, ORIGINAL_NET_AMOUNT)
 WHERE COST_CENTER_CODE = '705239'
   AND CHECK_SERIAL_NUMBER = '0523972677';
   
SELECT * FROM STORE_DRAFTS WHERE COST_CENTER_CODE = '703171' AND CHECK_SERIAL_NUMBER = '0317145092';

UPDATE STORE_DRAFTS    
   SET PAID_DATE = '05-JAN-2018',
       PAY_INDICATOR = 'Y',
       BANK_PAID_AMOUNT = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT),
       GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT),
       NET_AMOUNT = NVL(NET_AMOUNT, ORIGINAL_NET_AMOUNT)
 WHERE COST_CENTER_CODE = '703171'
   AND CHECK_SERIAL_NUMBER = '0317145092';
   
SELECT * FROM STORE_DRAFTS WHERE COST_CENTER_CODE = '702845' AND CHECK_SERIAL_NUMBER = '0284566429';

UPDATE STORE_DRAFTS    
   SET PAID_DATE = '21-DEC-2017',
       PAY_INDICATOR = 'Y',
       BANK_PAID_AMOUNT = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT),
       GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT),
       NET_AMOUNT = NVL(NET_AMOUNT, ORIGINAL_NET_AMOUNT)
 WHERE COST_CENTER_CODE = '702845'
   AND CHECK_SERIAL_NUMBER = '0284566429';
   
   
SELECT * FROM STORE_DRAFTS WHERE COST_CENTER_CODE = '702845' AND CHECK_SERIAL_NUMBER = '0284566460';

UPDATE STORE_DRAFTS    
   SET PAID_DATE = '21-DEC-2017',
       PAY_INDICATOR = 'Y',
       BANK_PAID_AMOUNT = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT),
       GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT),
       NET_AMOUNT = NVL(NET_AMOUNT, ORIGINAL_NET_AMOUNT)
 WHERE COST_CENTER_CODE = '702845'
   AND CHECK_SERIAL_NUMBER = '0284566460';
   
SELECT * FROM STORE_DRAFTS WHERE COST_CENTER_CODE = '702845' AND CHECK_SERIAL_NUMBER = '0284566486';

UPDATE STORE_DRAFTS    
   SET PAID_DATE = '21-DEC-2017',
       PAY_INDICATOR = 'Y',
       BANK_PAID_AMOUNT = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT),
       GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT),
       NET_AMOUNT = NVL(NET_AMOUNT, ORIGINAL_NET_AMOUNT)
 WHERE COST_CENTER_CODE = '702845'
   AND CHECK_SERIAL_NUMBER = '0284566486';
   
SELECT * FROM STORE_DRAFTS WHERE COST_CENTER_CODE = '702233' AND CHECK_SERIAL_NUMBER = '0223350166';

UPDATE STORE_DRAFTS    
   SET PAID_DATE = '02-DEC-2017',
       PAY_INDICATOR = 'Y',
       BANK_PAID_AMOUNT = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT),
       GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT),
       NET_AMOUNT = NVL(NET_AMOUNT, ORIGINAL_NET_AMOUNT)
 WHERE COST_CENTER_CODE = '702233'
   AND CHECK_SERIAL_NUMBER = '0223350166';
   
SELECT * FROM STORE_DRAFTS WHERE COST_CENTER_CODE = '702335' AND CHECK_SERIAL_NUMBER = '0233563808';

UPDATE STORE_DRAFTS    
   SET PAID_DATE = '05-JAN-2018',
       PAY_INDICATOR = 'Y',
       BANK_PAID_AMOUNT = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT),
       GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT),
       NET_AMOUNT = NVL(NET_AMOUNT, ORIGINAL_NET_AMOUNT)
 WHERE COST_CENTER_CODE = '702335'
   AND CHECK_SERIAL_NUMBER = '0233563808';
   
SELECT * FROM STORE_DRAFTS WHERE COST_CENTER_CODE = '701222' AND CHECK_SERIAL_NUMBER = '0122211535';

UPDATE STORE_DRAFTS    
   SET PAID_DATE = '10-JAN-2018',
       PAY_INDICATOR = 'Y',
       BANK_PAID_AMOUNT = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT),
       GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT),
       NET_AMOUNT = NVL(NET_AMOUNT, ORIGINAL_NET_AMOUNT)
 WHERE COST_CENTER_CODE = '701222'
   AND CHECK_SERIAL_NUMBER = '0122211535';
   
   
SELECT * FROM STORE_DRAFTS WHERE COST_CENTER_CODE = '701648' AND CHECK_SERIAL_NUMBER = '0164815565';

UPDATE STORE_DRAFTS    
   SET PAID_DATE = '02-DEC-2017',
       PAY_INDICATOR = 'Y',
       BANK_PAID_AMOUNT = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT),
       GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT),
       NET_AMOUNT = NVL(NET_AMOUNT, ORIGINAL_NET_AMOUNT)
 WHERE COST_CENTER_CODE = '701648'
   AND CHECK_SERIAL_NUMBER = '0164815565';
   
SELECT * FROM STORE_DRAFTS WHERE COST_CENTER_CODE = '701911' AND CHECK_SERIAL_NUMBER = '0191122647';

UPDATE STORE_DRAFTS    
   SET PAID_DATE = '09-JAN-2018',
       PAY_INDICATOR = 'Y',
       BANK_PAID_AMOUNT = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT),
       GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT),
       NET_AMOUNT = NVL(NET_AMOUNT, ORIGINAL_NET_AMOUNT)
 WHERE COST_CENTER_CODE = '701911'
   AND CHECK_SERIAL_NUMBER = '0191122647';
   
SELECT * FROM STORE_DRAFTS WHERE COST_CENTER_CODE = '707385' AND CHECK_SERIAL_NUMBER = '0738531920';

UPDATE STORE_DRAFTS    
   SET PAID_DATE = '11-JAN-2018',
       PAY_INDICATOR = 'Y',
       BANK_PAID_AMOUNT = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT),
       GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT),
       NET_AMOUNT = NVL(NET_AMOUNT, ORIGINAL_NET_AMOUNT)
 WHERE COST_CENTER_CODE = '707385'
   AND CHECK_SERIAL_NUMBER = '0738531920';
   
SELECT * FROM STORE_DRAFTS WHERE COST_CENTER_CODE = '707704' AND CHECK_SERIAL_NUMBER = '0770438463';

UPDATE STORE_DRAFTS    
   SET PAID_DATE = '09-JAN-2018',
       PAY_INDICATOR = 'Y',
       BANK_PAID_AMOUNT = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT),
       GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT),
       NET_AMOUNT = NVL(NET_AMOUNT, ORIGINAL_NET_AMOUNT)
 WHERE COST_CENTER_CODE = '707704'
   AND CHECK_SERIAL_NUMBER = '0770438463';
   
SELECT * FROM STORE_DRAFTS WHERE COST_CENTER_CODE = '707588' AND CHECK_SERIAL_NUMBER = '0758864375';

UPDATE STORE_DRAFTS    
   SET PAID_DATE = '10-JAN-2018',
       PAY_INDICATOR = 'Y',
       BANK_PAID_AMOUNT = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT),
       GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT),
       NET_AMOUNT = NVL(NET_AMOUNT, ORIGINAL_NET_AMOUNT)
 WHERE COST_CENTER_CODE = '707588'
   AND CHECK_SERIAL_NUMBER = '0758864375';
   
   
SELECT * FROM STORE_DRAFTS WHERE COST_CENTER_CODE = '708570' AND CHECK_SERIAL_NUMBER = '0857037402';

UPDATE STORE_DRAFTS    
   SET PAID_DATE = '11-JAN-2018',
       PAY_INDICATOR = 'Y',
       BANK_PAID_AMOUNT = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT),
       GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT),
       NET_AMOUNT = NVL(NET_AMOUNT, ORIGINAL_NET_AMOUNT)
 WHERE COST_CENTER_CODE = '708570'
   AND CHECK_SERIAL_NUMBER = '0857037402';
   
SELECT * FROM STORE_DRAFTS WHERE COST_CENTER_CODE = '701214' AND CHECK_SERIAL_NUMBER = '0121454565';

UPDATE STORE_DRAFTS    
   SET PAID_DATE = '11-JAN-2018',
       PAY_INDICATOR = 'Y',
       BANK_PAID_AMOUNT = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT),
       GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT),
       NET_AMOUNT = NVL(NET_AMOUNT, ORIGINAL_NET_AMOUNT)
 WHERE COST_CENTER_CODE = '701214'
   AND CHECK_SERIAL_NUMBER = '0121454565';
   
SELECT * FROM STORE_DRAFTS WHERE COST_CENTER_CODE = '701214' AND CHECK_SERIAL_NUMBER = '0121454664';

UPDATE STORE_DRAFTS    
   SET PAID_DATE = '10-JAN-2018',
       PAY_INDICATOR = 'Y',
       BANK_PAID_AMOUNT = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT),
       GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT),
       NET_AMOUNT = NVL(NET_AMOUNT, ORIGINAL_NET_AMOUNT)
 WHERE COST_CENTER_CODE = '701214'
   AND CHECK_SERIAL_NUMBER = '0121454664';
   
SELECT * FROM STORE_DRAFTS WHERE COST_CENTER_CODE = '705338' AND CHECK_SERIAL_NUMBER = '0533845368';

UPDATE STORE_DRAFTS    
   SET PAID_DATE = '19-JAN-2018',
       PAY_INDICATOR = 'Y',
       BANK_PAID_AMOUNT = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT),
       GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT),
       NET_AMOUNT = NVL(NET_AMOUNT, ORIGINAL_NET_AMOUNT)
 WHERE COST_CENTER_CODE = '705338'
   AND CHECK_SERIAL_NUMBER = '0533845368';
   
SELECT * FROM STORE_DRAFTS WHERE COST_CENTER_CODE = '705336' AND CHECK_SERIAL_NUMBER = '0533687570';

UPDATE STORE_DRAFTS    
   SET PAID_DATE = '19-JAN-2018',
       PAY_INDICATOR = 'Y',
       BANK_PAID_AMOUNT = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT),
       GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT),
       NET_AMOUNT = NVL(NET_AMOUNT, ORIGINAL_NET_AMOUNT)
 WHERE COST_CENTER_CODE = '705336'
   AND CHECK_SERIAL_NUMBER = '0533687570';
   
   
SELECT * FROM STORE_DRAFTS WHERE COST_CENTER_CODE = '702263' AND CHECK_SERIAL_NUMBER = '0226383206';

UPDATE STORE_DRAFTS    
   SET PAID_DATE = '10-JAN-2018',
       PAY_INDICATOR = 'Y',
       BANK_PAID_AMOUNT = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT),
       GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT),
       NET_AMOUNT = NVL(NET_AMOUNT, ORIGINAL_NET_AMOUNT)
 WHERE COST_CENTER_CODE = '702263'
   AND CHECK_SERIAL_NUMBER = '0226383206';
   
SELECT * FROM STORE_DRAFTS WHERE COST_CENTER_CODE = '707465' AND CHECK_SERIAL_NUMBER = '0746575042';

UPDATE STORE_DRAFTS    
   SET PAID_DATE = '19-JAN-2018',
       PAY_INDICATOR = 'Y',
       BANK_PAID_AMOUNT = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT),
       GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT),
       NET_AMOUNT = NVL(NET_AMOUNT, ORIGINAL_NET_AMOUNT)
 WHERE COST_CENTER_CODE = '707465'
   AND CHECK_SERIAL_NUMBER = '0746575042';
   
SELECT * FROM STORE_DRAFTS WHERE COST_CENTER_CODE = '702595' AND CHECK_SERIAL_NUMBER = '0259510055';

UPDATE STORE_DRAFTS    
   SET PAID_DATE = '11-JAN-2018',
       PAY_INDICATOR = 'Y',
       BANK_PAID_AMOUNT = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT),
       GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT),
       NET_AMOUNT = NVL(NET_AMOUNT, ORIGINAL_NET_AMOUNT)
 WHERE COST_CENTER_CODE = '702595'
   AND CHECK_SERIAL_NUMBER = '0259510055';
   
SELECT * FROM STORE_DRAFTS WHERE COST_CENTER_CODE = '707706' AND CHECK_SERIAL_NUMBER = '0770618015';

UPDATE STORE_DRAFTS    
   SET PAID_DATE = '05-JAN-2018',
       PAY_INDICATOR = 'Y',
       BANK_PAID_AMOUNT = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT),
       GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT),
       NET_AMOUNT = NVL(NET_AMOUNT, ORIGINAL_NET_AMOUNT)
 WHERE COST_CENTER_CODE = '707706'
   AND CHECK_SERIAL_NUMBER = '0770618015';
   
SELECT * FROM STORE_DRAFTS WHERE COST_CENTER_CODE = '708665' AND CHECK_SERIAL_NUMBER = '0866510316';

UPDATE STORE_DRAFTS    
   SET PAID_DATE = '22-JAN-2018',
       PAY_INDICATOR = 'Y',
       BANK_PAID_AMOUNT = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT),
       GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT),
       NET_AMOUNT = NVL(NET_AMOUNT, ORIGINAL_NET_AMOUNT)
 WHERE COST_CENTER_CODE = '708665'
   AND CHECK_SERIAL_NUMBER = '0866510316';
   
   
SELECT * FROM STORE_DRAFTS WHERE COST_CENTER_CODE = '701691' AND CHECK_SERIAL_NUMBER = '0169115847';

UPDATE STORE_DRAFTS    
   SET PAID_DATE = '19-JAN-2018',
       PAY_INDICATOR = 'Y',
       BANK_PAID_AMOUNT = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT),
       GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT),
       NET_AMOUNT = NVL(NET_AMOUNT, ORIGINAL_NET_AMOUNT)
 WHERE COST_CENTER_CODE = '701691'
   AND CHECK_SERIAL_NUMBER = '0169115847';
   
COMMIT;