/*
Store Drafts paids update request from Jeremy

Created : 10/2/2019 jxc517 CCN Project Team....
Changed : 
*/
SELECT * FROM STORE_DRAFTS WHERE CHECK_SERIAL_NUMBER IN ('0195928304','0532593837','0749710075','0852410067','0223628892','0132718495','0349219618') ORDER BY 1;

UPDATE STORE_DRAFTS
   SET PAID_DATE                  = '28-AUG-2019',
       PAY_INDICATOR              = 'Y',
       BANK_PAID_AMOUNT           = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT), 
       GROSS_AMOUNT               = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT), 
       NET_AMOUNT                 = NVL(NET_AMOUNT, ORIGINAL_NET_AMOUNT),
       VOID_INDICATOR             = 'N',
       VOID_DATE                  = NULL,
       OPEN_INDICATOR             = 'Y'
 WHERE CHECK_SERIAL_NUMBER = '0132718495'; --Voided -> 8/28/19 = $1086.50

UPDATE STORE_DRAFTS
   SET PAID_DATE                  = '30-SEP-2019',
       PAY_INDICATOR              = 'Y',
       BANK_PAID_AMOUNT           = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT), 
       GROSS_AMOUNT               = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT), 
       NET_AMOUNT                 = NVL(NET_AMOUNT, ORIGINAL_NET_AMOUNT),
       STOP_INDICATOR             = 'N',
       STOP_PAY_DATE              = NULL,
       STOP_PAY_MARKED_BY_CCN_IND = NULL,
       OPEN_INDICATOR             = 'Y'
 WHERE CHECK_SERIAL_NUMBER = '0195928304'; --Stopped -> 9/30/19 = $100

UPDATE STORE_DRAFTS
   SET PAID_DATE                  = '30-SEP-2019',
       PAY_INDICATOR              = 'Y',
       BANK_PAID_AMOUNT           = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT), 
       GROSS_AMOUNT               = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT), 
       NET_AMOUNT                 = NVL(NET_AMOUNT, ORIGINAL_NET_AMOUNT),
       STOP_INDICATOR             = 'N',
       STOP_PAY_DATE              = NULL,
       STOP_PAY_MARKED_BY_CCN_IND = NULL,
       OPEN_INDICATOR             = 'Y'
 WHERE CHECK_SERIAL_NUMBER = '0223628892'; --Stopped -> 9/30/19 = $2556.74

UPDATE STORE_DRAFTS
   SET PAID_DATE                  = '20-AUG-2019',
       PAY_INDICATOR              = 'Y',
       BANK_PAID_AMOUNT           = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT), 
       GROSS_AMOUNT               = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT), 
       NET_AMOUNT                 = NVL(NET_AMOUNT, ORIGINAL_NET_AMOUNT),
       VOID_INDICATOR             = 'N',
       VOID_DATE                  = NULL,
       OPEN_INDICATOR             = 'Y'
 WHERE CHECK_SERIAL_NUMBER = '0349219618'; --Voided -> 8/20/19 = $2721.26

UPDATE STORE_DRAFTS
   SET PAID_DATE                  = '30-SEP-2019',
       PAY_INDICATOR              = 'Y',
       BANK_PAID_AMOUNT           = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT), 
       GROSS_AMOUNT               = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT), 
       NET_AMOUNT                 = NVL(NET_AMOUNT, ORIGINAL_NET_AMOUNT),
       STOP_INDICATOR             = 'N',
       STOP_PAY_DATE              = NULL,
       STOP_PAY_MARKED_BY_CCN_IND = NULL,
       OPEN_INDICATOR             = 'Y'
 WHERE CHECK_SERIAL_NUMBER = '0532593837'; --Stopped -> 9/30/19 = $175

UPDATE STORE_DRAFTS
   SET PAID_DATE                  = '30-SEP-2019',
       PAY_INDICATOR              = 'Y',
       BANK_PAID_AMOUNT           = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT), 
       GROSS_AMOUNT               = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT), 
       NET_AMOUNT                 = NVL(NET_AMOUNT, ORIGINAL_NET_AMOUNT),
       STOP_INDICATOR             = 'N',
       STOP_PAY_DATE              = NULL,
       STOP_PAY_MARKED_BY_CCN_IND = NULL,
       OPEN_INDICATOR             = 'Y'
 WHERE CHECK_SERIAL_NUMBER = '0749710075'; --Stopped -> 9/30/19 = $400

--Jeremy confirmed to skip below draft as it is already paid
--UPDATE STORE_DRAFTS SET PAID_DATE = '30-SEP-2019' WHERE CHECK_SERIAL_NUMBER = '0852410067'; --Paid = 03-SEP-2019 -> 9/30/19 = $2000

SELECT * FROM STORE_DRAFTS WHERE CHECK_SERIAL_NUMBER IN ('0195928304','0532593837','0749710075','0852410067','0223628892','0132718495','0349219618') ORDER BY 1;

COMMIT;