/* BELOW SCRIPT WILL UPDATE THE STORE DRAFTS PAID DETAILS 
   AS REQUESTED BY KATIE M. PSCHESANG
   CREATED : 01/03/2018 NXK927 CCN PROJECT TEAM.... 
   
   Store #     Draft#      Paid Date        Amount 
   768826      10249       9/12/2017          $70.00 
   768936      10592       9/12/2017       $1,179.96

*/ 



SELECT * FROM STORE_DRAFTS WHERE CHECK_SERIAL_NUMBER = '0882610249'; 

UPDATE STORE_DRAFTS    
  SET PAID_DATE = '12-SEP-2017',
      BANK_PAID_AMOUNT = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT),
      GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT),
      NET_AMOUNT = NVL(NET_AMOUNT, ORIGINAL_NET_AMOUNT)
WHERE CHECK_SERIAL_NUMBER = '0882610249';


SELECT * FROM STORE_DRAFTS WHERE CHECK_SERIAL_NUMBER = '0893610592';

UPDATE STORE_DRAFTS    
  SET PAID_DATE = '12-SEP-2017',
      PAY_INDICATOR = 'Y',
      BANK_PAID_AMOUNT = DECODE(AMOUNT_CHANGE_DATE, NULL, ORIGINAL_NET_AMOUNT, NET_AMOUNT),
      GROSS_AMOUNT = NVL(GROSS_AMOUNT, ORIGINAL_NET_AMOUNT),
      NET_AMOUNT = NVL(NET_AMOUNT, ORIGINAL_NET_AMOUNT)
WHERE CHECK_SERIAL_NUMBER = '0893610592';

COMMIT;