#!/bin/sh
#################################################################
# Script name   : SRA30000_dailyRun_ftp.sh
#
# Description   : Use to ftp the SRA30000 file to stuar2hq.sw.sherwin.com server
#                 For the time being, this file is generated by Mainframe and CCN is just FTPing it.
#
# Created  : 10/17/2016 vxv336 CCN Project Team.....
# Modified : 03/27/2017 gxg192 Changes to capture ftp status correctly
#          : 06/16/2017 gxg192 Changes to add Time after ftp status check.
#
#################################################################
# below command will get the path for banking.config respective to the environment from which it is run from
. /app/banking/dev/banking.config

proc_name="SRA30000_dailyRun_ftp"
FTPLOG=$HOME/logs/SRA30000_dailyRun_ftplogfile.log
TIME=`date +"%H:%M:%S"`
DATE=`date +"%m/%d/%Y"`
YYMMDD=`date +"%y%m%d"`
echo "Processing Started for $proc_name at $TIME on $DATE"

############################################################################
# ftp the SRA30000
# files to stuar2hq.sw.sherwin.com server
############################################################################
ftp -inv ${uar_host} <<FTP_MF > $FTPLOG
quote user ${uar_user}
quote pass ${uar_pw}
cd "/reconnet/uardata/rt1/TEST INPUT"
put $HOME/initLoad/SRA30000_D$YYMMDD* uar_gift_card.pos
bye
END_SCRIPT
echo "bye the transfer is complete"
FTP_MF

############################################################################
#                           ERROR STATUS CHECK
############################################################################
./check_ftp_status.sh $FTPLOG
status=$?
if test $status -ne 0
then
   TIME=`date +"%H:%M:%S"`
   echo "The transfer of SRA30000_D$YYMMDD* to uar FAILED at ${TIME} on ${DATE}"
   exit 1;
fi
echo "Processing finished for $proc_name at ${TIME} on ${DATE}"

exit 0

