DROP TABLE MIGRATION_REPOS;
DROP TABLE MIGRATION_USERS;
DROP TABLE MIGRATION_APPROVAL;
DROP TABLE MIGRATION_DETAIL;
DROP TABLE MIGRATION_REVIEW;
DROP TABLE MIGRATION_HEADER;

CREATE TABLE MIGRATION_HEADER (
MIGRATION_ID                    INTEGER,
MIGRATION_NAME                  VARCHAR2(500),
PROJECT_NAME                    VARCHAR2(100),
SOURCE                          VARCHAR2(200),
DESTINATION                     VARCHAR2(200),
SERVER                          VARCHAR2(100),
MIGRATED_BY                     VARCHAR2(10), --updated during actual migration, not at request
MIGRATED_IND                    VARCHAR2(1), --updatable=Y/N
CONSTRAINT pk_migration_id PRIMARY KEY (MIGRATION_ID)
);

CREATE TABLE MIGRATION_DETAIL (
MIGRATION_ID       INTEGER,
COMPONENT_PATH     VARCHAR2(1000),
COMPONENT_NAME     VARCHAR2(50),
COMPONENT_DETAILS  VARCHAR2(100),
OPERATION          VARCHAR2(10), --updatable=ADD/REMOVE/UPDATE/DELETED
CONSTRAINT fk_dtl_mig_id FOREIGN KEY (MIGRATION_ID) REFERENCES MIGRATION_HEADER(MIGRATION_ID)
);

CREATE TABLE MIGRATION_APPROVAL (
MIGRATION_ID       INTEGER,
REQUESTOR_ID       VARCHAR2(10),
REQUESTED_ON_DT    DATE,
RQST_TO_MGRT_DT    DATE,
APPROVER_ID        VARCHAR2(10),
APPROVED_ON_DT     DATE, --updatable=SYSDATE
APPROVAL_STATUS    VARCHAR2(20), --updatable=PENDING APPROVAL/APPROVED/REJECTED
COMMENTS VARCHAR2(2000), --updatable
ACTV_IND VARCHAR2(1), --updatable=Y/N
CONSTRAINT fk_apprvl_mig_id FOREIGN KEY (MIGRATION_ID) REFERENCES MIGRATION_HEADER(MIGRATION_ID)
);

CREATE TABLE MIGRATION_USERS(
USER_ID VARCHAR2(10),
ROLE VARCHAR2(30),
CREATION_DATE DATE,
CREATED_BY VARCHAR2(10),
ACTV_IND VARCHAR2(1)
);

CREATE TABLE MIGRATION_REPOS(
NAME VARCHAR2(100),
TYPE VARCHAR2(30),
CREATION_DATE DATE,
CREATED_BY VARCHAR2(10),
ACTV_IND VARCHAR2(1)
);

CREATE TABLE MIGRATION_REVIEW (
MIGRATION_ID       INTEGER,
REQUESTOR_ID       VARCHAR2(10),
REQUESTED_ON_DT    DATE,
RQST_TO_MGRT_DT    DATE,
REVIEWER_ID        VARCHAR2(10),
REVIEWED_ON_DT     DATE, --updatable=SYSDATE
REVIEW_STATUS      VARCHAR2(20), --updatable=PENDING REVIEW/APPROVED/REJECTED
COMMENTS VARCHAR2(2000), --updatable
ACTV_IND VARCHAR2(1), --updatable=Y/N
CONSTRAINT fk_review_mig_id FOREIGN KEY (MIGRATION_ID) REFERENCES MIGRATION_HEADER(MIGRATION_ID)
);
